--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\usa13509.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 21101041
New Best Solution Fitness: 21093320
New Best Solution Fitness: 21091523
Generation: 3
New Best Solution Fitness: 20620113
New Best Solution Fitness: 20619712
New Best Solution Fitness: 20619289
New Best Solution Fitness: 20619230
New Best Solution Fitness: 20616152
Generation: 4
New Best Solution Fitness: 20564178
New Best Solution Fitness: 20564033
New Best Solution Fitness: 20563300
New Best Solution Fitness: 20562810
Generation: 5
New Best Solution Fitness: 20540410
New Best Solution Fitness: 20537525
Generation: 6
New Best Solution Fitness: 20529161
New Best Solution Fitness: 20528768
Generation: 7
Generation: 8
New Best Solution Fitness: 20525155
Generation: 9
New Best Solution Fitness: 20524572
New Best Solution Fitness: 20524545
New Best Solution Fitness: 20524439
New Best Solution Fitness: 20524109
Generation: 10
New Best Solution Fitness: 20524002
New Best Solution Fitness: 20523901
New Best Solution Fitness: 20523784
New Best Solution Fitness: 20521614
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 7.41111 
Mean sub-tour choices: 8.2 
Best Solution Fitness: 20521614 
--------------------------------------------- 
