--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\usa13509.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 20806293
New Best Solution Fitness: 20794721
New Best Solution Fitness: 20790198
New Best Solution Fitness: 20787875
Generation: 3
New Best Solution Fitness: 20633713
New Best Solution Fitness: 20632498
New Best Solution Fitness: 20620912
Generation: 4
New Best Solution Fitness: 20596228
New Best Solution Fitness: 20596082
New Best Solution Fitness: 20595974
Generation: 5
New Best Solution Fitness: 20595141
New Best Solution Fitness: 20594995
Generation: 6
New Best Solution Fitness: 20590853
New Best Solution Fitness: 20580665
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 20577668
New Best Solution Fitness: 20577189
Generation: 10
New Best Solution Fitness: 20469075
New Best Solution Fitness: 20469066
New Best Solution Fitness: 20468817
New Best Solution Fitness: 20461677
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 8 
Mean sub-tour choices: 8.84444 
Best Solution Fitness: 20461677 
--------------------------------------------- 
