--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\usa13509.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 20691197
New Best Solution Fitness: 20679090
New Best Solution Fitness: 20677395
New Best Solution Fitness: 20672815
Generation: 3
New Best Solution Fitness: 20590273
New Best Solution Fitness: 20588043
New Best Solution Fitness: 20565859
Generation: 4
New Best Solution Fitness: 20545570
New Best Solution Fitness: 20542918
New Best Solution Fitness: 20542331
New Best Solution Fitness: 20541077
Generation: 5
New Best Solution Fitness: 20536969
New Best Solution Fitness: 20536738
New Best Solution Fitness: 20536601
Generation: 6
New Best Solution Fitness: 20523200
New Best Solution Fitness: 20522969
Generation: 7
New Best Solution Fitness: 20522898
New Best Solution Fitness: 20522818
Generation: 8
New Best Solution Fitness: 20522747
Generation: 9
Generation: 10
New Best Solution Fitness: 20521858
New Best Solution Fitness: 20505271
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 8.68889 
Mean sub-tour choices: 9.52222 
Best Solution Fitness: 20505271 
--------------------------------------------- 
