--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\usa13509.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 21364459
New Best Solution Fitness: 21333587
New Best Solution Fitness: 21332814
Generation: 3
New Best Solution Fitness: 20884791
New Best Solution Fitness: 20881936
New Best Solution Fitness: 20879847
New Best Solution Fitness: 20868544
New Best Solution Fitness: 20865140
Generation: 4
New Best Solution Fitness: 20783370
New Best Solution Fitness: 20783285
New Best Solution Fitness: 20754796
New Best Solution Fitness: 20751888
Generation: 5
New Best Solution Fitness: 20567115
New Best Solution Fitness: 20560687
New Best Solution Fitness: 20554178
Generation: 6
New Best Solution Fitness: 20509336
New Best Solution Fitness: 20507869
Generation: 7
New Best Solution Fitness: 20504605
Generation: 8
New Best Solution Fitness: 20502497
Generation: 9
New Best Solution Fitness: 20502122
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 7.8 
Mean sub-tour choices: 8.5 
Best Solution Fitness: 20502122 
--------------------------------------------- 
