--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\usa13509.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 20659680
New Best Solution Fitness: 20651256
New Best Solution Fitness: 20649060
New Best Solution Fitness: 20647933
Generation: 3
New Best Solution Fitness: 20583908
New Best Solution Fitness: 20582287
New Best Solution Fitness: 20582040
Generation: 4
New Best Solution Fitness: 20538973
Generation: 5
New Best Solution Fitness: 20527407
New Best Solution Fitness: 20527124
Generation: 6
Generation: 7
New Best Solution Fitness: 20507468
New Best Solution Fitness: 20507148
New Best Solution Fitness: 20505610
Generation: 8
New Best Solution Fitness: 20502568
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.28889 
Mean sub-tour choices: 4.92222 
Best Solution Fitness: 20502568 
--------------------------------------------- 
