--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\usa13509.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 21306779
New Best Solution Fitness: 21301421
New Best Solution Fitness: 21300176
New Best Solution Fitness: 21298522
New Best Solution Fitness: 21296043
Generation: 3
New Best Solution Fitness: 20822939
New Best Solution Fitness: 20821196
New Best Solution Fitness: 20820136
New Best Solution Fitness: 20816885
Generation: 4
New Best Solution Fitness: 20610499
New Best Solution Fitness: 20608372
New Best Solution Fitness: 20602685
Generation: 5
New Best Solution Fitness: 20527931
New Best Solution Fitness: 20527865
New Best Solution Fitness: 20527709
Generation: 6
New Best Solution Fitness: 20524349
Generation: 7
Generation: 8
New Best Solution Fitness: 20523506
Generation: 9
New Best Solution Fitness: 20512256
New Best Solution Fitness: 20511406
New Best Solution Fitness: 20511229
New Best Solution Fitness: 20510554
Generation: 10
New Best Solution Fitness: 20503121
New Best Solution Fitness: 20502944
New Best Solution Fitness: 20501779
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 6 
Mean sub-tour choices: 6.75556 
Best Solution Fitness: 20501779 
--------------------------------------------- 
