--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\usa13509.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 20860841
New Best Solution Fitness: 20853225
New Best Solution Fitness: 20851375
New Best Solution Fitness: 20848910
New Best Solution Fitness: 20848802
Generation: 3
New Best Solution Fitness: 20693086
New Best Solution Fitness: 20690562
New Best Solution Fitness: 20690558
New Best Solution Fitness: 20682400
Generation: 4
New Best Solution Fitness: 20638862
New Best Solution Fitness: 20636976
New Best Solution Fitness: 20636764
Generation: 5
New Best Solution Fitness: 20614011
New Best Solution Fitness: 20613524
New Best Solution Fitness: 20611760
Generation: 6
New Best Solution Fitness: 20599342
New Best Solution Fitness: 20599289
New Best Solution Fitness: 20598221
Generation: 7
New Best Solution Fitness: 20597595
New Best Solution Fitness: 20597542
New Best Solution Fitness: 20596733
Generation: 8
New Best Solution Fitness: 20596683
Generation: 9
Generation: 10
New Best Solution Fitness: 20595236
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 6.07778 
Mean sub-tour choices: 6.86667 
Best Solution Fitness: 20595236 
--------------------------------------------- 
