--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\usa13509.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 20923614
New Best Solution Fitness: 20911074
New Best Solution Fitness: 20906371
New Best Solution Fitness: 20905404
Generation: 3
New Best Solution Fitness: 20813706
New Best Solution Fitness: 20808703
Generation: 4
New Best Solution Fitness: 20807071
New Best Solution Fitness: 20806847
New Best Solution Fitness: 20803355
Generation: 5
New Best Solution Fitness: 20802950
Generation: 6
New Best Solution Fitness: 20765430
New Best Solution Fitness: 20765337
New Best Solution Fitness: 20750411
Generation: 7
New Best Solution Fitness: 20702912
New Best Solution Fitness: 20702769
New Best Solution Fitness: 20702494
New Best Solution Fitness: 20701630
Generation: 8
New Best Solution Fitness: 20699110
New Best Solution Fitness: 20698967
New Best Solution Fitness: 20698692
Generation: 9
New Best Solution Fitness: 20694862
New Best Solution Fitness: 20694806
New Best Solution Fitness: 20694719
Generation: 10
New Best Solution Fitness: 20690245
New Best Solution Fitness: 20690189
New Best Solution Fitness: 20690002
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 7.25556 
Mean sub-tour choices: 8.07778 
Best Solution Fitness: 20690002 
--------------------------------------------- 
