--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87887
New Best Solution Fitness: 87882
New Best Solution Fitness: 87828
Generation: 3
New Best Solution Fitness: 87823
Generation: 4
New Best Solution Fitness: 87802
New Best Solution Fitness: 87797
New Best Solution Fitness: 87685
Generation: 5
Generation: 6
New Best Solution Fitness: 87675
Generation: 7
New Best Solution Fitness: 87649
New Best Solution Fitness: 87629
Generation: 8
New Best Solution Fitness: 87618
Generation: 9
New Best Solution Fitness: 87566
Generation: 10
New Best Solution Fitness: 87523
New Best Solution Fitness: 87446
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.955556 
Mean sub-tour choices: 1.51111 
Best Solution Fitness: 87446 
--------------------------------------------- 
