--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88292
New Best Solution Fitness: 88149
Generation: 3
New Best Solution Fitness: 87749
New Best Solution Fitness: 87634
Generation: 4
New Best Solution Fitness: 87605
Generation: 5
Generation: 6
New Best Solution Fitness: 87487
New Best Solution Fitness: 87439
Generation: 7
New Best Solution Fitness: 87282
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.766667 
Mean sub-tour choices: 1.18889 
Best Solution Fitness: 87282 
--------------------------------------------- 
