--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88713
New Best Solution Fitness: 88576
Generation: 3
New Best Solution Fitness: 88541
New Best Solution Fitness: 88520
New Best Solution Fitness: 88519
Generation: 4
New Best Solution Fitness: 88498
Generation: 5
New Best Solution Fitness: 88326
New Best Solution Fitness: 88117
New Best Solution Fitness: 88108
New Best Solution Fitness: 88059
Generation: 6
New Best Solution Fitness: 88034
New Best Solution Fitness: 88018
New Best Solution Fitness: 87920
Generation: 7
New Best Solution Fitness: 87899
New Best Solution Fitness: 87883
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 87747
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.14444 
Mean sub-tour choices: 1.77778 
Best Solution Fitness: 87747 
--------------------------------------------- 
