--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88817
New Best Solution Fitness: 88760
New Best Solution Fitness: 88655
Generation: 3
New Best Solution Fitness: 88423
New Best Solution Fitness: 88366
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 88205
New Best Solution Fitness: 88135
Generation: 7
Generation: 8
New Best Solution Fitness: 87954
Generation: 9
New Best Solution Fitness: 87699
New Best Solution Fitness: 87634
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.711111 
Mean sub-tour choices: 1.17778 
Best Solution Fitness: 87634 
--------------------------------------------- 
