--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88014
New Best Solution Fitness: 87984
New Best Solution Fitness: 87642
Generation: 3
New Best Solution Fitness: 87625
Generation: 4
New Best Solution Fitness: 87521
Generation: 5
New Best Solution Fitness: 87516
Generation: 6
New Best Solution Fitness: 87503
Generation: 7
Generation: 8
New Best Solution Fitness: 87466
New Best Solution Fitness: 87462
Generation: 9
New Best Solution Fitness: 87447
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.455556 
Mean sub-tour choices: 0.777778 
Best Solution Fitness: 87447 
--------------------------------------------- 
