--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88516
New Best Solution Fitness: 88447
Generation: 3
New Best Solution Fitness: 88294
New Best Solution Fitness: 88225
New Best Solution Fitness: 88217
Generation: 4
New Best Solution Fitness: 88083
Generation: 5
New Best Solution Fitness: 88002
New Best Solution Fitness: 87991
Generation: 6
New Best Solution Fitness: 87598
Generation: 7
New Best Solution Fitness: 87592
New Best Solution Fitness: 87577
Generation: 8
New Best Solution Fitness: 87567
Generation: 9
New Best Solution Fitness: 87563
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.755556 
Mean sub-tour choices: 1.28889 
Best Solution Fitness: 87563 
--------------------------------------------- 
