--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88003
New Best Solution Fitness: 87971
New Best Solution Fitness: 87957
Generation: 3
New Best Solution Fitness: 87949
Generation: 4
New Best Solution Fitness: 87906
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 87590
New Best Solution Fitness: 87517
Generation: 9
New Best Solution Fitness: 87442
Generation: 10
New Best Solution Fitness: 87252
New Best Solution Fitness: 87234
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.477778 
Mean sub-tour choices: 0.855556 
Best Solution Fitness: 87234 
--------------------------------------------- 
