--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88061
New Best Solution Fitness: 88035
Generation: 3
New Best Solution Fitness: 87154
Generation: 4
New Best Solution Fitness: 87128
New Best Solution Fitness: 87105
Generation: 5
New Best Solution Fitness: 87102
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.466667 
Mean sub-tour choices: 0.833333 
Best Solution Fitness: 87102 
--------------------------------------------- 
