--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88956
New Best Solution Fitness: 88906
New Best Solution Fitness: 88757
Generation: 3
New Best Solution Fitness: 88182
New Best Solution Fitness: 88176
Generation: 4
New Best Solution Fitness: 88170
Generation: 5
New Best Solution Fitness: 88115
New Best Solution Fitness: 88068
Generation: 6
Generation: 7
New Best Solution Fitness: 87885
New Best Solution Fitness: 87831
Generation: 8
New Best Solution Fitness: 87553
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.655556 
Mean sub-tour choices: 1.05556 
Best Solution Fitness: 87553 
--------------------------------------------- 
