--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87996
New Best Solution Fitness: 87915
Generation: 3
New Best Solution Fitness: 87541
Generation: 4
New Best Solution Fitness: 87430
New Best Solution Fitness: 87420
New Best Solution Fitness: 87417
New Best Solution Fitness: 87402
Generation: 5
New Best Solution Fitness: 87392
Generation: 6
Generation: 7
New Best Solution Fitness: 87382
New Best Solution Fitness: 87365
Generation: 8
New Best Solution Fitness: 87248
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.722222 
Mean sub-tour choices: 1.23333 
Best Solution Fitness: 87248 
--------------------------------------------- 
