--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88350
Generation: 3
New Best Solution Fitness: 88148
Generation: 4
New Best Solution Fitness: 88125
Generation: 5
New Best Solution Fitness: 87764
New Best Solution Fitness: 87760
Generation: 6
New Best Solution Fitness: 87734
New Best Solution Fitness: 87699
Generation: 7
Generation: 8
New Best Solution Fitness: 87698
Generation: 9
New Best Solution Fitness: 87697
New Best Solution Fitness: 87673
New Best Solution Fitness: 87580
Generation: 10
New Best Solution Fitness: 87569
New Best Solution Fitness: 87556
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.533333 
Mean sub-tour choices: 0.944444 
Best Solution Fitness: 87556 
--------------------------------------------- 
