--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87967
Generation: 3
New Best Solution Fitness: 87867
New Best Solution Fitness: 87865
Generation: 4
New Best Solution Fitness: 87757
Generation: 5
New Best Solution Fitness: 87688
Generation: 6
New Best Solution Fitness: 87660
Generation: 7
New Best Solution Fitness: 87656
New Best Solution Fitness: 87630
Generation: 8
New Best Solution Fitness: 87626
Generation: 9
Generation: 10
New Best Solution Fitness: 87433
New Best Solution Fitness: 87371
New Best Solution Fitness: 87369
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.455556 
Mean sub-tour choices: 0.8 
Best Solution Fitness: 87369 
--------------------------------------------- 
