--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88660
New Best Solution Fitness: 88624
New Best Solution Fitness: 88593
Generation: 3
New Best Solution Fitness: 88367
Generation: 4
New Best Solution Fitness: 88216
New Best Solution Fitness: 87957
Generation: 5
New Best Solution Fitness: 87762
Generation: 6
New Best Solution Fitness: 87590
Generation: 7
New Best Solution Fitness: 87546
New Best Solution Fitness: 87493
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.633333 
Mean sub-tour choices: 1 
Best Solution Fitness: 87493 
--------------------------------------------- 
