--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88400
New Best Solution Fitness: 88022
New Best Solution Fitness: 87993
Generation: 3
New Best Solution Fitness: 87948
Generation: 4
New Best Solution Fitness: 87805
New Best Solution Fitness: 87717
Generation: 5
New Best Solution Fitness: 87600
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 87568
New Best Solution Fitness: 87566
Generation: 9
New Best Solution Fitness: 87499
Generation: 10
New Best Solution Fitness: 87477
New Best Solution Fitness: 87379
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.588889 
Mean sub-tour choices: 0.988889 
Best Solution Fitness: 87379 
--------------------------------------------- 
