--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87732
New Best Solution Fitness: 87700
Generation: 3
New Best Solution Fitness: 87617
New Best Solution Fitness: 87483
Generation: 4
Generation: 5
New Best Solution Fitness: 87398
Generation: 6
New Best Solution Fitness: 87392
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.04444 
Mean sub-tour choices: 1.67778 
Best Solution Fitness: 87392 
--------------------------------------------- 
