--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88696
Generation: 3
New Best Solution Fitness: 88287
New Best Solution Fitness: 87878
New Best Solution Fitness: 87842
Generation: 4
New Best Solution Fitness: 87836
Generation: 5
Generation: 6
New Best Solution Fitness: 87815
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 87765
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.588889 
Mean sub-tour choices: 1 
Best Solution Fitness: 87765 
--------------------------------------------- 
