--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88441
New Best Solution Fitness: 88416
Generation: 3
New Best Solution Fitness: 88193
New Best Solution Fitness: 88176
Generation: 4
Generation: 5
New Best Solution Fitness: 88169
Generation: 6
New Best Solution Fitness: 87916
New Best Solution Fitness: 87468
Generation: 7
New Best Solution Fitness: 87385
Generation: 8
New Best Solution Fitness: 87337
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.511111 
Mean sub-tour choices: 0.855556 
Best Solution Fitness: 87337 
--------------------------------------------- 
