--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88335
New Best Solution Fitness: 88258
New Best Solution Fitness: 88182
Generation: 3
New Best Solution Fitness: 87337
New Best Solution Fitness: 87261
Generation: 4
New Best Solution Fitness: 87231
Generation: 5
New Best Solution Fitness: 87220
Generation: 6
New Best Solution Fitness: 87214
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 87210
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.911111 
Mean sub-tour choices: 1.54444 
Best Solution Fitness: 87210 
--------------------------------------------- 
