--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 89501
New Best Solution Fitness: 89344
Generation: 3
New Best Solution Fitness: 88191
New Best Solution Fitness: 88180
Generation: 4
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 88085
Generation: 8
New Best Solution Fitness: 88057
Generation: 9
Generation: 10
New Best Solution Fitness: 87319
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.533333 
Mean sub-tour choices: 0.933333 
Best Solution Fitness: 87319 
--------------------------------------------- 
