--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88682
New Best Solution Fitness: 88661
New Best Solution Fitness: 88423
Generation: 3
New Best Solution Fitness: 88092
New Best Solution Fitness: 88022
New Best Solution Fitness: 88018
New Best Solution Fitness: 88005
Generation: 4
New Best Solution Fitness: 87892
New Best Solution Fitness: 87871
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.766667 
Mean sub-tour choices: 1.25556 
Best Solution Fitness: 87871 
--------------------------------------------- 
