--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88193
New Best Solution Fitness: 88182
Generation: 3
New Best Solution Fitness: 88147
New Best Solution Fitness: 88118
Generation: 4
New Best Solution Fitness: 87927
Generation: 5
New Best Solution Fitness: 87845
Generation: 6
New Best Solution Fitness: 87819
New Best Solution Fitness: 87814
New Best Solution Fitness: 87668
Generation: 7
New Best Solution Fitness: 87465
New Best Solution Fitness: 87464
Generation: 8
Generation: 9
New Best Solution Fitness: 87289
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.611111 
Mean sub-tour choices: 1.07778 
Best Solution Fitness: 87289 
--------------------------------------------- 
