--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88129
New Best Solution Fitness: 88092
New Best Solution Fitness: 88040
Generation: 3
New Best Solution Fitness: 87880
Generation: 4
Generation: 5
New Best Solution Fitness: 87813
New Best Solution Fitness: 87782
New Best Solution Fitness: 87765
Generation: 6
Generation: 7
New Best Solution Fitness: 87743
Generation: 8
New Best Solution Fitness: 87707
New Best Solution Fitness: 87670
Generation: 9
New Best Solution Fitness: 87644
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.688889 
Mean sub-tour choices: 1.08889 
Best Solution Fitness: 87644 
--------------------------------------------- 
