--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88145
New Best Solution Fitness: 88092
Generation: 3
New Best Solution Fitness: 88009
New Best Solution Fitness: 88008
Generation: 4
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 87950
Generation: 9
New Best Solution Fitness: 87842
New Best Solution Fitness: 87838
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.633333 
Mean sub-tour choices: 1.07778 
Best Solution Fitness: 87838 
--------------------------------------------- 
