--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88366
New Best Solution Fitness: 88302
New Best Solution Fitness: 88146
Generation: 3
New Best Solution Fitness: 88032
Generation: 4
Generation: 5
New Best Solution Fitness: 87700
Generation: 6
Generation: 7
New Best Solution Fitness: 87689
New Best Solution Fitness: 87654
Generation: 8
New Best Solution Fitness: 87617
New Best Solution Fitness: 87494
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.444444 
Mean sub-tour choices: 0.744444 
Best Solution Fitness: 87494 
--------------------------------------------- 
