--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88196
New Best Solution Fitness: 88185
Generation: 3
New Best Solution Fitness: 87931
New Best Solution Fitness: 87814
Generation: 4
New Best Solution Fitness: 87802
Generation: 5
New Best Solution Fitness: 87707
New Best Solution Fitness: 87702
New Best Solution Fitness: 87680
Generation: 6
New Best Solution Fitness: 87676
Generation: 7
Generation: 8
New Best Solution Fitness: 87624
New Best Solution Fitness: 87620
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.622222 
Mean sub-tour choices: 1.13333 
Best Solution Fitness: 87620 
--------------------------------------------- 
