--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88864
New Best Solution Fitness: 88847
New Best Solution Fitness: 88795
Generation: 3
New Best Solution Fitness: 88740
Generation: 4
Generation: 5
New Best Solution Fitness: 88258
New Best Solution Fitness: 88000
Generation: 6
New Best Solution Fitness: 87958
Generation: 7
New Best Solution Fitness: 87903
Generation: 8
New Best Solution Fitness: 87800
New Best Solution Fitness: 87743
New Best Solution Fitness: 87723
New Best Solution Fitness: 87704
Generation: 9
New Best Solution Fitness: 87597
Generation: 10
New Best Solution Fitness: 87356
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.566667 
Mean sub-tour choices: 1.02222 
Best Solution Fitness: 87356 
--------------------------------------------- 
