--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88689
New Best Solution Fitness: 88674
New Best Solution Fitness: 88645
New Best Solution Fitness: 88096
New Best Solution Fitness: 88069
Generation: 3
New Best Solution Fitness: 87387
New Best Solution Fitness: 87358
Generation: 4
New Best Solution Fitness: 87352
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 87309
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.16667 
Mean sub-tour choices: 1.81111 
Best Solution Fitness: 87309 
--------------------------------------------- 
