--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 89037
Generation: 3
New Best Solution Fitness: 88504
Generation: 4
New Best Solution Fitness: 88443
Generation: 5
New Best Solution Fitness: 88369
New Best Solution Fitness: 88150
Generation: 6
New Best Solution Fitness: 88130
New Best Solution Fitness: 88091
Generation: 7
New Best Solution Fitness: 87673
Generation: 8
New Best Solution Fitness: 87614
Generation: 9
Generation: 10
New Best Solution Fitness: 87578
New Best Solution Fitness: 87558
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.555556 
Mean sub-tour choices: 0.988889 
Best Solution Fitness: 87558 
--------------------------------------------- 
