--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88517
New Best Solution Fitness: 88414
Generation: 3
New Best Solution Fitness: 88390
New Best Solution Fitness: 88366
Generation: 4
Generation: 5
New Best Solution Fitness: 88303
New Best Solution Fitness: 88255
Generation: 6
Generation: 7
New Best Solution Fitness: 88211
Generation: 8
New Best Solution Fitness: 87918
New Best Solution Fitness: 87872
Generation: 9
New Best Solution Fitness: 87838
Generation: 10
New Best Solution Fitness: 87815
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.666667 
Mean sub-tour choices: 1.13333 
Best Solution Fitness: 87815 
--------------------------------------------- 
