--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88763
New Best Solution Fitness: 88677
Generation: 3
New Best Solution Fitness: 88501
New Best Solution Fitness: 88479
Generation: 4
New Best Solution Fitness: 88020
Generation: 5
New Best Solution Fitness: 87888
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 87878
Generation: 9
New Best Solution Fitness: 87862
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.844444 
Mean sub-tour choices: 1.32222 
Best Solution Fitness: 87862 
--------------------------------------------- 
