--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88705
New Best Solution Fitness: 88698
New Best Solution Fitness: 88639
Generation: 3
New Best Solution Fitness: 88222
Generation: 4
New Best Solution Fitness: 88088
Generation: 5
New Best Solution Fitness: 88003
New Best Solution Fitness: 87972
Generation: 6
New Best Solution Fitness: 87697
New Best Solution Fitness: 87628
Generation: 7
New Best Solution Fitness: 87584
Generation: 8
New Best Solution Fitness: 87563
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.566667 
Mean sub-tour choices: 0.944444 
Best Solution Fitness: 87563 
--------------------------------------------- 
