--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88160
New Best Solution Fitness: 88082
Generation: 3
New Best Solution Fitness: 88053
Generation: 4
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 88042
Generation: 8
New Best Solution Fitness: 87690
New Best Solution Fitness: 87686
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.4 
Mean sub-tour choices: 0.722222 
Best Solution Fitness: 87686 
--------------------------------------------- 
