--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88550
New Best Solution Fitness: 88506
New Best Solution Fitness: 88346
Generation: 3
New Best Solution Fitness: 88315
Generation: 4
New Best Solution Fitness: 87499
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 87461
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.722222 
Mean sub-tour choices: 1.23333 
Best Solution Fitness: 87461 
--------------------------------------------- 
