--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 89589
New Best Solution Fitness: 89503
New Best Solution Fitness: 89451
Generation: 3
New Best Solution Fitness: 88959
New Best Solution Fitness: 88584
Generation: 4
New Best Solution Fitness: 88522
Generation: 5
New Best Solution Fitness: 88335
New Best Solution Fitness: 88275
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 88247
New Best Solution Fitness: 88213
New Best Solution Fitness: 87909
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.422222 
Mean sub-tour choices: 0.733333 
Best Solution Fitness: 87909 
--------------------------------------------- 
