--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88328
New Best Solution Fitness: 88308
Generation: 3
New Best Solution Fitness: 88042
New Best Solution Fitness: 88040
Generation: 4
New Best Solution Fitness: 87925
New Best Solution Fitness: 87923
Generation: 5
New Best Solution Fitness: 87897
Generation: 6
New Best Solution Fitness: 87422
New Best Solution Fitness: 87346
Generation: 7
New Best Solution Fitness: 87284
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.411111 
Mean sub-tour choices: 0.744444 
Best Solution Fitness: 87284 
--------------------------------------------- 
