--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88056
New Best Solution Fitness: 88001
Generation: 3
Generation: 4
New Best Solution Fitness: 87603
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 87469
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.311111 
Mean sub-tour choices: 0.544444 
Best Solution Fitness: 87469 
--------------------------------------------- 
