--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88908
Generation: 3
New Best Solution Fitness: 88286
Generation: 4
New Best Solution Fitness: 88258
New Best Solution Fitness: 88253
Generation: 5
New Best Solution Fitness: 87772
Generation: 6
New Best Solution Fitness: 87686
Generation: 7
New Best Solution Fitness: 87453
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 87180
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.333333 
Mean sub-tour choices: 0.555556 
Best Solution Fitness: 87180 
--------------------------------------------- 
