--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88871
New Best Solution Fitness: 88726
Generation: 3
New Best Solution Fitness: 88389
New Best Solution Fitness: 88351
Generation: 4
New Best Solution Fitness: 88230
Generation: 5
New Best Solution Fitness: 88115
New Best Solution Fitness: 87887
New Best Solution Fitness: 87826
New Best Solution Fitness: 87540
Generation: 6
New Best Solution Fitness: 87299
Generation: 7
New Best Solution Fitness: 87289
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 87188
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.588889 
Mean sub-tour choices: 0.988889 
Best Solution Fitness: 87188 
--------------------------------------------- 
