--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87920
New Best Solution Fitness: 87911
Generation: 3
New Best Solution Fitness: 87498
New Best Solution Fitness: 87373
Generation: 4
New Best Solution Fitness: 87357
New Best Solution Fitness: 87351
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.922222 
Mean sub-tour choices: 1.37778 
Best Solution Fitness: 87351 
--------------------------------------------- 
