--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 89581
New Best Solution Fitness: 89524
New Best Solution Fitness: 88400
Generation: 3
New Best Solution Fitness: 87986
New Best Solution Fitness: 87611
Generation: 4
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 87607
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.4 
Mean sub-tour choices: 2.13333 
Best Solution Fitness: 87607 
--------------------------------------------- 
