--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88491
New Best Solution Fitness: 88480
New Best Solution Fitness: 88198
Generation: 3
New Best Solution Fitness: 87945
New Best Solution Fitness: 87930
New Best Solution Fitness: 87911
Generation: 4
New Best Solution Fitness: 87896
Generation: 5
New Best Solution Fitness: 87852
Generation: 6
Generation: 7
New Best Solution Fitness: 87764
Generation: 8
Generation: 9
New Best Solution Fitness: 87743
Generation: 10
New Best Solution Fitness: 87731
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.933333 
Mean sub-tour choices: 1.45556 
Best Solution Fitness: 87731 
--------------------------------------------- 
