--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87509
Generation: 3
New Best Solution Fitness: 87389
Generation: 4
New Best Solution Fitness: 87373
Generation: 5
New Best Solution Fitness: 87358
Generation: 6
Generation: 7
New Best Solution Fitness: 87353
Generation: 8
New Best Solution Fitness: 87349
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.833333 
Mean sub-tour choices: 1.36667 
Best Solution Fitness: 87349 
--------------------------------------------- 
