--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 89491
New Best Solution Fitness: 88313
Generation: 3
New Best Solution Fitness: 87852
Generation: 4
New Best Solution Fitness: 87835
Generation: 5
Generation: 6
New Best Solution Fitness: 87641
Generation: 7
New Best Solution Fitness: 87635
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.488889 
Mean sub-tour choices: 0.877778 
Best Solution Fitness: 87635 
--------------------------------------------- 
