--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 89453
New Best Solution Fitness: 89437
New Best Solution Fitness: 89285
Generation: 3
New Best Solution Fitness: 87912
New Best Solution Fitness: 87633
Generation: 4
New Best Solution Fitness: 87622
Generation: 5
New Best Solution Fitness: 87597
New Best Solution Fitness: 87579
Generation: 6
New Best Solution Fitness: 87571
Generation: 7
New Best Solution Fitness: 87431
New Best Solution Fitness: 87376
New Best Solution Fitness: 87286
Generation: 8
New Best Solution Fitness: 87246
Generation: 9
New Best Solution Fitness: 87242
Generation: 10
New Best Solution Fitness: 87138
New Best Solution Fitness: 87123
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.4 
Mean sub-tour choices: 2.12222 
Best Solution Fitness: 87123 
--------------------------------------------- 
