--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88665
New Best Solution Fitness: 88386
New Best Solution Fitness: 88296
Generation: 3
New Best Solution Fitness: 87923
New Best Solution Fitness: 87912
Generation: 4
New Best Solution Fitness: 87887
Generation: 5
Generation: 6
New Best Solution Fitness: 87537
Generation: 7
New Best Solution Fitness: 87529
New Best Solution Fitness: 87521
Generation: 8
Generation: 9
New Best Solution Fitness: 87520
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.644444 
Mean sub-tour choices: 1.04444 
Best Solution Fitness: 87520 
--------------------------------------------- 
