--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88109
New Best Solution Fitness: 88034
New Best Solution Fitness: 87942
New Best Solution Fitness: 87917
Generation: 3
New Best Solution Fitness: 87874
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 87869
Generation: 7
New Best Solution Fitness: 87716
New Best Solution Fitness: 87687
Generation: 8
New Best Solution Fitness: 87638
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.777778 
Mean sub-tour choices: 1.14444 
Best Solution Fitness: 87638 
--------------------------------------------- 
