--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88702
New Best Solution Fitness: 88274
Generation: 3
New Best Solution Fitness: 87702
New Best Solution Fitness: 87479
Generation: 4
New Best Solution Fitness: 87448
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 87362
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.6 
Mean sub-tour choices: 1.05556 
Best Solution Fitness: 87362 
--------------------------------------------- 
