--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88772
New Best Solution Fitness: 88754
New Best Solution Fitness: 88743
Generation: 3
New Best Solution Fitness: 88732
New Best Solution Fitness: 88689
New Best Solution Fitness: 88667
Generation: 4
New Best Solution Fitness: 88656
New Best Solution Fitness: 88625
New Best Solution Fitness: 88624
Generation: 5
New Best Solution Fitness: 88572
Generation: 6
New Best Solution Fitness: 88565
New Best Solution Fitness: 88564
Generation: 7
Generation: 8
New Best Solution Fitness: 88546
Generation: 9
New Best Solution Fitness: 88439
New Best Solution Fitness: 88311
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.21111 
Mean sub-tour choices: 1.85556 
Best Solution Fitness: 88311 
--------------------------------------------- 
