--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88379
Generation: 3
New Best Solution Fitness: 88322
New Best Solution Fitness: 88304
Generation: 4
New Best Solution Fitness: 88283
New Best Solution Fitness: 88246
New Best Solution Fitness: 88245
Generation: 5
New Best Solution Fitness: 88201
New Best Solution Fitness: 88182
New Best Solution Fitness: 88158
Generation: 6
New Best Solution Fitness: 87833
New Best Solution Fitness: 87712
Generation: 7
New Best Solution Fitness: 87571
New Best Solution Fitness: 87539
Generation: 8
Generation: 9
New Best Solution Fitness: 87426
New Best Solution Fitness: 87333
Generation: 10
New Best Solution Fitness: 87316
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.533333 
Mean sub-tour choices: 0.922222 
Best Solution Fitness: 87316 
--------------------------------------------- 
