--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88527
New Best Solution Fitness: 88511
New Best Solution Fitness: 88507
New Best Solution Fitness: 88497
Generation: 3
New Best Solution Fitness: 88387
New Best Solution Fitness: 88088
Generation: 4
New Best Solution Fitness: 88036
Generation: 5
New Best Solution Fitness: 88034
New Best Solution Fitness: 88025
New Best Solution Fitness: 87979
Generation: 6
Generation: 7
New Best Solution Fitness: 87964
Generation: 8
New Best Solution Fitness: 87914
New Best Solution Fitness: 87720
New Best Solution Fitness: 87705
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.711111 
Mean sub-tour choices: 1.16667 
Best Solution Fitness: 87705 
--------------------------------------------- 
