--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88465
New Best Solution Fitness: 88445
Generation: 3
New Best Solution Fitness: 87458
Generation: 4
Generation: 5
New Best Solution Fitness: 87457
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 87398
New Best Solution Fitness: 87397
New Best Solution Fitness: 87383
Generation: 9
New Best Solution Fitness: 87301
New Best Solution Fitness: 87300
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.333333 
Mean sub-tour choices: 0.566667 
Best Solution Fitness: 87300 
--------------------------------------------- 
