--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87530
New Best Solution Fitness: 87526
Generation: 3
Generation: 4
New Best Solution Fitness: 87475
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 87451
New Best Solution Fitness: 87286
Generation: 9
New Best Solution Fitness: 87251
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.655556 
Mean sub-tour choices: 1.15556 
Best Solution Fitness: 87251 
--------------------------------------------- 
