--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88307
New Best Solution Fitness: 88230
Generation: 3
New Best Solution Fitness: 87969
New Best Solution Fitness: 87712
Generation: 4
New Best Solution Fitness: 87654
New Best Solution Fitness: 87652
New Best Solution Fitness: 87577
Generation: 5
New Best Solution Fitness: 87575
Generation: 6
New Best Solution Fitness: 87517
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 87512
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.522222 
Mean sub-tour choices: 0.911111 
Best Solution Fitness: 87512 
--------------------------------------------- 
