--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87973
New Best Solution Fitness: 87967
New Best Solution Fitness: 87768
Generation: 3
New Best Solution Fitness: 87745
New Best Solution Fitness: 87616
Generation: 4
New Best Solution Fitness: 87537
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 87534
New Best Solution Fitness: 87489
Generation: 8
New Best Solution Fitness: 87446
New Best Solution Fitness: 87355
New Best Solution Fitness: 87349
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.644444 
Mean sub-tour choices: 1.06667 
Best Solution Fitness: 87349 
--------------------------------------------- 
