--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88667
New Best Solution Fitness: 88635
Generation: 3
New Best Solution Fitness: 88477
New Best Solution Fitness: 88352
Generation: 4
New Best Solution Fitness: 88022
Generation: 5
New Best Solution Fitness: 87944
New Best Solution Fitness: 87927
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 87661
New Best Solution Fitness: 87654
Generation: 10
New Best Solution Fitness: 87423
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.655556 
Mean sub-tour choices: 1.05556 
Best Solution Fitness: 87423 
--------------------------------------------- 
