--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88787
New Best Solution Fitness: 88618
Generation: 3
New Best Solution Fitness: 88113
New Best Solution Fitness: 87963
New Best Solution Fitness: 87885
Generation: 4
New Best Solution Fitness: 87876
New Best Solution Fitness: 87735
Generation: 5
New Best Solution Fitness: 87724
New Best Solution Fitness: 87716
Generation: 6
New Best Solution Fitness: 87701
Generation: 7
Generation: 8
New Best Solution Fitness: 87560
New Best Solution Fitness: 87504
Generation: 9
Generation: 10
New Best Solution Fitness: 87495
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.01111 
Mean sub-tour choices: 1.67778 
Best Solution Fitness: 87495 
--------------------------------------------- 
