--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88208
New Best Solution Fitness: 88037
Generation: 3
New Best Solution Fitness: 88019
Generation: 4
New Best Solution Fitness: 87714
New Best Solution Fitness: 87699
Generation: 5
New Best Solution Fitness: 87420
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.655556 
Mean sub-tour choices: 1.02222 
Best Solution Fitness: 87420 
--------------------------------------------- 
