--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88162
New Best Solution Fitness: 88131
New Best Solution Fitness: 88126
Generation: 3
New Best Solution Fitness: 88052
New Best Solution Fitness: 88031
Generation: 4
New Best Solution Fitness: 88012
Generation: 5
New Best Solution Fitness: 87977
Generation: 6
New Best Solution Fitness: 87948
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 87858
New Best Solution Fitness: 87832
New Best Solution Fitness: 87790
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.35556 
Mean sub-tour choices: 1.98889 
Best Solution Fitness: 87790 
--------------------------------------------- 
