--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88785
New Best Solution Fitness: 88730
Generation: 3
New Best Solution Fitness: 88143
Generation: 4
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 87535
Generation: 9
Generation: 10
New Best Solution Fitness: 87533
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.344444 
Mean sub-tour choices: 0.633333 
Best Solution Fitness: 87533 
--------------------------------------------- 
