--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87901
New Best Solution Fitness: 87864
New Best Solution Fitness: 87817
Generation: 3
New Best Solution Fitness: 87705
Generation: 4
Generation: 5
New Best Solution Fitness: 87702
New Best Solution Fitness: 87681
Generation: 6
New Best Solution Fitness: 87586
New Best Solution Fitness: 87547
Generation: 7
New Best Solution Fitness: 87474
Generation: 8
Generation: 9
New Best Solution Fitness: 87466
New Best Solution Fitness: 87442
New Best Solution Fitness: 87420
Generation: 10
New Best Solution Fitness: 87366
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.888889 
Mean sub-tour choices: 1.42222 
Best Solution Fitness: 87366 
--------------------------------------------- 
