--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88531
New Best Solution Fitness: 88404
Generation: 3
New Best Solution Fitness: 88086
New Best Solution Fitness: 88022
Generation: 4
New Best Solution Fitness: 87893
New Best Solution Fitness: 87874
Generation: 5
New Best Solution Fitness: 87723
Generation: 6
New Best Solution Fitness: 87718
Generation: 7
New Best Solution Fitness: 87655
New Best Solution Fitness: 87654
Generation: 8
Generation: 9
New Best Solution Fitness: 87650
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.677778 
Mean sub-tour choices: 1.06667 
Best Solution Fitness: 87650 
--------------------------------------------- 
