--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88828
New Best Solution Fitness: 88825
New Best Solution Fitness: 88788
Generation: 3
New Best Solution Fitness: 88589
New Best Solution Fitness: 88585
New Best Solution Fitness: 88552
Generation: 4
New Best Solution Fitness: 88350
New Best Solution Fitness: 88346
Generation: 5
New Best Solution Fitness: 88338
Generation: 6
New Best Solution Fitness: 88329
New Best Solution Fitness: 88140
Generation: 7
New Best Solution Fitness: 88047
Generation: 8
Generation: 9
New Best Solution Fitness: 87637
New Best Solution Fitness: 87594
Generation: 10
New Best Solution Fitness: 87481
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.6 
Mean sub-tour choices: 1.02222 
Best Solution Fitness: 87481 
--------------------------------------------- 
