--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88023
New Best Solution Fitness: 88013
Generation: 3
New Best Solution Fitness: 87727
New Best Solution Fitness: 87702
Generation: 4
New Best Solution Fitness: 87676
Generation: 5
Generation: 6
New Best Solution Fitness: 87610
Generation: 7
New Best Solution Fitness: 87591
Generation: 8
Generation: 9
New Best Solution Fitness: 87538
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.455556 
Mean sub-tour choices: 0.811111 
Best Solution Fitness: 87538 
--------------------------------------------- 
