--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88640
New Best Solution Fitness: 88602
New Best Solution Fitness: 88588
Generation: 3
New Best Solution Fitness: 88298
Generation: 4
New Best Solution Fitness: 87844
New Best Solution Fitness: 87793
Generation: 5
New Best Solution Fitness: 87461
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 87341
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.9 
Mean sub-tour choices: 2.73333 
Best Solution Fitness: 87341 
--------------------------------------------- 
