--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87826
New Best Solution Fitness: 87812
Generation: 3
New Best Solution Fitness: 87459
New Best Solution Fitness: 87388
Generation: 4
Generation: 5
New Best Solution Fitness: 87329
Generation: 6
Generation: 7
New Best Solution Fitness: 87317
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.511111 
Mean sub-tour choices: 0.911111 
Best Solution Fitness: 87317 
--------------------------------------------- 
