--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88700
New Best Solution Fitness: 88647
New Best Solution Fitness: 88529
Generation: 3
New Best Solution Fitness: 88108
New Best Solution Fitness: 88085
Generation: 4
New Best Solution Fitness: 87725
New Best Solution Fitness: 87721
Generation: 5
New Best Solution Fitness: 87556
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.511111 
Mean sub-tour choices: 0.866667 
Best Solution Fitness: 87556 
--------------------------------------------- 
