--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88843
New Best Solution Fitness: 88836
Generation: 3
New Best Solution Fitness: 88720
New Best Solution Fitness: 88541
Generation: 4
New Best Solution Fitness: 88486
New Best Solution Fitness: 88484
New Best Solution Fitness: 88361
Generation: 5
New Best Solution Fitness: 88106
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 88078
New Best Solution Fitness: 87892
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.07778 
Mean sub-tour choices: 1.71111 
Best Solution Fitness: 87892 
--------------------------------------------- 
