--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88675
New Best Solution Fitness: 88649
New Best Solution Fitness: 88541
Generation: 3
New Best Solution Fitness: 88152
New Best Solution Fitness: 88085
Generation: 4
Generation: 5
New Best Solution Fitness: 88047
New Best Solution Fitness: 87948
Generation: 6
New Best Solution Fitness: 87656
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 87648
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.688889 
Mean sub-tour choices: 1.17778 
Best Solution Fitness: 87648 
--------------------------------------------- 
