--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87771
Generation: 3
New Best Solution Fitness: 87761
New Best Solution Fitness: 87727
Generation: 4
New Best Solution Fitness: 87624
New Best Solution Fitness: 87590
Generation: 5
New Best Solution Fitness: 87506
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.611111 
Mean sub-tour choices: 1.03333 
Best Solution Fitness: 87506 
--------------------------------------------- 
