--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87804
New Best Solution Fitness: 87765
New Best Solution Fitness: 87739
Generation: 3
New Best Solution Fitness: 87638
Generation: 4
New Best Solution Fitness: 87614
Generation: 5
New Best Solution Fitness: 87595
Generation: 6
New Best Solution Fitness: 87404
Generation: 7
New Best Solution Fitness: 87380
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.288889 
Mean sub-tour choices: 0.522222 
Best Solution Fitness: 87380 
--------------------------------------------- 
