--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88212
New Best Solution Fitness: 88207
Generation: 3
New Best Solution Fitness: 88123
New Best Solution Fitness: 88007
Generation: 4
New Best Solution Fitness: 87981
Generation: 5
Generation: 6
New Best Solution Fitness: 87954
Generation: 7
Generation: 8
New Best Solution Fitness: 87776
Generation: 9
New Best Solution Fitness: 87480
New Best Solution Fitness: 87457
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.944444 
Mean sub-tour choices: 1.56667 
Best Solution Fitness: 87457 
--------------------------------------------- 
