--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88274
New Best Solution Fitness: 88244
New Best Solution Fitness: 88194
Generation: 3
New Best Solution Fitness: 88052
New Best Solution Fitness: 88022
Generation: 4
Generation: 5
New Best Solution Fitness: 87733
New Best Solution Fitness: 87615
Generation: 6
New Best Solution Fitness: 87529
New Best Solution Fitness: 87427
Generation: 7
New Best Solution Fitness: 87300
Generation: 8
New Best Solution Fitness: 87290
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.611111 
Mean sub-tour choices: 1.01111 
Best Solution Fitness: 87290 
--------------------------------------------- 
