--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88649
New Best Solution Fitness: 88594
Generation: 3
New Best Solution Fitness: 87658
New Best Solution Fitness: 87613
New Best Solution Fitness: 87568
Generation: 4
New Best Solution Fitness: 87563
New Best Solution Fitness: 87508
Generation: 5
New Best Solution Fitness: 87463
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.744444 
Mean sub-tour choices: 1.17778 
Best Solution Fitness: 87463 
--------------------------------------------- 
