--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88060
New Best Solution Fitness: 87902
Generation: 3
New Best Solution Fitness: 87884
Generation: 4
New Best Solution Fitness: 87848
Generation: 5
New Best Solution Fitness: 87830
Generation: 6
Generation: 7
New Best Solution Fitness: 87798
New Best Solution Fitness: 87784
Generation: 8
New Best Solution Fitness: 87783
Generation: 9
New Best Solution Fitness: 87524
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.744444 
Mean sub-tour choices: 1.26667 
Best Solution Fitness: 87524 
--------------------------------------------- 
