--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87851
New Best Solution Fitness: 87827
New Best Solution Fitness: 87715
New Best Solution Fitness: 87654
Generation: 3
New Best Solution Fitness: 87640
Generation: 4
New Best Solution Fitness: 87619
Generation: 5
New Best Solution Fitness: 87596
New Best Solution Fitness: 87575
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 87470
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.644444 
Mean sub-tour choices: 1.05556 
Best Solution Fitness: 87470 
--------------------------------------------- 
