--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88178
New Best Solution Fitness: 88130
New Best Solution Fitness: 88030
Generation: 3
New Best Solution Fitness: 87724
New Best Solution Fitness: 87699
New Best Solution Fitness: 87697
Generation: 4
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 87406
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.644444 
Mean sub-tour choices: 1.11111 
Best Solution Fitness: 87406 
--------------------------------------------- 
