--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88944
New Best Solution Fitness: 88796
Generation: 3
New Best Solution Fitness: 88609
New Best Solution Fitness: 88606
New Best Solution Fitness: 88464
Generation: 4
New Best Solution Fitness: 88428
Generation: 5
New Best Solution Fitness: 88109
New Best Solution Fitness: 87686
Generation: 6
New Best Solution Fitness: 87680
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 87560
New Best Solution Fitness: 87526
New Best Solution Fitness: 87511
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.22222 
Mean sub-tour choices: 1.9 
Best Solution Fitness: 87511 
--------------------------------------------- 
