--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88481
New Best Solution Fitness: 88460
New Best Solution Fitness: 88290
Generation: 3
New Best Solution Fitness: 88214
Generation: 4
New Best Solution Fitness: 88165
Generation: 5
New Best Solution Fitness: 88137
Generation: 6
New Best Solution Fitness: 88016
Generation: 7
New Best Solution Fitness: 87557
Generation: 8
New Best Solution Fitness: 87504
New Best Solution Fitness: 87493
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.811111 
Mean sub-tour choices: 1.43333 
Best Solution Fitness: 87493 
--------------------------------------------- 
