--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88475
New Best Solution Fitness: 88273
New Best Solution Fitness: 88268
Generation: 3
New Best Solution Fitness: 87710
Generation: 4
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 87427
New Best Solution Fitness: 87359
Generation: 10
New Best Solution Fitness: 87329
New Best Solution Fitness: 87247
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.444444 
Mean sub-tour choices: 0.755556 
Best Solution Fitness: 87247 
--------------------------------------------- 
