--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88884
New Best Solution Fitness: 88867
New Best Solution Fitness: 88836
Generation: 3
New Best Solution Fitness: 88290
New Best Solution Fitness: 88182
Generation: 4
New Best Solution Fitness: 88155
New Best Solution Fitness: 88091
Generation: 5
New Best Solution Fitness: 88003
Generation: 6
New Best Solution Fitness: 87976
New Best Solution Fitness: 87919
Generation: 7
New Best Solution Fitness: 87892
New Best Solution Fitness: 87887
Generation: 8
New Best Solution Fitness: 87883
New Best Solution Fitness: 87860
Generation: 9
New Best Solution Fitness: 87856
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.777778 
Mean sub-tour choices: 1.34444 
Best Solution Fitness: 87856 
--------------------------------------------- 
