--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88164
New Best Solution Fitness: 87929
Generation: 3
New Best Solution Fitness: 87881
New Best Solution Fitness: 87863
Generation: 4
New Best Solution Fitness: 87691
Generation: 5
New Best Solution Fitness: 87546
New Best Solution Fitness: 87524
New Best Solution Fitness: 87520
Generation: 6
New Best Solution Fitness: 87498
Generation: 7
Generation: 8
New Best Solution Fitness: 87484
Generation: 9
New Best Solution Fitness: 87416
New Best Solution Fitness: 87415
Generation: 10
New Best Solution Fitness: 87052
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.711111 
Mean sub-tour choices: 1.1 
Best Solution Fitness: 87052 
--------------------------------------------- 
