--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88872
Generation: 3
New Best Solution Fitness: 88836
New Best Solution Fitness: 88066
Generation: 4
New Best Solution Fitness: 88038
Generation: 5
New Best Solution Fitness: 87998
Generation: 6
Generation: 7
New Best Solution Fitness: 87908
Generation: 8
Generation: 9
New Best Solution Fitness: 87578
Generation: 10
New Best Solution Fitness: 87572
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.488889 
Mean sub-tour choices: 0.833333 
Best Solution Fitness: 87572 
--------------------------------------------- 
