--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88675
New Best Solution Fitness: 88645
New Best Solution Fitness: 88592
New Best Solution Fitness: 88566
Generation: 3
New Best Solution Fitness: 88478
New Best Solution Fitness: 88329
Generation: 4
New Best Solution Fitness: 88269
New Best Solution Fitness: 88217
Generation: 5
New Best Solution Fitness: 88065
Generation: 6
Generation: 7
New Best Solution Fitness: 88045
Generation: 8
Generation: 9
New Best Solution Fitness: 87696
New Best Solution Fitness: 87666
Generation: 10
New Best Solution Fitness: 87644
New Best Solution Fitness: 87614
New Best Solution Fitness: 87473
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.855556 
Mean sub-tour choices: 1.35556 
Best Solution Fitness: 87473 
--------------------------------------------- 
