--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87759
New Best Solution Fitness: 87720
Generation: 3
Generation: 4
New Best Solution Fitness: 87694
New Best Solution Fitness: 87655
Generation: 5
New Best Solution Fitness: 87611
New Best Solution Fitness: 87570
New Best Solution Fitness: 87552
Generation: 6
New Best Solution Fitness: 87545
Generation: 7
Generation: 8
New Best Solution Fitness: 87532
New Best Solution Fitness: 87530
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.8 
Mean sub-tour choices: 1.28889 
Best Solution Fitness: 87530 
--------------------------------------------- 
