--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88412
New Best Solution Fitness: 88293
New Best Solution Fitness: 88288
Generation: 3
New Best Solution Fitness: 88054
New Best Solution Fitness: 87966
New Best Solution Fitness: 87783
Generation: 4
New Best Solution Fitness: 87602
Generation: 5
New Best Solution Fitness: 87587
New Best Solution Fitness: 87571
Generation: 6
New Best Solution Fitness: 87559
New Best Solution Fitness: 87535
Generation: 7
Generation: 8
New Best Solution Fitness: 87451
Generation: 9
Generation: 10
New Best Solution Fitness: 87378
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.7 
Mean sub-tour choices: 1.11111 
Best Solution Fitness: 87378 
--------------------------------------------- 
