--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88151
New Best Solution Fitness: 88131
New Best Solution Fitness: 88061
Generation: 3
New Best Solution Fitness: 88038
Generation: 4
New Best Solution Fitness: 88033
Generation: 5
New Best Solution Fitness: 88015
Generation: 6
Generation: 7
New Best Solution Fitness: 87873
New Best Solution Fitness: 87868
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 87492
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.922222 
Mean sub-tour choices: 1.5 
Best Solution Fitness: 87492 
--------------------------------------------- 
