--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88243
New Best Solution Fitness: 88108
New Best Solution Fitness: 87927
Generation: 3
New Best Solution Fitness: 87846
New Best Solution Fitness: 87748
Generation: 4
New Best Solution Fitness: 87711
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 87700
Generation: 8
New Best Solution Fitness: 87697
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.13333 
Mean sub-tour choices: 1.71111 
Best Solution Fitness: 87697 
--------------------------------------------- 
