--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88975
New Best Solution Fitness: 88641
Generation: 3
New Best Solution Fitness: 88541
New Best Solution Fitness: 88535
New Best Solution Fitness: 88390
Generation: 4
New Best Solution Fitness: 88327
Generation: 5
New Best Solution Fitness: 88302
Generation: 6
New Best Solution Fitness: 88161
New Best Solution Fitness: 88155
New Best Solution Fitness: 88100
Generation: 7
New Best Solution Fitness: 87799
New Best Solution Fitness: 87782
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.766667 
Mean sub-tour choices: 1.24444 
Best Solution Fitness: 87782 
--------------------------------------------- 
