--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 89184
New Best Solution Fitness: 89068
New Best Solution Fitness: 88734
Generation: 3
New Best Solution Fitness: 88630
Generation: 4
New Best Solution Fitness: 88520
Generation: 5
New Best Solution Fitness: 88493
New Best Solution Fitness: 87723
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 87653
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.644444 
Mean sub-tour choices: 1.08889 
Best Solution Fitness: 87653 
--------------------------------------------- 
