--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88148
Generation: 3
New Best Solution Fitness: 87616
New Best Solution Fitness: 87542
Generation: 4
New Best Solution Fitness: 87419
Generation: 5
New Best Solution Fitness: 87331
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 87324
New Best Solution Fitness: 87304
Generation: 9
New Best Solution Fitness: 87263
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.544444 
Mean sub-tour choices: 0.933333 
Best Solution Fitness: 87263 
--------------------------------------------- 
