--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88471
New Best Solution Fitness: 88292
Generation: 3
New Best Solution Fitness: 88060
New Best Solution Fitness: 87952
Generation: 4
New Best Solution Fitness: 87850
New Best Solution Fitness: 87824
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 87759
Generation: 10
New Best Solution Fitness: 87605
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.444444 
Mean sub-tour choices: 0.744444 
Best Solution Fitness: 87605 
--------------------------------------------- 
