--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88510
New Best Solution Fitness: 88475
Generation: 3
New Best Solution Fitness: 88445
Generation: 4
New Best Solution Fitness: 88393
New Best Solution Fitness: 88363
Generation: 5
Generation: 6
New Best Solution Fitness: 88176
New Best Solution Fitness: 88157
Generation: 7
New Best Solution Fitness: 88013
Generation: 8
New Best Solution Fitness: 87983
New Best Solution Fitness: 87933
New Best Solution Fitness: 87798
Generation: 9
New Best Solution Fitness: 87232
New Best Solution Fitness: 87185
Generation: 10
New Best Solution Fitness: 87120
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.677778 
Mean sub-tour choices: 1.13333 
Best Solution Fitness: 87120 
--------------------------------------------- 
