--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87599
New Best Solution Fitness: 87592
Generation: 3
New Best Solution Fitness: 87496
Generation: 4
Generation: 5
New Best Solution Fitness: 87436
New Best Solution Fitness: 87410
Generation: 6
Generation: 7
New Best Solution Fitness: 87354
New Best Solution Fitness: 87328
Generation: 8
New Best Solution Fitness: 87316
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.744444 
Mean sub-tour choices: 1.24444 
Best Solution Fitness: 87316 
--------------------------------------------- 
