--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88347
New Best Solution Fitness: 88276
New Best Solution Fitness: 88213
Generation: 3
New Best Solution Fitness: 87777
Generation: 4
New Best Solution Fitness: 87740
New Best Solution Fitness: 87630
Generation: 5
New Best Solution Fitness: 87493
New Best Solution Fitness: 87400
Generation: 6
New Best Solution Fitness: 87215
Generation: 7
New Best Solution Fitness: 87204
Generation: 8
New Best Solution Fitness: 87169
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.866667 
Mean sub-tour choices: 1.3 
Best Solution Fitness: 87169 
--------------------------------------------- 
