--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88699
Generation: 3
New Best Solution Fitness: 88459
Generation: 4
New Best Solution Fitness: 88416
New Best Solution Fitness: 88415
Generation: 5
New Best Solution Fitness: 87618
New Best Solution Fitness: 87494
Generation: 6
New Best Solution Fitness: 87485
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.255556 
Mean sub-tour choices: 0.455556 
Best Solution Fitness: 87485 
--------------------------------------------- 
