--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 89559
New Best Solution Fitness: 89450
New Best Solution Fitness: 89434
New Best Solution Fitness: 89432
Generation: 3
New Best Solution Fitness: 88176
New Best Solution Fitness: 88097
Generation: 4
New Best Solution Fitness: 88081
Generation: 5
New Best Solution Fitness: 87803
New Best Solution Fitness: 87584
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 87399
New Best Solution Fitness: 87384
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.588889 
Mean sub-tour choices: 1.01111 
Best Solution Fitness: 87384 
--------------------------------------------- 
