--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87727
New Best Solution Fitness: 87633
Generation: 3
New Best Solution Fitness: 87404
Generation: 4
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 87394
New Best Solution Fitness: 87373
Generation: 8
New Best Solution Fitness: 87358
Generation: 9
New Best Solution Fitness: 87353
New Best Solution Fitness: 87270
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.5 
Mean sub-tour choices: 0.833333 
Best Solution Fitness: 87270 
--------------------------------------------- 
