--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88948
New Best Solution Fitness: 88146
Generation: 3
New Best Solution Fitness: 87876
Generation: 4
New Best Solution Fitness: 87700
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 87619
New Best Solution Fitness: 87591
Generation: 9
New Best Solution Fitness: 87424
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.477778 
Mean sub-tour choices: 0.811111 
Best Solution Fitness: 87424 
--------------------------------------------- 
