--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Black Box Steady State 
Population: 10
Mutation probability: 1
Crossover probability: 0.0020284
--------------------------
Job Complete 
Best Solution Fitness: 39404
Iterations: 2430490
--------------------------------------------- 
