--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 587764
New Best Solution Fitness: 586722
New Best Solution Fitness: 586537
Generation: 3
New Best Solution Fitness: 585215
New Best Solution Fitness: 585120
New Best Solution Fitness: 585005
Generation: 4
New Best Solution Fitness: 584367
New Best Solution Fitness: 584303
New Best Solution Fitness: 583969
Generation: 5
New Best Solution Fitness: 583905
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.42222 
Mean sub-tour choices: 5.4 
Best Solution Fitness: 583905 
--------------------------------------------- 
