--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 588861
New Best Solution Fitness: 588254
New Best Solution Fitness: 588046
New Best Solution Fitness: 587782
New Best Solution Fitness: 587547
Generation: 3
New Best Solution Fitness: 584936
New Best Solution Fitness: 584577
Generation: 4
New Best Solution Fitness: 583056
New Best Solution Fitness: 582967
New Best Solution Fitness: 582886
Generation: 5
New Best Solution Fitness: 582394
Generation: 6
New Best Solution Fitness: 582250
Generation: 7
New Best Solution Fitness: 582185
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 582138
New Best Solution Fitness: 582081
New Best Solution Fitness: 579960
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.55556 
Mean sub-tour choices: 4.34444 
Best Solution Fitness: 579960 
--------------------------------------------- 
