--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 594389
New Best Solution Fitness: 594083
New Best Solution Fitness: 593596
New Best Solution Fitness: 593522
Generation: 3
New Best Solution Fitness: 584589
New Best Solution Fitness: 584440
New Best Solution Fitness: 584205
New Best Solution Fitness: 584019
Generation: 4
New Best Solution Fitness: 582847
New Best Solution Fitness: 582833
New Best Solution Fitness: 582721
New Best Solution Fitness: 582683
Generation: 5
New Best Solution Fitness: 582599
New Best Solution Fitness: 582533
New Best Solution Fitness: 582490
Generation: 6
New Best Solution Fitness: 582370
New Best Solution Fitness: 582271
Generation: 7
New Best Solution Fitness: 581941
Generation: 8
New Best Solution Fitness: 581915
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.02222 
Mean sub-tour choices: 4.95556 
Best Solution Fitness: 581915 
--------------------------------------------- 
