--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 586142
New Best Solution Fitness: 585520
New Best Solution Fitness: 585229
New Best Solution Fitness: 585130
New Best Solution Fitness: 584893
New Best Solution Fitness: 584672
Generation: 3
New Best Solution Fitness: 583416
New Best Solution Fitness: 583360
New Best Solution Fitness: 583302
New Best Solution Fitness: 583280
New Best Solution Fitness: 583239
Generation: 4
New Best Solution Fitness: 582980
New Best Solution Fitness: 582961
Generation: 5
Generation: 6
New Best Solution Fitness: 582772
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.86667 
Mean sub-tour choices: 5.02222 
Best Solution Fitness: 582772 
--------------------------------------------- 
