--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 599763
New Best Solution Fitness: 599583
New Best Solution Fitness: 599486
Generation: 3
New Best Solution Fitness: 593020
New Best Solution Fitness: 592916
Generation: 4
New Best Solution Fitness: 588366
New Best Solution Fitness: 588354
Generation: 5
New Best Solution Fitness: 587006
Generation: 6
New Best Solution Fitness: 586970
Generation: 7
New Best Solution Fitness: 586465
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.67778 
Mean sub-tour choices: 3.46667 
Best Solution Fitness: 586465 
--------------------------------------------- 
