--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 585325
New Best Solution Fitness: 584912
New Best Solution Fitness: 584896
New Best Solution Fitness: 584888
New Best Solution Fitness: 584838
New Best Solution Fitness: 584649
Generation: 3
New Best Solution Fitness: 582214
New Best Solution Fitness: 582203
New Best Solution Fitness: 582193
Generation: 4
New Best Solution Fitness: 581773
New Best Solution Fitness: 581579
Generation: 5
New Best Solution Fitness: 581138
Generation: 6
Generation: 7
New Best Solution Fitness: 581073
Generation: 8
Generation: 9
New Best Solution Fitness: 579515
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.4 
Mean sub-tour choices: 3.11111 
Best Solution Fitness: 579515 
--------------------------------------------- 
