--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 599500
New Best Solution Fitness: 599415
New Best Solution Fitness: 599412
New Best Solution Fitness: 599150
New Best Solution Fitness: 599143
Generation: 3
New Best Solution Fitness: 594948
New Best Solution Fitness: 594914
New Best Solution Fitness: 594838
Generation: 4
New Best Solution Fitness: 592797
New Best Solution Fitness: 592591
Generation: 5
New Best Solution Fitness: 592041
New Best Solution Fitness: 591961
Generation: 6
New Best Solution Fitness: 591917
New Best Solution Fitness: 591883
Generation: 7
Generation: 8
New Best Solution Fitness: 591866
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.15556 
Mean sub-tour choices: 3.96667 
Best Solution Fitness: 591866 
--------------------------------------------- 
