--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 587545
New Best Solution Fitness: 587307
New Best Solution Fitness: 586992
New Best Solution Fitness: 586376
Generation: 3
New Best Solution Fitness: 584478
New Best Solution Fitness: 584168
New Best Solution Fitness: 584122
Generation: 4
New Best Solution Fitness: 583818
New Best Solution Fitness: 583764
Generation: 5
New Best Solution Fitness: 583724
Generation: 6
New Best Solution Fitness: 583462
New Best Solution Fitness: 583110
Generation: 7
New Best Solution Fitness: 582578
New Best Solution Fitness: 582235
Generation: 8
New Best Solution Fitness: 581726
New Best Solution Fitness: 581680
Generation: 9
New Best Solution Fitness: 581515
New Best Solution Fitness: 581512
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3 
Mean sub-tour choices: 4.01111 
Best Solution Fitness: 581512 
--------------------------------------------- 
