--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 587191
New Best Solution Fitness: 586632
Generation: 3
New Best Solution Fitness: 581014
New Best Solution Fitness: 580960
New Best Solution Fitness: 580580
Generation: 4
New Best Solution Fitness: 580035
New Best Solution Fitness: 579876
Generation: 5
New Best Solution Fitness: 579807
New Best Solution Fitness: 579766
Generation: 6
New Best Solution Fitness: 579688
New Best Solution Fitness: 579673
Generation: 7
New Best Solution Fitness: 579622
New Best Solution Fitness: 579581
Generation: 8
New Best Solution Fitness: 579470
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.94444 
Mean sub-tour choices: 5.4 
Best Solution Fitness: 579470 
--------------------------------------------- 
