--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 588201
New Best Solution Fitness: 587974
New Best Solution Fitness: 587567
New Best Solution Fitness: 587562
Generation: 3
New Best Solution Fitness: 584041
New Best Solution Fitness: 583991
New Best Solution Fitness: 583919
New Best Solution Fitness: 583418
New Best Solution Fitness: 583186
Generation: 4
New Best Solution Fitness: 582604
New Best Solution Fitness: 582537
New Best Solution Fitness: 582450
New Best Solution Fitness: 582170
Generation: 5
New Best Solution Fitness: 582138
New Best Solution Fitness: 582123
New Best Solution Fitness: 582079
New Best Solution Fitness: 582063
Generation: 6
New Best Solution Fitness: 580555
New Best Solution Fitness: 580500
New Best Solution Fitness: 580488
New Best Solution Fitness: 580432
Generation: 7
New Best Solution Fitness: 579675
New Best Solution Fitness: 579608
Generation: 8
New Best Solution Fitness: 579583
New Best Solution Fitness: 579524
Generation: 9
New Best Solution Fitness: 579442
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 5.83333 
Mean sub-tour choices: 6.9 
Best Solution Fitness: 579442 
--------------------------------------------- 
