--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 588546
New Best Solution Fitness: 588315
Generation: 3
New Best Solution Fitness: 584486
New Best Solution Fitness: 584253
New Best Solution Fitness: 584197
Generation: 4
New Best Solution Fitness: 582565
New Best Solution Fitness: 582333
New Best Solution Fitness: 580410
Generation: 5
New Best Solution Fitness: 579764
New Best Solution Fitness: 579478
Generation: 6
New Best Solution Fitness: 579098
Generation: 7
New Best Solution Fitness: 579070
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 578547
New Best Solution Fitness: 578446
New Best Solution Fitness: 577107
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.83333 
Mean sub-tour choices: 3.75556 
Best Solution Fitness: 577107 
--------------------------------------------- 
