--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 584671
New Best Solution Fitness: 584401
New Best Solution Fitness: 584152
New Best Solution Fitness: 584137
Generation: 3
New Best Solution Fitness: 582584
New Best Solution Fitness: 582542
New Best Solution Fitness: 582172
New Best Solution Fitness: 582135
New Best Solution Fitness: 581760
Generation: 4
New Best Solution Fitness: 579647
New Best Solution Fitness: 579600
Generation: 5
New Best Solution Fitness: 579548
New Best Solution Fitness: 579542
Generation: 6
New Best Solution Fitness: 579340
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.93333 
Mean sub-tour choices: 4.1 
Best Solution Fitness: 579340 
--------------------------------------------- 
