--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 598948
New Best Solution Fitness: 598484
New Best Solution Fitness: 598366
Generation: 3
New Best Solution Fitness: 588075
New Best Solution Fitness: 587853
New Best Solution Fitness: 587823
Generation: 4
New Best Solution Fitness: 582830
New Best Solution Fitness: 582805
Generation: 5
New Best Solution Fitness: 580460
New Best Solution Fitness: 580435
New Best Solution Fitness: 580406
New Best Solution Fitness: 580399
Generation: 6
New Best Solution Fitness: 579057
New Best Solution Fitness: 579049
New Best Solution Fitness: 579044
New Best Solution Fitness: 579017
Generation: 7
New Best Solution Fitness: 578976
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.54444 
Mean sub-tour choices: 4.37778 
Best Solution Fitness: 578976 
--------------------------------------------- 
