--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 588238
New Best Solution Fitness: 588035
New Best Solution Fitness: 587735
New Best Solution Fitness: 587687
New Best Solution Fitness: 587606
Generation: 3
New Best Solution Fitness: 583877
New Best Solution Fitness: 583813
New Best Solution Fitness: 583544
New Best Solution Fitness: 583506
New Best Solution Fitness: 583470
Generation: 4
New Best Solution Fitness: 583249
New Best Solution Fitness: 583197
Generation: 5
New Best Solution Fitness: 582933
New Best Solution Fitness: 582697
Generation: 6
New Best Solution Fitness: 582541
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 582096
New Best Solution Fitness: 582082
New Best Solution Fitness: 582055
New Best Solution Fitness: 582041
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.58889 
Mean sub-tour choices: 3.51111 
Best Solution Fitness: 582041 
--------------------------------------------- 
