--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 585272
New Best Solution Fitness: 584761
New Best Solution Fitness: 584421
Generation: 3
New Best Solution Fitness: 581185
New Best Solution Fitness: 581026
New Best Solution Fitness: 581013
New Best Solution Fitness: 580685
New Best Solution Fitness: 580466
Generation: 4
New Best Solution Fitness: 579298
New Best Solution Fitness: 579147
Generation: 5
New Best Solution Fitness: 579136
New Best Solution Fitness: 579104
Generation: 6
New Best Solution Fitness: 579093
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 579018
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.04444 
Mean sub-tour choices: 5.07778 
Best Solution Fitness: 579018 
--------------------------------------------- 
