--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 587520
New Best Solution Fitness: 587300
New Best Solution Fitness: 587097
New Best Solution Fitness: 586791
New Best Solution Fitness: 584203
Generation: 3
New Best Solution Fitness: 581103
New Best Solution Fitness: 580946
New Best Solution Fitness: 580722
Generation: 4
New Best Solution Fitness: 580334
New Best Solution Fitness: 580243
New Best Solution Fitness: 580229
Generation: 5
New Best Solution Fitness: 580061
Generation: 6
New Best Solution Fitness: 579933
New Best Solution Fitness: 579460
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.83333 
Mean sub-tour choices: 4.86667 
Best Solution Fitness: 579460 
--------------------------------------------- 
