--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 583016
New Best Solution Fitness: 582887
New Best Solution Fitness: 582655
New Best Solution Fitness: 582605
New Best Solution Fitness: 582436
Generation: 3
New Best Solution Fitness: 580868
New Best Solution Fitness: 580817
New Best Solution Fitness: 580776
New Best Solution Fitness: 580670
Generation: 4
New Best Solution Fitness: 580220
New Best Solution Fitness: 580209
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.34444 
Mean sub-tour choices: 3.14444 
Best Solution Fitness: 580209 
--------------------------------------------- 
