--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 589403
New Best Solution Fitness: 589254
New Best Solution Fitness: 589178
New Best Solution Fitness: 589176
Generation: 3
New Best Solution Fitness: 582694
New Best Solution Fitness: 582617
New Best Solution Fitness: 582546
Generation: 4
New Best Solution Fitness: 582044
New Best Solution Fitness: 581873
Generation: 5
Generation: 6
New Best Solution Fitness: 581460
New Best Solution Fitness: 581454
New Best Solution Fitness: 581429
Generation: 7
New Best Solution Fitness: 580967
New Best Solution Fitness: 580961
Generation: 8
New Best Solution Fitness: 580939
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.53333 
Mean sub-tour choices: 4.35556 
Best Solution Fitness: 580939 
--------------------------------------------- 
