--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 590673
New Best Solution Fitness: 590338
New Best Solution Fitness: 589890
New Best Solution Fitness: 589788
New Best Solution Fitness: 589450
Generation: 3
New Best Solution Fitness: 585112
New Best Solution Fitness: 585036
New Best Solution Fitness: 585031
Generation: 4
New Best Solution Fitness: 583774
New Best Solution Fitness: 583767
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.15556 
Mean sub-tour choices: 3 
Best Solution Fitness: 583767 
--------------------------------------------- 
