--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 584308
New Best Solution Fitness: 583550
New Best Solution Fitness: 582925
Generation: 3
New Best Solution Fitness: 581070
New Best Solution Fitness: 581018
New Best Solution Fitness: 580716
Generation: 4
New Best Solution Fitness: 579657
Generation: 5
New Best Solution Fitness: 579463
Generation: 6
Generation: 7
New Best Solution Fitness: 579281
Generation: 8
New Best Solution Fitness: 579127
New Best Solution Fitness: 578851
Generation: 9
New Best Solution Fitness: 578710
Generation: 10
New Best Solution Fitness: 578651
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.33333 
Mean sub-tour choices: 5.58889 
Best Solution Fitness: 578651 
--------------------------------------------- 
