--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 584763
New Best Solution Fitness: 583940
New Best Solution Fitness: 583853
Generation: 3
New Best Solution Fitness: 581691
New Best Solution Fitness: 581568
New Best Solution Fitness: 581555
New Best Solution Fitness: 581489
Generation: 4
New Best Solution Fitness: 581145
New Best Solution Fitness: 581097
New Best Solution Fitness: 581032
Generation: 5
New Best Solution Fitness: 580984
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 5.97778 
Mean sub-tour choices: 6.96667 
Best Solution Fitness: 580984 
--------------------------------------------- 
