--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 587982
New Best Solution Fitness: 587712
New Best Solution Fitness: 587677
New Best Solution Fitness: 587381
New Best Solution Fitness: 587321
Generation: 3
New Best Solution Fitness: 584135
New Best Solution Fitness: 583937
New Best Solution Fitness: 583791
Generation: 4
New Best Solution Fitness: 583332
New Best Solution Fitness: 583297
New Best Solution Fitness: 583273
Generation: 5
New Best Solution Fitness: 582740
New Best Solution Fitness: 582705
Generation: 6
New Best Solution Fitness: 582668
Generation: 7
New Best Solution Fitness: 582627
Generation: 8
New Best Solution Fitness: 582606
Generation: 9
Generation: 10
New Best Solution Fitness: 581482
New Best Solution Fitness: 581406
New Best Solution Fitness: 580857
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.02222 
Mean sub-tour choices: 4.27778 
Best Solution Fitness: 580857 
--------------------------------------------- 
