--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 587026
New Best Solution Fitness: 586340
New Best Solution Fitness: 586316
New Best Solution Fitness: 586262
Generation: 3
New Best Solution Fitness: 581571
New Best Solution Fitness: 581532
New Best Solution Fitness: 581367
New Best Solution Fitness: 581217
New Best Solution Fitness: 580227
Generation: 4
New Best Solution Fitness: 580052
New Best Solution Fitness: 580001
Generation: 5
New Best Solution Fitness: 579965
Generation: 6
Generation: 7
New Best Solution Fitness: 579586
New Best Solution Fitness: 579524
Generation: 8
New Best Solution Fitness: 579489
Generation: 9
New Best Solution Fitness: 579472
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.7 
Mean sub-tour choices: 4 
Best Solution Fitness: 579472 
--------------------------------------------- 
