--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 593086
New Best Solution Fitness: 592985
New Best Solution Fitness: 592888
New Best Solution Fitness: 592640
Generation: 3
New Best Solution Fitness: 585384
New Best Solution Fitness: 585295
New Best Solution Fitness: 585150
Generation: 4
New Best Solution Fitness: 582423
New Best Solution Fitness: 582390
Generation: 5
New Best Solution Fitness: 582232
New Best Solution Fitness: 582224
Generation: 6
New Best Solution Fitness: 582151
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.63333 
Mean sub-tour choices: 5.46667 
Best Solution Fitness: 582151 
--------------------------------------------- 
