--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 585949
New Best Solution Fitness: 585912
New Best Solution Fitness: 585204
Generation: 3
New Best Solution Fitness: 580028
New Best Solution Fitness: 580020
New Best Solution Fitness: 579998
New Best Solution Fitness: 579991
New Best Solution Fitness: 579904
Generation: 4
New Best Solution Fitness: 579521
New Best Solution Fitness: 579503
New Best Solution Fitness: 579157
New Best Solution Fitness: 578994
Generation: 5
New Best Solution Fitness: 578558
Generation: 6
New Best Solution Fitness: 578471
New Best Solution Fitness: 578468
Generation: 7
New Best Solution Fitness: 578446
New Best Solution Fitness: 578392
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.46667 
Mean sub-tour choices: 4.47778 
Best Solution Fitness: 578392 
--------------------------------------------- 
