--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 585743
New Best Solution Fitness: 584911
New Best Solution Fitness: 584816
New Best Solution Fitness: 584685
Generation: 3
New Best Solution Fitness: 581571
New Best Solution Fitness: 581511
New Best Solution Fitness: 581222
Generation: 4
New Best Solution Fitness: 580573
New Best Solution Fitness: 580544
Generation: 5
New Best Solution Fitness: 580539
New Best Solution Fitness: 580214
Generation: 6
New Best Solution Fitness: 580186
Generation: 7
New Best Solution Fitness: 580181
Generation: 8
New Best Solution Fitness: 580069
Generation: 9
New Best Solution Fitness: 579980
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 5.01111 
Mean sub-tour choices: 6.08889 
Best Solution Fitness: 579980 
--------------------------------------------- 
