--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 592570
New Best Solution Fitness: 592389
New Best Solution Fitness: 592072
New Best Solution Fitness: 592057
New Best Solution Fitness: 591906
Generation: 3
New Best Solution Fitness: 585672
New Best Solution Fitness: 585661
New Best Solution Fitness: 585529
Generation: 4
New Best Solution Fitness: 585009
New Best Solution Fitness: 584998
New Best Solution Fitness: 584571
Generation: 5
New Best Solution Fitness: 584286
New Best Solution Fitness: 584227
New Best Solution Fitness: 584089
Generation: 6
New Best Solution Fitness: 584049
Generation: 7
New Best Solution Fitness: 583956
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.73333 
Mean sub-tour choices: 4.64444 
Best Solution Fitness: 583956 
--------------------------------------------- 
