--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 592567
New Best Solution Fitness: 591725
New Best Solution Fitness: 591270
New Best Solution Fitness: 591238
Generation: 3
New Best Solution Fitness: 588179
New Best Solution Fitness: 588152
New Best Solution Fitness: 588040
Generation: 4
New Best Solution Fitness: 585999
New Best Solution Fitness: 585981
Generation: 5
New Best Solution Fitness: 584540
Generation: 6
New Best Solution Fitness: 584287
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 581931
New Best Solution Fitness: 581911
New Best Solution Fitness: 581832
New Best Solution Fitness: 581194
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.55556 
Mean sub-tour choices: 4.32222 
Best Solution Fitness: 581194 
--------------------------------------------- 
