--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 588154
New Best Solution Fitness: 587373
New Best Solution Fitness: 587118
Generation: 3
New Best Solution Fitness: 583107
New Best Solution Fitness: 582823
Generation: 4
New Best Solution Fitness: 580920
New Best Solution Fitness: 580681
New Best Solution Fitness: 580648
Generation: 5
New Best Solution Fitness: 580631
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 5.82222 
Mean sub-tour choices: 6.85556 
Best Solution Fitness: 580631 
--------------------------------------------- 
