--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 588380
New Best Solution Fitness: 588020
New Best Solution Fitness: 587920
New Best Solution Fitness: 587008
Generation: 3
New Best Solution Fitness: 583373
New Best Solution Fitness: 583287
New Best Solution Fitness: 583262
New Best Solution Fitness: 583226
Generation: 4
New Best Solution Fitness: 580725
New Best Solution Fitness: 580478
New Best Solution Fitness: 580345
Generation: 5
New Best Solution Fitness: 580173
New Best Solution Fitness: 580151
New Best Solution Fitness: 579700
Generation: 6
New Best Solution Fitness: 579678
Generation: 7
New Best Solution Fitness: 579670
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.24444 
Mean sub-tour choices: 5.71111 
Best Solution Fitness: 579670 
--------------------------------------------- 
