--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 590094
New Best Solution Fitness: 589828
New Best Solution Fitness: 589803
New Best Solution Fitness: 589760
New Best Solution Fitness: 589682
Generation: 3
New Best Solution Fitness: 587719
New Best Solution Fitness: 587440
Generation: 4
New Best Solution Fitness: 585997
New Best Solution Fitness: 585912
New Best Solution Fitness: 585864
Generation: 5
New Best Solution Fitness: 584317
New Best Solution Fitness: 584289
Generation: 6
New Best Solution Fitness: 584168
New Best Solution Fitness: 584039
Generation: 7
New Best Solution Fitness: 583510
New Best Solution Fitness: 583482
Generation: 8
New Best Solution Fitness: 583473
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.6 
Mean sub-tour choices: 4.74444 
Best Solution Fitness: 583473 
--------------------------------------------- 
