--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 119823
New Best Solution Fitness: 119491
New Best Solution Fitness: 119269
Generation: 3
Generation: 4
New Best Solution Fitness: 119238
New Best Solution Fitness: 119194
Generation: 5
New Best Solution Fitness: 118852
Generation: 6
Generation: 7
New Best Solution Fitness: 118662
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.155556 
Mean sub-tour choices: 0.177778 
Best Solution Fitness: 118662 
--------------------------------------------- 
