--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 118933
Generation: 3
New Best Solution Fitness: 118925
Generation: 4
Generation: 5
New Best Solution Fitness: 118845
Generation: 6
Generation: 7
New Best Solution Fitness: 118616
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.0444444 
Mean sub-tour choices: 0.0666667 
Best Solution Fitness: 118616 
--------------------------------------------- 
