--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 119851
New Best Solution Fitness: 119781
Generation: 3
Generation: 4
Generation: 5
New Best Solution Fitness: 119707
Generation: 6
New Best Solution Fitness: 119355
Generation: 7
New Best Solution Fitness: 119288
Generation: 8
New Best Solution Fitness: 119093
Generation: 9
New Best Solution Fitness: 118900
Generation: 10
New Best Solution Fitness: 118856
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.188889 
Mean sub-tour choices: 0.288889 
Best Solution Fitness: 118856 
--------------------------------------------- 
