--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 120385
Generation: 3
New Best Solution Fitness: 120312
Generation: 4
New Best Solution Fitness: 120311
Generation: 5
New Best Solution Fitness: 119894
Generation: 6
New Best Solution Fitness: 118856
New Best Solution Fitness: 118423
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.288889 
Mean sub-tour choices: 0.344444 
Best Solution Fitness: 118423 
--------------------------------------------- 
