--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 119903
New Best Solution Fitness: 119829
Generation: 3
New Best Solution Fitness: 119769
Generation: 4
New Best Solution Fitness: 119683
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 118715
Generation: 8
New Best Solution Fitness: 118682
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.122222 
Mean sub-tour choices: 0.2 
Best Solution Fitness: 118682 
--------------------------------------------- 
