--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 120077
New Best Solution Fitness: 119989
Generation: 3
New Best Solution Fitness: 119940
Generation: 4
New Best Solution Fitness: 119135
New Best Solution Fitness: 119102
New Best Solution Fitness: 119091
Generation: 5
New Best Solution Fitness: 119058
Generation: 6
New Best Solution Fitness: 119001
New Best Solution Fitness: 118780
Generation: 7
New Best Solution Fitness: 118616
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.244444 
Mean sub-tour choices: 0.344444 
Best Solution Fitness: 118616 
--------------------------------------------- 
