--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 120032
Generation: 3
New Best Solution Fitness: 119558
New Best Solution Fitness: 119525
New Best Solution Fitness: 119458
Generation: 4
New Best Solution Fitness: 119238
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 119223
Generation: 9
New Best Solution Fitness: 119064
Generation: 10
New Best Solution Fitness: 119054
New Best Solution Fitness: 118856
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.188889 
Mean sub-tour choices: 0.333333 
Best Solution Fitness: 118856 
--------------------------------------------- 
