--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
Generation: 3
Generation: 4
New Best Solution Fitness: 119064
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 118902
Generation: 8
New Best Solution Fitness: 118682
Generation: 9
Generation: 10
New Best Solution Fitness: 118616
New Best Solution Fitness: 118282
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.0333333 
Mean sub-tour choices: 0.0444444 
Best Solution Fitness: 118282 
--------------------------------------------- 
