--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 119346
Generation: 3
Generation: 4
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 118960
New Best Solution Fitness: 118944
New Best Solution Fitness: 118900
Generation: 8
New Best Solution Fitness: 118856
Generation: 9
New Best Solution Fitness: 118838
Generation: 10
New Best Solution Fitness: 118467
New Best Solution Fitness: 118423
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.188889 
Mean sub-tour choices: 0.277778 
Best Solution Fitness: 118423 
--------------------------------------------- 
