--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 120313
Generation: 3
New Best Solution Fitness: 120239
Generation: 4
New Best Solution Fitness: 119141
Generation: 5
Generation: 6
New Best Solution Fitness: 118497
New Best Solution Fitness: 118423
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.144444 
Mean sub-tour choices: 0.244444 
Best Solution Fitness: 118423 
--------------------------------------------- 
