--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 119400
Generation: 3
New Best Solution Fitness: 118856
New Best Solution Fitness: 118838
Generation: 4
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 118715
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.0333333 
Mean sub-tour choices: 0.0444444 
Best Solution Fitness: 118715 
--------------------------------------------- 
