--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 119440
New Best Solution Fitness: 119425
Generation: 3
New Best Solution Fitness: 119205
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 119058
Generation: 7
Generation: 8
New Best Solution Fitness: 118900
New Best Solution Fitness: 118856
Generation: 9
New Best Solution Fitness: 118682
Generation: 10
New Best Solution Fitness: 118423
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.322222 
Mean sub-tour choices: 0.355556 
Best Solution Fitness: 118423 
--------------------------------------------- 
