--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 120576
New Best Solution Fitness: 120413
Generation: 3
New Best Solution Fitness: 119790
Generation: 4
New Best Solution Fitness: 119695
New Best Solution Fitness: 119487
Generation: 5
New Best Solution Fitness: 119442
New Best Solution Fitness: 118815
Generation: 6
New Best Solution Fitness: 118689
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 118615
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.188889 
Mean sub-tour choices: 0.277778 
Best Solution Fitness: 118615 
--------------------------------------------- 
