--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 119419
Generation: 3
Generation: 4
New Best Solution Fitness: 119004
Generation: 5
Generation: 6
New Best Solution Fitness: 118944
Generation: 7
New Best Solution Fitness: 118932
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 118790
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.111111 
Mean sub-tour choices: 0.2 
Best Solution Fitness: 118790 
--------------------------------------------- 
