--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 120911
Generation: 3
New Best Solution Fitness: 120462
Generation: 4
New Best Solution Fitness: 119661
New Best Solution Fitness: 119630
New Best Solution Fitness: 119400
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 119279
Generation: 10
New Best Solution Fitness: 118497
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.4 
Mean sub-tour choices: 0.455556 
Best Solution Fitness: 118497 
--------------------------------------------- 
