--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 120176
Generation: 3
New Best Solution Fitness: 119191
New Best Solution Fitness: 119165
Generation: 4
New Best Solution Fitness: 119062
Generation: 5
Generation: 6
New Best Solution Fitness: 118970
New Best Solution Fitness: 118914
Generation: 7
Generation: 8
New Best Solution Fitness: 118759
Generation: 9
New Best Solution Fitness: 118616
Generation: 10
New Best Solution Fitness: 118423
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.144444 
Mean sub-tour choices: 0.155556 
Best Solution Fitness: 118423 
--------------------------------------------- 
