--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 120561
New Best Solution Fitness: 120487
Generation: 3
New Best Solution Fitness: 119400
Generation: 4
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 119379
Generation: 10
New Best Solution Fitness: 119020
New Best Solution Fitness: 118994
New Best Solution Fitness: 118579
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.255556 
Mean sub-tour choices: 0.333333 
Best Solution Fitness: 118579 
--------------------------------------------- 
