--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 118497
Generation: 3
Generation: 4
Generation: 5
New Best Solution Fitness: 118356
Generation: 6
New Best Solution Fitness: 118282
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.0888889 
Mean sub-tour choices: 0.133333 
Best Solution Fitness: 118282 
--------------------------------------------- 
