--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 119324
New Best Solution Fitness: 119312
New Best Solution Fitness: 119177
Generation: 3
New Best Solution Fitness: 119156
Generation: 4
New Best Solution Fitness: 118915
Generation: 5
New Best Solution Fitness: 118888
Generation: 6
New Best Solution Fitness: 118711
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 118662
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.155556 
Mean sub-tour choices: 0.277778 
Best Solution Fitness: 118662 
--------------------------------------------- 
