--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 119622
New Best Solution Fitness: 119578
New Best Solution Fitness: 119420
Generation: 3
New Best Solution Fitness: 119376
Generation: 4
New Best Solution Fitness: 119332
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 119064
Generation: 8
Generation: 9
New Best Solution Fitness: 118975
Generation: 10
New Best Solution Fitness: 118771
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.177778 
Mean sub-tour choices: 0.244444 
Best Solution Fitness: 118771 
--------------------------------------------- 
