--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 119225
Generation: 3
New Best Solution Fitness: 119221
Generation: 4
New Best Solution Fitness: 119062
Generation: 5
Generation: 6
New Best Solution Fitness: 118579
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0 
Mean sub-tour choices: 0 
Best Solution Fitness: 118579 
--------------------------------------------- 
