--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 120595
New Best Solution Fitness: 119689
Generation: 3
Generation: 4
New Best Solution Fitness: 119141
New Best Solution Fitness: 118947
Generation: 5
New Best Solution Fitness: 118682
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.211111 
Mean sub-tour choices: 0.222222 
Best Solution Fitness: 118682 
--------------------------------------------- 
