--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 119069
New Best Solution Fitness: 118780
Generation: 3
New Best Solution Fitness: 118715
New Best Solution Fitness: 118282
Generation: 4
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.266667 
Mean sub-tour choices: 0.388889 
Best Solution Fitness: 118282 
--------------------------------------------- 
