--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 119255
New Best Solution Fitness: 119195
Generation: 3
Generation: 4
Generation: 5
New Best Solution Fitness: 118856
Generation: 6
Generation: 7
New Best Solution Fitness: 118780
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 118616
New Best Solution Fitness: 118423
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.244444 
Mean sub-tour choices: 0.333333 
Best Solution Fitness: 118423 
--------------------------------------------- 
