--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 119683
Generation: 3
Generation: 4
New Best Solution Fitness: 119655
Generation: 5
New Best Solution Fitness: 119259
Generation: 6
Generation: 7
New Best Solution Fitness: 118955
New Best Solution Fitness: 118900
Generation: 8
New Best Solution Fitness: 118759
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.122222 
Mean sub-tour choices: 0.144444 
Best Solution Fitness: 118759 
--------------------------------------------- 
