--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 118764
Generation: 3
Generation: 4
New Best Solution Fitness: 118759
New Best Solution Fitness: 118715
Generation: 5
Generation: 6
New Best Solution Fitness: 118647
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 118616
Generation: 10
New Best Solution Fitness: 118579
New Best Solution Fitness: 118423
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.144444 
Mean sub-tour choices: 0.177778 
Best Solution Fitness: 118423 
--------------------------------------------- 
