--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 119541
Generation: 3
New Best Solution Fitness: 119400
Generation: 4
New Best Solution Fitness: 119399
New Best Solution Fitness: 119242
Generation: 5
New Best Solution Fitness: 118973
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 118715
Generation: 9
New Best Solution Fitness: 118682
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.255556 
Mean sub-tour choices: 0.277778 
Best Solution Fitness: 118682 
--------------------------------------------- 
