--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 120567
New Best Solution Fitness: 120509
Generation: 3
New Best Solution Fitness: 120264
Generation: 4
New Best Solution Fitness: 119855
New Best Solution Fitness: 119764
Generation: 5
New Best Solution Fitness: 119566
New Best Solution Fitness: 119514
Generation: 6
Generation: 7
New Best Solution Fitness: 119064
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 119008
New Best Solution Fitness: 119001
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.266667 
Mean sub-tour choices: 0.311111 
Best Solution Fitness: 119001 
--------------------------------------------- 
