--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 119626
Generation: 3
Generation: 4
Generation: 5
New Best Solution Fitness: 119519
Generation: 6
Generation: 7
New Best Solution Fitness: 119313
Generation: 8
New Best Solution Fitness: 118930
Generation: 9
New Best Solution Fitness: 118856
Generation: 10
New Best Solution Fitness: 118723
New Best Solution Fitness: 118616
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.0666667 
Mean sub-tour choices: 0.0888889 
Best Solution Fitness: 118616 
--------------------------------------------- 
