--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 119984
Generation: 3
New Best Solution Fitness: 119654
Generation: 4
New Best Solution Fitness: 119124
New Best Solution Fitness: 119064
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 118990
Generation: 9
Generation: 10
New Best Solution Fitness: 118873
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.0666667 
Mean sub-tour choices: 0.133333 
Best Solution Fitness: 118873 
--------------------------------------------- 
