--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 120195
Generation: 3
New Best Solution Fitness: 119223
New Best Solution Fitness: 119002
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 118959
New Best Solution Fitness: 118715
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 118584
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.355556 
Mean sub-tour choices: 0.422222 
Best Solution Fitness: 118584 
--------------------------------------------- 
