--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\usa13509.tsp
Algorithm: Black Box Steady State 
Population: 10
Mutation probability: 1
Crossover probability: 7.40247e-05
--------------------------
Job Complete 
Best Solution Fitness: 22742735
Iterations: 1824930810
--------------------------------------------- 
