--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Black Box Steady State 
Population: 10
Mutation probability: 1
Crossover probability: 0.000550358
--------------------------
Job Complete 
Best Solution Fitness: 67445
Iterations: 33014890
--------------------------------------------- 
