--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142232
New Best Solution Fitness: 142193
New Best Solution Fitness: 142190
New Best Solution Fitness: 142177
Generation: 3
New Best Solution Fitness: 141916
New Best Solution Fitness: 141867
Generation: 4
New Best Solution Fitness: 141755
New Best Solution Fitness: 141751
New Best Solution Fitness: 141681
Generation: 5
New Best Solution Fitness: 141680
Generation: 6
Generation: 7
New Best Solution Fitness: 141676
Generation: 8
New Best Solution Fitness: 141672
Generation: 9
New Best Solution Fitness: 141430
Generation: 10
New Best Solution Fitness: 141377
New Best Solution Fitness: 141296
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.36667 
Mean sub-tour choices: 3.12222 
Best Solution Fitness: 141296 
--------------------------------------------- 
