--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141686
New Best Solution Fitness: 141670
New Best Solution Fitness: 141577
Generation: 3
New Best Solution Fitness: 141268
New Best Solution Fitness: 141193
Generation: 4
New Best Solution Fitness: 141025
New Best Solution Fitness: 141015
New Best Solution Fitness: 140994
Generation: 5
New Best Solution Fitness: 140984
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 140971
New Best Solution Fitness: 140957
New Best Solution Fitness: 140940
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.38889 
Mean sub-tour choices: 4.05556 
Best Solution Fitness: 140940 
--------------------------------------------- 
