--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141667
New Best Solution Fitness: 141640
New Best Solution Fitness: 141624
New Best Solution Fitness: 141547
New Best Solution Fitness: 141545
New Best Solution Fitness: 141513
Generation: 3
New Best Solution Fitness: 141296
New Best Solution Fitness: 141277
New Best Solution Fitness: 141217
Generation: 4
New Best Solution Fitness: 141169
New Best Solution Fitness: 141168
New Best Solution Fitness: 141160
New Best Solution Fitness: 141149
Generation: 5
New Best Solution Fitness: 141047
New Best Solution Fitness: 141030
New Best Solution Fitness: 141019
Generation: 6
New Best Solution Fitness: 141015
New Best Solution Fitness: 141003
Generation: 7
Generation: 8
New Best Solution Fitness: 140999
Generation: 9
Generation: 10
New Best Solution Fitness: 140944
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.38889 
Mean sub-tour choices: 3.12222 
Best Solution Fitness: 140944 
--------------------------------------------- 
