--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142019
New Best Solution Fitness: 141873
New Best Solution Fitness: 141871
Generation: 3
New Best Solution Fitness: 141377
New Best Solution Fitness: 141334
New Best Solution Fitness: 141297
New Best Solution Fitness: 141294
Generation: 4
New Best Solution Fitness: 141232
New Best Solution Fitness: 141227
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 141065
Generation: 8
New Best Solution Fitness: 140945
New Best Solution Fitness: 140892
Generation: 9
New Best Solution Fitness: 140890
New Best Solution Fitness: 140854
Generation: 10
New Best Solution Fitness: 140800
New Best Solution Fitness: 140797
New Best Solution Fitness: 140794
New Best Solution Fitness: 140787
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.92222 
Mean sub-tour choices: 3.7 
Best Solution Fitness: 140787 
--------------------------------------------- 
