--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142051
New Best Solution Fitness: 141919
New Best Solution Fitness: 141775
Generation: 3
New Best Solution Fitness: 141451
New Best Solution Fitness: 141395
New Best Solution Fitness: 141386
New Best Solution Fitness: 141350
Generation: 4
New Best Solution Fitness: 141318
New Best Solution Fitness: 141311
New Best Solution Fitness: 141287
Generation: 5
New Best Solution Fitness: 141213
Generation: 6
Generation: 7
New Best Solution Fitness: 141189
Generation: 8
New Best Solution Fitness: 141159
New Best Solution Fitness: 141133
New Best Solution Fitness: 141114
Generation: 9
New Best Solution Fitness: 141040
New Best Solution Fitness: 141032
New Best Solution Fitness: 141019
Generation: 10
New Best Solution Fitness: 141011
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.9 
Mean sub-tour choices: 4.74444 
Best Solution Fitness: 141011 
--------------------------------------------- 
