--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142096
New Best Solution Fitness: 142058
New Best Solution Fitness: 142032
Generation: 3
New Best Solution Fitness: 141661
New Best Solution Fitness: 141603
Generation: 4
New Best Solution Fitness: 141423
New Best Solution Fitness: 141381
Generation: 5
New Best Solution Fitness: 141346
Generation: 6
New Best Solution Fitness: 141328
Generation: 7
Generation: 8
New Best Solution Fitness: 141322
Generation: 9
Generation: 10
New Best Solution Fitness: 141220
New Best Solution Fitness: 141194
New Best Solution Fitness: 141037
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.07778 
Mean sub-tour choices: 3.81111 
Best Solution Fitness: 141037 
--------------------------------------------- 
