--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141377
New Best Solution Fitness: 141363
New Best Solution Fitness: 141272
Generation: 3
New Best Solution Fitness: 140996
New Best Solution Fitness: 140899
New Best Solution Fitness: 140882
New Best Solution Fitness: 140668
Generation: 4
New Best Solution Fitness: 140571
New Best Solution Fitness: 140555
New Best Solution Fitness: 140457
Generation: 5
New Best Solution Fitness: 140398
New Best Solution Fitness: 140382
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 140337
Generation: 9
Generation: 10
New Best Solution Fitness: 140181
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.95556 
Mean sub-tour choices: 2.61111 
Best Solution Fitness: 140181 
--------------------------------------------- 
