--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141933
New Best Solution Fitness: 141890
New Best Solution Fitness: 141864
New Best Solution Fitness: 141783
Generation: 3
New Best Solution Fitness: 141392
New Best Solution Fitness: 141366
Generation: 4
New Best Solution Fitness: 141131
New Best Solution Fitness: 141130
Generation: 5
New Best Solution Fitness: 141119
New Best Solution Fitness: 141047
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.24444 
Mean sub-tour choices: 4.03333 
Best Solution Fitness: 141047 
--------------------------------------------- 
