--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141497
New Best Solution Fitness: 141229
New Best Solution Fitness: 141228
New Best Solution Fitness: 141124
Generation: 3
New Best Solution Fitness: 140976
New Best Solution Fitness: 140963
New Best Solution Fitness: 140939
New Best Solution Fitness: 140901
New Best Solution Fitness: 140885
Generation: 4
New Best Solution Fitness: 140862
New Best Solution Fitness: 140842
Generation: 5
New Best Solution Fitness: 140841
New Best Solution Fitness: 140839
New Best Solution Fitness: 140837
Generation: 6
New Best Solution Fitness: 140834
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.81111 
Mean sub-tour choices: 5.71111 
Best Solution Fitness: 140834 
--------------------------------------------- 
