--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141528
New Best Solution Fitness: 141447
Generation: 3
New Best Solution Fitness: 141183
New Best Solution Fitness: 141182
New Best Solution Fitness: 141170
Generation: 4
New Best Solution Fitness: 141132
New Best Solution Fitness: 141102
Generation: 5
New Best Solution Fitness: 141080
Generation: 6
New Best Solution Fitness: 141046
Generation: 7
New Best Solution Fitness: 141027
New Best Solution Fitness: 141015
New Best Solution Fitness: 140941
Generation: 8
New Best Solution Fitness: 140929
Generation: 9
New Best Solution Fitness: 140928
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.57778 
Mean sub-tour choices: 2.24444 
Best Solution Fitness: 140928 
--------------------------------------------- 
