--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 143058
New Best Solution Fitness: 143041
New Best Solution Fitness: 143023
New Best Solution Fitness: 142935
New Best Solution Fitness: 142703
Generation: 3
New Best Solution Fitness: 142033
New Best Solution Fitness: 141911
New Best Solution Fitness: 141547
Generation: 4
New Best Solution Fitness: 140859
New Best Solution Fitness: 140839
New Best Solution Fitness: 140809
Generation: 5
New Best Solution Fitness: 140714
New Best Solution Fitness: 140694
Generation: 6
New Best Solution Fitness: 140671
New Best Solution Fitness: 140667
Generation: 7
New Best Solution Fitness: 140656
Generation: 8
New Best Solution Fitness: 140648
New Best Solution Fitness: 140645
Generation: 9
New Best Solution Fitness: 140637
Generation: 10
New Best Solution Fitness: 140636
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.66667 
Mean sub-tour choices: 3.36667 
Best Solution Fitness: 140636 
--------------------------------------------- 
