--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141927
New Best Solution Fitness: 141830
New Best Solution Fitness: 141791
New Best Solution Fitness: 141783
Generation: 3
New Best Solution Fitness: 141187
New Best Solution Fitness: 141147
Generation: 4
New Best Solution Fitness: 141094
New Best Solution Fitness: 141080
Generation: 5
New Best Solution Fitness: 141072
New Best Solution Fitness: 141070
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 140925
New Best Solution Fitness: 140908
New Best Solution Fitness: 140895
Generation: 9
New Best Solution Fitness: 140876
Generation: 10
New Best Solution Fitness: 140856
New Best Solution Fitness: 140846
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.01111 
Mean sub-tour choices: 4.78889 
Best Solution Fitness: 140846 
--------------------------------------------- 
