--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141537
New Best Solution Fitness: 141485
New Best Solution Fitness: 141466
New Best Solution Fitness: 141450
Generation: 3
New Best Solution Fitness: 141301
New Best Solution Fitness: 141223
Generation: 4
New Best Solution Fitness: 141196
Generation: 5
New Best Solution Fitness: 141180
New Best Solution Fitness: 141152
New Best Solution Fitness: 141120
Generation: 6
New Best Solution Fitness: 141105
New Best Solution Fitness: 141104
New Best Solution Fitness: 141086
Generation: 7
New Best Solution Fitness: 140922
New Best Solution Fitness: 140805
Generation: 8
New Best Solution Fitness: 140796
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.93333 
Mean sub-tour choices: 2.51111 
Best Solution Fitness: 140796 
--------------------------------------------- 
