--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141918
New Best Solution Fitness: 141833
New Best Solution Fitness: 141759
Generation: 3
New Best Solution Fitness: 141582
New Best Solution Fitness: 141578
New Best Solution Fitness: 141563
New Best Solution Fitness: 141551
New Best Solution Fitness: 141507
Generation: 4
New Best Solution Fitness: 141468
New Best Solution Fitness: 141465
Generation: 5
New Best Solution Fitness: 141445
Generation: 6
New Best Solution Fitness: 141444
New Best Solution Fitness: 141376
Generation: 7
New Best Solution Fitness: 141371
Generation: 8
New Best Solution Fitness: 141319
Generation: 9
New Best Solution Fitness: 141248
New Best Solution Fitness: 141246
New Best Solution Fitness: 141218
New Best Solution Fitness: 141168
Generation: 10
New Best Solution Fitness: 141072
New Best Solution Fitness: 141061
New Best Solution Fitness: 141034
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.36667 
Mean sub-tour choices: 3.08889 
Best Solution Fitness: 141034 
--------------------------------------------- 
