--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141626
New Best Solution Fitness: 141550
New Best Solution Fitness: 141521
Generation: 3
New Best Solution Fitness: 141420
New Best Solution Fitness: 141376
Generation: 4
New Best Solution Fitness: 141349
Generation: 5
New Best Solution Fitness: 141252
New Best Solution Fitness: 141225
Generation: 6
New Best Solution Fitness: 141224
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 141195
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.81111 
Mean sub-tour choices: 4.58889 
Best Solution Fitness: 141195 
--------------------------------------------- 
