--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142115
New Best Solution Fitness: 141966
New Best Solution Fitness: 141870
New Best Solution Fitness: 141855
Generation: 3
New Best Solution Fitness: 141205
New Best Solution Fitness: 141107
New Best Solution Fitness: 141103
Generation: 4
New Best Solution Fitness: 140975
New Best Solution Fitness: 140974
Generation: 5
New Best Solution Fitness: 140953
New Best Solution Fitness: 140933
Generation: 6
New Best Solution Fitness: 140912
Generation: 7
New Best Solution Fitness: 140880
Generation: 8
New Best Solution Fitness: 140791
New Best Solution Fitness: 140776
Generation: 9
New Best Solution Fitness: 140740
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.37778 
Mean sub-tour choices: 4.07778 
Best Solution Fitness: 140740 
--------------------------------------------- 
