--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141424
New Best Solution Fitness: 141354
Generation: 3
New Best Solution Fitness: 141296
New Best Solution Fitness: 141292
New Best Solution Fitness: 141223
Generation: 4
New Best Solution Fitness: 141222
New Best Solution Fitness: 141213
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 141175
New Best Solution Fitness: 141166
Generation: 8
New Best Solution Fitness: 141145
Generation: 9
Generation: 10
New Best Solution Fitness: 141141
New Best Solution Fitness: 141123
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.31111 
Mean sub-tour choices: 3 
Best Solution Fitness: 141123 
--------------------------------------------- 
