--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141996
New Best Solution Fitness: 141914
New Best Solution Fitness: 141882
Generation: 3
New Best Solution Fitness: 141626
New Best Solution Fitness: 141598
New Best Solution Fitness: 141581
Generation: 4
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 141561
Generation: 10
New Best Solution Fitness: 141551
New Best Solution Fitness: 141543
New Best Solution Fitness: 141531
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.22222 
Mean sub-tour choices: 2.8 
Best Solution Fitness: 141531 
--------------------------------------------- 
