--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141515
New Best Solution Fitness: 141470
New Best Solution Fitness: 141460
New Best Solution Fitness: 141454
Generation: 3
New Best Solution Fitness: 141150
New Best Solution Fitness: 141134
New Best Solution Fitness: 141121
New Best Solution Fitness: 141096
Generation: 4
New Best Solution Fitness: 141081
New Best Solution Fitness: 141065
Generation: 5
New Best Solution Fitness: 141055
New Best Solution Fitness: 141050
Generation: 6
New Best Solution Fitness: 141045
New Best Solution Fitness: 141040
Generation: 7
New Best Solution Fitness: 141035
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 141026
New Best Solution Fitness: 140993
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.06667 
Mean sub-tour choices: 3.81111 
Best Solution Fitness: 140993 
--------------------------------------------- 
