--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142198
New Best Solution Fitness: 142158
New Best Solution Fitness: 142127
New Best Solution Fitness: 142104
New Best Solution Fitness: 142072
Generation: 3
New Best Solution Fitness: 141831
New Best Solution Fitness: 141751
New Best Solution Fitness: 141421
Generation: 4
New Best Solution Fitness: 141341
Generation: 5
Generation: 6
New Best Solution Fitness: 141257
New Best Solution Fitness: 141208
Generation: 7
New Best Solution Fitness: 141134
Generation: 8
New Best Solution Fitness: 141132
Generation: 9
New Best Solution Fitness: 141046
New Best Solution Fitness: 140963
Generation: 10
New Best Solution Fitness: 140877
New Best Solution Fitness: 140797
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.77778 
Mean sub-tour choices: 2.41111 
Best Solution Fitness: 140797 
--------------------------------------------- 
