--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142065
New Best Solution Fitness: 142043
New Best Solution Fitness: 142020
New Best Solution Fitness: 142012
New Best Solution Fitness: 141991
Generation: 3
New Best Solution Fitness: 141893
New Best Solution Fitness: 141876
New Best Solution Fitness: 141870
Generation: 4
New Best Solution Fitness: 141866
New Best Solution Fitness: 141853
New Best Solution Fitness: 141790
Generation: 5
New Best Solution Fitness: 141786
New Best Solution Fitness: 141773
Generation: 6
New Best Solution Fitness: 141767
New Best Solution Fitness: 141750
Generation: 7
New Best Solution Fitness: 141313
New Best Solution Fitness: 141296
Generation: 8
New Best Solution Fitness: 141292
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.05556 
Mean sub-tour choices: 3.9 
Best Solution Fitness: 141292 
--------------------------------------------- 
