--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142052
New Best Solution Fitness: 142012
New Best Solution Fitness: 141972
New Best Solution Fitness: 141902
Generation: 3
New Best Solution Fitness: 141808
New Best Solution Fitness: 141805
New Best Solution Fitness: 141541
Generation: 4
New Best Solution Fitness: 141360
New Best Solution Fitness: 141353
New Best Solution Fitness: 141330
Generation: 5
New Best Solution Fitness: 141257
Generation: 6
New Best Solution Fitness: 141013
New Best Solution Fitness: 140964
Generation: 7
New Best Solution Fitness: 140903
Generation: 8
New Best Solution Fitness: 140885
New Best Solution Fitness: 140854
Generation: 9
New Best Solution Fitness: 140833
Generation: 10
New Best Solution Fitness: 140824
New Best Solution Fitness: 140819
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.28889 
Mean sub-tour choices: 4.04444 
Best Solution Fitness: 140819 
--------------------------------------------- 
