--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141579
New Best Solution Fitness: 141531
New Best Solution Fitness: 141487
Generation: 3
New Best Solution Fitness: 141041
New Best Solution Fitness: 141032
New Best Solution Fitness: 141021
Generation: 4
New Best Solution Fitness: 140989
New Best Solution Fitness: 140988
New Best Solution Fitness: 140982
Generation: 5
New Best Solution Fitness: 140980
New Best Solution Fitness: 140979
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 140966
New Best Solution Fitness: 140963
Generation: 9
New Best Solution Fitness: 140925
New Best Solution Fitness: 140924
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.34444 
Mean sub-tour choices: 4.16667 
Best Solution Fitness: 140924 
--------------------------------------------- 
