--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142178
New Best Solution Fitness: 142159
New Best Solution Fitness: 142140
New Best Solution Fitness: 142130
Generation: 3
New Best Solution Fitness: 141852
New Best Solution Fitness: 141824
New Best Solution Fitness: 141817
Generation: 4
New Best Solution Fitness: 141811
Generation: 5
New Best Solution Fitness: 141788
New Best Solution Fitness: 141787
New Best Solution Fitness: 141774
New Best Solution Fitness: 141722
Generation: 6
New Best Solution Fitness: 141717
New Best Solution Fitness: 141690
Generation: 7
New Best Solution Fitness: 141463
New Best Solution Fitness: 141447
Generation: 8
New Best Solution Fitness: 141437
Generation: 9
New Best Solution Fitness: 141424
Generation: 10
New Best Solution Fitness: 141384
New Best Solution Fitness: 141371
New Best Solution Fitness: 141339
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.48889 
Mean sub-tour choices: 2.14444 
Best Solution Fitness: 141339 
--------------------------------------------- 
