--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142533
New Best Solution Fitness: 142398
New Best Solution Fitness: 142356
Generation: 3
New Best Solution Fitness: 141855
New Best Solution Fitness: 141851
New Best Solution Fitness: 141820
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 141811
New Best Solution Fitness: 141806
Generation: 7
New Best Solution Fitness: 141693
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 141638
New Best Solution Fitness: 141273
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.11111 
Mean sub-tour choices: 3.82222 
Best Solution Fitness: 141273 
--------------------------------------------- 
