--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142291
New Best Solution Fitness: 142248
New Best Solution Fitness: 142231
Generation: 3
New Best Solution Fitness: 141559
New Best Solution Fitness: 141545
New Best Solution Fitness: 141544
Generation: 4
New Best Solution Fitness: 141491
New Best Solution Fitness: 141475
Generation: 5
New Best Solution Fitness: 141294
New Best Solution Fitness: 141278
New Best Solution Fitness: 141262
Generation: 6
New Best Solution Fitness: 141198
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 141169
New Best Solution Fitness: 141111
Generation: 10
New Best Solution Fitness: 141036
New Best Solution Fitness: 141027
New Best Solution Fitness: 140992
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.81111 
Mean sub-tour choices: 2.46667 
Best Solution Fitness: 140992 
--------------------------------------------- 
