--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142016
New Best Solution Fitness: 141969
New Best Solution Fitness: 141956
New Best Solution Fitness: 141886
Generation: 3
New Best Solution Fitness: 141128
New Best Solution Fitness: 141109
New Best Solution Fitness: 141105
Generation: 4
New Best Solution Fitness: 141062
New Best Solution Fitness: 140942
Generation: 5
New Best Solution Fitness: 140916
Generation: 6
New Best Solution Fitness: 140829
New Best Solution Fitness: 140825
New Best Solution Fitness: 140803
New Best Solution Fitness: 140768
Generation: 7
New Best Solution Fitness: 140759
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.11111 
Mean sub-tour choices: 3.84444 
Best Solution Fitness: 140759 
--------------------------------------------- 
