--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141818
New Best Solution Fitness: 141747
New Best Solution Fitness: 141724
New Best Solution Fitness: 141679
Generation: 3
New Best Solution Fitness: 141615
New Best Solution Fitness: 141611
Generation: 4
New Best Solution Fitness: 141319
New Best Solution Fitness: 141312
Generation: 5
New Best Solution Fitness: 141301
New Best Solution Fitness: 141295
New Best Solution Fitness: 141267
Generation: 6
New Best Solution Fitness: 141261
Generation: 7
Generation: 8
New Best Solution Fitness: 141214
Generation: 9
New Best Solution Fitness: 141212
Generation: 10
New Best Solution Fitness: 141204
New Best Solution Fitness: 141187
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.33333 
Mean sub-tour choices: 3.02222 
Best Solution Fitness: 141187 
--------------------------------------------- 
