--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 143126
New Best Solution Fitness: 142960
New Best Solution Fitness: 142943
New Best Solution Fitness: 142938
New Best Solution Fitness: 142933
Generation: 3
New Best Solution Fitness: 141673
New Best Solution Fitness: 141631
New Best Solution Fitness: 141620
Generation: 4
New Best Solution Fitness: 141545
New Best Solution Fitness: 141529
Generation: 5
New Best Solution Fitness: 141332
New Best Solution Fitness: 141316
Generation: 6
New Best Solution Fitness: 141315
New Best Solution Fitness: 141312
New Best Solution Fitness: 141311
New Best Solution Fitness: 141217
Generation: 7
New Best Solution Fitness: 141214
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 141185
New Best Solution Fitness: 141177
New Best Solution Fitness: 141101
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.76667 
Mean sub-tour choices: 5.64444 
Best Solution Fitness: 141101 
--------------------------------------------- 
