--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141599
New Best Solution Fitness: 141562
New Best Solution Fitness: 141530
New Best Solution Fitness: 141259
Generation: 3
New Best Solution Fitness: 141166
New Best Solution Fitness: 141165
New Best Solution Fitness: 141103
Generation: 4
New Best Solution Fitness: 141098
New Best Solution Fitness: 141041
Generation: 5
New Best Solution Fitness: 140925
New Best Solution Fitness: 140916
Generation: 6
Generation: 7
New Best Solution Fitness: 140890
Generation: 8
New Best Solution Fitness: 140888
Generation: 9
New Best Solution Fitness: 140773
New Best Solution Fitness: 140771
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.56667 
Mean sub-tour choices: 3.28889 
Best Solution Fitness: 140771 
--------------------------------------------- 
