--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141446
New Best Solution Fitness: 141406
New Best Solution Fitness: 141323
New Best Solution Fitness: 141261
Generation: 3
New Best Solution Fitness: 141186
New Best Solution Fitness: 141172
New Best Solution Fitness: 141148
Generation: 4
New Best Solution Fitness: 141107
Generation: 5
New Best Solution Fitness: 141093
Generation: 6
Generation: 7
New Best Solution Fitness: 141041
New Best Solution Fitness: 140948
New Best Solution Fitness: 140929
Generation: 8
Generation: 9
New Best Solution Fitness: 140924
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.45556 
Mean sub-tour choices: 3.21111 
Best Solution Fitness: 140924 
--------------------------------------------- 
