--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142410
New Best Solution Fitness: 142294
New Best Solution Fitness: 142274
Generation: 3
New Best Solution Fitness: 142130
New Best Solution Fitness: 142116
New Best Solution Fitness: 142074
Generation: 4
New Best Solution Fitness: 142069
New Best Solution Fitness: 142068
New Best Solution Fitness: 142028
Generation: 5
New Best Solution Fitness: 142027
New Best Solution Fitness: 142021
New Best Solution Fitness: 142009
Generation: 6
New Best Solution Fitness: 142008
New Best Solution Fitness: 142002
New Best Solution Fitness: 141983
Generation: 7
New Best Solution Fitness: 141978
New Best Solution Fitness: 141977
New Best Solution Fitness: 141971
Generation: 8
New Best Solution Fitness: 141960
New Best Solution Fitness: 141959
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.72222 
Mean sub-tour choices: 4.56667 
Best Solution Fitness: 141959 
--------------------------------------------- 
