--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142323
New Best Solution Fitness: 142268
New Best Solution Fitness: 142261
New Best Solution Fitness: 142231
New Best Solution Fitness: 142148
Generation: 3
New Best Solution Fitness: 141897
New Best Solution Fitness: 141864
New Best Solution Fitness: 141838
Generation: 4
New Best Solution Fitness: 141615
Generation: 5
Generation: 6
New Best Solution Fitness: 141576
Generation: 7
New Best Solution Fitness: 141205
New Best Solution Fitness: 141191
Generation: 8
New Best Solution Fitness: 141109
New Best Solution Fitness: 141082
Generation: 9
New Best Solution Fitness: 141080
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.43333 
Mean sub-tour choices: 3.11111 
Best Solution Fitness: 141080 
--------------------------------------------- 
