--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142416
New Best Solution Fitness: 142334
New Best Solution Fitness: 142331
New Best Solution Fitness: 142297
New Best Solution Fitness: 142289
New Best Solution Fitness: 142285
Generation: 3
New Best Solution Fitness: 141777
New Best Solution Fitness: 141760
New Best Solution Fitness: 141754
Generation: 4
New Best Solution Fitness: 141691
New Best Solution Fitness: 141686
New Best Solution Fitness: 141668
Generation: 5
New Best Solution Fitness: 141621
Generation: 6
New Best Solution Fitness: 141604
Generation: 7
Generation: 8
New Best Solution Fitness: 141278
New Best Solution Fitness: 141267
New Best Solution Fitness: 141251
Generation: 9
New Best Solution Fitness: 141243
New Best Solution Fitness: 141232
Generation: 10
New Best Solution Fitness: 141190
New Best Solution Fitness: 141183
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.85556 
Mean sub-tour choices: 2.44444 
Best Solution Fitness: 141183 
--------------------------------------------- 
