--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142122
New Best Solution Fitness: 142070
New Best Solution Fitness: 142062
New Best Solution Fitness: 142049
New Best Solution Fitness: 142037
Generation: 3
New Best Solution Fitness: 141932
New Best Solution Fitness: 141914
New Best Solution Fitness: 141909
Generation: 4
New Best Solution Fitness: 141900
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 141823
Generation: 8
Generation: 9
New Best Solution Fitness: 141611
New Best Solution Fitness: 141581
Generation: 10
New Best Solution Fitness: 141433
New Best Solution Fitness: 141403
New Best Solution Fitness: 141365
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.64444 
Mean sub-tour choices: 3.38889 
Best Solution Fitness: 141365 
--------------------------------------------- 
