--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141892
New Best Solution Fitness: 141862
New Best Solution Fitness: 141710
Generation: 3
New Best Solution Fitness: 141457
New Best Solution Fitness: 141431
New Best Solution Fitness: 141424
Generation: 4
New Best Solution Fitness: 141408
New Best Solution Fitness: 141367
Generation: 5
New Best Solution Fitness: 141309
New Best Solution Fitness: 141308
Generation: 6
New Best Solution Fitness: 141162
Generation: 7
New Best Solution Fitness: 141159
Generation: 8
New Best Solution Fitness: 141019
New Best Solution Fitness: 140978
Generation: 9
Generation: 10
New Best Solution Fitness: 140887
New Best Solution Fitness: 140854
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.75556 
Mean sub-tour choices: 2.5 
Best Solution Fitness: 140854 
--------------------------------------------- 
