--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141829
New Best Solution Fitness: 141799
New Best Solution Fitness: 141776
Generation: 3
New Best Solution Fitness: 141491
New Best Solution Fitness: 141481
New Best Solution Fitness: 141398
Generation: 4
New Best Solution Fitness: 141381
New Best Solution Fitness: 141321
Generation: 5
New Best Solution Fitness: 141306
New Best Solution Fitness: 141296
New Best Solution Fitness: 141289
Generation: 6
New Best Solution Fitness: 141267
Generation: 7
Generation: 8
New Best Solution Fitness: 141244
New Best Solution Fitness: 141231
Generation: 9
New Best Solution Fitness: 141073
New Best Solution Fitness: 141058
New Best Solution Fitness: 141057
New Best Solution Fitness: 141037
Generation: 10
New Best Solution Fitness: 141007
New Best Solution Fitness: 140992
New Best Solution Fitness: 140991
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.35556 
Mean sub-tour choices: 3.03333 
Best Solution Fitness: 140991 
--------------------------------------------- 
