--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141402
New Best Solution Fitness: 141222
Generation: 3
New Best Solution Fitness: 141133
New Best Solution Fitness: 141112
Generation: 4
New Best Solution Fitness: 140937
New Best Solution Fitness: 140918
New Best Solution Fitness: 140916
Generation: 5
New Best Solution Fitness: 140684
Generation: 6
New Best Solution Fitness: 140664
New Best Solution Fitness: 140645
Generation: 7
Generation: 8
New Best Solution Fitness: 140630
Generation: 9
New Best Solution Fitness: 140597
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.73333 
Mean sub-tour choices: 2.38889 
Best Solution Fitness: 140597 
--------------------------------------------- 
