--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142641
New Best Solution Fitness: 142604
New Best Solution Fitness: 142591
New Best Solution Fitness: 142545
Generation: 3
New Best Solution Fitness: 141316
New Best Solution Fitness: 141294
New Best Solution Fitness: 141182
Generation: 4
New Best Solution Fitness: 141145
New Best Solution Fitness: 141100
Generation: 5
New Best Solution Fitness: 141092
Generation: 6
New Best Solution Fitness: 141073
New Best Solution Fitness: 141056
New Best Solution Fitness: 141007
Generation: 7
New Best Solution Fitness: 140854
New Best Solution Fitness: 140831
Generation: 8
New Best Solution Fitness: 140801
Generation: 9
New Best Solution Fitness: 140800
Generation: 10
New Best Solution Fitness: 140792
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.04444 
Mean sub-tour choices: 3.81111 
Best Solution Fitness: 140792 
--------------------------------------------- 
