--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141664
New Best Solution Fitness: 141633
New Best Solution Fitness: 141612
Generation: 3
New Best Solution Fitness: 141315
New Best Solution Fitness: 141265
New Best Solution Fitness: 141247
New Best Solution Fitness: 141236
New Best Solution Fitness: 141235
Generation: 4
New Best Solution Fitness: 141221
New Best Solution Fitness: 141219
Generation: 5
New Best Solution Fitness: 141157
New Best Solution Fitness: 141156
New Best Solution Fitness: 141155
Generation: 6
New Best Solution Fitness: 141105
New Best Solution Fitness: 141104
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.64444 
Mean sub-tour choices: 2.35556 
Best Solution Fitness: 141104 
--------------------------------------------- 
