--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142344
New Best Solution Fitness: 142297
New Best Solution Fitness: 142169
New Best Solution Fitness: 142143
Generation: 3
New Best Solution Fitness: 141932
New Best Solution Fitness: 141925
New Best Solution Fitness: 141816
New Best Solution Fitness: 141789
Generation: 4
New Best Solution Fitness: 141315
New Best Solution Fitness: 141304
New Best Solution Fitness: 141199
Generation: 5
New Best Solution Fitness: 141140
New Best Solution Fitness: 141129
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 141126
Generation: 9
Generation: 10
New Best Solution Fitness: 141122
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.64444 
Mean sub-tour choices: 3.37778 
Best Solution Fitness: 141122 
--------------------------------------------- 
