--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142166
New Best Solution Fitness: 141973
Generation: 3
New Best Solution Fitness: 141103
New Best Solution Fitness: 141091
New Best Solution Fitness: 140984
Generation: 4
New Best Solution Fitness: 140955
Generation: 5
New Best Solution Fitness: 140941
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 140933
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.63333 
Mean sub-tour choices: 4.45556 
Best Solution Fitness: 140933 
--------------------------------------------- 
