--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142157
New Best Solution Fitness: 141940
Generation: 3
New Best Solution Fitness: 141297
New Best Solution Fitness: 141232
Generation: 4
New Best Solution Fitness: 141190
New Best Solution Fitness: 141187
New Best Solution Fitness: 141185
Generation: 5
New Best Solution Fitness: 141184
New Best Solution Fitness: 141183
New Best Solution Fitness: 141181
Generation: 6
New Best Solution Fitness: 141160
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.84444 
Mean sub-tour choices: 4.72222 
Best Solution Fitness: 141160 
--------------------------------------------- 
