--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141009
New Best Solution Fitness: 140990
New Best Solution Fitness: 140968
New Best Solution Fitness: 140966
Generation: 3
New Best Solution Fitness: 140836
New Best Solution Fitness: 140802
Generation: 4
New Best Solution Fitness: 140725
New Best Solution Fitness: 140694
Generation: 5
New Best Solution Fitness: 140691
New Best Solution Fitness: 140684
Generation: 6
New Best Solution Fitness: 140672
New Best Solution Fitness: 140665
New Best Solution Fitness: 140623
Generation: 7
New Best Solution Fitness: 140620
New Best Solution Fitness: 140613
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.94444 
Mean sub-tour choices: 2.63333 
Best Solution Fitness: 140613 
--------------------------------------------- 
