--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141626
New Best Solution Fitness: 141463
New Best Solution Fitness: 141449
New Best Solution Fitness: 141435
New Best Solution Fitness: 141345
Generation: 3
New Best Solution Fitness: 141134
New Best Solution Fitness: 141088
New Best Solution Fitness: 141069
Generation: 4
New Best Solution Fitness: 141056
New Best Solution Fitness: 141055
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 141034
Generation: 8
New Best Solution Fitness: 140885
New Best Solution Fitness: 140884
New Best Solution Fitness: 140840
New Best Solution Fitness: 140830
Generation: 9
New Best Solution Fitness: 140654
New Best Solution Fitness: 140609
Generation: 10
New Best Solution Fitness: 140582
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.86667 
Mean sub-tour choices: 3.45556 
Best Solution Fitness: 140582 
--------------------------------------------- 
