--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142238
New Best Solution Fitness: 142192
New Best Solution Fitness: 142147
New Best Solution Fitness: 142141
New Best Solution Fitness: 142128
Generation: 3
New Best Solution Fitness: 141805
New Best Solution Fitness: 141772
New Best Solution Fitness: 141707
Generation: 4
New Best Solution Fitness: 141685
New Best Solution Fitness: 141653
New Best Solution Fitness: 141652
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 141622
New Best Solution Fitness: 141615
Generation: 8
New Best Solution Fitness: 141603
Generation: 9
New Best Solution Fitness: 141395
Generation: 10
New Best Solution Fitness: 141299
New Best Solution Fitness: 141296
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.18889 
Mean sub-tour choices: 2.9 
Best Solution Fitness: 141296 
--------------------------------------------- 
