--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141581
New Best Solution Fitness: 141533
New Best Solution Fitness: 141504
New Best Solution Fitness: 141424
Generation: 3
New Best Solution Fitness: 141157
New Best Solution Fitness: 141115
Generation: 4
New Best Solution Fitness: 141049
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 141045
Generation: 8
New Best Solution Fitness: 141029
New Best Solution Fitness: 141024
Generation: 9
New Best Solution Fitness: 141023
Generation: 10
New Best Solution Fitness: 141008
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.81111 
Mean sub-tour choices: 3.58889 
Best Solution Fitness: 141008 
--------------------------------------------- 
