--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141298
New Best Solution Fitness: 141250
New Best Solution Fitness: 141224
Generation: 3
New Best Solution Fitness: 140801
New Best Solution Fitness: 140770
Generation: 4
New Best Solution Fitness: 140718
New Best Solution Fitness: 140717
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 140709
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.76667 
Mean sub-tour choices: 3.53333 
Best Solution Fitness: 140709 
--------------------------------------------- 
