--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142819
New Best Solution Fitness: 142628
New Best Solution Fitness: 142599
New Best Solution Fitness: 142579
New Best Solution Fitness: 142520
Generation: 3
New Best Solution Fitness: 142134
New Best Solution Fitness: 141963
Generation: 4
New Best Solution Fitness: 141961
New Best Solution Fitness: 141951
New Best Solution Fitness: 141884
Generation: 5
New Best Solution Fitness: 141841
Generation: 6
Generation: 7
New Best Solution Fitness: 141671
Generation: 8
New Best Solution Fitness: 141480
New Best Solution Fitness: 141476
New Best Solution Fitness: 141438
Generation: 9
New Best Solution Fitness: 141410
New Best Solution Fitness: 141406
Generation: 10
New Best Solution Fitness: 141401
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.35556 
Mean sub-tour choices: 3.01111 
Best Solution Fitness: 141401 
--------------------------------------------- 
