--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142257
New Best Solution Fitness: 142182
New Best Solution Fitness: 142180
New Best Solution Fitness: 142114
Generation: 3
New Best Solution Fitness: 141963
New Best Solution Fitness: 141909
New Best Solution Fitness: 141782
Generation: 4
New Best Solution Fitness: 141542
New Best Solution Fitness: 141529
New Best Solution Fitness: 141520
New Best Solution Fitness: 141482
Generation: 5
New Best Solution Fitness: 141458
New Best Solution Fitness: 141409
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 141377
New Best Solution Fitness: 141368
Generation: 10
New Best Solution Fitness: 141364
New Best Solution Fitness: 141187
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.93333 
Mean sub-tour choices: 3.71111 
Best Solution Fitness: 141187 
--------------------------------------------- 
