--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142114
New Best Solution Fitness: 142026
New Best Solution Fitness: 141939
New Best Solution Fitness: 141913
Generation: 3
New Best Solution Fitness: 141637
New Best Solution Fitness: 141502
Generation: 4
New Best Solution Fitness: 141478
New Best Solution Fitness: 141464
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 141372
New Best Solution Fitness: 141359
Generation: 8
New Best Solution Fitness: 141300
New Best Solution Fitness: 141293
Generation: 9
New Best Solution Fitness: 141289
New Best Solution Fitness: 141283
New Best Solution Fitness: 141272
Generation: 10
New Best Solution Fitness: 141075
New Best Solution Fitness: 141051
New Best Solution Fitness: 140983
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.45556 
Mean sub-tour choices: 3.21111 
Best Solution Fitness: 140983 
--------------------------------------------- 
