--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142463
New Best Solution Fitness: 142437
New Best Solution Fitness: 142432
New Best Solution Fitness: 142426
Generation: 3
New Best Solution Fitness: 141795
New Best Solution Fitness: 141766
Generation: 4
New Best Solution Fitness: 141611
New Best Solution Fitness: 141595
Generation: 5
New Best Solution Fitness: 141332
New Best Solution Fitness: 141316
Generation: 6
New Best Solution Fitness: 141215
New Best Solution Fitness: 141143
Generation: 7
Generation: 8
New Best Solution Fitness: 141138
Generation: 9
New Best Solution Fitness: 141132
Generation: 10
New Best Solution Fitness: 140953
New Best Solution Fitness: 140916
New Best Solution Fitness: 140909
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.33333 
Mean sub-tour choices: 1.82222 
Best Solution Fitness: 140909 
--------------------------------------------- 
