--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141769
New Best Solution Fitness: 141699
New Best Solution Fitness: 141682
New Best Solution Fitness: 141677
Generation: 3
New Best Solution Fitness: 141271
New Best Solution Fitness: 141255
New Best Solution Fitness: 141235
New Best Solution Fitness: 141233
New Best Solution Fitness: 141202
New Best Solution Fitness: 141195
Generation: 4
New Best Solution Fitness: 141107
New Best Solution Fitness: 141077
Generation: 5
New Best Solution Fitness: 141056
New Best Solution Fitness: 141026
Generation: 6
New Best Solution Fitness: 141022
New Best Solution Fitness: 141020
Generation: 7
New Best Solution Fitness: 141012
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.33333 
Mean sub-tour choices: 3.04444 
Best Solution Fitness: 141012 
--------------------------------------------- 
