--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142590
New Best Solution Fitness: 142495
Generation: 3
New Best Solution Fitness: 141412
New Best Solution Fitness: 141399
Generation: 4
New Best Solution Fitness: 141366
New Best Solution Fitness: 141363
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 141337
Generation: 9
Generation: 10
New Best Solution Fitness: 141069
New Best Solution Fitness: 141055
New Best Solution Fitness: 141048
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.11111 
Mean sub-tour choices: 2.73333 
Best Solution Fitness: 141048 
--------------------------------------------- 
