--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142925
New Best Solution Fitness: 142854
New Best Solution Fitness: 142833
New Best Solution Fitness: 142737
Generation: 3
New Best Solution Fitness: 142125
New Best Solution Fitness: 142084
New Best Solution Fitness: 142070
New Best Solution Fitness: 142035
New Best Solution Fitness: 142017
Generation: 4
New Best Solution Fitness: 141625
New Best Solution Fitness: 141607
New Best Solution Fitness: 141584
New Best Solution Fitness: 141570
Generation: 5
New Best Solution Fitness: 141563
New Best Solution Fitness: 141485
Generation: 6
New Best Solution Fitness: 141467
Generation: 7
New Best Solution Fitness: 141464
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 141394
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.61111 
Mean sub-tour choices: 3.3 
Best Solution Fitness: 141394 
--------------------------------------------- 
