--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141875
New Best Solution Fitness: 141692
Generation: 3
New Best Solution Fitness: 141570
New Best Solution Fitness: 141569
New Best Solution Fitness: 141355
Generation: 4
New Best Solution Fitness: 141224
New Best Solution Fitness: 141215
New Best Solution Fitness: 141210
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 141140
New Best Solution Fitness: 141133
New Best Solution Fitness: 141005
Generation: 9
New Best Solution Fitness: 140976
New Best Solution Fitness: 140953
Generation: 10
New Best Solution Fitness: 140910
New Best Solution Fitness: 140879
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.32222 
Mean sub-tour choices: 3.03333 
Best Solution Fitness: 140879 
--------------------------------------------- 
