--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141572
New Best Solution Fitness: 141551
New Best Solution Fitness: 141549
New Best Solution Fitness: 141544
New Best Solution Fitness: 141390
Generation: 3
New Best Solution Fitness: 141087
New Best Solution Fitness: 141072
New Best Solution Fitness: 141069
Generation: 4
New Best Solution Fitness: 140951
New Best Solution Fitness: 140948
New Best Solution Fitness: 140944
New Best Solution Fitness: 140936
Generation: 5
Generation: 6
New Best Solution Fitness: 140903
Generation: 7
New Best Solution Fitness: 140892
Generation: 8
New Best Solution Fitness: 140885
Generation: 9
New Best Solution Fitness: 140853
Generation: 10
New Best Solution Fitness: 140852
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.44444 
Mean sub-tour choices: 3.15556 
Best Solution Fitness: 140852 
--------------------------------------------- 
