--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142036
New Best Solution Fitness: 141932
New Best Solution Fitness: 141875
New Best Solution Fitness: 141842
Generation: 3
New Best Solution Fitness: 141608
New Best Solution Fitness: 141575
New Best Solution Fitness: 141561
New Best Solution Fitness: 141526
Generation: 4
New Best Solution Fitness: 141513
New Best Solution Fitness: 141508
Generation: 5
New Best Solution Fitness: 141495
New Best Solution Fitness: 141461
Generation: 6
New Best Solution Fitness: 141448
New Best Solution Fitness: 141425
Generation: 7
New Best Solution Fitness: 141381
New Best Solution Fitness: 141368
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 7.36667 
Mean sub-tour choices: 8.26667 
Best Solution Fitness: 141368 
--------------------------------------------- 
