--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141835
New Best Solution Fitness: 141674
New Best Solution Fitness: 141607
New Best Solution Fitness: 141579
Generation: 3
New Best Solution Fitness: 141158
New Best Solution Fitness: 141118
Generation: 4
New Best Solution Fitness: 141112
New Best Solution Fitness: 141107
New Best Solution Fitness: 141092
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 141068
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 140941
New Best Solution Fitness: 140938
New Best Solution Fitness: 140890
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.56667 
Mean sub-tour choices: 3.28889 
Best Solution Fitness: 140890 
--------------------------------------------- 
