--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141953
New Best Solution Fitness: 141861
Generation: 3
New Best Solution Fitness: 141742
New Best Solution Fitness: 141534
Generation: 4
New Best Solution Fitness: 141455
New Best Solution Fitness: 141402
New Best Solution Fitness: 141390
Generation: 5
New Best Solution Fitness: 141380
New Best Solution Fitness: 141337
Generation: 6
New Best Solution Fitness: 141275
New Best Solution Fitness: 141222
Generation: 7
New Best Solution Fitness: 141216
New Best Solution Fitness: 141211
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.78889 
Mean sub-tour choices: 3.54444 
Best Solution Fitness: 141211 
--------------------------------------------- 
