--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141946
New Best Solution Fitness: 141910
New Best Solution Fitness: 141856
Generation: 3
New Best Solution Fitness: 141646
New Best Solution Fitness: 141529
Generation: 4
New Best Solution Fitness: 141524
New Best Solution Fitness: 141523
Generation: 5
New Best Solution Fitness: 141518
Generation: 6
New Best Solution Fitness: 141502
Generation: 7
New Best Solution Fitness: 141501
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 141429
New Best Solution Fitness: 141395
New Best Solution Fitness: 141381
New Best Solution Fitness: 141296
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.32222 
Mean sub-tour choices: 4.15556 
Best Solution Fitness: 141296 
--------------------------------------------- 
