--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142255
New Best Solution Fitness: 142149
New Best Solution Fitness: 142103
New Best Solution Fitness: 142057
Generation: 3
New Best Solution Fitness: 141070
New Best Solution Fitness: 141052
New Best Solution Fitness: 141051
New Best Solution Fitness: 141044
New Best Solution Fitness: 141031
Generation: 4
New Best Solution Fitness: 140981
New Best Solution Fitness: 140974
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.56667 
Mean sub-tour choices: 3.24444 
Best Solution Fitness: 140974 
--------------------------------------------- 
