--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141848
New Best Solution Fitness: 141828
New Best Solution Fitness: 141782
Generation: 3
New Best Solution Fitness: 141370
New Best Solution Fitness: 141366
New Best Solution Fitness: 141350
New Best Solution Fitness: 141345
Generation: 4
New Best Solution Fitness: 141284
New Best Solution Fitness: 141273
New Best Solution Fitness: 141267
Generation: 5
New Best Solution Fitness: 141256
New Best Solution Fitness: 141247
Generation: 6
New Best Solution Fitness: 141154
New Best Solution Fitness: 141134
Generation: 7
New Best Solution Fitness: 141099
New Best Solution Fitness: 141088
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.38889 
Mean sub-tour choices: 3.18889 
Best Solution Fitness: 141088 
--------------------------------------------- 
