--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141550
New Best Solution Fitness: 141489
New Best Solution Fitness: 141395
Generation: 3
New Best Solution Fitness: 140912
New Best Solution Fitness: 140858
Generation: 4
New Best Solution Fitness: 140857
New Best Solution Fitness: 140813
Generation: 5
New Best Solution Fitness: 140787
Generation: 6
Generation: 7
New Best Solution Fitness: 140786
Generation: 8
New Best Solution Fitness: 140785
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.75556 
Mean sub-tour choices: 3.51111 
Best Solution Fitness: 140785 
--------------------------------------------- 
