--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Black Box Steady State 
Population: 10
Mutation probability: 1
Crossover probability: 0.00787402
--------------------------
Job Complete 
Best Solution Fitness: 126395
Iterations: 161290
--------------------------------------------- 
