--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35514
New Best Solution Fitness: 35513
New Best Solution Fitness: 35489
Generation: 3
Generation: 4
Generation: 5
New Best Solution Fitness: 35396
Generation: 6
New Best Solution Fitness: 35361
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 35356
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.855556 
Mean sub-tour choices: 1.12222 
Best Solution Fitness: 35356 
--------------------------------------------- 
