--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35496
New Best Solution Fitness: 35486
Generation: 3
New Best Solution Fitness: 35480
New Best Solution Fitness: 35479
New Best Solution Fitness: 35428
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 35388
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.944444 
Mean sub-tour choices: 1.37778 
Best Solution Fitness: 35388 
--------------------------------------------- 
