--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35470
New Best Solution Fitness: 35453
Generation: 3
New Best Solution Fitness: 35373
New Best Solution Fitness: 35353
Generation: 4
New Best Solution Fitness: 35335
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 35312
New Best Solution Fitness: 35273
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.611111 
Mean sub-tour choices: 0.855556 
Best Solution Fitness: 35273 
--------------------------------------------- 
