--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35618
New Best Solution Fitness: 35586
Generation: 3
New Best Solution Fitness: 35570
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 35502
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 35445
Generation: 10
New Best Solution Fitness: 35398
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.388889 
Mean sub-tour choices: 0.644444 
Best Solution Fitness: 35398 
--------------------------------------------- 
