--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35765
New Best Solution Fitness: 35733
New Best Solution Fitness: 35729
Generation: 3
New Best Solution Fitness: 35588
New Best Solution Fitness: 35529
Generation: 4
Generation: 5
New Best Solution Fitness: 35443
Generation: 6
New Best Solution Fitness: 35437
Generation: 7
Generation: 8
New Best Solution Fitness: 35423
Generation: 9
New Best Solution Fitness: 35303
Generation: 10
New Best Solution Fitness: 35253
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.622222 
Mean sub-tour choices: 0.877778 
Best Solution Fitness: 35253 
--------------------------------------------- 
