--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35643
New Best Solution Fitness: 35632
Generation: 3
New Best Solution Fitness: 35625
Generation: 4
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 35508
New Best Solution Fitness: 35489
New Best Solution Fitness: 35462
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.966667 
Mean sub-tour choices: 1.45556 
Best Solution Fitness: 35462 
--------------------------------------------- 
