--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35637
New Best Solution Fitness: 35604
Generation: 3
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 35537
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 35446
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.344444 
Mean sub-tour choices: 0.588889 
Best Solution Fitness: 35446 
--------------------------------------------- 
