--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35857
Generation: 3
New Best Solution Fitness: 35828
Generation: 4
New Best Solution Fitness: 35780
New Best Solution Fitness: 35770
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 35751
Generation: 9
New Best Solution Fitness: 35748
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.4 
Mean sub-tour choices: 1.55556 
Best Solution Fitness: 35748 
--------------------------------------------- 
