--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35609
New Best Solution Fitness: 35573
New Best Solution Fitness: 35549
New Best Solution Fitness: 35546
Generation: 3
New Best Solution Fitness: 35427
New Best Solution Fitness: 35423
Generation: 4
New Best Solution Fitness: 35310
Generation: 5
New Best Solution Fitness: 35293
Generation: 6
New Best Solution Fitness: 35269
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.633333 
Mean sub-tour choices: 0.877778 
Best Solution Fitness: 35269 
--------------------------------------------- 
