--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35970
New Best Solution Fitness: 35920
New Best Solution Fitness: 35913
Generation: 3
New Best Solution Fitness: 35831
New Best Solution Fitness: 35817
Generation: 4
New Best Solution Fitness: 35757
Generation: 5
New Best Solution Fitness: 35712
New Best Solution Fitness: 35708
Generation: 6
Generation: 7
New Best Solution Fitness: 35494
New Best Solution Fitness: 35475
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.8 
Mean sub-tour choices: 1.14444 
Best Solution Fitness: 35475 
--------------------------------------------- 
