--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35436
Generation: 3
New Best Solution Fitness: 35381
Generation: 4
Generation: 5
New Best Solution Fitness: 35374
Generation: 6
New Best Solution Fitness: 35365
Generation: 7
Generation: 8
New Best Solution Fitness: 35345
New Best Solution Fitness: 35326
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.42222 
Mean sub-tour choices: 1.94444 
Best Solution Fitness: 35326 
--------------------------------------------- 
