--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35661
Generation: 3
New Best Solution Fitness: 35501
Generation: 4
New Best Solution Fitness: 35478
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 35472
Generation: 8
New Best Solution Fitness: 35435
New Best Solution Fitness: 35286
Generation: 9
New Best Solution Fitness: 35283
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.766667 
Mean sub-tour choices: 1.02222 
Best Solution Fitness: 35283 
--------------------------------------------- 
