--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35743
New Best Solution Fitness: 35715
Generation: 3
New Best Solution Fitness: 35476
New Best Solution Fitness: 35472
Generation: 4
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 35436
New Best Solution Fitness: 35390
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.366667 
Mean sub-tour choices: 0.666667 
Best Solution Fitness: 35390 
--------------------------------------------- 
