--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35870
New Best Solution Fitness: 35860
New Best Solution Fitness: 35829
Generation: 3
New Best Solution Fitness: 35791
New Best Solution Fitness: 35750
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 35495
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.41111 
Mean sub-tour choices: 1.56667 
Best Solution Fitness: 35495 
--------------------------------------------- 
