--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35533
New Best Solution Fitness: 35424
New Best Solution Fitness: 35420
Generation: 3
New Best Solution Fitness: 35387
New Best Solution Fitness: 35349
Generation: 4
New Best Solution Fitness: 35348
Generation: 5
New Best Solution Fitness: 35335
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.52222 
Mean sub-tour choices: 1.76667 
Best Solution Fitness: 35335 
--------------------------------------------- 
