--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35890
New Best Solution Fitness: 35830
New Best Solution Fitness: 35584
Generation: 3
Generation: 4
Generation: 5
New Best Solution Fitness: 35542
New Best Solution Fitness: 35529
Generation: 6
Generation: 7
New Best Solution Fitness: 35430
Generation: 8
New Best Solution Fitness: 35339
Generation: 9
New Best Solution Fitness: 35293
New Best Solution Fitness: 35285
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.488889 
Mean sub-tour choices: 0.711111 
Best Solution Fitness: 35285 
--------------------------------------------- 
