--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35596
Generation: 3
New Best Solution Fitness: 35542
Generation: 4
Generation: 5
New Best Solution Fitness: 35493
New Best Solution Fitness: 35490
Generation: 6
New Best Solution Fitness: 35399
Generation: 7
New Best Solution Fitness: 35354
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.688889 
Mean sub-tour choices: 1.26667 
Best Solution Fitness: 35354 
--------------------------------------------- 
