--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35602
Generation: 3
New Best Solution Fitness: 35553
New Best Solution Fitness: 35544
Generation: 4
New Best Solution Fitness: 35539
New Best Solution Fitness: 35530
Generation: 5
New Best Solution Fitness: 35494
Generation: 6
New Best Solution Fitness: 35457
Generation: 7
New Best Solution Fitness: 35454
Generation: 8
New Best Solution Fitness: 35450
Generation: 9
Generation: 10
New Best Solution Fitness: 35449
New Best Solution Fitness: 35421
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.977778 
Mean sub-tour choices: 1.26667 
Best Solution Fitness: 35421 
--------------------------------------------- 
