--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35827
New Best Solution Fitness: 35788
Generation: 3
New Best Solution Fitness: 35773
Generation: 4
Generation: 5
New Best Solution Fitness: 35684
New Best Solution Fitness: 35666
Generation: 6
Generation: 7
New Best Solution Fitness: 35634
New Best Solution Fitness: 35633
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.811111 
Mean sub-tour choices: 1.11111 
Best Solution Fitness: 35633 
--------------------------------------------- 
