--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35682
Generation: 3
New Best Solution Fitness: 35666
New Best Solution Fitness: 35515
Generation: 4
New Best Solution Fitness: 35513
Generation: 5
Generation: 6
New Best Solution Fitness: 35487
New Best Solution Fitness: 35460
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.13333 
Mean sub-tour choices: 1.75556 
Best Solution Fitness: 35460 
--------------------------------------------- 
