--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35703
New Best Solution Fitness: 35695
Generation: 3
Generation: 4
New Best Solution Fitness: 35688
New Best Solution Fitness: 35555
Generation: 5
Generation: 6
New Best Solution Fitness: 35478
Generation: 7
Generation: 8
New Best Solution Fitness: 35461
Generation: 9
New Best Solution Fitness: 35448
Generation: 10
New Best Solution Fitness: 35435
New Best Solution Fitness: 35419
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.811111 
Mean sub-tour choices: 1.21111 
Best Solution Fitness: 35419 
--------------------------------------------- 
