--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35723
New Best Solution Fitness: 35718
New Best Solution Fitness: 35717
New Best Solution Fitness: 35706
Generation: 3
New Best Solution Fitness: 35655
New Best Solution Fitness: 35651
New Best Solution Fitness: 35649
Generation: 4
New Best Solution Fitness: 35645
Generation: 5
New Best Solution Fitness: 35626
New Best Solution Fitness: 35555
Generation: 6
Generation: 7
New Best Solution Fitness: 35549
Generation: 8
New Best Solution Fitness: 35506
New Best Solution Fitness: 35504
New Best Solution Fitness: 35499
Generation: 9
New Best Solution Fitness: 35485
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.766667 
Mean sub-tour choices: 1.13333 
Best Solution Fitness: 35485 
--------------------------------------------- 
