--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35542
Generation: 3
New Best Solution Fitness: 35514
Generation: 4
New Best Solution Fitness: 35498
New Best Solution Fitness: 35469
Generation: 5
New Best Solution Fitness: 35461
Generation: 6
New Best Solution Fitness: 35370
New Best Solution Fitness: 35363
New Best Solution Fitness: 35354
Generation: 7
New Best Solution Fitness: 35320
New Best Solution Fitness: 35318
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.711111 
Mean sub-tour choices: 1.02222 
Best Solution Fitness: 35318 
--------------------------------------------- 
