--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35631
New Best Solution Fitness: 35612
Generation: 3
New Best Solution Fitness: 35596
Generation: 4
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 35593
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.855556 
Mean sub-tour choices: 1.28889 
Best Solution Fitness: 35593 
--------------------------------------------- 
