--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35714
New Best Solution Fitness: 35676
Generation: 3
New Best Solution Fitness: 35571
Generation: 4
Generation: 5
New Best Solution Fitness: 35393
New Best Solution Fitness: 35386
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 35374
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.511111 
Mean sub-tour choices: 0.777778 
Best Solution Fitness: 35374 
--------------------------------------------- 
