--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35660
New Best Solution Fitness: 35589
New Best Solution Fitness: 35588
New Best Solution Fitness: 35543
Generation: 3
New Best Solution Fitness: 35444
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 35432
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.466667 
Mean sub-tour choices: 0.666667 
Best Solution Fitness: 35432 
--------------------------------------------- 
