--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35854
New Best Solution Fitness: 35813
Generation: 3
New Best Solution Fitness: 35487
New Best Solution Fitness: 35446
Generation: 4
New Best Solution Fitness: 35444
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.911111 
Mean sub-tour choices: 1.35556 
Best Solution Fitness: 35444 
--------------------------------------------- 
