--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35623
New Best Solution Fitness: 35586
Generation: 3
New Best Solution Fitness: 35559
New Best Solution Fitness: 35551
Generation: 4
New Best Solution Fitness: 35541
New Best Solution Fitness: 35525
Generation: 5
New Best Solution Fitness: 35519
Generation: 6
New Best Solution Fitness: 35511
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.24444 
Mean sub-tour choices: 1.7 
Best Solution Fitness: 35511 
--------------------------------------------- 
