--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35673
New Best Solution Fitness: 35654
Generation: 3
New Best Solution Fitness: 35646
New Best Solution Fitness: 35627
New Best Solution Fitness: 35624
Generation: 4
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 35614
Generation: 8
New Best Solution Fitness: 35582
New Best Solution Fitness: 35550
Generation: 9
New Best Solution Fitness: 35542
Generation: 10
New Best Solution Fitness: 35523
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.22222 
Mean sub-tour choices: 1.66667 
Best Solution Fitness: 35523 
--------------------------------------------- 
