--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35668
New Best Solution Fitness: 35652
New Best Solution Fitness: 35635
Generation: 3
New Best Solution Fitness: 35494
Generation: 4
Generation: 5
New Best Solution Fitness: 35461
New Best Solution Fitness: 35454
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 35437
Generation: 9
New Best Solution Fitness: 35421
New Best Solution Fitness: 35398
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.488889 
Mean sub-tour choices: 0.711111 
Best Solution Fitness: 35398 
--------------------------------------------- 
