--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35719
New Best Solution Fitness: 35715
New Best Solution Fitness: 35710
New Best Solution Fitness: 35665
Generation: 3
New Best Solution Fitness: 35658
New Best Solution Fitness: 35654
New Best Solution Fitness: 35649
Generation: 4
New Best Solution Fitness: 35645
Generation: 5
New Best Solution Fitness: 35599
New Best Solution Fitness: 35595
Generation: 6
New Best Solution Fitness: 35591
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 35590
New Best Solution Fitness: 35579
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.41111 
Mean sub-tour choices: 1.78889 
Best Solution Fitness: 35579 
--------------------------------------------- 
