--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35636
New Best Solution Fitness: 35616
New Best Solution Fitness: 35604
Generation: 3
New Best Solution Fitness: 35383
New Best Solution Fitness: 35370
New Best Solution Fitness: 35363
Generation: 4
Generation: 5
New Best Solution Fitness: 35349
New Best Solution Fitness: 35344
Generation: 6
New Best Solution Fitness: 35272
New Best Solution Fitness: 35256
Generation: 7
Generation: 8
New Best Solution Fitness: 35219
Generation: 9
New Best Solution Fitness: 35218
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.63333 
Mean sub-tour choices: 1.84444 
Best Solution Fitness: 35218 
--------------------------------------------- 
