--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35656
New Best Solution Fitness: 35633
Generation: 3
New Best Solution Fitness: 35604
Generation: 4
New Best Solution Fitness: 35592
New Best Solution Fitness: 35538
Generation: 5
New Best Solution Fitness: 35518
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 35513
New Best Solution Fitness: 35437
Generation: 10
New Best Solution Fitness: 35432
New Best Solution Fitness: 35420
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.611111 
Mean sub-tour choices: 0.788889 
Best Solution Fitness: 35420 
--------------------------------------------- 
