--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35917
New Best Solution Fitness: 35899
Generation: 3
New Best Solution Fitness: 35725
Generation: 4
New Best Solution Fitness: 35654
Generation: 5
New Best Solution Fitness: 35631
Generation: 6
New Best Solution Fitness: 35612
Generation: 7
Generation: 8
New Best Solution Fitness: 35473
New Best Solution Fitness: 35466
Generation: 9
New Best Solution Fitness: 35429
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.8 
Mean sub-tour choices: 1.12222 
Best Solution Fitness: 35429 
--------------------------------------------- 
