--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35849
New Best Solution Fitness: 35827
Generation: 3
New Best Solution Fitness: 35731
New Best Solution Fitness: 35725
Generation: 4
New Best Solution Fitness: 35683
New Best Solution Fitness: 35671
Generation: 5
New Best Solution Fitness: 35638
New Best Solution Fitness: 35613
Generation: 6
Generation: 7
New Best Solution Fitness: 35451
New Best Solution Fitness: 35439
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.911111 
Mean sub-tour choices: 1.42222 
Best Solution Fitness: 35439 
--------------------------------------------- 
