--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35664
New Best Solution Fitness: 35612
Generation: 3
Generation: 4
New Best Solution Fitness: 35593
Generation: 5
New Best Solution Fitness: 35590
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.18889 
Mean sub-tour choices: 1.81111 
Best Solution Fitness: 35590 
--------------------------------------------- 
