--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35839
New Best Solution Fitness: 35700
Generation: 3
New Best Solution Fitness: 35625
Generation: 4
New Best Solution Fitness: 35614
Generation: 5
Generation: 6
New Best Solution Fitness: 35610
Generation: 7
New Best Solution Fitness: 35606
Generation: 8
Generation: 9
New Best Solution Fitness: 35526
New Best Solution Fitness: 35523
New Best Solution Fitness: 35517
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.35556 
Mean sub-tour choices: 1.32222 
Best Solution Fitness: 35517 
--------------------------------------------- 
