--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35622
New Best Solution Fitness: 35605
Generation: 3
New Best Solution Fitness: 35514
New Best Solution Fitness: 35506
Generation: 4
New Best Solution Fitness: 35494
New Best Solution Fitness: 35486
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.61111 
Mean sub-tour choices: 1.98889 
Best Solution Fitness: 35486 
--------------------------------------------- 
