--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35785
New Best Solution Fitness: 35776
Generation: 3
New Best Solution Fitness: 35674
New Best Solution Fitness: 35670
Generation: 4
New Best Solution Fitness: 35660
Generation: 5
New Best Solution Fitness: 35646
Generation: 6
New Best Solution Fitness: 35595
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 35493
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.7 
Mean sub-tour choices: 0.977778 
Best Solution Fitness: 35493 
--------------------------------------------- 
