--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35709
New Best Solution Fitness: 35690
Generation: 3
New Best Solution Fitness: 35636
Generation: 4
New Best Solution Fitness: 35577
Generation: 5
New Best Solution Fitness: 35557
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 35518
Generation: 9
New Best Solution Fitness: 35516
Generation: 10
New Best Solution Fitness: 35392
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.877778 
Mean sub-tour choices: 1.24444 
Best Solution Fitness: 35392 
--------------------------------------------- 
