--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35638
New Best Solution Fitness: 35635
New Best Solution Fitness: 35625
Generation: 3
New Best Solution Fitness: 35622
Generation: 4
New Best Solution Fitness: 35619
New Best Solution Fitness: 35615
Generation: 5
New Best Solution Fitness: 35577
New Best Solution Fitness: 35574
Generation: 6
New Best Solution Fitness: 35568
Generation: 7
New Best Solution Fitness: 35503
New Best Solution Fitness: 35462
Generation: 8
New Best Solution Fitness: 35442
Generation: 9
New Best Solution Fitness: 35354
New Best Solution Fitness: 35351
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.7 
Mean sub-tour choices: 0.911111 
Best Solution Fitness: 35351 
--------------------------------------------- 
