--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35619
New Best Solution Fitness: 35618
Generation: 3
New Best Solution Fitness: 35534
New Best Solution Fitness: 35514
Generation: 4
New Best Solution Fitness: 35497
Generation: 5
Generation: 6
New Best Solution Fitness: 35450
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.588889 
Mean sub-tour choices: 0.833333 
Best Solution Fitness: 35450 
--------------------------------------------- 
