--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35418
New Best Solution Fitness: 35410
New Best Solution Fitness: 35396
Generation: 3
New Best Solution Fitness: 35389
New Best Solution Fitness: 35381
Generation: 4
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 35318
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.711111 
Mean sub-tour choices: 0.933333 
Best Solution Fitness: 35318 
--------------------------------------------- 
