--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35574
Generation: 3
New Best Solution Fitness: 35525
Generation: 4
Generation: 5
New Best Solution Fitness: 35414
Generation: 6
New Best Solution Fitness: 35399
New Best Solution Fitness: 35391
Generation: 7
New Best Solution Fitness: 35362
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.988889 
Mean sub-tour choices: 1.28889 
Best Solution Fitness: 35362 
--------------------------------------------- 
