--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35447
New Best Solution Fitness: 35429
Generation: 3
New Best Solution Fitness: 35412
New Best Solution Fitness: 35409
New Best Solution Fitness: 35385
New Best Solution Fitness: 35367
Generation: 4
New Best Solution Fitness: 35344
Generation: 5
New Best Solution Fitness: 35335
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 35279
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.08889 
Mean sub-tour choices: 1.51111 
Best Solution Fitness: 35279 
--------------------------------------------- 
