--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35889
Generation: 3
New Best Solution Fitness: 35789
New Best Solution Fitness: 35779
New Best Solution Fitness: 35770
Generation: 4
New Best Solution Fitness: 35760
Generation: 5
New Best Solution Fitness: 35746
New Best Solution Fitness: 35736
New Best Solution Fitness: 35687
Generation: 6
New Best Solution Fitness: 35683
Generation: 7
New Best Solution Fitness: 35666
Generation: 8
New Best Solution Fitness: 35629
New Best Solution Fitness: 35615
New Best Solution Fitness: 35598
Generation: 9
New Best Solution Fitness: 35563
New Best Solution Fitness: 35537
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.51111 
Mean sub-tour choices: 1.63333 
Best Solution Fitness: 35537 
--------------------------------------------- 
