--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35679
New Best Solution Fitness: 35662
New Best Solution Fitness: 35597
Generation: 3
New Best Solution Fitness: 35506
New Best Solution Fitness: 35438
New Best Solution Fitness: 35427
Generation: 4
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 35425
Generation: 8
New Best Solution Fitness: 35402
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.27778 
Mean sub-tour choices: 2 
Best Solution Fitness: 35402 
--------------------------------------------- 
