--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 36113
Generation: 3
New Best Solution Fitness: 35584
Generation: 4
New Best Solution Fitness: 35476
Generation: 5
New Best Solution Fitness: 35382
Generation: 6
Generation: 7
New Best Solution Fitness: 35241
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.488889 
Mean sub-tour choices: 0.944444 
Best Solution Fitness: 35241 
--------------------------------------------- 
