--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35272
New Best Solution Fitness: 35260
Generation: 3
New Best Solution Fitness: 35168
New Best Solution Fitness: 35138
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 35115
Generation: 7
Generation: 8
New Best Solution Fitness: 35080
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.911111 
Mean sub-tour choices: 1.11111 
Best Solution Fitness: 35080 
--------------------------------------------- 
