--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35747
New Best Solution Fitness: 35696
New Best Solution Fitness: 35691
New Best Solution Fitness: 35685
Generation: 3
New Best Solution Fitness: 35556
New Best Solution Fitness: 35550
New Best Solution Fitness: 35547
Generation: 4
New Best Solution Fitness: 35532
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 35529
Generation: 8
New Best Solution Fitness: 35500
Generation: 9
New Best Solution Fitness: 35432
New Best Solution Fitness: 35420
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.811111 
Mean sub-tour choices: 1.27778 
Best Solution Fitness: 35420 
--------------------------------------------- 
