--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35533
Generation: 3
New Best Solution Fitness: 35338
New Best Solution Fitness: 35324
Generation: 4
New Best Solution Fitness: 35278
New Best Solution Fitness: 35264
Generation: 5
New Best Solution Fitness: 35228
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.85556 
Mean sub-tour choices: 1.86667 
Best Solution Fitness: 35228 
--------------------------------------------- 
