--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35700
New Best Solution Fitness: 35693
New Best Solution Fitness: 35671
Generation: 3
New Best Solution Fitness: 35599
Generation: 4
New Best Solution Fitness: 35580
Generation: 5
New Best Solution Fitness: 35532
New Best Solution Fitness: 35528
Generation: 6
Generation: 7
New Best Solution Fitness: 35523
Generation: 8
New Best Solution Fitness: 35514
New Best Solution Fitness: 35509
Generation: 9
New Best Solution Fitness: 35503
Generation: 10
New Best Solution Fitness: 35498
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.03333 
Mean sub-tour choices: 1.92222 
Best Solution Fitness: 35498 
--------------------------------------------- 
