--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35573
New Best Solution Fitness: 35570
New Best Solution Fitness: 35563
New Best Solution Fitness: 35544
Generation: 3
New Best Solution Fitness: 35407
Generation: 4
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 35310
New Best Solution Fitness: 35233
Generation: 8
New Best Solution Fitness: 35182
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.911111 
Mean sub-tour choices: 1.07778 
Best Solution Fitness: 35182 
--------------------------------------------- 
