--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35664
Generation: 3
New Best Solution Fitness: 35608
New Best Solution Fitness: 35562
New Best Solution Fitness: 35553
Generation: 4
New Best Solution Fitness: 35545
New Best Solution Fitness: 35542
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 35523
Generation: 9
Generation: 10
New Best Solution Fitness: 35516
New Best Solution Fitness: 35509
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.18889 
Mean sub-tour choices: 1.21111 
Best Solution Fitness: 35509 
--------------------------------------------- 
