--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35735
New Best Solution Fitness: 35732
Generation: 3
New Best Solution Fitness: 35580
New Best Solution Fitness: 35577
Generation: 4
New Best Solution Fitness: 35401
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.666667 
Mean sub-tour choices: 1.02222 
Best Solution Fitness: 35401 
--------------------------------------------- 
