--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 36445
Generation: 3
New Best Solution Fitness: 35778
New Best Solution Fitness: 35772
New Best Solution Fitness: 35765
Generation: 4
New Best Solution Fitness: 35714
New Best Solution Fitness: 35708
Generation: 5
Generation: 6
New Best Solution Fitness: 35577
Generation: 7
New Best Solution Fitness: 35473
Generation: 8
New Best Solution Fitness: 35461
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.44444 
Mean sub-tour choices: 1.52222 
Best Solution Fitness: 35461 
--------------------------------------------- 
