--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35719
New Best Solution Fitness: 35699
Generation: 3
New Best Solution Fitness: 35630
Generation: 4
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 35575
Generation: 9
New Best Solution Fitness: 35521
New Best Solution Fitness: 35510
Generation: 10
New Best Solution Fitness: 35487
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.877778 
Mean sub-tour choices: 1.18889 
Best Solution Fitness: 35487 
--------------------------------------------- 
