--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35525
New Best Solution Fitness: 35501
Generation: 3
New Best Solution Fitness: 35348
Generation: 4
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 35347
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.67778 
Mean sub-tour choices: 1.86667 
Best Solution Fitness: 35347 
--------------------------------------------- 
