--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35609
New Best Solution Fitness: 35605
New Best Solution Fitness: 35543
Generation: 3
New Best Solution Fitness: 35524
New Best Solution Fitness: 35517
New Best Solution Fitness: 35482
Generation: 4
New Best Solution Fitness: 35444
New Best Solution Fitness: 35437
Generation: 5
Generation: 6
New Best Solution Fitness: 35332
Generation: 7
New Best Solution Fitness: 35295
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.888889 
Mean sub-tour choices: 1.27778 
Best Solution Fitness: 35295 
--------------------------------------------- 
