--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35544
New Best Solution Fitness: 35522
New Best Solution Fitness: 35412
Generation: 3
New Best Solution Fitness: 35393
New Best Solution Fitness: 35377
Generation: 4
Generation: 5
New Best Solution Fitness: 35365
Generation: 6
Generation: 7
New Best Solution Fitness: 35316
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.02222 
Mean sub-tour choices: 1.41111 
Best Solution Fitness: 35316 
--------------------------------------------- 
