--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35716
New Best Solution Fitness: 35703
New Best Solution Fitness: 35671
Generation: 3
New Best Solution Fitness: 35663
Generation: 4
New Best Solution Fitness: 35609
New Best Solution Fitness: 35590
Generation: 5
New Best Solution Fitness: 35588
Generation: 6
New Best Solution Fitness: 35577
Generation: 7
New Best Solution Fitness: 35537
Generation: 8
Generation: 9
New Best Solution Fitness: 35517
New Best Solution Fitness: 35434
Generation: 10
New Best Solution Fitness: 35415
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.655556 
Mean sub-tour choices: 0.966667 
Best Solution Fitness: 35415 
--------------------------------------------- 
