--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35461
New Best Solution Fitness: 35448
New Best Solution Fitness: 35440
Generation: 3
New Best Solution Fitness: 35433
New Best Solution Fitness: 35424
Generation: 4
New Best Solution Fitness: 35417
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 35414
Generation: 8
Generation: 9
New Best Solution Fitness: 35404
New Best Solution Fitness: 35398
New Best Solution Fitness: 35395
Generation: 10
New Best Solution Fitness: 35388
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.04444 
Mean sub-tour choices: 1.43333 
Best Solution Fitness: 35388 
--------------------------------------------- 
