--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35745
Generation: 3
New Best Solution Fitness: 35718
New Best Solution Fitness: 35703
Generation: 4
New Best Solution Fitness: 35656
Generation: 5
New Best Solution Fitness: 35617
Generation: 6
Generation: 7
New Best Solution Fitness: 35497
New Best Solution Fitness: 35479
Generation: 8
New Best Solution Fitness: 35453
New Best Solution Fitness: 35447
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.5 
Mean sub-tour choices: 0.8 
Best Solution Fitness: 35447 
--------------------------------------------- 
