--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35739
Generation: 3
New Best Solution Fitness: 35734
New Best Solution Fitness: 35706
Generation: 4
Generation: 5
New Best Solution Fitness: 35674
Generation: 6
Generation: 7
New Best Solution Fitness: 35521
New Best Solution Fitness: 35489
Generation: 8
New Best Solution Fitness: 35435
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.577778 
Mean sub-tour choices: 0.9 
Best Solution Fitness: 35435 
--------------------------------------------- 
