--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35797
New Best Solution Fitness: 35709
Generation: 3
New Best Solution Fitness: 35696
New Best Solution Fitness: 35627
Generation: 4
New Best Solution Fitness: 35621
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 35556
New Best Solution Fitness: 35553
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.23333 
Mean sub-tour choices: 1.83333 
Best Solution Fitness: 35553 
--------------------------------------------- 
