--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35476
Generation: 3
New Best Solution Fitness: 35420
New Best Solution Fitness: 35394
New Best Solution Fitness: 35361
Generation: 4
New Best Solution Fitness: 35331
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 35258
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.05556 
Mean sub-tour choices: 1.35556 
Best Solution Fitness: 35258 
--------------------------------------------- 
