--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35393
New Best Solution Fitness: 35392
New Best Solution Fitness: 35322
Generation: 3
New Best Solution Fitness: 35313
New Best Solution Fitness: 35301
Generation: 4
Generation: 5
New Best Solution Fitness: 35230
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 35226
Generation: 9
New Best Solution Fitness: 35223
New Best Solution Fitness: 35219
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.588889 
Mean sub-tour choices: 0.877778 
Best Solution Fitness: 35219 
--------------------------------------------- 
