--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35642
New Best Solution Fitness: 35633
New Best Solution Fitness: 35600
Generation: 3
New Best Solution Fitness: 35523
New Best Solution Fitness: 35514
Generation: 4
New Best Solution Fitness: 35508
Generation: 5
New Best Solution Fitness: 35504
Generation: 6
New Best Solution Fitness: 35498
Generation: 7
Generation: 8
New Best Solution Fitness: 35432
Generation: 9
New Best Solution Fitness: 35416
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1 
Mean sub-tour choices: 1.38889 
Best Solution Fitness: 35416 
--------------------------------------------- 
