--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35601
New Best Solution Fitness: 35579
Generation: 3
New Best Solution Fitness: 35482
Generation: 4
Generation: 5
New Best Solution Fitness: 35463
New Best Solution Fitness: 35437
Generation: 6
New Best Solution Fitness: 35430
Generation: 7
New Best Solution Fitness: 35343
Generation: 8
New Best Solution Fitness: 35318
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.722222 
Mean sub-tour choices: 0.888889 
Best Solution Fitness: 35318 
--------------------------------------------- 
