--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35633
Generation: 3
New Best Solution Fitness: 35619
New Best Solution Fitness: 35589
New Best Solution Fitness: 35559
Generation: 4
New Best Solution Fitness: 35529
Generation: 5
Generation: 6
New Best Solution Fitness: 35515
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 35499
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1 
Mean sub-tour choices: 1.34444 
Best Solution Fitness: 35499 
--------------------------------------------- 
