--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35566
New Best Solution Fitness: 35546
New Best Solution Fitness: 35522
Generation: 3
New Best Solution Fitness: 35502
Generation: 4
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 35414
Generation: 10
New Best Solution Fitness: 35402
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.26667 
Mean sub-tour choices: 1.43333 
Best Solution Fitness: 35402 
--------------------------------------------- 
