--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35608
New Best Solution Fitness: 35602
Generation: 3
New Best Solution Fitness: 35502
New Best Solution Fitness: 35441
Generation: 4
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 35435
New Best Solution Fitness: 35416
New Best Solution Fitness: 35407
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 35401
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.644444 
Mean sub-tour choices: 1.01111 
Best Solution Fitness: 35401 
--------------------------------------------- 
