--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35556
New Best Solution Fitness: 35415
Generation: 3
New Best Solution Fitness: 35202
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 35110
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 35103
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.6 
Mean sub-tour choices: 1.77778 
Best Solution Fitness: 35103 
--------------------------------------------- 
