--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35585
Generation: 3
Generation: 4
New Best Solution Fitness: 35518
New Best Solution Fitness: 35509
Generation: 5
New Best Solution Fitness: 35499
Generation: 6
New Best Solution Fitness: 35286
New Best Solution Fitness: 35276
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 35266
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.588889 
Mean sub-tour choices: 1.07778 
Best Solution Fitness: 35266 
--------------------------------------------- 
