--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35532
New Best Solution Fitness: 35520
Generation: 3
New Best Solution Fitness: 35505
Generation: 4
Generation: 5
New Best Solution Fitness: 35478
Generation: 6
New Best Solution Fitness: 35441
New Best Solution Fitness: 35422
Generation: 7
Generation: 8
New Best Solution Fitness: 35340
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.833333 
Mean sub-tour choices: 1.3 
Best Solution Fitness: 35340 
--------------------------------------------- 
