--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35456
New Best Solution Fitness: 35416
Generation: 3
New Best Solution Fitness: 35395
Generation: 4
Generation: 5
New Best Solution Fitness: 35326
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 35250
Generation: 9
Generation: 10
New Best Solution Fitness: 35234
New Best Solution Fitness: 35221
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.84444 
Mean sub-tour choices: 1.64444 
Best Solution Fitness: 35221 
--------------------------------------------- 
