--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35794
Generation: 3
New Best Solution Fitness: 35749
Generation: 4
New Best Solution Fitness: 35686
New Best Solution Fitness: 35671
Generation: 5
New Best Solution Fitness: 35661
Generation: 6
Generation: 7
New Best Solution Fitness: 35645
New Best Solution Fitness: 35620
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 35541
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.522222 
Mean sub-tour choices: 0.822222 
Best Solution Fitness: 35541 
--------------------------------------------- 
