--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35484
Generation: 3
New Best Solution Fitness: 35387
Generation: 4
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 35367
New Best Solution Fitness: 35289
Generation: 9
Generation: 10
New Best Solution Fitness: 35276
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.733333 
Mean sub-tour choices: 1.13333 
Best Solution Fitness: 35276 
--------------------------------------------- 
