--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35804
New Best Solution Fitness: 35798
Generation: 3
New Best Solution Fitness: 35534
New Best Solution Fitness: 35532
New Best Solution Fitness: 35524
New Best Solution Fitness: 35505
Generation: 4
New Best Solution Fitness: 35435
New Best Solution Fitness: 35358
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.888889 
Mean sub-tour choices: 1.04444 
Best Solution Fitness: 35358 
--------------------------------------------- 
