--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35492
New Best Solution Fitness: 35483
Generation: 3
New Best Solution Fitness: 35480
Generation: 4
New Best Solution Fitness: 35475
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 35428
Generation: 9
Generation: 10
New Best Solution Fitness: 35397
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.35556 
Mean sub-tour choices: 1.71111 
Best Solution Fitness: 35397 
--------------------------------------------- 
