--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35877
New Best Solution Fitness: 35831
Generation: 3
New Best Solution Fitness: 35719
Generation: 4
New Best Solution Fitness: 35702
New Best Solution Fitness: 35699
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 35694
Generation: 8
Generation: 9
New Best Solution Fitness: 35500
Generation: 10
New Best Solution Fitness: 35479
New Best Solution Fitness: 35418
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.533333 
Mean sub-tour choices: 0.877778 
Best Solution Fitness: 35418 
--------------------------------------------- 
