--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35708
New Best Solution Fitness: 35653
New Best Solution Fitness: 35649
Generation: 3
New Best Solution Fitness: 35585
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 35523
Generation: 7
New Best Solution Fitness: 35514
Generation: 8
Generation: 9
New Best Solution Fitness: 35510
Generation: 10
New Best Solution Fitness: 35508
New Best Solution Fitness: 35504
New Best Solution Fitness: 35479
New Best Solution Fitness: 35475
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.66667 
Mean sub-tour choices: 1.96667 
Best Solution Fitness: 35475 
--------------------------------------------- 
