--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35454
Generation: 3
New Best Solution Fitness: 35402
Generation: 4
Generation: 5
New Best Solution Fitness: 35399
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 35358
Generation: 9
Generation: 10
New Best Solution Fitness: 35355
New Best Solution Fitness: 35324
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.9 
Mean sub-tour choices: 1.52222 
Best Solution Fitness: 35324 
--------------------------------------------- 
