--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35789
New Best Solution Fitness: 35773
New Best Solution Fitness: 35631
Generation: 3
New Best Solution Fitness: 35578
New Best Solution Fitness: 35524
Generation: 4
New Best Solution Fitness: 35508
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 35500
New Best Solution Fitness: 35470
Generation: 8
New Best Solution Fitness: 35414
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.44444 
Mean sub-tour choices: 1.41111 
Best Solution Fitness: 35414 
--------------------------------------------- 
