--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35592
Generation: 3
New Best Solution Fitness: 35564
Generation: 4
New Best Solution Fitness: 35545
New Best Solution Fitness: 35540
Generation: 5
New Best Solution Fitness: 35521
Generation: 6
New Best Solution Fitness: 35513
Generation: 7
New Best Solution Fitness: 35483
New Best Solution Fitness: 35459
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 35446
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.544444 
Mean sub-tour choices: 0.944444 
Best Solution Fitness: 35446 
--------------------------------------------- 
