--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35505
New Best Solution Fitness: 35480
New Best Solution Fitness: 35469
Generation: 3
New Best Solution Fitness: 35449
New Best Solution Fitness: 35447
Generation: 4
New Best Solution Fitness: 35440
Generation: 5
New Best Solution Fitness: 35428
New Best Solution Fitness: 35387
Generation: 6
New Best Solution Fitness: 35360
Generation: 7
Generation: 8
New Best Solution Fitness: 35318
New Best Solution Fitness: 35314
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.977778 
Mean sub-tour choices: 1.22222 
Best Solution Fitness: 35314 
--------------------------------------------- 
