--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35535
New Best Solution Fitness: 35520
Generation: 3
New Best Solution Fitness: 35510
Generation: 4
Generation: 5
New Best Solution Fitness: 35483
New Best Solution Fitness: 35461
Generation: 6
New Best Solution Fitness: 35457
Generation: 7
New Best Solution Fitness: 35441
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 35388
New Best Solution Fitness: 35362
New Best Solution Fitness: 35338
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.977778 
Mean sub-tour choices: 1.35556 
Best Solution Fitness: 35338 
--------------------------------------------- 
