--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35490
New Best Solution Fitness: 35456
New Best Solution Fitness: 35364
Generation: 3
New Best Solution Fitness: 35323
Generation: 4
Generation: 5
New Best Solution Fitness: 35308
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 35299
Generation: 10
New Best Solution Fitness: 35276
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.788889 
Mean sub-tour choices: 1.06667 
Best Solution Fitness: 35276 
--------------------------------------------- 
