--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35695
New Best Solution Fitness: 35691
New Best Solution Fitness: 35689
New Best Solution Fitness: 35682
New Best Solution Fitness: 35681
Generation: 3
New Best Solution Fitness: 35574
New Best Solution Fitness: 35561
New Best Solution Fitness: 35507
Generation: 4
New Best Solution Fitness: 35478
New Best Solution Fitness: 35474
Generation: 5
New Best Solution Fitness: 35469
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 35462
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.02222 
Mean sub-tour choices: 1.56667 
Best Solution Fitness: 35462 
--------------------------------------------- 
