--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 596304
New Best Solution Fitness: 596050
New Best Solution Fitness: 595977
Generation: 3
New Best Solution Fitness: 585989
New Best Solution Fitness: 585582
New Best Solution Fitness: 585431
Generation: 4
New Best Solution Fitness: 583028
New Best Solution Fitness: 582835
Generation: 5
New Best Solution Fitness: 581292
New Best Solution Fitness: 578668
Generation: 6
New Best Solution Fitness: 578559
New Best Solution Fitness: 578440
Generation: 7
New Best Solution Fitness: 578380
Generation: 8
New Best Solution Fitness: 578372
Generation: 9
New Best Solution Fitness: 578120
Generation: 10
New Best Solution Fitness: 576555
New Best Solution Fitness: 576548
New Best Solution Fitness: 576046
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.72222 
Mean sub-tour choices: 1.74444 
Best Solution Fitness: 576046 
--------------------------------------------- 
