--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 583252
New Best Solution Fitness: 583198
New Best Solution Fitness: 583153
Generation: 3
New Best Solution Fitness: 581855
New Best Solution Fitness: 581783
New Best Solution Fitness: 581431
Generation: 4
New Best Solution Fitness: 581272
New Best Solution Fitness: 581267
New Best Solution Fitness: 581200
Generation: 5
New Best Solution Fitness: 581191
New Best Solution Fitness: 581186
Generation: 6
New Best Solution Fitness: 581181
Generation: 7
New Best Solution Fitness: 581138
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 5.28889 
Mean sub-tour choices: 2.33333 
Best Solution Fitness: 581138 
--------------------------------------------- 
