--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 583951
New Best Solution Fitness: 583916
New Best Solution Fitness: 583627
New Best Solution Fitness: 583477
Generation: 3
New Best Solution Fitness: 581574
New Best Solution Fitness: 581573
New Best Solution Fitness: 581551
Generation: 4
New Best Solution Fitness: 580420
New Best Solution Fitness: 580419
Generation: 5
New Best Solution Fitness: 580269
New Best Solution Fitness: 580242
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 8.1 
Mean sub-tour choices: 2.75556 
Best Solution Fitness: 580242 
--------------------------------------------- 
