--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 592274
New Best Solution Fitness: 591498
Generation: 3
New Best Solution Fitness: 584759
New Best Solution Fitness: 584745
Generation: 4
New Best Solution Fitness: 580622
New Best Solution Fitness: 580569
New Best Solution Fitness: 580553
Generation: 5
New Best Solution Fitness: 579935
New Best Solution Fitness: 579882
Generation: 6
New Best Solution Fitness: 579603
New Best Solution Fitness: 579587
Generation: 7
New Best Solution Fitness: 579549
Generation: 8
Generation: 9
New Best Solution Fitness: 579492
New Best Solution Fitness: 579423
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 5.56667 
Mean sub-tour choices: 2.11111 
Best Solution Fitness: 579423 
--------------------------------------------- 
