--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 594926
New Best Solution Fitness: 594842
New Best Solution Fitness: 594750
Generation: 3
New Best Solution Fitness: 589617
New Best Solution Fitness: 589605
New Best Solution Fitness: 589408
Generation: 4
New Best Solution Fitness: 587378
New Best Solution Fitness: 587366
Generation: 5
New Best Solution Fitness: 585086
New Best Solution Fitness: 584648
Generation: 6
New Best Solution Fitness: 584547
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.26667 
Mean sub-tour choices: 1.43333 
Best Solution Fitness: 584547 
--------------------------------------------- 
