--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 595138
New Best Solution Fitness: 594179
New Best Solution Fitness: 594148
Generation: 3
New Best Solution Fitness: 590495
New Best Solution Fitness: 590376
Generation: 4
New Best Solution Fitness: 589903
New Best Solution Fitness: 589831
Generation: 5
New Best Solution Fitness: 589815
New Best Solution Fitness: 589757
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 6.97778 
Mean sub-tour choices: 2.15556 
Best Solution Fitness: 589757 
--------------------------------------------- 
