--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 594536
New Best Solution Fitness: 594380
New Best Solution Fitness: 594301
Generation: 3
New Best Solution Fitness: 589177
New Best Solution Fitness: 589172
New Best Solution Fitness: 589140
Generation: 4
New Best Solution Fitness: 587245
New Best Solution Fitness: 587224
New Best Solution Fitness: 587208
Generation: 5
New Best Solution Fitness: 586857
New Best Solution Fitness: 586836
Generation: 6
New Best Solution Fitness: 586583
New Best Solution Fitness: 586551
Generation: 7
New Best Solution Fitness: 583909
Generation: 8
New Best Solution Fitness: 583209
Generation: 9
New Best Solution Fitness: 583168
New Best Solution Fitness: 583094
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 5.18889 
Mean sub-tour choices: 1.92222 
Best Solution Fitness: 583094 
--------------------------------------------- 
