--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 585464
New Best Solution Fitness: 585288
Generation: 3
New Best Solution Fitness: 581724
New Best Solution Fitness: 581610
Generation: 4
New Best Solution Fitness: 581166
New Best Solution Fitness: 581111
New Best Solution Fitness: 581098
Generation: 5
New Best Solution Fitness: 581027
New Best Solution Fitness: 581015
Generation: 6
New Best Solution Fitness: 579118
New Best Solution Fitness: 579097
Generation: 7
New Best Solution Fitness: 578692
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 5.33333 
Mean sub-tour choices: 2.87778 
Best Solution Fitness: 578692 
--------------------------------------------- 
