--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 584773
New Best Solution Fitness: 584485
New Best Solution Fitness: 584368
Generation: 3
New Best Solution Fitness: 582317
New Best Solution Fitness: 582282
New Best Solution Fitness: 582138
New Best Solution Fitness: 582130
Generation: 4
New Best Solution Fitness: 580818
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 580783
Generation: 8
New Best Solution Fitness: 580782
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.3 
Mean sub-tour choices: 2.42222 
Best Solution Fitness: 580782 
--------------------------------------------- 
