--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 599326
New Best Solution Fitness: 599313
New Best Solution Fitness: 599293
New Best Solution Fitness: 598704
Generation: 3
New Best Solution Fitness: 589751
New Best Solution Fitness: 589654
Generation: 4
New Best Solution Fitness: 586522
New Best Solution Fitness: 586509
Generation: 5
New Best Solution Fitness: 583518
Generation: 6
New Best Solution Fitness: 583177
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.92222 
Mean sub-tour choices: 1.87778 
Best Solution Fitness: 583177 
--------------------------------------------- 
