--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 604743
New Best Solution Fitness: 604702
New Best Solution Fitness: 604506
Generation: 3
New Best Solution Fitness: 598159
New Best Solution Fitness: 598145
New Best Solution Fitness: 598028
Generation: 4
New Best Solution Fitness: 592096
New Best Solution Fitness: 591918
New Best Solution Fitness: 591863
Generation: 5
New Best Solution Fitness: 584807
New Best Solution Fitness: 584726
Generation: 6
New Best Solution Fitness: 584270
Generation: 7
New Best Solution Fitness: 584262
Generation: 8
New Best Solution Fitness: 584188
Generation: 9
Generation: 10
New Best Solution Fitness: 583823
New Best Solution Fitness: 583774
New Best Solution Fitness: 583658
New Best Solution Fitness: 582962
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.35556 
Mean sub-tour choices: 1.62222 
Best Solution Fitness: 582962 
--------------------------------------------- 
