--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 589157
New Best Solution Fitness: 589100
New Best Solution Fitness: 588112
Generation: 3
New Best Solution Fitness: 585860
New Best Solution Fitness: 584967
New Best Solution Fitness: 584527
Generation: 4
New Best Solution Fitness: 584389
New Best Solution Fitness: 584364
Generation: 5
New Best Solution Fitness: 584238
Generation: 6
New Best Solution Fitness: 583323
Generation: 7
Generation: 8
New Best Solution Fitness: 583041
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 5.6 
Mean sub-tour choices: 3.11111 
Best Solution Fitness: 583041 
--------------------------------------------- 
