--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 588497
New Best Solution Fitness: 588491
New Best Solution Fitness: 588416
New Best Solution Fitness: 588403
New Best Solution Fitness: 588329
New Best Solution Fitness: 588040
Generation: 3
New Best Solution Fitness: 582841
New Best Solution Fitness: 582755
New Best Solution Fitness: 582566
New Best Solution Fitness: 582459
Generation: 4
New Best Solution Fitness: 580981
New Best Solution Fitness: 580955
New Best Solution Fitness: 580941
Generation: 5
New Best Solution Fitness: 580932
Generation: 6
New Best Solution Fitness: 580928
Generation: 7
New Best Solution Fitness: 580877
Generation: 8
New Best Solution Fitness: 580756
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.82222 
Mean sub-tour choices: 2.65556 
Best Solution Fitness: 580756 
--------------------------------------------- 
