--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 596309
New Best Solution Fitness: 594987
Generation: 3
New Best Solution Fitness: 586639
New Best Solution Fitness: 586547
New Best Solution Fitness: 585599
Generation: 4
New Best Solution Fitness: 585383
New Best Solution Fitness: 585369
New Best Solution Fitness: 585265
Generation: 5
New Best Solution Fitness: 584197
New Best Solution Fitness: 584171
Generation: 6
New Best Solution Fitness: 582028
New Best Solution Fitness: 582004
Generation: 7
New Best Solution Fitness: 581990
New Best Solution Fitness: 581892
Generation: 8
New Best Solution Fitness: 581878
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 6.4 
Mean sub-tour choices: 2.31111 
Best Solution Fitness: 581878 
--------------------------------------------- 
