--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 584097
New Best Solution Fitness: 583678
New Best Solution Fitness: 583492
Generation: 3
New Best Solution Fitness: 580081
New Best Solution Fitness: 579957
New Best Solution Fitness: 579905
Generation: 4
New Best Solution Fitness: 579614
Generation: 5
Generation: 6
New Best Solution Fitness: 579365
New Best Solution Fitness: 579182
Generation: 7
New Best Solution Fitness: 579127
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.66667 
Mean sub-tour choices: 1.9 
Best Solution Fitness: 579127 
--------------------------------------------- 
