--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 588086
New Best Solution Fitness: 588079
New Best Solution Fitness: 587961
Generation: 3
New Best Solution Fitness: 585553
New Best Solution Fitness: 585401
Generation: 4
New Best Solution Fitness: 585007
Generation: 5
New Best Solution Fitness: 584850
New Best Solution Fitness: 584809
Generation: 6
New Best Solution Fitness: 584601
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.25556 
Mean sub-tour choices: 1.94444 
Best Solution Fitness: 584601 
--------------------------------------------- 
