--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 595293
New Best Solution Fitness: 594999
Generation: 3
New Best Solution Fitness: 587930
New Best Solution Fitness: 587671
Generation: 4
New Best Solution Fitness: 583356
New Best Solution Fitness: 583242
Generation: 5
New Best Solution Fitness: 583058
New Best Solution Fitness: 583042
Generation: 6
New Best Solution Fitness: 582990
New Best Solution Fitness: 582952
Generation: 7
New Best Solution Fitness: 582877
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 582798
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.66667 
Mean sub-tour choices: 1.86667 
Best Solution Fitness: 582798 
--------------------------------------------- 
