--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 584968
New Best Solution Fitness: 584793
New Best Solution Fitness: 584559
New Best Solution Fitness: 584463
Generation: 3
New Best Solution Fitness: 581431
New Best Solution Fitness: 581399
New Best Solution Fitness: 580758
Generation: 4
New Best Solution Fitness: 579709
New Best Solution Fitness: 579535
New Best Solution Fitness: 579480
Generation: 5
New Best Solution Fitness: 578537
New Best Solution Fitness: 578416
New Best Solution Fitness: 578363
New Best Solution Fitness: 577591
Generation: 6
New Best Solution Fitness: 577394
New Best Solution Fitness: 577220
Generation: 7
New Best Solution Fitness: 577201
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.86667 
Mean sub-tour choices: 2.1 
Best Solution Fitness: 577201 
--------------------------------------------- 
