--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 594484
New Best Solution Fitness: 594160
New Best Solution Fitness: 594150
New Best Solution Fitness: 594144
New Best Solution Fitness: 594123
New Best Solution Fitness: 594039
Generation: 3
New Best Solution Fitness: 589370
New Best Solution Fitness: 589330
New Best Solution Fitness: 589132
Generation: 4
New Best Solution Fitness: 585189
New Best Solution Fitness: 585168
Generation: 5
New Best Solution Fitness: 581127
New Best Solution Fitness: 581028
Generation: 6
New Best Solution Fitness: 580278
New Best Solution Fitness: 580261
New Best Solution Fitness: 580153
Generation: 7
New Best Solution Fitness: 580025
New Best Solution Fitness: 580008
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 579847
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.32222 
Mean sub-tour choices: 1.55556 
Best Solution Fitness: 579847 
--------------------------------------------- 
