--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 590902
New Best Solution Fitness: 590338
Generation: 3
New Best Solution Fitness: 588340
New Best Solution Fitness: 588297
New Best Solution Fitness: 588235
New Best Solution Fitness: 588194
New Best Solution Fitness: 588137
Generation: 4
New Best Solution Fitness: 587122
New Best Solution Fitness: 587117
New Best Solution Fitness: 587017
Generation: 5
New Best Solution Fitness: 586891
New Best Solution Fitness: 586886
Generation: 6
New Best Solution Fitness: 586044
Generation: 7
New Best Solution Fitness: 585797
Generation: 8
New Best Solution Fitness: 585787
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.08889 
Mean sub-tour choices: 2.23333 
Best Solution Fitness: 585787 
--------------------------------------------- 
