--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 590419
New Best Solution Fitness: 590175
Generation: 3
New Best Solution Fitness: 587970
New Best Solution Fitness: 587448
New Best Solution Fitness: 587324
Generation: 4
New Best Solution Fitness: 584172
New Best Solution Fitness: 583966
Generation: 5
New Best Solution Fitness: 583307
New Best Solution Fitness: 583008
Generation: 6
New Best Solution Fitness: 582986
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 5.31111 
Mean sub-tour choices: 2.87778 
Best Solution Fitness: 582986 
--------------------------------------------- 
