--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 597089
New Best Solution Fitness: 596560
New Best Solution Fitness: 596394
Generation: 3
New Best Solution Fitness: 594859
New Best Solution Fitness: 594660
Generation: 4
New Best Solution Fitness: 592300
Generation: 5
New Best Solution Fitness: 586459
Generation: 6
New Best Solution Fitness: 583308
New Best Solution Fitness: 583238
Generation: 7
New Best Solution Fitness: 581635
New Best Solution Fitness: 581627
Generation: 8
New Best Solution Fitness: 581329
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 5 
Mean sub-tour choices: 2.16667 
Best Solution Fitness: 581329 
--------------------------------------------- 
