--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 592616
New Best Solution Fitness: 592125
New Best Solution Fitness: 591365
New Best Solution Fitness: 591020
Generation: 3
New Best Solution Fitness: 586336
New Best Solution Fitness: 585948
New Best Solution Fitness: 585870
New Best Solution Fitness: 585803
Generation: 4
New Best Solution Fitness: 582542
New Best Solution Fitness: 582506
New Best Solution Fitness: 582242
Generation: 5
New Best Solution Fitness: 581847
New Best Solution Fitness: 581220
Generation: 6
New Best Solution Fitness: 580948
Generation: 7
New Best Solution Fitness: 580938
Generation: 8
New Best Solution Fitness: 580900
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 5.92222 
Mean sub-tour choices: 3.4 
Best Solution Fitness: 580900 
--------------------------------------------- 
