--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 593791
New Best Solution Fitness: 593464
New Best Solution Fitness: 593443
Generation: 3
New Best Solution Fitness: 587098
New Best Solution Fitness: 587060
Generation: 4
New Best Solution Fitness: 582126
Generation: 5
New Best Solution Fitness: 581415
Generation: 6
New Best Solution Fitness: 580532
New Best Solution Fitness: 580475
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 580438
New Best Solution Fitness: 579910
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.62222 
Mean sub-tour choices: 1.24444 
Best Solution Fitness: 579910 
--------------------------------------------- 
