--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 585353
New Best Solution Fitness: 585210
New Best Solution Fitness: 585067
New Best Solution Fitness: 584571
Generation: 3
New Best Solution Fitness: 580842
New Best Solution Fitness: 580766
Generation: 4
New Best Solution Fitness: 579720
New Best Solution Fitness: 579696
New Best Solution Fitness: 579353
Generation: 5
New Best Solution Fitness: 579329
New Best Solution Fitness: 579237
Generation: 6
New Best Solution Fitness: 579213
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 6.7 
Mean sub-tour choices: 2.53333 
Best Solution Fitness: 579213 
--------------------------------------------- 
