--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 599576
New Best Solution Fitness: 598952
Generation: 3
New Best Solution Fitness: 592363
New Best Solution Fitness: 592114
Generation: 4
New Best Solution Fitness: 586269
New Best Solution Fitness: 586240
New Best Solution Fitness: 586228
Generation: 5
New Best Solution Fitness: 584215
New Best Solution Fitness: 584186
Generation: 6
New Best Solution Fitness: 584166
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 5.44444 
Mean sub-tour choices: 1.98889 
Best Solution Fitness: 584166 
--------------------------------------------- 
