--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 584875
New Best Solution Fitness: 584866
New Best Solution Fitness: 584667
Generation: 3
New Best Solution Fitness: 583179
New Best Solution Fitness: 583176
New Best Solution Fitness: 583159
New Best Solution Fitness: 582543
Generation: 4
New Best Solution Fitness: 582022
New Best Solution Fitness: 581947
Generation: 5
New Best Solution Fitness: 581924
New Best Solution Fitness: 581318
Generation: 6
New Best Solution Fitness: 581283
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.8 
Mean sub-tour choices: 2.26667 
Best Solution Fitness: 581283 
--------------------------------------------- 
