--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 587848
New Best Solution Fitness: 587793
New Best Solution Fitness: 587653
Generation: 3
New Best Solution Fitness: 585435
New Best Solution Fitness: 585414
New Best Solution Fitness: 585388
Generation: 4
New Best Solution Fitness: 585011
New Best Solution Fitness: 584964
New Best Solution Fitness: 584455
Generation: 5
New Best Solution Fitness: 584434
New Best Solution Fitness: 584410
Generation: 6
New Best Solution Fitness: 584389
New Best Solution Fitness: 584363
Generation: 7
New Best Solution Fitness: 584355
Generation: 8
New Best Solution Fitness: 584345
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 6.33333 
Mean sub-tour choices: 3.11111 
Best Solution Fitness: 584345 
--------------------------------------------- 
