--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 590630
New Best Solution Fitness: 590511
New Best Solution Fitness: 590481
New Best Solution Fitness: 590395
Generation: 3
New Best Solution Fitness: 583402
New Best Solution Fitness: 583390
New Best Solution Fitness: 583336
Generation: 4
New Best Solution Fitness: 581596
New Best Solution Fitness: 581584
New Best Solution Fitness: 581577
Generation: 5
New Best Solution Fitness: 581290
New Best Solution Fitness: 581242
Generation: 6
New Best Solution Fitness: 580898
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 580871
Generation: 10
New Best Solution Fitness: 580360
New Best Solution Fitness: 580344
New Best Solution Fitness: 580304
New Best Solution Fitness: 579204
New Best Solution Fitness: 578408
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4 
Mean sub-tour choices: 1.97778 
Best Solution Fitness: 578408 
--------------------------------------------- 
