--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 592913
New Best Solution Fitness: 590972
Generation: 3
New Best Solution Fitness: 586738
New Best Solution Fitness: 586627
New Best Solution Fitness: 586477
Generation: 4
New Best Solution Fitness: 585781
New Best Solution Fitness: 585774
New Best Solution Fitness: 585764
Generation: 5
New Best Solution Fitness: 584724
New Best Solution Fitness: 584717
Generation: 6
New Best Solution Fitness: 584104
Generation: 7
New Best Solution Fitness: 583262
New Best Solution Fitness: 583207
Generation: 8
New Best Solution Fitness: 583123
Generation: 9
New Best Solution Fitness: 583047
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.31111 
Mean sub-tour choices: 1.81111 
Best Solution Fitness: 583047 
--------------------------------------------- 
