--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 593780
New Best Solution Fitness: 593543
New Best Solution Fitness: 593429
Generation: 3
New Best Solution Fitness: 584625
New Best Solution Fitness: 584242
Generation: 4
New Best Solution Fitness: 582659
New Best Solution Fitness: 582537
Generation: 5
New Best Solution Fitness: 582519
New Best Solution Fitness: 582512
New Best Solution Fitness: 582502
New Best Solution Fitness: 582474
Generation: 6
New Best Solution Fitness: 582434
New Best Solution Fitness: 582427
New Best Solution Fitness: 582417
Generation: 7
New Best Solution Fitness: 582410
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 7.27778 
Mean sub-tour choices: 2.27778 
Best Solution Fitness: 582410 
--------------------------------------------- 
