--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 590927
New Best Solution Fitness: 590235
New Best Solution Fitness: 589393
Generation: 3
New Best Solution Fitness: 588276
New Best Solution Fitness: 588239
New Best Solution Fitness: 587907
Generation: 4
New Best Solution Fitness: 587632
New Best Solution Fitness: 587622
New Best Solution Fitness: 587589
Generation: 5
New Best Solution Fitness: 587579
Generation: 6
New Best Solution Fitness: 587452
Generation: 7
New Best Solution Fitness: 586960
New Best Solution Fitness: 586933
Generation: 8
New Best Solution Fitness: 586899
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.05556 
Mean sub-tour choices: 2.63333 
Best Solution Fitness: 586899 
--------------------------------------------- 
