--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35857
New Best Solution Fitness: 35820
Generation: 3
New Best Solution Fitness: 35672
New Best Solution Fitness: 35632
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 35605
Generation: 7
New Best Solution Fitness: 35517
Generation: 8
Generation: 9
New Best Solution Fitness: 35274
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.4 
Mean sub-tour choices: 0.7 
Best Solution Fitness: 35274 
--------------------------------------------- 
