--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35722
New Best Solution Fitness: 35720
New Best Solution Fitness: 35635
Generation: 3
Generation: 4
Generation: 5
New Best Solution Fitness: 35562
New Best Solution Fitness: 35532
Generation: 6
New Best Solution Fitness: 35527
New Best Solution Fitness: 35524
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 35508
Generation: 10
New Best Solution Fitness: 35493
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.866667 
Mean sub-tour choices: 1.36667 
Best Solution Fitness: 35493 
--------------------------------------------- 
