--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35823
New Best Solution Fitness: 35790
New Best Solution Fitness: 35775
Generation: 3
New Best Solution Fitness: 35746
New Best Solution Fitness: 35739
New Best Solution Fitness: 35708
Generation: 4
New Best Solution Fitness: 35693
Generation: 5
New Best Solution Fitness: 35670
New Best Solution Fitness: 35632
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 35627
Generation: 9
Generation: 10
New Best Solution Fitness: 35533
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.644444 
Mean sub-tour choices: 1.12222 
Best Solution Fitness: 35533 
--------------------------------------------- 
