--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35540
New Best Solution Fitness: 35491
Generation: 3
New Best Solution Fitness: 35474
New Best Solution Fitness: 35435
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 35426
Generation: 7
New Best Solution Fitness: 35412
Generation: 8
New Best Solution Fitness: 35401
New Best Solution Fitness: 35394
Generation: 9
Generation: 10
New Best Solution Fitness: 35388
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.644444 
Mean sub-tour choices: 1.07778 
Best Solution Fitness: 35388 
--------------------------------------------- 
