--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35544
New Best Solution Fitness: 35462
Generation: 3
New Best Solution Fitness: 35416
Generation: 4
New Best Solution Fitness: 35411
New Best Solution Fitness: 35372
Generation: 5
New Best Solution Fitness: 35370
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 35369
Generation: 9
Generation: 10
New Best Solution Fitness: 35353
New Best Solution Fitness: 35278
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.333333 
Mean sub-tour choices: 0.611111 
Best Solution Fitness: 35278 
--------------------------------------------- 
