--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35818
New Best Solution Fitness: 35743
New Best Solution Fitness: 35706
New Best Solution Fitness: 35664
Generation: 3
New Best Solution Fitness: 35597
Generation: 4
New Best Solution Fitness: 35573
New Best Solution Fitness: 35568
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 35529
Generation: 8
New Best Solution Fitness: 35527
Generation: 9
Generation: 10
New Best Solution Fitness: 35510
New Best Solution Fitness: 35508
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.07778 
Mean sub-tour choices: 1.64444 
Best Solution Fitness: 35508 
--------------------------------------------- 
