--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35813
New Best Solution Fitness: 35798
New Best Solution Fitness: 35732
Generation: 3
New Best Solution Fitness: 35667
Generation: 4
New Best Solution Fitness: 35662
New Best Solution Fitness: 35606
Generation: 5
New Best Solution Fitness: 35505
Generation: 6
New Best Solution Fitness: 35479
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 35467
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.766667 
Mean sub-tour choices: 1.22222 
Best Solution Fitness: 35467 
--------------------------------------------- 
