--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35705
New Best Solution Fitness: 35606
Generation: 3
New Best Solution Fitness: 35552
New Best Solution Fitness: 35451
Generation: 4
New Best Solution Fitness: 35443
New Best Solution Fitness: 35435
Generation: 5
New Best Solution Fitness: 35434
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 35303
New Best Solution Fitness: 35295
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.666667 
Mean sub-tour choices: 1.16667 
Best Solution Fitness: 35295 
--------------------------------------------- 
