--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35811
New Best Solution Fitness: 35806
New Best Solution Fitness: 35750
Generation: 3
New Best Solution Fitness: 35708
Generation: 4
Generation: 5
New Best Solution Fitness: 35572
New Best Solution Fitness: 35566
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 35556
New Best Solution Fitness: 35539
New Best Solution Fitness: 35333
Generation: 10
New Best Solution Fitness: 35310
New Best Solution Fitness: 35299
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.644444 
Mean sub-tour choices: 1.06667 
Best Solution Fitness: 35299 
--------------------------------------------- 
