--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35756
New Best Solution Fitness: 35684
Generation: 3
New Best Solution Fitness: 35676
New Best Solution Fitness: 35576
Generation: 4
Generation: 5
New Best Solution Fitness: 35555
Generation: 6
Generation: 7
New Best Solution Fitness: 35403
Generation: 8
New Best Solution Fitness: 35334
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.577778 
Mean sub-tour choices: 1 
Best Solution Fitness: 35334 
--------------------------------------------- 
