--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35786
New Best Solution Fitness: 35760
Generation: 3
New Best Solution Fitness: 35624
New Best Solution Fitness: 35608
Generation: 4
New Best Solution Fitness: 35604
New Best Solution Fitness: 35601
Generation: 5
New Best Solution Fitness: 35597
Generation: 6
New Best Solution Fitness: 35526
Generation: 7
Generation: 8
New Best Solution Fitness: 35355
Generation: 9
New Best Solution Fitness: 35350
New Best Solution Fitness: 35342
Generation: 10
New Best Solution Fitness: 35336
New Best Solution Fitness: 35307
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.466667 
Mean sub-tour choices: 0.855556 
Best Solution Fitness: 35307 
--------------------------------------------- 
