--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35344
New Best Solution Fitness: 35336
New Best Solution Fitness: 35327
Generation: 3
New Best Solution Fitness: 35323
New Best Solution Fitness: 35317
New Best Solution Fitness: 35290
Generation: 4
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 35282
Generation: 8
New Best Solution Fitness: 35276
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.655556 
Mean sub-tour choices: 1.08889 
Best Solution Fitness: 35276 
--------------------------------------------- 
