--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35429
New Best Solution Fitness: 35426
Generation: 3
Generation: 4
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 35407
Generation: 8
Generation: 9
New Best Solution Fitness: 35405
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.666667 
Mean sub-tour choices: 1.13333 
Best Solution Fitness: 35405 
--------------------------------------------- 
