--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35525
Generation: 3
New Best Solution Fitness: 35460
New Best Solution Fitness: 35438
New Best Solution Fitness: 35397
Generation: 4
New Best Solution Fitness: 35374
Generation: 5
New Best Solution Fitness: 35310
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 35227
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.622222 
Mean sub-tour choices: 1.02222 
Best Solution Fitness: 35227 
--------------------------------------------- 
