--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35818
New Best Solution Fitness: 35750
New Best Solution Fitness: 35720
New Best Solution Fitness: 35712
Generation: 3
New Best Solution Fitness: 35695
New Best Solution Fitness: 35691
New Best Solution Fitness: 35667
Generation: 4
New Best Solution Fitness: 35663
Generation: 5
New Best Solution Fitness: 35662
Generation: 6
New Best Solution Fitness: 35659
New Best Solution Fitness: 35564
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 35538
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.888889 
Mean sub-tour choices: 1.32222 
Best Solution Fitness: 35538 
--------------------------------------------- 
