--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35720
New Best Solution Fitness: 35652
Generation: 3
New Best Solution Fitness: 35631
New Best Solution Fitness: 35614
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 35582
New Best Solution Fitness: 35569
New Best Solution Fitness: 35531
Generation: 7
New Best Solution Fitness: 35528
New Best Solution Fitness: 35518
Generation: 8
New Best Solution Fitness: 35515
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.533333 
Mean sub-tour choices: 0.911111 
Best Solution Fitness: 35515 
--------------------------------------------- 
