--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35524
New Best Solution Fitness: 35510
New Best Solution Fitness: 35494
Generation: 3
New Best Solution Fitness: 35489
Generation: 4
Generation: 5
New Best Solution Fitness: 35464
New Best Solution Fitness: 35440
New Best Solution Fitness: 35437
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 35418
New Best Solution Fitness: 35416
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.977778 
Mean sub-tour choices: 1.51111 
Best Solution Fitness: 35416 
--------------------------------------------- 
