--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35563
Generation: 3
New Best Solution Fitness: 35498
Generation: 4
New Best Solution Fitness: 35495
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 35490
Generation: 8
New Best Solution Fitness: 35451
New Best Solution Fitness: 35446
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.411111 
Mean sub-tour choices: 0.733333 
Best Solution Fitness: 35446 
--------------------------------------------- 
