--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35834
New Best Solution Fitness: 35822
New Best Solution Fitness: 35814
New Best Solution Fitness: 35812
Generation: 3
New Best Solution Fitness: 35725
Generation: 4
New Best Solution Fitness: 35676
New Best Solution Fitness: 35669
Generation: 5
New Best Solution Fitness: 35626
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.611111 
Mean sub-tour choices: 1.03333 
Best Solution Fitness: 35626 
--------------------------------------------- 
