--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35887
New Best Solution Fitness: 35777
Generation: 3
New Best Solution Fitness: 35681
New Best Solution Fitness: 35670
Generation: 4
New Best Solution Fitness: 35584
Generation: 5
New Best Solution Fitness: 35569
Generation: 6
Generation: 7
New Best Solution Fitness: 35522
New Best Solution Fitness: 35511
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.7 
Mean sub-tour choices: 1.13333 
Best Solution Fitness: 35511 
--------------------------------------------- 
