--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35656
New Best Solution Fitness: 35643
New Best Solution Fitness: 35620
Generation: 3
New Best Solution Fitness: 35615
New Best Solution Fitness: 35597
Generation: 4
New Best Solution Fitness: 35589
Generation: 5
New Best Solution Fitness: 35541
Generation: 6
Generation: 7
New Best Solution Fitness: 35533
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 35515
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.566667 
Mean sub-tour choices: 0.933333 
Best Solution Fitness: 35515 
--------------------------------------------- 
