--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35427
Generation: 3
New Best Solution Fitness: 35413
Generation: 4
New Best Solution Fitness: 35410
Generation: 5
Generation: 6
New Best Solution Fitness: 35397
Generation: 7
Generation: 8
New Best Solution Fitness: 35392
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.388889 
Mean sub-tour choices: 0.7 
Best Solution Fitness: 35392 
--------------------------------------------- 
