--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35630
New Best Solution Fitness: 35627
New Best Solution Fitness: 35589
New Best Solution Fitness: 35587
New Best Solution Fitness: 35585
Generation: 3
New Best Solution Fitness: 35539
New Best Solution Fitness: 35511
Generation: 4
New Best Solution Fitness: 35483
Generation: 5
Generation: 6
New Best Solution Fitness: 35462
Generation: 7
New Best Solution Fitness: 35444
New Best Solution Fitness: 35435
Generation: 8
Generation: 9
New Best Solution Fitness: 35420
Generation: 10
New Best Solution Fitness: 35382
New Best Solution Fitness: 35373
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.933333 
Mean sub-tour choices: 1.46667 
Best Solution Fitness: 35373 
--------------------------------------------- 
