--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35751
Generation: 3
New Best Solution Fitness: 35567
Generation: 4
Generation: 5
New Best Solution Fitness: 35543
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 35527
Generation: 9
Generation: 10
New Best Solution Fitness: 35375
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.311111 
Mean sub-tour choices: 0.566667 
Best Solution Fitness: 35375 
--------------------------------------------- 
