--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35734
New Best Solution Fitness: 35718
New Best Solution Fitness: 35692
Generation: 3
New Best Solution Fitness: 35622
New Best Solution Fitness: 35610
Generation: 4
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 35569
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.777778 
Mean sub-tour choices: 1.31111 
Best Solution Fitness: 35569 
--------------------------------------------- 
