--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35512
New Best Solution Fitness: 35495
New Best Solution Fitness: 35491
Generation: 3
Generation: 4
New Best Solution Fitness: 35486
Generation: 5
New Best Solution Fitness: 35458
New Best Solution Fitness: 35447
Generation: 6
Generation: 7
New Best Solution Fitness: 35345
New Best Solution Fitness: 35334
Generation: 8
New Best Solution Fitness: 35295
Generation: 9
New Best Solution Fitness: 35290
New Best Solution Fitness: 35282
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.844444 
Mean sub-tour choices: 1.4 
Best Solution Fitness: 35282 
--------------------------------------------- 
