--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35494
New Best Solution Fitness: 35490
New Best Solution Fitness: 35481
Generation: 3
New Best Solution Fitness: 35391
New Best Solution Fitness: 35382
Generation: 4
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 35341
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.444444 
Mean sub-tour choices: 0.788889 
Best Solution Fitness: 35341 
--------------------------------------------- 
