--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35533
New Best Solution Fitness: 35529
New Best Solution Fitness: 35527
Generation: 3
New Best Solution Fitness: 35472
New Best Solution Fitness: 35464
Generation: 4
New Best Solution Fitness: 35460
Generation: 5
Generation: 6
New Best Solution Fitness: 35451
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 35446
Generation: 10
New Best Solution Fitness: 35445
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.2 
Mean sub-tour choices: 1.84444 
Best Solution Fitness: 35445 
--------------------------------------------- 
