--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35704
New Best Solution Fitness: 35681
Generation: 3
New Best Solution Fitness: 35468
New Best Solution Fitness: 35447
Generation: 4
New Best Solution Fitness: 35417
Generation: 5
New Best Solution Fitness: 35415
Generation: 6
New Best Solution Fitness: 35395
New Best Solution Fitness: 35391
Generation: 7
New Best Solution Fitness: 35281
New Best Solution Fitness: 35217
Generation: 8
Generation: 9
New Best Solution Fitness: 35202
Generation: 10
New Best Solution Fitness: 35196
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.577778 
Mean sub-tour choices: 0.966667 
Best Solution Fitness: 35196 
--------------------------------------------- 
