--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35526
New Best Solution Fitness: 35519
Generation: 3
New Best Solution Fitness: 35438
Generation: 4
New Best Solution Fitness: 35429
Generation: 5
New Best Solution Fitness: 35420
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.344444 
Mean sub-tour choices: 0.611111 
Best Solution Fitness: 35420 
--------------------------------------------- 
