--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35781
Generation: 3
New Best Solution Fitness: 35639
Generation: 4
New Best Solution Fitness: 35525
Generation: 5
New Best Solution Fitness: 35447
Generation: 6
New Best Solution Fitness: 35443
Generation: 7
Generation: 8
New Best Solution Fitness: 35322
Generation: 9
New Best Solution Fitness: 35309
Generation: 10
New Best Solution Fitness: 35258
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.5 
Mean sub-tour choices: 0.844444 
Best Solution Fitness: 35258 
--------------------------------------------- 
