--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35936
New Best Solution Fitness: 35783
New Best Solution Fitness: 35764
Generation: 3
New Best Solution Fitness: 35754
New Best Solution Fitness: 35689
Generation: 4
New Best Solution Fitness: 35573
Generation: 5
New Best Solution Fitness: 35538
New Best Solution Fitness: 35527
Generation: 6
New Best Solution Fitness: 35386
Generation: 7
New Best Solution Fitness: 35374
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.422222 
Mean sub-tour choices: 0.755556 
Best Solution Fitness: 35374 
--------------------------------------------- 
