--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35606
New Best Solution Fitness: 35575
Generation: 3
New Best Solution Fitness: 35572
New Best Solution Fitness: 35539
Generation: 4
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 35454
New Best Solution Fitness: 35449
Generation: 9
New Best Solution Fitness: 35437
New Best Solution Fitness: 35432
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.04444 
Mean sub-tour choices: 1.53333 
Best Solution Fitness: 35432 
--------------------------------------------- 
