--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35464
New Best Solution Fitness: 35459
Generation: 3
New Best Solution Fitness: 35458
Generation: 4
Generation: 5
New Best Solution Fitness: 35420
Generation: 6
New Best Solution Fitness: 35381
Generation: 7
Generation: 8
New Best Solution Fitness: 35354
Generation: 9
New Best Solution Fitness: 35313
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.422222 
Mean sub-tour choices: 0.7 
Best Solution Fitness: 35313 
--------------------------------------------- 
