--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35839
Generation: 3
Generation: 4
Generation: 5
New Best Solution Fitness: 35670
Generation: 6
New Best Solution Fitness: 35634
Generation: 7
New Best Solution Fitness: 35491
Generation: 8
New Best Solution Fitness: 35454
New Best Solution Fitness: 35425
Generation: 9
New Best Solution Fitness: 35414
Generation: 10
New Best Solution Fitness: 35405
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.422222 
Mean sub-tour choices: 0.733333 
Best Solution Fitness: 35405 
--------------------------------------------- 
