--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35302
Generation: 3
New Best Solution Fitness: 35249
New Best Solution Fitness: 35240
Generation: 4
New Best Solution Fitness: 35232
Generation: 5
Generation: 6
New Best Solution Fitness: 35229
Generation: 7
Generation: 8
New Best Solution Fitness: 35228
Generation: 9
New Best Solution Fitness: 35205
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.6 
Mean sub-tour choices: 1.01111 
Best Solution Fitness: 35205 
--------------------------------------------- 
