--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35685
New Best Solution Fitness: 35676
New Best Solution Fitness: 35660
Generation: 3
New Best Solution Fitness: 35592
New Best Solution Fitness: 35567
Generation: 4
New Best Solution Fitness: 35546
Generation: 5
New Best Solution Fitness: 35440
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 35347
New Best Solution Fitness: 35328
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.633333 
Mean sub-tour choices: 1.05556 
Best Solution Fitness: 35328 
--------------------------------------------- 
