--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35819
New Best Solution Fitness: 35791
New Best Solution Fitness: 35740
Generation: 3
New Best Solution Fitness: 35631
New Best Solution Fitness: 35603
New Best Solution Fitness: 35601
Generation: 4
Generation: 5
New Best Solution Fitness: 35576
New Best Solution Fitness: 35574
Generation: 6
New Best Solution Fitness: 35542
Generation: 7
New Best Solution Fitness: 35501
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 35477
New Best Solution Fitness: 35440
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.711111 
Mean sub-tour choices: 1.23333 
Best Solution Fitness: 35440 
--------------------------------------------- 
