--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35697
Generation: 3
New Best Solution Fitness: 35621
Generation: 4
New Best Solution Fitness: 35568
New Best Solution Fitness: 35562
Generation: 5
New Best Solution Fitness: 35554
New Best Solution Fitness: 35553
Generation: 6
New Best Solution Fitness: 35487
New Best Solution Fitness: 35479
Generation: 7
New Best Solution Fitness: 35431
Generation: 8
New Best Solution Fitness: 35394
Generation: 9
New Best Solution Fitness: 35327
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.5 
Mean sub-tour choices: 0.833333 
Best Solution Fitness: 35327 
--------------------------------------------- 
