--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35470
New Best Solution Fitness: 35446
Generation: 3
New Best Solution Fitness: 35431
Generation: 4
Generation: 5
New Best Solution Fitness: 35365
New Best Solution Fitness: 35329
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 35276
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.788889 
Mean sub-tour choices: 1.24444 
Best Solution Fitness: 35276 
--------------------------------------------- 
