--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35686
New Best Solution Fitness: 35659
Generation: 3
New Best Solution Fitness: 35389
Generation: 4
New Best Solution Fitness: 35364
Generation: 5
New Best Solution Fitness: 35353
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 35332
Generation: 9
New Best Solution Fitness: 35319
New Best Solution Fitness: 35276
Generation: 10
New Best Solution Fitness: 35263
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.466667 
Mean sub-tour choices: 0.844444 
Best Solution Fitness: 35263 
--------------------------------------------- 
