--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35384
New Best Solution Fitness: 35373
Generation: 3
New Best Solution Fitness: 35371
Generation: 4
New Best Solution Fitness: 35353
Generation: 5
New Best Solution Fitness: 35338
Generation: 6
New Best Solution Fitness: 35333
Generation: 7
New Best Solution Fitness: 35300
Generation: 8
Generation: 9
New Best Solution Fitness: 35240
Generation: 10
New Best Solution Fitness: 35239
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.966667 
Mean sub-tour choices: 1.53333 
Best Solution Fitness: 35239 
--------------------------------------------- 
