--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35657
New Best Solution Fitness: 35648
New Best Solution Fitness: 35620
Generation: 3
New Best Solution Fitness: 35322
Generation: 4
New Best Solution Fitness: 35311
Generation: 5
Generation: 6
New Best Solution Fitness: 35247
Generation: 7
New Best Solution Fitness: 35207
New Best Solution Fitness: 35179
Generation: 8
New Best Solution Fitness: 35178
Generation: 9
Generation: 10
New Best Solution Fitness: 35171
New Best Solution Fitness: 35163
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.977778 
Mean sub-tour choices: 1.4 
Best Solution Fitness: 35163 
--------------------------------------------- 
