--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35824
New Best Solution Fitness: 35806
New Best Solution Fitness: 35795
Generation: 3
New Best Solution Fitness: 35713
New Best Solution Fitness: 35683
New Best Solution Fitness: 35653
Generation: 4
New Best Solution Fitness: 35648
Generation: 5
New Best Solution Fitness: 35629
Generation: 6
Generation: 7
New Best Solution Fitness: 35601
New Best Solution Fitness: 35597
Generation: 8
New Best Solution Fitness: 35578
New Best Solution Fitness: 35574
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.933333 
Mean sub-tour choices: 1.5 
Best Solution Fitness: 35574 
--------------------------------------------- 
