--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35653
Generation: 3
New Best Solution Fitness: 35599
New Best Solution Fitness: 35595
Generation: 4
New Best Solution Fitness: 35520
New Best Solution Fitness: 35516
Generation: 5
Generation: 6
New Best Solution Fitness: 35514
New Best Solution Fitness: 35513
New Best Solution Fitness: 35509
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.2 
Mean sub-tour choices: 1.78889 
Best Solution Fitness: 35509 
--------------------------------------------- 
