--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35591
New Best Solution Fitness: 35566
New Best Solution Fitness: 35563
New Best Solution Fitness: 35557
New Best Solution Fitness: 35542
Generation: 3
New Best Solution Fitness: 35541
New Best Solution Fitness: 35532
Generation: 4
New Best Solution Fitness: 35523
New Best Solution Fitness: 35514
Generation: 5
New Best Solution Fitness: 35489
Generation: 6
New Best Solution Fitness: 35444
New Best Solution Fitness: 35442
Generation: 7
Generation: 8
New Best Solution Fitness: 35354
Generation: 9
New Best Solution Fitness: 35340
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.06667 
Mean sub-tour choices: 1.67778 
Best Solution Fitness: 35340 
--------------------------------------------- 
