--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35433
Generation: 3
Generation: 4
New Best Solution Fitness: 35404
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 35395
Generation: 8
New Best Solution Fitness: 35383
Generation: 9
New Best Solution Fitness: 35371
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.6 
Mean sub-tour choices: 0.966667 
Best Solution Fitness: 35371 
--------------------------------------------- 
