--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35680
New Best Solution Fitness: 35665
Generation: 3
New Best Solution Fitness: 35617
New Best Solution Fitness: 35604
Generation: 4
New Best Solution Fitness: 35552
Generation: 5
New Best Solution Fitness: 35535
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 35404
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.255556 
Mean sub-tour choices: 0.466667 
Best Solution Fitness: 35404 
--------------------------------------------- 
