--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35699
New Best Solution Fitness: 35688
Generation: 3
Generation: 4
New Best Solution Fitness: 35683
Generation: 5
New Best Solution Fitness: 35634
New Best Solution Fitness: 35629
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 35516
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.411111 
Mean sub-tour choices: 0.688889 
Best Solution Fitness: 35516 
--------------------------------------------- 
