--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35740
Generation: 3
New Best Solution Fitness: 35729
Generation: 4
New Best Solution Fitness: 35720
New Best Solution Fitness: 35710
Generation: 5
Generation: 6
New Best Solution Fitness: 35575
New Best Solution Fitness: 35568
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 35472
New Best Solution Fitness: 35392
Generation: 10
New Best Solution Fitness: 35387
New Best Solution Fitness: 35381
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.455556 
Mean sub-tour choices: 0.822222 
Best Solution Fitness: 35381 
--------------------------------------------- 
