--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35376
Generation: 3
New Best Solution Fitness: 35363
Generation: 4
New Best Solution Fitness: 35353
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 35320
New Best Solution Fitness: 35285
Generation: 8
New Best Solution Fitness: 35278
Generation: 9
New Best Solution Fitness: 35253
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.733333 
Mean sub-tour choices: 1.18889 
Best Solution Fitness: 35253 
--------------------------------------------- 
