--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35600
Generation: 3
New Best Solution Fitness: 35530
Generation: 4
New Best Solution Fitness: 35527
Generation: 5
New Best Solution Fitness: 35357
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.377778 
Mean sub-tour choices: 0.588889 
Best Solution Fitness: 35357 
--------------------------------------------- 
