--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35544
Generation: 3
Generation: 4
New Best Solution Fitness: 35534
New Best Solution Fitness: 35476
Generation: 5
New Best Solution Fitness: 35456
Generation: 6
New Best Solution Fitness: 35410
New Best Solution Fitness: 35408
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 35276
Generation: 10
New Best Solution Fitness: 35260
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.722222 
Mean sub-tour choices: 1.15556 
Best Solution Fitness: 35260 
--------------------------------------------- 
