--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35516
New Best Solution Fitness: 35472
New Best Solution Fitness: 35471
Generation: 3
New Best Solution Fitness: 35438
New Best Solution Fitness: 35437
Generation: 4
New Best Solution Fitness: 35428
New Best Solution Fitness: 35424
Generation: 5
New Best Solution Fitness: 35401
New Best Solution Fitness: 35397
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 35390
Generation: 10
New Best Solution Fitness: 35294
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.23333 
Mean sub-tour choices: 1.83333 
Best Solution Fitness: 35294 
--------------------------------------------- 
