--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35773
New Best Solution Fitness: 35753
New Best Solution Fitness: 35740
Generation: 3
New Best Solution Fitness: 35737
New Best Solution Fitness: 35724
Generation: 4
New Best Solution Fitness: 35681
Generation: 5
New Best Solution Fitness: 35574
New Best Solution Fitness: 35552
Generation: 6
New Best Solution Fitness: 35480
New Best Solution Fitness: 35478
Generation: 7
Generation: 8
New Best Solution Fitness: 35451
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.722222 
Mean sub-tour choices: 1.15556 
Best Solution Fitness: 35451 
--------------------------------------------- 
