--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35895
Generation: 3
New Best Solution Fitness: 35836
Generation: 4
New Best Solution Fitness: 35637
New Best Solution Fitness: 35531
Generation: 5
Generation: 6
New Best Solution Fitness: 35504
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 35470
Generation: 10
New Best Solution Fitness: 35156
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.755556 
Mean sub-tour choices: 1.22222 
Best Solution Fitness: 35156 
--------------------------------------------- 
