--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35435
New Best Solution Fitness: 35386
Generation: 3
New Best Solution Fitness: 35367
Generation: 4
Generation: 5
New Best Solution Fitness: 35356
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 35355
Generation: 9
New Best Solution Fitness: 35329
Generation: 10
New Best Solution Fitness: 35307
New Best Solution Fitness: 35280
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.433333 
Mean sub-tour choices: 0.811111 
Best Solution Fitness: 35280 
--------------------------------------------- 
