--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35695
New Best Solution Fitness: 35675
Generation: 3
New Best Solution Fitness: 35516
Generation: 4
New Best Solution Fitness: 35507
Generation: 5
New Best Solution Fitness: 35433
Generation: 6
New Best Solution Fitness: 35425
Generation: 7
New Best Solution Fitness: 35413
Generation: 8
New Best Solution Fitness: 35406
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.666667 
Mean sub-tour choices: 1.13333 
Best Solution Fitness: 35406 
--------------------------------------------- 
