--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35758
New Best Solution Fitness: 35756
New Best Solution Fitness: 35727
Generation: 3
New Best Solution Fitness: 35662
New Best Solution Fitness: 35643
New Best Solution Fitness: 35631
Generation: 4
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 35592
New Best Solution Fitness: 35588
Generation: 10
New Best Solution Fitness: 35369
New Best Solution Fitness: 35352
New Best Solution Fitness: 35292
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.977778 
Mean sub-tour choices: 1.66667 
Best Solution Fitness: 35292 
--------------------------------------------- 
