--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35567
New Best Solution Fitness: 35475
Generation: 3
New Best Solution Fitness: 35462
New Best Solution Fitness: 35453
Generation: 4
New Best Solution Fitness: 35436
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 35400
New Best Solution Fitness: 35392
Generation: 9
New Best Solution Fitness: 35364
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.788889 
Mean sub-tour choices: 1.31111 
Best Solution Fitness: 35364 
--------------------------------------------- 
