--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35403
New Best Solution Fitness: 35390
Generation: 3
New Best Solution Fitness: 35385
Generation: 4
New Best Solution Fitness: 35381
Generation: 5
Generation: 6
New Best Solution Fitness: 35379
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.6 
Mean sub-tour choices: 1.08889 
Best Solution Fitness: 35379 
--------------------------------------------- 
