--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35750
New Best Solution Fitness: 35742
New Best Solution Fitness: 35725
Generation: 3
New Best Solution Fitness: 35712
Generation: 4
Generation: 5
New Best Solution Fitness: 35687
Generation: 6
Generation: 7
New Best Solution Fitness: 35441
New Best Solution Fitness: 35415
Generation: 8
New Best Solution Fitness: 35406
Generation: 9
Generation: 10
New Best Solution Fitness: 35398
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.766667 
Mean sub-tour choices: 1.22222 
Best Solution Fitness: 35398 
--------------------------------------------- 
