--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35872
New Best Solution Fitness: 35790
Generation: 3
New Best Solution Fitness: 35687
New Best Solution Fitness: 35678
Generation: 4
New Best Solution Fitness: 35675
New Best Solution Fitness: 35647
Generation: 5
New Best Solution Fitness: 35624
New Best Solution Fitness: 35569
New Best Solution Fitness: 35553
Generation: 6
New Best Solution Fitness: 35504
New Best Solution Fitness: 35492
New Best Solution Fitness: 35472
Generation: 7
New Best Solution Fitness: 35460
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.11111 
Mean sub-tour choices: 1.8 
Best Solution Fitness: 35460 
--------------------------------------------- 
