--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35672
New Best Solution Fitness: 35657
Generation: 3
New Best Solution Fitness: 35538
Generation: 4
New Best Solution Fitness: 35452
Generation: 5
New Best Solution Fitness: 35433
Generation: 6
Generation: 7
New Best Solution Fitness: 35416
Generation: 8
Generation: 9
New Best Solution Fitness: 35413
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.5 
Mean sub-tour choices: 0.855556 
Best Solution Fitness: 35413 
--------------------------------------------- 
