--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35917
Generation: 3
New Best Solution Fitness: 35872
Generation: 4
New Best Solution Fitness: 35617
New Best Solution Fitness: 35567
Generation: 5
New Best Solution Fitness: 35451
New Best Solution Fitness: 35433
New Best Solution Fitness: 35413
Generation: 6
New Best Solution Fitness: 35397
Generation: 7
New Best Solution Fitness: 35380
New Best Solution Fitness: 35329
Generation: 8
New Best Solution Fitness: 35327
New Best Solution Fitness: 35318
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.377778 
Mean sub-tour choices: 0.666667 
Best Solution Fitness: 35318 
--------------------------------------------- 
