--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35559
Generation: 3
New Best Solution Fitness: 35549
Generation: 4
New Best Solution Fitness: 35513
Generation: 5
New Best Solution Fitness: 35496
New Best Solution Fitness: 35492
Generation: 6
Generation: 7
New Best Solution Fitness: 35472
New Best Solution Fitness: 35469
Generation: 8
New Best Solution Fitness: 35448
New Best Solution Fitness: 35426
Generation: 9
Generation: 10
New Best Solution Fitness: 35380
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.755556 
Mean sub-tour choices: 1.26667 
Best Solution Fitness: 35380 
--------------------------------------------- 
