--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35447
New Best Solution Fitness: 35444
Generation: 3
Generation: 4
New Best Solution Fitness: 35403
Generation: 5
New Best Solution Fitness: 35402
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 35400
New Best Solution Fitness: 35397
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.611111 
Mean sub-tour choices: 1.05556 
Best Solution Fitness: 35397 
--------------------------------------------- 
