--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35689
New Best Solution Fitness: 35643
Generation: 3
New Best Solution Fitness: 35523
New Best Solution Fitness: 35488
Generation: 4
New Best Solution Fitness: 35461
New Best Solution Fitness: 35456
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 35455
New Best Solution Fitness: 35452
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.533333 
Mean sub-tour choices: 0.855556 
Best Solution Fitness: 35452 
--------------------------------------------- 
