--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35507
New Best Solution Fitness: 35427
Generation: 3
New Best Solution Fitness: 35423
New Best Solution Fitness: 35390
Generation: 4
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 35381
Generation: 8
New Best Solution Fitness: 35377
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.02222 
Mean sub-tour choices: 1.63333 
Best Solution Fitness: 35377 
--------------------------------------------- 
