--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35709
Generation: 3
New Best Solution Fitness: 35701
Generation: 4
New Best Solution Fitness: 35644
New Best Solution Fitness: 35630
Generation: 5
New Best Solution Fitness: 35436
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 35421
Generation: 10
New Best Solution Fitness: 35406
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.466667 
Mean sub-tour choices: 0.833333 
Best Solution Fitness: 35406 
--------------------------------------------- 
