--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35585
New Best Solution Fitness: 35538
Generation: 3
New Best Solution Fitness: 35522
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 35464
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 35463
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.15556 
Mean sub-tour choices: 1.7 
Best Solution Fitness: 35463 
--------------------------------------------- 
