--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35800
New Best Solution Fitness: 35797
New Best Solution Fitness: 35748
Generation: 3
New Best Solution Fitness: 35651
New Best Solution Fitness: 35639
Generation: 4
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.388889 
Mean sub-tour choices: 0.677778 
Best Solution Fitness: 35639 
--------------------------------------------- 
