--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35367
New Best Solution Fitness: 35350
Generation: 3
New Best Solution Fitness: 35345
New Best Solution Fitness: 35339
Generation: 4
New Best Solution Fitness: 35336
Generation: 5
New Best Solution Fitness: 35333
New Best Solution Fitness: 35321
New Best Solution Fitness: 35316
New Best Solution Fitness: 35304
Generation: 6
New Best Solution Fitness: 35302
Generation: 7
New Best Solution Fitness: 35296
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.655556 
Mean sub-tour choices: 1 
Best Solution Fitness: 35296 
--------------------------------------------- 
