--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35837
New Best Solution Fitness: 35831
Generation: 3
New Best Solution Fitness: 35791
New Best Solution Fitness: 35785
Generation: 4
New Best Solution Fitness: 35769
Generation: 5
New Best Solution Fitness: 35704
Generation: 6
New Best Solution Fitness: 35620
Generation: 7
New Best Solution Fitness: 35506
Generation: 8
New Best Solution Fitness: 35452
Generation: 9
Generation: 10
New Best Solution Fitness: 35447
New Best Solution Fitness: 35337
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.777778 
Mean sub-tour choices: 1.25556 
Best Solution Fitness: 35337 
--------------------------------------------- 
