--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35721
New Best Solution Fitness: 35661
New Best Solution Fitness: 35651
New Best Solution Fitness: 35645
New Best Solution Fitness: 35640
Generation: 3
New Best Solution Fitness: 35610
New Best Solution Fitness: 35606
Generation: 4
Generation: 5
New Best Solution Fitness: 35593
Generation: 6
Generation: 7
New Best Solution Fitness: 35572
New Best Solution Fitness: 35545
New Best Solution Fitness: 35539
New Best Solution Fitness: 35480
Generation: 8
New Best Solution Fitness: 35455
Generation: 9
New Best Solution Fitness: 35454
New Best Solution Fitness: 35429
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.22222 
Mean sub-tour choices: 1.94444 
Best Solution Fitness: 35429 
--------------------------------------------- 
