--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35569
New Best Solution Fitness: 35552
Generation: 3
New Best Solution Fitness: 35461
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 35420
Generation: 7
New Best Solution Fitness: 35393
Generation: 8
Generation: 9
New Best Solution Fitness: 35385
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.266667 
Mean sub-tour choices: 0.511111 
Best Solution Fitness: 35385 
--------------------------------------------- 
