--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35836
New Best Solution Fitness: 35743
Generation: 3
New Best Solution Fitness: 35707
New Best Solution Fitness: 35697
New Best Solution Fitness: 35651
Generation: 4
New Best Solution Fitness: 35643
Generation: 5
Generation: 6
New Best Solution Fitness: 35506
New Best Solution Fitness: 35492
Generation: 7
New Best Solution Fitness: 35465
Generation: 8
Generation: 9
New Best Solution Fitness: 35455
Generation: 10
New Best Solution Fitness: 35450
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.02222 
Mean sub-tour choices: 1.52222 
Best Solution Fitness: 35450 
--------------------------------------------- 
