--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35543
New Best Solution Fitness: 35460
Generation: 3
New Best Solution Fitness: 35384
Generation: 4
Generation: 5
New Best Solution Fitness: 35318
Generation: 6
New Best Solution Fitness: 35285
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 35272
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.844444 
Mean sub-tour choices: 1.37778 
Best Solution Fitness: 35272 
--------------------------------------------- 
