--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35886
New Best Solution Fitness: 35853
New Best Solution Fitness: 35820
Generation: 3
New Best Solution Fitness: 35752
New Best Solution Fitness: 35719
New Best Solution Fitness: 35700
Generation: 4
Generation: 5
New Best Solution Fitness: 35464
New Best Solution Fitness: 35456
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 35451
Generation: 10
New Best Solution Fitness: 35410
New Best Solution Fitness: 35407
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.655556 
Mean sub-tour choices: 1.06667 
Best Solution Fitness: 35407 
--------------------------------------------- 
