--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35684
New Best Solution Fitness: 35651
New Best Solution Fitness: 35607
Generation: 3
New Best Solution Fitness: 35542
New Best Solution Fitness: 35509
Generation: 4
New Best Solution Fitness: 35465
Generation: 5
New Best Solution Fitness: 35436
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 35432
Generation: 9
Generation: 10
New Best Solution Fitness: 35390
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.633333 
Mean sub-tour choices: 0.988889 
Best Solution Fitness: 35390 
--------------------------------------------- 
