--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35559
New Best Solution Fitness: 35540
New Best Solution Fitness: 35529
Generation: 3
New Best Solution Fitness: 35486
New Best Solution Fitness: 35442
Generation: 4
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 35354
New Best Solution Fitness: 35344
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.8 
Mean sub-tour choices: 1.34444 
Best Solution Fitness: 35344 
--------------------------------------------- 
