--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35338
New Best Solution Fitness: 35311
Generation: 3
New Best Solution Fitness: 35307
Generation: 4
New Best Solution Fitness: 35293
New Best Solution Fitness: 35274
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 35270
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.644444 
Mean sub-tour choices: 1.08889 
Best Solution Fitness: 35270 
--------------------------------------------- 
