--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35620
Generation: 3
New Best Solution Fitness: 35438
Generation: 4
New Best Solution Fitness: 35396
New Best Solution Fitness: 35395
New Best Solution Fitness: 35383
Generation: 5
New Best Solution Fitness: 35382
New Best Solution Fitness: 35374
Generation: 6
New Best Solution Fitness: 35370
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.766667 
Mean sub-tour choices: 1.16667 
Best Solution Fitness: 35370 
--------------------------------------------- 
