--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35538
New Best Solution Fitness: 35529
New Best Solution Fitness: 35521
Generation: 3
New Best Solution Fitness: 35485
New Best Solution Fitness: 35469
Generation: 4
New Best Solution Fitness: 35439
Generation: 5
New Best Solution Fitness: 35421
New Best Solution Fitness: 35415
Generation: 6
New Best Solution Fitness: 35376
New Best Solution Fitness: 35297
New Best Solution Fitness: 35239
Generation: 7
New Best Solution Fitness: 35238
New Best Solution Fitness: 35213
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.04444 
Mean sub-tour choices: 1.64444 
Best Solution Fitness: 35213 
--------------------------------------------- 
