--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Black Box Generational 
Population: 10
Mutation probability: 1
Crossover probability: 0.0018797
---------------
Job Complete 
Iterations: 2830240
Best Solution Fitness: 95835
--------------------------------------------- 
