NAME: gpxtest14
TYPE: TSP
COMMENT: 14-Staedte in Burma (Zaw Win)
DIMENSION: 14
EDGE_WEIGHT_TYPE: GEO
EDGE_WEIGHT_FORMAT: FUNCTION 
DISPLAY_DATA_TYPE: COORD_DISPLAY
NODE_COORD_SECTION
   1  2.0         3.5
   2  4.5         3.5
   3  4.5         2.0
   4  3.5         1.0
   5  8.0         1.0
   6  7.0         2.0
   7  7.0         3.5
   8  8.0         4.5
   9  9.5         2.5
  10  2.0         7.0
  11  3.0         6.0
  12  1.0         6.0
  13  1.0         5.0
  14  3.0         5.0
EOF



