NAME: test14
TYPE: TSP
COMMENT: 14-Staedte in Burma (Zaw Win)
DIMENSION: 14
EDGE_WEIGHT_TYPE: GEO
EDGE_WEIGHT_FORMAT: FUNCTION 
DISPLAY_DATA_TYPE: COORD_DISPLAY
NODE_COORD_SECTION
   1  100.0         500.0
   2  200.0         400.0
   3  50.0          300.0
   4  250.0         100.0
   5  400.0         150.0
   6  650.0         200.0
   7  800.0         250.0
   8  850.0         350.0
   9  700.0         400.0
  10  800.0         500.0
  11  700.0         600.0
  12  600.0         600.0
  13  400.0         300.0
  14  400.0         550.0
EOF



