NAME: test14
TYPE: TSP
COMMENT: 14-Staedte in Burma (Zaw Win)
DIMENSION: 14
EDGE_WEIGHT_TYPE: GEO
EDGE_WEIGHT_FORMAT: FUNCTION 
DISPLAY_DATA_TYPE: COORD_DISPLAY
NODE_COORD_SECTION
   1  1.0         5.0
   2  2.0         4.0
   3  0.5         3.0
   4  2.5         1.0
   5  4.0         1.5
   6  6.5         2.0
   7  8.0         2.5
   8  8.5         3.5
   9  7.0         4.0
  10  8.0         5.0
  11  7.0         5.5
  12  6.0         6.0
  13  4.0         3.0
  14  4.0         5.5
EOF



