--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88958
New Best Solution Fitness: 88764
Generation: 3
New Best Solution Fitness: 88480
New Best Solution Fitness: 88424
Generation: 4
New Best Solution Fitness: 88384
Generation: 5
New Best Solution Fitness: 88376
Generation: 6
New Best Solution Fitness: 88167
New Best Solution Fitness: 88123
Generation: 7
New Best Solution Fitness: 88017
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 88000
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.866667 
Mean sub-tour choices: 1.44444 
Best Solution Fitness: 88000 
--------------------------------------------- 
