--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88531
New Best Solution Fitness: 88335
Generation: 3
New Best Solution Fitness: 88233
New Best Solution Fitness: 88211
Generation: 4
Generation: 5
New Best Solution Fitness: 88138
Generation: 6
Generation: 7
New Best Solution Fitness: 87593
New Best Solution Fitness: 87555
New Best Solution Fitness: 87545
Generation: 8
New Best Solution Fitness: 87538
Generation: 9
New Best Solution Fitness: 87491
New Best Solution Fitness: 87455
New Best Solution Fitness: 87453
Generation: 10
New Best Solution Fitness: 87380
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.48889 
Mean sub-tour choices: 2.25556 
Best Solution Fitness: 87380 
--------------------------------------------- 
