--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88435
New Best Solution Fitness: 88240
Generation: 3
New Best Solution Fitness: 87641
New Best Solution Fitness: 87617
Generation: 4
Generation: 5
New Best Solution Fitness: 87578
New Best Solution Fitness: 87562
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 87440
New Best Solution Fitness: 87424
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.46667 
Mean sub-tour choices: 2.22222 
Best Solution Fitness: 87424 
--------------------------------------------- 
