--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87595
New Best Solution Fitness: 87584
New Best Solution Fitness: 87576
New Best Solution Fitness: 87503
Generation: 3
New Best Solution Fitness: 87468
Generation: 4
New Best Solution Fitness: 87448
New Best Solution Fitness: 87389
New Best Solution Fitness: 87388
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 87384
New Best Solution Fitness: 87333
Generation: 8
Generation: 9
New Best Solution Fitness: 87329
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.9 
Mean sub-tour choices: 1.58889 
Best Solution Fitness: 87329 
--------------------------------------------- 
