--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88124
New Best Solution Fitness: 88026
New Best Solution Fitness: 88021
New Best Solution Fitness: 87916
New Best Solution Fitness: 87908
Generation: 3
New Best Solution Fitness: 87698
New Best Solution Fitness: 87663
Generation: 4
New Best Solution Fitness: 87567
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.911111 
Mean sub-tour choices: 1.41111 
Best Solution Fitness: 87567 
--------------------------------------------- 
