--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88320
New Best Solution Fitness: 88306
New Best Solution Fitness: 88247
Generation: 3
New Best Solution Fitness: 87790
New Best Solution Fitness: 87705
Generation: 4
New Best Solution Fitness: 87637
Generation: 5
Generation: 6
New Best Solution Fitness: 87590
Generation: 7
New Best Solution Fitness: 87555
Generation: 8
New Best Solution Fitness: 87398
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.6 
Mean sub-tour choices: 1.08889 
Best Solution Fitness: 87398 
--------------------------------------------- 
