--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87604
New Best Solution Fitness: 87314
Generation: 3
New Best Solution Fitness: 87097
Generation: 4
New Best Solution Fitness: 87085
Generation: 5
Generation: 6
New Best Solution Fitness: 87070
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.966667 
Mean sub-tour choices: 1.64444 
Best Solution Fitness: 87070 
--------------------------------------------- 
