--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 90129
New Best Solution Fitness: 89592
Generation: 3
New Best Solution Fitness: 88728
Generation: 4
New Best Solution Fitness: 88726
New Best Solution Fitness: 88694
New Best Solution Fitness: 88693
Generation: 5
New Best Solution Fitness: 88542
New Best Solution Fitness: 88541
Generation: 6
New Best Solution Fitness: 88404
New Best Solution Fitness: 88251
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 88150
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.911111 
Mean sub-tour choices: 1.6 
Best Solution Fitness: 88150 
--------------------------------------------- 
