--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88404
New Best Solution Fitness: 88303
New Best Solution Fitness: 88273
Generation: 3
New Best Solution Fitness: 88046
Generation: 4
New Best Solution Fitness: 88019
Generation: 5
Generation: 6
New Best Solution Fitness: 87895
New Best Solution Fitness: 87825
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 87820
New Best Solution Fitness: 87637
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.833333 
Mean sub-tour choices: 1.45556 
Best Solution Fitness: 87637 
--------------------------------------------- 
