--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88650
New Best Solution Fitness: 88610
New Best Solution Fitness: 88539
New Best Solution Fitness: 88516
Generation: 3
New Best Solution Fitness: 88486
New Best Solution Fitness: 88378
New Best Solution Fitness: 88356
Generation: 4
New Best Solution Fitness: 88050
Generation: 5
New Best Solution Fitness: 87769
Generation: 6
New Best Solution Fitness: 87754
Generation: 7
Generation: 8
New Best Solution Fitness: 87685
Generation: 9
New Best Solution Fitness: 87519
New Best Solution Fitness: 87458
Generation: 10
New Best Solution Fitness: 87419
New Best Solution Fitness: 87418
New Best Solution Fitness: 87033
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.688889 
Mean sub-tour choices: 1.32222 
Best Solution Fitness: 87033 
--------------------------------------------- 
