--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88985
New Best Solution Fitness: 88922
New Best Solution Fitness: 88821
Generation: 3
New Best Solution Fitness: 88663
New Best Solution Fitness: 88550
Generation: 4
New Best Solution Fitness: 88390
New Best Solution Fitness: 88375
Generation: 5
New Best Solution Fitness: 88341
New Best Solution Fitness: 88299
Generation: 6
Generation: 7
New Best Solution Fitness: 88222
Generation: 8
Generation: 9
New Best Solution Fitness: 88199
Generation: 10
New Best Solution Fitness: 87956
New Best Solution Fitness: 87955
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.01111 
Mean sub-tour choices: 1.6 
Best Solution Fitness: 87955 
--------------------------------------------- 
