--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87972
New Best Solution Fitness: 87901
New Best Solution Fitness: 87849
Generation: 3
New Best Solution Fitness: 87807
Generation: 4
New Best Solution Fitness: 87646
New Best Solution Fitness: 87639
Generation: 5
Generation: 6
New Best Solution Fitness: 87578
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 87553
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.566667 
Mean sub-tour choices: 0.911111 
Best Solution Fitness: 87553 
--------------------------------------------- 
