--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88939
New Best Solution Fitness: 88914
New Best Solution Fitness: 88908
Generation: 3
New Best Solution Fitness: 88791
New Best Solution Fitness: 88673
Generation: 4
New Best Solution Fitness: 88488
New Best Solution Fitness: 88457
Generation: 5
New Best Solution Fitness: 88301
Generation: 6
Generation: 7
New Best Solution Fitness: 88155
New Best Solution Fitness: 87938
Generation: 8
Generation: 9
New Best Solution Fitness: 87936
Generation: 10
New Best Solution Fitness: 87555
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.922222 
Mean sub-tour choices: 1.8 
Best Solution Fitness: 87555 
--------------------------------------------- 
