--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88507
New Best Solution Fitness: 88414
Generation: 3
New Best Solution Fitness: 88193
New Best Solution Fitness: 88074
New Best Solution Fitness: 88064
Generation: 4
New Best Solution Fitness: 87978
Generation: 5
New Best Solution Fitness: 87848
New Best Solution Fitness: 87797
New Best Solution Fitness: 87729
Generation: 6
New Best Solution Fitness: 87645
Generation: 7
New Best Solution Fitness: 87626
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.04444 
Mean sub-tour choices: 1.54444 
Best Solution Fitness: 87626 
--------------------------------------------- 
