--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88174
New Best Solution Fitness: 88153
New Best Solution Fitness: 88138
Generation: 3
Generation: 4
Generation: 5
New Best Solution Fitness: 87813
New Best Solution Fitness: 87704
Generation: 6
New Best Solution Fitness: 87698
New Best Solution Fitness: 87693
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 87688
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.655556 
Mean sub-tour choices: 1.14444 
Best Solution Fitness: 87688 
--------------------------------------------- 
