--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88218
New Best Solution Fitness: 88214
Generation: 3
New Best Solution Fitness: 87969
Generation: 4
New Best Solution Fitness: 87853
Generation: 5
Generation: 6
New Best Solution Fitness: 87849
New Best Solution Fitness: 87827
Generation: 7
New Best Solution Fitness: 87703
Generation: 8
New Best Solution Fitness: 87699
New Best Solution Fitness: 87561
Generation: 9
New Best Solution Fitness: 87481
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.622222 
Mean sub-tour choices: 0.955556 
Best Solution Fitness: 87481 
--------------------------------------------- 
