--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88484
New Best Solution Fitness: 88480
Generation: 3
New Best Solution Fitness: 88381
New Best Solution Fitness: 88367
New Best Solution Fitness: 88314
Generation: 4
New Best Solution Fitness: 88211
Generation: 5
New Best Solution Fitness: 87919
New Best Solution Fitness: 87883
Generation: 6
New Best Solution Fitness: 87748
Generation: 7
Generation: 8
New Best Solution Fitness: 87457
Generation: 9
New Best Solution Fitness: 87370
New Best Solution Fitness: 87321
Generation: 10
New Best Solution Fitness: 87294
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.511111 
Mean sub-tour choices: 0.888889 
Best Solution Fitness: 87294 
--------------------------------------------- 
