--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 89034
New Best Solution Fitness: 88997
New Best Solution Fitness: 88934
Generation: 3
New Best Solution Fitness: 88319
Generation: 4
New Best Solution Fitness: 88059
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.41111 
Mean sub-tour choices: 2.25556 
Best Solution Fitness: 88059 
--------------------------------------------- 
