--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88016
New Best Solution Fitness: 87968
Generation: 3
New Best Solution Fitness: 87964
Generation: 4
New Best Solution Fitness: 87957
New Best Solution Fitness: 87911
Generation: 5
New Best Solution Fitness: 87907
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 87851
Generation: 9
New Best Solution Fitness: 87676
New Best Solution Fitness: 87620
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.977778 
Mean sub-tour choices: 1.51111 
Best Solution Fitness: 87620 
--------------------------------------------- 
