--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 89236
Generation: 3
New Best Solution Fitness: 88710
New Best Solution Fitness: 88628
Generation: 4
Generation: 5
New Best Solution Fitness: 88585
New Best Solution Fitness: 88538
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 88227
Generation: 9
Generation: 10
New Best Solution Fitness: 88181
New Best Solution Fitness: 88063
New Best Solution Fitness: 87980
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.488889 
Mean sub-tour choices: 0.911111 
Best Solution Fitness: 87980 
--------------------------------------------- 
