--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88819
New Best Solution Fitness: 88515
New Best Solution Fitness: 88425
Generation: 3
New Best Solution Fitness: 88291
New Best Solution Fitness: 88273
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 88258
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.45556 
Mean sub-tour choices: 1.76667 
Best Solution Fitness: 88258 
--------------------------------------------- 
