--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88131
New Best Solution Fitness: 88042
New Best Solution Fitness: 87963
Generation: 3
New Best Solution Fitness: 87713
New Best Solution Fitness: 87681
New Best Solution Fitness: 87628
Generation: 4
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.522222 
Mean sub-tour choices: 0.911111 
Best Solution Fitness: 87628 
--------------------------------------------- 
