--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88496
New Best Solution Fitness: 88352
New Best Solution Fitness: 88291
Generation: 3
New Best Solution Fitness: 88151
Generation: 4
New Best Solution Fitness: 88092
Generation: 5
New Best Solution Fitness: 88058
Generation: 6
New Best Solution Fitness: 88009
New Best Solution Fitness: 87971
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 87845
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.788889 
Mean sub-tour choices: 1.26667 
Best Solution Fitness: 87845 
--------------------------------------------- 
