--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88651
New Best Solution Fitness: 88625
New Best Solution Fitness: 88513
New Best Solution Fitness: 88505
Generation: 3
New Best Solution Fitness: 88287
New Best Solution Fitness: 88226
Generation: 4
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 88098
New Best Solution Fitness: 88061
Generation: 9
New Best Solution Fitness: 87949
New Best Solution Fitness: 87938
Generation: 10
New Best Solution Fitness: 87677
New Best Solution Fitness: 87643
New Best Solution Fitness: 87632
New Best Solution Fitness: 87620
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.64444 
Mean sub-tour choices: 2.42222 
Best Solution Fitness: 87620 
--------------------------------------------- 
