--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 90081
New Best Solution Fitness: 90071
New Best Solution Fitness: 90003
New Best Solution Fitness: 89997
New Best Solution Fitness: 89939
Generation: 3
New Best Solution Fitness: 88218
New Best Solution Fitness: 88198
Generation: 4
New Best Solution Fitness: 88160
New Best Solution Fitness: 88139
New Best Solution Fitness: 88129
Generation: 5
Generation: 6
New Best Solution Fitness: 88092
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 87893
New Best Solution Fitness: 87813
New Best Solution Fitness: 87603
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.17778 
Mean sub-tour choices: 1.83333 
Best Solution Fitness: 87603 
--------------------------------------------- 
