--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87518
New Best Solution Fitness: 87513
New Best Solution Fitness: 87464
Generation: 3
New Best Solution Fitness: 87459
Generation: 4
New Best Solution Fitness: 87420
New Best Solution Fitness: 87395
Generation: 5
New Best Solution Fitness: 87270
New Best Solution Fitness: 87197
Generation: 6
New Best Solution Fitness: 87171
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 87170
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.933333 
Mean sub-tour choices: 1.51111 
Best Solution Fitness: 87170 
--------------------------------------------- 
