--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88539
New Best Solution Fitness: 88522
New Best Solution Fitness: 88458
Generation: 3
New Best Solution Fitness: 88383
New Best Solution Fitness: 88365
New Best Solution Fitness: 88324
Generation: 4
New Best Solution Fitness: 88001
New Best Solution Fitness: 87920
Generation: 5
New Best Solution Fitness: 87836
New Best Solution Fitness: 87818
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.18889 
Mean sub-tour choices: 1.85556 
Best Solution Fitness: 87818 
--------------------------------------------- 
