--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87898
New Best Solution Fitness: 87894
Generation: 3
New Best Solution Fitness: 87803
New Best Solution Fitness: 87798
Generation: 4
New Best Solution Fitness: 87599
New Best Solution Fitness: 87515
Generation: 5
New Best Solution Fitness: 87496
New Best Solution Fitness: 87422
New Best Solution Fitness: 87401
Generation: 6
New Best Solution Fitness: 87293
Generation: 7
New Best Solution Fitness: 87265
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 87210
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.677778 
Mean sub-tour choices: 1.35556 
Best Solution Fitness: 87210 
--------------------------------------------- 
