--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 89136
New Best Solution Fitness: 89132
Generation: 3
New Best Solution Fitness: 88840
New Best Solution Fitness: 88814
Generation: 4
New Best Solution Fitness: 88768
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 88696
New Best Solution Fitness: 88647
Generation: 8
Generation: 9
New Best Solution Fitness: 88572
New Best Solution Fitness: 88568
New Best Solution Fitness: 88519
Generation: 10
New Best Solution Fitness: 88327
New Best Solution Fitness: 88302
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.488889 
Mean sub-tour choices: 0.888889 
Best Solution Fitness: 88302 
--------------------------------------------- 
