--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88132
New Best Solution Fitness: 88050
New Best Solution Fitness: 88024
Generation: 3
New Best Solution Fitness: 87839
Generation: 4
Generation: 5
New Best Solution Fitness: 87830
New Best Solution Fitness: 87770
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 87769
New Best Solution Fitness: 87610
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.433333 
Mean sub-tour choices: 0.766667 
Best Solution Fitness: 87610 
--------------------------------------------- 
