--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 89002
New Best Solution Fitness: 88575
Generation: 3
New Best Solution Fitness: 87995
New Best Solution Fitness: 87843
Generation: 4
New Best Solution Fitness: 87320
Generation: 5
New Best Solution Fitness: 87241
New Best Solution Fitness: 87223
Generation: 6
New Best Solution Fitness: 87094
New Best Solution Fitness: 87089
Generation: 7
Generation: 8
New Best Solution Fitness: 87085
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.444444 
Mean sub-tour choices: 0.733333 
Best Solution Fitness: 87085 
--------------------------------------------- 
