--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87800
New Best Solution Fitness: 87756
Generation: 3
New Best Solution Fitness: 87647
Generation: 4
Generation: 5
New Best Solution Fitness: 87623
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 87594
Generation: 10
New Best Solution Fitness: 87568
New Best Solution Fitness: 87524
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.822222 
Mean sub-tour choices: 1.5 
Best Solution Fitness: 87524 
--------------------------------------------- 
