--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88695
New Best Solution Fitness: 88693
New Best Solution Fitness: 88570
Generation: 3
New Best Solution Fitness: 88507
Generation: 4
Generation: 5
New Best Solution Fitness: 88401
New Best Solution Fitness: 88011
Generation: 6
New Best Solution Fitness: 87609
New Best Solution Fitness: 87317
Generation: 7
New Best Solution Fitness: 87265
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.744444 
Mean sub-tour choices: 1.22222 
Best Solution Fitness: 87265 
--------------------------------------------- 
