--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 89234
New Best Solution Fitness: 89136
New Best Solution Fitness: 89082
Generation: 3
New Best Solution Fitness: 88821
New Best Solution Fitness: 88567
Generation: 4
New Best Solution Fitness: 88513
Generation: 5
New Best Solution Fitness: 88501
Generation: 6
Generation: 7
New Best Solution Fitness: 88493
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 88285
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.711111 
Mean sub-tour choices: 1.17778 
Best Solution Fitness: 88285 
--------------------------------------------- 
