--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88032
New Best Solution Fitness: 88015
Generation: 3
New Best Solution Fitness: 88005
New Best Solution Fitness: 88001
Generation: 4
New Best Solution Fitness: 87993
Generation: 5
Generation: 6
New Best Solution Fitness: 87786
New Best Solution Fitness: 87768
Generation: 7
New Best Solution Fitness: 87716
Generation: 8
New Best Solution Fitness: 87606
Generation: 9
New Best Solution Fitness: 87391
Generation: 10
New Best Solution Fitness: 87205
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.21111 
Mean sub-tour choices: 1.74444 
Best Solution Fitness: 87205 
--------------------------------------------- 
