--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88290
New Best Solution Fitness: 88112
New Best Solution Fitness: 88086
New Best Solution Fitness: 88043
New Best Solution Fitness: 88013
Generation: 3
New Best Solution Fitness: 87970
New Best Solution Fitness: 87943
New Best Solution Fitness: 87917
Generation: 4
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 87916
Generation: 9
New Best Solution Fitness: 87902
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.22222 
Mean sub-tour choices: 1.62222 
Best Solution Fitness: 87902 
--------------------------------------------- 
