--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88444
New Best Solution Fitness: 88330
New Best Solution Fitness: 88316
Generation: 3
New Best Solution Fitness: 88287
New Best Solution Fitness: 88222
New Best Solution Fitness: 88208
Generation: 4
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 88025
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.5 
Mean sub-tour choices: 2.04444 
Best Solution Fitness: 88025 
--------------------------------------------- 
