--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88258
New Best Solution Fitness: 88194
Generation: 3
New Best Solution Fitness: 87913
New Best Solution Fitness: 87847
Generation: 4
Generation: 5
New Best Solution Fitness: 87681
New Best Solution Fitness: 87504
New Best Solution Fitness: 87244
Generation: 6
New Best Solution Fitness: 87174
Generation: 7
Generation: 8
New Best Solution Fitness: 87132
New Best Solution Fitness: 87073
Generation: 9
New Best Solution Fitness: 87026
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.522222 
Mean sub-tour choices: 0.9 
Best Solution Fitness: 87026 
--------------------------------------------- 
