--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88084
New Best Solution Fitness: 88026
Generation: 3
New Best Solution Fitness: 87825
New Best Solution Fitness: 87791
Generation: 4
New Best Solution Fitness: 87790
Generation: 5
New Best Solution Fitness: 87785
New Best Solution Fitness: 87768
New Best Solution Fitness: 87717
Generation: 6
New Best Solution Fitness: 87658
Generation: 7
New Best Solution Fitness: 87647
New Best Solution Fitness: 87596
Generation: 8
New Best Solution Fitness: 87579
New Best Solution Fitness: 87519
Generation: 9
New Best Solution Fitness: 87502
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.26667 
Mean sub-tour choices: 1.8 
Best Solution Fitness: 87502 
--------------------------------------------- 
