--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88074
New Best Solution Fitness: 87996
New Best Solution Fitness: 87995
Generation: 3
New Best Solution Fitness: 87831
New Best Solution Fitness: 87811
New Best Solution Fitness: 87761
Generation: 4
New Best Solution Fitness: 87689
Generation: 5
New Best Solution Fitness: 87661
New Best Solution Fitness: 87550
New Best Solution Fitness: 87531
New Best Solution Fitness: 87530
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 87363
Generation: 10
New Best Solution Fitness: 87245
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.44444 
Mean sub-tour choices: 2.04444 
Best Solution Fitness: 87245 
--------------------------------------------- 
