--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88365
New Best Solution Fitness: 88262
Generation: 3
New Best Solution Fitness: 88059
Generation: 4
New Best Solution Fitness: 87977
New Best Solution Fitness: 87958
New Best Solution Fitness: 87830
Generation: 5
New Best Solution Fitness: 87827
Generation: 6
New Best Solution Fitness: 87751
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.07778 
Mean sub-tour choices: 1.75556 
Best Solution Fitness: 87751 
--------------------------------------------- 
