--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88782
New Best Solution Fitness: 88742
Generation: 3
New Best Solution Fitness: 88688
Generation: 4
New Best Solution Fitness: 88670
Generation: 5
Generation: 6
New Best Solution Fitness: 88655
New Best Solution Fitness: 88141
Generation: 7
New Best Solution Fitness: 88058
New Best Solution Fitness: 87939
Generation: 8
New Best Solution Fitness: 87899
Generation: 9
Generation: 10
New Best Solution Fitness: 87756
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.711111 
Mean sub-tour choices: 1.22222 
Best Solution Fitness: 87756 
--------------------------------------------- 
