--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88476
New Best Solution Fitness: 88475
Generation: 3
New Best Solution Fitness: 88336
Generation: 4
New Best Solution Fitness: 88204
New Best Solution Fitness: 88124
Generation: 5
New Best Solution Fitness: 87830
Generation: 6
Generation: 7
New Best Solution Fitness: 87520
New Best Solution Fitness: 87517
Generation: 8
New Best Solution Fitness: 87468
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.5 
Mean sub-tour choices: 0.833333 
Best Solution Fitness: 87468 
--------------------------------------------- 
