--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88258
New Best Solution Fitness: 88253
New Best Solution Fitness: 88071
New Best Solution Fitness: 87979
Generation: 3
New Best Solution Fitness: 87617
Generation: 4
New Best Solution Fitness: 87552
New Best Solution Fitness: 87518
New Best Solution Fitness: 87481
New Best Solution Fitness: 87477
Generation: 5
New Best Solution Fitness: 87455
New Best Solution Fitness: 87433
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 87417
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.611111 
Mean sub-tour choices: 1.1 
Best Solution Fitness: 87417 
--------------------------------------------- 
