--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88041
New Best Solution Fitness: 87986
New Best Solution Fitness: 87964
Generation: 3
New Best Solution Fitness: 87932
Generation: 4
New Best Solution Fitness: 87452
New Best Solution Fitness: 87347
Generation: 5
Generation: 6
New Best Solution Fitness: 87340
New Best Solution Fitness: 87306
Generation: 7
New Best Solution Fitness: 87284
New Best Solution Fitness: 87269
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.544444 
Mean sub-tour choices: 1.04444 
Best Solution Fitness: 87269 
--------------------------------------------- 
