--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 89434
New Best Solution Fitness: 89107
New Best Solution Fitness: 89100
Generation: 3
New Best Solution Fitness: 88581
Generation: 4
Generation: 5
New Best Solution Fitness: 88410
Generation: 6
New Best Solution Fitness: 88305
New Best Solution Fitness: 88275
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.688889 
Mean sub-tour choices: 1.13333 
Best Solution Fitness: 88275 
--------------------------------------------- 
