--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87867
New Best Solution Fitness: 87708
Generation: 3
New Best Solution Fitness: 87522
New Best Solution Fitness: 87512
Generation: 4
New Best Solution Fitness: 87511
New Best Solution Fitness: 87497
Generation: 5
Generation: 6
New Best Solution Fitness: 87494
New Best Solution Fitness: 87451
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 87369
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.988889 
Mean sub-tour choices: 1.7 
Best Solution Fitness: 87369 
--------------------------------------------- 
