--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87879
New Best Solution Fitness: 87820
New Best Solution Fitness: 87803
New Best Solution Fitness: 87622
Generation: 3
New Best Solution Fitness: 87561
New Best Solution Fitness: 87544
Generation: 4
New Best Solution Fitness: 87533
New Best Solution Fitness: 87516
New Best Solution Fitness: 87491
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 87483
Generation: 8
New Best Solution Fitness: 87479
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.22222 
Mean sub-tour choices: 1.72222 
Best Solution Fitness: 87479 
--------------------------------------------- 
