--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87993
New Best Solution Fitness: 87968
Generation: 3
New Best Solution Fitness: 87953
Generation: 4
New Best Solution Fitness: 87872
Generation: 5
New Best Solution Fitness: 87615
Generation: 6
New Best Solution Fitness: 87395
New Best Solution Fitness: 87208
Generation: 7
New Best Solution Fitness: 87147
Generation: 8
New Best Solution Fitness: 87059
Generation: 9
New Best Solution Fitness: 87012
New Best Solution Fitness: 86924
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.444444 
Mean sub-tour choices: 0.8 
Best Solution Fitness: 86924 
--------------------------------------------- 
