--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87846
Generation: 3
New Best Solution Fitness: 87600
New Best Solution Fitness: 87579
Generation: 4
Generation: 5
New Best Solution Fitness: 87443
Generation: 6
Generation: 7
New Best Solution Fitness: 87391
Generation: 8
New Best Solution Fitness: 87355
New Best Solution Fitness: 87295
Generation: 9
New Best Solution Fitness: 87274
New Best Solution Fitness: 87222
Generation: 10
New Best Solution Fitness: 87172
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.488889 
Mean sub-tour choices: 0.766667 
Best Solution Fitness: 87172 
--------------------------------------------- 
