--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88664
New Best Solution Fitness: 88637
Generation: 3
New Best Solution Fitness: 88209
New Best Solution Fitness: 88184
Generation: 4
New Best Solution Fitness: 88174
New Best Solution Fitness: 88149
Generation: 5
New Best Solution Fitness: 87940
New Best Solution Fitness: 87870
New Best Solution Fitness: 87810
Generation: 6
New Best Solution Fitness: 87590
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.11111 
Mean sub-tour choices: 1.67778 
Best Solution Fitness: 87590 
--------------------------------------------- 
