--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88189
New Best Solution Fitness: 88120
New Best Solution Fitness: 88010
New Best Solution Fitness: 88002
Generation: 3
New Best Solution Fitness: 87606
New Best Solution Fitness: 87598
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 87542
Generation: 7
New Best Solution Fitness: 87532
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.844444 
Mean sub-tour choices: 1.51111 
Best Solution Fitness: 87532 
--------------------------------------------- 
