--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88097
Generation: 3
New Best Solution Fitness: 87941
New Best Solution Fitness: 87931
Generation: 4
New Best Solution Fitness: 87802
New Best Solution Fitness: 87754
Generation: 5
New Best Solution Fitness: 87736
New Best Solution Fitness: 87705
Generation: 6
New Best Solution Fitness: 87515
New Best Solution Fitness: 87496
Generation: 7
New Best Solution Fitness: 87484
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.4 
Mean sub-tour choices: 0.866667 
Best Solution Fitness: 87484 
--------------------------------------------- 
