--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88519
New Best Solution Fitness: 88487
Generation: 3
New Best Solution Fitness: 88366
New Best Solution Fitness: 88360
New Best Solution Fitness: 88355
Generation: 4
New Best Solution Fitness: 88210
New Best Solution Fitness: 88167
Generation: 5
New Best Solution Fitness: 87872
New Best Solution Fitness: 87866
Generation: 6
New Best Solution Fitness: 87743
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.955556 
Mean sub-tour choices: 1.56667 
Best Solution Fitness: 87743 
--------------------------------------------- 
