--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87863
New Best Solution Fitness: 87852
New Best Solution Fitness: 87846
New Best Solution Fitness: 87775
New Best Solution Fitness: 87764
Generation: 3
New Best Solution Fitness: 87743
New Best Solution Fitness: 87697
Generation: 4
Generation: 5
New Best Solution Fitness: 87644
New Best Solution Fitness: 87444
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 87443
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.25556 
Mean sub-tour choices: 2.27778 
Best Solution Fitness: 87443 
--------------------------------------------- 
