--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88283
New Best Solution Fitness: 87995
Generation: 3
New Best Solution Fitness: 87768
Generation: 4
New Best Solution Fitness: 87596
New Best Solution Fitness: 87455
New Best Solution Fitness: 87217
New Best Solution Fitness: 87196
Generation: 5
New Best Solution Fitness: 87184
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.733333 
Mean sub-tour choices: 1.22222 
Best Solution Fitness: 87184 
--------------------------------------------- 
