--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88059
New Best Solution Fitness: 88055
New Best Solution Fitness: 88030
New Best Solution Fitness: 87961
Generation: 3
New Best Solution Fitness: 87906
New Best Solution Fitness: 87877
New Best Solution Fitness: 87824
Generation: 4
New Best Solution Fitness: 87795
Generation: 5
New Best Solution Fitness: 87780
Generation: 6
New Best Solution Fitness: 87745
Generation: 7
New Best Solution Fitness: 87734
New Best Solution Fitness: 87725
New Best Solution Fitness: 87672
Generation: 8
Generation: 9
New Best Solution Fitness: 87580
New Best Solution Fitness: 87513
Generation: 10
New Best Solution Fitness: 87413
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.2 
Mean sub-tour choices: 1.83333 
Best Solution Fitness: 87413 
--------------------------------------------- 
