--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88483
New Best Solution Fitness: 88462
New Best Solution Fitness: 88427
Generation: 3
New Best Solution Fitness: 88406
New Best Solution Fitness: 88402
Generation: 4
New Best Solution Fitness: 88064
New Best Solution Fitness: 88054
Generation: 5
New Best Solution Fitness: 87705
New Best Solution Fitness: 87563
Generation: 6
New Best Solution Fitness: 87538
New Best Solution Fitness: 87396
Generation: 7
Generation: 8
New Best Solution Fitness: 87354
New Best Solution Fitness: 87303
Generation: 9
New Best Solution Fitness: 87302
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.655556 
Mean sub-tour choices: 1.12222 
Best Solution Fitness: 87302 
--------------------------------------------- 
