--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88710
New Best Solution Fitness: 88592
New Best Solution Fitness: 88539
Generation: 3
New Best Solution Fitness: 87996
New Best Solution Fitness: 87986
New Best Solution Fitness: 87891
New Best Solution Fitness: 87812
Generation: 4
New Best Solution Fitness: 87775
Generation: 5
New Best Solution Fitness: 87640
New Best Solution Fitness: 87590
Generation: 6
New Best Solution Fitness: 87589
Generation: 7
Generation: 8
New Best Solution Fitness: 87077
Generation: 9
Generation: 10
New Best Solution Fitness: 87066
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.655556 
Mean sub-tour choices: 1.06667 
Best Solution Fitness: 87066 
--------------------------------------------- 
