--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88567
New Best Solution Fitness: 88422
Generation: 3
New Best Solution Fitness: 88284
Generation: 4
Generation: 5
New Best Solution Fitness: 87921
New Best Solution Fitness: 87885
New Best Solution Fitness: 87844
Generation: 6
New Best Solution Fitness: 87834
New Best Solution Fitness: 87829
Generation: 7
Generation: 8
New Best Solution Fitness: 87812
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.711111 
Mean sub-tour choices: 1.2 
Best Solution Fitness: 87812 
--------------------------------------------- 
