--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88387
New Best Solution Fitness: 88301
Generation: 3
New Best Solution Fitness: 88224
New Best Solution Fitness: 88147
Generation: 4
New Best Solution Fitness: 87853
New Best Solution Fitness: 87538
Generation: 5
New Best Solution Fitness: 87506
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 87392
Generation: 9
Generation: 10
New Best Solution Fitness: 87358
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.733333 
Mean sub-tour choices: 1.33333 
Best Solution Fitness: 87358 
--------------------------------------------- 
