--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88632
New Best Solution Fitness: 88464
New Best Solution Fitness: 88404
Generation: 3
New Best Solution Fitness: 88271
New Best Solution Fitness: 88265
Generation: 4
New Best Solution Fitness: 88102
New Best Solution Fitness: 88096
Generation: 5
New Best Solution Fitness: 88083
Generation: 6
New Best Solution Fitness: 88021
Generation: 7
New Best Solution Fitness: 88020
Generation: 8
New Best Solution Fitness: 87766
New Best Solution Fitness: 87714
Generation: 9
New Best Solution Fitness: 87702
Generation: 10
New Best Solution Fitness: 87682
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.03333 
Mean sub-tour choices: 2.9 
Best Solution Fitness: 87682 
--------------------------------------------- 
