--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87706
New Best Solution Fitness: 87642
Generation: 3
New Best Solution Fitness: 87577
Generation: 4
New Best Solution Fitness: 87345
New Best Solution Fitness: 87281
Generation: 5
New Best Solution Fitness: 87240
Generation: 6
New Best Solution Fitness: 87235
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 87162
New Best Solution Fitness: 87105
New Best Solution Fitness: 87038
Generation: 10
New Best Solution Fitness: 87020
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.788889 
Mean sub-tour choices: 1.23333 
Best Solution Fitness: 87020 
--------------------------------------------- 
