--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88607
Generation: 3
New Best Solution Fitness: 88148
Generation: 4
New Best Solution Fitness: 88096
New Best Solution Fitness: 88088
Generation: 5
New Best Solution Fitness: 88083
Generation: 6
New Best Solution Fitness: 87736
New Best Solution Fitness: 87675
New Best Solution Fitness: 87670
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.488889 
Mean sub-tour choices: 0.966667 
Best Solution Fitness: 87670 
--------------------------------------------- 
