--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88288
New Best Solution Fitness: 88180
Generation: 3
New Best Solution Fitness: 87777
New Best Solution Fitness: 87724
Generation: 4
Generation: 5
New Best Solution Fitness: 87507
Generation: 6
Generation: 7
New Best Solution Fitness: 87490
New Best Solution Fitness: 87479
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 87468
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.722222 
Mean sub-tour choices: 1.37778 
Best Solution Fitness: 87468 
--------------------------------------------- 
