--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87971
New Best Solution Fitness: 87885
Generation: 3
New Best Solution Fitness: 87600
Generation: 4
New Best Solution Fitness: 87576
Generation: 5
New Best Solution Fitness: 87540
Generation: 6
New Best Solution Fitness: 87418
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.644444 
Mean sub-tour choices: 1.07778 
Best Solution Fitness: 87418 
--------------------------------------------- 
