--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87778
New Best Solution Fitness: 87610
Generation: 3
New Best Solution Fitness: 87479
New Best Solution Fitness: 87457
Generation: 4
Generation: 5
New Best Solution Fitness: 87393
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 87392
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.666667 
Mean sub-tour choices: 1.5 
Best Solution Fitness: 87392 
--------------------------------------------- 
