--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87919
New Best Solution Fitness: 87888
New Best Solution Fitness: 87871
New Best Solution Fitness: 87839
Generation: 3
New Best Solution Fitness: 87582
New Best Solution Fitness: 87497
New Best Solution Fitness: 87409
Generation: 4
New Best Solution Fitness: 87392
Generation: 5
Generation: 6
New Best Solution Fitness: 87352
Generation: 7
Generation: 8
New Best Solution Fitness: 87205
New Best Solution Fitness: 87196
Generation: 9
Generation: 10
New Best Solution Fitness: 87092
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.711111 
Mean sub-tour choices: 1.1 
Best Solution Fitness: 87092 
--------------------------------------------- 
