--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88818
New Best Solution Fitness: 88469
Generation: 3
New Best Solution Fitness: 88250
New Best Solution Fitness: 88231
Generation: 4
New Best Solution Fitness: 88211
New Best Solution Fitness: 88209
New Best Solution Fitness: 88147
Generation: 5
New Best Solution Fitness: 88103
New Best Solution Fitness: 88092
Generation: 6
New Best Solution Fitness: 87684
New Best Solution Fitness: 87676
New Best Solution Fitness: 87673
Generation: 7
New Best Solution Fitness: 87630
New Best Solution Fitness: 87622
Generation: 8
Generation: 9
New Best Solution Fitness: 87571
Generation: 10
New Best Solution Fitness: 87352
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.633333 
Mean sub-tour choices: 1.13333 
Best Solution Fitness: 87352 
--------------------------------------------- 
