--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88013
New Best Solution Fitness: 87928
Generation: 3
New Best Solution Fitness: 87717
New Best Solution Fitness: 87687
New Best Solution Fitness: 87631
Generation: 4
New Best Solution Fitness: 87608
New Best Solution Fitness: 87522
Generation: 5
New Best Solution Fitness: 87518
Generation: 6
New Best Solution Fitness: 87501
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.41111 
Mean sub-tour choices: 2.03333 
Best Solution Fitness: 87501 
--------------------------------------------- 
