--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87688
New Best Solution Fitness: 87599
New Best Solution Fitness: 87589
Generation: 3
New Best Solution Fitness: 87469
New Best Solution Fitness: 87459
Generation: 4
New Best Solution Fitness: 87449
Generation: 5
New Best Solution Fitness: 87444
Generation: 6
New Best Solution Fitness: 87422
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.34444 
Mean sub-tour choices: 2.78889 
Best Solution Fitness: 87422 
--------------------------------------------- 
