--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87881
New Best Solution Fitness: 87860
New Best Solution Fitness: 87779
Generation: 3
New Best Solution Fitness: 87698
New Best Solution Fitness: 87593
Generation: 4
New Best Solution Fitness: 87432
Generation: 5
New Best Solution Fitness: 87390
Generation: 6
New Best Solution Fitness: 87306
Generation: 7
Generation: 8
New Best Solution Fitness: 87285
Generation: 9
New Best Solution Fitness: 87276
New Best Solution Fitness: 87258
New Best Solution Fitness: 87255
Generation: 10
New Best Solution Fitness: 87237
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.46667 
Mean sub-tour choices: 2.05556 
Best Solution Fitness: 87237 
--------------------------------------------- 
