--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88550
New Best Solution Fitness: 88475
Generation: 3
New Best Solution Fitness: 88095
Generation: 4
Generation: 5
New Best Solution Fitness: 88080
Generation: 6
New Best Solution Fitness: 87912
Generation: 7
Generation: 8
New Best Solution Fitness: 87894
Generation: 9
Generation: 10
New Best Solution Fitness: 87890
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.366667 
Mean sub-tour choices: 0.644444 
Best Solution Fitness: 87890 
--------------------------------------------- 
