--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87822
New Best Solution Fitness: 87770
Generation: 3
Generation: 4
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 87653
Generation: 8
New Best Solution Fitness: 87646
Generation: 9
New Best Solution Fitness: 87589
Generation: 10
New Best Solution Fitness: 87583
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.755556 
Mean sub-tour choices: 1.34444 
Best Solution Fitness: 87583 
--------------------------------------------- 
