--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88576
New Best Solution Fitness: 88364
New Best Solution Fitness: 88349
Generation: 3
New Best Solution Fitness: 87768
Generation: 4
New Best Solution Fitness: 87763
Generation: 5
New Best Solution Fitness: 87736
New Best Solution Fitness: 87658
New Best Solution Fitness: 87641
Generation: 6
New Best Solution Fitness: 87637
Generation: 7
New Best Solution Fitness: 87628
New Best Solution Fitness: 87624
Generation: 8
New Best Solution Fitness: 87534
New Best Solution Fitness: 87523
New Best Solution Fitness: 87517
Generation: 9
New Best Solution Fitness: 87506
New Best Solution Fitness: 87485
Generation: 10
New Best Solution Fitness: 87392
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.25556 
Mean sub-tour choices: 1.9 
Best Solution Fitness: 87392 
--------------------------------------------- 
