--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87978
New Best Solution Fitness: 87963
New Best Solution Fitness: 87959
New Best Solution Fitness: 87954
New Best Solution Fitness: 87952
Generation: 3
New Best Solution Fitness: 87563
New Best Solution Fitness: 87559
Generation: 4
New Best Solution Fitness: 87476
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 87441
Generation: 8
Generation: 9
New Best Solution Fitness: 87421
Generation: 10
New Best Solution Fitness: 87380
New Best Solution Fitness: 87296
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.811111 
Mean sub-tour choices: 1.2 
Best Solution Fitness: 87296 
--------------------------------------------- 
