--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88683
New Best Solution Fitness: 88564
New Best Solution Fitness: 88449
Generation: 3
New Best Solution Fitness: 88330
New Best Solution Fitness: 88222
Generation: 4
New Best Solution Fitness: 88197
New Best Solution Fitness: 88180
Generation: 5
New Best Solution Fitness: 88110
Generation: 6
New Best Solution Fitness: 88022
Generation: 7
Generation: 8
New Best Solution Fitness: 88016
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.28889 
Mean sub-tour choices: 2.1 
Best Solution Fitness: 88016 
--------------------------------------------- 
