--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87903
New Best Solution Fitness: 87860
Generation: 3
New Best Solution Fitness: 87758
New Best Solution Fitness: 87752
Generation: 4
New Best Solution Fitness: 87718
New Best Solution Fitness: 87692
New Best Solution Fitness: 87686
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.03333 
Mean sub-tour choices: 1.7 
Best Solution Fitness: 87686 
--------------------------------------------- 
