--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88075
New Best Solution Fitness: 88072
New Best Solution Fitness: 88069
New Best Solution Fitness: 88000
New Best Solution Fitness: 87967
Generation: 3
New Best Solution Fitness: 87850
New Best Solution Fitness: 87600
Generation: 4
New Best Solution Fitness: 87549
Generation: 5
New Best Solution Fitness: 87548
New Best Solution Fitness: 87542
New Best Solution Fitness: 87531
Generation: 6
New Best Solution Fitness: 87511
New Best Solution Fitness: 87480
Generation: 7
New Best Solution Fitness: 87474
Generation: 8
New Best Solution Fitness: 87472
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.811111 
Mean sub-tour choices: 1.41111 
Best Solution Fitness: 87472 
--------------------------------------------- 
