--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88918
New Best Solution Fitness: 88748
New Best Solution Fitness: 88725
Generation: 3
New Best Solution Fitness: 88702
Generation: 4
New Best Solution Fitness: 87923
New Best Solution Fitness: 87681
New Best Solution Fitness: 87680
Generation: 5
New Best Solution Fitness: 87669
Generation: 6
Generation: 7
New Best Solution Fitness: 87482
Generation: 8
New Best Solution Fitness: 87451
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.455556 
Mean sub-tour choices: 0.722222 
Best Solution Fitness: 87451 
--------------------------------------------- 
