--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88242
New Best Solution Fitness: 88241
New Best Solution Fitness: 88227
New Best Solution Fitness: 88215
Generation: 3
New Best Solution Fitness: 88209
New Best Solution Fitness: 88200
Generation: 4
Generation: 5
New Best Solution Fitness: 88076
New Best Solution Fitness: 88034
New Best Solution Fitness: 87819
Generation: 6
New Best Solution Fitness: 87616
Generation: 7
Generation: 8
New Best Solution Fitness: 87607
Generation: 9
New Best Solution Fitness: 87576
New Best Solution Fitness: 87558
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.2 
Mean sub-tour choices: 1.75556 
Best Solution Fitness: 87558 
--------------------------------------------- 
