--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87828
New Best Solution Fitness: 87792
New Best Solution Fitness: 87752
Generation: 3
New Best Solution Fitness: 87634
New Best Solution Fitness: 87529
Generation: 4
New Best Solution Fitness: 87501
New Best Solution Fitness: 87401
Generation: 5
New Best Solution Fitness: 87254
New Best Solution Fitness: 87253
Generation: 6
New Best Solution Fitness: 87225
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.11111 
Mean sub-tour choices: 1.82222 
Best Solution Fitness: 87225 
--------------------------------------------- 
