--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88249
New Best Solution Fitness: 88147
Generation: 3
New Best Solution Fitness: 87949
Generation: 4
New Best Solution Fitness: 87755
Generation: 5
New Best Solution Fitness: 87702
Generation: 6
New Best Solution Fitness: 87444
New Best Solution Fitness: 87443
New Best Solution Fitness: 87427
Generation: 7
Generation: 8
New Best Solution Fitness: 87312
Generation: 9
New Best Solution Fitness: 87293
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.277778 
Mean sub-tour choices: 0.555556 
Best Solution Fitness: 87293 
--------------------------------------------- 
