--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88514
New Best Solution Fitness: 88448
Generation: 3
New Best Solution Fitness: 88399
Generation: 4
New Best Solution Fitness: 88335
New Best Solution Fitness: 88289
Generation: 5
Generation: 6
New Best Solution Fitness: 87663
New Best Solution Fitness: 87628
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 87465
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.655556 
Mean sub-tour choices: 1.04444 
Best Solution Fitness: 87465 
--------------------------------------------- 
