--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88375
New Best Solution Fitness: 88278
Generation: 3
New Best Solution Fitness: 88267
New Best Solution Fitness: 88225
Generation: 4
New Best Solution Fitness: 88156
New Best Solution Fitness: 88064
Generation: 5
New Best Solution Fitness: 88044
New Best Solution Fitness: 88002
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 87866
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.7 
Mean sub-tour choices: 1.14444 
Best Solution Fitness: 87866 
--------------------------------------------- 
