--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88882
New Best Solution Fitness: 88835
New Best Solution Fitness: 88643
Generation: 3
Generation: 4
New Best Solution Fitness: 88511
Generation: 5
New Best Solution Fitness: 88080
New Best Solution Fitness: 88045
Generation: 6
New Best Solution Fitness: 87946
New Best Solution Fitness: 87911
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 87855
New Best Solution Fitness: 87833
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.722222 
Mean sub-tour choices: 1 
Best Solution Fitness: 87833 
--------------------------------------------- 
