--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 89117
New Best Solution Fitness: 89115
New Best Solution Fitness: 88450
Generation: 3
New Best Solution Fitness: 88300
New Best Solution Fitness: 88248
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 87811
New Best Solution Fitness: 87756
Generation: 7
Generation: 8
New Best Solution Fitness: 87720
New Best Solution Fitness: 87665
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.577778 
Mean sub-tour choices: 1.15556 
Best Solution Fitness: 87665 
--------------------------------------------- 
