--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 89314
New Best Solution Fitness: 89265
Generation: 3
New Best Solution Fitness: 88653
New Best Solution Fitness: 88604
New Best Solution Fitness: 88550
Generation: 4
Generation: 5
New Best Solution Fitness: 88448
New Best Solution Fitness: 88417
New Best Solution Fitness: 88254
Generation: 6
New Best Solution Fitness: 87870
Generation: 7
New Best Solution Fitness: 87443
New Best Solution Fitness: 87412
Generation: 8
New Best Solution Fitness: 87408
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.822222 
Mean sub-tour choices: 1.28889 
Best Solution Fitness: 87408 
--------------------------------------------- 
