--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88187
New Best Solution Fitness: 88168
New Best Solution Fitness: 88166
New Best Solution Fitness: 88162
New Best Solution Fitness: 88151
New Best Solution Fitness: 88149
Generation: 3
New Best Solution Fitness: 88130
New Best Solution Fitness: 88123
Generation: 4
New Best Solution Fitness: 88100
New Best Solution Fitness: 88023
Generation: 5
New Best Solution Fitness: 88012
Generation: 6
New Best Solution Fitness: 87950
New Best Solution Fitness: 87939
Generation: 7
New Best Solution Fitness: 87887
Generation: 8
New Best Solution Fitness: 87837
Generation: 9
New Best Solution Fitness: 87814
Generation: 10
New Best Solution Fitness: 87792
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.16667 
Mean sub-tour choices: 1.85556 
Best Solution Fitness: 87792 
--------------------------------------------- 
