--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 89863
New Best Solution Fitness: 89854
New Best Solution Fitness: 89537
Generation: 3
New Best Solution Fitness: 88548
Generation: 4
New Best Solution Fitness: 88530
Generation: 5
New Best Solution Fitness: 88420
New Best Solution Fitness: 88153
Generation: 6
New Best Solution Fitness: 87811
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 87790
New Best Solution Fitness: 87762
Generation: 10
New Best Solution Fitness: 87492
New Best Solution Fitness: 87466
New Best Solution Fitness: 87437
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.711111 
Mean sub-tour choices: 1.17778 
Best Solution Fitness: 87437 
--------------------------------------------- 
