--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88648
New Best Solution Fitness: 88641
New Best Solution Fitness: 88460
Generation: 3
New Best Solution Fitness: 88445
New Best Solution Fitness: 88423
Generation: 4
New Best Solution Fitness: 88380
New Best Solution Fitness: 88347
Generation: 5
New Best Solution Fitness: 88336
New Best Solution Fitness: 88325
Generation: 6
New Best Solution Fitness: 88234
Generation: 7
New Best Solution Fitness: 88230
Generation: 8
New Best Solution Fitness: 88197
Generation: 9
Generation: 10
New Best Solution Fitness: 87921
New Best Solution Fitness: 87523
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1 
Mean sub-tour choices: 1.61111 
Best Solution Fitness: 87523 
--------------------------------------------- 
