--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88629
New Best Solution Fitness: 88464
Generation: 3
New Best Solution Fitness: 87798
Generation: 4
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 87653
Generation: 8
Generation: 9
New Best Solution Fitness: 87644
New Best Solution Fitness: 87624
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.855556 
Mean sub-tour choices: 1.51111 
Best Solution Fitness: 87624 
--------------------------------------------- 
