--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87822
New Best Solution Fitness: 87547
Generation: 3
New Best Solution Fitness: 87444
New Best Solution Fitness: 87426
Generation: 4
New Best Solution Fitness: 87073
Generation: 5
New Best Solution Fitness: 87056
Generation: 6
New Best Solution Fitness: 86994
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.477778 
Mean sub-tour choices: 0.922222 
Best Solution Fitness: 86994 
--------------------------------------------- 
