--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88657
New Best Solution Fitness: 88641
Generation: 3
Generation: 4
New Best Solution Fitness: 88636
New Best Solution Fitness: 88615
Generation: 5
New Best Solution Fitness: 88483
New Best Solution Fitness: 88478
New Best Solution Fitness: 88211
Generation: 6
New Best Solution Fitness: 88091
Generation: 7
New Best Solution Fitness: 87778
New Best Solution Fitness: 87773
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.23333 
Mean sub-tour choices: 1.62222 
Best Solution Fitness: 87773 
--------------------------------------------- 
