--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88759
New Best Solution Fitness: 88758
New Best Solution Fitness: 88733
Generation: 3
New Best Solution Fitness: 88725
New Best Solution Fitness: 88678
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 88656
Generation: 7
New Best Solution Fitness: 88518
Generation: 8
New Best Solution Fitness: 88412
New Best Solution Fitness: 87994
Generation: 9
Generation: 10
New Best Solution Fitness: 87993
New Best Solution Fitness: 87917
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.911111 
Mean sub-tour choices: 1.5 
Best Solution Fitness: 87917 
--------------------------------------------- 
