--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87851
New Best Solution Fitness: 87780
Generation: 3
New Best Solution Fitness: 87776
Generation: 4
New Best Solution Fitness: 87748
Generation: 5
New Best Solution Fitness: 87743
Generation: 6
New Best Solution Fitness: 87665
New Best Solution Fitness: 87660
Generation: 7
Generation: 8
New Best Solution Fitness: 87634
Generation: 9
New Best Solution Fitness: 87572
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.966667 
Mean sub-tour choices: 1.51111 
Best Solution Fitness: 87572 
--------------------------------------------- 
