--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Black Box Steady State 
Population: 10
Mutation probability: 1
Crossover probability: 0.00152207
--------------------------
Job Complete 
Best Solution Fitness: 53688
Iterations: 4316490
--------------------------------------------- 
