--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\usa13509.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 20942592
New Best Solution Fitness: 20940887
Generation: 3
New Best Solution Fitness: 20714163
New Best Solution Fitness: 20708474
Generation: 4
New Best Solution Fitness: 20511150
New Best Solution Fitness: 20511027
New Best Solution Fitness: 20509519
Generation: 5
New Best Solution Fitness: 20499010
New Best Solution Fitness: 20498887
New Best Solution Fitness: 20496996
Generation: 6
New Best Solution Fitness: 20492983
New Best Solution Fitness: 20492860
Generation: 7
New Best Solution Fitness: 20492757
Generation: 8
New Best Solution Fitness: 20492067
Generation: 9
New Best Solution Fitness: 20491730
Generation: 10
New Best Solution Fitness: 20486995
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 7.53333 
Mean sub-tour choices: 1.92222 
Best Solution Fitness: 20486995 
--------------------------------------------- 
