--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\usa13509.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 20559430
New Best Solution Fitness: 20559291
New Best Solution Fitness: 20553585
New Best Solution Fitness: 20551396
New Best Solution Fitness: 20550279
Generation: 3
New Best Solution Fitness: 20490014
New Best Solution Fitness: 20489252
New Best Solution Fitness: 20485121
Generation: 4
New Best Solution Fitness: 20467161
New Best Solution Fitness: 20465649
New Best Solution Fitness: 20465010
Generation: 5
New Best Solution Fitness: 20463498
Generation: 6
New Best Solution Fitness: 20462744
New Best Solution Fitness: 20460218
Generation: 7
New Best Solution Fitness: 20459323
Generation: 8
New Best Solution Fitness: 20459208
Generation: 9
New Best Solution Fitness: 20414141
New Best Solution Fitness: 20414035
Generation: 10
New Best Solution Fitness: 20411654
New Best Solution Fitness: 20411598
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 10.0556 
Mean sub-tour choices: 2.32222 
Best Solution Fitness: 20411598 
--------------------------------------------- 
