--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\usa13509.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 20686680
New Best Solution Fitness: 20671040
New Best Solution Fitness: 20629464
Generation: 3
New Best Solution Fitness: 20493142
New Best Solution Fitness: 20492681
Generation: 4
New Best Solution Fitness: 20458918
New Best Solution Fitness: 20458812
New Best Solution Fitness: 20453893
Generation: 5
New Best Solution Fitness: 20437193
New Best Solution Fitness: 20437087
Generation: 6
New Best Solution Fitness: 20436756
Generation: 7
Generation: 8
New Best Solution Fitness: 20436712
Generation: 9
New Best Solution Fitness: 20435907
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 11.5 
Mean sub-tour choices: 3.46667 
Best Solution Fitness: 20435907 
--------------------------------------------- 
