--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\usa13509.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 20610641
New Best Solution Fitness: 20609748
New Best Solution Fitness: 20606528
New Best Solution Fitness: 20594115
New Best Solution Fitness: 20592844
Generation: 3
New Best Solution Fitness: 20535661
New Best Solution Fitness: 20535323
New Best Solution Fitness: 20534871
New Best Solution Fitness: 20530741
Generation: 4
New Best Solution Fitness: 20522444
New Best Solution Fitness: 20519903
Generation: 5
New Best Solution Fitness: 20513012
New Best Solution Fitness: 20512496
New Best Solution Fitness: 20510848
Generation: 6
New Best Solution Fitness: 20508206
New Best Solution Fitness: 20507001
Generation: 7
New Best Solution Fitness: 20505567
Generation: 8
New Best Solution Fitness: 20505558
Generation: 9
New Best Solution Fitness: 20503302
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 10.7 
Mean sub-tour choices: 3.34444 
Best Solution Fitness: 20503302 
--------------------------------------------- 
