--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\usa13509.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 20665366
New Best Solution Fitness: 20660025
New Best Solution Fitness: 20655098
Generation: 3
New Best Solution Fitness: 20485576
New Best Solution Fitness: 20485219
New Best Solution Fitness: 20485020
New Best Solution Fitness: 20484825
New Best Solution Fitness: 20483040
Generation: 4
New Best Solution Fitness: 20448266
New Best Solution Fitness: 20448009
New Best Solution Fitness: 20447399
Generation: 5
New Best Solution Fitness: 20431173
New Best Solution Fitness: 20430432
Generation: 6
New Best Solution Fitness: 20427332
New Best Solution Fitness: 20427232
New Best Solution Fitness: 20426581
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 20426173
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 11.9778 
Mean sub-tour choices: 2.52222 
Best Solution Fitness: 20426173 
--------------------------------------------- 
