--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\usa13509.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 20944361
New Best Solution Fitness: 20941823
Generation: 3
New Best Solution Fitness: 20780504
New Best Solution Fitness: 20779503
New Best Solution Fitness: 20778086
Generation: 4
New Best Solution Fitness: 20755946
New Best Solution Fitness: 20754047
New Best Solution Fitness: 20753379
Generation: 5
New Best Solution Fitness: 20710204
New Best Solution Fitness: 20710078
New Best Solution Fitness: 20708305
Generation: 6
New Best Solution Fitness: 20591881
New Best Solution Fitness: 20591378
Generation: 7
New Best Solution Fitness: 20589143
New Best Solution Fitness: 20589017
New Best Solution Fitness: 20588887
Generation: 8
New Best Solution Fitness: 20587861
New Best Solution Fitness: 20587735
Generation: 9
New Best Solution Fitness: 20545590
Generation: 10
New Best Solution Fitness: 20522375
New Best Solution Fitness: 20519707
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 11.4 
Mean sub-tour choices: 2.14444 
Best Solution Fitness: 20519707 
--------------------------------------------- 
