--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\usa13509.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 20890495
New Best Solution Fitness: 20888829
New Best Solution Fitness: 20878010
Generation: 3
New Best Solution Fitness: 20702711
Generation: 4
New Best Solution Fitness: 20613699
New Best Solution Fitness: 20613074
Generation: 5
New Best Solution Fitness: 20543917
New Best Solution Fitness: 20541625
New Best Solution Fitness: 20538679
Generation: 6
New Best Solution Fitness: 20489402
New Best Solution Fitness: 20488525
Generation: 7
New Best Solution Fitness: 20478247
New Best Solution Fitness: 20478147
New Best Solution Fitness: 20478031
New Best Solution Fitness: 20477932
New Best Solution Fitness: 20470905
Generation: 8
New Best Solution Fitness: 20455411
New Best Solution Fitness: 20455304
Generation: 9
New Best Solution Fitness: 20447822
Generation: 10
New Best Solution Fitness: 20443455
New Best Solution Fitness: 20441429
New Best Solution Fitness: 20438951
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 12.7889 
Mean sub-tour choices: 2.06667 
Best Solution Fitness: 20438951 
--------------------------------------------- 
