--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\usa13509.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 20979215
New Best Solution Fitness: 20978824
New Best Solution Fitness: 20978527
Generation: 3
New Best Solution Fitness: 20705339
New Best Solution Fitness: 20705216
New Best Solution Fitness: 20704689
New Best Solution Fitness: 20701737
Generation: 4
New Best Solution Fitness: 20539477
New Best Solution Fitness: 20539283
New Best Solution Fitness: 20537579
New Best Solution Fitness: 20537294
Generation: 5
New Best Solution Fitness: 20533317
New Best Solution Fitness: 20532783
New Best Solution Fitness: 20532263
Generation: 6
New Best Solution Fitness: 20531211
New Best Solution Fitness: 20531017
New Best Solution Fitness: 20530677
Generation: 7
New Best Solution Fitness: 20530483
New Best Solution Fitness: 20522628
Generation: 8
New Best Solution Fitness: 20521828
Generation: 9
New Best Solution Fitness: 20521634
Generation: 10
New Best Solution Fitness: 20521530
New Best Solution Fitness: 20520850
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 13.2778 
Mean sub-tour choices: 2.45556 
Best Solution Fitness: 20520850 
--------------------------------------------- 
