--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 119004
New Best Solution Fitness: 118780
Generation: 3
Generation: 4
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 118708
New Best Solution Fitness: 118356
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.322222 
Mean sub-tour choices: 0.433333 
Best Solution Fitness: 118356 
--------------------------------------------- 
