--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 118714
Generation: 3
Generation: 4
New Best Solution Fitness: 118662
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 118579
Generation: 8
Generation: 9
New Best Solution Fitness: 118282
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.0444444 
Mean sub-tour choices: 0.0666667 
Best Solution Fitness: 118282 
--------------------------------------------- 
