--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 119600
Generation: 3
New Best Solution Fitness: 119200
Generation: 4
New Best Solution Fitness: 119163
Generation: 5
New Best Solution Fitness: 118977
Generation: 6
New Best Solution Fitness: 118626
Generation: 7
New Best Solution Fitness: 118579
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.0666667 
Mean sub-tour choices: 0.111111 
Best Solution Fitness: 118579 
--------------------------------------------- 
