--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 119924
Generation: 3
New Best Solution Fitness: 119750
Generation: 4
New Best Solution Fitness: 119421
Generation: 5
New Best Solution Fitness: 119319
Generation: 6
Generation: 7
New Best Solution Fitness: 119146
New Best Solution Fitness: 118944
Generation: 8
New Best Solution Fitness: 118900
Generation: 9
New Best Solution Fitness: 118715
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.0888889 
Mean sub-tour choices: 0.133333 
Best Solution Fitness: 118715 
--------------------------------------------- 
