--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 120422
Generation: 3
New Best Solution Fitness: 120281
Generation: 4
New Best Solution Fitness: 118999
Generation: 5
New Best Solution Fitness: 118955
Generation: 6
Generation: 7
New Best Solution Fitness: 118423
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.0333333 
Mean sub-tour choices: 0.0666667 
Best Solution Fitness: 118423 
--------------------------------------------- 
