--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 119941
New Best Solution Fitness: 119747
Generation: 3
New Best Solution Fitness: 119141
Generation: 4
Generation: 5
New Best Solution Fitness: 118527
New Best Solution Fitness: 118467
New Best Solution Fitness: 118423
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.311111 
Mean sub-tour choices: 0.422222 
Best Solution Fitness: 118423 
--------------------------------------------- 
