--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 119961
Generation: 3
New Best Solution Fitness: 119725
Generation: 4
New Best Solution Fitness: 119446
Generation: 5
New Best Solution Fitness: 119097
Generation: 6
New Best Solution Fitness: 118932
New Best Solution Fitness: 118888
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 118470
New Best Solution Fitness: 118423
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.166667 
Mean sub-tour choices: 0.222222 
Best Solution Fitness: 118423 
--------------------------------------------- 
