--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 119426
Generation: 3
New Best Solution Fitness: 119200
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 119172
Generation: 7
New Best Solution Fitness: 118942
Generation: 8
Generation: 9
New Best Solution Fitness: 118657
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.0222222 
Mean sub-tour choices: 0.0222222 
Best Solution Fitness: 118657 
--------------------------------------------- 
