--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 118899
Generation: 3
New Best Solution Fitness: 118757
New Best Solution Fitness: 118683
Generation: 4
Generation: 5
New Best Solution Fitness: 118579
Generation: 6
New Best Solution Fitness: 118423
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.177778 
Mean sub-tour choices: 0.333333 
Best Solution Fitness: 118423 
--------------------------------------------- 
