--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 119875
Generation: 3
New Best Solution Fitness: 119366
Generation: 4
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 119329
Generation: 8
New Best Solution Fitness: 119064
Generation: 9
New Best Solution Fitness: 118900
New Best Solution Fitness: 118856
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.133333 
Mean sub-tour choices: 0.177778 
Best Solution Fitness: 118856 
--------------------------------------------- 
