--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 118816
New Best Solution Fitness: 118804
Generation: 3
New Best Solution Fitness: 118760
Generation: 4
Generation: 5
New Best Solution Fitness: 118579
Generation: 6
New Best Solution Fitness: 118356
New Best Solution Fitness: 118282
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.177778 
Mean sub-tour choices: 0.277778 
Best Solution Fitness: 118282 
--------------------------------------------- 
