--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 120052
Generation: 3
New Best Solution Fitness: 119832
Generation: 4
New Best Solution Fitness: 119141
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 118856
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 118683
New Best Solution Fitness: 118657
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.133333 
Mean sub-tour choices: 0.177778 
Best Solution Fitness: 118657 
--------------------------------------------- 
