--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 118713
New Best Solution Fitness: 118682
Generation: 3
Generation: 4
New Best Solution Fitness: 118616
Generation: 5
New Best Solution Fitness: 118579
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.3 
Mean sub-tour choices: 0.344444 
Best Solution Fitness: 118579 
--------------------------------------------- 
