--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 118856
Generation: 3
New Best Solution Fitness: 118792
Generation: 4
New Best Solution Fitness: 118780
Generation: 5
New Best Solution Fitness: 118615
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 118554
Generation: 9
New Best Solution Fitness: 118282
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.1 
Mean sub-tour choices: 0.155556 
Best Solution Fitness: 118282 
--------------------------------------------- 
