--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
Generation: 3
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 119178
New Best Solution Fitness: 118615
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.0777778 
Mean sub-tour choices: 0.111111 
Best Solution Fitness: 118615 
--------------------------------------------- 
