--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 119734
Generation: 3
Generation: 4
New Best Solution Fitness: 119620
Generation: 5
New Best Solution Fitness: 119608
Generation: 6
Generation: 7
New Best Solution Fitness: 119205
Generation: 8
New Best Solution Fitness: 118767
New Best Solution Fitness: 118693
Generation: 9
Generation: 10
New Best Solution Fitness: 118621
New Best Solution Fitness: 118423
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.355556 
Mean sub-tour choices: 0.488889 
Best Solution Fitness: 118423 
--------------------------------------------- 
