--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 119801
New Best Solution Fitness: 119747
Generation: 3
Generation: 4
New Best Solution Fitness: 119695
Generation: 5
New Best Solution Fitness: 119654
Generation: 6
New Best Solution Fitness: 119487
Generation: 7
New Best Solution Fitness: 119426
New Best Solution Fitness: 119313
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.277778 
Mean sub-tour choices: 0.411111 
Best Solution Fitness: 119313 
--------------------------------------------- 
