--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 120543
Generation: 3
New Best Solution Fitness: 120438
Generation: 4
New Best Solution Fitness: 119367
New Best Solution Fitness: 119313
Generation: 5
Generation: 6
New Best Solution Fitness: 118962
Generation: 7
Generation: 8
New Best Solution Fitness: 118579
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.0888889 
Mean sub-tour choices: 0.155556 
Best Solution Fitness: 118579 
--------------------------------------------- 
