--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 120127
Generation: 3
New Best Solution Fitness: 119438
Generation: 4
New Best Solution Fitness: 118766
New Best Solution Fitness: 118692
Generation: 5
Generation: 6
New Best Solution Fitness: 118461
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.0444444 
Mean sub-tour choices: 0.0666667 
Best Solution Fitness: 118461 
--------------------------------------------- 
