--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 118715
Generation: 3
Generation: 4
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 118681
New Best Solution Fitness: 118607
Generation: 8
New Best Solution Fitness: 118282
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.0888889 
Mean sub-tour choices: 0.1 
Best Solution Fitness: 118282 
--------------------------------------------- 
