--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 119539
New Best Solution Fitness: 119487
Generation: 3
Generation: 4
New Best Solution Fitness: 119431
New Best Solution Fitness: 119268
Generation: 5
New Best Solution Fitness: 119194
Generation: 6
New Best Solution Fitness: 118973
Generation: 7
Generation: 8
New Best Solution Fitness: 118861
Generation: 9
Generation: 10
New Best Solution Fitness: 118788
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.222222 
Mean sub-tour choices: 0.266667 
Best Solution Fitness: 118788 
--------------------------------------------- 
