--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Black Box Steady State 
Population: 10
Mutation probability: 1
Crossover probability: 0.000169062
--------------------------
Job Complete 
Best Solution Fitness: 659493
Iterations: 349872250
--------------------------------------------- 
