--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142229
New Best Solution Fitness: 142188
New Best Solution Fitness: 142173
Generation: 3
New Best Solution Fitness: 141715
New Best Solution Fitness: 141648
New Best Solution Fitness: 141606
Generation: 4
New Best Solution Fitness: 141474
New Best Solution Fitness: 141460
Generation: 5
New Best Solution Fitness: 141413
New Best Solution Fitness: 141401
Generation: 6
New Best Solution Fitness: 141398
New Best Solution Fitness: 141338
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.54444 
Mean sub-tour choices: 2.56667 
Best Solution Fitness: 141338 
--------------------------------------------- 
