--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142205
New Best Solution Fitness: 142145
Generation: 3
New Best Solution Fitness: 141826
New Best Solution Fitness: 141817
New Best Solution Fitness: 141797
Generation: 4
New Best Solution Fitness: 141722
Generation: 5
New Best Solution Fitness: 141713
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 141708
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.26667 
Mean sub-tour choices: 2.25556 
Best Solution Fitness: 141708 
--------------------------------------------- 
