--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142579
New Best Solution Fitness: 142543
New Best Solution Fitness: 142403
New Best Solution Fitness: 142394
Generation: 3
New Best Solution Fitness: 141705
New Best Solution Fitness: 141668
New Best Solution Fitness: 141651
Generation: 4
New Best Solution Fitness: 141518
New Best Solution Fitness: 141464
Generation: 5
New Best Solution Fitness: 141444
New Best Solution Fitness: 141433
New Best Solution Fitness: 141345
Generation: 6
New Best Solution Fitness: 141319
Generation: 7
New Best Solution Fitness: 141305
Generation: 8
New Best Solution Fitness: 141294
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 5.31111 
Mean sub-tour choices: 2.15556 
Best Solution Fitness: 141294 
--------------------------------------------- 
