--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142477
New Best Solution Fitness: 142389
New Best Solution Fitness: 142242
New Best Solution Fitness: 142170
Generation: 3
New Best Solution Fitness: 141934
New Best Solution Fitness: 141885
New Best Solution Fitness: 141853
Generation: 4
New Best Solution Fitness: 141695
New Best Solution Fitness: 141658
Generation: 5
New Best Solution Fitness: 141631
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 5.14444 
Mean sub-tour choices: 2.66667 
Best Solution Fitness: 141631 
--------------------------------------------- 
