--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142650
New Best Solution Fitness: 142594
Generation: 3
New Best Solution Fitness: 142152
New Best Solution Fitness: 142115
New Best Solution Fitness: 142036
Generation: 4
New Best Solution Fitness: 141609
New Best Solution Fitness: 141493
Generation: 5
New Best Solution Fitness: 141297
Generation: 6
New Best Solution Fitness: 141241
Generation: 7
New Best Solution Fitness: 141170
Generation: 8
Generation: 9
New Best Solution Fitness: 140968
New Best Solution Fitness: 140952
Generation: 10
New Best Solution Fitness: 140950
New Best Solution Fitness: 140915
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.62222 
Mean sub-tour choices: 1.44444 
Best Solution Fitness: 140915 
--------------------------------------------- 
