--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142298
New Best Solution Fitness: 142250
New Best Solution Fitness: 142210
New Best Solution Fitness: 142087
Generation: 3
New Best Solution Fitness: 141808
New Best Solution Fitness: 141805
Generation: 4
New Best Solution Fitness: 141720
New Best Solution Fitness: 141718
New Best Solution Fitness: 141708
Generation: 5
New Best Solution Fitness: 141706
Generation: 6
New Best Solution Fitness: 141482
New Best Solution Fitness: 141480
Generation: 7
New Best Solution Fitness: 141426
New Best Solution Fitness: 141424
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 141341
New Best Solution Fitness: 141324
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.35556 
Mean sub-tour choices: 2.06667 
Best Solution Fitness: 141324 
--------------------------------------------- 
