--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142294
New Best Solution Fitness: 142233
Generation: 3
New Best Solution Fitness: 141583
New Best Solution Fitness: 141576
Generation: 4
New Best Solution Fitness: 141193
New Best Solution Fitness: 141192
Generation: 5
New Best Solution Fitness: 141184
New Best Solution Fitness: 141179
New Best Solution Fitness: 141175
Generation: 6
New Best Solution Fitness: 141173
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 141045
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.34444 
Mean sub-tour choices: 1.95556 
Best Solution Fitness: 141045 
--------------------------------------------- 
