--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142131
Generation: 3
New Best Solution Fitness: 141368
New Best Solution Fitness: 141312
New Best Solution Fitness: 141232
Generation: 4
New Best Solution Fitness: 141113
New Best Solution Fitness: 141068
Generation: 5
Generation: 6
New Best Solution Fitness: 140603
New Best Solution Fitness: 140590
New Best Solution Fitness: 140581
Generation: 7
New Best Solution Fitness: 140461
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 140328
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.83333 
Mean sub-tour choices: 1.71111 
Best Solution Fitness: 140328 
--------------------------------------------- 
