--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142256
New Best Solution Fitness: 142250
New Best Solution Fitness: 142128
New Best Solution Fitness: 142106
New Best Solution Fitness: 142102
Generation: 3
New Best Solution Fitness: 142006
New Best Solution Fitness: 141980
New Best Solution Fitness: 141950
Generation: 4
New Best Solution Fitness: 141946
New Best Solution Fitness: 141930
Generation: 5
New Best Solution Fitness: 141642
New Best Solution Fitness: 141640
New Best Solution Fitness: 141636
Generation: 6
New Best Solution Fitness: 141634
New Best Solution Fitness: 141633
New Best Solution Fitness: 141632
Generation: 7
New Best Solution Fitness: 141606
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.52222 
Mean sub-tour choices: 2.37778 
Best Solution Fitness: 141606 
--------------------------------------------- 
