--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141711
New Best Solution Fitness: 141674
New Best Solution Fitness: 141586
New Best Solution Fitness: 141484
Generation: 3
New Best Solution Fitness: 141293
Generation: 4
New Best Solution Fitness: 141158
New Best Solution Fitness: 141140
New Best Solution Fitness: 141086
Generation: 5
New Best Solution Fitness: 141036
New Best Solution Fitness: 141018
Generation: 6
New Best Solution Fitness: 140950
New Best Solution Fitness: 140947
Generation: 7
New Best Solution Fitness: 140943
New Best Solution Fitness: 140925
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.63333 
Mean sub-tour choices: 2.2 
Best Solution Fitness: 140925 
--------------------------------------------- 
