--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142007
New Best Solution Fitness: 141992
New Best Solution Fitness: 141988
New Best Solution Fitness: 141955
Generation: 3
New Best Solution Fitness: 141583
New Best Solution Fitness: 141337
Generation: 4
New Best Solution Fitness: 141231
New Best Solution Fitness: 141206
Generation: 5
New Best Solution Fitness: 141191
Generation: 6
New Best Solution Fitness: 141129
New Best Solution Fitness: 141115
Generation: 7
New Best Solution Fitness: 141113
Generation: 8
New Best Solution Fitness: 141077
New Best Solution Fitness: 141076
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 6.05556 
Mean sub-tour choices: 2.1 
Best Solution Fitness: 141076 
--------------------------------------------- 
