--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142106
New Best Solution Fitness: 142095
New Best Solution Fitness: 142087
New Best Solution Fitness: 142076
Generation: 3
New Best Solution Fitness: 141715
New Best Solution Fitness: 141707
Generation: 4
New Best Solution Fitness: 141697
New Best Solution Fitness: 141695
New Best Solution Fitness: 141684
New Best Solution Fitness: 141681
New Best Solution Fitness: 141676
Generation: 5
New Best Solution Fitness: 141567
New Best Solution Fitness: 141551
New Best Solution Fitness: 141547
Generation: 6
New Best Solution Fitness: 141531
Generation: 7
New Best Solution Fitness: 141494
New Best Solution Fitness: 141486
New Best Solution Fitness: 141481
Generation: 8
New Best Solution Fitness: 141449
New Best Solution Fitness: 141441
Generation: 9
New Best Solution Fitness: 141403
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.66667 
Mean sub-tour choices: 1.97778 
Best Solution Fitness: 141403 
--------------------------------------------- 
