--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142195
New Best Solution Fitness: 142106
Generation: 3
New Best Solution Fitness: 141835
New Best Solution Fitness: 141827
New Best Solution Fitness: 141816
New Best Solution Fitness: 141782
Generation: 4
New Best Solution Fitness: 141766
New Best Solution Fitness: 141758
New Best Solution Fitness: 141700
Generation: 5
New Best Solution Fitness: 141616
New Best Solution Fitness: 141470
New Best Solution Fitness: 141465
Generation: 6
New Best Solution Fitness: 141430
Generation: 7
New Best Solution Fitness: 141415
Generation: 8
New Best Solution Fitness: 141390
Generation: 9
New Best Solution Fitness: 141383
Generation: 10
New Best Solution Fitness: 141378
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.4 
Mean sub-tour choices: 2.33333 
Best Solution Fitness: 141378 
--------------------------------------------- 
