--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142534
New Best Solution Fitness: 142502
New Best Solution Fitness: 142425
New Best Solution Fitness: 142420
Generation: 3
New Best Solution Fitness: 142206
New Best Solution Fitness: 142161
Generation: 4
New Best Solution Fitness: 142073
New Best Solution Fitness: 142061
Generation: 5
Generation: 6
New Best Solution Fitness: 142046
Generation: 7
New Best Solution Fitness: 141931
New Best Solution Fitness: 141913
Generation: 8
New Best Solution Fitness: 141893
New Best Solution Fitness: 141887
Generation: 9
New Best Solution Fitness: 141873
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.72222 
Mean sub-tour choices: 2.72222 
Best Solution Fitness: 141873 
--------------------------------------------- 
