--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141879
New Best Solution Fitness: 141762
Generation: 3
New Best Solution Fitness: 141311
New Best Solution Fitness: 141309
New Best Solution Fitness: 141301
Generation: 4
New Best Solution Fitness: 141265
New Best Solution Fitness: 141255
New Best Solution Fitness: 141236
Generation: 5
New Best Solution Fitness: 141233
New Best Solution Fitness: 141223
Generation: 6
New Best Solution Fitness: 141202
Generation: 7
New Best Solution Fitness: 141200
Generation: 8
Generation: 9
New Best Solution Fitness: 141194
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.32222 
Mean sub-tour choices: 1.91111 
Best Solution Fitness: 141194 
--------------------------------------------- 
