--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142154
New Best Solution Fitness: 142132
New Best Solution Fitness: 142130
Generation: 3
New Best Solution Fitness: 141725
New Best Solution Fitness: 141716
New Best Solution Fitness: 141672
Generation: 4
New Best Solution Fitness: 141523
New Best Solution Fitness: 141505
New Best Solution Fitness: 141501
Generation: 5
New Best Solution Fitness: 141433
Generation: 6
New Best Solution Fitness: 141415
Generation: 7
Generation: 8
New Best Solution Fitness: 141411
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.42222 
Mean sub-tour choices: 2.65556 
Best Solution Fitness: 141411 
--------------------------------------------- 
