--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141852
New Best Solution Fitness: 141814
New Best Solution Fitness: 141711
Generation: 3
New Best Solution Fitness: 141443
New Best Solution Fitness: 141428
New Best Solution Fitness: 141379
New Best Solution Fitness: 141282
Generation: 4
New Best Solution Fitness: 141257
New Best Solution Fitness: 141253
New Best Solution Fitness: 141193
Generation: 5
New Best Solution Fitness: 141190
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 5.63333 
Mean sub-tour choices: 4.16667 
Best Solution Fitness: 141190 
--------------------------------------------- 
