--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141679
New Best Solution Fitness: 141663
Generation: 3
New Best Solution Fitness: 141302
New Best Solution Fitness: 141283
Generation: 4
New Best Solution Fitness: 141280
Generation: 5
New Best Solution Fitness: 141256
Generation: 6
New Best Solution Fitness: 141215
New Best Solution Fitness: 141191
New Best Solution Fitness: 141187
Generation: 7
New Best Solution Fitness: 141183
New Best Solution Fitness: 141177
New Best Solution Fitness: 141160
Generation: 8
New Best Solution Fitness: 141154
Generation: 9
New Best Solution Fitness: 141148
Generation: 10
New Best Solution Fitness: 141143
New Best Solution Fitness: 141046
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.31111 
Mean sub-tour choices: 2.32222 
Best Solution Fitness: 141046 
--------------------------------------------- 
