--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142002
New Best Solution Fitness: 141975
New Best Solution Fitness: 141954
New Best Solution Fitness: 141859
Generation: 3
New Best Solution Fitness: 141628
New Best Solution Fitness: 141609
New Best Solution Fitness: 141607
New Best Solution Fitness: 141588
New Best Solution Fitness: 141572
Generation: 4
New Best Solution Fitness: 141532
New Best Solution Fitness: 141527
Generation: 5
New Best Solution Fitness: 141492
Generation: 6
New Best Solution Fitness: 141487
Generation: 7
Generation: 8
New Best Solution Fitness: 141458
Generation: 9
New Best Solution Fitness: 141210
Generation: 10
New Best Solution Fitness: 141088
New Best Solution Fitness: 141083
New Best Solution Fitness: 141067
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.7 
Mean sub-tour choices: 2.16667 
Best Solution Fitness: 141067 
--------------------------------------------- 
