--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142009
New Best Solution Fitness: 141942
New Best Solution Fitness: 141700
Generation: 3
New Best Solution Fitness: 141230
New Best Solution Fitness: 141226
New Best Solution Fitness: 141225
Generation: 4
New Best Solution Fitness: 141015
New Best Solution Fitness: 141002
Generation: 5
New Best Solution Fitness: 140837
Generation: 6
New Best Solution Fitness: 140836
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4 
Mean sub-tour choices: 2.73333 
Best Solution Fitness: 140836 
--------------------------------------------- 
