--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141513
New Best Solution Fitness: 141431
Generation: 3
New Best Solution Fitness: 141007
New Best Solution Fitness: 141002
New Best Solution Fitness: 140995
Generation: 4
New Best Solution Fitness: 140906
New Best Solution Fitness: 140904
Generation: 5
New Best Solution Fitness: 140797
Generation: 6
Generation: 7
New Best Solution Fitness: 140752
Generation: 8
New Best Solution Fitness: 140734
New Best Solution Fitness: 140675
Generation: 9
New Best Solution Fitness: 140657
Generation: 10
New Best Solution Fitness: 140646
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.31111 
Mean sub-tour choices: 1.7 
Best Solution Fitness: 140646 
--------------------------------------------- 
