--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141888
New Best Solution Fitness: 141833
Generation: 3
New Best Solution Fitness: 141519
New Best Solution Fitness: 141404
Generation: 4
New Best Solution Fitness: 141344
New Best Solution Fitness: 141292
Generation: 5
New Best Solution Fitness: 141053
New Best Solution Fitness: 141051
Generation: 6
New Best Solution Fitness: 141049
New Best Solution Fitness: 141041
Generation: 7
New Best Solution Fitness: 140988
New Best Solution Fitness: 140950
Generation: 8
New Best Solution Fitness: 140940
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 5.53333 
Mean sub-tour choices: 2.64444 
Best Solution Fitness: 140940 
--------------------------------------------- 
