--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142285
New Best Solution Fitness: 142167
Generation: 3
New Best Solution Fitness: 141725
New Best Solution Fitness: 141695
Generation: 4
New Best Solution Fitness: 141242
New Best Solution Fitness: 141209
New Best Solution Fitness: 141207
Generation: 5
New Best Solution Fitness: 141193
New Best Solution Fitness: 141167
New Best Solution Fitness: 141161
Generation: 6
New Best Solution Fitness: 141052
New Best Solution Fitness: 141026
Generation: 7
New Best Solution Fitness: 140970
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.16667 
Mean sub-tour choices: 2.1 
Best Solution Fitness: 140970 
--------------------------------------------- 
