--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141040
New Best Solution Fitness: 141033
New Best Solution Fitness: 141025
New Best Solution Fitness: 140974
Generation: 3
New Best Solution Fitness: 140856
New Best Solution Fitness: 140795
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 140794
Generation: 7
New Best Solution Fitness: 140792
New Best Solution Fitness: 140790
New Best Solution Fitness: 140776
Generation: 8
New Best Solution Fitness: 140734
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.44444 
Mean sub-tour choices: 1.74444 
Best Solution Fitness: 140734 
--------------------------------------------- 
