--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142322
New Best Solution Fitness: 142317
New Best Solution Fitness: 142287
Generation: 3
New Best Solution Fitness: 141883
New Best Solution Fitness: 141881
New Best Solution Fitness: 141842
New Best Solution Fitness: 141836
Generation: 4
New Best Solution Fitness: 141705
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 141673
New Best Solution Fitness: 141663
Generation: 9
New Best Solution Fitness: 141662
Generation: 10
New Best Solution Fitness: 141597
New Best Solution Fitness: 141573
New Best Solution Fitness: 141453
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.97778 
Mean sub-tour choices: 2.1 
Best Solution Fitness: 141453 
--------------------------------------------- 
