--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141512
New Best Solution Fitness: 141457
New Best Solution Fitness: 141441
Generation: 3
New Best Solution Fitness: 141187
New Best Solution Fitness: 141143
Generation: 4
New Best Solution Fitness: 141121
Generation: 5
New Best Solution Fitness: 141100
New Best Solution Fitness: 141086
Generation: 6
New Best Solution Fitness: 141062
Generation: 7
Generation: 8
New Best Solution Fitness: 141052
Generation: 9
New Best Solution Fitness: 140883
New Best Solution Fitness: 140876
New Best Solution Fitness: 140857
Generation: 10
New Best Solution Fitness: 140821
New Best Solution Fitness: 140814
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.94444 
Mean sub-tour choices: 1.76667 
Best Solution Fitness: 140814 
--------------------------------------------- 
