--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142432
New Best Solution Fitness: 142397
Generation: 3
New Best Solution Fitness: 142003
New Best Solution Fitness: 141988
New Best Solution Fitness: 141969
Generation: 4
New Best Solution Fitness: 141947
New Best Solution Fitness: 141896
Generation: 5
New Best Solution Fitness: 141885
New Best Solution Fitness: 141880
Generation: 6
New Best Solution Fitness: 141776
Generation: 7
New Best Solution Fitness: 141742
Generation: 8
New Best Solution Fitness: 141721
New Best Solution Fitness: 141709
Generation: 9
New Best Solution Fitness: 141691
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.15556 
Mean sub-tour choices: 2.63333 
Best Solution Fitness: 141691 
--------------------------------------------- 
