--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141739
New Best Solution Fitness: 141735
New Best Solution Fitness: 141713
Generation: 3
New Best Solution Fitness: 141297
New Best Solution Fitness: 141262
New Best Solution Fitness: 141204
Generation: 4
New Best Solution Fitness: 141173
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.13333 
Mean sub-tour choices: 1.87778 
Best Solution Fitness: 141173 
--------------------------------------------- 
