--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142275
New Best Solution Fitness: 142117
New Best Solution Fitness: 142064
Generation: 3
New Best Solution Fitness: 141538
New Best Solution Fitness: 141498
New Best Solution Fitness: 141465
Generation: 4
New Best Solution Fitness: 141345
New Best Solution Fitness: 141131
Generation: 5
New Best Solution Fitness: 141109
Generation: 6
New Best Solution Fitness: 141089
Generation: 7
Generation: 8
New Best Solution Fitness: 141077
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.15556 
Mean sub-tour choices: 4.15556 
Best Solution Fitness: 141077 
--------------------------------------------- 
