--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142053
New Best Solution Fitness: 141895
Generation: 3
New Best Solution Fitness: 141431
New Best Solution Fitness: 141404
Generation: 4
New Best Solution Fitness: 141396
New Best Solution Fitness: 141301
Generation: 5
New Best Solution Fitness: 141245
New Best Solution Fitness: 141237
Generation: 6
Generation: 7
New Best Solution Fitness: 141234
Generation: 8
New Best Solution Fitness: 141218
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.97778 
Mean sub-tour choices: 2.76667 
Best Solution Fitness: 141218 
--------------------------------------------- 
