--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 143072
New Best Solution Fitness: 143070
New Best Solution Fitness: 143035
Generation: 3
New Best Solution Fitness: 141812
New Best Solution Fitness: 141793
New Best Solution Fitness: 141790
Generation: 4
New Best Solution Fitness: 141766
New Best Solution Fitness: 141747
Generation: 5
New Best Solution Fitness: 141740
New Best Solution Fitness: 141607
Generation: 6
New Best Solution Fitness: 141600
Generation: 7
New Best Solution Fitness: 141593
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.95556 
Mean sub-tour choices: 1.82222 
Best Solution Fitness: 141593 
--------------------------------------------- 
