--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141367
New Best Solution Fitness: 141352
Generation: 3
New Best Solution Fitness: 141071
Generation: 4
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 141055
New Best Solution Fitness: 141054
New Best Solution Fitness: 141040
Generation: 9
New Best Solution Fitness: 140979
New Best Solution Fitness: 140965
Generation: 10
New Best Solution Fitness: 140851
New Best Solution Fitness: 140815
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2 
Mean sub-tour choices: 1.71111 
Best Solution Fitness: 140815 
--------------------------------------------- 
