--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142311
New Best Solution Fitness: 142310
New Best Solution Fitness: 142223
Generation: 3
New Best Solution Fitness: 141969
New Best Solution Fitness: 141934
Generation: 4
New Best Solution Fitness: 141568
New Best Solution Fitness: 141491
New Best Solution Fitness: 141412
Generation: 5
New Best Solution Fitness: 141371
New Best Solution Fitness: 141339
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 141317
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.23333 
Mean sub-tour choices: 2.35556 
Best Solution Fitness: 141317 
--------------------------------------------- 
