--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142289
New Best Solution Fitness: 142278
New Best Solution Fitness: 142132
Generation: 3
New Best Solution Fitness: 141721
New Best Solution Fitness: 141694
New Best Solution Fitness: 141663
New Best Solution Fitness: 141656
Generation: 4
New Best Solution Fitness: 141639
New Best Solution Fitness: 141494
Generation: 5
New Best Solution Fitness: 141428
New Best Solution Fitness: 141380
Generation: 6
New Best Solution Fitness: 141373
Generation: 7
New Best Solution Fitness: 141367
Generation: 8
New Best Solution Fitness: 141364
New Best Solution Fitness: 141351
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.7 
Mean sub-tour choices: 3.12222 
Best Solution Fitness: 141351 
--------------------------------------------- 
