--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142713
New Best Solution Fitness: 142684
New Best Solution Fitness: 142634
New Best Solution Fitness: 142464
Generation: 3
New Best Solution Fitness: 141211
New Best Solution Fitness: 141197
New Best Solution Fitness: 141182
New Best Solution Fitness: 141165
Generation: 4
New Best Solution Fitness: 141087
New Best Solution Fitness: 141058
Generation: 5
New Best Solution Fitness: 141042
Generation: 6
New Best Solution Fitness: 140707
New Best Solution Fitness: 140701
New Best Solution Fitness: 140693
Generation: 7
New Best Solution Fitness: 140664
New Best Solution Fitness: 140635
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.92222 
Mean sub-tour choices: 3.06667 
Best Solution Fitness: 140635 
--------------------------------------------- 
