--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142996
New Best Solution Fitness: 142989
New Best Solution Fitness: 142975
New Best Solution Fitness: 142832
Generation: 3
New Best Solution Fitness: 142612
New Best Solution Fitness: 142595
Generation: 4
New Best Solution Fitness: 142382
New Best Solution Fitness: 142304
Generation: 5
New Best Solution Fitness: 142293
New Best Solution Fitness: 142245
New Best Solution Fitness: 142168
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 5.25556 
Mean sub-tour choices: 2.46667 
Best Solution Fitness: 142168 
--------------------------------------------- 
