--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141617
New Best Solution Fitness: 141599
New Best Solution Fitness: 141587
New Best Solution Fitness: 141579
Generation: 3
New Best Solution Fitness: 141161
New Best Solution Fitness: 141143
New Best Solution Fitness: 141097
Generation: 4
New Best Solution Fitness: 141091
New Best Solution Fitness: 141073
New Best Solution Fitness: 141044
Generation: 5
New Best Solution Fitness: 141042
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 5.11111 
Mean sub-tour choices: 2.81111 
Best Solution Fitness: 141042 
--------------------------------------------- 
