--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141924
New Best Solution Fitness: 141878
New Best Solution Fitness: 141757
Generation: 3
New Best Solution Fitness: 141622
New Best Solution Fitness: 141621
New Best Solution Fitness: 141597
Generation: 4
New Best Solution Fitness: 141543
Generation: 5
New Best Solution Fitness: 141528
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 141508
Generation: 9
New Best Solution Fitness: 141427
Generation: 10
New Best Solution Fitness: 141317
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.67778 
Mean sub-tour choices: 2.73333 
Best Solution Fitness: 141317 
--------------------------------------------- 
