--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142353
New Best Solution Fitness: 142244
New Best Solution Fitness: 142225
Generation: 3
New Best Solution Fitness: 141681
New Best Solution Fitness: 141593
New Best Solution Fitness: 141572
Generation: 4
New Best Solution Fitness: 141443
New Best Solution Fitness: 141442
Generation: 5
New Best Solution Fitness: 141390
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 141353
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.36667 
Mean sub-tour choices: 2.23333 
Best Solution Fitness: 141353 
--------------------------------------------- 
