--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141834
New Best Solution Fitness: 141787
New Best Solution Fitness: 141771
Generation: 3
New Best Solution Fitness: 141575
New Best Solution Fitness: 141570
New Best Solution Fitness: 141532
New Best Solution Fitness: 141502
Generation: 4
New Best Solution Fitness: 141497
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 141496
Generation: 9
New Best Solution Fitness: 141494
New Best Solution Fitness: 141487
Generation: 10
New Best Solution Fitness: 141397
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.72222 
Mean sub-tour choices: 2.55556 
Best Solution Fitness: 141397 
--------------------------------------------- 
