--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142322
New Best Solution Fitness: 142263
New Best Solution Fitness: 142199
New Best Solution Fitness: 142180
Generation: 3
New Best Solution Fitness: 141878
New Best Solution Fitness: 141873
New Best Solution Fitness: 141777
Generation: 4
New Best Solution Fitness: 141689
New Best Solution Fitness: 141661
Generation: 5
New Best Solution Fitness: 141506
New Best Solution Fitness: 141501
New Best Solution Fitness: 141500
Generation: 6
New Best Solution Fitness: 141495
Generation: 7
New Best Solution Fitness: 141492
Generation: 8
New Best Solution Fitness: 141455
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.83333 
Mean sub-tour choices: 2.77778 
Best Solution Fitness: 141455 
--------------------------------------------- 
