--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142151
New Best Solution Fitness: 142139
New Best Solution Fitness: 142138
New Best Solution Fitness: 142125
Generation: 3
New Best Solution Fitness: 142000
New Best Solution Fitness: 141994
New Best Solution Fitness: 141935
Generation: 4
New Best Solution Fitness: 141838
New Best Solution Fitness: 141795
Generation: 5
New Best Solution Fitness: 141791
New Best Solution Fitness: 141790
Generation: 6
Generation: 7
New Best Solution Fitness: 141769
New Best Solution Fitness: 141760
Generation: 8
New Best Solution Fitness: 141687
Generation: 9
New Best Solution Fitness: 141644
Generation: 10
New Best Solution Fitness: 141628
New Best Solution Fitness: 141586
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.57778 
Mean sub-tour choices: 2.05556 
Best Solution Fitness: 141586 
--------------------------------------------- 
