--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141735
New Best Solution Fitness: 141696
New Best Solution Fitness: 141657
New Best Solution Fitness: 141655
Generation: 3
New Best Solution Fitness: 141387
New Best Solution Fitness: 141373
New Best Solution Fitness: 141369
New Best Solution Fitness: 141331
Generation: 4
New Best Solution Fitness: 141223
New Best Solution Fitness: 141204
New Best Solution Fitness: 141170
Generation: 5
New Best Solution Fitness: 141151
Generation: 6
New Best Solution Fitness: 141137
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 141124
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.53333 
Mean sub-tour choices: 2.8 
Best Solution Fitness: 141124 
--------------------------------------------- 
