--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142152
New Best Solution Fitness: 142146
New Best Solution Fitness: 142115
New Best Solution Fitness: 142017
New Best Solution Fitness: 142003
Generation: 3
New Best Solution Fitness: 141474
New Best Solution Fitness: 141433
New Best Solution Fitness: 141385
Generation: 4
New Best Solution Fitness: 141034
New Best Solution Fitness: 140926
Generation: 5
New Best Solution Fitness: 140821
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 140747
New Best Solution Fitness: 140724
Generation: 9
New Best Solution Fitness: 140712
New Best Solution Fitness: 140711
New Best Solution Fitness: 140702
Generation: 10
New Best Solution Fitness: 140677
New Best Solution Fitness: 140665
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.64444 
Mean sub-tour choices: 2.12222 
Best Solution Fitness: 140665 
--------------------------------------------- 
