--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142573
New Best Solution Fitness: 142498
New Best Solution Fitness: 142369
Generation: 3
New Best Solution Fitness: 141882
New Best Solution Fitness: 141826
Generation: 4
New Best Solution Fitness: 141773
New Best Solution Fitness: 141738
Generation: 5
New Best Solution Fitness: 141639
Generation: 6
Generation: 7
New Best Solution Fitness: 141573
New Best Solution Fitness: 141369
Generation: 8
New Best Solution Fitness: 141215
Generation: 9
Generation: 10
New Best Solution Fitness: 140882
New Best Solution Fitness: 140861
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.35556 
Mean sub-tour choices: 2.47778 
Best Solution Fitness: 140861 
--------------------------------------------- 
