--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 140941
New Best Solution Fitness: 140885
Generation: 3
New Best Solution Fitness: 140784
New Best Solution Fitness: 140712
Generation: 4
New Best Solution Fitness: 140548
New Best Solution Fitness: 140525
New Best Solution Fitness: 140477
Generation: 5
New Best Solution Fitness: 140474
New Best Solution Fitness: 140470
Generation: 6
Generation: 7
New Best Solution Fitness: 140444
Generation: 8
Generation: 9
New Best Solution Fitness: 140421
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.62222 
Mean sub-tour choices: 2.75556 
Best Solution Fitness: 140421 
--------------------------------------------- 
