--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142282
New Best Solution Fitness: 142243
New Best Solution Fitness: 142146
New Best Solution Fitness: 142077
Generation: 3
New Best Solution Fitness: 141910
New Best Solution Fitness: 141884
Generation: 4
New Best Solution Fitness: 141475
New Best Solution Fitness: 141467
New Best Solution Fitness: 141412
Generation: 5
New Best Solution Fitness: 141307
New Best Solution Fitness: 141305
New Best Solution Fitness: 141291
Generation: 6
New Best Solution Fitness: 141289
Generation: 7
New Best Solution Fitness: 141288
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.86667 
Mean sub-tour choices: 2.48889 
Best Solution Fitness: 141288 
--------------------------------------------- 
