--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142308
New Best Solution Fitness: 142196
New Best Solution Fitness: 142132
New Best Solution Fitness: 142043
Generation: 3
New Best Solution Fitness: 141885
New Best Solution Fitness: 141872
Generation: 4
New Best Solution Fitness: 141821
Generation: 5
New Best Solution Fitness: 141804
Generation: 6
New Best Solution Fitness: 141598
Generation: 7
New Best Solution Fitness: 141596
Generation: 8
New Best Solution Fitness: 141586
Generation: 9
New Best Solution Fitness: 141286
New Best Solution Fitness: 141276
New Best Solution Fitness: 141275
Generation: 10
New Best Solution Fitness: 141107
New Best Solution Fitness: 141097
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.17778 
Mean sub-tour choices: 2.04444 
Best Solution Fitness: 141097 
--------------------------------------------- 
