--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 140872
New Best Solution Fitness: 140611
Generation: 3
New Best Solution Fitness: 140427
New Best Solution Fitness: 140422
New Best Solution Fitness: 140408
New Best Solution Fitness: 140401
Generation: 4
New Best Solution Fitness: 140396
New Best Solution Fitness: 140386
New Best Solution Fitness: 140379
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 140292
Generation: 8
New Best Solution Fitness: 140219
Generation: 9
New Best Solution Fitness: 140201
New Best Solution Fitness: 140196
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.54444 
Mean sub-tour choices: 2.35556 
Best Solution Fitness: 140196 
--------------------------------------------- 
