--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141985
New Best Solution Fitness: 141866
Generation: 3
New Best Solution Fitness: 141547
New Best Solution Fitness: 141499
Generation: 4
New Best Solution Fitness: 141381
New Best Solution Fitness: 141364
Generation: 5
New Best Solution Fitness: 141219
New Best Solution Fitness: 141195
Generation: 6
New Best Solution Fitness: 141191
New Best Solution Fitness: 141189
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.98889 
Mean sub-tour choices: 2.13333 
Best Solution Fitness: 141189 
--------------------------------------------- 
