--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141700
New Best Solution Fitness: 141698
New Best Solution Fitness: 141697
New Best Solution Fitness: 141671
Generation: 3
New Best Solution Fitness: 141580
New Best Solution Fitness: 141579
New Best Solution Fitness: 141578
Generation: 4
New Best Solution Fitness: 141433
New Best Solution Fitness: 141348
Generation: 5
New Best Solution Fitness: 141208
Generation: 6
New Best Solution Fitness: 141171
New Best Solution Fitness: 141162
Generation: 7
New Best Solution Fitness: 141147
Generation: 8
Generation: 9
New Best Solution Fitness: 140914
New Best Solution Fitness: 140895
Generation: 10
New Best Solution Fitness: 140859
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.36667 
Mean sub-tour choices: 1.75556 
Best Solution Fitness: 140859 
--------------------------------------------- 
