--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142088
New Best Solution Fitness: 142022
New Best Solution Fitness: 141909
Generation: 3
New Best Solution Fitness: 141668
New Best Solution Fitness: 141657
New Best Solution Fitness: 141641
New Best Solution Fitness: 141615
Generation: 4
New Best Solution Fitness: 141464
New Best Solution Fitness: 141401
Generation: 5
New Best Solution Fitness: 141215
New Best Solution Fitness: 141212
Generation: 6
New Best Solution Fitness: 141186
New Best Solution Fitness: 141183
New Best Solution Fitness: 141085
Generation: 7
New Best Solution Fitness: 141082
Generation: 8
New Best Solution Fitness: 141080
Generation: 9
New Best Solution Fitness: 141060
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.01111 
Mean sub-tour choices: 2.3 
Best Solution Fitness: 141060 
--------------------------------------------- 
