--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142376
New Best Solution Fitness: 142346
New Best Solution Fitness: 142276
Generation: 3
New Best Solution Fitness: 141590
New Best Solution Fitness: 141568
New Best Solution Fitness: 141539
Generation: 4
New Best Solution Fitness: 141528
New Best Solution Fitness: 141521
Generation: 5
New Best Solution Fitness: 141467
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.37778 
Mean sub-tour choices: 2.32222 
Best Solution Fitness: 141467 
--------------------------------------------- 
