--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141868
New Best Solution Fitness: 141816
New Best Solution Fitness: 141807
Generation: 3
New Best Solution Fitness: 141302
New Best Solution Fitness: 141294
New Best Solution Fitness: 141287
New Best Solution Fitness: 141233
Generation: 4
New Best Solution Fitness: 141179
New Best Solution Fitness: 141171
Generation: 5
New Best Solution Fitness: 141094
New Best Solution Fitness: 141056
Generation: 6
New Best Solution Fitness: 141021
Generation: 7
New Best Solution Fitness: 140950
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.33333 
Mean sub-tour choices: 2.46667 
Best Solution Fitness: 140950 
--------------------------------------------- 
