--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142724
New Best Solution Fitness: 142704
New Best Solution Fitness: 142692
Generation: 3
New Best Solution Fitness: 142175
New Best Solution Fitness: 142167
New Best Solution Fitness: 142153
New Best Solution Fitness: 142151
Generation: 4
New Best Solution Fitness: 141910
New Best Solution Fitness: 141888
Generation: 5
New Best Solution Fitness: 141885
New Best Solution Fitness: 141880
Generation: 6
New Best Solution Fitness: 141815
New Best Solution Fitness: 141789
Generation: 7
New Best Solution Fitness: 141786
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.17778 
Mean sub-tour choices: 2.2 
Best Solution Fitness: 141786 
--------------------------------------------- 
