--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142696
New Best Solution Fitness: 142553
New Best Solution Fitness: 142514
Generation: 3
New Best Solution Fitness: 141873
New Best Solution Fitness: 141807
Generation: 4
New Best Solution Fitness: 141705
New Best Solution Fitness: 141680
Generation: 5
New Best Solution Fitness: 141626
New Best Solution Fitness: 141611
Generation: 6
Generation: 7
New Best Solution Fitness: 141604
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 141573
New Best Solution Fitness: 141547
New Best Solution Fitness: 141505
New Best Solution Fitness: 141501
New Best Solution Fitness: 141439
New Best Solution Fitness: 141436
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.73333 
Mean sub-tour choices: 1.77778 
Best Solution Fitness: 141436 
--------------------------------------------- 
