--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141827
New Best Solution Fitness: 141793
New Best Solution Fitness: 141772
New Best Solution Fitness: 141769
New Best Solution Fitness: 141706
Generation: 3
New Best Solution Fitness: 141373
New Best Solution Fitness: 141366
New Best Solution Fitness: 141350
Generation: 4
New Best Solution Fitness: 141270
New Best Solution Fitness: 141259
New Best Solution Fitness: 141163
Generation: 5
New Best Solution Fitness: 141156
New Best Solution Fitness: 141072
Generation: 6
New Best Solution Fitness: 141049
Generation: 7
New Best Solution Fitness: 140932
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.64444 
Mean sub-tour choices: 2.14444 
Best Solution Fitness: 140932 
--------------------------------------------- 
