--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141923
New Best Solution Fitness: 141911
New Best Solution Fitness: 141889
Generation: 3
New Best Solution Fitness: 141471
New Best Solution Fitness: 141448
New Best Solution Fitness: 141418
New Best Solution Fitness: 141255
Generation: 4
New Best Solution Fitness: 141218
Generation: 5
New Best Solution Fitness: 141166
New Best Solution Fitness: 141161
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.2 
Mean sub-tour choices: 2.1 
Best Solution Fitness: 141161 
--------------------------------------------- 
