--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142995
New Best Solution Fitness: 142971
New Best Solution Fitness: 142967
New Best Solution Fitness: 142890
Generation: 3
New Best Solution Fitness: 142183
New Best Solution Fitness: 142060
Generation: 4
New Best Solution Fitness: 142004
New Best Solution Fitness: 141989
Generation: 5
New Best Solution Fitness: 141985
New Best Solution Fitness: 141983
Generation: 6
Generation: 7
New Best Solution Fitness: 141973
Generation: 8
New Best Solution Fitness: 141963
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.05556 
Mean sub-tour choices: 2.68889 
Best Solution Fitness: 141963 
--------------------------------------------- 
