--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141585
New Best Solution Fitness: 141524
New Best Solution Fitness: 141500
Generation: 3
New Best Solution Fitness: 141175
New Best Solution Fitness: 141172
New Best Solution Fitness: 141062
Generation: 4
New Best Solution Fitness: 140985
New Best Solution Fitness: 140983
Generation: 5
New Best Solution Fitness: 140922
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.03333 
Mean sub-tour choices: 2.96667 
Best Solution Fitness: 140922 
--------------------------------------------- 
