--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141104
New Best Solution Fitness: 141053
Generation: 3
New Best Solution Fitness: 140975
New Best Solution Fitness: 140962
New Best Solution Fitness: 140955
New Best Solution Fitness: 140944
Generation: 4
New Best Solution Fitness: 140807
New Best Solution Fitness: 140787
New Best Solution Fitness: 140757
Generation: 5
New Best Solution Fitness: 140732
New Best Solution Fitness: 140731
New Best Solution Fitness: 140712
Generation: 6
Generation: 7
New Best Solution Fitness: 140711
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 140682
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.07778 
Mean sub-tour choices: 2.85556 
Best Solution Fitness: 140682 
--------------------------------------------- 
