--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141819
New Best Solution Fitness: 141767
New Best Solution Fitness: 141744
Generation: 3
New Best Solution Fitness: 141497
Generation: 4
New Best Solution Fitness: 141443
New Best Solution Fitness: 141407
Generation: 5
New Best Solution Fitness: 141406
Generation: 6
Generation: 7
New Best Solution Fitness: 141397
Generation: 8
New Best Solution Fitness: 141396
New Best Solution Fitness: 141374
Generation: 9
New Best Solution Fitness: 141348
Generation: 10
New Best Solution Fitness: 141344
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.18889 
Mean sub-tour choices: 1.65556 
Best Solution Fitness: 141344 
--------------------------------------------- 
