--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141928
New Best Solution Fitness: 141822
Generation: 3
New Best Solution Fitness: 141365
New Best Solution Fitness: 141360
Generation: 4
New Best Solution Fitness: 141023
New Best Solution Fitness: 140907
New Best Solution Fitness: 140780
Generation: 5
New Best Solution Fitness: 140753
New Best Solution Fitness: 140747
New Best Solution Fitness: 140713
Generation: 6
New Best Solution Fitness: 140630
New Best Solution Fitness: 140625
Generation: 7
New Best Solution Fitness: 140585
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 140584
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.08889 
Mean sub-tour choices: 2.71111 
Best Solution Fitness: 140584 
--------------------------------------------- 
