--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142117
New Best Solution Fitness: 142041
Generation: 3
New Best Solution Fitness: 141875
New Best Solution Fitness: 141854
New Best Solution Fitness: 141836
New Best Solution Fitness: 141825
New Best Solution Fitness: 141783
Generation: 4
New Best Solution Fitness: 141739
New Best Solution Fitness: 141683
Generation: 5
New Best Solution Fitness: 141679
Generation: 6
New Best Solution Fitness: 141666
Generation: 7
New Best Solution Fitness: 141644
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.27778 
Mean sub-tour choices: 2.77778 
Best Solution Fitness: 141644 
--------------------------------------------- 
