--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35713
New Best Solution Fitness: 35704
New Best Solution Fitness: 35619
Generation: 3
New Best Solution Fitness: 35609
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 35587
New Best Solution Fitness: 35452
Generation: 7
New Best Solution Fitness: 35433
Generation: 8
Generation: 9
New Best Solution Fitness: 35407
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.43333 
Mean sub-tour choices: 2.13333 
Best Solution Fitness: 35407 
--------------------------------------------- 
