--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35524
New Best Solution Fitness: 35488
Generation: 3
New Best Solution Fitness: 35461
Generation: 4
New Best Solution Fitness: 35385
New Best Solution Fitness: 35372
Generation: 5
New Best Solution Fitness: 35353
Generation: 6
New Best Solution Fitness: 35299
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.35556 
Mean sub-tour choices: 2.01111 
Best Solution Fitness: 35299 
--------------------------------------------- 
