--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35722
New Best Solution Fitness: 35711
New Best Solution Fitness: 35708
New Best Solution Fitness: 35684
Generation: 3
New Best Solution Fitness: 35645
New Best Solution Fitness: 35451
Generation: 4
New Best Solution Fitness: 35440
Generation: 5
New Best Solution Fitness: 35436
Generation: 6
New Best Solution Fitness: 35412
Generation: 7
New Best Solution Fitness: 35402
New Best Solution Fitness: 35386
New Best Solution Fitness: 35348
Generation: 8
Generation: 9
New Best Solution Fitness: 35329
New Best Solution Fitness: 35309
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.05556 
Mean sub-tour choices: 1.7 
Best Solution Fitness: 35309 
--------------------------------------------- 
