--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35645
New Best Solution Fitness: 35635
New Best Solution Fitness: 35614
Generation: 3
Generation: 4
New Best Solution Fitness: 35560
New Best Solution Fitness: 35552
New Best Solution Fitness: 35519
Generation: 5
New Best Solution Fitness: 35412
New Best Solution Fitness: 35400
Generation: 6
New Best Solution Fitness: 35359
Generation: 7
New Best Solution Fitness: 35357
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.06667 
Mean sub-tour choices: 1.62222 
Best Solution Fitness: 35357 
--------------------------------------------- 
