--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35540
New Best Solution Fitness: 35522
New Best Solution Fitness: 35505
New Best Solution Fitness: 35501
New Best Solution Fitness: 35481
Generation: 3
Generation: 4
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 35477
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.5 
Mean sub-tour choices: 2.04444 
Best Solution Fitness: 35477 
--------------------------------------------- 
