--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35740
Generation: 3
New Best Solution Fitness: 35668
New Best Solution Fitness: 35653
New Best Solution Fitness: 35622
New Best Solution Fitness: 35603
Generation: 4
Generation: 5
New Best Solution Fitness: 35588
Generation: 6
New Best Solution Fitness: 35576
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 35566
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.822222 
Mean sub-tour choices: 1.37778 
Best Solution Fitness: 35566 
--------------------------------------------- 
