--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35790
New Best Solution Fitness: 35737
New Best Solution Fitness: 35654
Generation: 3
New Best Solution Fitness: 35443
New Best Solution Fitness: 35306
Generation: 4
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 35291
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.76667 
Mean sub-tour choices: 2.94444 
Best Solution Fitness: 35291 
--------------------------------------------- 
