--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35748
New Best Solution Fitness: 35739
Generation: 3
New Best Solution Fitness: 35586
Generation: 4
New Best Solution Fitness: 35564
New Best Solution Fitness: 35555
Generation: 5
New Best Solution Fitness: 35551
Generation: 6
New Best Solution Fitness: 35422
New Best Solution Fitness: 35414
New Best Solution Fitness: 35413
Generation: 7
New Best Solution Fitness: 35405
New Best Solution Fitness: 35397
Generation: 8
Generation: 9
New Best Solution Fitness: 35359
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.966667 
Mean sub-tour choices: 1.53333 
Best Solution Fitness: 35359 
--------------------------------------------- 
