--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35414
New Best Solution Fitness: 35404
Generation: 3
New Best Solution Fitness: 35358
Generation: 4
New Best Solution Fitness: 35333
Generation: 5
Generation: 6
New Best Solution Fitness: 35295
New Best Solution Fitness: 35292
New Best Solution Fitness: 35291
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.08889 
Mean sub-tour choices: 1.81111 
Best Solution Fitness: 35291 
--------------------------------------------- 
