--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35811
Generation: 3
New Best Solution Fitness: 35795
New Best Solution Fitness: 35776
Generation: 4
New Best Solution Fitness: 35692
Generation: 5
New Best Solution Fitness: 35663
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.977778 
Mean sub-tour choices: 1.74444 
Best Solution Fitness: 35663 
--------------------------------------------- 
