--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35770
New Best Solution Fitness: 35751
Generation: 3
Generation: 4
Generation: 5
New Best Solution Fitness: 35549
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 35515
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.25556 
Mean sub-tour choices: 1.76667 
Best Solution Fitness: 35515 
--------------------------------------------- 
