--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35850
New Best Solution Fitness: 35806
Generation: 3
Generation: 4
New Best Solution Fitness: 35775
New Best Solution Fitness: 35772
Generation: 5
New Best Solution Fitness: 35640
New Best Solution Fitness: 35634
Generation: 6
Generation: 7
New Best Solution Fitness: 35593
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.722222 
Mean sub-tour choices: 1.13333 
Best Solution Fitness: 35593 
--------------------------------------------- 
