--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35449
New Best Solution Fitness: 35430
New Best Solution Fitness: 35421
Generation: 3
New Best Solution Fitness: 35416
New Best Solution Fitness: 35412
Generation: 4
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 35400
Generation: 8
Generation: 9
New Best Solution Fitness: 35392
Generation: 10
New Best Solution Fitness: 35382
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.24444 
Mean sub-tour choices: 1.84444 
Best Solution Fitness: 35382 
--------------------------------------------- 
