--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35654
New Best Solution Fitness: 35570
Generation: 3
New Best Solution Fitness: 35534
Generation: 4
New Best Solution Fitness: 35531
Generation: 5
New Best Solution Fitness: 35530
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 35458
Generation: 10
New Best Solution Fitness: 35428
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.02222 
Mean sub-tour choices: 1.41111 
Best Solution Fitness: 35428 
--------------------------------------------- 
