--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35606
New Best Solution Fitness: 35603
New Best Solution Fitness: 35589
Generation: 3
New Best Solution Fitness: 35555
New Best Solution Fitness: 35552
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 35517
Generation: 7
New Best Solution Fitness: 35412
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.922222 
Mean sub-tour choices: 1.33333 
Best Solution Fitness: 35412 
--------------------------------------------- 
