--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35728
New Best Solution Fitness: 35726
New Best Solution Fitness: 35710
Generation: 3
Generation: 4
New Best Solution Fitness: 35654
Generation: 5
New Best Solution Fitness: 35628
New Best Solution Fitness: 35626
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 35607
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.611111 
Mean sub-tour choices: 1.24444 
Best Solution Fitness: 35607 
--------------------------------------------- 
