--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35709
Generation: 3
Generation: 4
New Best Solution Fitness: 35653
Generation: 5
Generation: 6
New Best Solution Fitness: 35625
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 35577
New Best Solution Fitness: 35564
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.03333 
Mean sub-tour choices: 1.64444 
Best Solution Fitness: 35564 
--------------------------------------------- 
