--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35491
New Best Solution Fitness: 35477
New Best Solution Fitness: 35448
New Best Solution Fitness: 35418
Generation: 3
New Best Solution Fitness: 35370
New Best Solution Fitness: 35334
Generation: 4
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 35329
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.12222 
Mean sub-tour choices: 1.71111 
Best Solution Fitness: 35329 
--------------------------------------------- 
