--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35560
New Best Solution Fitness: 35554
Generation: 3
New Best Solution Fitness: 35524
Generation: 4
New Best Solution Fitness: 35515
Generation: 5
New Best Solution Fitness: 35420
Generation: 6
New Best Solution Fitness: 35395
New Best Solution Fitness: 35356
Generation: 7
New Best Solution Fitness: 35354
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.26667 
Mean sub-tour choices: 1.91111 
Best Solution Fitness: 35354 
--------------------------------------------- 
