--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35417
New Best Solution Fitness: 35416
New Best Solution Fitness: 35375
Generation: 3
New Best Solution Fitness: 35328
Generation: 4
Generation: 5
New Best Solution Fitness: 35325
New Best Solution Fitness: 35324
Generation: 6
New Best Solution Fitness: 35316
New Best Solution Fitness: 35315
New Best Solution Fitness: 35312
Generation: 7
New Best Solution Fitness: 35220
New Best Solution Fitness: 35216
Generation: 8
New Best Solution Fitness: 35191
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.46667 
Mean sub-tour choices: 2.07778 
Best Solution Fitness: 35191 
--------------------------------------------- 
