--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35648
New Best Solution Fitness: 35608
Generation: 3
New Best Solution Fitness: 35577
New Best Solution Fitness: 35573
Generation: 4
New Best Solution Fitness: 35563
New Best Solution Fitness: 35561
New Best Solution Fitness: 35550
Generation: 5
New Best Solution Fitness: 35548
Generation: 6
Generation: 7
New Best Solution Fitness: 35545
Generation: 8
New Best Solution Fitness: 35510
Generation: 9
New Best Solution Fitness: 35419
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.877778 
Mean sub-tour choices: 1.44444 
Best Solution Fitness: 35419 
--------------------------------------------- 
