--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35620
New Best Solution Fitness: 35593
Generation: 3
New Best Solution Fitness: 35553
New Best Solution Fitness: 35517
Generation: 4
New Best Solution Fitness: 35498
New Best Solution Fitness: 35481
Generation: 5
New Best Solution Fitness: 35476
New Best Solution Fitness: 35461
Generation: 6
New Best Solution Fitness: 35460
Generation: 7
New Best Solution Fitness: 35399
Generation: 8
Generation: 9
New Best Solution Fitness: 35382
New Best Solution Fitness: 35365
New Best Solution Fitness: 35342
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.844444 
Mean sub-tour choices: 1.4 
Best Solution Fitness: 35342 
--------------------------------------------- 
