--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35513
New Best Solution Fitness: 35509
New Best Solution Fitness: 35501
Generation: 3
New Best Solution Fitness: 35439
New Best Solution Fitness: 35435
Generation: 4
Generation: 5
New Best Solution Fitness: 35347
Generation: 6
New Best Solution Fitness: 35336
New Best Solution Fitness: 35318
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 35296
New Best Solution Fitness: 35286
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.71111 
Mean sub-tour choices: 2.55556 
Best Solution Fitness: 35286 
--------------------------------------------- 
