--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35889
New Best Solution Fitness: 35873
Generation: 3
New Best Solution Fitness: 35848
Generation: 4
New Best Solution Fitness: 35715
Generation: 5
New Best Solution Fitness: 35603
New Best Solution Fitness: 35599
New Best Solution Fitness: 35594
Generation: 6
New Best Solution Fitness: 35583
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 35548
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.655556 
Mean sub-tour choices: 1.16667 
Best Solution Fitness: 35548 
--------------------------------------------- 
