--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35329
New Best Solution Fitness: 35323
Generation: 3
New Best Solution Fitness: 35275
New Best Solution Fitness: 35269
New Best Solution Fitness: 35265
Generation: 4
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.31111 
Mean sub-tour choices: 1.96667 
Best Solution Fitness: 35265 
--------------------------------------------- 
