--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35564
New Best Solution Fitness: 35559
New Best Solution Fitness: 35556
New Best Solution Fitness: 35537
Generation: 3
New Best Solution Fitness: 35465
Generation: 4
New Best Solution Fitness: 35445
Generation: 5
New Best Solution Fitness: 35400
New Best Solution Fitness: 35368
New Best Solution Fitness: 35366
Generation: 6
New Best Solution Fitness: 35301
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.755556 
Mean sub-tour choices: 1.55556 
Best Solution Fitness: 35301 
--------------------------------------------- 
