--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35855
New Best Solution Fitness: 35852
New Best Solution Fitness: 35814
Generation: 3
New Best Solution Fitness: 35774
New Best Solution Fitness: 35771
Generation: 4
New Best Solution Fitness: 35763
New Best Solution Fitness: 35760
Generation: 5
New Best Solution Fitness: 35727
New Best Solution Fitness: 35675
New Best Solution Fitness: 35674
New Best Solution Fitness: 35620
Generation: 6
New Best Solution Fitness: 35604
New Best Solution Fitness: 35601
New Best Solution Fitness: 35600
Generation: 7
New Best Solution Fitness: 35539
Generation: 8
New Best Solution Fitness: 35530
New Best Solution Fitness: 35521
Generation: 9
Generation: 10
New Best Solution Fitness: 35493
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.588889 
Mean sub-tour choices: 1.08889 
Best Solution Fitness: 35493 
--------------------------------------------- 
