--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35560
New Best Solution Fitness: 35517
Generation: 3
New Best Solution Fitness: 35513
Generation: 4
New Best Solution Fitness: 35483
New Best Solution Fitness: 35482
Generation: 5
New Best Solution Fitness: 35469
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 35466
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.25556 
Mean sub-tour choices: 2.03333 
Best Solution Fitness: 35466 
--------------------------------------------- 
