--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35743
New Best Solution Fitness: 35737
Generation: 3
New Best Solution Fitness: 35575
Generation: 4
New Best Solution Fitness: 35570
New Best Solution Fitness: 35569
Generation: 5
New Best Solution Fitness: 35513
Generation: 6
Generation: 7
New Best Solution Fitness: 35429
New Best Solution Fitness: 35409
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.622222 
Mean sub-tour choices: 1.06667 
Best Solution Fitness: 35409 
--------------------------------------------- 
