--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35618
New Best Solution Fitness: 35610
New Best Solution Fitness: 35501
Generation: 3
New Best Solution Fitness: 35482
Generation: 4
New Best Solution Fitness: 35480
New Best Solution Fitness: 35477
Generation: 5
New Best Solution Fitness: 35476
New Best Solution Fitness: 35454
Generation: 6
Generation: 7
New Best Solution Fitness: 35442
Generation: 8
New Best Solution Fitness: 35430
New Best Solution Fitness: 35419
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.32222 
Mean sub-tour choices: 2.14444 
Best Solution Fitness: 35419 
--------------------------------------------- 
