--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35526
New Best Solution Fitness: 35497
New Best Solution Fitness: 35464
Generation: 3
New Best Solution Fitness: 35131
Generation: 4
Generation: 5
New Best Solution Fitness: 35109
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 35108
Generation: 9
New Best Solution Fitness: 35099
New Best Solution Fitness: 35073
Generation: 10
New Best Solution Fitness: 35047
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.12222 
Mean sub-tour choices: 1.67778 
Best Solution Fitness: 35047 
--------------------------------------------- 
