--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35603
New Best Solution Fitness: 35596
New Best Solution Fitness: 35586
New Best Solution Fitness: 35583
New Best Solution Fitness: 35575
Generation: 3
New Best Solution Fitness: 35461
Generation: 4
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.06667 
Mean sub-tour choices: 2.87778 
Best Solution Fitness: 35461 
--------------------------------------------- 
