--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35928
New Best Solution Fitness: 35862
Generation: 3
Generation: 4
New Best Solution Fitness: 35856
New Best Solution Fitness: 35851
Generation: 5
New Best Solution Fitness: 35797
Generation: 6
New Best Solution Fitness: 35734
Generation: 7
Generation: 8
New Best Solution Fitness: 35648
New Best Solution Fitness: 35611
Generation: 9
Generation: 10
New Best Solution Fitness: 35546
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.13333 
Mean sub-tour choices: 1.95556 
Best Solution Fitness: 35546 
--------------------------------------------- 
