--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 36434
New Best Solution Fitness: 36325
New Best Solution Fitness: 36220
Generation: 3
New Best Solution Fitness: 35945
New Best Solution Fitness: 35934
Generation: 4
New Best Solution Fitness: 35879
Generation: 5
New Best Solution Fitness: 35817
Generation: 6
New Best Solution Fitness: 35734
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.37778 
Mean sub-tour choices: 2.18889 
Best Solution Fitness: 35734 
--------------------------------------------- 
