--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35843
New Best Solution Fitness: 35842
Generation: 3
Generation: 4
Generation: 5
New Best Solution Fitness: 35801
Generation: 6
New Best Solution Fitness: 35782
New Best Solution Fitness: 35777
Generation: 7
New Best Solution Fitness: 35714
New Best Solution Fitness: 35709
Generation: 8
New Best Solution Fitness: 35706
Generation: 9
New Best Solution Fitness: 35622
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.27778 
Mean sub-tour choices: 1.83333 
Best Solution Fitness: 35622 
--------------------------------------------- 
