--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35480
New Best Solution Fitness: 35461
New Best Solution Fitness: 35426
Generation: 3
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 35375
Generation: 7
Generation: 8
New Best Solution Fitness: 35355
New Best Solution Fitness: 35343
Generation: 9
Generation: 10
New Best Solution Fitness: 35305
New Best Solution Fitness: 35303
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.25556 
Mean sub-tour choices: 1.84444 
Best Solution Fitness: 35303 
--------------------------------------------- 
