--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35850
New Best Solution Fitness: 35842
Generation: 3
New Best Solution Fitness: 35809
New Best Solution Fitness: 35799
Generation: 4
New Best Solution Fitness: 35773
Generation: 5
New Best Solution Fitness: 35769
Generation: 6
Generation: 7
New Best Solution Fitness: 35757
New Best Solution Fitness: 35706
Generation: 8
New Best Solution Fitness: 35695
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.922222 
Mean sub-tour choices: 1.77778 
Best Solution Fitness: 35695 
--------------------------------------------- 
