--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35560
New Best Solution Fitness: 35540
Generation: 3
New Best Solution Fitness: 35534
Generation: 4
New Best Solution Fitness: 35505
New Best Solution Fitness: 35446
Generation: 5
New Best Solution Fitness: 35443
Generation: 6
Generation: 7
New Best Solution Fitness: 35420
New Best Solution Fitness: 35377
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.3 
Mean sub-tour choices: 2.05556 
Best Solution Fitness: 35377 
--------------------------------------------- 
