--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35676
New Best Solution Fitness: 35659
Generation: 3
New Best Solution Fitness: 35599
Generation: 4
New Best Solution Fitness: 35586
Generation: 5
Generation: 6
New Best Solution Fitness: 35441
New Best Solution Fitness: 35429
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.1 
Mean sub-tour choices: 1.91111 
Best Solution Fitness: 35429 
--------------------------------------------- 
