--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35716
Generation: 3
New Best Solution Fitness: 35609
New Best Solution Fitness: 35603
New Best Solution Fitness: 35597
Generation: 4
New Best Solution Fitness: 35591
Generation: 5
New Best Solution Fitness: 35568
Generation: 6
New Best Solution Fitness: 35549
Generation: 7
New Best Solution Fitness: 35541
Generation: 8
New Best Solution Fitness: 35538
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.911111 
Mean sub-tour choices: 1.28889 
Best Solution Fitness: 35538 
--------------------------------------------- 
