--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35896
New Best Solution Fitness: 35844
New Best Solution Fitness: 35810
Generation: 3
New Best Solution Fitness: 35803
New Best Solution Fitness: 35802
New Best Solution Fitness: 35787
Generation: 4
Generation: 5
New Best Solution Fitness: 35786
New Best Solution Fitness: 35782
Generation: 6
Generation: 7
New Best Solution Fitness: 35781
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.5 
Mean sub-tour choices: 2.14444 
Best Solution Fitness: 35781 
--------------------------------------------- 
