--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35436
New Best Solution Fitness: 35427
Generation: 3
New Best Solution Fitness: 35421
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 35414
Generation: 7
New Best Solution Fitness: 35409
Generation: 8
Generation: 9
New Best Solution Fitness: 35400
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.733333 
Mean sub-tour choices: 1.11111 
Best Solution Fitness: 35400 
--------------------------------------------- 
