--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35646
New Best Solution Fitness: 35618
Generation: 3
New Best Solution Fitness: 35533
Generation: 4
New Best Solution Fitness: 35496
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 35479
New Best Solution Fitness: 35469
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.833333 
Mean sub-tour choices: 1.28889 
Best Solution Fitness: 35469 
--------------------------------------------- 
