--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35542
New Best Solution Fitness: 35475
Generation: 3
New Best Solution Fitness: 35470
Generation: 4
New Best Solution Fitness: 35459
New Best Solution Fitness: 35454
Generation: 5
New Best Solution Fitness: 35422
New Best Solution Fitness: 35411
Generation: 6
New Best Solution Fitness: 35406
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 35333
Generation: 10
New Best Solution Fitness: 35314
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.17778 
Mean sub-tour choices: 1.63333 
Best Solution Fitness: 35314 
--------------------------------------------- 
