--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35396
New Best Solution Fitness: 35363
New Best Solution Fitness: 35362
Generation: 3
New Best Solution Fitness: 35351
New Best Solution Fitness: 35341
Generation: 4
Generation: 5
New Best Solution Fitness: 35295
New Best Solution Fitness: 35256
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 35237
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.21111 
Mean sub-tour choices: 1.96667 
Best Solution Fitness: 35237 
--------------------------------------------- 
