--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35705
Generation: 3
Generation: 4
New Best Solution Fitness: 35655
Generation: 5
New Best Solution Fitness: 35603
Generation: 6
Generation: 7
New Best Solution Fitness: 35540
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 35534
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.744444 
Mean sub-tour choices: 1.31111 
Best Solution Fitness: 35534 
--------------------------------------------- 
