--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35720
Generation: 3
New Best Solution Fitness: 35656
Generation: 4
New Best Solution Fitness: 35590
New Best Solution Fitness: 35589
Generation: 5
Generation: 6
New Best Solution Fitness: 35506
Generation: 7
New Best Solution Fitness: 35503
Generation: 8
Generation: 9
New Best Solution Fitness: 35502
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.21111 
Mean sub-tour choices: 1.86667 
Best Solution Fitness: 35502 
--------------------------------------------- 
