--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35710
New Best Solution Fitness: 35693
New Best Solution Fitness: 35692
New Best Solution Fitness: 35683
Generation: 3
New Best Solution Fitness: 35581
New Best Solution Fitness: 35575
New Best Solution Fitness: 35566
Generation: 4
New Best Solution Fitness: 35514
New Best Solution Fitness: 35508
Generation: 5
New Best Solution Fitness: 35483
New Best Solution Fitness: 35386
Generation: 6
Generation: 7
New Best Solution Fitness: 35363
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.41111 
Mean sub-tour choices: 2.21111 
Best Solution Fitness: 35363 
--------------------------------------------- 
