--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35723
New Best Solution Fitness: 35715
Generation: 3
New Best Solution Fitness: 35688
New Best Solution Fitness: 35683
Generation: 4
New Best Solution Fitness: 35679
Generation: 5
New Best Solution Fitness: 35613
New Best Solution Fitness: 35605
Generation: 6
New Best Solution Fitness: 35523
New Best Solution Fitness: 35520
Generation: 7
New Best Solution Fitness: 35508
Generation: 8
New Best Solution Fitness: 35414
New Best Solution Fitness: 35399
Generation: 9
New Best Solution Fitness: 35374
New Best Solution Fitness: 35371
Generation: 10
New Best Solution Fitness: 35355
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.8 
Mean sub-tour choices: 1.38889 
Best Solution Fitness: 35355 
--------------------------------------------- 
