--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35588
New Best Solution Fitness: 35569
Generation: 3
New Best Solution Fitness: 35505
Generation: 4
New Best Solution Fitness: 35463
New Best Solution Fitness: 35446
New Best Solution Fitness: 35382
Generation: 5
New Best Solution Fitness: 35378
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.45556 
Mean sub-tour choices: 2.18889 
Best Solution Fitness: 35378 
--------------------------------------------- 
