--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35662
New Best Solution Fitness: 35573
New Best Solution Fitness: 35571
Generation: 3
New Best Solution Fitness: 35386
New Best Solution Fitness: 35370
New Best Solution Fitness: 35336
New Best Solution Fitness: 35322
Generation: 4
New Best Solution Fitness: 35318
New Best Solution Fitness: 35308
New Best Solution Fitness: 35302
Generation: 5
New Best Solution Fitness: 35292
New Best Solution Fitness: 35283
Generation: 6
New Best Solution Fitness: 35273
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.11111 
Mean sub-tour choices: 2.87778 
Best Solution Fitness: 35273 
--------------------------------------------- 
