--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35626
New Best Solution Fitness: 35604
New Best Solution Fitness: 35595
New Best Solution Fitness: 35592
Generation: 3
New Best Solution Fitness: 35533
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 35500
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 35491
Generation: 10
New Best Solution Fitness: 35461
New Best Solution Fitness: 35459
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.16667 
Mean sub-tour choices: 1.92222 
Best Solution Fitness: 35459 
--------------------------------------------- 
