--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35524
New Best Solution Fitness: 35504
Generation: 3
New Best Solution Fitness: 35472
New Best Solution Fitness: 35445
Generation: 4
New Best Solution Fitness: 35430
Generation: 5
New Best Solution Fitness: 35405
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.36667 
Mean sub-tour choices: 1.94444 
Best Solution Fitness: 35405 
--------------------------------------------- 
