--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35926
New Best Solution Fitness: 35797
Generation: 3
New Best Solution Fitness: 35661
Generation: 4
New Best Solution Fitness: 35516
Generation: 5
New Best Solution Fitness: 35436
Generation: 6
Generation: 7
New Best Solution Fitness: 35375
Generation: 8
New Best Solution Fitness: 35333
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1 
Mean sub-tour choices: 1.64444 
Best Solution Fitness: 35333 
--------------------------------------------- 
