--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35502
Generation: 3
New Best Solution Fitness: 35454
New Best Solution Fitness: 35453
Generation: 4
Generation: 5
New Best Solution Fitness: 35416
Generation: 6
New Best Solution Fitness: 35404
Generation: 7
New Best Solution Fitness: 35400
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.288889 
Mean sub-tour choices: 0.544444 
Best Solution Fitness: 35400 
--------------------------------------------- 
