--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35919
Generation: 3
New Best Solution Fitness: 35863
Generation: 4
Generation: 5
New Best Solution Fitness: 35750
Generation: 6
New Best Solution Fitness: 35714
Generation: 7
New Best Solution Fitness: 35661
Generation: 8
New Best Solution Fitness: 35653
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.544444 
Mean sub-tour choices: 1 
Best Solution Fitness: 35653 
--------------------------------------------- 
