--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35697
Generation: 3
New Best Solution Fitness: 35629
New Best Solution Fitness: 35612
Generation: 4
New Best Solution Fitness: 35593
Generation: 5
Generation: 6
New Best Solution Fitness: 35550
Generation: 7
New Best Solution Fitness: 35542
Generation: 8
New Best Solution Fitness: 35495
Generation: 9
New Best Solution Fitness: 35488
New Best Solution Fitness: 35476
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.644444 
Mean sub-tour choices: 1.15556 
Best Solution Fitness: 35476 
--------------------------------------------- 
