--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35634
New Best Solution Fitness: 35627
New Best Solution Fitness: 35625
New Best Solution Fitness: 35593
Generation: 3
New Best Solution Fitness: 35578
New Best Solution Fitness: 35575
Generation: 4
New Best Solution Fitness: 35536
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.42222 
Mean sub-tour choices: 2.6 
Best Solution Fitness: 35536 
--------------------------------------------- 
