--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35519
New Best Solution Fitness: 35510
Generation: 3
New Best Solution Fitness: 35491
New Best Solution Fitness: 35453
Generation: 4
Generation: 5
New Best Solution Fitness: 35449
Generation: 6
New Best Solution Fitness: 35441
New Best Solution Fitness: 35408
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.07778 
Mean sub-tour choices: 1.7 
Best Solution Fitness: 35408 
--------------------------------------------- 
