--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35456
New Best Solution Fitness: 35434
Generation: 3
Generation: 4
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 35425
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.38889 
Mean sub-tour choices: 1.95556 
Best Solution Fitness: 35425 
--------------------------------------------- 
