--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35672
New Best Solution Fitness: 35656
New Best Solution Fitness: 35494
Generation: 3
New Best Solution Fitness: 35487
New Best Solution Fitness: 35478
New Best Solution Fitness: 35437
Generation: 4
New Best Solution Fitness: 35424
Generation: 5
New Best Solution Fitness: 35349
New Best Solution Fitness: 35340
Generation: 6
New Best Solution Fitness: 35339
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.26667 
Mean sub-tour choices: 2.45556 
Best Solution Fitness: 35339 
--------------------------------------------- 
