--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35538
Generation: 3
Generation: 4
Generation: 5
New Best Solution Fitness: 35515
Generation: 6
New Best Solution Fitness: 35460
Generation: 7
Generation: 8
New Best Solution Fitness: 35418
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.822222 
Mean sub-tour choices: 1.34444 
Best Solution Fitness: 35418 
--------------------------------------------- 
