--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35479
New Best Solution Fitness: 35478
New Best Solution Fitness: 35477
Generation: 3
New Best Solution Fitness: 35476
New Best Solution Fitness: 35475
Generation: 4
New Best Solution Fitness: 35465
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 35424
Generation: 9
New Best Solution Fitness: 35367
New Best Solution Fitness: 35366
Generation: 10
New Best Solution Fitness: 35355
New Best Solution Fitness: 35347
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.622222 
Mean sub-tour choices: 1.14444 
Best Solution Fitness: 35347 
--------------------------------------------- 
