--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35732
New Best Solution Fitness: 35731
New Best Solution Fitness: 35726
Generation: 3
New Best Solution Fitness: 35721
New Best Solution Fitness: 35720
New Best Solution Fitness: 35715
Generation: 4
New Best Solution Fitness: 35682
New Best Solution Fitness: 35681
Generation: 5
Generation: 6
New Best Solution Fitness: 35647
Generation: 7
New Best Solution Fitness: 35605
Generation: 8
Generation: 9
New Best Solution Fitness: 35577
Generation: 10
New Best Solution Fitness: 35519
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.877778 
Mean sub-tour choices: 1.45556 
Best Solution Fitness: 35519 
--------------------------------------------- 
