--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35894
New Best Solution Fitness: 35874
Generation: 3
New Best Solution Fitness: 35831
Generation: 4
New Best Solution Fitness: 35783
New Best Solution Fitness: 35751
New Best Solution Fitness: 35732
Generation: 5
New Best Solution Fitness: 35650
Generation: 6
New Best Solution Fitness: 35577
New Best Solution Fitness: 35558
New Best Solution Fitness: 35539
Generation: 7
New Best Solution Fitness: 35536
Generation: 8
New Best Solution Fitness: 35517
Generation: 9
New Best Solution Fitness: 35486
New Best Solution Fitness: 35483
Generation: 10
New Best Solution Fitness: 35196
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.766667 
Mean sub-tour choices: 1.21111 
Best Solution Fitness: 35196 
--------------------------------------------- 
