--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35725
New Best Solution Fitness: 35682
Generation: 3
New Best Solution Fitness: 35561
Generation: 4
New Best Solution Fitness: 35539
Generation: 5
New Best Solution Fitness: 35388
Generation: 6
New Best Solution Fitness: 35377
Generation: 7
New Best Solution Fitness: 35369
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 35284
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.733333 
Mean sub-tour choices: 1.04444 
Best Solution Fitness: 35284 
--------------------------------------------- 
