--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35756
New Best Solution Fitness: 35732
New Best Solution Fitness: 35712
New Best Solution Fitness: 35700
New Best Solution Fitness: 35696
Generation: 3
New Best Solution Fitness: 35544
Generation: 4
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 35507
New Best Solution Fitness: 35463
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.2 
Mean sub-tour choices: 1.75556 
Best Solution Fitness: 35463 
--------------------------------------------- 
