--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35633
Generation: 3
New Best Solution Fitness: 35579
Generation: 4
New Best Solution Fitness: 35577
New Best Solution Fitness: 35517
Generation: 5
Generation: 6
New Best Solution Fitness: 35505
Generation: 7
New Best Solution Fitness: 35493
New Best Solution Fitness: 35491
Generation: 8
New Best Solution Fitness: 35284
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.766667 
Mean sub-tour choices: 1.24444 
Best Solution Fitness: 35284 
--------------------------------------------- 
