--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35664
New Best Solution Fitness: 35660
New Best Solution Fitness: 35559
Generation: 3
New Best Solution Fitness: 35524
New Best Solution Fitness: 35521
New Best Solution Fitness: 35380
Generation: 4
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 35341
Generation: 9
New Best Solution Fitness: 35339
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.877778 
Mean sub-tour choices: 1.54444 
Best Solution Fitness: 35339 
--------------------------------------------- 
