--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35863
New Best Solution Fitness: 35832
Generation: 3
New Best Solution Fitness: 35632
Generation: 4
New Best Solution Fitness: 35523
New Best Solution Fitness: 35484
Generation: 5
New Best Solution Fitness: 35451
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.31111 
Mean sub-tour choices: 3.28889 
Best Solution Fitness: 35451 
--------------------------------------------- 
