--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35639
New Best Solution Fitness: 35598
Generation: 3
New Best Solution Fitness: 35597
Generation: 4
New Best Solution Fitness: 35583
New Best Solution Fitness: 35542
Generation: 5
New Best Solution Fitness: 35502
Generation: 6
New Best Solution Fitness: 35488
Generation: 7
New Best Solution Fitness: 35482
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.2 
Mean sub-tour choices: 1.91111 
Best Solution Fitness: 35482 
--------------------------------------------- 
