--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35608
Generation: 3
New Best Solution Fitness: 35580
Generation: 4
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 35537
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.18889 
Mean sub-tour choices: 1.98889 
Best Solution Fitness: 35537 
--------------------------------------------- 
