--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35594
Generation: 3
Generation: 4
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 35516
New Best Solution Fitness: 35512
Generation: 10
New Best Solution Fitness: 35413
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.844444 
Mean sub-tour choices: 1.33333 
Best Solution Fitness: 35413 
--------------------------------------------- 
