--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35486
New Best Solution Fitness: 35453
New Best Solution Fitness: 35448
New Best Solution Fitness: 35354
Generation: 3
New Best Solution Fitness: 35318
Generation: 4
Generation: 5
New Best Solution Fitness: 35152
Generation: 6
Generation: 7
New Best Solution Fitness: 35140
Generation: 8
New Best Solution Fitness: 35110
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1 
Mean sub-tour choices: 1.62222 
Best Solution Fitness: 35110 
--------------------------------------------- 
