--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35861
New Best Solution Fitness: 35844
Generation: 3
Generation: 4
New Best Solution Fitness: 35789
New Best Solution Fitness: 35772
New Best Solution Fitness: 35766
Generation: 5
New Best Solution Fitness: 35735
Generation: 6
New Best Solution Fitness: 35698
Generation: 7
New Best Solution Fitness: 35551
Generation: 8
Generation: 9
New Best Solution Fitness: 35526
New Best Solution Fitness: 35514
Generation: 10
New Best Solution Fitness: 35490
New Best Solution Fitness: 35483
New Best Solution Fitness: 35453
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.51111 
Mean sub-tour choices: 2.07778 
Best Solution Fitness: 35453 
--------------------------------------------- 
