--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35798
New Best Solution Fitness: 35708
New Best Solution Fitness: 35681
New Best Solution Fitness: 35672
Generation: 3
Generation: 4
Generation: 5
New Best Solution Fitness: 35589
Generation: 6
Generation: 7
New Best Solution Fitness: 35580
New Best Solution Fitness: 35571
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 35550
New Best Solution Fitness: 35518
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.888889 
Mean sub-tour choices: 1.28889 
Best Solution Fitness: 35518 
--------------------------------------------- 
