--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35651
Generation: 3
New Best Solution Fitness: 35589
New Best Solution Fitness: 35577
Generation: 4
New Best Solution Fitness: 35458
Generation: 5
Generation: 6
New Best Solution Fitness: 35396
New Best Solution Fitness: 35374
New Best Solution Fitness: 35351
Generation: 7
New Best Solution Fitness: 35302
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.433333 
Mean sub-tour choices: 0.711111 
Best Solution Fitness: 35302 
--------------------------------------------- 
