--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35580
New Best Solution Fitness: 35546
New Best Solution Fitness: 35544
Generation: 3
New Best Solution Fitness: 35467
New Best Solution Fitness: 35461
Generation: 4
New Best Solution Fitness: 35448
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.68889 
Mean sub-tour choices: 2.44444 
Best Solution Fitness: 35448 
--------------------------------------------- 
