--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35567
Generation: 3
New Best Solution Fitness: 35412
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 35365
Generation: 7
New Best Solution Fitness: 35333
Generation: 8
New Best Solution Fitness: 35319
New Best Solution Fitness: 35272
Generation: 9
New Best Solution Fitness: 35260
Generation: 10
New Best Solution Fitness: 35206
New Best Solution Fitness: 35205
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.911111 
Mean sub-tour choices: 1.27778 
Best Solution Fitness: 35205 
--------------------------------------------- 
