--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35609
New Best Solution Fitness: 35604
New Best Solution Fitness: 35592
Generation: 3
New Best Solution Fitness: 35526
New Best Solution Fitness: 35451
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 35444
Generation: 7
New Best Solution Fitness: 35430
Generation: 8
New Best Solution Fitness: 35415
Generation: 9
Generation: 10
New Best Solution Fitness: 35408
New Best Solution Fitness: 35388
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.27778 
Mean sub-tour choices: 2.05556 
Best Solution Fitness: 35388 
--------------------------------------------- 
