--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35432
New Best Solution Fitness: 35407
New Best Solution Fitness: 35389
Generation: 3
New Best Solution Fitness: 35359
Generation: 4
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 35328
New Best Solution Fitness: 35321
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.24444 
Mean sub-tour choices: 1.97778 
Best Solution Fitness: 35321 
--------------------------------------------- 
