--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35398
New Best Solution Fitness: 35360
Generation: 3
New Best Solution Fitness: 35339
Generation: 4
New Best Solution Fitness: 35278
Generation: 5
New Best Solution Fitness: 35274
Generation: 6
New Best Solution Fitness: 35245
Generation: 7
New Best Solution Fitness: 35241
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.755556 
Mean sub-tour choices: 1.27778 
Best Solution Fitness: 35241 
--------------------------------------------- 
