--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35670
New Best Solution Fitness: 35650
Generation: 3
New Best Solution Fitness: 35632
New Best Solution Fitness: 35625
Generation: 4
New Best Solution Fitness: 35594
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 35509
New Best Solution Fitness: 35490
Generation: 9
New Best Solution Fitness: 35473
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.433333 
Mean sub-tour choices: 0.777778 
Best Solution Fitness: 35473 
--------------------------------------------- 
