--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35686
New Best Solution Fitness: 35653
Generation: 3
New Best Solution Fitness: 35587
Generation: 4
New Best Solution Fitness: 35584
New Best Solution Fitness: 35548
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 35538
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.733333 
Mean sub-tour choices: 1.28889 
Best Solution Fitness: 35538 
--------------------------------------------- 
