--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35599
New Best Solution Fitness: 35598
Generation: 3
Generation: 4
New Best Solution Fitness: 35364
New Best Solution Fitness: 35361
New Best Solution Fitness: 35329
Generation: 5
New Best Solution Fitness: 35301
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.488889 
Mean sub-tour choices: 0.8 
Best Solution Fitness: 35301 
--------------------------------------------- 
