--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35554
New Best Solution Fitness: 35532
Generation: 3
New Best Solution Fitness: 35523
Generation: 4
New Best Solution Fitness: 35505
Generation: 5
New Best Solution Fitness: 35378
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 35360
New Best Solution Fitness: 35351
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.23333 
Mean sub-tour choices: 1.95556 
Best Solution Fitness: 35351 
--------------------------------------------- 
