--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35693
New Best Solution Fitness: 35680
Generation: 3
New Best Solution Fitness: 35663
Generation: 4
New Best Solution Fitness: 35528
New Best Solution Fitness: 35526
Generation: 5
New Best Solution Fitness: 35453
Generation: 6
New Best Solution Fitness: 35451
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 35422
New Best Solution Fitness: 35414
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.866667 
Mean sub-tour choices: 1.46667 
Best Solution Fitness: 35414 
--------------------------------------------- 
