--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35578
New Best Solution Fitness: 35570
Generation: 3
New Best Solution Fitness: 35565
Generation: 4
New Best Solution Fitness: 35552
New Best Solution Fitness: 35546
Generation: 5
Generation: 6
New Best Solution Fitness: 35398
Generation: 7
New Best Solution Fitness: 35375
Generation: 8
New Best Solution Fitness: 35337
New Best Solution Fitness: 35334
New Best Solution Fitness: 35325
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.722222 
Mean sub-tour choices: 1.13333 
Best Solution Fitness: 35325 
--------------------------------------------- 
