--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35663
New Best Solution Fitness: 35640
New Best Solution Fitness: 35602
Generation: 3
New Best Solution Fitness: 35599
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 35555
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 35494
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.2 
Mean sub-tour choices: 1.76667 
Best Solution Fitness: 35494 
--------------------------------------------- 
