--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d493.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 35723
New Best Solution Fitness: 35720
New Best Solution Fitness: 35682
Generation: 3
New Best Solution Fitness: 35587
Generation: 4
New Best Solution Fitness: 35584
New Best Solution Fitness: 35581
New Best Solution Fitness: 35539
Generation: 5
New Best Solution Fitness: 35536
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.14444 
Mean sub-tour choices: 1.71111 
Best Solution Fitness: 35536 
--------------------------------------------- 
