--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50117
New Best Solution Fitness: 50073
New Best Solution Fitness: 50062
Generation: 3
New Best Solution Fitness: 50005
Generation: 4
Generation: 5
New Best Solution Fitness: 49829
New Best Solution Fitness: 49819
New Best Solution Fitness: 49763
Generation: 6
New Best Solution Fitness: 49619
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 49606
New Best Solution Fitness: 49605
New Best Solution Fitness: 49567
Generation: 10
New Best Solution Fitness: 49545
New Best Solution Fitness: 49544
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.644444 
Mean sub-tour choices: 1.06667 
Best Solution Fitness: 49544 
--------------------------------------------- 
