--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49766
New Best Solution Fitness: 49725
New Best Solution Fitness: 49714
Generation: 3
New Best Solution Fitness: 49693
New Best Solution Fitness: 49678
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 49650
Generation: 7
Generation: 8
New Best Solution Fitness: 49554
New Best Solution Fitness: 49541
New Best Solution Fitness: 49520
Generation: 9
Generation: 10
New Best Solution Fitness: 49474
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.811111 
Mean sub-tour choices: 1.25556 
Best Solution Fitness: 49474 
--------------------------------------------- 
