--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49604
New Best Solution Fitness: 49585
New Best Solution Fitness: 49546
Generation: 3
New Best Solution Fitness: 49517
New Best Solution Fitness: 49506
New Best Solution Fitness: 49498
Generation: 4
Generation: 5
New Best Solution Fitness: 49474
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 49434
New Best Solution Fitness: 49423
Generation: 9
Generation: 10
New Best Solution Fitness: 49329
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.733333 
Mean sub-tour choices: 1.15556 
Best Solution Fitness: 49329 
--------------------------------------------- 
