--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50219
Generation: 3
New Best Solution Fitness: 50079
New Best Solution Fitness: 50068
Generation: 4
New Best Solution Fitness: 49719
New Best Solution Fitness: 49658
Generation: 5
New Best Solution Fitness: 49652
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 49629
New Best Solution Fitness: 49599
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.555556 
Mean sub-tour choices: 0.966667 
Best Solution Fitness: 49599 
--------------------------------------------- 
