--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49829
New Best Solution Fitness: 49818
Generation: 3
New Best Solution Fitness: 49790
Generation: 4
New Best Solution Fitness: 49576
New Best Solution Fitness: 49491
Generation: 5
Generation: 6
New Best Solution Fitness: 49482
Generation: 7
Generation: 8
New Best Solution Fitness: 49479
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.833333 
Mean sub-tour choices: 1.35556 
Best Solution Fitness: 49479 
--------------------------------------------- 
