--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49736
New Best Solution Fitness: 49671
New Best Solution Fitness: 49659
Generation: 3
New Best Solution Fitness: 49644
New Best Solution Fitness: 49544
Generation: 4
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 49529
Generation: 8
New Best Solution Fitness: 49523
Generation: 9
Generation: 10
New Best Solution Fitness: 49412
New Best Solution Fitness: 49410
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.11111 
Mean sub-tour choices: 1.68889 
Best Solution Fitness: 49410 
--------------------------------------------- 
