--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49865
New Best Solution Fitness: 49843
Generation: 3
New Best Solution Fitness: 49566
New Best Solution Fitness: 49551
Generation: 4
New Best Solution Fitness: 49480
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 49446
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.566667 
Mean sub-tour choices: 0.966667 
Best Solution Fitness: 49446 
--------------------------------------------- 
