--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49903
New Best Solution Fitness: 49796
Generation: 3
New Best Solution Fitness: 49788
Generation: 4
New Best Solution Fitness: 49771
Generation: 5
New Best Solution Fitness: 49760
New Best Solution Fitness: 49743
Generation: 6
Generation: 7
New Best Solution Fitness: 49606
New Best Solution Fitness: 49602
New Best Solution Fitness: 49594
Generation: 8
New Best Solution Fitness: 49511
Generation: 9
New Best Solution Fitness: 49507
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.788889 
Mean sub-tour choices: 1.26667 
Best Solution Fitness: 49507 
--------------------------------------------- 
