--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49660
New Best Solution Fitness: 49637
Generation: 3
New Best Solution Fitness: 49606
Generation: 4
New Best Solution Fitness: 49532
New Best Solution Fitness: 49496
Generation: 5
New Best Solution Fitness: 49486
New Best Solution Fitness: 49477
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.15556 
Mean sub-tour choices: 1.7 
Best Solution Fitness: 49477 
--------------------------------------------- 
