--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49716
New Best Solution Fitness: 49701
New Best Solution Fitness: 49667
New Best Solution Fitness: 49638
Generation: 3
New Best Solution Fitness: 49599
New Best Solution Fitness: 49560
Generation: 4
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 49463
Generation: 8
New Best Solution Fitness: 49444
New Best Solution Fitness: 49410
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.633333 
Mean sub-tour choices: 0.966667 
Best Solution Fitness: 49410 
--------------------------------------------- 
