--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49963
New Best Solution Fitness: 49916
Generation: 3
New Best Solution Fitness: 49642
New Best Solution Fitness: 49621
Generation: 4
New Best Solution Fitness: 49573
New Best Solution Fitness: 49546
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 49496
New Best Solution Fitness: 49467
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 49381
New Best Solution Fitness: 49352
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.777778 
Mean sub-tour choices: 1.27778 
Best Solution Fitness: 49352 
--------------------------------------------- 
