--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49890
New Best Solution Fitness: 49849
Generation: 3
New Best Solution Fitness: 49722
New Best Solution Fitness: 49704
Generation: 4
New Best Solution Fitness: 49668
Generation: 5
New Best Solution Fitness: 49663
New Best Solution Fitness: 49651
Generation: 6
New Best Solution Fitness: 49603
New Best Solution Fitness: 49591
Generation: 7
New Best Solution Fitness: 49532
Generation: 8
Generation: 9
New Best Solution Fitness: 49446
New Best Solution Fitness: 49381
Generation: 10
New Best Solution Fitness: 49373
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.01111 
Mean sub-tour choices: 1.64444 
Best Solution Fitness: 49373 
--------------------------------------------- 
