--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50115
New Best Solution Fitness: 50013
Generation: 3
New Best Solution Fitness: 49659
Generation: 4
New Best Solution Fitness: 49648
Generation: 5
New Best Solution Fitness: 49613
New Best Solution Fitness: 49607
New Best Solution Fitness: 49600
Generation: 6
New Best Solution Fitness: 49553
New Best Solution Fitness: 49547
Generation: 7
New Best Solution Fitness: 49480
New Best Solution Fitness: 49474
Generation: 8
New Best Solution Fitness: 49458
New Best Solution Fitness: 49425
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.422222 
Mean sub-tour choices: 0.733333 
Best Solution Fitness: 49425 
--------------------------------------------- 
