--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49920
New Best Solution Fitness: 49815
New Best Solution Fitness: 49738
Generation: 3
New Best Solution Fitness: 49725
Generation: 4
New Best Solution Fitness: 49679
New Best Solution Fitness: 49674
New Best Solution Fitness: 49658
Generation: 5
New Best Solution Fitness: 49539
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 49532
New Best Solution Fitness: 49521
New Best Solution Fitness: 49498
Generation: 9
New Best Solution Fitness: 49493
New Best Solution Fitness: 49441
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.788889 
Mean sub-tour choices: 1.3 
Best Solution Fitness: 49441 
--------------------------------------------- 
