--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49689
New Best Solution Fitness: 49686
Generation: 3
New Best Solution Fitness: 49525
New Best Solution Fitness: 49479
Generation: 4
Generation: 5
New Best Solution Fitness: 49471
Generation: 6
New Best Solution Fitness: 49450
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 49342
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.522222 
Mean sub-tour choices: 0.9 
Best Solution Fitness: 49342 
--------------------------------------------- 
