--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49762
New Best Solution Fitness: 49568
Generation: 3
New Best Solution Fitness: 49545
New Best Solution Fitness: 49453
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 49410
Generation: 7
New Best Solution Fitness: 49389
New Best Solution Fitness: 49386
Generation: 8
New Best Solution Fitness: 49365
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.8 
Mean sub-tour choices: 1.3 
Best Solution Fitness: 49365 
--------------------------------------------- 
