--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49743
New Best Solution Fitness: 49735
Generation: 3
New Best Solution Fitness: 49679
New Best Solution Fitness: 49520
Generation: 4
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 49484
New Best Solution Fitness: 49479
Generation: 9
New Best Solution Fitness: 49459
New Best Solution Fitness: 49434
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.5 
Mean sub-tour choices: 0.844444 
Best Solution Fitness: 49434 
--------------------------------------------- 
