--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49840
New Best Solution Fitness: 49816
New Best Solution Fitness: 49791
Generation: 3
New Best Solution Fitness: 49680
New Best Solution Fitness: 49659
New Best Solution Fitness: 49654
Generation: 4
New Best Solution Fitness: 49583
New Best Solution Fitness: 49557
Generation: 5
New Best Solution Fitness: 49536
Generation: 6
New Best Solution Fitness: 49531
Generation: 7
New Best Solution Fitness: 49527
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.622222 
Mean sub-tour choices: 1.1 
Best Solution Fitness: 49527 
--------------------------------------------- 
