--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50300
New Best Solution Fitness: 50239
New Best Solution Fitness: 50226
New Best Solution Fitness: 50040
Generation: 3
New Best Solution Fitness: 49872
New Best Solution Fitness: 49854
Generation: 4
New Best Solution Fitness: 49734
New Best Solution Fitness: 49716
New Best Solution Fitness: 49676
New Best Solution Fitness: 49658
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 49652
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.777778 
Mean sub-tour choices: 1.27778 
Best Solution Fitness: 49652 
--------------------------------------------- 
