--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49961
New Best Solution Fitness: 49960
Generation: 3
Generation: 4
New Best Solution Fitness: 49791
Generation: 5
New Best Solution Fitness: 49677
Generation: 6
New Best Solution Fitness: 49587
New Best Solution Fitness: 49575
Generation: 7
New Best Solution Fitness: 49564
Generation: 8
Generation: 9
New Best Solution Fitness: 49548
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.4 
Mean sub-tour choices: 0.688889 
Best Solution Fitness: 49548 
--------------------------------------------- 
