--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50358
New Best Solution Fitness: 50353
New Best Solution Fitness: 50146
Generation: 3
New Best Solution Fitness: 49992
New Best Solution Fitness: 49975
New Best Solution Fitness: 49961
Generation: 4
New Best Solution Fitness: 49920
New Best Solution Fitness: 49903
Generation: 5
New Best Solution Fitness: 49879
New Best Solution Fitness: 49856
Generation: 6
New Best Solution Fitness: 49822
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 49727
Generation: 10
New Best Solution Fitness: 49645
New Best Solution Fitness: 49640
New Best Solution Fitness: 49621
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.933333 
Mean sub-tour choices: 1.48889 
Best Solution Fitness: 49621 
--------------------------------------------- 
