--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49940
New Best Solution Fitness: 49934
New Best Solution Fitness: 49857
Generation: 3
New Best Solution Fitness: 49783
Generation: 4
New Best Solution Fitness: 49733
Generation: 5
Generation: 6
New Best Solution Fitness: 49728
Generation: 7
Generation: 8
New Best Solution Fitness: 49666
Generation: 9
New Best Solution Fitness: 49665
Generation: 10
New Best Solution Fitness: 49639
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.555556 
Mean sub-tour choices: 0.977778 
Best Solution Fitness: 49639 
--------------------------------------------- 
