--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49892
New Best Solution Fitness: 49868
New Best Solution Fitness: 49800
Generation: 3
New Best Solution Fitness: 49759
New Best Solution Fitness: 49735
Generation: 4
New Best Solution Fitness: 49733
Generation: 5
New Best Solution Fitness: 49686
New Best Solution Fitness: 49659
New Best Solution Fitness: 49611
Generation: 6
New Best Solution Fitness: 49608
Generation: 7
New Best Solution Fitness: 49574
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.911111 
Mean sub-tour choices: 1.44444 
Best Solution Fitness: 49574 
--------------------------------------------- 
