--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49878
New Best Solution Fitness: 49799
New Best Solution Fitness: 49662
Generation: 3
New Best Solution Fitness: 49651
Generation: 4
New Best Solution Fitness: 49623
Generation: 5
New Best Solution Fitness: 49526
New Best Solution Fitness: 49520
New Best Solution Fitness: 49513
Generation: 6
New Best Solution Fitness: 49472
Generation: 7
New Best Solution Fitness: 49422
Generation: 8
New Best Solution Fitness: 49403
New Best Solution Fitness: 49402
Generation: 9
New Best Solution Fitness: 49393
New Best Solution Fitness: 49385
Generation: 10
New Best Solution Fitness: 49379
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.544444 
Mean sub-tour choices: 0.922222 
Best Solution Fitness: 49379 
--------------------------------------------- 
