--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50148
New Best Solution Fitness: 50114
New Best Solution Fitness: 50108
Generation: 3
Generation: 4
New Best Solution Fitness: 49905
New Best Solution Fitness: 49904
New Best Solution Fitness: 49889
Generation: 5
New Best Solution Fitness: 49884
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 49818
New Best Solution Fitness: 49749
Generation: 10
New Best Solution Fitness: 49668
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.5 
Mean sub-tour choices: 0.844444 
Best Solution Fitness: 49668 
--------------------------------------------- 
