--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49931
New Best Solution Fitness: 49920
Generation: 3
New Best Solution Fitness: 49767
New Best Solution Fitness: 49765
New Best Solution Fitness: 49733
Generation: 4
New Best Solution Fitness: 49731
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 49704
New Best Solution Fitness: 49691
New Best Solution Fitness: 49684
Generation: 8
New Best Solution Fitness: 49671
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.666667 
Mean sub-tour choices: 1.06667 
Best Solution Fitness: 49671 
--------------------------------------------- 
