--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49736
New Best Solution Fitness: 49621
Generation: 3
New Best Solution Fitness: 49554
New Best Solution Fitness: 49512
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 49508
Generation: 7
Generation: 8
New Best Solution Fitness: 49484
Generation: 9
Generation: 10
New Best Solution Fitness: 49473
New Best Solution Fitness: 49347
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.24444 
Mean sub-tour choices: 1.95556 
Best Solution Fitness: 49347 
--------------------------------------------- 
