--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49649
New Best Solution Fitness: 49513
Generation: 3
New Best Solution Fitness: 49506
New Best Solution Fitness: 49496
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 49465
New Best Solution Fitness: 49419
Generation: 7
New Best Solution Fitness: 49346
New Best Solution Fitness: 49293
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.444444 
Mean sub-tour choices: 0.777778 
Best Solution Fitness: 49293 
--------------------------------------------- 
