--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49871
New Best Solution Fitness: 49863
New Best Solution Fitness: 49764
New Best Solution Fitness: 49671
Generation: 3
New Best Solution Fitness: 49567
New Best Solution Fitness: 49461
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 49430
Generation: 7
Generation: 8
New Best Solution Fitness: 49410
Generation: 9
Generation: 10
New Best Solution Fitness: 49354
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.577778 
Mean sub-tour choices: 0.966667 
Best Solution Fitness: 49354 
--------------------------------------------- 
