--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49719
New Best Solution Fitness: 49669
New Best Solution Fitness: 49656
Generation: 3
New Best Solution Fitness: 49635
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 49611
New Best Solution Fitness: 49579
Generation: 7
New Best Solution Fitness: 49537
New Best Solution Fitness: 49520
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 49439
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.4 
Mean sub-tour choices: 0.688889 
Best Solution Fitness: 49439 
--------------------------------------------- 
