--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49620
New Best Solution Fitness: 49554
Generation: 3
New Best Solution Fitness: 49254
New Best Solution Fitness: 49241
Generation: 4
Generation: 5
New Best Solution Fitness: 49198
Generation: 6
New Best Solution Fitness: 49159
Generation: 7
New Best Solution Fitness: 49135
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.755556 
Mean sub-tour choices: 1.22222 
Best Solution Fitness: 49135 
--------------------------------------------- 
