--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49443
New Best Solution Fitness: 49436
New Best Solution Fitness: 49392
New Best Solution Fitness: 49386
Generation: 3
New Best Solution Fitness: 49379
New Best Solution Fitness: 49375
Generation: 4
New Best Solution Fitness: 49366
Generation: 5
New Best Solution Fitness: 49253
New Best Solution Fitness: 49231
Generation: 6
Generation: 7
New Best Solution Fitness: 49225
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.666667 
Mean sub-tour choices: 1.11111 
Best Solution Fitness: 49225 
--------------------------------------------- 
