--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49963
New Best Solution Fitness: 49962
New Best Solution Fitness: 49913
Generation: 3
New Best Solution Fitness: 49912
Generation: 4
New Best Solution Fitness: 49882
New Best Solution Fitness: 49881
New Best Solution Fitness: 49861
Generation: 5
New Best Solution Fitness: 49796
Generation: 6
New Best Solution Fitness: 49780
New Best Solution Fitness: 49769
Generation: 7
New Best Solution Fitness: 49683
Generation: 8
New Best Solution Fitness: 49667
Generation: 9
New Best Solution Fitness: 49601
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.25556 
Mean sub-tour choices: 1.85556 
Best Solution Fitness: 49601 
--------------------------------------------- 
