--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49682
New Best Solution Fitness: 49641
Generation: 3
New Best Solution Fitness: 49635
Generation: 4
New Best Solution Fitness: 49615
New Best Solution Fitness: 49597
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 49509
New Best Solution Fitness: 49488
New Best Solution Fitness: 49487
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.566667 
Mean sub-tour choices: 0.933333 
Best Solution Fitness: 49487 
--------------------------------------------- 
