--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49898
New Best Solution Fitness: 49670
New Best Solution Fitness: 49653
Generation: 3
New Best Solution Fitness: 49618
Generation: 4
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 49571
Generation: 9
New Best Solution Fitness: 49565
Generation: 10
New Best Solution Fitness: 49560
New Best Solution Fitness: 49502
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.844444 
Mean sub-tour choices: 1.38889 
Best Solution Fitness: 49502 
--------------------------------------------- 
