--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50050
New Best Solution Fitness: 50005
New Best Solution Fitness: 49936
Generation: 3
New Best Solution Fitness: 49756
New Best Solution Fitness: 49748
Generation: 4
New Best Solution Fitness: 49725
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.388889 
Mean sub-tour choices: 0.7 
Best Solution Fitness: 49725 
--------------------------------------------- 
