--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50026
New Best Solution Fitness: 49998
New Best Solution Fitness: 49996
New Best Solution Fitness: 49952
Generation: 3
New Best Solution Fitness: 49948
New Best Solution Fitness: 49920
Generation: 4
New Best Solution Fitness: 49918
Generation: 5
New Best Solution Fitness: 49794
New Best Solution Fitness: 49781
New Best Solution Fitness: 49712
Generation: 6
New Best Solution Fitness: 49707
Generation: 7
New Best Solution Fitness: 49428
New Best Solution Fitness: 49423
Generation: 8
New Best Solution Fitness: 49417
Generation: 9
Generation: 10
New Best Solution Fitness: 49406
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.01111 
Mean sub-tour choices: 1.6 
Best Solution Fitness: 49406 
--------------------------------------------- 
