--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50330
New Best Solution Fitness: 50158
Generation: 3
New Best Solution Fitness: 50134
New Best Solution Fitness: 49983
Generation: 4
New Best Solution Fitness: 49909
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 49891
Generation: 8
Generation: 9
New Best Solution Fitness: 49709
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.8 
Mean sub-tour choices: 1.17778 
Best Solution Fitness: 49709 
--------------------------------------------- 
