--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50073
New Best Solution Fitness: 50039
Generation: 3
New Best Solution Fitness: 49884
New Best Solution Fitness: 49732
Generation: 4
New Best Solution Fitness: 49731
Generation: 5
New Best Solution Fitness: 49673
New Best Solution Fitness: 49669
Generation: 6
New Best Solution Fitness: 49603
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 49494
New Best Solution Fitness: 49458
Generation: 10
New Best Solution Fitness: 49435
New Best Solution Fitness: 49356
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.444444 
Mean sub-tour choices: 0.777778 
Best Solution Fitness: 49356 
--------------------------------------------- 
