--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50296
New Best Solution Fitness: 50278
New Best Solution Fitness: 50276
New Best Solution Fitness: 50253
Generation: 3
New Best Solution Fitness: 49831
Generation: 4
New Best Solution Fitness: 49802
Generation: 5
New Best Solution Fitness: 49719
New Best Solution Fitness: 49712
New Best Solution Fitness: 49683
Generation: 6
New Best Solution Fitness: 49485
New Best Solution Fitness: 49456
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.588889 
Mean sub-tour choices: 1.02222 
Best Solution Fitness: 49456 
--------------------------------------------- 
