--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49957
New Best Solution Fitness: 49852
New Best Solution Fitness: 49843
Generation: 3
New Best Solution Fitness: 49689
New Best Solution Fitness: 49674
Generation: 4
New Best Solution Fitness: 49522
Generation: 5
Generation: 6
New Best Solution Fitness: 49458
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 49435
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.5 
Mean sub-tour choices: 0.822222 
Best Solution Fitness: 49435 
--------------------------------------------- 
