--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49832
New Best Solution Fitness: 49797
New Best Solution Fitness: 49796
Generation: 3
New Best Solution Fitness: 49753
New Best Solution Fitness: 49747
Generation: 4
New Best Solution Fitness: 49726
New Best Solution Fitness: 49724
New Best Solution Fitness: 49705
Generation: 5
New Best Solution Fitness: 49674
New Best Solution Fitness: 49669
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 49620
New Best Solution Fitness: 49617
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.7 
Mean sub-tour choices: 1.21111 
Best Solution Fitness: 49617 
--------------------------------------------- 
