--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49719
New Best Solution Fitness: 49574
Generation: 3
New Best Solution Fitness: 49363
New Best Solution Fitness: 49347
Generation: 4
New Best Solution Fitness: 49324
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 49313
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.6 
Mean sub-tour choices: 1 
Best Solution Fitness: 49313 
--------------------------------------------- 
