--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50047
New Best Solution Fitness: 50036
New Best Solution Fitness: 49946
Generation: 3
New Best Solution Fitness: 49534
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 49513
New Best Solution Fitness: 49407
Generation: 7
New Best Solution Fitness: 49331
New Best Solution Fitness: 49330
New Best Solution Fitness: 49310
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.977778 
Mean sub-tour choices: 1.55556 
Best Solution Fitness: 49310 
--------------------------------------------- 
