--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50504
New Best Solution Fitness: 50494
Generation: 3
New Best Solution Fitness: 49867
New Best Solution Fitness: 49866
Generation: 4
New Best Solution Fitness: 49721
New Best Solution Fitness: 49694
Generation: 5
New Best Solution Fitness: 49618
New Best Solution Fitness: 49525
Generation: 6
Generation: 7
New Best Solution Fitness: 49501
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.08889 
Mean sub-tour choices: 1.6 
Best Solution Fitness: 49501 
--------------------------------------------- 
