--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50174
New Best Solution Fitness: 50070
New Best Solution Fitness: 50046
Generation: 3
New Best Solution Fitness: 49977
New Best Solution Fitness: 49976
New Best Solution Fitness: 49974
Generation: 4
New Best Solution Fitness: 49945
Generation: 5
New Best Solution Fitness: 49917
Generation: 6
Generation: 7
New Best Solution Fitness: 49565
Generation: 8
New Best Solution Fitness: 49499
New Best Solution Fitness: 49475
Generation: 9
New Best Solution Fitness: 49443
Generation: 10
New Best Solution Fitness: 49432
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.811111 
Mean sub-tour choices: 1.32222 
Best Solution Fitness: 49432 
--------------------------------------------- 
