--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49755
New Best Solution Fitness: 49594
New Best Solution Fitness: 49558
Generation: 3
New Best Solution Fitness: 49465
Generation: 4
New Best Solution Fitness: 49331
New Best Solution Fitness: 49320
Generation: 5
New Best Solution Fitness: 49240
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.422222 
Mean sub-tour choices: 0.722222 
Best Solution Fitness: 49240 
--------------------------------------------- 
