--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49770
New Best Solution Fitness: 49581
Generation: 3
New Best Solution Fitness: 49563
Generation: 4
New Best Solution Fitness: 49553
New Best Solution Fitness: 49548
Generation: 5
New Best Solution Fitness: 49516
Generation: 6
Generation: 7
New Best Solution Fitness: 49494
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.722222 
Mean sub-tour choices: 1.08889 
Best Solution Fitness: 49494 
--------------------------------------------- 
