--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49757
New Best Solution Fitness: 49636
New Best Solution Fitness: 49628
Generation: 3
New Best Solution Fitness: 49492
New Best Solution Fitness: 49482
New Best Solution Fitness: 49455
Generation: 4
New Best Solution Fitness: 49453
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 49449
New Best Solution Fitness: 49438
New Best Solution Fitness: 49386
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 49380
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.733333 
Mean sub-tour choices: 1.26667 
Best Solution Fitness: 49380 
--------------------------------------------- 
