--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50188
New Best Solution Fitness: 50152
New Best Solution Fitness: 50098
Generation: 3
New Best Solution Fitness: 49957
Generation: 4
New Best Solution Fitness: 49942
Generation: 5
New Best Solution Fitness: 49920
New Best Solution Fitness: 49919
Generation: 6
Generation: 7
New Best Solution Fitness: 49815
Generation: 8
New Best Solution Fitness: 49807
Generation: 9
Generation: 10
New Best Solution Fitness: 49757
New Best Solution Fitness: 49739
New Best Solution Fitness: 49711
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.28889 
Mean sub-tour choices: 1.93333 
Best Solution Fitness: 49711 
--------------------------------------------- 
