--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49769
New Best Solution Fitness: 49741
Generation: 3
New Best Solution Fitness: 49679
Generation: 4
New Best Solution Fitness: 49671
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 49659
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.288889 
Mean sub-tour choices: 0.533333 
Best Solution Fitness: 49659 
--------------------------------------------- 
