--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49912
New Best Solution Fitness: 49853
New Best Solution Fitness: 49814
New Best Solution Fitness: 49747
Generation: 3
New Best Solution Fitness: 49680
New Best Solution Fitness: 49647
Generation: 4
New Best Solution Fitness: 49638
Generation: 5
New Best Solution Fitness: 49627
Generation: 6
New Best Solution Fitness: 49580
New Best Solution Fitness: 49571
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.955556 
Mean sub-tour choices: 1.45556 
Best Solution Fitness: 49571 
--------------------------------------------- 
