--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49778
New Best Solution Fitness: 49770
New Best Solution Fitness: 49764
New Best Solution Fitness: 49710
Generation: 3
New Best Solution Fitness: 49591
New Best Solution Fitness: 49546
New Best Solution Fitness: 49515
Generation: 4
New Best Solution Fitness: 49471
New Best Solution Fitness: 49448
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 49447
Generation: 8
Generation: 9
New Best Solution Fitness: 49423
New Best Solution Fitness: 49388
Generation: 10
New Best Solution Fitness: 49378
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.811111 
Mean sub-tour choices: 1.34444 
Best Solution Fitness: 49378 
--------------------------------------------- 
