--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49797
New Best Solution Fitness: 49761
New Best Solution Fitness: 49751
Generation: 3
New Best Solution Fitness: 49659
New Best Solution Fitness: 49637
Generation: 4
New Best Solution Fitness: 49616
New Best Solution Fitness: 49569
Generation: 5
Generation: 6
New Best Solution Fitness: 49568
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 49547
Generation: 10
New Best Solution Fitness: 49520
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.611111 
Mean sub-tour choices: 1.03333 
Best Solution Fitness: 49520 
--------------------------------------------- 
