--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49854
New Best Solution Fitness: 49836
New Best Solution Fitness: 49828
Generation: 3
New Best Solution Fitness: 49717
Generation: 4
New Best Solution Fitness: 49684
New Best Solution Fitness: 49681
New Best Solution Fitness: 49666
Generation: 5
New Best Solution Fitness: 49481
New Best Solution Fitness: 49477
New Best Solution Fitness: 49426
Generation: 6
New Best Solution Fitness: 49349
Generation: 7
New Best Solution Fitness: 49341
Generation: 8
New Best Solution Fitness: 49314
New Best Solution Fitness: 49245
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.611111 
Mean sub-tour choices: 1.04444 
Best Solution Fitness: 49245 
--------------------------------------------- 
