--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50571
New Best Solution Fitness: 50548
New Best Solution Fitness: 50402
Generation: 3
New Best Solution Fitness: 49823
New Best Solution Fitness: 49822
New Best Solution Fitness: 49627
Generation: 4
New Best Solution Fitness: 49626
New Best Solution Fitness: 49605
Generation: 5
New Best Solution Fitness: 49604
New Best Solution Fitness: 49513
Generation: 6
New Best Solution Fitness: 49512
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.711111 
Mean sub-tour choices: 1.14444 
Best Solution Fitness: 49512 
--------------------------------------------- 
