--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50150
New Best Solution Fitness: 50145
New Best Solution Fitness: 50110
Generation: 3
New Best Solution Fitness: 49896
New Best Solution Fitness: 49830
Generation: 4
Generation: 5
New Best Solution Fitness: 49750
Generation: 6
New Best Solution Fitness: 49608
Generation: 7
New Best Solution Fitness: 49373
New Best Solution Fitness: 49363
Generation: 8
New Best Solution Fitness: 49328
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.444444 
Mean sub-tour choices: 0.766667 
Best Solution Fitness: 49328 
--------------------------------------------- 
