--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49875
New Best Solution Fitness: 49865
New Best Solution Fitness: 49862
Generation: 3
New Best Solution Fitness: 49574
New Best Solution Fitness: 49559
Generation: 4
Generation: 5
New Best Solution Fitness: 49543
Generation: 6
New Best Solution Fitness: 49533
Generation: 7
New Best Solution Fitness: 49504
Generation: 8
New Best Solution Fitness: 49453
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.811111 
Mean sub-tour choices: 1.31111 
Best Solution Fitness: 49453 
--------------------------------------------- 
