--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49871
New Best Solution Fitness: 49845
New Best Solution Fitness: 49804
Generation: 3
New Best Solution Fitness: 49726
New Best Solution Fitness: 49661
Generation: 4
New Best Solution Fitness: 49623
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 49615
Generation: 8
New Best Solution Fitness: 49445
New Best Solution Fitness: 49437
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.944444 
Mean sub-tour choices: 1.46667 
Best Solution Fitness: 49437 
--------------------------------------------- 
