--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49980
New Best Solution Fitness: 49969
New Best Solution Fitness: 49948
Generation: 3
New Best Solution Fitness: 49758
New Best Solution Fitness: 49742
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 49717
Generation: 7
New Best Solution Fitness: 49705
Generation: 8
Generation: 9
New Best Solution Fitness: 49667
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.577778 
Mean sub-tour choices: 0.922222 
Best Solution Fitness: 49667 
--------------------------------------------- 
