--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49564
New Best Solution Fitness: 49559
New Best Solution Fitness: 49541
Generation: 3
New Best Solution Fitness: 49491
Generation: 4
Generation: 5
New Best Solution Fitness: 49410
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 49334
Generation: 9
New Best Solution Fitness: 49333
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.12222 
Mean sub-tour choices: 1.78889 
Best Solution Fitness: 49333 
--------------------------------------------- 
