--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50124
New Best Solution Fitness: 50113
New Best Solution Fitness: 50112
New Best Solution Fitness: 50107
New Best Solution Fitness: 50083
Generation: 3
New Best Solution Fitness: 49921
New Best Solution Fitness: 49916
Generation: 4
New Best Solution Fitness: 49894
New Best Solution Fitness: 49753
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 49679
Generation: 9
New Best Solution Fitness: 49678
Generation: 10
New Best Solution Fitness: 49665
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.32222 
Mean sub-tour choices: 2.01111 
Best Solution Fitness: 49665 
--------------------------------------------- 
