--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50027
New Best Solution Fitness: 49988
Generation: 3
New Best Solution Fitness: 49976
New Best Solution Fitness: 49924
Generation: 4
New Best Solution Fitness: 49876
Generation: 5
New Best Solution Fitness: 49865
Generation: 6
New Best Solution Fitness: 49842
New Best Solution Fitness: 49828
Generation: 7
New Best Solution Fitness: 49623
New Best Solution Fitness: 49609
Generation: 8
New Best Solution Fitness: 49599
Generation: 9
Generation: 10
New Best Solution Fitness: 49578
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.855556 
Mean sub-tour choices: 1.36667 
Best Solution Fitness: 49578 
--------------------------------------------- 
