--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49530
Generation: 3
Generation: 4
New Best Solution Fitness: 49454
Generation: 5
New Best Solution Fitness: 49436
New Best Solution Fitness: 49412
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 49407
Generation: 9
New Best Solution Fitness: 49391
Generation: 10
New Best Solution Fitness: 49368
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.533333 
Mean sub-tour choices: 0.933333 
Best Solution Fitness: 49368 
--------------------------------------------- 
