--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50724
New Best Solution Fitness: 50590
New Best Solution Fitness: 50438
Generation: 3
New Best Solution Fitness: 49784
New Best Solution Fitness: 49632
New Best Solution Fitness: 49621
Generation: 4
Generation: 5
New Best Solution Fitness: 49531
New Best Solution Fitness: 49503
New Best Solution Fitness: 49467
Generation: 6
New Best Solution Fitness: 49431
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.755556 
Mean sub-tour choices: 1.23333 
Best Solution Fitness: 49431 
--------------------------------------------- 
