--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50045
New Best Solution Fitness: 50011
New Best Solution Fitness: 50005
Generation: 3
New Best Solution Fitness: 49990
New Best Solution Fitness: 49956
Generation: 4
New Best Solution Fitness: 49939
Generation: 5
New Best Solution Fitness: 49897
New Best Solution Fitness: 49880
Generation: 6
Generation: 7
New Best Solution Fitness: 49852
New Best Solution Fitness: 49739
Generation: 8
New Best Solution Fitness: 49691
Generation: 9
New Best Solution Fitness: 49672
Generation: 10
New Best Solution Fitness: 49598
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.466667 
Mean sub-tour choices: 0.833333 
Best Solution Fitness: 49598 
--------------------------------------------- 
