--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49905
Generation: 3
New Best Solution Fitness: 49717
New Best Solution Fitness: 49714
Generation: 4
New Best Solution Fitness: 49605
New Best Solution Fitness: 49602
Generation: 5
New Best Solution Fitness: 49596
Generation: 6
New Best Solution Fitness: 49561
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 49524
New Best Solution Fitness: 49508
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.855556 
Mean sub-tour choices: 1.47778 
Best Solution Fitness: 49508 
--------------------------------------------- 
