--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49798
New Best Solution Fitness: 49762
New Best Solution Fitness: 49653
Generation: 3
New Best Solution Fitness: 49648
New Best Solution Fitness: 49581
Generation: 4
New Best Solution Fitness: 49509
New Best Solution Fitness: 49473
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 49452
Generation: 8
New Best Solution Fitness: 49436
Generation: 9
Generation: 10
New Best Solution Fitness: 49307
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.711111 
Mean sub-tour choices: 1.22222 
Best Solution Fitness: 49307 
--------------------------------------------- 
