--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49680
New Best Solution Fitness: 49641
Generation: 3
New Best Solution Fitness: 49566
New Best Solution Fitness: 49548
Generation: 4
New Best Solution Fitness: 49546
New Best Solution Fitness: 49542
Generation: 5
New Best Solution Fitness: 49540
Generation: 6
New Best Solution Fitness: 49463
Generation: 7
New Best Solution Fitness: 49435
Generation: 8
New Best Solution Fitness: 49409
Generation: 9
New Best Solution Fitness: 49408
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.933333 
Mean sub-tour choices: 1.53333 
Best Solution Fitness: 49408 
--------------------------------------------- 
