--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49878
New Best Solution Fitness: 49805
Generation: 3
New Best Solution Fitness: 49779
New Best Solution Fitness: 49705
Generation: 4
New Best Solution Fitness: 49646
New Best Solution Fitness: 49625
Generation: 5
New Best Solution Fitness: 49591
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.12222 
Mean sub-tour choices: 1.73333 
Best Solution Fitness: 49591 
--------------------------------------------- 
