--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49611
New Best Solution Fitness: 49589
New Best Solution Fitness: 49581
Generation: 3
New Best Solution Fitness: 49559
New Best Solution Fitness: 49553
Generation: 4
New Best Solution Fitness: 49542
Generation: 5
New Best Solution Fitness: 49490
New Best Solution Fitness: 49406
Generation: 6
New Best Solution Fitness: 49366
Generation: 7
New Best Solution Fitness: 49357
Generation: 8
Generation: 9
New Best Solution Fitness: 49335
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.755556 
Mean sub-tour choices: 1.23333 
Best Solution Fitness: 49335 
--------------------------------------------- 
