--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50346
New Best Solution Fitness: 50321
New Best Solution Fitness: 50290
New Best Solution Fitness: 50273
Generation: 3
New Best Solution Fitness: 50058
New Best Solution Fitness: 50010
Generation: 4
New Best Solution Fitness: 49999
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 49776
New Best Solution Fitness: 49699
Generation: 9
New Best Solution Fitness: 49597
Generation: 10
New Best Solution Fitness: 49595
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.54444 
Mean sub-tour choices: 2.22222 
Best Solution Fitness: 49595 
--------------------------------------------- 
