--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49416
New Best Solution Fitness: 49373
Generation: 3
New Best Solution Fitness: 49336
New Best Solution Fitness: 49325
New Best Solution Fitness: 49323
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 49312
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 49284
New Best Solution Fitness: 49263
Generation: 10
New Best Solution Fitness: 49246
New Best Solution Fitness: 49221
New Best Solution Fitness: 49214
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.47778 
Mean sub-tour choices: 2.12222 
Best Solution Fitness: 49214 
--------------------------------------------- 
