--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49754
New Best Solution Fitness: 49695
Generation: 3
New Best Solution Fitness: 49579
Generation: 4
Generation: 5
New Best Solution Fitness: 49570
New Best Solution Fitness: 49556
Generation: 6
New Best Solution Fitness: 49555
New Best Solution Fitness: 49507
New Best Solution Fitness: 49506
Generation: 7
New Best Solution Fitness: 49497
Generation: 8
New Best Solution Fitness: 49462
Generation: 9
Generation: 10
New Best Solution Fitness: 49428
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.633333 
Mean sub-tour choices: 1.08889 
Best Solution Fitness: 49428 
--------------------------------------------- 
