--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49549
New Best Solution Fitness: 49535
Generation: 3
New Best Solution Fitness: 49452
New Best Solution Fitness: 49404
Generation: 4
New Best Solution Fitness: 49391
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 49390
New Best Solution Fitness: 49379
Generation: 8
New Best Solution Fitness: 49343
Generation: 9
Generation: 10
New Best Solution Fitness: 49316
New Best Solution Fitness: 49291
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.566667 
Mean sub-tour choices: 1.02222 
Best Solution Fitness: 49291 
--------------------------------------------- 
