--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50082
New Best Solution Fitness: 50074
New Best Solution Fitness: 50054
Generation: 3
New Best Solution Fitness: 49878
New Best Solution Fitness: 49861
New Best Solution Fitness: 49818
Generation: 4
New Best Solution Fitness: 49672
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 49661
Generation: 10
New Best Solution Fitness: 49620
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.366667 
Mean sub-tour choices: 0.622222 
Best Solution Fitness: 49620 
--------------------------------------------- 
