--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49428
New Best Solution Fitness: 49408
New Best Solution Fitness: 49356
Generation: 3
New Best Solution Fitness: 49352
Generation: 4
New Best Solution Fitness: 49274
New Best Solution Fitness: 49253
Generation: 5
New Best Solution Fitness: 49244
Generation: 6
New Best Solution Fitness: 49187
Generation: 7
New Best Solution Fitness: 49143
Generation: 8
Generation: 9
New Best Solution Fitness: 49137
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.677778 
Mean sub-tour choices: 1.17778 
Best Solution Fitness: 49137 
--------------------------------------------- 
