--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49753
New Best Solution Fitness: 49742
New Best Solution Fitness: 49729
Generation: 3
New Best Solution Fitness: 49669
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 49595
Generation: 7
New Best Solution Fitness: 49594
Generation: 8
New Best Solution Fitness: 49384
New Best Solution Fitness: 49383
Generation: 9
New Best Solution Fitness: 49366
New Best Solution Fitness: 49355
New Best Solution Fitness: 49354
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.677778 
Mean sub-tour choices: 1.16667 
Best Solution Fitness: 49354 
--------------------------------------------- 
