--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50383
New Best Solution Fitness: 50356
New Best Solution Fitness: 50331
New Best Solution Fitness: 50198
New Best Solution Fitness: 50190
New Best Solution Fitness: 50159
Generation: 3
New Best Solution Fitness: 50058
Generation: 4
New Best Solution Fitness: 49872
New Best Solution Fitness: 49838
Generation: 5
New Best Solution Fitness: 49697
New Best Solution Fitness: 49694
Generation: 6
New Best Solution Fitness: 49619
Generation: 7
New Best Solution Fitness: 49614
Generation: 8
Generation: 9
New Best Solution Fitness: 49524
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.677778 
Mean sub-tour choices: 1.14444 
Best Solution Fitness: 49524 
--------------------------------------------- 
