--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49768
Generation: 3
New Best Solution Fitness: 49674
Generation: 4
New Best Solution Fitness: 49558
New Best Solution Fitness: 49557
Generation: 5
New Best Solution Fitness: 49556
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 49479
New Best Solution Fitness: 49475
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.466667 
Mean sub-tour choices: 0.811111 
Best Solution Fitness: 49475 
--------------------------------------------- 
