--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50125
New Best Solution Fitness: 50114
New Best Solution Fitness: 50108
New Best Solution Fitness: 50082
Generation: 3
New Best Solution Fitness: 49921
New Best Solution Fitness: 49741
New Best Solution Fitness: 49684
Generation: 4
New Best Solution Fitness: 49621
Generation: 5
New Best Solution Fitness: 49615
New Best Solution Fitness: 49610
Generation: 6
Generation: 7
New Best Solution Fitness: 49585
Generation: 8
New Best Solution Fitness: 49530
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.833333 
Mean sub-tour choices: 1.32222 
Best Solution Fitness: 49530 
--------------------------------------------- 
