--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49603
New Best Solution Fitness: 49593
New Best Solution Fitness: 49564
Generation: 3
New Best Solution Fitness: 49499
Generation: 4
New Best Solution Fitness: 49480
New Best Solution Fitness: 49471
Generation: 5
New Best Solution Fitness: 49395
New Best Solution Fitness: 49371
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 49312
Generation: 9
New Best Solution Fitness: 49256
Generation: 10
New Best Solution Fitness: 49250
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.988889 
Mean sub-tour choices: 1.45556 
Best Solution Fitness: 49250 
--------------------------------------------- 
