--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50525
Generation: 3
New Best Solution Fitness: 50067
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 49594
Generation: 7
New Best Solution Fitness: 49496
New Best Solution Fitness: 49472
Generation: 8
New Best Solution Fitness: 49415
New Best Solution Fitness: 49397
New Best Solution Fitness: 49386
New Best Solution Fitness: 49369
Generation: 9
New Best Solution Fitness: 49353
New Best Solution Fitness: 49351
New Best Solution Fitness: 49345
Generation: 10
New Best Solution Fitness: 49329
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.477778 
Mean sub-tour choices: 0.855556 
Best Solution Fitness: 49329 
--------------------------------------------- 
