--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49945
New Best Solution Fitness: 49934
New Best Solution Fitness: 49891
Generation: 3
New Best Solution Fitness: 49582
New Best Solution Fitness: 49571
New Best Solution Fitness: 49552
New Best Solution Fitness: 49516
Generation: 4
New Best Solution Fitness: 49489
Generation: 5
New Best Solution Fitness: 49477
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 49433
New Best Solution Fitness: 49399
Generation: 10
New Best Solution Fitness: 49391
New Best Solution Fitness: 49363
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.666667 
Mean sub-tour choices: 1.14444 
Best Solution Fitness: 49363 
--------------------------------------------- 
