--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49615
New Best Solution Fitness: 49596
New Best Solution Fitness: 49585
Generation: 3
New Best Solution Fitness: 49542
New Best Solution Fitness: 49482
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 49467
Generation: 7
New Best Solution Fitness: 49437
New Best Solution Fitness: 49427
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.477778 
Mean sub-tour choices: 0.811111 
Best Solution Fitness: 49427 
--------------------------------------------- 
