--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49842
New Best Solution Fitness: 49741
New Best Solution Fitness: 49716
Generation: 3
New Best Solution Fitness: 49672
New Best Solution Fitness: 49651
New Best Solution Fitness: 49611
Generation: 4
New Best Solution Fitness: 49590
Generation: 5
Generation: 6
New Best Solution Fitness: 49580
Generation: 7
Generation: 8
New Best Solution Fitness: 49579
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.955556 
Mean sub-tour choices: 1.54444 
Best Solution Fitness: 49579 
--------------------------------------------- 
