--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49813
New Best Solution Fitness: 49807
New Best Solution Fitness: 49726
Generation: 3
New Best Solution Fitness: 49687
New Best Solution Fitness: 49538
Generation: 4
New Best Solution Fitness: 49522
New Best Solution Fitness: 49475
New Best Solution Fitness: 49404
Generation: 5
New Best Solution Fitness: 49357
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.6 
Mean sub-tour choices: 1.02222 
Best Solution Fitness: 49357 
--------------------------------------------- 
