--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50014
New Best Solution Fitness: 49945
Generation: 3
New Best Solution Fitness: 49901
New Best Solution Fitness: 49838
New Best Solution Fitness: 49809
Generation: 4
New Best Solution Fitness: 49801
New Best Solution Fitness: 49775
Generation: 5
New Best Solution Fitness: 49749
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 49626
New Best Solution Fitness: 49606
New Best Solution Fitness: 49605
Generation: 9
New Best Solution Fitness: 49574
New Best Solution Fitness: 49486
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.32222 
Mean sub-tour choices: 1.98889 
Best Solution Fitness: 49486 
--------------------------------------------- 
