--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49662
New Best Solution Fitness: 49626
Generation: 3
New Best Solution Fitness: 49521
Generation: 4
Generation: 5
New Best Solution Fitness: 49515
New Best Solution Fitness: 49486
Generation: 6
New Best Solution Fitness: 49480
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 49444
New Best Solution Fitness: 49393
Generation: 10
New Best Solution Fitness: 49348
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.522222 
Mean sub-tour choices: 0.9 
Best Solution Fitness: 49348 
--------------------------------------------- 
