--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49798
New Best Solution Fitness: 49762
Generation: 3
New Best Solution Fitness: 49605
Generation: 4
Generation: 5
New Best Solution Fitness: 49581
Generation: 6
New Best Solution Fitness: 49567
Generation: 7
New Best Solution Fitness: 49532
New Best Solution Fitness: 49473
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.533333 
Mean sub-tour choices: 1 
Best Solution Fitness: 49473 
--------------------------------------------- 
