--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49853
New Best Solution Fitness: 49820
New Best Solution Fitness: 49809
New Best Solution Fitness: 49798
New Best Solution Fitness: 49739
Generation: 3
New Best Solution Fitness: 49724
New Best Solution Fitness: 49713
Generation: 4
Generation: 5
New Best Solution Fitness: 49679
Generation: 6
New Best Solution Fitness: 49668
Generation: 7
New Best Solution Fitness: 49633
Generation: 8
New Best Solution Fitness: 49557
New Best Solution Fitness: 49514
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.16667 
Mean sub-tour choices: 1.67778 
Best Solution Fitness: 49514 
--------------------------------------------- 
