--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50038
New Best Solution Fitness: 49972
Generation: 3
New Best Solution Fitness: 49699
Generation: 4
Generation: 5
New Best Solution Fitness: 49694
Generation: 6
New Best Solution Fitness: 49659
Generation: 7
New Best Solution Fitness: 49543
New Best Solution Fitness: 49519
Generation: 8
New Best Solution Fitness: 49496
Generation: 9
New Best Solution Fitness: 49451
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.588889 
Mean sub-tour choices: 1.02222 
Best Solution Fitness: 49451 
--------------------------------------------- 
