--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50305
New Best Solution Fitness: 50296
New Best Solution Fitness: 50269
Generation: 3
New Best Solution Fitness: 49909
New Best Solution Fitness: 49827
Generation: 4
New Best Solution Fitness: 49784
New Best Solution Fitness: 49775
Generation: 5
New Best Solution Fitness: 49759
Generation: 6
New Best Solution Fitness: 49705
Generation: 7
New Best Solution Fitness: 49666
New Best Solution Fitness: 49656
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 49648
New Best Solution Fitness: 49647
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.644444 
Mean sub-tour choices: 1.04444 
Best Solution Fitness: 49647 
--------------------------------------------- 
