--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49934
Generation: 3
New Best Solution Fitness: 49780
Generation: 4
New Best Solution Fitness: 49766
New Best Solution Fitness: 49765
Generation: 5
New Best Solution Fitness: 49620
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 49356
Generation: 9
Generation: 10
New Best Solution Fitness: 49355
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.4 
Mean sub-tour choices: 0.744444 
Best Solution Fitness: 49355 
--------------------------------------------- 
