--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50510
New Best Solution Fitness: 50486
New Best Solution Fitness: 50383
Generation: 3
New Best Solution Fitness: 50126
New Best Solution Fitness: 50022
Generation: 4
New Best Solution Fitness: 49939
New Best Solution Fitness: 49835
Generation: 5
Generation: 6
New Best Solution Fitness: 49805
Generation: 7
Generation: 8
New Best Solution Fitness: 49781
New Best Solution Fitness: 49719
Generation: 9
Generation: 10
New Best Solution Fitness: 49600
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.42222 
Mean sub-tour choices: 2.1 
Best Solution Fitness: 49600 
--------------------------------------------- 
