--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50116
New Best Solution Fitness: 50107
New Best Solution Fitness: 50095
Generation: 3
New Best Solution Fitness: 49992
New Best Solution Fitness: 49967
Generation: 4
New Best Solution Fitness: 49962
New Best Solution Fitness: 49959
Generation: 5
New Best Solution Fitness: 49933
New Best Solution Fitness: 49902
New Best Solution Fitness: 49878
Generation: 6
New Best Solution Fitness: 49840
New Best Solution Fitness: 49818
New Best Solution Fitness: 49683
Generation: 7
New Best Solution Fitness: 49572
New Best Solution Fitness: 49547
Generation: 8
New Best Solution Fitness: 49537
Generation: 9
Generation: 10
New Best Solution Fitness: 49516
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.7 
Mean sub-tour choices: 1.14444 
Best Solution Fitness: 49516 
--------------------------------------------- 
