--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49884
New Best Solution Fitness: 49853
New Best Solution Fitness: 49810
Generation: 3
New Best Solution Fitness: 49809
New Best Solution Fitness: 49797
New Best Solution Fitness: 49755
New Best Solution Fitness: 49741
Generation: 4
New Best Solution Fitness: 49687
Generation: 5
New Best Solution Fitness: 49601
New Best Solution Fitness: 49563
Generation: 6
New Best Solution Fitness: 49557
New Best Solution Fitness: 49497
Generation: 7
New Best Solution Fitness: 49491
Generation: 8
New Best Solution Fitness: 49490
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.866667 
Mean sub-tour choices: 1.37778 
Best Solution Fitness: 49490 
--------------------------------------------- 
