--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 89670
New Best Solution Fitness: 89609
New Best Solution Fitness: 89281
Generation: 3
New Best Solution Fitness: 89131
New Best Solution Fitness: 89118
Generation: 4
New Best Solution Fitness: 89058
Generation: 5
New Best Solution Fitness: 88938
New Best Solution Fitness: 88931
Generation: 6
New Best Solution Fitness: 88529
Generation: 7
New Best Solution Fitness: 87949
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.944444 
Mean sub-tour choices: 1.17778 
Best Solution Fitness: 87949 
--------------------------------------------- 
