--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88535
New Best Solution Fitness: 88102
Generation: 3
New Best Solution Fitness: 87839
New Best Solution Fitness: 87777
Generation: 4
New Best Solution Fitness: 87746
Generation: 5
New Best Solution Fitness: 87736
Generation: 6
Generation: 7
New Best Solution Fitness: 87620
Generation: 8
Generation: 9
New Best Solution Fitness: 87508
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.24444 
Mean sub-tour choices: 1.47778 
Best Solution Fitness: 87508 
--------------------------------------------- 
