--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 89225
New Best Solution Fitness: 89053
Generation: 3
New Best Solution Fitness: 88411
New Best Solution Fitness: 88358
Generation: 4
New Best Solution Fitness: 88250
Generation: 5
New Best Solution Fitness: 88162
New Best Solution Fitness: 88076
New Best Solution Fitness: 88056
Generation: 6
New Best Solution Fitness: 87970
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.544444 
Mean sub-tour choices: 0.722222 
Best Solution Fitness: 87970 
--------------------------------------------- 
