--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88058
Generation: 3
New Best Solution Fitness: 87667
Generation: 4
New Best Solution Fitness: 87562
Generation: 5
New Best Solution Fitness: 87526
New Best Solution Fitness: 87491
Generation: 6
New Best Solution Fitness: 87411
New Best Solution Fitness: 87408
New Best Solution Fitness: 87291
New Best Solution Fitness: 87289
Generation: 7
New Best Solution Fitness: 87030
Generation: 8
New Best Solution Fitness: 86977
Generation: 9
Generation: 10
New Best Solution Fitness: 86967
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.722222 
Mean sub-tour choices: 1.11111 
Best Solution Fitness: 86967 
--------------------------------------------- 
