--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88028
New Best Solution Fitness: 88019
Generation: 3
New Best Solution Fitness: 87925
New Best Solution Fitness: 87921
Generation: 4
New Best Solution Fitness: 87648
New Best Solution Fitness: 87631
New Best Solution Fitness: 87510
Generation: 5
New Best Solution Fitness: 87471
New Best Solution Fitness: 87467
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 87351
New Best Solution Fitness: 87350
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.04444 
Mean sub-tour choices: 1.36667 
Best Solution Fitness: 87350 
--------------------------------------------- 
