--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87742
New Best Solution Fitness: 87707
New Best Solution Fitness: 87618
Generation: 3
New Best Solution Fitness: 87525
Generation: 4
New Best Solution Fitness: 87520
New Best Solution Fitness: 87315
Generation: 5
Generation: 6
New Best Solution Fitness: 87177
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 87166
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.488889 
Mean sub-tour choices: 0.8 
Best Solution Fitness: 87166 
--------------------------------------------- 
