--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88018
New Best Solution Fitness: 87933
Generation: 3
New Best Solution Fitness: 87821
Generation: 4
New Best Solution Fitness: 87642
Generation: 5
New Best Solution Fitness: 87637
New Best Solution Fitness: 87525
Generation: 6
New Best Solution Fitness: 87497
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 87456
Generation: 10
New Best Solution Fitness: 87281
New Best Solution Fitness: 87155
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.611111 
Mean sub-tour choices: 0.9 
Best Solution Fitness: 87155 
--------------------------------------------- 
