--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88485
Generation: 3
New Best Solution Fitness: 88317
New Best Solution Fitness: 88274
New Best Solution Fitness: 88269
Generation: 4
New Best Solution Fitness: 88071
Generation: 5
Generation: 6
New Best Solution Fitness: 88016
New Best Solution Fitness: 87926
Generation: 7
New Best Solution Fitness: 87846
Generation: 8
New Best Solution Fitness: 87345
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.566667 
Mean sub-tour choices: 0.955556 
Best Solution Fitness: 87345 
--------------------------------------------- 
