--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88623
New Best Solution Fitness: 88604
Generation: 3
New Best Solution Fitness: 88446
New Best Solution Fitness: 88285
Generation: 4
New Best Solution Fitness: 88220
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 88188
Generation: 9
New Best Solution Fitness: 87880
Generation: 10
New Best Solution Fitness: 87870
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.755556 
Mean sub-tour choices: 1.01111 
Best Solution Fitness: 87870 
--------------------------------------------- 
