--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87941
New Best Solution Fitness: 87933
Generation: 3
New Best Solution Fitness: 87774
Generation: 4
New Best Solution Fitness: 87693
Generation: 5
New Best Solution Fitness: 87634
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 87500
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.6 
Mean sub-tour choices: 0.877778 
Best Solution Fitness: 87500 
--------------------------------------------- 
