--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 89242
New Best Solution Fitness: 89237
New Best Solution Fitness: 89231
Generation: 3
New Best Solution Fitness: 88919
Generation: 4
Generation: 5
New Best Solution Fitness: 87940
New Best Solution Fitness: 87934
Generation: 6
Generation: 7
New Best Solution Fitness: 87730
New Best Solution Fitness: 87711
Generation: 8
New Best Solution Fitness: 87599
Generation: 9
Generation: 10
New Best Solution Fitness: 87414
New Best Solution Fitness: 87366
New Best Solution Fitness: 87291
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.18889 
Mean sub-tour choices: 1.51111 
Best Solution Fitness: 87291 
--------------------------------------------- 
