--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 90182
New Best Solution Fitness: 90098
New Best Solution Fitness: 90062
Generation: 3
New Best Solution Fitness: 88863
New Best Solution Fitness: 88856
New Best Solution Fitness: 88852
Generation: 4
New Best Solution Fitness: 87992
New Best Solution Fitness: 87928
Generation: 5
New Best Solution Fitness: 87776
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 87515
Generation: 9
Generation: 10
New Best Solution Fitness: 87261
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.633333 
Mean sub-tour choices: 0.755556 
Best Solution Fitness: 87261 
--------------------------------------------- 
