--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88060
New Best Solution Fitness: 88025
Generation: 3
New Best Solution Fitness: 87977
Generation: 4
New Best Solution Fitness: 87973
Generation: 5
Generation: 6
New Best Solution Fitness: 87776
Generation: 7
New Best Solution Fitness: 87500
New Best Solution Fitness: 87461
New Best Solution Fitness: 87427
Generation: 8
New Best Solution Fitness: 87285
New Best Solution Fitness: 87279
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.333333 
Mean sub-tour choices: 0.566667 
Best Solution Fitness: 87279 
--------------------------------------------- 
