--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88071
Generation: 3
New Best Solution Fitness: 87966
New Best Solution Fitness: 87961
Generation: 4
Generation: 5
New Best Solution Fitness: 87950
Generation: 6
New Best Solution Fitness: 87671
New Best Solution Fitness: 87507
New Best Solution Fitness: 87435
Generation: 7
New Best Solution Fitness: 87378
New Best Solution Fitness: 87271
Generation: 8
New Best Solution Fitness: 87266
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.866667 
Mean sub-tour choices: 1.13333 
Best Solution Fitness: 87266 
--------------------------------------------- 
