--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 89757
New Best Solution Fitness: 89663
New Best Solution Fitness: 89270
Generation: 3
New Best Solution Fitness: 89036
Generation: 4
New Best Solution Fitness: 88475
Generation: 5
New Best Solution Fitness: 88132
New Best Solution Fitness: 88073
Generation: 6
New Best Solution Fitness: 87943
Generation: 7
New Best Solution Fitness: 87869
Generation: 8
New Best Solution Fitness: 87785
New Best Solution Fitness: 87779
Generation: 9
Generation: 10
New Best Solution Fitness: 87508
New Best Solution Fitness: 87506
New Best Solution Fitness: 87482
New Best Solution Fitness: 87356
New Best Solution Fitness: 87306
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.555556 
Mean sub-tour choices: 0.866667 
Best Solution Fitness: 87306 
--------------------------------------------- 
