--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 89352
New Best Solution Fitness: 89153
New Best Solution Fitness: 88725
Generation: 3
New Best Solution Fitness: 88661
Generation: 4
New Best Solution Fitness: 88518
Generation: 5
Generation: 6
New Best Solution Fitness: 88409
New Best Solution Fitness: 88298
New Best Solution Fitness: 88264
Generation: 7
New Best Solution Fitness: 88243
New Best Solution Fitness: 88232
New Best Solution Fitness: 88147
Generation: 8
New Best Solution Fitness: 88136
New Best Solution Fitness: 88126
Generation: 9
New Best Solution Fitness: 88115
Generation: 10
New Best Solution Fitness: 88104
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.11111 
Mean sub-tour choices: 1.53333 
Best Solution Fitness: 88104 
--------------------------------------------- 
