--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88756
New Best Solution Fitness: 88670
New Best Solution Fitness: 88247
Generation: 3
New Best Solution Fitness: 88015
New Best Solution Fitness: 88012
New Best Solution Fitness: 87905
Generation: 4
New Best Solution Fitness: 87885
Generation: 5
New Best Solution Fitness: 87873
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 87649
New Best Solution Fitness: 87607
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.866667 
Mean sub-tour choices: 1.1 
Best Solution Fitness: 87607 
--------------------------------------------- 
