--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88882
New Best Solution Fitness: 88576
Generation: 3
New Best Solution Fitness: 88464
Generation: 4
New Best Solution Fitness: 88283
New Best Solution Fitness: 88272
Generation: 5
New Best Solution Fitness: 88270
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 88106
New Best Solution Fitness: 88092
New Best Solution Fitness: 88062
New Best Solution Fitness: 88051
New Best Solution Fitness: 87622
New Best Solution Fitness: 87527
New Best Solution Fitness: 87518
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.811111 
Mean sub-tour choices: 1.13333 
Best Solution Fitness: 87518 
--------------------------------------------- 
