--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88421
New Best Solution Fitness: 88361
New Best Solution Fitness: 88137
Generation: 3
New Best Solution Fitness: 87780
New Best Solution Fitness: 87755
Generation: 4
New Best Solution Fitness: 87516
New Best Solution Fitness: 87515
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.433333 
Mean sub-tour choices: 0.688889 
Best Solution Fitness: 87515 
--------------------------------------------- 
