--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88558
Generation: 3
New Best Solution Fitness: 88504
New Best Solution Fitness: 88270
Generation: 4
New Best Solution Fitness: 88256
New Best Solution Fitness: 88191
Generation: 5
New Best Solution Fitness: 88156
New Best Solution Fitness: 88046
Generation: 6
Generation: 7
New Best Solution Fitness: 88032
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.866667 
Mean sub-tour choices: 1.52222 
Best Solution Fitness: 88032 
--------------------------------------------- 
