--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 89388
New Best Solution Fitness: 89340
Generation: 3
New Best Solution Fitness: 89149
New Best Solution Fitness: 89140
Generation: 4
New Best Solution Fitness: 88625
New Best Solution Fitness: 88421
New Best Solution Fitness: 88338
Generation: 5
New Best Solution Fitness: 88136
New Best Solution Fitness: 88128
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 88108
New Best Solution Fitness: 88092
New Best Solution Fitness: 88059
Generation: 10
New Best Solution Fitness: 87908
New Best Solution Fitness: 87887
New Best Solution Fitness: 87751
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.688889 
Mean sub-tour choices: 1.03333 
Best Solution Fitness: 87751 
--------------------------------------------- 
