--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88417
New Best Solution Fitness: 88408
New Best Solution Fitness: 88304
Generation: 3
New Best Solution Fitness: 87855
New Best Solution Fitness: 87834
Generation: 4
New Best Solution Fitness: 87806
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 87743
New Best Solution Fitness: 87729
Generation: 9
New Best Solution Fitness: 87640
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.666667 
Mean sub-tour choices: 0.988889 
Best Solution Fitness: 87640 
--------------------------------------------- 
