--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88578
New Best Solution Fitness: 88528
New Best Solution Fitness: 88267
Generation: 3
New Best Solution Fitness: 88120
New Best Solution Fitness: 88116
New Best Solution Fitness: 88089
Generation: 4
New Best Solution Fitness: 88085
Generation: 5
Generation: 6
New Best Solution Fitness: 88001
Generation: 7
New Best Solution Fitness: 87873
Generation: 8
New Best Solution Fitness: 87827
Generation: 9
New Best Solution Fitness: 87760
Generation: 10
New Best Solution Fitness: 87747
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.06667 
Mean sub-tour choices: 1.13333 
Best Solution Fitness: 87747 
--------------------------------------------- 
