--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88621
New Best Solution Fitness: 88607
Generation: 3
New Best Solution Fitness: 88465
Generation: 4
New Best Solution Fitness: 88292
New Best Solution Fitness: 88241
New Best Solution Fitness: 88150
Generation: 5
New Best Solution Fitness: 88119
Generation: 6
New Best Solution Fitness: 88043
Generation: 7
New Best Solution Fitness: 88018
New Best Solution Fitness: 88012
New Best Solution Fitness: 87984
Generation: 8
New Best Solution Fitness: 87859
New Best Solution Fitness: 87690
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.32222 
Mean sub-tour choices: 1.68889 
Best Solution Fitness: 87690 
--------------------------------------------- 
