--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88764
New Best Solution Fitness: 88745
Generation: 3
New Best Solution Fitness: 88384
Generation: 4
New Best Solution Fitness: 88234
New Best Solution Fitness: 88215
Generation: 5
New Best Solution Fitness: 88197
New Best Solution Fitness: 88182
Generation: 6
New Best Solution Fitness: 87883
New Best Solution Fitness: 87851
Generation: 7
New Best Solution Fitness: 87845
Generation: 8
New Best Solution Fitness: 87772
New Best Solution Fitness: 87771
Generation: 9
New Best Solution Fitness: 87442
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.688889 
Mean sub-tour choices: 0.933333 
Best Solution Fitness: 87442 
--------------------------------------------- 
