--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88503
New Best Solution Fitness: 88426
New Best Solution Fitness: 88334
Generation: 3
New Best Solution Fitness: 87443
New Best Solution Fitness: 87388
Generation: 4
New Best Solution Fitness: 87381
New Best Solution Fitness: 87371
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 87352
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.96667 
Mean sub-tour choices: 2.1 
Best Solution Fitness: 87352 
--------------------------------------------- 
