--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88687
New Best Solution Fitness: 88613
Generation: 3
New Best Solution Fitness: 88529
New Best Solution Fitness: 88504
Generation: 4
New Best Solution Fitness: 88129
New Best Solution Fitness: 88067
Generation: 5
New Best Solution Fitness: 87956
Generation: 6
New Best Solution Fitness: 87725
New Best Solution Fitness: 87641
Generation: 7
New Best Solution Fitness: 87539
New Best Solution Fitness: 87500
Generation: 8
New Best Solution Fitness: 87424
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.522222 
Mean sub-tour choices: 0.833333 
Best Solution Fitness: 87424 
--------------------------------------------- 
