--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88590
New Best Solution Fitness: 88503
New Best Solution Fitness: 88345
Generation: 3
Generation: 4
New Best Solution Fitness: 88310
Generation: 5
New Best Solution Fitness: 88227
Generation: 6
New Best Solution Fitness: 88131
New Best Solution Fitness: 88120
Generation: 7
Generation: 8
New Best Solution Fitness: 88101
Generation: 9
New Best Solution Fitness: 87919
Generation: 10
New Best Solution Fitness: 87900
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.644444 
Mean sub-tour choices: 1.05556 
Best Solution Fitness: 87900 
--------------------------------------------- 
