--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87707
New Best Solution Fitness: 87447
Generation: 3
New Best Solution Fitness: 87445
Generation: 4
New Best Solution Fitness: 87416
Generation: 5
New Best Solution Fitness: 87401
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.7 
Mean sub-tour choices: 1.13333 
Best Solution Fitness: 87401 
--------------------------------------------- 
