--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87681
New Best Solution Fitness: 87678
New Best Solution Fitness: 87670
Generation: 3
New Best Solution Fitness: 87654
New Best Solution Fitness: 87588
Generation: 4
Generation: 5
New Best Solution Fitness: 87531
Generation: 6
New Best Solution Fitness: 87324
New Best Solution Fitness: 87197
Generation: 7
New Best Solution Fitness: 87171
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.711111 
Mean sub-tour choices: 1.13333 
Best Solution Fitness: 87171 
--------------------------------------------- 
