--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 89150
New Best Solution Fitness: 88949
Generation: 3
New Best Solution Fitness: 87867
Generation: 4
New Best Solution Fitness: 87761
Generation: 5
Generation: 6
New Best Solution Fitness: 87368
Generation: 7
Generation: 8
New Best Solution Fitness: 87363
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.7 
Mean sub-tour choices: 0.833333 
Best Solution Fitness: 87363 
--------------------------------------------- 
