--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88303
New Best Solution Fitness: 88044
Generation: 3
New Best Solution Fitness: 88008
New Best Solution Fitness: 87965
Generation: 4
New Best Solution Fitness: 87476
New Best Solution Fitness: 87469
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 87408
Generation: 9
New Best Solution Fitness: 87386
New Best Solution Fitness: 87327
Generation: 10
New Best Solution Fitness: 87298
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.7 
Mean sub-tour choices: 1.05556 
Best Solution Fitness: 87298 
--------------------------------------------- 
