--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88237
New Best Solution Fitness: 88172
Generation: 3
New Best Solution Fitness: 88122
New Best Solution Fitness: 88111
New Best Solution Fitness: 88087
Generation: 4
New Best Solution Fitness: 88076
Generation: 5
Generation: 6
New Best Solution Fitness: 87955
New Best Solution Fitness: 87898
New Best Solution Fitness: 87877
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 87715
New Best Solution Fitness: 87686
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.811111 
Mean sub-tour choices: 1.11111 
Best Solution Fitness: 87686 
--------------------------------------------- 
