--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88693
New Best Solution Fitness: 88692
New Best Solution Fitness: 88684
Generation: 3
New Best Solution Fitness: 88549
New Best Solution Fitness: 88403
Generation: 4
New Best Solution Fitness: 88395
New Best Solution Fitness: 88215
Generation: 5
New Best Solution Fitness: 88204
Generation: 6
New Best Solution Fitness: 87953
New Best Solution Fitness: 87931
New Best Solution Fitness: 87925
Generation: 7
New Best Solution Fitness: 87808
New Best Solution Fitness: 87798
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 87605
New Best Solution Fitness: 87411
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.511111 
Mean sub-tour choices: 0.844444 
Best Solution Fitness: 87411 
--------------------------------------------- 
