--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88487
New Best Solution Fitness: 88473
Generation: 3
Generation: 4
Generation: 5
New Best Solution Fitness: 88072
Generation: 6
New Best Solution Fitness: 87882
Generation: 7
New Best Solution Fitness: 87734
Generation: 8
New Best Solution Fitness: 87262
Generation: 9
New Best Solution Fitness: 87238
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.622222 
Mean sub-tour choices: 0.8 
Best Solution Fitness: 87238 
--------------------------------------------- 
