--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88648
New Best Solution Fitness: 88604
New Best Solution Fitness: 88554
Generation: 3
New Best Solution Fitness: 88311
New Best Solution Fitness: 88215
Generation: 4
New Best Solution Fitness: 88070
New Best Solution Fitness: 88053
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 88044
New Best Solution Fitness: 88041
New Best Solution Fitness: 88026
New Best Solution Fitness: 87946
Generation: 10
New Best Solution Fitness: 87759
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.777778 
Mean sub-tour choices: 1.18889 
Best Solution Fitness: 87759 
--------------------------------------------- 
