--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88383
New Best Solution Fitness: 88334
New Best Solution Fitness: 88286
Generation: 3
New Best Solution Fitness: 87685
Generation: 4
New Best Solution Fitness: 87581
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.444444 
Mean sub-tour choices: 0.744444 
Best Solution Fitness: 87581 
--------------------------------------------- 
