--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88437
New Best Solution Fitness: 88394
New Best Solution Fitness: 88190
Generation: 3
New Best Solution Fitness: 88160
New Best Solution Fitness: 88102
Generation: 4
New Best Solution Fitness: 88069
Generation: 5
New Best Solution Fitness: 87979
Generation: 6
New Best Solution Fitness: 87837
Generation: 7
Generation: 8
New Best Solution Fitness: 87796
Generation: 9
New Best Solution Fitness: 87784
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.577778 
Mean sub-tour choices: 1.04444 
Best Solution Fitness: 87784 
--------------------------------------------- 
