--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87756
New Best Solution Fitness: 87653
Generation: 3
New Best Solution Fitness: 87601
Generation: 4
New Best Solution Fitness: 87556
New Best Solution Fitness: 87535
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 87519
New Best Solution Fitness: 87448
New Best Solution Fitness: 87407
Generation: 10
New Best Solution Fitness: 87320
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.777778 
Mean sub-tour choices: 1.14444 
Best Solution Fitness: 87320 
--------------------------------------------- 
