--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87753
New Best Solution Fitness: 87724
Generation: 3
New Best Solution Fitness: 87322
Generation: 4
New Best Solution Fitness: 87289
New Best Solution Fitness: 87260
New Best Solution Fitness: 87208
Generation: 5
New Best Solution Fitness: 87180
New Best Solution Fitness: 87179
Generation: 6
New Best Solution Fitness: 87142
New Best Solution Fitness: 87137
New Best Solution Fitness: 87112
Generation: 7
New Best Solution Fitness: 87082
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.933333 
Mean sub-tour choices: 1.46667 
Best Solution Fitness: 87082 
--------------------------------------------- 
