--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88202
New Best Solution Fitness: 88200
New Best Solution Fitness: 87930
Generation: 3
New Best Solution Fitness: 87910
New Best Solution Fitness: 87828
Generation: 4
New Best Solution Fitness: 87826
New Best Solution Fitness: 87794
Generation: 5
Generation: 6
New Best Solution Fitness: 87789
New Best Solution Fitness: 87535
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.7 
Mean sub-tour choices: 1.11111 
Best Solution Fitness: 87535 
--------------------------------------------- 
