--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87622
New Best Solution Fitness: 87531
New Best Solution Fitness: 87514
Generation: 3
New Best Solution Fitness: 87494
New Best Solution Fitness: 87457
Generation: 4
New Best Solution Fitness: 87413
Generation: 5
New Best Solution Fitness: 87389
New Best Solution Fitness: 87244
Generation: 6
New Best Solution Fitness: 87179
New Best Solution Fitness: 87095
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 87085
New Best Solution Fitness: 87058
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.377778 
Mean sub-tour choices: 0.666667 
Best Solution Fitness: 87058 
--------------------------------------------- 
