--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87596
New Best Solution Fitness: 87593
Generation: 3
New Best Solution Fitness: 87572
Generation: 4
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 87513
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.566667 
Mean sub-tour choices: 0.766667 
Best Solution Fitness: 87513 
--------------------------------------------- 
