--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 89077
New Best Solution Fitness: 88942
New Best Solution Fitness: 88887
Generation: 3
New Best Solution Fitness: 87981
New Best Solution Fitness: 87926
New Best Solution Fitness: 87907
Generation: 4
New Best Solution Fitness: 87824
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 87822
Generation: 9
Generation: 10
New Best Solution Fitness: 87774
New Best Solution Fitness: 87747
New Best Solution Fitness: 87629
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.755556 
Mean sub-tour choices: 1.02222 
Best Solution Fitness: 87629 
--------------------------------------------- 
