--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88105
New Best Solution Fitness: 88085
New Best Solution Fitness: 88068
Generation: 3
New Best Solution Fitness: 87603
New Best Solution Fitness: 87560
Generation: 4
New Best Solution Fitness: 87539
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.955556 
Mean sub-tour choices: 1.37778 
Best Solution Fitness: 87539 
--------------------------------------------- 
