--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88244
New Best Solution Fitness: 88198
Generation: 3
New Best Solution Fitness: 88185
New Best Solution Fitness: 88170
New Best Solution Fitness: 88115
Generation: 4
New Best Solution Fitness: 88077
New Best Solution Fitness: 88054
Generation: 5
New Best Solution Fitness: 88014
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 87715
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.766667 
Mean sub-tour choices: 1.41111 
Best Solution Fitness: 87715 
--------------------------------------------- 
