--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88574
New Best Solution Fitness: 88486
Generation: 3
New Best Solution Fitness: 87900
New Best Solution Fitness: 87889
Generation: 4
New Best Solution Fitness: 87861
Generation: 5
Generation: 6
New Best Solution Fitness: 87840
Generation: 7
New Best Solution Fitness: 87726
Generation: 8
Generation: 9
New Best Solution Fitness: 87677
New Best Solution Fitness: 87676
Generation: 10
New Best Solution Fitness: 87611
New Best Solution Fitness: 87508
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.577778 
Mean sub-tour choices: 0.944444 
Best Solution Fitness: 87508 
--------------------------------------------- 
