--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88325
New Best Solution Fitness: 88318
Generation: 3
New Best Solution Fitness: 88076
New Best Solution Fitness: 88065
New Best Solution Fitness: 88060
Generation: 4
New Best Solution Fitness: 88008
New Best Solution Fitness: 87997
Generation: 5
New Best Solution Fitness: 87993
Generation: 6
New Best Solution Fitness: 87561
Generation: 7
New Best Solution Fitness: 87560
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.844444 
Mean sub-tour choices: 1.2 
Best Solution Fitness: 87560 
--------------------------------------------- 
