--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88718
New Best Solution Fitness: 88713
Generation: 3
New Best Solution Fitness: 88441
New Best Solution Fitness: 88436
Generation: 4
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 87837
New Best Solution Fitness: 87829
Generation: 9
New Best Solution Fitness: 87766
New Best Solution Fitness: 87765
Generation: 10
New Best Solution Fitness: 87699
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.36667 
Mean sub-tour choices: 1.66667 
Best Solution Fitness: 87699 
--------------------------------------------- 
