--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88363
New Best Solution Fitness: 88324
New Best Solution Fitness: 88288
Generation: 3
New Best Solution Fitness: 88051
Generation: 4
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 87995
Generation: 8
New Best Solution Fitness: 87925
New Best Solution Fitness: 87760
Generation: 9
Generation: 10
New Best Solution Fitness: 87740
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.1 
Mean sub-tour choices: 1.34444 
Best Solution Fitness: 87740 
--------------------------------------------- 
