--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 89044
New Best Solution Fitness: 88979
Generation: 3
New Best Solution Fitness: 88612
New Best Solution Fitness: 88504
Generation: 4
New Best Solution Fitness: 88486
New Best Solution Fitness: 88350
Generation: 5
New Best Solution Fitness: 88346
New Best Solution Fitness: 88335
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 87999
New Best Solution Fitness: 87891
New Best Solution Fitness: 87817
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.744444 
Mean sub-tour choices: 1.1 
Best Solution Fitness: 87817 
--------------------------------------------- 
