--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 89276
New Best Solution Fitness: 89143
Generation: 3
New Best Solution Fitness: 88928
New Best Solution Fitness: 88923
Generation: 4
New Best Solution Fitness: 88690
New Best Solution Fitness: 88669
Generation: 5
New Best Solution Fitness: 88438
Generation: 6
New Best Solution Fitness: 88422
Generation: 7
New Best Solution Fitness: 88103
New Best Solution Fitness: 88032
New Best Solution Fitness: 88016
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.944444 
Mean sub-tour choices: 1.44444 
Best Solution Fitness: 88016 
--------------------------------------------- 
