--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 89418
New Best Solution Fitness: 89397
New Best Solution Fitness: 89396
Generation: 3
New Best Solution Fitness: 89090
New Best Solution Fitness: 89069
Generation: 4
New Best Solution Fitness: 88756
New Best Solution Fitness: 88718
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 88702
Generation: 9
New Best Solution Fitness: 88591
New Best Solution Fitness: 88556
Generation: 10
New Best Solution Fitness: 88272
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.533333 
Mean sub-tour choices: 0.855556 
Best Solution Fitness: 88272 
--------------------------------------------- 
