--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88867
New Best Solution Fitness: 88836
Generation: 3
New Best Solution Fitness: 88795
Generation: 4
New Best Solution Fitness: 88073
Generation: 5
New Best Solution Fitness: 88037
Generation: 6
New Best Solution Fitness: 87781
New Best Solution Fitness: 87707
New Best Solution Fitness: 87652
Generation: 7
New Best Solution Fitness: 87595
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.422222 
Mean sub-tour choices: 0.677778 
Best Solution Fitness: 87595 
--------------------------------------------- 
