--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88016
New Best Solution Fitness: 87977
New Best Solution Fitness: 87954
New Best Solution Fitness: 87793
Generation: 3
New Best Solution Fitness: 87715
Generation: 4
New Best Solution Fitness: 87561
New Best Solution Fitness: 87468
Generation: 5
New Best Solution Fitness: 87443
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.05556 
Mean sub-tour choices: 1.58889 
Best Solution Fitness: 87443 
--------------------------------------------- 
