--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87748
New Best Solution Fitness: 87690
New Best Solution Fitness: 87686
New Best Solution Fitness: 87671
Generation: 3
New Best Solution Fitness: 87604
Generation: 4
New Best Solution Fitness: 87599
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 87491
New Best Solution Fitness: 87486
Generation: 8
New Best Solution Fitness: 87470
Generation: 9
New Best Solution Fitness: 87453
New Best Solution Fitness: 87448
Generation: 10
New Best Solution Fitness: 87434
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.3 
Mean sub-tour choices: 1.54444 
Best Solution Fitness: 87434 
--------------------------------------------- 
