--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88226
New Best Solution Fitness: 88211
New Best Solution Fitness: 88196
New Best Solution Fitness: 88023
Generation: 3
New Best Solution Fitness: 87857
New Best Solution Fitness: 87842
Generation: 4
New Best Solution Fitness: 87814
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.477778 
Mean sub-tour choices: 0.688889 
Best Solution Fitness: 87814 
--------------------------------------------- 
