--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87477
New Best Solution Fitness: 87451
Generation: 3
Generation: 4
New Best Solution Fitness: 87426
New Best Solution Fitness: 87395
Generation: 5
New Best Solution Fitness: 87354
Generation: 6
New Best Solution Fitness: 87208
New Best Solution Fitness: 87201
Generation: 7
New Best Solution Fitness: 87196
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.455556 
Mean sub-tour choices: 0.788889 
Best Solution Fitness: 87196 
--------------------------------------------- 
