--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87985
New Best Solution Fitness: 87939
Generation: 3
New Best Solution Fitness: 87911
New Best Solution Fitness: 87904
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 87813
Generation: 7
New Best Solution Fitness: 87579
New Best Solution Fitness: 87484
New Best Solution Fitness: 87483
New Best Solution Fitness: 87287
Generation: 8
New Best Solution Fitness: 87248
New Best Solution Fitness: 87247
Generation: 9
Generation: 10
New Best Solution Fitness: 87183
New Best Solution Fitness: 87182
New Best Solution Fitness: 87161
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.07778 
Mean sub-tour choices: 1.87778 
Best Solution Fitness: 87161 
--------------------------------------------- 
