--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 90298
Generation: 3
New Best Solution Fitness: 88227
Generation: 4
New Best Solution Fitness: 88017
Generation: 5
Generation: 6
New Best Solution Fitness: 87589
New Best Solution Fitness: 87536
Generation: 7
New Best Solution Fitness: 87484
Generation: 8
New Best Solution Fitness: 87415
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.655556 
Mean sub-tour choices: 0.855556 
Best Solution Fitness: 87415 
--------------------------------------------- 
