--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88266
New Best Solution Fitness: 88112
Generation: 3
New Best Solution Fitness: 87593
New Best Solution Fitness: 87589
New Best Solution Fitness: 87572
Generation: 4
New Best Solution Fitness: 87558
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.02222 
Mean sub-tour choices: 1.44444 
Best Solution Fitness: 87558 
--------------------------------------------- 
