--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88725
New Best Solution Fitness: 88519
New Best Solution Fitness: 88169
Generation: 3
New Best Solution Fitness: 87693
New Best Solution Fitness: 87638
New Best Solution Fitness: 87509
Generation: 4
New Best Solution Fitness: 87424
Generation: 5
Generation: 6
New Best Solution Fitness: 87420
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 87389
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.455556 
Mean sub-tour choices: 0.577778 
Best Solution Fitness: 87389 
--------------------------------------------- 
