--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88172
Generation: 3
New Best Solution Fitness: 87995
New Best Solution Fitness: 87937
Generation: 4
New Best Solution Fitness: 87782
Generation: 5
Generation: 6
New Best Solution Fitness: 87701
New Best Solution Fitness: 87593
New Best Solution Fitness: 87547
Generation: 7
New Best Solution Fitness: 87537
Generation: 8
New Best Solution Fitness: 87525
Generation: 9
New Best Solution Fitness: 87520
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.722222 
Mean sub-tour choices: 1.24444 
Best Solution Fitness: 87520 
--------------------------------------------- 
