--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88142
New Best Solution Fitness: 87977
New Best Solution Fitness: 87957
New Best Solution Fitness: 87787
Generation: 3
New Best Solution Fitness: 87602
Generation: 4
New Best Solution Fitness: 87597
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 87338
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.33333 
Mean sub-tour choices: 1.61111 
Best Solution Fitness: 87338 
--------------------------------------------- 
