--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88518
New Best Solution Fitness: 88496
Generation: 3
New Best Solution Fitness: 88425
New Best Solution Fitness: 88383
Generation: 4
New Best Solution Fitness: 88321
New Best Solution Fitness: 88320
Generation: 5
New Best Solution Fitness: 88300
Generation: 6
New Best Solution Fitness: 88248
New Best Solution Fitness: 88022
New Best Solution Fitness: 88011
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 87958
Generation: 10
New Best Solution Fitness: 87896
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.633333 
Mean sub-tour choices: 1 
Best Solution Fitness: 87896 
--------------------------------------------- 
