--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87581
New Best Solution Fitness: 87547
New Best Solution Fitness: 87542
New Best Solution Fitness: 87536
Generation: 3
New Best Solution Fitness: 87494
New Best Solution Fitness: 87488
New Best Solution Fitness: 87477
Generation: 4
New Best Solution Fitness: 87475
Generation: 5
Generation: 6
New Best Solution Fitness: 87241
New Best Solution Fitness: 87238
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.622222 
Mean sub-tour choices: 0.944444 
Best Solution Fitness: 87238 
--------------------------------------------- 
