--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87971
New Best Solution Fitness: 87954
New Best Solution Fitness: 87939
Generation: 3
New Best Solution Fitness: 87837
New Best Solution Fitness: 87733
Generation: 4
New Best Solution Fitness: 87713
New Best Solution Fitness: 87567
Generation: 5
New Best Solution Fitness: 87531
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.833333 
Mean sub-tour choices: 0.855556 
Best Solution Fitness: 87531 
--------------------------------------------- 
