--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88082
New Best Solution Fitness: 87808
New Best Solution Fitness: 87779
Generation: 3
New Best Solution Fitness: 87734
New Best Solution Fitness: 87696
Generation: 4
New Best Solution Fitness: 87679
Generation: 5
Generation: 6
New Best Solution Fitness: 87645
Generation: 7
Generation: 8
New Best Solution Fitness: 87642
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1 
Mean sub-tour choices: 1.41111 
Best Solution Fitness: 87642 
--------------------------------------------- 
