--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87907
New Best Solution Fitness: 87848
Generation: 3
New Best Solution Fitness: 87351
Generation: 4
New Best Solution Fitness: 87333
Generation: 5
Generation: 6
New Best Solution Fitness: 87265
Generation: 7
New Best Solution Fitness: 87197
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.577778 
Mean sub-tour choices: 0.933333 
Best Solution Fitness: 87197 
--------------------------------------------- 
