--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88759
New Best Solution Fitness: 88727
New Best Solution Fitness: 88541
Generation: 3
New Best Solution Fitness: 88473
New Best Solution Fitness: 88377
New Best Solution Fitness: 88365
Generation: 4
New Best Solution Fitness: 88353
New Best Solution Fitness: 88336
New Best Solution Fitness: 88334
Generation: 5
New Best Solution Fitness: 88317
Generation: 6
New Best Solution Fitness: 88304
New Best Solution Fitness: 88287
Generation: 7
New Best Solution Fitness: 88179
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 88165
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.06667 
Mean sub-tour choices: 1.56667 
Best Solution Fitness: 88165 
--------------------------------------------- 
