--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88672
New Best Solution Fitness: 88661
Generation: 3
New Best Solution Fitness: 88610
New Best Solution Fitness: 88584
Generation: 4
New Best Solution Fitness: 87959
New Best Solution Fitness: 87938
Generation: 5
New Best Solution Fitness: 87701
Generation: 6
New Best Solution Fitness: 87662
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 87643
New Best Solution Fitness: 87631
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.622222 
Mean sub-tour choices: 1.06667 
Best Solution Fitness: 87631 
--------------------------------------------- 
