--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88486
New Best Solution Fitness: 88351
Generation: 3
New Best Solution Fitness: 88117
Generation: 4
New Best Solution Fitness: 88100
Generation: 5
New Best Solution Fitness: 88031
New Best Solution Fitness: 88014
Generation: 6
New Best Solution Fitness: 88005
New Best Solution Fitness: 87830
Generation: 7
New Best Solution Fitness: 87780
Generation: 8
New Best Solution Fitness: 87258
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.2 
Mean sub-tour choices: 1.67778 
Best Solution Fitness: 87258 
--------------------------------------------- 
