--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87987
New Best Solution Fitness: 87963
Generation: 3
New Best Solution Fitness: 87749
New Best Solution Fitness: 87735
Generation: 4
New Best Solution Fitness: 87720
New Best Solution Fitness: 87703
Generation: 5
New Best Solution Fitness: 87699
New Best Solution Fitness: 87689
Generation: 6
New Best Solution Fitness: 87654
New Best Solution Fitness: 87644
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 87597
New Best Solution Fitness: 87368
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.8 
Mean sub-tour choices: 1.2 
Best Solution Fitness: 87368 
--------------------------------------------- 
