--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88243
New Best Solution Fitness: 88166
New Best Solution Fitness: 88001
Generation: 3
New Best Solution Fitness: 87930
Generation: 4
New Best Solution Fitness: 87878
Generation: 5
New Best Solution Fitness: 87755
New Best Solution Fitness: 87703
Generation: 6
New Best Solution Fitness: 87668
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 87642
New Best Solution Fitness: 87631
New Best Solution Fitness: 87621
Generation: 10
New Best Solution Fitness: 87274
New Best Solution Fitness: 87263
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.755556 
Mean sub-tour choices: 1.17778 
Best Solution Fitness: 87263 
--------------------------------------------- 
