--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88314
New Best Solution Fitness: 88309
New Best Solution Fitness: 88249
Generation: 3
New Best Solution Fitness: 88176
New Best Solution Fitness: 88116
Generation: 4
New Best Solution Fitness: 87825
Generation: 5
Generation: 6
New Best Solution Fitness: 87718
New Best Solution Fitness: 87676
Generation: 7
New Best Solution Fitness: 87505
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.611111 
Mean sub-tour choices: 0.8 
Best Solution Fitness: 87505 
--------------------------------------------- 
