--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88180
New Best Solution Fitness: 88080
Generation: 3
New Best Solution Fitness: 87891
Generation: 4
New Best Solution Fitness: 87886
Generation: 5
New Best Solution Fitness: 87875
New Best Solution Fitness: 87859
Generation: 6
New Best Solution Fitness: 87759
Generation: 7
Generation: 8
New Best Solution Fitness: 87462
New Best Solution Fitness: 87401
New Best Solution Fitness: 87399
New Best Solution Fitness: 87384
Generation: 9
New Best Solution Fitness: 87323
New Best Solution Fitness: 87316
New Best Solution Fitness: 87260
Generation: 10
New Best Solution Fitness: 87212
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.433333 
Mean sub-tour choices: 0.711111 
Best Solution Fitness: 87212 
--------------------------------------------- 
