--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87455
New Best Solution Fitness: 87362
Generation: 3
New Best Solution Fitness: 87213
New Best Solution Fitness: 87209
New Best Solution Fitness: 87206
Generation: 4
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.466667 
Mean sub-tour choices: 0.855556 
Best Solution Fitness: 87206 
--------------------------------------------- 
