--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 89041
New Best Solution Fitness: 88606
Generation: 3
New Best Solution Fitness: 88473
New Best Solution Fitness: 88467
Generation: 4
New Best Solution Fitness: 88244
New Best Solution Fitness: 88240
Generation: 5
Generation: 6
New Best Solution Fitness: 87576
Generation: 7
Generation: 8
New Best Solution Fitness: 87482
New Best Solution Fitness: 87369
Generation: 9
New Best Solution Fitness: 87275
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.511111 
Mean sub-tour choices: 0.788889 
Best Solution Fitness: 87275 
--------------------------------------------- 
