--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88208
New Best Solution Fitness: 88091
New Best Solution Fitness: 87963
Generation: 3
New Best Solution Fitness: 87823
New Best Solution Fitness: 87728
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 87692
Generation: 7
New Best Solution Fitness: 87412
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.8 
Mean sub-tour choices: 1.08889 
Best Solution Fitness: 87412 
--------------------------------------------- 
