--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87870
New Best Solution Fitness: 87753
Generation: 3
New Best Solution Fitness: 87698
Generation: 4
New Best Solution Fitness: 87656
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 87569
New Best Solution Fitness: 87471
Generation: 9
New Best Solution Fitness: 87314
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.611111 
Mean sub-tour choices: 1.11111 
Best Solution Fitness: 87314 
--------------------------------------------- 
