--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88099
New Best Solution Fitness: 87929
Generation: 3
New Best Solution Fitness: 87893
Generation: 4
Generation: 5
New Best Solution Fitness: 87891
Generation: 6
New Best Solution Fitness: 87775
Generation: 7
New Best Solution Fitness: 87664
Generation: 8
New Best Solution Fitness: 87643
Generation: 9
Generation: 10
New Best Solution Fitness: 87462
New Best Solution Fitness: 87456
New Best Solution Fitness: 87369
New Best Solution Fitness: 87335
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.8 
Mean sub-tour choices: 1.12222 
Best Solution Fitness: 87335 
--------------------------------------------- 
