--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88133
New Best Solution Fitness: 88101
New Best Solution Fitness: 88077
Generation: 3
New Best Solution Fitness: 87664
New Best Solution Fitness: 87608
Generation: 4
New Best Solution Fitness: 87590
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 87589
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.08889 
Mean sub-tour choices: 1.58889 
Best Solution Fitness: 87589 
--------------------------------------------- 
