--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88433
New Best Solution Fitness: 88429
New Best Solution Fitness: 88417
Generation: 3
New Best Solution Fitness: 88398
New Best Solution Fitness: 88346
Generation: 4
New Best Solution Fitness: 87880
New Best Solution Fitness: 87634
Generation: 5
New Best Solution Fitness: 87595
New Best Solution Fitness: 87543
Generation: 6
New Best Solution Fitness: 87508
New Best Solution Fitness: 87482
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.866667 
Mean sub-tour choices: 1.43333 
Best Solution Fitness: 87482 
--------------------------------------------- 
