--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 87998
New Best Solution Fitness: 87962
New Best Solution Fitness: 87829
New Best Solution Fitness: 87818
Generation: 3
New Best Solution Fitness: 87801
New Best Solution Fitness: 87796
Generation: 4
New Best Solution Fitness: 87753
Generation: 5
New Best Solution Fitness: 87742
Generation: 6
New Best Solution Fitness: 87676
Generation: 7
New Best Solution Fitness: 87632
Generation: 8
New Best Solution Fitness: 87595
Generation: 9
New Best Solution Fitness: 87547
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.855556 
Mean sub-tour choices: 1.45556 
Best Solution Fitness: 87547 
--------------------------------------------- 
