--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88686
Generation: 3
New Best Solution Fitness: 88641
New Best Solution Fitness: 88630
Generation: 4
New Best Solution Fitness: 88595
New Best Solution Fitness: 88582
New Best Solution Fitness: 88539
Generation: 5
New Best Solution Fitness: 88406
New Best Solution Fitness: 88395
Generation: 6
New Best Solution Fitness: 88344
Generation: 7
Generation: 8
New Best Solution Fitness: 88114
Generation: 9
New Best Solution Fitness: 88062
Generation: 10
New Best Solution Fitness: 88058
New Best Solution Fitness: 87950
New Best Solution Fitness: 87935
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.988889 
Mean sub-tour choices: 1.31111 
Best Solution Fitness: 87935 
--------------------------------------------- 
