--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88045
New Best Solution Fitness: 87997
Generation: 3
New Best Solution Fitness: 87996
Generation: 4
Generation: 5
New Best Solution Fitness: 87868
Generation: 6
New Best Solution Fitness: 87859
Generation: 7
Generation: 8
New Best Solution Fitness: 87784
New Best Solution Fitness: 87783
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.411111 
Mean sub-tour choices: 0.744444 
Best Solution Fitness: 87783 
--------------------------------------------- 
