--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 89335
New Best Solution Fitness: 89242
New Best Solution Fitness: 89178
Generation: 3
New Best Solution Fitness: 88791
New Best Solution Fitness: 88727
Generation: 4
New Best Solution Fitness: 88701
New Best Solution Fitness: 88671
New Best Solution Fitness: 88655
Generation: 5
New Best Solution Fitness: 88625
Generation: 6
New Best Solution Fitness: 88597
Generation: 7
New Best Solution Fitness: 88536
New Best Solution Fitness: 88520
Generation: 8
New Best Solution Fitness: 88459
Generation: 9
New Best Solution Fitness: 88238
Generation: 10
New Best Solution Fitness: 87623
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.8 
Mean sub-tour choices: 1.33333 
Best Solution Fitness: 87623 
--------------------------------------------- 
