--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88221
New Best Solution Fitness: 88082
Generation: 3
New Best Solution Fitness: 88052
Generation: 4
New Best Solution Fitness: 87958
Generation: 5
New Best Solution Fitness: 87799
New Best Solution Fitness: 87787
New Best Solution Fitness: 87775
New Best Solution Fitness: 87739
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 87255
Generation: 9
New Best Solution Fitness: 87232
New Best Solution Fitness: 87228
New Best Solution Fitness: 87211
Generation: 10
New Best Solution Fitness: 87205
New Best Solution Fitness: 87181
New Best Solution Fitness: 87105
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.744444 
Mean sub-tour choices: 1.07778 
Best Solution Fitness: 87105 
--------------------------------------------- 
