--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 89251
New Best Solution Fitness: 88449
Generation: 3
New Best Solution Fitness: 88096
Generation: 4
New Best Solution Fitness: 88013
New Best Solution Fitness: 87979
Generation: 5
New Best Solution Fitness: 87963
Generation: 6
New Best Solution Fitness: 87960
New Best Solution Fitness: 87904
Generation: 7
New Best Solution Fitness: 87570
Generation: 8
New Best Solution Fitness: 87530
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.5 
Mean sub-tour choices: 0.744444 
Best Solution Fitness: 87530 
--------------------------------------------- 
