--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88951
New Best Solution Fitness: 88642
Generation: 3
Generation: 4
New Best Solution Fitness: 87786
New Best Solution Fitness: 87781
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 87685
New Best Solution Fitness: 87675
Generation: 8
New Best Solution Fitness: 87605
New Best Solution Fitness: 87592
Generation: 9
New Best Solution Fitness: 87586
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.511111 
Mean sub-tour choices: 0.711111 
Best Solution Fitness: 87586 
--------------------------------------------- 
