--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88347
New Best Solution Fitness: 88184
New Best Solution Fitness: 88028
Generation: 3
New Best Solution Fitness: 87859
Generation: 4
New Best Solution Fitness: 87673
New Best Solution Fitness: 87620
Generation: 5
New Best Solution Fitness: 87595
Generation: 6
New Best Solution Fitness: 87590
Generation: 7
Generation: 8
New Best Solution Fitness: 87480
New Best Solution Fitness: 87449
Generation: 9
Generation: 10
New Best Solution Fitness: 87420
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.555556 
Mean sub-tour choices: 0.788889 
Best Solution Fitness: 87420 
--------------------------------------------- 
