--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 89002
New Best Solution Fitness: 88905
New Best Solution Fitness: 88712
Generation: 3
New Best Solution Fitness: 88658
New Best Solution Fitness: 88652
New Best Solution Fitness: 88415
Generation: 4
Generation: 5
New Best Solution Fitness: 88335
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 88107
Generation: 9
New Best Solution Fitness: 87772
Generation: 10
New Best Solution Fitness: 87730
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.5 
Mean sub-tour choices: 0.733333 
Best Solution Fitness: 87730 
--------------------------------------------- 
