--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\att532.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 88463
New Best Solution Fitness: 88426
New Best Solution Fitness: 88406
New Best Solution Fitness: 88300
Generation: 3
New Best Solution Fitness: 87706
New Best Solution Fitness: 87687
New Best Solution Fitness: 87685
Generation: 4
New Best Solution Fitness: 87666
Generation: 5
Generation: 6
New Best Solution Fitness: 87610
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.855556 
Mean sub-tour choices: 1.18889 
Best Solution Fitness: 87610 
--------------------------------------------- 
