--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59202
New Best Solution Fitness: 59080
New Best Solution Fitness: 59060
New Best Solution Fitness: 59056
Generation: 3
New Best Solution Fitness: 58917
New Best Solution Fitness: 58902
New Best Solution Fitness: 58823
Generation: 4
New Best Solution Fitness: 58802
New Best Solution Fitness: 58786
New Best Solution Fitness: 58780
New Best Solution Fitness: 58765
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.78889 
Mean sub-tour choices: 4.26667 
Best Solution Fitness: 58765 
--------------------------------------------- 
