--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59350
New Best Solution Fitness: 59345
New Best Solution Fitness: 59328
New Best Solution Fitness: 59267
Generation: 3
New Best Solution Fitness: 59171
New Best Solution Fitness: 59147
New Best Solution Fitness: 59144
New Best Solution Fitness: 59131
Generation: 4
New Best Solution Fitness: 58914
New Best Solution Fitness: 58874
Generation: 5
New Best Solution Fitness: 58872
New Best Solution Fitness: 58860
Generation: 6
New Best Solution Fitness: 58858
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 58856
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.94444 
Mean sub-tour choices: 2.8 
Best Solution Fitness: 58856 
--------------------------------------------- 
