--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59702
New Best Solution Fitness: 59666
New Best Solution Fitness: 59448
New Best Solution Fitness: 59386
Generation: 3
New Best Solution Fitness: 59174
New Best Solution Fitness: 59157
New Best Solution Fitness: 59092
Generation: 4
New Best Solution Fitness: 59038
New Best Solution Fitness: 59005
Generation: 5
New Best Solution Fitness: 58963
Generation: 6
Generation: 7
New Best Solution Fitness: 58946
Generation: 8
New Best Solution Fitness: 58818
New Best Solution Fitness: 58801
Generation: 9
Generation: 10
New Best Solution Fitness: 58739
New Best Solution Fitness: 58738
New Best Solution Fitness: 58731
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.21111 
Mean sub-tour choices: 4.13333 
Best Solution Fitness: 58731 
--------------------------------------------- 
