--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 58964
New Best Solution Fitness: 58957
New Best Solution Fitness: 58800
Generation: 3
New Best Solution Fitness: 58592
New Best Solution Fitness: 58591
New Best Solution Fitness: 58590
New Best Solution Fitness: 58589
Generation: 4
New Best Solution Fitness: 58519
New Best Solution Fitness: 58518
New Best Solution Fitness: 58517
Generation: 5
New Best Solution Fitness: 58516
Generation: 6
New Best Solution Fitness: 58498
Generation: 7
New Best Solution Fitness: 58479
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 58460
New Best Solution Fitness: 58429
New Best Solution Fitness: 58427
New Best Solution Fitness: 58253
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.58889 
Mean sub-tour choices: 2.45556 
Best Solution Fitness: 58253 
--------------------------------------------- 
