--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59252
New Best Solution Fitness: 59216
New Best Solution Fitness: 59206
New Best Solution Fitness: 59166
Generation: 3
New Best Solution Fitness: 59009
New Best Solution Fitness: 58995
Generation: 4
New Best Solution Fitness: 58944
New Best Solution Fitness: 58834
Generation: 5
New Best Solution Fitness: 58810
New Best Solution Fitness: 58770
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.06667 
Mean sub-tour choices: 4.44444 
Best Solution Fitness: 58770 
--------------------------------------------- 
