--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 58573
New Best Solution Fitness: 58511
New Best Solution Fitness: 58497
New Best Solution Fitness: 58420
New Best Solution Fitness: 58402
Generation: 3
New Best Solution Fitness: 58310
New Best Solution Fitness: 58266
New Best Solution Fitness: 58256
Generation: 4
New Best Solution Fitness: 58255
New Best Solution Fitness: 58212
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 58168
Generation: 10
New Best Solution Fitness: 58132
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.22222 
Mean sub-tour choices: 3.16667 
Best Solution Fitness: 58132 
--------------------------------------------- 
