--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59195
New Best Solution Fitness: 59077
Generation: 3
New Best Solution Fitness: 59046
New Best Solution Fitness: 59039
New Best Solution Fitness: 59035
Generation: 4
New Best Solution Fitness: 59028
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 59014
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.04444 
Mean sub-tour choices: 2.83333 
Best Solution Fitness: 59014 
--------------------------------------------- 
