--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59217
New Best Solution Fitness: 59139
Generation: 3
New Best Solution Fitness: 58957
New Best Solution Fitness: 58946
New Best Solution Fitness: 58910
Generation: 4
New Best Solution Fitness: 58905
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.35556 
Mean sub-tour choices: 4.3 
Best Solution Fitness: 58905 
--------------------------------------------- 
