--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 58909
New Best Solution Fitness: 58803
New Best Solution Fitness: 58777
Generation: 3
New Best Solution Fitness: 58677
New Best Solution Fitness: 58665
Generation: 4
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.24444 
Mean sub-tour choices: 3.43333 
Best Solution Fitness: 58665 
--------------------------------------------- 
