--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 58817
New Best Solution Fitness: 58803
New Best Solution Fitness: 58795
Generation: 3
New Best Solution Fitness: 58781
New Best Solution Fitness: 58770
New Best Solution Fitness: 58767
New Best Solution Fitness: 58760
New Best Solution Fitness: 58753
New Best Solution Fitness: 58736
Generation: 4
New Best Solution Fitness: 58694
New Best Solution Fitness: 58683
New Best Solution Fitness: 58681
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 5.15556 
Mean sub-tour choices: 6.4 
Best Solution Fitness: 58681 
--------------------------------------------- 
