--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59359
New Best Solution Fitness: 59358
New Best Solution Fitness: 59329
New Best Solution Fitness: 59292
Generation: 3
New Best Solution Fitness: 59265
New Best Solution Fitness: 59264
New Best Solution Fitness: 59263
New Best Solution Fitness: 59208
Generation: 4
New Best Solution Fitness: 59059
Generation: 5
New Best Solution Fitness: 59057
Generation: 6
Generation: 7
New Best Solution Fitness: 58965
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.28889 
Mean sub-tour choices: 3.11111 
Best Solution Fitness: 58965 
--------------------------------------------- 
