--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59362
New Best Solution Fitness: 59123
New Best Solution Fitness: 59120
Generation: 3
New Best Solution Fitness: 58918
New Best Solution Fitness: 58901
New Best Solution Fitness: 58889
Generation: 4
New Best Solution Fitness: 58756
Generation: 5
Generation: 6
New Best Solution Fitness: 58734
Generation: 7
New Best Solution Fitness: 58730
Generation: 8
Generation: 9
New Best Solution Fitness: 58729
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.98889 
Mean sub-tour choices: 4.01111 
Best Solution Fitness: 58729 
--------------------------------------------- 
