--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59666
New Best Solution Fitness: 59625
Generation: 3
New Best Solution Fitness: 59113
New Best Solution Fitness: 59038
New Best Solution Fitness: 59031
Generation: 4
New Best Solution Fitness: 58951
New Best Solution Fitness: 58941
New Best Solution Fitness: 58936
Generation: 5
New Best Solution Fitness: 58759
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 58757
Generation: 10
New Best Solution Fitness: 58729
New Best Solution Fitness: 58719
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.15556 
Mean sub-tour choices: 2.92222 
Best Solution Fitness: 58719 
--------------------------------------------- 
