--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59773
New Best Solution Fitness: 59585
Generation: 3
New Best Solution Fitness: 59423
New Best Solution Fitness: 59418
New Best Solution Fitness: 59381
Generation: 4
New Best Solution Fitness: 59218
New Best Solution Fitness: 59135
Generation: 5
New Best Solution Fitness: 59123
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 59082
Generation: 10
New Best Solution Fitness: 59062
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.87778 
Mean sub-tour choices: 2.76667 
Best Solution Fitness: 59062 
--------------------------------------------- 
