--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59285
New Best Solution Fitness: 59238
New Best Solution Fitness: 59228
Generation: 3
New Best Solution Fitness: 58985
New Best Solution Fitness: 58975
New Best Solution Fitness: 58912
Generation: 4
New Best Solution Fitness: 58908
New Best Solution Fitness: 58896
Generation: 5
New Best Solution Fitness: 58894
New Best Solution Fitness: 58892
Generation: 6
New Best Solution Fitness: 58890
Generation: 7
New Best Solution Fitness: 58888
Generation: 8
New Best Solution Fitness: 58870
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.81111 
Mean sub-tour choices: 4.71111 
Best Solution Fitness: 58870 
--------------------------------------------- 
