--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 60464
New Best Solution Fitness: 60429
New Best Solution Fitness: 60368
New Best Solution Fitness: 60279
New Best Solution Fitness: 60223
Generation: 3
New Best Solution Fitness: 59868
New Best Solution Fitness: 59797
New Best Solution Fitness: 59794
New Best Solution Fitness: 59746
Generation: 4
New Best Solution Fitness: 59635
New Best Solution Fitness: 59616
Generation: 5
New Best Solution Fitness: 59594
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.27778 
Mean sub-tour choices: 4.66667 
Best Solution Fitness: 59594 
--------------------------------------------- 
