--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59424
New Best Solution Fitness: 59398
New Best Solution Fitness: 59351
New Best Solution Fitness: 59302
Generation: 3
New Best Solution Fitness: 59123
New Best Solution Fitness: 59002
Generation: 4
New Best Solution Fitness: 58995
New Best Solution Fitness: 58986
Generation: 5
New Best Solution Fitness: 58922
New Best Solution Fitness: 58897
New Best Solution Fitness: 58883
Generation: 6
New Best Solution Fitness: 58815
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.83333 
Mean sub-tour choices: 4.84444 
Best Solution Fitness: 58815 
--------------------------------------------- 
