--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59241
New Best Solution Fitness: 59129
Generation: 3
New Best Solution Fitness: 59058
New Best Solution Fitness: 59057
New Best Solution Fitness: 59022
New Best Solution Fitness: 59016
New Best Solution Fitness: 59000
Generation: 4
New Best Solution Fitness: 58996
New Best Solution Fitness: 58967
Generation: 5
New Best Solution Fitness: 58913
New Best Solution Fitness: 58884
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.54444 
Mean sub-tour choices: 4.95556 
Best Solution Fitness: 58884 
--------------------------------------------- 
