--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59263
New Best Solution Fitness: 59210
New Best Solution Fitness: 59107
Generation: 3
New Best Solution Fitness: 58956
New Best Solution Fitness: 58935
New Best Solution Fitness: 58894
New Best Solution Fitness: 58838
Generation: 4
New Best Solution Fitness: 58834
New Best Solution Fitness: 58808
New Best Solution Fitness: 58806
Generation: 5
New Best Solution Fitness: 58774
New Best Solution Fitness: 58752
Generation: 6
New Best Solution Fitness: 58737
Generation: 7
New Best Solution Fitness: 58730
New Best Solution Fitness: 58715
New Best Solution Fitness: 58684
Generation: 8
New Best Solution Fitness: 58669
Generation: 9
New Best Solution Fitness: 58665
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 6.4 
Mean sub-tour choices: 7.53333 
Best Solution Fitness: 58665 
--------------------------------------------- 
