--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59413
New Best Solution Fitness: 59317
Generation: 3
New Best Solution Fitness: 58770
New Best Solution Fitness: 58753
New Best Solution Fitness: 58742
New Best Solution Fitness: 58704
Generation: 4
New Best Solution Fitness: 58652
New Best Solution Fitness: 58619
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.63333 
Mean sub-tour choices: 3.62222 
Best Solution Fitness: 58619 
--------------------------------------------- 
