--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 58790
New Best Solution Fitness: 58786
New Best Solution Fitness: 58778
New Best Solution Fitness: 58766
New Best Solution Fitness: 58742
Generation: 3
New Best Solution Fitness: 58529
New Best Solution Fitness: 58517
New Best Solution Fitness: 58491
Generation: 4
New Best Solution Fitness: 58479
New Best Solution Fitness: 58474
New Best Solution Fitness: 58460
Generation: 5
New Best Solution Fitness: 58455
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 58454
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.11111 
Mean sub-tour choices: 3.22222 
Best Solution Fitness: 58454 
--------------------------------------------- 
