--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59572
New Best Solution Fitness: 59482
New Best Solution Fitness: 59445
New Best Solution Fitness: 59441
New Best Solution Fitness: 59425
New Best Solution Fitness: 59423
Generation: 3
New Best Solution Fitness: 59195
New Best Solution Fitness: 59193
New Best Solution Fitness: 59080
Generation: 4
New Best Solution Fitness: 59039
Generation: 5
New Best Solution Fitness: 59017
Generation: 6
New Best Solution Fitness: 58927
Generation: 7
New Best Solution Fitness: 58907
New Best Solution Fitness: 58899
Generation: 8
New Best Solution Fitness: 58884
New Best Solution Fitness: 58656
Generation: 9
New Best Solution Fitness: 58624
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.26667 
Mean sub-tour choices: 3.44444 
Best Solution Fitness: 58624 
--------------------------------------------- 
