--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59333
New Best Solution Fitness: 59241
New Best Solution Fitness: 59227
New Best Solution Fitness: 59118
New Best Solution Fitness: 59037
Generation: 3
New Best Solution Fitness: 58964
New Best Solution Fitness: 58962
New Best Solution Fitness: 58947
New Best Solution Fitness: 58841
New Best Solution Fitness: 58821
Generation: 4
New Best Solution Fitness: 58753
New Best Solution Fitness: 58752
Generation: 5
New Best Solution Fitness: 58626
Generation: 6
New Best Solution Fitness: 58613
New Best Solution Fitness: 58611
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.04444 
Mean sub-tour choices: 5.21111 
Best Solution Fitness: 58611 
--------------------------------------------- 
