--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59452
New Best Solution Fitness: 59402
New Best Solution Fitness: 59383
New Best Solution Fitness: 59380
Generation: 3
New Best Solution Fitness: 58966
New Best Solution Fitness: 58954
New Best Solution Fitness: 58867
Generation: 4
New Best Solution Fitness: 58532
New Best Solution Fitness: 58482
Generation: 5
New Best Solution Fitness: 58417
Generation: 6
New Best Solution Fitness: 58403
Generation: 7
New Best Solution Fitness: 58390
Generation: 8
New Best Solution Fitness: 58360
Generation: 9
New Best Solution Fitness: 58357
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.04444 
Mean sub-tour choices: 2.85556 
Best Solution Fitness: 58357 
--------------------------------------------- 
