--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 58900
New Best Solution Fitness: 58898
New Best Solution Fitness: 58897
New Best Solution Fitness: 58885
New Best Solution Fitness: 58877
New Best Solution Fitness: 58839
Generation: 3
New Best Solution Fitness: 58685
New Best Solution Fitness: 58683
New Best Solution Fitness: 58674
New Best Solution Fitness: 58629
New Best Solution Fitness: 58618
Generation: 4
New Best Solution Fitness: 58616
New Best Solution Fitness: 58607
New Best Solution Fitness: 58606
Generation: 5
New Best Solution Fitness: 58604
Generation: 6
New Best Solution Fitness: 58600
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.68889 
Mean sub-tour choices: 3.93333 
Best Solution Fitness: 58600 
--------------------------------------------- 
