--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59213
New Best Solution Fitness: 59154
Generation: 3
New Best Solution Fitness: 58720
New Best Solution Fitness: 58701
Generation: 4
New Best Solution Fitness: 58496
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.21111 
Mean sub-tour choices: 1.9 
Best Solution Fitness: 58496 
--------------------------------------------- 
