--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59505
New Best Solution Fitness: 59499
New Best Solution Fitness: 59436
Generation: 3
New Best Solution Fitness: 59190
New Best Solution Fitness: 59140
New Best Solution Fitness: 59108
Generation: 4
New Best Solution Fitness: 59106
Generation: 5
New Best Solution Fitness: 58971
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.4 
Mean sub-tour choices: 4.32222 
Best Solution Fitness: 58971 
--------------------------------------------- 
