--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59429
New Best Solution Fitness: 59243
New Best Solution Fitness: 59208
New Best Solution Fitness: 59115
Generation: 3
New Best Solution Fitness: 58992
New Best Solution Fitness: 58905
Generation: 4
New Best Solution Fitness: 58903
New Best Solution Fitness: 58772
Generation: 5
Generation: 6
New Best Solution Fitness: 58732
New Best Solution Fitness: 58531
Generation: 7
New Best Solution Fitness: 58503
New Best Solution Fitness: 58417
Generation: 8
New Best Solution Fitness: 58404
Generation: 9
New Best Solution Fitness: 58394
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.81111 
Mean sub-tour choices: 2.63333 
Best Solution Fitness: 58394 
--------------------------------------------- 
