--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59509
New Best Solution Fitness: 59481
New Best Solution Fitness: 59284
Generation: 3
New Best Solution Fitness: 59016
New Best Solution Fitness: 58988
New Best Solution Fitness: 58905
Generation: 4
New Best Solution Fitness: 58859
New Best Solution Fitness: 58851
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 58836
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.53333 
Mean sub-tour choices: 4.43333 
Best Solution Fitness: 58836 
--------------------------------------------- 
