--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59613
New Best Solution Fitness: 59581
New Best Solution Fitness: 59577
New Best Solution Fitness: 59558
Generation: 3
New Best Solution Fitness: 59055
New Best Solution Fitness: 59053
Generation: 4
New Best Solution Fitness: 58935
New Best Solution Fitness: 58928
Generation: 5
New Best Solution Fitness: 58915
Generation: 6
New Best Solution Fitness: 58910
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 58894
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.63333 
Mean sub-tour choices: 3.33333 
Best Solution Fitness: 58894 
--------------------------------------------- 
