--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59526
New Best Solution Fitness: 59382
New Best Solution Fitness: 59360
New Best Solution Fitness: 59287
Generation: 3
New Best Solution Fitness: 59050
New Best Solution Fitness: 58872
Generation: 4
New Best Solution Fitness: 58838
New Best Solution Fitness: 58835
New Best Solution Fitness: 58828
New Best Solution Fitness: 58825
New Best Solution Fitness: 58765
Generation: 5
New Best Solution Fitness: 58764
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.86667 
Mean sub-tour choices: 5.08889 
Best Solution Fitness: 58764 
--------------------------------------------- 
