--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59136
New Best Solution Fitness: 59085
New Best Solution Fitness: 59075
New Best Solution Fitness: 59056
Generation: 3
New Best Solution Fitness: 58919
New Best Solution Fitness: 58877
Generation: 4
New Best Solution Fitness: 58867
New Best Solution Fitness: 58860
New Best Solution Fitness: 58845
Generation: 5
New Best Solution Fitness: 58838
New Best Solution Fitness: 58832
Generation: 6
New Best Solution Fitness: 58778
Generation: 7
New Best Solution Fitness: 58764
Generation: 8
New Best Solution Fitness: 58762
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.86667 
Mean sub-tour choices: 5.91111 
Best Solution Fitness: 58762 
--------------------------------------------- 
