--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 58932
New Best Solution Fitness: 58914
New Best Solution Fitness: 58855
New Best Solution Fitness: 58810
New Best Solution Fitness: 58788
Generation: 3
New Best Solution Fitness: 58635
New Best Solution Fitness: 58625
New Best Solution Fitness: 58566
New Best Solution Fitness: 58536
Generation: 4
New Best Solution Fitness: 58507
New Best Solution Fitness: 58497
Generation: 5
New Best Solution Fitness: 58487
New Best Solution Fitness: 58428
Generation: 6
New Best Solution Fitness: 58418
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 58403
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.15556 
Mean sub-tour choices: 4.51111 
Best Solution Fitness: 58403 
--------------------------------------------- 
