--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59371
New Best Solution Fitness: 59313
New Best Solution Fitness: 59281
New Best Solution Fitness: 59257
Generation: 3
New Best Solution Fitness: 58966
New Best Solution Fitness: 58953
New Best Solution Fitness: 58916
New Best Solution Fitness: 58889
New Best Solution Fitness: 58766
Generation: 4
New Best Solution Fitness: 58669
New Best Solution Fitness: 58612
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.21111 
Mean sub-tour choices: 4.78889 
Best Solution Fitness: 58612 
--------------------------------------------- 
