--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59311
New Best Solution Fitness: 59279
New Best Solution Fitness: 59265
New Best Solution Fitness: 59252
Generation: 3
New Best Solution Fitness: 59045
New Best Solution Fitness: 58975
New Best Solution Fitness: 58924
Generation: 4
New Best Solution Fitness: 58922
New Best Solution Fitness: 58888
New Best Solution Fitness: 58846
Generation: 5
New Best Solution Fitness: 58841
Generation: 6
New Best Solution Fitness: 58830
Generation: 7
New Best Solution Fitness: 58788
New Best Solution Fitness: 58763
New Best Solution Fitness: 58760
Generation: 8
New Best Solution Fitness: 58748
New Best Solution Fitness: 58698
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.86667 
Mean sub-tour choices: 3.8 
Best Solution Fitness: 58698 
--------------------------------------------- 
