--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59237
New Best Solution Fitness: 59214
New Best Solution Fitness: 59184
New Best Solution Fitness: 59172
Generation: 3
New Best Solution Fitness: 58880
New Best Solution Fitness: 58878
New Best Solution Fitness: 58775
Generation: 4
New Best Solution Fitness: 58773
Generation: 5
Generation: 6
New Best Solution Fitness: 58771
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.54444 
Mean sub-tour choices: 3.63333 
Best Solution Fitness: 58771 
--------------------------------------------- 
