--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 58881
New Best Solution Fitness: 58868
New Best Solution Fitness: 58843
New Best Solution Fitness: 58804
New Best Solution Fitness: 58793
Generation: 3
New Best Solution Fitness: 58621
New Best Solution Fitness: 58589
Generation: 4
New Best Solution Fitness: 58514
New Best Solution Fitness: 58506
New Best Solution Fitness: 58423
Generation: 5
New Best Solution Fitness: 58312
Generation: 6
New Best Solution Fitness: 58240
Generation: 7
New Best Solution Fitness: 58235
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.02222 
Mean sub-tour choices: 5.03333 
Best Solution Fitness: 58235 
--------------------------------------------- 
