--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 60270
New Best Solution Fitness: 60250
New Best Solution Fitness: 60227
New Best Solution Fitness: 60139
Generation: 3
New Best Solution Fitness: 59627
New Best Solution Fitness: 59518
New Best Solution Fitness: 59501
Generation: 4
New Best Solution Fitness: 59399
New Best Solution Fitness: 59392
New Best Solution Fitness: 59386
Generation: 5
New Best Solution Fitness: 59180
New Best Solution Fitness: 59148
New Best Solution Fitness: 59146
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.06667 
Mean sub-tour choices: 2.97778 
Best Solution Fitness: 59146 
--------------------------------------------- 
