--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59617
New Best Solution Fitness: 59556
New Best Solution Fitness: 59548
Generation: 3
New Best Solution Fitness: 58984
New Best Solution Fitness: 58946
New Best Solution Fitness: 58938
New Best Solution Fitness: 58848
Generation: 4
New Best Solution Fitness: 58842
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.22222 
Mean sub-tour choices: 2.98889 
Best Solution Fitness: 58842 
--------------------------------------------- 
