--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59254
New Best Solution Fitness: 59202
New Best Solution Fitness: 59197
New Best Solution Fitness: 59188
Generation: 3
New Best Solution Fitness: 58920
New Best Solution Fitness: 58914
New Best Solution Fitness: 58913
New Best Solution Fitness: 58875
Generation: 4
New Best Solution Fitness: 58844
New Best Solution Fitness: 58814
New Best Solution Fitness: 58680
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 58658
Generation: 8
New Best Solution Fitness: 58651
New Best Solution Fitness: 58646
Generation: 9
New Best Solution Fitness: 58639
Generation: 10
New Best Solution Fitness: 58543
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.66667 
Mean sub-tour choices: 2.52222 
Best Solution Fitness: 58543 
--------------------------------------------- 
