--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59554
New Best Solution Fitness: 59277
New Best Solution Fitness: 59217
New Best Solution Fitness: 59188
Generation: 3
New Best Solution Fitness: 58970
New Best Solution Fitness: 58901
New Best Solution Fitness: 58875
New Best Solution Fitness: 58862
Generation: 4
New Best Solution Fitness: 58856
New Best Solution Fitness: 58815
New Best Solution Fitness: 58787
Generation: 5
New Best Solution Fitness: 58746
Generation: 6
New Best Solution Fitness: 58744
Generation: 7
Generation: 8
New Best Solution Fitness: 58695
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.01111 
Mean sub-tour choices: 3.98889 
Best Solution Fitness: 58695 
--------------------------------------------- 
