--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59570
New Best Solution Fitness: 59467
New Best Solution Fitness: 59400
Generation: 3
New Best Solution Fitness: 59192
New Best Solution Fitness: 59065
Generation: 4
Generation: 5
New Best Solution Fitness: 59059
New Best Solution Fitness: 58949
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.74444 
Mean sub-tour choices: 3.95556 
Best Solution Fitness: 58949 
--------------------------------------------- 
