--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 58926
New Best Solution Fitness: 58923
New Best Solution Fitness: 58916
New Best Solution Fitness: 58899
Generation: 3
New Best Solution Fitness: 58758
New Best Solution Fitness: 58698
Generation: 4
New Best Solution Fitness: 58658
New Best Solution Fitness: 58656
New Best Solution Fitness: 58645
Generation: 5
New Best Solution Fitness: 58643
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 58642
New Best Solution Fitness: 58621
New Best Solution Fitness: 58593
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.37778 
Mean sub-tour choices: 3.13333 
Best Solution Fitness: 58593 
--------------------------------------------- 
