--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59246
New Best Solution Fitness: 59152
New Best Solution Fitness: 59074
Generation: 3
New Best Solution Fitness: 58907
New Best Solution Fitness: 58849
New Best Solution Fitness: 58836
New Best Solution Fitness: 58813
New Best Solution Fitness: 58461
Generation: 4
New Best Solution Fitness: 58460
Generation: 5
Generation: 6
New Best Solution Fitness: 58443
New Best Solution Fitness: 58350
Generation: 7
New Best Solution Fitness: 58349
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.54444 
Mean sub-tour choices: 4.54444 
Best Solution Fitness: 58349 
--------------------------------------------- 
