--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59062
New Best Solution Fitness: 59041
New Best Solution Fitness: 59011
New Best Solution Fitness: 58987
Generation: 3
New Best Solution Fitness: 58551
New Best Solution Fitness: 58525
Generation: 4
New Best Solution Fitness: 58512
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 58497
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.57778 
Mean sub-tour choices: 3.71111 
Best Solution Fitness: 58497 
--------------------------------------------- 
