--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59098
New Best Solution Fitness: 59076
New Best Solution Fitness: 59060
New Best Solution Fitness: 59039
Generation: 3
New Best Solution Fitness: 59031
Generation: 4
New Best Solution Fitness: 59008
New Best Solution Fitness: 59004
Generation: 5
New Best Solution Fitness: 58996
Generation: 6
Generation: 7
New Best Solution Fitness: 58982
Generation: 8
New Best Solution Fitness: 58978
Generation: 9
New Best Solution Fitness: 58945
New Best Solution Fitness: 58931
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.38889 
Mean sub-tour choices: 3.12222 
Best Solution Fitness: 58931 
--------------------------------------------- 
