--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59312
New Best Solution Fitness: 59275
New Best Solution Fitness: 59249
Generation: 3
New Best Solution Fitness: 58985
New Best Solution Fitness: 58977
Generation: 4
New Best Solution Fitness: 58949
New Best Solution Fitness: 58941
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.28889 
Mean sub-tour choices: 4.17778 
Best Solution Fitness: 58941 
--------------------------------------------- 
