--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59302
New Best Solution Fitness: 59274
New Best Solution Fitness: 59266
New Best Solution Fitness: 59130
Generation: 3
New Best Solution Fitness: 58948
New Best Solution Fitness: 58932
New Best Solution Fitness: 58915
Generation: 4
New Best Solution Fitness: 58910
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 58850
Generation: 8
New Best Solution Fitness: 58633
New Best Solution Fitness: 58558
Generation: 9
New Best Solution Fitness: 58516
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.31111 
Mean sub-tour choices: 3.47778 
Best Solution Fitness: 58516 
--------------------------------------------- 
