--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59731
New Best Solution Fitness: 59701
New Best Solution Fitness: 59692
New Best Solution Fitness: 59689
Generation: 3
New Best Solution Fitness: 59394
New Best Solution Fitness: 59392
Generation: 4
New Best Solution Fitness: 59102
New Best Solution Fitness: 59094
Generation: 5
New Best Solution Fitness: 59014
New Best Solution Fitness: 58948
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.3 
Mean sub-tour choices: 3.25556 
Best Solution Fitness: 58948 
--------------------------------------------- 
