--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59685
New Best Solution Fitness: 59635
New Best Solution Fitness: 59554
Generation: 3
New Best Solution Fitness: 59073
New Best Solution Fitness: 59063
New Best Solution Fitness: 59048
Generation: 4
New Best Solution Fitness: 59043
New Best Solution Fitness: 59033
Generation: 5
New Best Solution Fitness: 58998
New Best Solution Fitness: 58954
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.96667 
Mean sub-tour choices: 3.9 
Best Solution Fitness: 58954 
--------------------------------------------- 
