--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59126
New Best Solution Fitness: 59052
New Best Solution Fitness: 59043
Generation: 3
New Best Solution Fitness: 58904
New Best Solution Fitness: 58899
New Best Solution Fitness: 58890
New Best Solution Fitness: 58861
Generation: 4
New Best Solution Fitness: 58853
New Best Solution Fitness: 58846
New Best Solution Fitness: 58836
Generation: 5
New Best Solution Fitness: 58829
New Best Solution Fitness: 58825
Generation: 6
New Best Solution Fitness: 58818
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.81111 
Mean sub-tour choices: 4.95556 
Best Solution Fitness: 58818 
--------------------------------------------- 
