--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59839
New Best Solution Fitness: 59823
New Best Solution Fitness: 59811
New Best Solution Fitness: 59808
Generation: 3
New Best Solution Fitness: 59072
New Best Solution Fitness: 59050
New Best Solution Fitness: 59043
New Best Solution Fitness: 58831
Generation: 4
New Best Solution Fitness: 58785
Generation: 5
Generation: 6
New Best Solution Fitness: 58698
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 58657
Generation: 10
New Best Solution Fitness: 58653
New Best Solution Fitness: 58601
New Best Solution Fitness: 58587
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.5 
Mean sub-tour choices: 2.62222 
Best Solution Fitness: 58587 
--------------------------------------------- 
