--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 58991
New Best Solution Fitness: 58963
New Best Solution Fitness: 58925
Generation: 3
New Best Solution Fitness: 58824
New Best Solution Fitness: 58814
New Best Solution Fitness: 58759
New Best Solution Fitness: 58666
Generation: 4
New Best Solution Fitness: 58631
New Best Solution Fitness: 58621
Generation: 5
New Best Solution Fitness: 58619
Generation: 6
New Best Solution Fitness: 58602
Generation: 7
New Best Solution Fitness: 58598
Generation: 8
New Best Solution Fitness: 58596
Generation: 9
New Best Solution Fitness: 58480
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.16667 
Mean sub-tour choices: 4.07778 
Best Solution Fitness: 58480 
--------------------------------------------- 
