--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59056
New Best Solution Fitness: 59049
New Best Solution Fitness: 59014
New Best Solution Fitness: 58974
New Best Solution Fitness: 58950
Generation: 3
New Best Solution Fitness: 58717
New Best Solution Fitness: 58712
New Best Solution Fitness: 58711
New Best Solution Fitness: 58695
New Best Solution Fitness: 58690
Generation: 4
New Best Solution Fitness: 58568
New Best Solution Fitness: 58551
New Best Solution Fitness: 58543
Generation: 5
Generation: 6
New Best Solution Fitness: 58542
Generation: 7
New Best Solution Fitness: 58535
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.61111 
Mean sub-tour choices: 3.77778 
Best Solution Fitness: 58535 
--------------------------------------------- 
