--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59338
New Best Solution Fitness: 59289
New Best Solution Fitness: 59168
Generation: 3
New Best Solution Fitness: 59011
New Best Solution Fitness: 58888
Generation: 4
New Best Solution Fitness: 58887
New Best Solution Fitness: 58857
Generation: 5
New Best Solution Fitness: 58791
Generation: 6
Generation: 7
New Best Solution Fitness: 58727
New Best Solution Fitness: 58703
Generation: 8
New Best Solution Fitness: 58699
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.5 
Mean sub-tour choices: 2.32222 
Best Solution Fitness: 58699 
--------------------------------------------- 
