--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59581
New Best Solution Fitness: 59529
New Best Solution Fitness: 59458
Generation: 3
New Best Solution Fitness: 59113
New Best Solution Fitness: 59082
New Best Solution Fitness: 59079
New Best Solution Fitness: 59069
Generation: 4
New Best Solution Fitness: 58794
Generation: 5
New Best Solution Fitness: 58793
New Best Solution Fitness: 58791
Generation: 6
New Best Solution Fitness: 58595
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 58576
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.64444 
Mean sub-tour choices: 2.45556 
Best Solution Fitness: 58576 
--------------------------------------------- 
