--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 58908
New Best Solution Fitness: 58877
New Best Solution Fitness: 58860
New Best Solution Fitness: 58837
New Best Solution Fitness: 58692
Generation: 3
New Best Solution Fitness: 58575
New Best Solution Fitness: 58545
New Best Solution Fitness: 58514
Generation: 4
New Best Solution Fitness: 58408
New Best Solution Fitness: 58406
New Best Solution Fitness: 58390
New Best Solution Fitness: 58386
New Best Solution Fitness: 58383
Generation: 5
New Best Solution Fitness: 58365
Generation: 6
New Best Solution Fitness: 58363
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.62222 
Mean sub-tour choices: 5.53333 
Best Solution Fitness: 58363 
--------------------------------------------- 
