--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59097
New Best Solution Fitness: 59045
New Best Solution Fitness: 59037
New Best Solution Fitness: 59008
Generation: 3
New Best Solution Fitness: 58863
New Best Solution Fitness: 58753
New Best Solution Fitness: 58699
Generation: 4
New Best Solution Fitness: 58621
Generation: 5
New Best Solution Fitness: 58613
Generation: 6
New Best Solution Fitness: 58546
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 58430
New Best Solution Fitness: 58421
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.18889 
Mean sub-tour choices: 3.97778 
Best Solution Fitness: 58421 
--------------------------------------------- 
