--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 58870
New Best Solution Fitness: 58704
Generation: 3
New Best Solution Fitness: 58572
New Best Solution Fitness: 58553
New Best Solution Fitness: 58551
Generation: 4
New Best Solution Fitness: 58549
Generation: 5
New Best Solution Fitness: 58548
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.41111 
Mean sub-tour choices: 3.14444 
Best Solution Fitness: 58548 
--------------------------------------------- 
