--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59952
New Best Solution Fitness: 59946
New Best Solution Fitness: 59934
New Best Solution Fitness: 59848
Generation: 3
New Best Solution Fitness: 59108
New Best Solution Fitness: 59102
New Best Solution Fitness: 59086
New Best Solution Fitness: 59060
Generation: 4
New Best Solution Fitness: 59042
Generation: 5
New Best Solution Fitness: 59026
Generation: 6
New Best Solution Fitness: 59017
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 59011
Generation: 10
New Best Solution Fitness: 58947
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.94444 
Mean sub-tour choices: 2.66667 
Best Solution Fitness: 58947 
--------------------------------------------- 
