--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 58746
New Best Solution Fitness: 58709
New Best Solution Fitness: 58690
New Best Solution Fitness: 58689
Generation: 3
New Best Solution Fitness: 58645
New Best Solution Fitness: 58628
New Best Solution Fitness: 58591
New Best Solution Fitness: 58577
New Best Solution Fitness: 58575
Generation: 4
New Best Solution Fitness: 58569
New Best Solution Fitness: 58552
New Best Solution Fitness: 58515
Generation: 5
Generation: 6
New Best Solution Fitness: 58511
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 58506
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.72222 
Mean sub-tour choices: 4.81111 
Best Solution Fitness: 58506 
--------------------------------------------- 
