--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59618
New Best Solution Fitness: 59499
New Best Solution Fitness: 59472
New Best Solution Fitness: 59444
Generation: 3
New Best Solution Fitness: 59055
New Best Solution Fitness: 59023
New Best Solution Fitness: 58926
Generation: 4
New Best Solution Fitness: 58788
New Best Solution Fitness: 58674
Generation: 5
New Best Solution Fitness: 58666
New Best Solution Fitness: 58634
Generation: 6
New Best Solution Fitness: 58626
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.23333 
Mean sub-tour choices: 4.16667 
Best Solution Fitness: 58626 
--------------------------------------------- 
