--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59471
New Best Solution Fitness: 59334
Generation: 3
New Best Solution Fitness: 59137
New Best Solution Fitness: 59114
Generation: 4
New Best Solution Fitness: 59100
Generation: 5
New Best Solution Fitness: 59095
New Best Solution Fitness: 59087
New Best Solution Fitness: 59081
Generation: 6
New Best Solution Fitness: 59080
New Best Solution Fitness: 59072
Generation: 7
New Best Solution Fitness: 59067
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.93333 
Mean sub-tour choices: 2.72222 
Best Solution Fitness: 59067 
--------------------------------------------- 
