--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 60626
New Best Solution Fitness: 60609
New Best Solution Fitness: 60593
New Best Solution Fitness: 60577
New Best Solution Fitness: 60498
Generation: 3
New Best Solution Fitness: 59559
New Best Solution Fitness: 59544
New Best Solution Fitness: 59516
New Best Solution Fitness: 59451
Generation: 4
New Best Solution Fitness: 59449
New Best Solution Fitness: 59391
Generation: 5
Generation: 6
New Best Solution Fitness: 59163
New Best Solution Fitness: 59112
Generation: 7
New Best Solution Fitness: 59025
New Best Solution Fitness: 58983
Generation: 8
Generation: 9
New Best Solution Fitness: 58962
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.34444 
Mean sub-tour choices: 3.07778 
Best Solution Fitness: 58962 
--------------------------------------------- 
