--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 58775
New Best Solution Fitness: 58712
New Best Solution Fitness: 58709
New Best Solution Fitness: 58696
New Best Solution Fitness: 58692
Generation: 3
New Best Solution Fitness: 58657
New Best Solution Fitness: 58650
Generation: 4
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.74444 
Mean sub-tour choices: 4.97778 
Best Solution Fitness: 58650 
--------------------------------------------- 
