--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59338
New Best Solution Fitness: 59260
Generation: 3
New Best Solution Fitness: 59051
Generation: 4
New Best Solution Fitness: 58797
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.25556 
Mean sub-tour choices: 3.42222 
Best Solution Fitness: 58797 
--------------------------------------------- 
