--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59078
New Best Solution Fitness: 59053
New Best Solution Fitness: 59003
New Best Solution Fitness: 58988
Generation: 3
New Best Solution Fitness: 58781
New Best Solution Fitness: 58780
New Best Solution Fitness: 58773
Generation: 4
New Best Solution Fitness: 58750
Generation: 5
New Best Solution Fitness: 58744
Generation: 6
Generation: 7
New Best Solution Fitness: 58570
New Best Solution Fitness: 58548
New Best Solution Fitness: 58541
Generation: 8
New Best Solution Fitness: 58513
New Best Solution Fitness: 58505
Generation: 9
New Best Solution Fitness: 58421
Generation: 10
New Best Solution Fitness: 58402
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.71111 
Mean sub-tour choices: 3.72222 
Best Solution Fitness: 58402 
--------------------------------------------- 
