--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59641
New Best Solution Fitness: 59622
New Best Solution Fitness: 59600
New Best Solution Fitness: 59579
New Best Solution Fitness: 59561
New Best Solution Fitness: 59539
Generation: 3
New Best Solution Fitness: 59009
New Best Solution Fitness: 58977
Generation: 4
New Best Solution Fitness: 58963
New Best Solution Fitness: 58958
Generation: 5
New Best Solution Fitness: 58921
Generation: 6
New Best Solution Fitness: 58912
Generation: 7
New Best Solution Fitness: 58836
Generation: 8
New Best Solution Fitness: 58792
New Best Solution Fitness: 58732
Generation: 9
New Best Solution Fitness: 58688
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.23333 
Mean sub-tour choices: 3.34444 
Best Solution Fitness: 58688 
--------------------------------------------- 
