--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59356
New Best Solution Fitness: 59288
New Best Solution Fitness: 59163
New Best Solution Fitness: 59049
New Best Solution Fitness: 58814
Generation: 3
New Best Solution Fitness: 58696
New Best Solution Fitness: 58692
Generation: 4
New Best Solution Fitness: 58628
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.75556 
Mean sub-tour choices: 3.64444 
Best Solution Fitness: 58628 
--------------------------------------------- 
