--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59365
New Best Solution Fitness: 59266
New Best Solution Fitness: 59244
New Best Solution Fitness: 59229
Generation: 3
New Best Solution Fitness: 58971
New Best Solution Fitness: 58935
New Best Solution Fitness: 58900
Generation: 4
New Best Solution Fitness: 58891
Generation: 5
New Best Solution Fitness: 58845
Generation: 6
Generation: 7
New Best Solution Fitness: 58809
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.01111 
Mean sub-tour choices: 5.22222 
Best Solution Fitness: 58809 
--------------------------------------------- 
