--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59724
New Best Solution Fitness: 59709
New Best Solution Fitness: 59688
New Best Solution Fitness: 59684
Generation: 3
New Best Solution Fitness: 59461
New Best Solution Fitness: 59445
New Best Solution Fitness: 59441
New Best Solution Fitness: 59428
New Best Solution Fitness: 59304
Generation: 4
New Best Solution Fitness: 59282
New Best Solution Fitness: 59265
Generation: 5
New Best Solution Fitness: 59082
New Best Solution Fitness: 59080
New Best Solution Fitness: 59076
Generation: 6
New Best Solution Fitness: 59071
New Best Solution Fitness: 59070
Generation: 7
New Best Solution Fitness: 59066
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.78889 
Mean sub-tour choices: 3.71111 
Best Solution Fitness: 59066 
--------------------------------------------- 
