--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59247
New Best Solution Fitness: 59213
New Best Solution Fitness: 59150
Generation: 3
New Best Solution Fitness: 59076
New Best Solution Fitness: 59073
New Best Solution Fitness: 58808
Generation: 4
New Best Solution Fitness: 58804
New Best Solution Fitness: 58803
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.36667 
Mean sub-tour choices: 2.3 
Best Solution Fitness: 58803 
--------------------------------------------- 
