--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59615
New Best Solution Fitness: 59577
Generation: 3
New Best Solution Fitness: 59391
New Best Solution Fitness: 59371
New Best Solution Fitness: 59299
Generation: 4
New Best Solution Fitness: 59255
New Best Solution Fitness: 59250
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 59218
Generation: 8
New Best Solution Fitness: 59170
New Best Solution Fitness: 59138
New Best Solution Fitness: 59131
New Best Solution Fitness: 59111
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.12222 
Mean sub-tour choices: 3.11111 
Best Solution Fitness: 59111 
--------------------------------------------- 
