--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59777
New Best Solution Fitness: 59673
New Best Solution Fitness: 59634
Generation: 3
New Best Solution Fitness: 58941
New Best Solution Fitness: 58847
Generation: 4
New Best Solution Fitness: 58843
New Best Solution Fitness: 58834
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 58734
New Best Solution Fitness: 58712
New Best Solution Fitness: 58698
New Best Solution Fitness: 58695
Generation: 8
New Best Solution Fitness: 58688
New Best Solution Fitness: 58681
New Best Solution Fitness: 58568
Generation: 9
New Best Solution Fitness: 58554
New Best Solution Fitness: 58545
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.85556 
Mean sub-tour choices: 4.06667 
Best Solution Fitness: 58545 
--------------------------------------------- 
