--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 58809
New Best Solution Fitness: 58771
New Best Solution Fitness: 58749
New Best Solution Fitness: 58635
Generation: 3
New Best Solution Fitness: 58527
New Best Solution Fitness: 58504
Generation: 4
New Best Solution Fitness: 58503
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.77778 
Mean sub-tour choices: 3.57778 
Best Solution Fitness: 58503 
--------------------------------------------- 
