--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59923
New Best Solution Fitness: 59802
Generation: 3
New Best Solution Fitness: 59189
New Best Solution Fitness: 59120
New Best Solution Fitness: 59114
Generation: 4
New Best Solution Fitness: 58979
New Best Solution Fitness: 58976
New Best Solution Fitness: 58964
Generation: 5
New Best Solution Fitness: 58908
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 58714
New Best Solution Fitness: 58663
New Best Solution Fitness: 58660
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.74444 
Mean sub-tour choices: 2.41111 
Best Solution Fitness: 58660 
--------------------------------------------- 
