--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 60136
New Best Solution Fitness: 60110
New Best Solution Fitness: 60095
Generation: 3
New Best Solution Fitness: 59459
New Best Solution Fitness: 59258
Generation: 4
New Best Solution Fitness: 59131
New Best Solution Fitness: 59127
Generation: 5
New Best Solution Fitness: 59059
New Best Solution Fitness: 59045
Generation: 6
New Best Solution Fitness: 58718
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.18889 
Mean sub-tour choices: 3.08889 
Best Solution Fitness: 58718 
--------------------------------------------- 
