--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 60873
New Best Solution Fitness: 60712
New Best Solution Fitness: 60691
Generation: 3
New Best Solution Fitness: 59190
New Best Solution Fitness: 59178
New Best Solution Fitness: 59138
Generation: 4
New Best Solution Fitness: 59082
New Best Solution Fitness: 59069
Generation: 5
New Best Solution Fitness: 59064
Generation: 6
New Best Solution Fitness: 59011
New Best Solution Fitness: 58951
Generation: 7
New Best Solution Fitness: 58867
New Best Solution Fitness: 58851
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.71111 
Mean sub-tour choices: 2.5 
Best Solution Fitness: 58851 
--------------------------------------------- 
