--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59419
New Best Solution Fitness: 59395
New Best Solution Fitness: 59378
Generation: 3
New Best Solution Fitness: 59243
New Best Solution Fitness: 59231
New Best Solution Fitness: 59224
Generation: 4
Generation: 5
New Best Solution Fitness: 59215
New Best Solution Fitness: 59177
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.74444 
Mean sub-tour choices: 3.77778 
Best Solution Fitness: 59177 
--------------------------------------------- 
