--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59260
New Best Solution Fitness: 59168
Generation: 3
New Best Solution Fitness: 59081
New Best Solution Fitness: 59004
Generation: 4
New Best Solution Fitness: 58987
New Best Solution Fitness: 58975
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 58895
Generation: 9
New Best Solution Fitness: 58851
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.15556 
Mean sub-tour choices: 3.26667 
Best Solution Fitness: 58851 
--------------------------------------------- 
