--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59328
New Best Solution Fitness: 59214
New Best Solution Fitness: 59190
Generation: 3
New Best Solution Fitness: 58805
New Best Solution Fitness: 58797
New Best Solution Fitness: 58718
New Best Solution Fitness: 58687
Generation: 4
New Best Solution Fitness: 58600
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 58591
Generation: 9
New Best Solution Fitness: 58583
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.55556 
Mean sub-tour choices: 3.48889 
Best Solution Fitness: 58583 
--------------------------------------------- 
