--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59355
New Best Solution Fitness: 59307
New Best Solution Fitness: 59305
New Best Solution Fitness: 59281
Generation: 3
New Best Solution Fitness: 58989
New Best Solution Fitness: 58987
Generation: 4
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 58957
Generation: 8
New Best Solution Fitness: 58956
Generation: 9
Generation: 10
New Best Solution Fitness: 58938
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.3 
Mean sub-tour choices: 1.85556 
Best Solution Fitness: 58938 
--------------------------------------------- 
