--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59655
New Best Solution Fitness: 59529
New Best Solution Fitness: 59527
New Best Solution Fitness: 59519
New Best Solution Fitness: 59504
New Best Solution Fitness: 59494
Generation: 3
New Best Solution Fitness: 59420
New Best Solution Fitness: 59383
New Best Solution Fitness: 59172
Generation: 4
New Best Solution Fitness: 59140
New Best Solution Fitness: 59138
Generation: 5
New Best Solution Fitness: 59106
Generation: 6
Generation: 7
New Best Solution Fitness: 59105
New Best Solution Fitness: 59066
Generation: 8
New Best Solution Fitness: 58826
New Best Solution Fitness: 58632
Generation: 9
New Best Solution Fitness: 58628
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.08889 
Mean sub-tour choices: 4.06667 
Best Solution Fitness: 58628 
--------------------------------------------- 
