--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59330
New Best Solution Fitness: 59314
New Best Solution Fitness: 59175
Generation: 3
New Best Solution Fitness: 59104
New Best Solution Fitness: 59082
New Best Solution Fitness: 59068
New Best Solution Fitness: 59066
Generation: 4
New Best Solution Fitness: 58847
New Best Solution Fitness: 58804
Generation: 5
New Best Solution Fitness: 58799
Generation: 6
New Best Solution Fitness: 58745
Generation: 7
New Best Solution Fitness: 58715
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.16667 
Mean sub-tour choices: 4.23333 
Best Solution Fitness: 58715 
--------------------------------------------- 
