--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59431
New Best Solution Fitness: 59395
New Best Solution Fitness: 59383
New Best Solution Fitness: 59378
New Best Solution Fitness: 59375
Generation: 3
New Best Solution Fitness: 59143
New Best Solution Fitness: 59141
New Best Solution Fitness: 59116
New Best Solution Fitness: 59115
Generation: 4
New Best Solution Fitness: 59096
Generation: 5
Generation: 6
New Best Solution Fitness: 58984
Generation: 7
New Best Solution Fitness: 58956
New Best Solution Fitness: 58926
Generation: 8
New Best Solution Fitness: 58913
New Best Solution Fitness: 58875
Generation: 9
New Best Solution Fitness: 58873
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.65556 
Mean sub-tour choices: 3.72222 
Best Solution Fitness: 58873 
--------------------------------------------- 
