--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59311
New Best Solution Fitness: 59185
Generation: 3
New Best Solution Fitness: 59088
New Best Solution Fitness: 59084
New Best Solution Fitness: 59073
New Best Solution Fitness: 59067
Generation: 4
New Best Solution Fitness: 59052
Generation: 5
New Best Solution Fitness: 59051
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.35556 
Mean sub-tour choices: 4.32222 
Best Solution Fitness: 59051 
--------------------------------------------- 
