--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59135
New Best Solution Fitness: 59116
New Best Solution Fitness: 59081
Generation: 3
New Best Solution Fitness: 58859
Generation: 4
New Best Solution Fitness: 58794
Generation: 5
New Best Solution Fitness: 58689
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.61111 
Mean sub-tour choices: 2.41111 
Best Solution Fitness: 58689 
--------------------------------------------- 
