--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59200
New Best Solution Fitness: 59176
Generation: 3
New Best Solution Fitness: 59175
New Best Solution Fitness: 59174
New Best Solution Fitness: 59073
Generation: 4
New Best Solution Fitness: 59068
New Best Solution Fitness: 59049
New Best Solution Fitness: 59047
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 58952
New Best Solution Fitness: 58930
New Best Solution Fitness: 58913
Generation: 9
New Best Solution Fitness: 58910
New Best Solution Fitness: 58908
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.93333 
Mean sub-tour choices: 3.06667 
Best Solution Fitness: 58908 
--------------------------------------------- 
