--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 58793
New Best Solution Fitness: 58763
New Best Solution Fitness: 58737
New Best Solution Fitness: 58649
Generation: 3
New Best Solution Fitness: 58605
New Best Solution Fitness: 58604
New Best Solution Fitness: 58603
Generation: 4
New Best Solution Fitness: 58602
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.67778 
Mean sub-tour choices: 3.57778 
Best Solution Fitness: 58602 
--------------------------------------------- 
