--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59032
New Best Solution Fitness: 58959
New Best Solution Fitness: 58929
New Best Solution Fitness: 58908
New Best Solution Fitness: 58869
Generation: 3
New Best Solution Fitness: 58718
New Best Solution Fitness: 58696
New Best Solution Fitness: 58693
New Best Solution Fitness: 58687
New Best Solution Fitness: 58683
Generation: 4
New Best Solution Fitness: 58680
New Best Solution Fitness: 58614
Generation: 5
New Best Solution Fitness: 58607
New Best Solution Fitness: 58604
Generation: 6
Generation: 7
New Best Solution Fitness: 58474
New Best Solution Fitness: 58460
New Best Solution Fitness: 58456
Generation: 8
New Best Solution Fitness: 58444
Generation: 9
New Best Solution Fitness: 58443
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.68889 
Mean sub-tour choices: 5.05556 
Best Solution Fitness: 58443 
--------------------------------------------- 
