--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59246
New Best Solution Fitness: 59156
New Best Solution Fitness: 59107
Generation: 3
New Best Solution Fitness: 59041
New Best Solution Fitness: 59039
New Best Solution Fitness: 58978
New Best Solution Fitness: 58966
Generation: 4
New Best Solution Fitness: 58907
New Best Solution Fitness: 58905
Generation: 5
New Best Solution Fitness: 58904
Generation: 6
New Best Solution Fitness: 58897
Generation: 7
New Best Solution Fitness: 58895
Generation: 8
New Best Solution Fitness: 58890
New Best Solution Fitness: 58877
Generation: 9
New Best Solution Fitness: 58876
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.97778 
Mean sub-tour choices: 3.94444 
Best Solution Fitness: 58876 
--------------------------------------------- 
