--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59445
New Best Solution Fitness: 59427
New Best Solution Fitness: 59425
New Best Solution Fitness: 59294
New Best Solution Fitness: 59285
Generation: 3
New Best Solution Fitness: 59094
New Best Solution Fitness: 59072
New Best Solution Fitness: 59030
New Best Solution Fitness: 58966
Generation: 4
New Best Solution Fitness: 58916
New Best Solution Fitness: 58915
New Best Solution Fitness: 58894
Generation: 5
New Best Solution Fitness: 58885
New Best Solution Fitness: 58862
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 58851
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.15556 
Mean sub-tour choices: 4.02222 
Best Solution Fitness: 58851 
--------------------------------------------- 
