--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59771
New Best Solution Fitness: 59709
New Best Solution Fitness: 59158
Generation: 3
New Best Solution Fitness: 59111
New Best Solution Fitness: 59106
New Best Solution Fitness: 58951
Generation: 4
New Best Solution Fitness: 58935
New Best Solution Fitness: 58779
Generation: 5
New Best Solution Fitness: 58720
New Best Solution Fitness: 58692
Generation: 6
New Best Solution Fitness: 58691
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 58677
Generation: 10
New Best Solution Fitness: 58675
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.12222 
Mean sub-tour choices: 3.17778 
Best Solution Fitness: 58675 
--------------------------------------------- 
