--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59648
New Best Solution Fitness: 59591
New Best Solution Fitness: 59569
Generation: 3
New Best Solution Fitness: 59230
New Best Solution Fitness: 59203
New Best Solution Fitness: 59190
Generation: 4
New Best Solution Fitness: 59129
Generation: 5
New Best Solution Fitness: 59117
New Best Solution Fitness: 59106
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 59078
New Best Solution Fitness: 59062
Generation: 10
New Best Solution Fitness: 59000
New Best Solution Fitness: 58973
New Best Solution Fitness: 58966
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.82222 
Mean sub-tour choices: 2.66667 
Best Solution Fitness: 58966 
--------------------------------------------- 
