--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59712
New Best Solution Fitness: 59661
New Best Solution Fitness: 59648
New Best Solution Fitness: 59602
Generation: 3
New Best Solution Fitness: 58881
New Best Solution Fitness: 58873
New Best Solution Fitness: 58856
Generation: 4
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.2 
Mean sub-tour choices: 4.48889 
Best Solution Fitness: 58856 
--------------------------------------------- 
