--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 58954
New Best Solution Fitness: 58920
New Best Solution Fitness: 58887
New Best Solution Fitness: 58867
Generation: 3
New Best Solution Fitness: 58788
New Best Solution Fitness: 58763
Generation: 4
New Best Solution Fitness: 58761
New Best Solution Fitness: 58758
New Best Solution Fitness: 58740
New Best Solution Fitness: 58738
Generation: 5
New Best Solution Fitness: 58724
New Best Solution Fitness: 58721
Generation: 6
New Best Solution Fitness: 58715
Generation: 7
New Best Solution Fitness: 58664
New Best Solution Fitness: 58612
Generation: 8
New Best Solution Fitness: 58600
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.18889 
Mean sub-tour choices: 4.52222 
Best Solution Fitness: 58600 
--------------------------------------------- 
