--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59177
New Best Solution Fitness: 59129
New Best Solution Fitness: 59080
New Best Solution Fitness: 59074
Generation: 3
New Best Solution Fitness: 58967
New Best Solution Fitness: 58951
Generation: 4
New Best Solution Fitness: 58949
Generation: 5
Generation: 6
New Best Solution Fitness: 58778
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 58568
New Best Solution Fitness: 58546
New Best Solution Fitness: 58531
Generation: 10
New Best Solution Fitness: 58496
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.78889 
Mean sub-tour choices: 2.53333 
Best Solution Fitness: 58496 
--------------------------------------------- 
