--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59733
New Best Solution Fitness: 59714
New Best Solution Fitness: 59532
New Best Solution Fitness: 59531
New Best Solution Fitness: 59348
Generation: 3
New Best Solution Fitness: 59133
New Best Solution Fitness: 59116
Generation: 4
New Best Solution Fitness: 59078
Generation: 5
Generation: 6
New Best Solution Fitness: 59057
Generation: 7
New Best Solution Fitness: 59047
New Best Solution Fitness: 59026
Generation: 8
New Best Solution Fitness: 59025
Generation: 9
Generation: 10
New Best Solution Fitness: 59017
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.82222 
Mean sub-tour choices: 2.5 
Best Solution Fitness: 59017 
--------------------------------------------- 
