--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59182
New Best Solution Fitness: 59134
New Best Solution Fitness: 59097
Generation: 3
New Best Solution Fitness: 58780
New Best Solution Fitness: 58778
Generation: 4
New Best Solution Fitness: 58752
New Best Solution Fitness: 58751
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 58715
New Best Solution Fitness: 58679
New Best Solution Fitness: 58626
Generation: 10
New Best Solution Fitness: 58622
New Best Solution Fitness: 58621
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.06667 
Mean sub-tour choices: 2.78889 
Best Solution Fitness: 58621 
--------------------------------------------- 
