--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59521
New Best Solution Fitness: 59499
New Best Solution Fitness: 59362
New Best Solution Fitness: 59197
New Best Solution Fitness: 59195
Generation: 3
New Best Solution Fitness: 58915
New Best Solution Fitness: 58897
New Best Solution Fitness: 58880
Generation: 4
New Best Solution Fitness: 58734
New Best Solution Fitness: 58724
Generation: 5
New Best Solution Fitness: 58696
Generation: 6
New Best Solution Fitness: 58620
Generation: 7
New Best Solution Fitness: 58568
Generation: 8
New Best Solution Fitness: 58564
New Best Solution Fitness: 58547
Generation: 9
Generation: 10
New Best Solution Fitness: 58545
New Best Solution Fitness: 58401
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.41111 
Mean sub-tour choices: 1.93333 
Best Solution Fitness: 58401 
--------------------------------------------- 
