--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59504
New Best Solution Fitness: 59477
New Best Solution Fitness: 59476
New Best Solution Fitness: 59461
New Best Solution Fitness: 59419
Generation: 3
New Best Solution Fitness: 59126
New Best Solution Fitness: 59111
New Best Solution Fitness: 59106
Generation: 4
New Best Solution Fitness: 58971
New Best Solution Fitness: 58965
Generation: 5
Generation: 6
New Best Solution Fitness: 58725
Generation: 7
New Best Solution Fitness: 58451
New Best Solution Fitness: 58384
Generation: 8
New Best Solution Fitness: 58376
Generation: 9
New Best Solution Fitness: 58340
Generation: 10
New Best Solution Fitness: 58188
New Best Solution Fitness: 58185
New Best Solution Fitness: 58157
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.97778 
Mean sub-tour choices: 2.66667 
Best Solution Fitness: 58157 
--------------------------------------------- 
