--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59086
New Best Solution Fitness: 59057
New Best Solution Fitness: 58961
New Best Solution Fitness: 58951
New Best Solution Fitness: 58923
Generation: 3
New Best Solution Fitness: 58839
New Best Solution Fitness: 58827
Generation: 4
New Best Solution Fitness: 58809
New Best Solution Fitness: 58757
Generation: 5
New Best Solution Fitness: 58725
Generation: 6
New Best Solution Fitness: 58711
Generation: 7
New Best Solution Fitness: 58618
New Best Solution Fitness: 58601
Generation: 8
New Best Solution Fitness: 58599
Generation: 9
New Best Solution Fitness: 58545
Generation: 10
New Best Solution Fitness: 58530
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.6 
Mean sub-tour choices: 2.15556 
Best Solution Fitness: 58530 
--------------------------------------------- 
