--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59844
New Best Solution Fitness: 59833
New Best Solution Fitness: 59763
New Best Solution Fitness: 59753
New Best Solution Fitness: 59722
Generation: 3
New Best Solution Fitness: 59615
New Best Solution Fitness: 59610
New Best Solution Fitness: 59442
Generation: 4
New Best Solution Fitness: 59261
New Best Solution Fitness: 59256
Generation: 5
New Best Solution Fitness: 58958
Generation: 6
New Best Solution Fitness: 58934
New Best Solution Fitness: 58863
Generation: 7
New Best Solution Fitness: 58846
New Best Solution Fitness: 58771
Generation: 8
New Best Solution Fitness: 58749
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.56667 
Mean sub-tour choices: 2.04444 
Best Solution Fitness: 58749 
--------------------------------------------- 
