--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 58908
New Best Solution Fitness: 58708
New Best Solution Fitness: 58703
New Best Solution Fitness: 58699
Generation: 3
New Best Solution Fitness: 58555
New Best Solution Fitness: 58551
New Best Solution Fitness: 58508
Generation: 4
New Best Solution Fitness: 58495
Generation: 5
Generation: 6
New Best Solution Fitness: 58428
Generation: 7
New Best Solution Fitness: 58405
Generation: 8
New Best Solution Fitness: 58367
New Best Solution Fitness: 58365
Generation: 9
New Best Solution Fitness: 58348
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.61111 
Mean sub-tour choices: 2.25556 
Best Solution Fitness: 58348 
--------------------------------------------- 
