--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59161
New Best Solution Fitness: 59153
New Best Solution Fitness: 59118
New Best Solution Fitness: 59052
New Best Solution Fitness: 59039
Generation: 3
New Best Solution Fitness: 58714
New Best Solution Fitness: 58704
New Best Solution Fitness: 58524
Generation: 4
New Best Solution Fitness: 58260
New Best Solution Fitness: 58231
Generation: 5
New Best Solution Fitness: 58223
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.6 
Mean sub-tour choices: 2.17778 
Best Solution Fitness: 58223 
--------------------------------------------- 
