--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59948
New Best Solution Fitness: 59889
New Best Solution Fitness: 59867
New Best Solution Fitness: 59840
Generation: 3
New Best Solution Fitness: 59366
New Best Solution Fitness: 59345
New Best Solution Fitness: 59328
Generation: 4
New Best Solution Fitness: 59309
New Best Solution Fitness: 59299
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 59289
New Best Solution Fitness: 59247
Generation: 8
New Best Solution Fitness: 59192
New Best Solution Fitness: 59189
New Best Solution Fitness: 59173
Generation: 9
New Best Solution Fitness: 59134
New Best Solution Fitness: 59111
Generation: 10
New Best Solution Fitness: 59028
New Best Solution Fitness: 59022
New Best Solution Fitness: 59009
New Best Solution Fitness: 58988
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.11111 
Mean sub-tour choices: 2.78889 
Best Solution Fitness: 58988 
--------------------------------------------- 
