--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59077
New Best Solution Fitness: 58967
New Best Solution Fitness: 58962
Generation: 3
New Best Solution Fitness: 58621
New Best Solution Fitness: 58611
New Best Solution Fitness: 58591
Generation: 4
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 58569
New Best Solution Fitness: 58567
Generation: 10
New Best Solution Fitness: 58485
New Best Solution Fitness: 58483
New Best Solution Fitness: 58473
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.72222 
Mean sub-tour choices: 2.31111 
Best Solution Fitness: 58473 
--------------------------------------------- 
