--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59461
New Best Solution Fitness: 59305
Generation: 3
New Best Solution Fitness: 59045
New Best Solution Fitness: 58958
Generation: 4
New Best Solution Fitness: 58519
New Best Solution Fitness: 58518
New Best Solution Fitness: 58423
Generation: 5
Generation: 6
New Best Solution Fitness: 58422
Generation: 7
New Best Solution Fitness: 58384
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 58377
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.96667 
Mean sub-tour choices: 2.63333 
Best Solution Fitness: 58377 
--------------------------------------------- 
