--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59011
New Best Solution Fitness: 58921
New Best Solution Fitness: 58897
New Best Solution Fitness: 58887
Generation: 3
New Best Solution Fitness: 58777
New Best Solution Fitness: 58759
Generation: 4
New Best Solution Fitness: 58751
New Best Solution Fitness: 58748
Generation: 5
Generation: 6
New Best Solution Fitness: 58706
Generation: 7
New Best Solution Fitness: 58562
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 58548
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.88889 
Mean sub-tour choices: 2.54444 
Best Solution Fitness: 58548 
--------------------------------------------- 
