--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59157
New Best Solution Fitness: 59140
New Best Solution Fitness: 59027
New Best Solution Fitness: 59023
Generation: 3
New Best Solution Fitness: 58937
New Best Solution Fitness: 58925
New Best Solution Fitness: 58875
New Best Solution Fitness: 58861
New Best Solution Fitness: 58839
New Best Solution Fitness: 58772
Generation: 4
New Best Solution Fitness: 58737
New Best Solution Fitness: 58601
Generation: 5
New Best Solution Fitness: 58593
New Best Solution Fitness: 58589
Generation: 6
New Best Solution Fitness: 58581
New Best Solution Fitness: 58577
Generation: 7
New Best Solution Fitness: 58569
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.61111 
Mean sub-tour choices: 3.48889 
Best Solution Fitness: 58569 
--------------------------------------------- 
