--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59724
New Best Solution Fitness: 59573
New Best Solution Fitness: 59571
Generation: 3
New Best Solution Fitness: 59087
New Best Solution Fitness: 59031
New Best Solution Fitness: 59002
Generation: 4
New Best Solution Fitness: 58818
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 58713
Generation: 8
New Best Solution Fitness: 58652
Generation: 9
Generation: 10
New Best Solution Fitness: 58560
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.73333 
Mean sub-tour choices: 3.48889 
Best Solution Fitness: 58560 
--------------------------------------------- 
