--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59026
New Best Solution Fitness: 58966
New Best Solution Fitness: 58935
Generation: 3
New Best Solution Fitness: 58669
New Best Solution Fitness: 58583
Generation: 4
New Best Solution Fitness: 58565
Generation: 5
New Best Solution Fitness: 58526
New Best Solution Fitness: 58430
Generation: 6
New Best Solution Fitness: 58416
Generation: 7
Generation: 8
New Best Solution Fitness: 58413
Generation: 9
New Best Solution Fitness: 58411
New Best Solution Fitness: 58408
Generation: 10
New Best Solution Fitness: 58389
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.61111 
Mean sub-tour choices: 2.18889 
Best Solution Fitness: 58389 
--------------------------------------------- 
