--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59796
New Best Solution Fitness: 59763
New Best Solution Fitness: 59730
Generation: 3
New Best Solution Fitness: 59246
New Best Solution Fitness: 59234
Generation: 4
New Best Solution Fitness: 59054
New Best Solution Fitness: 59047
Generation: 5
New Best Solution Fitness: 58994
Generation: 6
New Best Solution Fitness: 58993
Generation: 7
New Best Solution Fitness: 58929
New Best Solution Fitness: 58899
New Best Solution Fitness: 58898
Generation: 8
New Best Solution Fitness: 58897
Generation: 9
New Best Solution Fitness: 58882
Generation: 10
New Best Solution Fitness: 58826
New Best Solution Fitness: 58760
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.13333 
Mean sub-tour choices: 2.84444 
Best Solution Fitness: 58760 
--------------------------------------------- 
