--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59424
New Best Solution Fitness: 59422
New Best Solution Fitness: 59378
New Best Solution Fitness: 59351
Generation: 3
New Best Solution Fitness: 59324
New Best Solution Fitness: 59265
Generation: 4
New Best Solution Fitness: 59258
Generation: 5
Generation: 6
New Best Solution Fitness: 59250
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 59234
Generation: 10
New Best Solution Fitness: 59136
New Best Solution Fitness: 58874
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.58889 
Mean sub-tour choices: 3.37778 
Best Solution Fitness: 58874 
--------------------------------------------- 
