--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59444
New Best Solution Fitness: 59299
Generation: 3
New Best Solution Fitness: 59210
Generation: 4
New Best Solution Fitness: 59162
Generation: 5
New Best Solution Fitness: 58914
New Best Solution Fitness: 58880
Generation: 6
New Best Solution Fitness: 58728
Generation: 7
New Best Solution Fitness: 58675
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.83333 
Mean sub-tour choices: 2.51111 
Best Solution Fitness: 58675 
--------------------------------------------- 
