--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59947
New Best Solution Fitness: 59868
New Best Solution Fitness: 59857
Generation: 3
New Best Solution Fitness: 59214
New Best Solution Fitness: 59212
New Best Solution Fitness: 59210
Generation: 4
New Best Solution Fitness: 59208
Generation: 5
Generation: 6
New Best Solution Fitness: 59108
New Best Solution Fitness: 59094
Generation: 7
New Best Solution Fitness: 59086
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.4 
Mean sub-tour choices: 1.9 
Best Solution Fitness: 59086 
--------------------------------------------- 
