--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59011
New Best Solution Fitness: 58996
New Best Solution Fitness: 58964
New Best Solution Fitness: 58926
Generation: 3
New Best Solution Fitness: 58571
New Best Solution Fitness: 58525
New Best Solution Fitness: 58518
Generation: 4
New Best Solution Fitness: 58498
New Best Solution Fitness: 58488
New Best Solution Fitness: 58483
Generation: 5
New Best Solution Fitness: 58473
Generation: 6
New Best Solution Fitness: 58431
Generation: 7
Generation: 8
New Best Solution Fitness: 58376
New Best Solution Fitness: 58365
Generation: 9
Generation: 10
New Best Solution Fitness: 58346
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.34444 
Mean sub-tour choices: 3.1 
Best Solution Fitness: 58346 
--------------------------------------------- 
