--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 58902
New Best Solution Fitness: 58865
Generation: 3
New Best Solution Fitness: 58802
New Best Solution Fitness: 58731
Generation: 4
New Best Solution Fitness: 58725
Generation: 5
Generation: 6
New Best Solution Fitness: 58703
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.34444 
Mean sub-tour choices: 3.08889 
Best Solution Fitness: 58703 
--------------------------------------------- 
