--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59782
New Best Solution Fitness: 59760
New Best Solution Fitness: 59636
Generation: 3
New Best Solution Fitness: 59583
New Best Solution Fitness: 59480
New Best Solution Fitness: 59472
Generation: 4
New Best Solution Fitness: 59471
New Best Solution Fitness: 59361
Generation: 5
New Best Solution Fitness: 59308
Generation: 6
Generation: 7
New Best Solution Fitness: 58971
Generation: 8
New Best Solution Fitness: 58956
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3 
Mean sub-tour choices: 3.77778 
Best Solution Fitness: 58956 
--------------------------------------------- 
