--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59523
New Best Solution Fitness: 59468
New Best Solution Fitness: 59342
Generation: 3
New Best Solution Fitness: 59276
New Best Solution Fitness: 59256
New Best Solution Fitness: 59232
New Best Solution Fitness: 59231
New Best Solution Fitness: 59224
Generation: 4
New Best Solution Fitness: 59212
Generation: 5
Generation: 6
New Best Solution Fitness: 59211
New Best Solution Fitness: 59205
Generation: 7
Generation: 8
New Best Solution Fitness: 58955
Generation: 9
Generation: 10
New Best Solution Fitness: 58951
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.17778 
Mean sub-tour choices: 4 
Best Solution Fitness: 58951 
--------------------------------------------- 
