--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59438
New Best Solution Fitness: 59314
Generation: 3
New Best Solution Fitness: 59141
New Best Solution Fitness: 59094
Generation: 4
New Best Solution Fitness: 58998
New Best Solution Fitness: 58984
New Best Solution Fitness: 58826
Generation: 5
New Best Solution Fitness: 58815
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 58813
New Best Solution Fitness: 58798
New Best Solution Fitness: 58757
Generation: 10
New Best Solution Fitness: 58699
New Best Solution Fitness: 58567
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.23333 
Mean sub-tour choices: 2.88889 
Best Solution Fitness: 58567 
--------------------------------------------- 
