--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59717
New Best Solution Fitness: 59616
New Best Solution Fitness: 59575
Generation: 3
New Best Solution Fitness: 59145
New Best Solution Fitness: 59131
New Best Solution Fitness: 59126
Generation: 4
New Best Solution Fitness: 59065
New Best Solution Fitness: 59057
Generation: 5
Generation: 6
New Best Solution Fitness: 59054
Generation: 7
Generation: 8
New Best Solution Fitness: 59046
Generation: 9
New Best Solution Fitness: 58841
New Best Solution Fitness: 58839
Generation: 10
New Best Solution Fitness: 58838
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.32222 
Mean sub-tour choices: 3.01111 
Best Solution Fitness: 58838 
--------------------------------------------- 
