--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 58812
New Best Solution Fitness: 58717
Generation: 3
New Best Solution Fitness: 58695
New Best Solution Fitness: 58691
New Best Solution Fitness: 58678
New Best Solution Fitness: 58625
Generation: 4
New Best Solution Fitness: 58608
Generation: 5
New Best Solution Fitness: 58607
New Best Solution Fitness: 58594
New Best Solution Fitness: 58568
Generation: 6
New Best Solution Fitness: 58567
New Best Solution Fitness: 58554
Generation: 7
New Best Solution Fitness: 58543
Generation: 8
New Best Solution Fitness: 58517
New Best Solution Fitness: 58516
Generation: 9
Generation: 10
New Best Solution Fitness: 58491
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.96667 
Mean sub-tour choices: 2.77778 
Best Solution Fitness: 58491 
--------------------------------------------- 
