--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59013
New Best Solution Fitness: 58921
Generation: 3
New Best Solution Fitness: 58679
New Best Solution Fitness: 58665
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 58634
New Best Solution Fitness: 58630
New Best Solution Fitness: 58608
Generation: 7
New Best Solution Fitness: 58604
New Best Solution Fitness: 58601
Generation: 8
New Best Solution Fitness: 58585
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.38889 
Mean sub-tour choices: 1.92222 
Best Solution Fitness: 58585 
--------------------------------------------- 
