--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59368
New Best Solution Fitness: 59340
New Best Solution Fitness: 59311
New Best Solution Fitness: 59275
Generation: 3
New Best Solution Fitness: 58626
New Best Solution Fitness: 58588
Generation: 4
New Best Solution Fitness: 58511
New Best Solution Fitness: 58393
Generation: 5
New Best Solution Fitness: 58371
Generation: 6
Generation: 7
New Best Solution Fitness: 58219
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.3 
Mean sub-tour choices: 1.8 
Best Solution Fitness: 58219 
--------------------------------------------- 
