--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 60084
New Best Solution Fitness: 60072
New Best Solution Fitness: 60009
New Best Solution Fitness: 60002
New Best Solution Fitness: 59997
Generation: 3
New Best Solution Fitness: 59430
New Best Solution Fitness: 59428
New Best Solution Fitness: 59418
New Best Solution Fitness: 59406
Generation: 4
New Best Solution Fitness: 59093
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 58965
New Best Solution Fitness: 58958
Generation: 10
New Best Solution Fitness: 58854
New Best Solution Fitness: 58850
New Best Solution Fitness: 58822
New Best Solution Fitness: 58817
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.57778 
Mean sub-tour choices: 2.07778 
Best Solution Fitness: 58817 
--------------------------------------------- 
