--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 58908
New Best Solution Fitness: 58904
New Best Solution Fitness: 58893
Generation: 3
New Best Solution Fitness: 58722
New Best Solution Fitness: 58717
Generation: 4
New Best Solution Fitness: 58712
New Best Solution Fitness: 58708
New Best Solution Fitness: 58677
Generation: 5
New Best Solution Fitness: 58667
Generation: 6
New Best Solution Fitness: 58567
New Best Solution Fitness: 58552
New Best Solution Fitness: 58542
Generation: 7
New Best Solution Fitness: 58527
Generation: 8
New Best Solution Fitness: 58524
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.24444 
Mean sub-tour choices: 1.9 
Best Solution Fitness: 58524 
--------------------------------------------- 
