--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59768
New Best Solution Fitness: 59713
Generation: 3
New Best Solution Fitness: 59561
New Best Solution Fitness: 59544
New Best Solution Fitness: 59486
Generation: 4
New Best Solution Fitness: 59405
New Best Solution Fitness: 59404
New Best Solution Fitness: 59388
Generation: 5
New Best Solution Fitness: 59358
New Best Solution Fitness: 59357
Generation: 6
New Best Solution Fitness: 59343
New Best Solution Fitness: 59326
Generation: 7
New Best Solution Fitness: 59136
New Best Solution Fitness: 59127
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.95556 
Mean sub-tour choices: 2.67778 
Best Solution Fitness: 59127 
--------------------------------------------- 
