--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 58923
New Best Solution Fitness: 58867
New Best Solution Fitness: 58846
New Best Solution Fitness: 58844
Generation: 3
New Best Solution Fitness: 58616
New Best Solution Fitness: 58602
New Best Solution Fitness: 58595
Generation: 4
New Best Solution Fitness: 58572
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 58570
New Best Solution Fitness: 58536
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.28889 
Mean sub-tour choices: 1.92222 
Best Solution Fitness: 58536 
--------------------------------------------- 
