--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59391
New Best Solution Fitness: 59151
New Best Solution Fitness: 59140
New Best Solution Fitness: 59114
New Best Solution Fitness: 59112
Generation: 3
New Best Solution Fitness: 58784
New Best Solution Fitness: 58675
Generation: 4
New Best Solution Fitness: 58502
New Best Solution Fitness: 58500
New Best Solution Fitness: 58480
Generation: 5
New Best Solution Fitness: 58478
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 58441
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.16667 
Mean sub-tour choices: 3.9 
Best Solution Fitness: 58441 
--------------------------------------------- 
