--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 58897
New Best Solution Fitness: 58807
New Best Solution Fitness: 58748
Generation: 3
New Best Solution Fitness: 58663
New Best Solution Fitness: 58654
New Best Solution Fitness: 58649
Generation: 4
New Best Solution Fitness: 58645
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 58593
New Best Solution Fitness: 58589
New Best Solution Fitness: 58586
New Best Solution Fitness: 58583
Generation: 10
New Best Solution Fitness: 58490
New Best Solution Fitness: 58461
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.53333 
Mean sub-tour choices: 2.08889 
Best Solution Fitness: 58461 
--------------------------------------------- 
