--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59657
New Best Solution Fitness: 59647
New Best Solution Fitness: 59646
New Best Solution Fitness: 59470
Generation: 3
New Best Solution Fitness: 59030
New Best Solution Fitness: 59025
New Best Solution Fitness: 59022
Generation: 4
New Best Solution Fitness: 58978
New Best Solution Fitness: 58977
Generation: 5
New Best Solution Fitness: 58970
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 58966
Generation: 10
New Best Solution Fitness: 58913
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.5 
Mean sub-tour choices: 2.13333 
Best Solution Fitness: 58913 
--------------------------------------------- 
