--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 58469
New Best Solution Fitness: 58280
Generation: 3
New Best Solution Fitness: 58214
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 58209
Generation: 7
New Best Solution Fitness: 58161
Generation: 8
Generation: 9
New Best Solution Fitness: 58153
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.35556 
Mean sub-tour choices: 1.96667 
Best Solution Fitness: 58153 
--------------------------------------------- 
