--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59795
New Best Solution Fitness: 59626
New Best Solution Fitness: 59605
Generation: 3
New Best Solution Fitness: 59310
New Best Solution Fitness: 59295
Generation: 4
New Best Solution Fitness: 59276
New Best Solution Fitness: 59269
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 59254
Generation: 8
New Best Solution Fitness: 59206
Generation: 9
New Best Solution Fitness: 58976
New Best Solution Fitness: 58971
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.08889 
Mean sub-tour choices: 2.7 
Best Solution Fitness: 58971 
--------------------------------------------- 
