--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59465
New Best Solution Fitness: 59450
New Best Solution Fitness: 59445
New Best Solution Fitness: 59362
New Best Solution Fitness: 59280
Generation: 3
New Best Solution Fitness: 59039
New Best Solution Fitness: 59029
New Best Solution Fitness: 58996
Generation: 4
New Best Solution Fitness: 58911
New Best Solution Fitness: 58798
Generation: 5
New Best Solution Fitness: 58777
New Best Solution Fitness: 58751
Generation: 6
Generation: 7
New Best Solution Fitness: 58740
Generation: 8
Generation: 9
New Best Solution Fitness: 58585
New Best Solution Fitness: 58572
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.3 
Mean sub-tour choices: 4.05556 
Best Solution Fitness: 58572 
--------------------------------------------- 
