--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59462
New Best Solution Fitness: 59399
New Best Solution Fitness: 59384
New Best Solution Fitness: 59353
Generation: 3
New Best Solution Fitness: 58862
New Best Solution Fitness: 58847
Generation: 4
New Best Solution Fitness: 58689
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.27778 
Mean sub-tour choices: 1.87778 
Best Solution Fitness: 58689 
--------------------------------------------- 
