--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59691
New Best Solution Fitness: 59627
New Best Solution Fitness: 59592
New Best Solution Fitness: 59478
Generation: 3
New Best Solution Fitness: 59414
New Best Solution Fitness: 59379
Generation: 4
New Best Solution Fitness: 59354
New Best Solution Fitness: 59319
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 59153
Generation: 8
New Best Solution Fitness: 59139
New Best Solution Fitness: 59122
New Best Solution Fitness: 59101
Generation: 9
New Best Solution Fitness: 58885
New Best Solution Fitness: 58870
Generation: 10
New Best Solution Fitness: 58853
New Best Solution Fitness: 58829
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.21111 
Mean sub-tour choices: 1.73333 
Best Solution Fitness: 58829 
--------------------------------------------- 
