--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59673
New Best Solution Fitness: 59572
New Best Solution Fitness: 59562
New Best Solution Fitness: 59546
New Best Solution Fitness: 59536
Generation: 3
New Best Solution Fitness: 59061
New Best Solution Fitness: 59046
Generation: 4
New Best Solution Fitness: 58790
Generation: 5
New Best Solution Fitness: 58719
Generation: 6
New Best Solution Fitness: 58712
New Best Solution Fitness: 58705
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 58674
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.54444 
Mean sub-tour choices: 2.16667 
Best Solution Fitness: 58674 
--------------------------------------------- 
