--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59149
New Best Solution Fitness: 59030
New Best Solution Fitness: 59001
New Best Solution Fitness: 58993
New Best Solution Fitness: 58926
Generation: 3
New Best Solution Fitness: 58831
New Best Solution Fitness: 58791
New Best Solution Fitness: 58671
Generation: 4
New Best Solution Fitness: 58661
New Best Solution Fitness: 58646
Generation: 5
New Best Solution Fitness: 58642
New Best Solution Fitness: 58632
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 58575
New Best Solution Fitness: 58555
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.1 
Mean sub-tour choices: 2.81111 
Best Solution Fitness: 58555 
--------------------------------------------- 
