--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59867
New Best Solution Fitness: 59817
New Best Solution Fitness: 59770
New Best Solution Fitness: 59626
New Best Solution Fitness: 59604
Generation: 3
New Best Solution Fitness: 59546
New Best Solution Fitness: 59525
Generation: 4
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 59408
New Best Solution Fitness: 59366
Generation: 8
New Best Solution Fitness: 59328
Generation: 9
New Best Solution Fitness: 59231
New Best Solution Fitness: 59214
New Best Solution Fitness: 59210
Generation: 10
New Best Solution Fitness: 59093
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.71111 
Mean sub-tour choices: 2.25556 
Best Solution Fitness: 59093 
--------------------------------------------- 
