--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59778
New Best Solution Fitness: 59604
New Best Solution Fitness: 59588
New Best Solution Fitness: 59529
Generation: 3
New Best Solution Fitness: 59390
New Best Solution Fitness: 59385
New Best Solution Fitness: 59338
Generation: 4
New Best Solution Fitness: 59334
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 59230
New Best Solution Fitness: 59229
New Best Solution Fitness: 59220
New Best Solution Fitness: 59201
Generation: 8
New Best Solution Fitness: 59129
Generation: 9
New Best Solution Fitness: 59128
New Best Solution Fitness: 59125
Generation: 10
New Best Solution Fitness: 59119
New Best Solution Fitness: 59077
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.54444 
Mean sub-tour choices: 2.18889 
Best Solution Fitness: 59077 
--------------------------------------------- 
