--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59767
New Best Solution Fitness: 59761
New Best Solution Fitness: 59727
New Best Solution Fitness: 59706
New Best Solution Fitness: 59704
New Best Solution Fitness: 59693
New Best Solution Fitness: 59606
New Best Solution Fitness: 59569
Generation: 3
New Best Solution Fitness: 59478
New Best Solution Fitness: 59439
New Best Solution Fitness: 59411
New Best Solution Fitness: 59403
Generation: 4
New Best Solution Fitness: 59324
New Best Solution Fitness: 59256
Generation: 5
New Best Solution Fitness: 59237
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.68889 
Mean sub-tour choices: 3.47778 
Best Solution Fitness: 59237 
--------------------------------------------- 
