--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59538
New Best Solution Fitness: 59318
New Best Solution Fitness: 59297
New Best Solution Fitness: 59282
New Best Solution Fitness: 59267
Generation: 3
New Best Solution Fitness: 59025
New Best Solution Fitness: 58995
New Best Solution Fitness: 58989
Generation: 4
New Best Solution Fitness: 58980
New Best Solution Fitness: 58971
Generation: 5
New Best Solution Fitness: 58964
Generation: 6
New Best Solution Fitness: 58943
Generation: 7
New Best Solution Fitness: 58911
Generation: 8
New Best Solution Fitness: 58774
New Best Solution Fitness: 58742
Generation: 9
Generation: 10
New Best Solution Fitness: 58657
New Best Solution Fitness: 58642
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.42222 
Mean sub-tour choices: 3.22222 
Best Solution Fitness: 58642 
--------------------------------------------- 
