--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59491
New Best Solution Fitness: 59487
New Best Solution Fitness: 59429
New Best Solution Fitness: 59420
New Best Solution Fitness: 59397
Generation: 3
New Best Solution Fitness: 59000
New Best Solution Fitness: 58992
New Best Solution Fitness: 58880
Generation: 4
New Best Solution Fitness: 58693
New Best Solution Fitness: 58676
New Best Solution Fitness: 58514
Generation: 5
New Best Solution Fitness: 58512
New Best Solution Fitness: 58495
New Best Solution Fitness: 58473
New Best Solution Fitness: 58460
Generation: 6
New Best Solution Fitness: 58437
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.86667 
Mean sub-tour choices: 4.7 
Best Solution Fitness: 58437 
--------------------------------------------- 
