--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59195
New Best Solution Fitness: 59160
New Best Solution Fitness: 59159
Generation: 3
New Best Solution Fitness: 58847
Generation: 4
Generation: 5
New Best Solution Fitness: 58757
New Best Solution Fitness: 58753
Generation: 6
New Best Solution Fitness: 58686
Generation: 7
Generation: 8
New Best Solution Fitness: 58650
Generation: 9
New Best Solution Fitness: 58521
Generation: 10
New Best Solution Fitness: 58507
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.26667 
Mean sub-tour choices: 1.84444 
Best Solution Fitness: 58507 
--------------------------------------------- 
