--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59353
New Best Solution Fitness: 59297
New Best Solution Fitness: 59281
Generation: 3
New Best Solution Fitness: 58706
New Best Solution Fitness: 58705
New Best Solution Fitness: 58673
Generation: 4
New Best Solution Fitness: 58672
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 58515
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.54444 
Mean sub-tour choices: 3.34444 
Best Solution Fitness: 58515 
--------------------------------------------- 
