--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59904
New Best Solution Fitness: 59874
New Best Solution Fitness: 59865
New Best Solution Fitness: 59851
Generation: 3
New Best Solution Fitness: 59418
New Best Solution Fitness: 59327
Generation: 4
New Best Solution Fitness: 59188
New Best Solution Fitness: 59177
New Best Solution Fitness: 59171
Generation: 5
New Best Solution Fitness: 59160
Generation: 6
New Best Solution Fitness: 58955
Generation: 7
New Best Solution Fitness: 58938
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 58912
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.83333 
Mean sub-tour choices: 2.48889 
Best Solution Fitness: 58912 
--------------------------------------------- 
