--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59487
New Best Solution Fitness: 59442
New Best Solution Fitness: 59421
Generation: 3
New Best Solution Fitness: 58734
New Best Solution Fitness: 58677
Generation: 4
New Best Solution Fitness: 58656
New Best Solution Fitness: 58637
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.77778 
Mean sub-tour choices: 2.32222 
Best Solution Fitness: 58637 
--------------------------------------------- 
