--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59713
New Best Solution Fitness: 59642
New Best Solution Fitness: 59608
New Best Solution Fitness: 59598
Generation: 3
New Best Solution Fitness: 59402
New Best Solution Fitness: 59326
Generation: 4
New Best Solution Fitness: 59204
New Best Solution Fitness: 59185
Generation: 5
New Best Solution Fitness: 59181
New Best Solution Fitness: 59177
New Best Solution Fitness: 59173
Generation: 6
New Best Solution Fitness: 59161
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 59152
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.73333 
Mean sub-tour choices: 3.51111 
Best Solution Fitness: 59152 
--------------------------------------------- 
