--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 58851
New Best Solution Fitness: 58824
New Best Solution Fitness: 58755
Generation: 3
New Best Solution Fitness: 58531
New Best Solution Fitness: 58526
New Best Solution Fitness: 58525
New Best Solution Fitness: 58499
New Best Solution Fitness: 58496
New Best Solution Fitness: 58468
Generation: 4
New Best Solution Fitness: 58452
New Best Solution Fitness: 58446
New Best Solution Fitness: 58442
Generation: 5
New Best Solution Fitness: 58439
New Best Solution Fitness: 58433
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 58425
Generation: 10
New Best Solution Fitness: 58404
New Best Solution Fitness: 58393
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.56667 
Mean sub-tour choices: 2.13333 
Best Solution Fitness: 58393 
--------------------------------------------- 
