--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59354
New Best Solution Fitness: 59343
New Best Solution Fitness: 59221
New Best Solution Fitness: 59180
Generation: 3
New Best Solution Fitness: 58867
New Best Solution Fitness: 58842
Generation: 4
New Best Solution Fitness: 58575
Generation: 5
New Best Solution Fitness: 58518
New Best Solution Fitness: 58498
Generation: 6
New Best Solution Fitness: 58495
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 58480
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.57778 
Mean sub-tour choices: 3.25556 
Best Solution Fitness: 58480 
--------------------------------------------- 
