--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 58500
New Best Solution Fitness: 58418
New Best Solution Fitness: 58401
Generation: 3
New Best Solution Fitness: 58258
New Best Solution Fitness: 58248
New Best Solution Fitness: 58243
Generation: 4
New Best Solution Fitness: 58241
New Best Solution Fitness: 58231
Generation: 5
Generation: 6
New Best Solution Fitness: 58223
Generation: 7
Generation: 8
New Best Solution Fitness: 58213
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.31111 
Mean sub-tour choices: 1.86667 
Best Solution Fitness: 58213 
--------------------------------------------- 
