--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59167
New Best Solution Fitness: 59147
New Best Solution Fitness: 59038
Generation: 3
New Best Solution Fitness: 58822
New Best Solution Fitness: 58735
Generation: 4
New Best Solution Fitness: 58719
New Best Solution Fitness: 58711
Generation: 5
New Best Solution Fitness: 58682
Generation: 6
Generation: 7
New Best Solution Fitness: 58676
Generation: 8
New Best Solution Fitness: 58670
Generation: 9
Generation: 10
New Best Solution Fitness: 58663
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.67778 
Mean sub-tour choices: 2.22222 
Best Solution Fitness: 58663 
--------------------------------------------- 
