--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59104
New Best Solution Fitness: 59080
New Best Solution Fitness: 59033
Generation: 3
New Best Solution Fitness: 58720
New Best Solution Fitness: 58706
Generation: 4
New Best Solution Fitness: 58696
Generation: 5
New Best Solution Fitness: 58689
Generation: 6
New Best Solution Fitness: 58685
Generation: 7
Generation: 8
New Best Solution Fitness: 58670
New Best Solution Fitness: 58632
New Best Solution Fitness: 58587
New Best Solution Fitness: 58504
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.12222 
Mean sub-tour choices: 2.84444 
Best Solution Fitness: 58504 
--------------------------------------------- 
