--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 58750
New Best Solution Fitness: 58735
New Best Solution Fitness: 58708
New Best Solution Fitness: 58705
New Best Solution Fitness: 58690
Generation: 3
New Best Solution Fitness: 58654
New Best Solution Fitness: 58639
New Best Solution Fitness: 58614
Generation: 4
New Best Solution Fitness: 58474
New Best Solution Fitness: 58469
Generation: 5
New Best Solution Fitness: 58429
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 58414
Generation: 9
New Best Solution Fitness: 58275
New Best Solution Fitness: 58253
New Best Solution Fitness: 58238
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.54444 
Mean sub-tour choices: 2.23333 
Best Solution Fitness: 58238 
--------------------------------------------- 
