--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59090
New Best Solution Fitness: 59076
New Best Solution Fitness: 58959
Generation: 3
New Best Solution Fitness: 58870
New Best Solution Fitness: 58694
Generation: 4
New Best Solution Fitness: 58647
New Best Solution Fitness: 58628
Generation: 5
New Best Solution Fitness: 58627
New Best Solution Fitness: 58625
Generation: 6
New Best Solution Fitness: 58623
Generation: 7
New Best Solution Fitness: 58601
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 58579
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.11111 
Mean sub-tour choices: 2.67778 
Best Solution Fitness: 58579 
--------------------------------------------- 
