--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 60345
New Best Solution Fitness: 60237
New Best Solution Fitness: 60153
New Best Solution Fitness: 60138
Generation: 3
New Best Solution Fitness: 59718
New Best Solution Fitness: 59573
New Best Solution Fitness: 59551
Generation: 4
New Best Solution Fitness: 59358
New Best Solution Fitness: 59343
New Best Solution Fitness: 59265
Generation: 5
New Best Solution Fitness: 59231
New Best Solution Fitness: 59230
Generation: 6
Generation: 7
New Best Solution Fitness: 59215
Generation: 8
New Best Solution Fitness: 59196
New Best Solution Fitness: 59190
Generation: 9
New Best Solution Fitness: 59014
Generation: 10
New Best Solution Fitness: 58946
New Best Solution Fitness: 58939
New Best Solution Fitness: 58938
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.57778 
Mean sub-tour choices: 3.27778 
Best Solution Fitness: 58938 
--------------------------------------------- 
