--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59393
New Best Solution Fitness: 59380
New Best Solution Fitness: 59244
New Best Solution Fitness: 59155
Generation: 3
New Best Solution Fitness: 58745
New Best Solution Fitness: 58744
New Best Solution Fitness: 58731
Generation: 4
New Best Solution Fitness: 58709
New Best Solution Fitness: 58660
Generation: 5
Generation: 6
New Best Solution Fitness: 58618
New Best Solution Fitness: 58602
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 58473
New Best Solution Fitness: 58379
New Best Solution Fitness: 58292
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.88889 
Mean sub-tour choices: 2.61111 
Best Solution Fitness: 58292 
--------------------------------------------- 
