--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 58976
New Best Solution Fitness: 58832
New Best Solution Fitness: 58825
Generation: 3
New Best Solution Fitness: 58518
New Best Solution Fitness: 58497
New Best Solution Fitness: 58480
Generation: 4
New Best Solution Fitness: 58353
New Best Solution Fitness: 58320
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 58308
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.77778 
Mean sub-tour choices: 2.48889 
Best Solution Fitness: 58308 
--------------------------------------------- 
