--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 60356
New Best Solution Fitness: 60058
Generation: 3
New Best Solution Fitness: 59464
New Best Solution Fitness: 59449
New Best Solution Fitness: 59416
Generation: 4
New Best Solution Fitness: 59372
New Best Solution Fitness: 59309
Generation: 5
New Best Solution Fitness: 59136
Generation: 6
Generation: 7
New Best Solution Fitness: 59054
New Best Solution Fitness: 59035
New Best Solution Fitness: 59029
Generation: 8
New Best Solution Fitness: 58912
New Best Solution Fitness: 58899
Generation: 9
Generation: 10
New Best Solution Fitness: 58818
New Best Solution Fitness: 58796
New Best Solution Fitness: 58696
New Best Solution Fitness: 58666
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.04444 
Mean sub-tour choices: 2.81111 
Best Solution Fitness: 58666 
--------------------------------------------- 
