--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59583
New Best Solution Fitness: 59513
New Best Solution Fitness: 59500
New Best Solution Fitness: 59486
New Best Solution Fitness: 59428
Generation: 3
New Best Solution Fitness: 58978
New Best Solution Fitness: 58956
Generation: 4
New Best Solution Fitness: 58804
New Best Solution Fitness: 58787
New Best Solution Fitness: 58786
Generation: 5
New Best Solution Fitness: 58771
Generation: 6
New Best Solution Fitness: 58723
Generation: 7
Generation: 8
New Best Solution Fitness: 58709
Generation: 9
New Best Solution Fitness: 58708
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.08889 
Mean sub-tour choices: 2.75556 
Best Solution Fitness: 58708 
--------------------------------------------- 
