--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59034
New Best Solution Fitness: 58901
Generation: 3
New Best Solution Fitness: 58813
New Best Solution Fitness: 58796
Generation: 4
Generation: 5
New Best Solution Fitness: 58699
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 58694
Generation: 9
Generation: 10
New Best Solution Fitness: 58621
New Best Solution Fitness: 58593
New Best Solution Fitness: 58576
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.7 
Mean sub-tour choices: 2.42222 
Best Solution Fitness: 58576 
--------------------------------------------- 
