--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59587
New Best Solution Fitness: 59570
New Best Solution Fitness: 59549
New Best Solution Fitness: 59491
Generation: 3
New Best Solution Fitness: 58784
New Best Solution Fitness: 58781
New Best Solution Fitness: 58775
New Best Solution Fitness: 58774
New Best Solution Fitness: 58751
Generation: 4
New Best Solution Fitness: 58653
New Best Solution Fitness: 58623
Generation: 5
New Best Solution Fitness: 58622
New Best Solution Fitness: 58615
New Best Solution Fitness: 58614
Generation: 6
New Best Solution Fitness: 58608
New Best Solution Fitness: 58588
Generation: 7
New Best Solution Fitness: 58582
New Best Solution Fitness: 58581
Generation: 8
New Best Solution Fitness: 58568
New Best Solution Fitness: 58562
Generation: 9
New Best Solution Fitness: 58559
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.45556 
Mean sub-tour choices: 4.26667 
Best Solution Fitness: 58559 
--------------------------------------------- 
