--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59567
New Best Solution Fitness: 59531
New Best Solution Fitness: 59505
Generation: 3
New Best Solution Fitness: 58993
New Best Solution Fitness: 58991
New Best Solution Fitness: 58968
New Best Solution Fitness: 58964
New Best Solution Fitness: 58952
Generation: 4
New Best Solution Fitness: 58895
New Best Solution Fitness: 58886
Generation: 5
New Best Solution Fitness: 58831
Generation: 6
New Best Solution Fitness: 58771
Generation: 7
New Best Solution Fitness: 58752
New Best Solution Fitness: 58705
New Best Solution Fitness: 58697
Generation: 8
New Best Solution Fitness: 58576
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.43333 
Mean sub-tour choices: 3.14444 
Best Solution Fitness: 58576 
--------------------------------------------- 
