--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59724
New Best Solution Fitness: 59651
Generation: 3
New Best Solution Fitness: 59204
New Best Solution Fitness: 59160
New Best Solution Fitness: 59147
New Best Solution Fitness: 59134
Generation: 4
New Best Solution Fitness: 59043
New Best Solution Fitness: 59036
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 58624
New Best Solution Fitness: 58602
Generation: 9
New Best Solution Fitness: 58539
New Best Solution Fitness: 58512
Generation: 10
New Best Solution Fitness: 58492
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.81111 
Mean sub-tour choices: 3.53333 
Best Solution Fitness: 58492 
--------------------------------------------- 
