--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59641
New Best Solution Fitness: 59605
New Best Solution Fitness: 59589
New Best Solution Fitness: 59572
Generation: 3
New Best Solution Fitness: 59240
New Best Solution Fitness: 59170
New Best Solution Fitness: 59158
Generation: 4
New Best Solution Fitness: 58552
New Best Solution Fitness: 58504
Generation: 5
New Best Solution Fitness: 58449
New Best Solution Fitness: 58432
Generation: 6
New Best Solution Fitness: 58285
New Best Solution Fitness: 58264
Generation: 7
New Best Solution Fitness: 58197
Generation: 8
Generation: 9
New Best Solution Fitness: 58185
New Best Solution Fitness: 58181
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.14444 
Mean sub-tour choices: 3.93333 
Best Solution Fitness: 58181 
--------------------------------------------- 
