--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59221
New Best Solution Fitness: 59088
New Best Solution Fitness: 59004
Generation: 3
New Best Solution Fitness: 58897
New Best Solution Fitness: 58860
Generation: 4
New Best Solution Fitness: 58814
New Best Solution Fitness: 58799
Generation: 5
Generation: 6
New Best Solution Fitness: 58651
New Best Solution Fitness: 58591
Generation: 7
New Best Solution Fitness: 58577
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.11111 
Mean sub-tour choices: 1.56667 
Best Solution Fitness: 58577 
--------------------------------------------- 
