--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 58740
New Best Solution Fitness: 58713
New Best Solution Fitness: 58698
Generation: 3
New Best Solution Fitness: 58642
New Best Solution Fitness: 58633
Generation: 4
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 58616
Generation: 9
New Best Solution Fitness: 58601
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.16667 
Mean sub-tour choices: 1.78889 
Best Solution Fitness: 58601 
--------------------------------------------- 
