--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59360
New Best Solution Fitness: 59311
New Best Solution Fitness: 59266
New Best Solution Fitness: 59170
New Best Solution Fitness: 59093
Generation: 3
New Best Solution Fitness: 59041
New Best Solution Fitness: 58958
Generation: 4
New Best Solution Fitness: 58803
New Best Solution Fitness: 58794
New Best Solution Fitness: 58720
Generation: 5
New Best Solution Fitness: 58711
New Best Solution Fitness: 58701
Generation: 6
Generation: 7
New Best Solution Fitness: 58694
New Best Solution Fitness: 58672
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.44444 
Mean sub-tour choices: 1.95556 
Best Solution Fitness: 58672 
--------------------------------------------- 
