--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59213
New Best Solution Fitness: 59211
Generation: 3
New Best Solution Fitness: 59191
New Best Solution Fitness: 59162
New Best Solution Fitness: 59151
New Best Solution Fitness: 58950
Generation: 4
New Best Solution Fitness: 58853
New Best Solution Fitness: 58852
Generation: 5
New Best Solution Fitness: 58742
Generation: 6
New Best Solution Fitness: 58676
New Best Solution Fitness: 58668
New Best Solution Fitness: 58647
Generation: 7
Generation: 8
New Best Solution Fitness: 58639
Generation: 9
New Best Solution Fitness: 58632
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.966667 
Mean sub-tour choices: 1.43333 
Best Solution Fitness: 58632 
--------------------------------------------- 
