--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59604
New Best Solution Fitness: 59453
New Best Solution Fitness: 59422
New Best Solution Fitness: 59396
Generation: 3
New Best Solution Fitness: 59215
New Best Solution Fitness: 59192
New Best Solution Fitness: 59088
New Best Solution Fitness: 59074
Generation: 4
New Best Solution Fitness: 58963
New Best Solution Fitness: 58960
New Best Solution Fitness: 58784
Generation: 5
New Best Solution Fitness: 58726
New Best Solution Fitness: 58723
New Best Solution Fitness: 58713
Generation: 6
New Best Solution Fitness: 58533
New Best Solution Fitness: 58523
Generation: 7
New Best Solution Fitness: 58378
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.14444 
Mean sub-tour choices: 2.81111 
Best Solution Fitness: 58378 
--------------------------------------------- 
