--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59603
New Best Solution Fitness: 59596
New Best Solution Fitness: 59410
Generation: 3
New Best Solution Fitness: 59047
New Best Solution Fitness: 58954
Generation: 4
New Best Solution Fitness: 58944
New Best Solution Fitness: 58841
Generation: 5
New Best Solution Fitness: 58781
New Best Solution Fitness: 58779
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 58754
New Best Solution Fitness: 58592
Generation: 9
New Best Solution Fitness: 58508
Generation: 10
New Best Solution Fitness: 58496
New Best Solution Fitness: 58495
New Best Solution Fitness: 58488
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.9 
Mean sub-tour choices: 2.56667 
Best Solution Fitness: 58488 
--------------------------------------------- 
