--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59634
New Best Solution Fitness: 59629
New Best Solution Fitness: 59609
New Best Solution Fitness: 59507
New Best Solution Fitness: 59469
Generation: 3
New Best Solution Fitness: 59104
New Best Solution Fitness: 59031
Generation: 4
New Best Solution Fitness: 58987
Generation: 5
New Best Solution Fitness: 58985
New Best Solution Fitness: 58977
Generation: 6
New Best Solution Fitness: 58967
New Best Solution Fitness: 58966
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 58938
Generation: 10
New Best Solution Fitness: 58916
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.98889 
Mean sub-tour choices: 3.72222 
Best Solution Fitness: 58916 
--------------------------------------------- 
