--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59509
New Best Solution Fitness: 59492
New Best Solution Fitness: 59491
Generation: 3
New Best Solution Fitness: 59447
New Best Solution Fitness: 59442
New Best Solution Fitness: 59426
Generation: 4
New Best Solution Fitness: 59425
New Best Solution Fitness: 59421
Generation: 5
New Best Solution Fitness: 59420
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 59360
New Best Solution Fitness: 59355
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.86667 
Mean sub-tour choices: 2.52222 
Best Solution Fitness: 59355 
--------------------------------------------- 
