--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59767
New Best Solution Fitness: 59498
Generation: 3
New Best Solution Fitness: 59088
New Best Solution Fitness: 59030
New Best Solution Fitness: 58805
Generation: 4
New Best Solution Fitness: 58761
New Best Solution Fitness: 58732
Generation: 5
New Best Solution Fitness: 58664
New Best Solution Fitness: 58632
Generation: 6
New Best Solution Fitness: 58622
New Best Solution Fitness: 58617
Generation: 7
New Best Solution Fitness: 58607
Generation: 8
New Best Solution Fitness: 58491
New Best Solution Fitness: 58481
Generation: 9
New Best Solution Fitness: 58474
New Best Solution Fitness: 58455
New Best Solution Fitness: 58417
Generation: 10
New Best Solution Fitness: 58398
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.88889 
Mean sub-tour choices: 2.62222 
Best Solution Fitness: 58398 
--------------------------------------------- 
