--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59340
New Best Solution Fitness: 59304
New Best Solution Fitness: 59275
New Best Solution Fitness: 59169
Generation: 3
New Best Solution Fitness: 58749
New Best Solution Fitness: 58591
Generation: 4
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 58577
Generation: 8
New Best Solution Fitness: 58560
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.04444 
Mean sub-tour choices: 1.61111 
Best Solution Fitness: 58560 
--------------------------------------------- 
