--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59795
New Best Solution Fitness: 59671
New Best Solution Fitness: 59610
Generation: 3
New Best Solution Fitness: 59028
New Best Solution Fitness: 59024
New Best Solution Fitness: 59008
Generation: 4
New Best Solution Fitness: 58893
New Best Solution Fitness: 58889
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 58609
New Best Solution Fitness: 58588
Generation: 8
Generation: 9
New Best Solution Fitness: 58584
Generation: 10
New Best Solution Fitness: 58582
New Best Solution Fitness: 58577
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.7 
Mean sub-tour choices: 2.27778 
Best Solution Fitness: 58577 
--------------------------------------------- 
