--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59269
New Best Solution Fitness: 59249
New Best Solution Fitness: 59234
New Best Solution Fitness: 59230
New Best Solution Fitness: 59184
Generation: 3
New Best Solution Fitness: 58937
New Best Solution Fitness: 58925
Generation: 4
New Best Solution Fitness: 58801
New Best Solution Fitness: 58793
Generation: 5
New Best Solution Fitness: 58719
New Best Solution Fitness: 58710
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 58688
Generation: 9
New Best Solution Fitness: 58649
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.34444 
Mean sub-tour choices: 1.96667 
Best Solution Fitness: 58649 
--------------------------------------------- 
