--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 58586
New Best Solution Fitness: 58523
New Best Solution Fitness: 58494
Generation: 3
New Best Solution Fitness: 58320
New Best Solution Fitness: 58260
New Best Solution Fitness: 58201
New Best Solution Fitness: 58188
Generation: 4
New Best Solution Fitness: 58093
Generation: 5
New Best Solution Fitness: 58092
Generation: 6
New Best Solution Fitness: 58074
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 58069
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.83333 
Mean sub-tour choices: 2.5 
Best Solution Fitness: 58069 
--------------------------------------------- 
