--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59223
New Best Solution Fitness: 59204
New Best Solution Fitness: 59188
Generation: 3
New Best Solution Fitness: 58993
New Best Solution Fitness: 58935
Generation: 4
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 58931
Generation: 8
Generation: 9
New Best Solution Fitness: 58556
New Best Solution Fitness: 58554
New Best Solution Fitness: 58549
Generation: 10
New Best Solution Fitness: 58506
New Best Solution Fitness: 58504
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.37778 
Mean sub-tour choices: 1.91111 
Best Solution Fitness: 58504 
--------------------------------------------- 
