--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59288
New Best Solution Fitness: 59285
New Best Solution Fitness: 59223
New Best Solution Fitness: 59148
Generation: 3
New Best Solution Fitness: 58738
New Best Solution Fitness: 58736
New Best Solution Fitness: 58721
Generation: 4
New Best Solution Fitness: 58704
New Best Solution Fitness: 58671
Generation: 5
New Best Solution Fitness: 58670
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.21111 
Mean sub-tour choices: 1.81111 
Best Solution Fitness: 58670 
--------------------------------------------- 
