--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59110
New Best Solution Fitness: 59101
Generation: 3
New Best Solution Fitness: 59027
Generation: 4
New Best Solution Fitness: 58996
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 58974
Generation: 9
Generation: 10
New Best Solution Fitness: 58852
New Best Solution Fitness: 58817
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.15556 
Mean sub-tour choices: 1.68889 
Best Solution Fitness: 58817 
--------------------------------------------- 
