--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59389
New Best Solution Fitness: 59289
New Best Solution Fitness: 59096
New Best Solution Fitness: 59077
Generation: 3
New Best Solution Fitness: 58767
New Best Solution Fitness: 58757
New Best Solution Fitness: 58745
New Best Solution Fitness: 58735
New Best Solution Fitness: 58651
Generation: 4
New Best Solution Fitness: 58602
New Best Solution Fitness: 58580
Generation: 5
New Best Solution Fitness: 58568
Generation: 6
Generation: 7
New Best Solution Fitness: 58558
Generation: 8
New Best Solution Fitness: 58536
New Best Solution Fitness: 58535
Generation: 9
New Best Solution Fitness: 58497
New Best Solution Fitness: 58496
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.72222 
Mean sub-tour choices: 2.31111 
Best Solution Fitness: 58496 
--------------------------------------------- 
