--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59145
New Best Solution Fitness: 59098
New Best Solution Fitness: 59082
New Best Solution Fitness: 59080
Generation: 3
New Best Solution Fitness: 59027
New Best Solution Fitness: 59022
Generation: 4
New Best Solution Fitness: 59020
Generation: 5
Generation: 6
New Best Solution Fitness: 58829
Generation: 7
New Best Solution Fitness: 58744
Generation: 8
New Best Solution Fitness: 58742
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.92222 
Mean sub-tour choices: 3.76667 
Best Solution Fitness: 58742 
--------------------------------------------- 
