--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59128
New Best Solution Fitness: 59099
New Best Solution Fitness: 59076
New Best Solution Fitness: 59070
New Best Solution Fitness: 59018
New Best Solution Fitness: 58971
Generation: 3
New Best Solution Fitness: 58901
New Best Solution Fitness: 58882
New Best Solution Fitness: 58813
Generation: 4
New Best Solution Fitness: 58805
Generation: 5
New Best Solution Fitness: 58804
Generation: 6
Generation: 7
New Best Solution Fitness: 58783
New Best Solution Fitness: 58769
Generation: 8
New Best Solution Fitness: 58755
Generation: 9
Generation: 10
New Best Solution Fitness: 58685
New Best Solution Fitness: 58681
New Best Solution Fitness: 58651
New Best Solution Fitness: 58568
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.83333 
Mean sub-tour choices: 2.46667 
Best Solution Fitness: 58568 
--------------------------------------------- 
