--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59013
New Best Solution Fitness: 58893
New Best Solution Fitness: 58854
Generation: 3
New Best Solution Fitness: 58720
New Best Solution Fitness: 58630
New Best Solution Fitness: 58567
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 58540
Generation: 7
New Best Solution Fitness: 58530
New Best Solution Fitness: 58503
Generation: 8
New Best Solution Fitness: 58436
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.9 
Mean sub-tour choices: 2.54444 
Best Solution Fitness: 58436 
--------------------------------------------- 
