--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 60391
New Best Solution Fitness: 60365
New Best Solution Fitness: 60320
Generation: 3
New Best Solution Fitness: 59118
New Best Solution Fitness: 58897
Generation: 4
New Best Solution Fitness: 58662
New Best Solution Fitness: 58565
Generation: 5
New Best Solution Fitness: 58551
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.52222 
Mean sub-tour choices: 2.1 
Best Solution Fitness: 58551 
--------------------------------------------- 
