--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 58694
New Best Solution Fitness: 58677
Generation: 3
New Best Solution Fitness: 58672
Generation: 4
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 58671
New Best Solution Fitness: 58601
Generation: 9
New Best Solution Fitness: 58579
New Best Solution Fitness: 58578
Generation: 10
New Best Solution Fitness: 58551
New Best Solution Fitness: 58538
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.55556 
Mean sub-tour choices: 2.2 
Best Solution Fitness: 58538 
--------------------------------------------- 
