--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 58615
New Best Solution Fitness: 58586
New Best Solution Fitness: 58553
Generation: 3
New Best Solution Fitness: 58380
New Best Solution Fitness: 58370
New Best Solution Fitness: 58365
Generation: 4
New Best Solution Fitness: 58355
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 58281
New Best Solution Fitness: 58264
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.27778 
Mean sub-tour choices: 1.86667 
Best Solution Fitness: 58264 
--------------------------------------------- 
