--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59031
New Best Solution Fitness: 58978
New Best Solution Fitness: 58950
New Best Solution Fitness: 58942
Generation: 3
New Best Solution Fitness: 58646
New Best Solution Fitness: 58598
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 58565
Generation: 7
New Best Solution Fitness: 58381
New Best Solution Fitness: 58380
New Best Solution Fitness: 58311
Generation: 8
New Best Solution Fitness: 58273
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.47778 
Mean sub-tour choices: 3.2 
Best Solution Fitness: 58273 
--------------------------------------------- 
