--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59290
New Best Solution Fitness: 59109
Generation: 3
New Best Solution Fitness: 58970
New Best Solution Fitness: 58909
New Best Solution Fitness: 58907
Generation: 4
New Best Solution Fitness: 58889
New Best Solution Fitness: 58806
Generation: 5
New Best Solution Fitness: 58766
New Best Solution Fitness: 58759
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 58737
New Best Solution Fitness: 58729
New Best Solution Fitness: 58622
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.54444 
Mean sub-tour choices: 3.28889 
Best Solution Fitness: 58622 
--------------------------------------------- 
