--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 58962
New Best Solution Fitness: 58921
Generation: 3
New Best Solution Fitness: 58720
New Best Solution Fitness: 58699
Generation: 4
New Best Solution Fitness: 58615
New Best Solution Fitness: 58609
Generation: 5
New Best Solution Fitness: 58605
Generation: 6
New Best Solution Fitness: 58591
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 58585
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.73333 
Mean sub-tour choices: 2.36667 
Best Solution Fitness: 58585 
--------------------------------------------- 
