--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Black Box Steady State 
Population: 10
Mutation probability: 1
Crossover probability: 0.000329164
--------------------------
Job Complete 
Best Solution Fitness: 158853
Iterations: 92294440
--------------------------------------------- 
