--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 118856
New Best Solution Fitness: 118689
Generation: 3
New Best Solution Fitness: 118541
New Best Solution Fitness: 118497
New Best Solution Fitness: 118467
Generation: 4
New Best Solution Fitness: 118423
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 118282
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.388889 
Mean sub-tour choices: 0.655556 
Best Solution Fitness: 118282 
--------------------------------------------- 
