--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 120264
Generation: 3
New Best Solution Fitness: 120159
Generation: 4
Generation: 5
New Best Solution Fitness: 119714
Generation: 6
New Best Solution Fitness: 119546
New Best Solution Fitness: 119444
Generation: 7
New Best Solution Fitness: 119400
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 119042
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.144444 
Mean sub-tour choices: 0.244444 
Best Solution Fitness: 119042 
--------------------------------------------- 
