--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 120520
Generation: 3
New Best Solution Fitness: 119073
New Best Solution Fitness: 118970
Generation: 4
New Best Solution Fitness: 118861
Generation: 5
Generation: 6
New Best Solution Fitness: 118616
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.0777778 
Mean sub-tour choices: 0.122222 
Best Solution Fitness: 118616 
--------------------------------------------- 
