--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 120715
Generation: 3
New Best Solution Fitness: 119608
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 119019
Generation: 7
Generation: 8
New Best Solution Fitness: 118945
Generation: 9
Generation: 10
New Best Solution Fitness: 118715
New Best Solution Fitness: 118579
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.0888889 
Mean sub-tour choices: 0.144444 
Best Solution Fitness: 118579 
--------------------------------------------- 
