--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 120138
Generation: 3
New Best Solution Fitness: 119225
Generation: 4
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 119217
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 119161
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.0666667 
Mean sub-tour choices: 0.1 
Best Solution Fitness: 119161 
--------------------------------------------- 
