--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 120662
New Best Solution Fitness: 120592
Generation: 3
New Best Solution Fitness: 119803
Generation: 4
Generation: 5
New Best Solution Fitness: 119001
Generation: 6
New Best Solution Fitness: 118621
Generation: 7
Generation: 8
New Best Solution Fitness: 118615
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.222222 
Mean sub-tour choices: 0.344444 
Best Solution Fitness: 118615 
--------------------------------------------- 
