--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 120161
Generation: 3
New Best Solution Fitness: 119616
Generation: 4
New Best Solution Fitness: 118854
Generation: 5
New Best Solution Fitness: 118780
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.244444 
Mean sub-tour choices: 0.4 
Best Solution Fitness: 118780 
--------------------------------------------- 
