--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 119400
Generation: 3
Generation: 4
Generation: 5
New Best Solution Fitness: 119108
Generation: 6
New Best Solution Fitness: 118856
New Best Solution Fitness: 118780
Generation: 7
Generation: 8
New Best Solution Fitness: 118423
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.111111 
Mean sub-tour choices: 0.188889 
Best Solution Fitness: 118423 
--------------------------------------------- 
