--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 119178
Generation: 3
Generation: 4
Generation: 5
New Best Solution Fitness: 118821
Generation: 6
Generation: 7
New Best Solution Fitness: 118750
Generation: 8
Generation: 9
New Best Solution Fitness: 118282
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.0888889 
Mean sub-tour choices: 0.133333 
Best Solution Fitness: 118282 
--------------------------------------------- 
