--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 118541
New Best Solution Fitness: 118467
Generation: 3
New Best Solution Fitness: 118423
Generation: 4
New Best Solution Fitness: 118356
New Best Solution Fitness: 118282
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.155556 
Mean sub-tour choices: 0.244444 
Best Solution Fitness: 118282 
--------------------------------------------- 
