--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 118973
Generation: 3
New Best Solution Fitness: 118955
Generation: 4
New Best Solution Fitness: 118900
New Best Solution Fitness: 118856
Generation: 5
New Best Solution Fitness: 118544
New Best Solution Fitness: 118470
Generation: 6
New Best Solution Fitness: 118423
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.133333 
Mean sub-tour choices: 0.211111 
Best Solution Fitness: 118423 
--------------------------------------------- 
