--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 118934
New Best Solution Fitness: 118860
Generation: 3
New Best Solution Fitness: 118848
Generation: 4
New Best Solution Fitness: 118847
Generation: 5
Generation: 6
New Best Solution Fitness: 118423
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 118356
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.133333 
Mean sub-tour choices: 0.2 
Best Solution Fitness: 118356 
--------------------------------------------- 
