--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 118922
Generation: 3
New Best Solution Fitness: 118900
Generation: 4
New Best Solution Fitness: 118834
Generation: 5
New Best Solution Fitness: 118623
New Best Solution Fitness: 118549
Generation: 6
New Best Solution Fitness: 118535
New Best Solution Fitness: 118461
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 118423
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.255556 
Mean sub-tour choices: 0.433333 
Best Solution Fitness: 118423 
--------------------------------------------- 
