--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 120718
New Best Solution Fitness: 120706
Generation: 3
Generation: 4
New Best Solution Fitness: 120349
Generation: 5
New Best Solution Fitness: 120147
New Best Solution Fitness: 119777
Generation: 6
New Best Solution Fitness: 119517
Generation: 7
Generation: 8
New Best Solution Fitness: 118856
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.266667 
Mean sub-tour choices: 0.433333 
Best Solution Fitness: 118856 
--------------------------------------------- 
