--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 120131
New Best Solution Fitness: 120057
New Best Solution Fitness: 120056
Generation: 3
Generation: 4
New Best Solution Fitness: 119725
New Best Solution Fitness: 119724
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 119366
Generation: 9
Generation: 10
New Best Solution Fitness: 118657
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.555556 
Mean sub-tour choices: 0.866667 
Best Solution Fitness: 118657 
--------------------------------------------- 
