--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 119322
Generation: 3
New Best Solution Fitness: 119269
Generation: 4
New Best Solution Fitness: 119064
Generation: 5
Generation: 6
New Best Solution Fitness: 118838
Generation: 7
Generation: 8
New Best Solution Fitness: 118616
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.155556 
Mean sub-tour choices: 0.266667 
Best Solution Fitness: 118616 
--------------------------------------------- 
