--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 119044
New Best Solution Fitness: 119031
Generation: 3
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 118789
New Best Solution Fitness: 118715
Generation: 7
Generation: 8
New Best Solution Fitness: 118682
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.133333 
Mean sub-tour choices: 0.255556 
Best Solution Fitness: 118682 
--------------------------------------------- 
