--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
Generation: 3
Generation: 4
Generation: 5
New Best Solution Fitness: 118914
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 118796
Generation: 9
New Best Solution Fitness: 118282
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.0555556 
Mean sub-tour choices: 0.1 
Best Solution Fitness: 118282 
--------------------------------------------- 
