--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 119876
New Best Solution Fitness: 119393
Generation: 3
New Best Solution Fitness: 119178
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 118988
New Best Solution Fitness: 118914
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 118780
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.155556 
Mean sub-tour choices: 0.244444 
Best Solution Fitness: 118780 
--------------------------------------------- 
