--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 119034
Generation: 3
New Best Solution Fitness: 118710
Generation: 4
New Best Solution Fitness: 118657
Generation: 5
Generation: 6
New Best Solution Fitness: 118616
Generation: 7
New Best Solution Fitness: 118497
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 118423
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.0222222 
Mean sub-tour choices: 0.0333333 
Best Solution Fitness: 118423 
--------------------------------------------- 
