--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 120035
Generation: 3
New Best Solution Fitness: 119894
Generation: 4
Generation: 5
New Best Solution Fitness: 119489
Generation: 6
New Best Solution Fitness: 119303
Generation: 7
New Best Solution Fitness: 119132
Generation: 8
New Best Solution Fitness: 118856
Generation: 9
Generation: 10
New Best Solution Fitness: 118584
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.277778 
Mean sub-tour choices: 0.477778 
Best Solution Fitness: 118584 
--------------------------------------------- 
