--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59163
New Best Solution Fitness: 59147
New Best Solution Fitness: 59133
New Best Solution Fitness: 59122
Generation: 3
New Best Solution Fitness: 59091
New Best Solution Fitness: 59070
New Best Solution Fitness: 59066
Generation: 4
New Best Solution Fitness: 58994
New Best Solution Fitness: 58984
Generation: 5
Generation: 6
New Best Solution Fitness: 58963
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 58909
New Best Solution Fitness: 58874
New Best Solution Fitness: 58692
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.25556 
Mean sub-tour choices: 2.05556 
Best Solution Fitness: 58692 
--------------------------------------------- 
