--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59670
New Best Solution Fitness: 59655
New Best Solution Fitness: 59629
Generation: 3
New Best Solution Fitness: 59016
New Best Solution Fitness: 59013
Generation: 4
New Best Solution Fitness: 59011
New Best Solution Fitness: 58998
Generation: 5
New Best Solution Fitness: 58991
New Best Solution Fitness: 58989
Generation: 6
New Best Solution Fitness: 58880
New Best Solution Fitness: 58865
New Best Solution Fitness: 58862
Generation: 7
New Best Solution Fitness: 58842
Generation: 8
New Best Solution Fitness: 58838
New Best Solution Fitness: 58806
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.62222 
Mean sub-tour choices: 2.28889 
Best Solution Fitness: 58806 
--------------------------------------------- 
