--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59416
New Best Solution Fitness: 59251
New Best Solution Fitness: 59240
Generation: 3
New Best Solution Fitness: 59113
New Best Solution Fitness: 59112
New Best Solution Fitness: 59096
New Best Solution Fitness: 59090
Generation: 4
New Best Solution Fitness: 59060
New Best Solution Fitness: 59045
New Best Solution Fitness: 58992
Generation: 5
New Best Solution Fitness: 58977
New Best Solution Fitness: 58941
Generation: 6
New Best Solution Fitness: 58926
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.18889 
Mean sub-tour choices: 1.97778 
Best Solution Fitness: 58926 
--------------------------------------------- 
