--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 58933
New Best Solution Fitness: 58921
New Best Solution Fitness: 58884
Generation: 3
New Best Solution Fitness: 58592
New Best Solution Fitness: 58588
Generation: 4
New Best Solution Fitness: 58536
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.8 
Mean sub-tour choices: 1.98889 
Best Solution Fitness: 58536 
--------------------------------------------- 
