--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59230
New Best Solution Fitness: 59201
Generation: 3
New Best Solution Fitness: 59059
New Best Solution Fitness: 59051
Generation: 4
Generation: 5
New Best Solution Fitness: 58980
New Best Solution Fitness: 58959
Generation: 6
Generation: 7
New Best Solution Fitness: 58937
Generation: 8
New Best Solution Fitness: 58915
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.55556 
Mean sub-tour choices: 1.35556 
Best Solution Fitness: 58915 
--------------------------------------------- 
