--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59158
New Best Solution Fitness: 58947
Generation: 3
New Best Solution Fitness: 58656
New Best Solution Fitness: 58648
New Best Solution Fitness: 58610
Generation: 4
New Best Solution Fitness: 58454
New Best Solution Fitness: 58375
Generation: 5
New Best Solution Fitness: 58355
New Best Solution Fitness: 58347
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 58330
Generation: 9
Generation: 10
New Best Solution Fitness: 58178
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.44444 
Mean sub-tour choices: 1.42222 
Best Solution Fitness: 58178 
--------------------------------------------- 
