--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59833
New Best Solution Fitness: 59777
Generation: 3
New Best Solution Fitness: 59554
New Best Solution Fitness: 59543
New Best Solution Fitness: 59542
New Best Solution Fitness: 59530
Generation: 4
New Best Solution Fitness: 59528
Generation: 5
New Best Solution Fitness: 59527
New Best Solution Fitness: 59510
New Best Solution Fitness: 59506
Generation: 6
New Best Solution Fitness: 59400
Generation: 7
New Best Solution Fitness: 59202
New Best Solution Fitness: 59163
Generation: 8
New Best Solution Fitness: 58891
New Best Solution Fitness: 58870
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.05556 
Mean sub-tour choices: 2.18889 
Best Solution Fitness: 58870 
--------------------------------------------- 
