--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59822
New Best Solution Fitness: 59688
New Best Solution Fitness: 59569
Generation: 3
New Best Solution Fitness: 59438
New Best Solution Fitness: 59333
Generation: 4
New Best Solution Fitness: 59332
New Best Solution Fitness: 59330
Generation: 5
New Best Solution Fitness: 59319
Generation: 6
New Best Solution Fitness: 59129
New Best Solution Fitness: 59111
New Best Solution Fitness: 59054
Generation: 7
New Best Solution Fitness: 58656
New Best Solution Fitness: 58653
New Best Solution Fitness: 58634
Generation: 8
New Best Solution Fitness: 58557
New Best Solution Fitness: 58554
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.85556 
Mean sub-tour choices: 2.21111 
Best Solution Fitness: 58554 
--------------------------------------------- 
