--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59042
New Best Solution Fitness: 59026
New Best Solution Fitness: 59023
New Best Solution Fitness: 58996
New Best Solution Fitness: 58977
Generation: 3
New Best Solution Fitness: 58853
New Best Solution Fitness: 58838
New Best Solution Fitness: 58799
Generation: 4
New Best Solution Fitness: 58769
New Best Solution Fitness: 58729
Generation: 5
Generation: 6
New Best Solution Fitness: 58702
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.51111 
Mean sub-tour choices: 2.6 
Best Solution Fitness: 58702 
--------------------------------------------- 
