--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59383
New Best Solution Fitness: 59294
New Best Solution Fitness: 59291
New Best Solution Fitness: 59287
Generation: 3
New Best Solution Fitness: 58901
New Best Solution Fitness: 58858
New Best Solution Fitness: 58689
Generation: 4
New Best Solution Fitness: 58668
Generation: 5
New Best Solution Fitness: 58658
New Best Solution Fitness: 58647
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.38889 
Mean sub-tour choices: 3.61111 
Best Solution Fitness: 58647 
--------------------------------------------- 
