--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59202
New Best Solution Fitness: 59126
New Best Solution Fitness: 59078
Generation: 3
New Best Solution Fitness: 58763
New Best Solution Fitness: 58752
Generation: 4
New Best Solution Fitness: 58750
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 58606
New Best Solution Fitness: 58601
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.41111 
Mean sub-tour choices: 3.23333 
Best Solution Fitness: 58601 
--------------------------------------------- 
