--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59606
New Best Solution Fitness: 59589
New Best Solution Fitness: 59584
New Best Solution Fitness: 59508
New Best Solution Fitness: 59431
Generation: 3
New Best Solution Fitness: 59328
New Best Solution Fitness: 59308
New Best Solution Fitness: 59249
Generation: 4
New Best Solution Fitness: 59239
New Best Solution Fitness: 59236
Generation: 5
New Best Solution Fitness: 59223
New Best Solution Fitness: 59217
Generation: 6
New Best Solution Fitness: 59204
Generation: 7
New Best Solution Fitness: 59198
Generation: 8
Generation: 9
New Best Solution Fitness: 59196
Generation: 10
New Best Solution Fitness: 59193
New Best Solution Fitness: 58984
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.81111 
Mean sub-tour choices: 3.64444 
Best Solution Fitness: 58984 
--------------------------------------------- 
