--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59211
New Best Solution Fitness: 59167
New Best Solution Fitness: 59141
Generation: 3
New Best Solution Fitness: 59037
New Best Solution Fitness: 59019
New Best Solution Fitness: 58981
New Best Solution Fitness: 58971
New Best Solution Fitness: 58889
Generation: 4
New Best Solution Fitness: 58849
New Best Solution Fitness: 58847
New Best Solution Fitness: 58837
Generation: 5
New Best Solution Fitness: 58835
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.92222 
Mean sub-tour choices: 3.18889 
Best Solution Fitness: 58835 
--------------------------------------------- 
