--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59015
New Best Solution Fitness: 58889
New Best Solution Fitness: 58813
New Best Solution Fitness: 58811
New Best Solution Fitness: 58803
Generation: 3
New Best Solution Fitness: 58749
New Best Solution Fitness: 58745
New Best Solution Fitness: 58741
New Best Solution Fitness: 58737
Generation: 4
New Best Solution Fitness: 58728
New Best Solution Fitness: 58724
Generation: 5
New Best Solution Fitness: 58721
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.42222 
Mean sub-tour choices: 2.4 
Best Solution Fitness: 58721 
--------------------------------------------- 
