--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59446
New Best Solution Fitness: 59411
New Best Solution Fitness: 59239
Generation: 3
New Best Solution Fitness: 58629
New Best Solution Fitness: 58625
Generation: 4
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 58603
Generation: 9
New Best Solution Fitness: 58317
New Best Solution Fitness: 58315
New Best Solution Fitness: 58314
Generation: 10
New Best Solution Fitness: 58313
New Best Solution Fitness: 58311
New Best Solution Fitness: 58301
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.63333 
Mean sub-tour choices: 1.34444 
Best Solution Fitness: 58301 
--------------------------------------------- 
