--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59340
New Best Solution Fitness: 59339
New Best Solution Fitness: 59306
Generation: 3
New Best Solution Fitness: 59208
New Best Solution Fitness: 59169
Generation: 4
New Best Solution Fitness: 59027
Generation: 5
New Best Solution Fitness: 58997
New Best Solution Fitness: 58990
Generation: 6
New Best Solution Fitness: 58969
New Best Solution Fitness: 58943
Generation: 7
New Best Solution Fitness: 58834
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.7 
Mean sub-tour choices: 2.07778 
Best Solution Fitness: 58834 
--------------------------------------------- 
