--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59945
New Best Solution Fitness: 59944
New Best Solution Fitness: 59930
Generation: 3
New Best Solution Fitness: 59730
New Best Solution Fitness: 59708
New Best Solution Fitness: 59648
Generation: 4
New Best Solution Fitness: 59489
New Best Solution Fitness: 59476
New Best Solution Fitness: 59474
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 59433
Generation: 8
New Best Solution Fitness: 59423
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.72222 
Mean sub-tour choices: 2.28889 
Best Solution Fitness: 59423 
--------------------------------------------- 
