--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59080
New Best Solution Fitness: 59079
New Best Solution Fitness: 58973
Generation: 3
New Best Solution Fitness: 58698
Generation: 4
New Best Solution Fitness: 58655
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.46667 
Mean sub-tour choices: 2.43333 
Best Solution Fitness: 58655 
--------------------------------------------- 
