--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59192
New Best Solution Fitness: 59100
New Best Solution Fitness: 59094
New Best Solution Fitness: 59085
Generation: 3
New Best Solution Fitness: 58845
New Best Solution Fitness: 58830
Generation: 4
New Best Solution Fitness: 58808
Generation: 5
Generation: 6
New Best Solution Fitness: 58807
Generation: 7
Generation: 8
New Best Solution Fitness: 58735
New Best Solution Fitness: 58703
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.3 
Mean sub-tour choices: 1.94444 
Best Solution Fitness: 58703 
--------------------------------------------- 
