--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 58745
New Best Solution Fitness: 58730
Generation: 3
New Best Solution Fitness: 58654
New Best Solution Fitness: 58649
New Best Solution Fitness: 58590
Generation: 4
New Best Solution Fitness: 58519
Generation: 5
New Best Solution Fitness: 58477
New Best Solution Fitness: 58408
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.9 
Mean sub-tour choices: 2.31111 
Best Solution Fitness: 58408 
--------------------------------------------- 
