--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59536
New Best Solution Fitness: 59530
New Best Solution Fitness: 59332
New Best Solution Fitness: 59328
Generation: 3
New Best Solution Fitness: 59131
New Best Solution Fitness: 58988
Generation: 4
New Best Solution Fitness: 58962
Generation: 5
New Best Solution Fitness: 58959
Generation: 6
New Best Solution Fitness: 58958
Generation: 7
Generation: 8
New Best Solution Fitness: 58952
Generation: 9
New Best Solution Fitness: 58771
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.71111 
Mean sub-tour choices: 1.93333 
Best Solution Fitness: 58771 
--------------------------------------------- 
