--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59795
New Best Solution Fitness: 59793
New Best Solution Fitness: 59765
New Best Solution Fitness: 59692
Generation: 3
New Best Solution Fitness: 59158
New Best Solution Fitness: 59119
New Best Solution Fitness: 59104
Generation: 4
New Best Solution Fitness: 59090
New Best Solution Fitness: 59024
Generation: 5
New Best Solution Fitness: 59013
New Best Solution Fitness: 59001
Generation: 6
New Best Solution Fitness: 59000
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.64444 
Mean sub-tour choices: 2.26667 
Best Solution Fitness: 59000 
--------------------------------------------- 
