--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59405
New Best Solution Fitness: 59404
New Best Solution Fitness: 59394
New Best Solution Fitness: 59374
Generation: 3
New Best Solution Fitness: 58999
New Best Solution Fitness: 58983
New Best Solution Fitness: 58935
Generation: 4
New Best Solution Fitness: 58919
New Best Solution Fitness: 58914
Generation: 5
New Best Solution Fitness: 58886
Generation: 6
New Best Solution Fitness: 58876
Generation: 7
New Best Solution Fitness: 58795
Generation: 8
New Best Solution Fitness: 58781
Generation: 9
Generation: 10
New Best Solution Fitness: 58741
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.83333 
Mean sub-tour choices: 1.82222 
Best Solution Fitness: 58741 
--------------------------------------------- 
