--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59609
New Best Solution Fitness: 59605
New Best Solution Fitness: 59589
New Best Solution Fitness: 59587
New Best Solution Fitness: 59564
Generation: 3
New Best Solution Fitness: 59179
New Best Solution Fitness: 59164
New Best Solution Fitness: 59141
Generation: 4
New Best Solution Fitness: 59130
New Best Solution Fitness: 59123
New Best Solution Fitness: 59113
Generation: 5
New Best Solution Fitness: 59111
Generation: 6
New Best Solution Fitness: 58864
New Best Solution Fitness: 58862
Generation: 7
New Best Solution Fitness: 58847
New Best Solution Fitness: 58787
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.06667 
Mean sub-tour choices: 2.91111 
Best Solution Fitness: 58787 
--------------------------------------------- 
