--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 58748
New Best Solution Fitness: 58670
Generation: 3
New Best Solution Fitness: 58576
New Best Solution Fitness: 58574
Generation: 4
New Best Solution Fitness: 58509
New Best Solution Fitness: 58464
New Best Solution Fitness: 58448
Generation: 5
New Best Solution Fitness: 58431
Generation: 6
New Best Solution Fitness: 58421
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 58406
Generation: 10
New Best Solution Fitness: 58404
New Best Solution Fitness: 58352
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.63333 
Mean sub-tour choices: 3.61111 
Best Solution Fitness: 58352 
--------------------------------------------- 
