--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59514
New Best Solution Fitness: 59452
New Best Solution Fitness: 59392
Generation: 3
New Best Solution Fitness: 59092
New Best Solution Fitness: 59087
New Best Solution Fitness: 59079
Generation: 4
New Best Solution Fitness: 58919
New Best Solution Fitness: 58907
Generation: 5
New Best Solution Fitness: 58905
Generation: 6
New Best Solution Fitness: 58899
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.04444 
Mean sub-tour choices: 2.43333 
Best Solution Fitness: 58899 
--------------------------------------------- 
