--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 58959
New Best Solution Fitness: 58851
Generation: 3
New Best Solution Fitness: 58735
New Best Solution Fitness: 58733
New Best Solution Fitness: 58704
Generation: 4
New Best Solution Fitness: 58702
New Best Solution Fitness: 58602
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 58592
Generation: 8
New Best Solution Fitness: 58590
Generation: 9
New Best Solution Fitness: 58588
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.85556 
Mean sub-tour choices: 2.16667 
Best Solution Fitness: 58588 
--------------------------------------------- 
