--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 58913
New Best Solution Fitness: 58856
New Best Solution Fitness: 58812
New Best Solution Fitness: 58712
Generation: 3
New Best Solution Fitness: 58494
Generation: 4
New Best Solution Fitness: 58351
Generation: 5
New Best Solution Fitness: 58301
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 58282
New Best Solution Fitness: 58280
New Best Solution Fitness: 58258
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.15556 
Mean sub-tour choices: 2.52222 
Best Solution Fitness: 58258 
--------------------------------------------- 
