--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59560
New Best Solution Fitness: 59508
Generation: 3
New Best Solution Fitness: 59222
New Best Solution Fitness: 59179
New Best Solution Fitness: 59174
Generation: 4
New Best Solution Fitness: 59135
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 59099
Generation: 10
New Best Solution Fitness: 59067
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.86667 
Mean sub-tour choices: 1.77778 
Best Solution Fitness: 59067 
--------------------------------------------- 
