--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 58835
New Best Solution Fitness: 58803
New Best Solution Fitness: 58752
New Best Solution Fitness: 58674
Generation: 3
New Best Solution Fitness: 58671
Generation: 4
New Best Solution Fitness: 58651
New Best Solution Fitness: 58648
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 58437
New Best Solution Fitness: 58428
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.24444 
Mean sub-tour choices: 2.42222 
Best Solution Fitness: 58428 
--------------------------------------------- 
