--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59709
New Best Solution Fitness: 59646
Generation: 3
New Best Solution Fitness: 58776
New Best Solution Fitness: 58747
New Best Solution Fitness: 58737
New Best Solution Fitness: 58721
Generation: 4
New Best Solution Fitness: 58714
New Best Solution Fitness: 58677
Generation: 5
New Best Solution Fitness: 58655
Generation: 6
New Best Solution Fitness: 58648
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.84444 
Mean sub-tour choices: 2.63333 
Best Solution Fitness: 58648 
--------------------------------------------- 
