--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 58673
New Best Solution Fitness: 58672
New Best Solution Fitness: 58640
Generation: 3
New Best Solution Fitness: 58634
New Best Solution Fitness: 58576
Generation: 4
New Best Solution Fitness: 58559
Generation: 5
New Best Solution Fitness: 58557
Generation: 6
New Best Solution Fitness: 58536
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 58526
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.55556 
Mean sub-tour choices: 2.64444 
Best Solution Fitness: 58526 
--------------------------------------------- 
