--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 58965
New Best Solution Fitness: 58958
New Best Solution Fitness: 58900
Generation: 3
New Best Solution Fitness: 58815
New Best Solution Fitness: 58809
New Best Solution Fitness: 58808
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 58791
Generation: 7
New Best Solution Fitness: 58713
New Best Solution Fitness: 58711
New Best Solution Fitness: 58705
Generation: 8
New Best Solution Fitness: 58658
New Best Solution Fitness: 58656
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.1 
Mean sub-tour choices: 1.14444 
Best Solution Fitness: 58656 
--------------------------------------------- 
