--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59289
New Best Solution Fitness: 59274
New Best Solution Fitness: 59256
Generation: 3
New Best Solution Fitness: 59061
New Best Solution Fitness: 59058
New Best Solution Fitness: 59046
New Best Solution Fitness: 58980
Generation: 4
New Best Solution Fitness: 58661
New Best Solution Fitness: 58650
Generation: 5
New Best Solution Fitness: 58562
New Best Solution Fitness: 58553
Generation: 6
New Best Solution Fitness: 58479
New Best Solution Fitness: 58464
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 58449
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.96667 
Mean sub-tour choices: 2.26667 
Best Solution Fitness: 58449 
--------------------------------------------- 
