--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59248
New Best Solution Fitness: 59246
Generation: 3
New Best Solution Fitness: 58957
New Best Solution Fitness: 58928
Generation: 4
New Best Solution Fitness: 58890
Generation: 5
New Best Solution Fitness: 58800
Generation: 6
New Best Solution Fitness: 58798
Generation: 7
New Best Solution Fitness: 58783
New Best Solution Fitness: 58771
Generation: 8
New Best Solution Fitness: 58756
Generation: 9
New Best Solution Fitness: 58673
New Best Solution Fitness: 58620
Generation: 10
New Best Solution Fitness: 58602
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.32222 
Mean sub-tour choices: 1.74444 
Best Solution Fitness: 58602 
--------------------------------------------- 
