--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 58702
New Best Solution Fitness: 58697
New Best Solution Fitness: 58548
Generation: 3
New Best Solution Fitness: 58428
New Best Solution Fitness: 58423
Generation: 4
New Best Solution Fitness: 58414
Generation: 5
New Best Solution Fitness: 58384
New Best Solution Fitness: 58369
New Best Solution Fitness: 58367
New Best Solution Fitness: 58288
Generation: 6
New Best Solution Fitness: 58271
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 58256
Generation: 10
New Best Solution Fitness: 58190
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.28889 
Mean sub-tour choices: 1.71111 
Best Solution Fitness: 58190 
--------------------------------------------- 
