--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59648
New Best Solution Fitness: 59591
Generation: 3
New Best Solution Fitness: 59169
New Best Solution Fitness: 59152
Generation: 4
New Best Solution Fitness: 58882
Generation: 5
Generation: 6
New Best Solution Fitness: 58559
New Best Solution Fitness: 58556
Generation: 7
New Best Solution Fitness: 58547
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.57778 
Mean sub-tour choices: 2.07778 
Best Solution Fitness: 58547 
--------------------------------------------- 
