--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59325
New Best Solution Fitness: 59293
New Best Solution Fitness: 59276
New Best Solution Fitness: 59095
Generation: 3
New Best Solution Fitness: 59051
New Best Solution Fitness: 59019
New Best Solution Fitness: 59002
Generation: 4
New Best Solution Fitness: 58927
New Best Solution Fitness: 58887
New Best Solution Fitness: 58886
Generation: 5
New Best Solution Fitness: 58786
New Best Solution Fitness: 58782
Generation: 6
New Best Solution Fitness: 58775
Generation: 7
Generation: 8
New Best Solution Fitness: 58644
New Best Solution Fitness: 58521
Generation: 9
New Best Solution Fitness: 58476
New Best Solution Fitness: 58444
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.01111 
Mean sub-tour choices: 2.4 
Best Solution Fitness: 58444 
--------------------------------------------- 
