--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59953
New Best Solution Fitness: 59410
Generation: 3
New Best Solution Fitness: 58751
New Best Solution Fitness: 58735
Generation: 4
New Best Solution Fitness: 58677
New Best Solution Fitness: 58670
New Best Solution Fitness: 58656
Generation: 5
New Best Solution Fitness: 58649
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 58623
New Best Solution Fitness: 58604
New Best Solution Fitness: 58595
Generation: 9
New Best Solution Fitness: 58472
New Best Solution Fitness: 58453
Generation: 10
New Best Solution Fitness: 58444
New Best Solution Fitness: 58440
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.08889 
Mean sub-tour choices: 1.84444 
Best Solution Fitness: 58440 
--------------------------------------------- 
