--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59359
New Best Solution Fitness: 59357
New Best Solution Fitness: 59216
Generation: 3
New Best Solution Fitness: 58962
New Best Solution Fitness: 58821
New Best Solution Fitness: 58814
Generation: 4
New Best Solution Fitness: 58812
New Best Solution Fitness: 58810
Generation: 5
New Best Solution Fitness: 58808
Generation: 6
New Best Solution Fitness: 58806
New Best Solution Fitness: 58792
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.81111 
Mean sub-tour choices: 1.52222 
Best Solution Fitness: 58792 
--------------------------------------------- 
