--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59727
New Best Solution Fitness: 59504
New Best Solution Fitness: 59495
Generation: 3
New Best Solution Fitness: 59361
New Best Solution Fitness: 59334
Generation: 4
New Best Solution Fitness: 59201
New Best Solution Fitness: 59184
New Best Solution Fitness: 59168
New Best Solution Fitness: 59139
Generation: 5
New Best Solution Fitness: 59109
New Best Solution Fitness: 59076
Generation: 6
New Best Solution Fitness: 59046
New Best Solution Fitness: 59031
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 59001
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.26667 
Mean sub-tour choices: 2.75556 
Best Solution Fitness: 59001 
--------------------------------------------- 
