--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59500
New Best Solution Fitness: 59439
New Best Solution Fitness: 59104
Generation: 3
New Best Solution Fitness: 58949
New Best Solution Fitness: 58946
New Best Solution Fitness: 58942
Generation: 4
New Best Solution Fitness: 58904
New Best Solution Fitness: 58888
Generation: 5
New Best Solution Fitness: 58885
Generation: 6
New Best Solution Fitness: 58713
New Best Solution Fitness: 58710
Generation: 7
New Best Solution Fitness: 58486
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.9 
Mean sub-tour choices: 1.82222 
Best Solution Fitness: 58486 
--------------------------------------------- 
