--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59725
New Best Solution Fitness: 59568
New Best Solution Fitness: 59528
Generation: 3
New Best Solution Fitness: 59128
New Best Solution Fitness: 59123
Generation: 4
New Best Solution Fitness: 59020
New Best Solution Fitness: 59018
New Best Solution Fitness: 58998
Generation: 5
New Best Solution Fitness: 58953
New Best Solution Fitness: 58951
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.76667 
Mean sub-tour choices: 2.56667 
Best Solution Fitness: 58951 
--------------------------------------------- 
