--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59512
New Best Solution Fitness: 59498
New Best Solution Fitness: 59377
Generation: 3
New Best Solution Fitness: 59257
New Best Solution Fitness: 59256
Generation: 4
New Best Solution Fitness: 59189
New Best Solution Fitness: 59157
New Best Solution Fitness: 59156
Generation: 5
New Best Solution Fitness: 59152
New Best Solution Fitness: 59140
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 59080
New Best Solution Fitness: 59077
Generation: 9
New Best Solution Fitness: 58996
New Best Solution Fitness: 58989
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.42222 
Mean sub-tour choices: 1.93333 
Best Solution Fitness: 58989 
--------------------------------------------- 
