--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 58987
New Best Solution Fitness: 58973
New Best Solution Fitness: 58964
New Best Solution Fitness: 58920
New Best Solution Fitness: 58910
Generation: 3
New Best Solution Fitness: 58715
New Best Solution Fitness: 58712
New Best Solution Fitness: 58711
New Best Solution Fitness: 58554
New Best Solution Fitness: 58500
Generation: 4
New Best Solution Fitness: 58468
New Best Solution Fitness: 58463
New Best Solution Fitness: 58405
Generation: 5
Generation: 6
New Best Solution Fitness: 58373
New Best Solution Fitness: 58243
Generation: 7
New Best Solution Fitness: 58242
New Best Solution Fitness: 58232
New Best Solution Fitness: 58209
Generation: 8
New Best Solution Fitness: 58199
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.5 
Mean sub-tour choices: 3.45556 
Best Solution Fitness: 58199 
--------------------------------------------- 
