--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59341
New Best Solution Fitness: 59332
New Best Solution Fitness: 59296
Generation: 3
New Best Solution Fitness: 59153
New Best Solution Fitness: 59145
Generation: 4
New Best Solution Fitness: 59138
New Best Solution Fitness: 59137
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.38889 
Mean sub-tour choices: 2.16667 
Best Solution Fitness: 59137 
--------------------------------------------- 
