--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 58787
New Best Solution Fitness: 58773
New Best Solution Fitness: 58749
New Best Solution Fitness: 58715
Generation: 3
New Best Solution Fitness: 58621
New Best Solution Fitness: 58610
New Best Solution Fitness: 58581
Generation: 4
New Best Solution Fitness: 58536
New Best Solution Fitness: 58496
Generation: 5
New Best Solution Fitness: 58363
Generation: 6
New Best Solution Fitness: 58359
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.91111 
Mean sub-tour choices: 3.65556 
Best Solution Fitness: 58359 
--------------------------------------------- 
