--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 60641
New Best Solution Fitness: 60613
New Best Solution Fitness: 60493
Generation: 3
New Best Solution Fitness: 59464
New Best Solution Fitness: 59369
New Best Solution Fitness: 59287
Generation: 4
New Best Solution Fitness: 59195
New Best Solution Fitness: 59186
Generation: 5
New Best Solution Fitness: 59183
Generation: 6
New Best Solution Fitness: 59182
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 59160
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.42222 
Mean sub-tour choices: 2.96667 
Best Solution Fitness: 59160 
--------------------------------------------- 
