--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59356
New Best Solution Fitness: 59313
Generation: 3
New Best Solution Fitness: 59238
New Best Solution Fitness: 59231
New Best Solution Fitness: 59230
New Best Solution Fitness: 59169
Generation: 4
New Best Solution Fitness: 59003
New Best Solution Fitness: 58934
New Best Solution Fitness: 58776
Generation: 5
New Best Solution Fitness: 58739
New Best Solution Fitness: 58699
New Best Solution Fitness: 58670
Generation: 6
New Best Solution Fitness: 58669
New Best Solution Fitness: 58630
Generation: 7
New Best Solution Fitness: 58604
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 58487
New Best Solution Fitness: 58436
New Best Solution Fitness: 58432
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.75556 
Mean sub-tour choices: 2.16667 
Best Solution Fitness: 58432 
--------------------------------------------- 
