--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59621
New Best Solution Fitness: 59588
New Best Solution Fitness: 59571
Generation: 3
New Best Solution Fitness: 59089
New Best Solution Fitness: 59087
New Best Solution Fitness: 59069
Generation: 4
New Best Solution Fitness: 58901
New Best Solution Fitness: 58892
New Best Solution Fitness: 58887
Generation: 5
New Best Solution Fitness: 58886
Generation: 6
New Best Solution Fitness: 58769
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.4 
Mean sub-tour choices: 2.5 
Best Solution Fitness: 58769 
--------------------------------------------- 
