--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59437
New Best Solution Fitness: 59402
New Best Solution Fitness: 59274
New Best Solution Fitness: 59256
Generation: 3
New Best Solution Fitness: 58774
New Best Solution Fitness: 58766
Generation: 4
New Best Solution Fitness: 58716
New Best Solution Fitness: 58699
New Best Solution Fitness: 58688
Generation: 5
New Best Solution Fitness: 58671
Generation: 6
New Best Solution Fitness: 58561
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.75556 
Mean sub-tour choices: 2.62222 
Best Solution Fitness: 58561 
--------------------------------------------- 
