--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59472
New Best Solution Fitness: 59456
New Best Solution Fitness: 59452
New Best Solution Fitness: 59447
Generation: 3
New Best Solution Fitness: 58992
New Best Solution Fitness: 58940
New Best Solution Fitness: 58865
Generation: 4
New Best Solution Fitness: 58851
New Best Solution Fitness: 58849
New Best Solution Fitness: 58766
Generation: 5
New Best Solution Fitness: 58764
Generation: 6
New Best Solution Fitness: 58756
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.03333 
Mean sub-tour choices: 1.57778 
Best Solution Fitness: 58756 
--------------------------------------------- 
