--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 58279
New Best Solution Fitness: 58231
New Best Solution Fitness: 58173
New Best Solution Fitness: 58162
Generation: 3
New Best Solution Fitness: 58015
New Best Solution Fitness: 57909
Generation: 4
New Best Solution Fitness: 57894
Generation: 5
New Best Solution Fitness: 57886
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.36667 
Mean sub-tour choices: 2.34444 
Best Solution Fitness: 57886 
--------------------------------------------- 
