--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59386
New Best Solution Fitness: 59311
New Best Solution Fitness: 59248
Generation: 3
New Best Solution Fitness: 59085
New Best Solution Fitness: 59053
Generation: 4
New Best Solution Fitness: 59045
Generation: 5
New Best Solution Fitness: 59023
New Best Solution Fitness: 59001
Generation: 6
New Best Solution Fitness: 58976
Generation: 7
New Best Solution Fitness: 58898
Generation: 8
Generation: 9
New Best Solution Fitness: 58757
New Best Solution Fitness: 58725
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.37778 
Mean sub-tour choices: 2.3 
Best Solution Fitness: 58725 
--------------------------------------------- 
