--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59297
New Best Solution Fitness: 59260
New Best Solution Fitness: 59242
New Best Solution Fitness: 59156
Generation: 3
New Best Solution Fitness: 59074
New Best Solution Fitness: 59059
Generation: 4
New Best Solution Fitness: 58912
Generation: 5
New Best Solution Fitness: 58716
New Best Solution Fitness: 58665
Generation: 6
New Best Solution Fitness: 58647
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 58397
New Best Solution Fitness: 58299
Generation: 10
New Best Solution Fitness: 58232
New Best Solution Fitness: 58217
New Best Solution Fitness: 58183
New Best Solution Fitness: 58182
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.34444 
Mean sub-tour choices: 1.84444 
Best Solution Fitness: 58182 
--------------------------------------------- 
