--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59614
New Best Solution Fitness: 59555
New Best Solution Fitness: 59380
New Best Solution Fitness: 59297
Generation: 3
New Best Solution Fitness: 59018
New Best Solution Fitness: 58919
Generation: 4
New Best Solution Fitness: 58881
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 58839
Generation: 8
New Best Solution Fitness: 58838
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.72222 
Mean sub-tour choices: 2.24444 
Best Solution Fitness: 58838 
--------------------------------------------- 
