--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59084
New Best Solution Fitness: 59043
New Best Solution Fitness: 59041
New Best Solution Fitness: 58997
Generation: 3
New Best Solution Fitness: 58772
New Best Solution Fitness: 58764
New Best Solution Fitness: 58736
New Best Solution Fitness: 58721
Generation: 4
New Best Solution Fitness: 58713
New Best Solution Fitness: 58638
Generation: 5
New Best Solution Fitness: 58621
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 58606
Generation: 10
New Best Solution Fitness: 58601
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.08889 
Mean sub-tour choices: 2.44444 
Best Solution Fitness: 58601 
--------------------------------------------- 
