--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59665
New Best Solution Fitness: 59626
New Best Solution Fitness: 59601
Generation: 3
New Best Solution Fitness: 59300
New Best Solution Fitness: 59247
New Best Solution Fitness: 59204
Generation: 4
New Best Solution Fitness: 59076
New Best Solution Fitness: 59057
Generation: 5
New Best Solution Fitness: 58998
New Best Solution Fitness: 58991
New Best Solution Fitness: 58990
Generation: 6
Generation: 7
New Best Solution Fitness: 58918
New Best Solution Fitness: 58836
Generation: 8
New Best Solution Fitness: 58827
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.07778 
Mean sub-tour choices: 2.47778 
Best Solution Fitness: 58827 
--------------------------------------------- 
