--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59461
New Best Solution Fitness: 59446
New Best Solution Fitness: 59370
New Best Solution Fitness: 59345
Generation: 3
New Best Solution Fitness: 59176
New Best Solution Fitness: 59162
New Best Solution Fitness: 59161
Generation: 4
New Best Solution Fitness: 59082
New Best Solution Fitness: 59068
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 59067
Generation: 9
New Best Solution Fitness: 58993
Generation: 10
New Best Solution Fitness: 58991
New Best Solution Fitness: 58940
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.01111 
Mean sub-tour choices: 2.01111 
Best Solution Fitness: 58940 
--------------------------------------------- 
