--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59879
New Best Solution Fitness: 59702
New Best Solution Fitness: 59684
Generation: 3
New Best Solution Fitness: 59613
New Best Solution Fitness: 59560
Generation: 4
New Best Solution Fitness: 59235
New Best Solution Fitness: 59221
New Best Solution Fitness: 59092
Generation: 5
New Best Solution Fitness: 59062
New Best Solution Fitness: 59009
New Best Solution Fitness: 58933
Generation: 6
New Best Solution Fitness: 58931
New Best Solution Fitness: 58917
Generation: 7
New Best Solution Fitness: 58895
New Best Solution Fitness: 58879
Generation: 8
New Best Solution Fitness: 58864
New Best Solution Fitness: 58857
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.96667 
Mean sub-tour choices: 2.03333 
Best Solution Fitness: 58857 
--------------------------------------------- 
