--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59268
New Best Solution Fitness: 58873
Generation: 3
New Best Solution Fitness: 58741
New Best Solution Fitness: 58737
New Best Solution Fitness: 58735
Generation: 4
New Best Solution Fitness: 58705
New Best Solution Fitness: 58695
Generation: 5
New Best Solution Fitness: 58680
New Best Solution Fitness: 58632
Generation: 6
New Best Solution Fitness: 58631
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.45556 
Mean sub-tour choices: 3.55556 
Best Solution Fitness: 58631 
--------------------------------------------- 
