--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59616
New Best Solution Fitness: 59510
Generation: 3
New Best Solution Fitness: 59309
New Best Solution Fitness: 59304
New Best Solution Fitness: 59298
New Best Solution Fitness: 59282
Generation: 4
New Best Solution Fitness: 59280
New Best Solution Fitness: 59271
Generation: 5
New Best Solution Fitness: 59018
Generation: 6
New Best Solution Fitness: 59012
Generation: 7
New Best Solution Fitness: 58926
Generation: 8
New Best Solution Fitness: 58891
Generation: 9
New Best Solution Fitness: 58788
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.05556 
Mean sub-tour choices: 2.63333 
Best Solution Fitness: 58788 
--------------------------------------------- 
