--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59353
New Best Solution Fitness: 59351
New Best Solution Fitness: 59145
Generation: 3
New Best Solution Fitness: 58681
New Best Solution Fitness: 58680
New Best Solution Fitness: 58626
New Best Solution Fitness: 58585
Generation: 4
New Best Solution Fitness: 58412
Generation: 5
New Best Solution Fitness: 58380
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.5 
Mean sub-tour choices: 2.45556 
Best Solution Fitness: 58380 
--------------------------------------------- 
