--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59241
New Best Solution Fitness: 59215
Generation: 3
New Best Solution Fitness: 58932
New Best Solution Fitness: 58764
Generation: 4
New Best Solution Fitness: 58723
New Best Solution Fitness: 58701
Generation: 5
New Best Solution Fitness: 58684
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.74444 
Mean sub-tour choices: 3.05556 
Best Solution Fitness: 58684 
--------------------------------------------- 
