--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59278
New Best Solution Fitness: 59244
New Best Solution Fitness: 59193
New Best Solution Fitness: 59186
Generation: 3
New Best Solution Fitness: 58937
New Best Solution Fitness: 58890
Generation: 4
New Best Solution Fitness: 58880
New Best Solution Fitness: 58866
Generation: 5
New Best Solution Fitness: 58838
New Best Solution Fitness: 58824
Generation: 6
New Best Solution Fitness: 58596
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 5.04444 
Mean sub-tour choices: 2.71111 
Best Solution Fitness: 58596 
--------------------------------------------- 
