--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59914
New Best Solution Fitness: 59902
New Best Solution Fitness: 59837
New Best Solution Fitness: 59819
New Best Solution Fitness: 59746
Generation: 3
New Best Solution Fitness: 59186
New Best Solution Fitness: 59179
New Best Solution Fitness: 59153
Generation: 4
New Best Solution Fitness: 59064
New Best Solution Fitness: 59057
Generation: 5
New Best Solution Fitness: 59053
Generation: 6
New Best Solution Fitness: 59048
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.1 
Mean sub-tour choices: 2.4 
Best Solution Fitness: 59048 
--------------------------------------------- 
