--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59230
New Best Solution Fitness: 59227
New Best Solution Fitness: 59210
Generation: 3
New Best Solution Fitness: 59093
Generation: 4
New Best Solution Fitness: 59041
Generation: 5
New Best Solution Fitness: 58758
New Best Solution Fitness: 58753
New Best Solution Fitness: 58638
New Best Solution Fitness: 58633
Generation: 6
New Best Solution Fitness: 58626
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 58615
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.47778 
Mean sub-tour choices: 1.36667 
Best Solution Fitness: 58615 
--------------------------------------------- 
