--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59646
New Best Solution Fitness: 59640
New Best Solution Fitness: 59607
New Best Solution Fitness: 59475
New Best Solution Fitness: 59431
Generation: 3
New Best Solution Fitness: 59189
New Best Solution Fitness: 59171
New Best Solution Fitness: 59004
Generation: 4
New Best Solution Fitness: 58946
New Best Solution Fitness: 58938
New Best Solution Fitness: 58933
Generation: 5
New Best Solution Fitness: 58932
New Best Solution Fitness: 58924
New Best Solution Fitness: 58918
Generation: 6
New Best Solution Fitness: 58910
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.42222 
Mean sub-tour choices: 2.64444 
Best Solution Fitness: 58910 
--------------------------------------------- 
