--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59241
New Best Solution Fitness: 59216
Generation: 3
New Best Solution Fitness: 58978
New Best Solution Fitness: 58974
Generation: 4
New Best Solution Fitness: 58958
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.31111 
Mean sub-tour choices: 2.18889 
Best Solution Fitness: 58958 
--------------------------------------------- 
