--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59677
New Best Solution Fitness: 59667
Generation: 3
New Best Solution Fitness: 59525
New Best Solution Fitness: 59519
New Best Solution Fitness: 59517
Generation: 4
New Best Solution Fitness: 59046
New Best Solution Fitness: 59045
New Best Solution Fitness: 59044
Generation: 5
New Best Solution Fitness: 58928
Generation: 6
New Best Solution Fitness: 58907
Generation: 7
New Best Solution Fitness: 58897
New Best Solution Fitness: 58759
Generation: 8
Generation: 9
New Best Solution Fitness: 58749
Generation: 10
New Best Solution Fitness: 58667
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.3 
Mean sub-tour choices: 2 
Best Solution Fitness: 58667 
--------------------------------------------- 
