--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 58868
New Best Solution Fitness: 58855
Generation: 3
New Best Solution Fitness: 58605
New Best Solution Fitness: 58592
Generation: 4
New Best Solution Fitness: 58569
Generation: 5
New Best Solution Fitness: 58559
Generation: 6
New Best Solution Fitness: 58448
Generation: 7
New Best Solution Fitness: 58426
Generation: 8
Generation: 9
New Best Solution Fitness: 58419
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.27778 
Mean sub-tour choices: 1.92222 
Best Solution Fitness: 58419 
--------------------------------------------- 
