--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 60026
New Best Solution Fitness: 59998
Generation: 3
New Best Solution Fitness: 59489
New Best Solution Fitness: 59467
New Best Solution Fitness: 59407
Generation: 4
New Best Solution Fitness: 59268
Generation: 5
New Best Solution Fitness: 59267
Generation: 6
New Best Solution Fitness: 59096
Generation: 7
New Best Solution Fitness: 58949
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.18889 
Mean sub-tour choices: 1.74444 
Best Solution Fitness: 58949 
--------------------------------------------- 
