--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59315
New Best Solution Fitness: 59171
New Best Solution Fitness: 59097
Generation: 3
New Best Solution Fitness: 58982
New Best Solution Fitness: 58842
Generation: 4
Generation: 5
New Best Solution Fitness: 58818
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 58782
Generation: 9
Generation: 10
New Best Solution Fitness: 58767
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.54444 
Mean sub-tour choices: 2.61111 
Best Solution Fitness: 58767 
--------------------------------------------- 
