--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59051
New Best Solution Fitness: 59028
New Best Solution Fitness: 59017
New Best Solution Fitness: 58991
Generation: 3
New Best Solution Fitness: 58878
New Best Solution Fitness: 58836
Generation: 4
New Best Solution Fitness: 58823
New Best Solution Fitness: 58771
Generation: 5
New Best Solution Fitness: 58752
New Best Solution Fitness: 58743
Generation: 6
New Best Solution Fitness: 58731
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.25556 
Mean sub-tour choices: 2.2 
Best Solution Fitness: 58731 
--------------------------------------------- 
