--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59157
New Best Solution Fitness: 59135
New Best Solution Fitness: 59069
New Best Solution Fitness: 59042
Generation: 3
New Best Solution Fitness: 58920
New Best Solution Fitness: 58888
New Best Solution Fitness: 58867
New Best Solution Fitness: 58765
Generation: 4
New Best Solution Fitness: 58568
Generation: 5
New Best Solution Fitness: 58547
Generation: 6
New Best Solution Fitness: 58501
Generation: 7
Generation: 8
New Best Solution Fitness: 58441
Generation: 9
Generation: 10
New Best Solution Fitness: 58400
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.46667 
Mean sub-tour choices: 2.2 
Best Solution Fitness: 58400 
--------------------------------------------- 
