--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59203
New Best Solution Fitness: 59189
New Best Solution Fitness: 59153
Generation: 3
New Best Solution Fitness: 59047
New Best Solution Fitness: 59016
New Best Solution Fitness: 58925
Generation: 4
New Best Solution Fitness: 58874
New Best Solution Fitness: 58860
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.34444 
Mean sub-tour choices: 2.16667 
Best Solution Fitness: 58860 
--------------------------------------------- 
