--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59058
New Best Solution Fitness: 59048
New Best Solution Fitness: 59026
Generation: 3
New Best Solution Fitness: 58776
New Best Solution Fitness: 58761
Generation: 4
New Best Solution Fitness: 58734
Generation: 5
New Best Solution Fitness: 58725
Generation: 6
New Best Solution Fitness: 58692
New Best Solution Fitness: 58670
Generation: 7
New Best Solution Fitness: 58655
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.23333 
Mean sub-tour choices: 2.87778 
Best Solution Fitness: 58655 
--------------------------------------------- 
