--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 58587
New Best Solution Fitness: 58555
New Best Solution Fitness: 58484
Generation: 3
New Best Solution Fitness: 58482
New Best Solution Fitness: 58480
Generation: 4
Generation: 5
New Best Solution Fitness: 58397
Generation: 6
New Best Solution Fitness: 58395
Generation: 7
New Best Solution Fitness: 58392
Generation: 8
Generation: 9
New Best Solution Fitness: 58374
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.18889 
Mean sub-tour choices: 2.01111 
Best Solution Fitness: 58374 
--------------------------------------------- 
