--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59103
New Best Solution Fitness: 59088
Generation: 3
New Best Solution Fitness: 58983
New Best Solution Fitness: 58954
New Best Solution Fitness: 58950
Generation: 4
New Best Solution Fitness: 58874
Generation: 5
New Best Solution Fitness: 58799
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.42222 
Mean sub-tour choices: 2.15556 
Best Solution Fitness: 58799 
--------------------------------------------- 
