--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59390
New Best Solution Fitness: 59368
New Best Solution Fitness: 59282
Generation: 3
New Best Solution Fitness: 58743
New Best Solution Fitness: 58741
Generation: 4
New Best Solution Fitness: 58602
New Best Solution Fitness: 58587
New Best Solution Fitness: 58582
Generation: 5
New Best Solution Fitness: 58490
New Best Solution Fitness: 58488
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 58470
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.08889 
Mean sub-tour choices: 2.78889 
Best Solution Fitness: 58470 
--------------------------------------------- 
