--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59797
New Best Solution Fitness: 59787
New Best Solution Fitness: 59707
New Best Solution Fitness: 59691
Generation: 3
New Best Solution Fitness: 59381
New Best Solution Fitness: 59364
Generation: 4
New Best Solution Fitness: 59168
New Best Solution Fitness: 59160
New Best Solution Fitness: 59053
Generation: 5
New Best Solution Fitness: 59035
New Best Solution Fitness: 59027
Generation: 6
New Best Solution Fitness: 58964
New Best Solution Fitness: 58956
Generation: 7
New Best Solution Fitness: 58709
New Best Solution Fitness: 58677
Generation: 8
New Best Solution Fitness: 58673
New Best Solution Fitness: 58657
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.58889 
Mean sub-tour choices: 2.83333 
Best Solution Fitness: 58657 
--------------------------------------------- 
