--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59315
New Best Solution Fitness: 59294
New Best Solution Fitness: 59262
New Best Solution Fitness: 59250
New Best Solution Fitness: 59193
Generation: 3
New Best Solution Fitness: 58962
New Best Solution Fitness: 58930
Generation: 4
New Best Solution Fitness: 58885
New Best Solution Fitness: 58774
Generation: 5
New Best Solution Fitness: 58772
Generation: 6
Generation: 7
New Best Solution Fitness: 58757
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.27778 
Mean sub-tour choices: 2.12222 
Best Solution Fitness: 58757 
--------------------------------------------- 
