--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59133
New Best Solution Fitness: 59087
Generation: 3
New Best Solution Fitness: 58928
New Best Solution Fitness: 58923
New Best Solution Fitness: 58911
Generation: 4
New Best Solution Fitness: 58906
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 58905
Generation: 8
New Best Solution Fitness: 58832
Generation: 9
Generation: 10
New Best Solution Fitness: 58823
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.01111 
Mean sub-tour choices: 1.72222 
Best Solution Fitness: 58823 
--------------------------------------------- 
