--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59130
New Best Solution Fitness: 59126
New Best Solution Fitness: 59117
New Best Solution Fitness: 59068
Generation: 3
New Best Solution Fitness: 58899
New Best Solution Fitness: 58885
New Best Solution Fitness: 58874
Generation: 4
New Best Solution Fitness: 58759
New Best Solution Fitness: 58745
Generation: 5
New Best Solution Fitness: 58735
Generation: 6
New Best Solution Fitness: 58720
New Best Solution Fitness: 58680
Generation: 7
New Best Solution Fitness: 58653
New Best Solution Fitness: 58643
Generation: 8
New Best Solution Fitness: 58635
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.9 
Mean sub-tour choices: 2.53333 
Best Solution Fitness: 58635 
--------------------------------------------- 
