--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59055
New Best Solution Fitness: 59033
New Best Solution Fitness: 59020
Generation: 3
New Best Solution Fitness: 58745
New Best Solution Fitness: 58741
New Best Solution Fitness: 58723
Generation: 4
New Best Solution Fitness: 58650
New Best Solution Fitness: 58646
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 58624
Generation: 8
New Best Solution Fitness: 58619
Generation: 9
New Best Solution Fitness: 58610
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.6 
Mean sub-tour choices: 1.88889 
Best Solution Fitness: 58610 
--------------------------------------------- 
