--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59411
New Best Solution Fitness: 59405
New Best Solution Fitness: 59351
New Best Solution Fitness: 59280
Generation: 3
New Best Solution Fitness: 58911
New Best Solution Fitness: 58905
New Best Solution Fitness: 58869
Generation: 4
New Best Solution Fitness: 58855
New Best Solution Fitness: 58711
Generation: 5
New Best Solution Fitness: 58708
New Best Solution Fitness: 58702
Generation: 6
New Best Solution Fitness: 58696
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 58688
New Best Solution Fitness: 58658
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.25556 
Mean sub-tour choices: 1.95556 
Best Solution Fitness: 58658 
--------------------------------------------- 
