--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59851
New Best Solution Fitness: 59690
Generation: 3
New Best Solution Fitness: 59334
New Best Solution Fitness: 59230
Generation: 4
New Best Solution Fitness: 59085
New Best Solution Fitness: 59079
New Best Solution Fitness: 59078
New Best Solution Fitness: 58997
Generation: 5
New Best Solution Fitness: 58959
Generation: 6
New Best Solution Fitness: 58945
New Best Solution Fitness: 58942
Generation: 7
Generation: 8
New Best Solution Fitness: 58754
Generation: 9
New Best Solution Fitness: 58692
Generation: 10
New Best Solution Fitness: 58675
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.13333 
Mean sub-tour choices: 2.48889 
Best Solution Fitness: 58675 
--------------------------------------------- 
