--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59779
New Best Solution Fitness: 59757
New Best Solution Fitness: 59743
Generation: 3
New Best Solution Fitness: 59607
New Best Solution Fitness: 59568
New Best Solution Fitness: 59553
Generation: 4
New Best Solution Fitness: 59543
New Best Solution Fitness: 59474
Generation: 5
New Best Solution Fitness: 59468
New Best Solution Fitness: 59435
Generation: 6
New Best Solution Fitness: 59422
Generation: 7
New Best Solution Fitness: 59353
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.64444 
Mean sub-tour choices: 2.33333 
Best Solution Fitness: 59353 
--------------------------------------------- 
