--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59231
New Best Solution Fitness: 59215
New Best Solution Fitness: 59066
Generation: 3
New Best Solution Fitness: 58908
New Best Solution Fitness: 58906
Generation: 4
New Best Solution Fitness: 58896
Generation: 5
New Best Solution Fitness: 58582
Generation: 6
New Best Solution Fitness: 58580
Generation: 7
New Best Solution Fitness: 58578
New Best Solution Fitness: 58570
Generation: 8
New Best Solution Fitness: 58568
Generation: 9
New Best Solution Fitness: 58508
Generation: 10
New Best Solution Fitness: 58496
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.72222 
Mean sub-tour choices: 1.56667 
Best Solution Fitness: 58496 
--------------------------------------------- 
