--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 60357
New Best Solution Fitness: 60283
New Best Solution Fitness: 60255
New Best Solution Fitness: 60238
Generation: 3
New Best Solution Fitness: 59692
New Best Solution Fitness: 59686
Generation: 4
New Best Solution Fitness: 59115
New Best Solution Fitness: 58975
Generation: 5
New Best Solution Fitness: 58971
New Best Solution Fitness: 58949
Generation: 6
Generation: 7
New Best Solution Fitness: 58938
Generation: 8
New Best Solution Fitness: 58937
New Best Solution Fitness: 58935
Generation: 9
New Best Solution Fitness: 58922
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.6 
Mean sub-tour choices: 2.08889 
Best Solution Fitness: 58922 
--------------------------------------------- 
