--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59165
New Best Solution Fitness: 59048
Generation: 3
New Best Solution Fitness: 58817
New Best Solution Fitness: 58794
New Best Solution Fitness: 58781
New Best Solution Fitness: 58750
New Best Solution Fitness: 58691
Generation: 4
New Best Solution Fitness: 58621
New Best Solution Fitness: 58585
Generation: 5
New Best Solution Fitness: 58553
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.78889 
Mean sub-tour choices: 3.26667 
Best Solution Fitness: 58553 
--------------------------------------------- 
