--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 58814
New Best Solution Fitness: 58811
New Best Solution Fitness: 58788
New Best Solution Fitness: 58707
Generation: 3
New Best Solution Fitness: 58544
New Best Solution Fitness: 58532
New Best Solution Fitness: 58522
Generation: 4
New Best Solution Fitness: 58512
Generation: 5
New Best Solution Fitness: 58489
Generation: 6
Generation: 7
New Best Solution Fitness: 58337
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.9 
Mean sub-tour choices: 3.34444 
Best Solution Fitness: 58337 
--------------------------------------------- 
