--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 58968
New Best Solution Fitness: 58967
New Best Solution Fitness: 58924
New Best Solution Fitness: 58907
New Best Solution Fitness: 58899
Generation: 3
New Best Solution Fitness: 58856
New Best Solution Fitness: 58846
Generation: 4
New Best Solution Fitness: 58753
New Best Solution Fitness: 58747
Generation: 5
New Best Solution Fitness: 58725
New Best Solution Fitness: 58715
Generation: 6
New Best Solution Fitness: 58714
Generation: 7
New Best Solution Fitness: 58701
New Best Solution Fitness: 58700
Generation: 8
New Best Solution Fitness: 58690
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.35556 
Mean sub-tour choices: 2 
Best Solution Fitness: 58690 
--------------------------------------------- 
