--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59176
New Best Solution Fitness: 59166
New Best Solution Fitness: 59164
New Best Solution Fitness: 59162
Generation: 3
New Best Solution Fitness: 59063
New Best Solution Fitness: 58919
Generation: 4
New Best Solution Fitness: 58914
New Best Solution Fitness: 58882
Generation: 5
New Best Solution Fitness: 58868
New Best Solution Fitness: 58856
Generation: 6
New Best Solution Fitness: 58567
New Best Solution Fitness: 58550
Generation: 7
New Best Solution Fitness: 58538
Generation: 8
New Best Solution Fitness: 58531
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 5.12222 
Mean sub-tour choices: 2.86667 
Best Solution Fitness: 58531 
--------------------------------------------- 
