--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 58751
New Best Solution Fitness: 58715
New Best Solution Fitness: 58698
New Best Solution Fitness: 58578
Generation: 3
New Best Solution Fitness: 58428
New Best Solution Fitness: 58338
Generation: 4
New Best Solution Fitness: 58265
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 58264
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.1 
Mean sub-tour choices: 1.83333 
Best Solution Fitness: 58264 
--------------------------------------------- 
