--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59299
New Best Solution Fitness: 59033
Generation: 3
New Best Solution Fitness: 58734
Generation: 4
New Best Solution Fitness: 58621
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.54444 
Mean sub-tour choices: 2.05556 
Best Solution Fitness: 58621 
--------------------------------------------- 
