--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59323
New Best Solution Fitness: 59259
New Best Solution Fitness: 59161
Generation: 3
New Best Solution Fitness: 58663
New Best Solution Fitness: 58501
Generation: 4
New Best Solution Fitness: 58334
New Best Solution Fitness: 58328
Generation: 5
New Best Solution Fitness: 58327
Generation: 6
New Best Solution Fitness: 58325
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.55556 
Mean sub-tour choices: 2.92222 
Best Solution Fitness: 58325 
--------------------------------------------- 
