--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 58880
New Best Solution Fitness: 58785
Generation: 3
New Best Solution Fitness: 58529
New Best Solution Fitness: 58515
New Best Solution Fitness: 58463
Generation: 4
New Best Solution Fitness: 58444
Generation: 5
Generation: 6
New Best Solution Fitness: 58436
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.48889 
Mean sub-tour choices: 1.72222 
Best Solution Fitness: 58436 
--------------------------------------------- 
