--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\u1817.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 59978
New Best Solution Fitness: 59965
New Best Solution Fitness: 59785
Generation: 3
New Best Solution Fitness: 59648
New Best Solution Fitness: 59645
Generation: 4
New Best Solution Fitness: 59388
Generation: 5
New Best Solution Fitness: 59357
Generation: 6
New Best Solution Fitness: 59311
Generation: 7
New Best Solution Fitness: 59243
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3 
Mean sub-tour choices: 2.61111 
Best Solution Fitness: 59243 
--------------------------------------------- 
