--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50431
New Best Solution Fitness: 50258
Generation: 3
New Best Solution Fitness: 50244
New Best Solution Fitness: 50208
Generation: 4
Generation: 5
New Best Solution Fitness: 50146
New Best Solution Fitness: 50138
Generation: 6
New Best Solution Fitness: 50089
New Best Solution Fitness: 50068
Generation: 7
Generation: 8
New Best Solution Fitness: 49791
Generation: 9
Generation: 10
New Best Solution Fitness: 49764
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.655556 
Mean sub-tour choices: 0.944444 
Best Solution Fitness: 49764 
--------------------------------------------- 
