--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50009
New Best Solution Fitness: 50002
Generation: 3
New Best Solution Fitness: 49781
New Best Solution Fitness: 49599
Generation: 4
New Best Solution Fitness: 49479
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 49437
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.466667 
Mean sub-tour choices: 0.7 
Best Solution Fitness: 49437 
--------------------------------------------- 
