--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50188
New Best Solution Fitness: 50151
Generation: 3
New Best Solution Fitness: 49859
Generation: 4
New Best Solution Fitness: 49856
Generation: 5
New Best Solution Fitness: 49801
New Best Solution Fitness: 49735
Generation: 6
New Best Solution Fitness: 49686
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 49661
Generation: 10
New Best Solution Fitness: 49634
New Best Solution Fitness: 49619
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.488889 
Mean sub-tour choices: 0.711111 
Best Solution Fitness: 49619 
--------------------------------------------- 
