--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49830
New Best Solution Fitness: 49779
New Best Solution Fitness: 49716
Generation: 3
New Best Solution Fitness: 49696
New Best Solution Fitness: 49645
Generation: 4
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 49642
New Best Solution Fitness: 49591
Generation: 8
New Best Solution Fitness: 49587
Generation: 9
Generation: 10
New Best Solution Fitness: 49576
New Best Solution Fitness: 49571
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.6 
Mean sub-tour choices: 0.911111 
Best Solution Fitness: 49571 
--------------------------------------------- 
