--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50260
New Best Solution Fitness: 50125
New Best Solution Fitness: 50117
Generation: 3
New Best Solution Fitness: 49898
New Best Solution Fitness: 49826
Generation: 4
New Best Solution Fitness: 49825
New Best Solution Fitness: 49819
New Best Solution Fitness: 49762
Generation: 5
New Best Solution Fitness: 49567
Generation: 6
New Best Solution Fitness: 49556
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 49402
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.2 
Mean sub-tour choices: 1.47778 
Best Solution Fitness: 49402 
--------------------------------------------- 
