--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49665
New Best Solution Fitness: 49658
New Best Solution Fitness: 49577
Generation: 3
New Best Solution Fitness: 49570
Generation: 4
New Best Solution Fitness: 49560
New Best Solution Fitness: 49551
Generation: 5
New Best Solution Fitness: 49414
New Best Solution Fitness: 49405
Generation: 6
New Best Solution Fitness: 49376
Generation: 7
Generation: 8
New Best Solution Fitness: 49345
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.855556 
Mean sub-tour choices: 1.5 
Best Solution Fitness: 49345 
--------------------------------------------- 
