--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50084
New Best Solution Fitness: 50078
New Best Solution Fitness: 50075
New Best Solution Fitness: 49986
Generation: 3
New Best Solution Fitness: 49768
New Best Solution Fitness: 49670
Generation: 4
New Best Solution Fitness: 49655
New Best Solution Fitness: 49636
Generation: 5
New Best Solution Fitness: 49635
Generation: 6
New Best Solution Fitness: 49629
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.83333 
Mean sub-tour choices: 2.17778 
Best Solution Fitness: 49629 
--------------------------------------------- 
