--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50054
New Best Solution Fitness: 49988
New Best Solution Fitness: 49936
Generation: 3
New Best Solution Fitness: 49667
New Best Solution Fitness: 49647
New Best Solution Fitness: 49645
New Best Solution Fitness: 49615
Generation: 4
New Best Solution Fitness: 49577
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 49433
New Best Solution Fitness: 49412
New Best Solution Fitness: 49409
Generation: 8
New Best Solution Fitness: 49388
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.788889 
Mean sub-tour choices: 0.955556 
Best Solution Fitness: 49388 
--------------------------------------------- 
