--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50015
New Best Solution Fitness: 49988
New Best Solution Fitness: 49969
Generation: 3
New Best Solution Fitness: 49860
Generation: 4
New Best Solution Fitness: 49853
Generation: 5
New Best Solution Fitness: 49796
New Best Solution Fitness: 49783
Generation: 6
New Best Solution Fitness: 49713
Generation: 7
New Best Solution Fitness: 49660
New Best Solution Fitness: 49632
Generation: 8
New Best Solution Fitness: 49544
Generation: 9
New Best Solution Fitness: 49487
New Best Solution Fitness: 49448
Generation: 10
New Best Solution Fitness: 49388
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.422222 
Mean sub-tour choices: 0.711111 
Best Solution Fitness: 49388 
--------------------------------------------- 
