--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50168
New Best Solution Fitness: 50127
New Best Solution Fitness: 50114
Generation: 3
New Best Solution Fitness: 50078
New Best Solution Fitness: 50069
New Best Solution Fitness: 50053
New Best Solution Fitness: 50044
Generation: 4
New Best Solution Fitness: 50019
Generation: 5
Generation: 6
New Best Solution Fitness: 49895
Generation: 7
New Best Solution Fitness: 49870
New Best Solution Fitness: 49819
Generation: 8
New Best Solution Fitness: 49677
Generation: 9
Generation: 10
New Best Solution Fitness: 49597
New Best Solution Fitness: 49526
New Best Solution Fitness: 49451
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.811111 
Mean sub-tour choices: 0.977778 
Best Solution Fitness: 49451 
--------------------------------------------- 
