--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50084
New Best Solution Fitness: 50056
New Best Solution Fitness: 50002
New Best Solution Fitness: 49970
Generation: 3
New Best Solution Fitness: 49796
New Best Solution Fitness: 49795
New Best Solution Fitness: 49762
Generation: 4
New Best Solution Fitness: 49731
Generation: 5
New Best Solution Fitness: 49697
Generation: 6
New Best Solution Fitness: 49628
New Best Solution Fitness: 49620
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 49543
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.6 
Mean sub-tour choices: 0.833333 
Best Solution Fitness: 49543 
--------------------------------------------- 
