--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49856
New Best Solution Fitness: 49846
Generation: 3
New Best Solution Fitness: 49650
New Best Solution Fitness: 49567
Generation: 4
New Best Solution Fitness: 49530
Generation: 5
Generation: 6
New Best Solution Fitness: 49510
Generation: 7
New Best Solution Fitness: 49489
Generation: 8
Generation: 9
New Best Solution Fitness: 49323
New Best Solution Fitness: 49312
Generation: 10
New Best Solution Fitness: 49299
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.877778 
Mean sub-tour choices: 1.13333 
Best Solution Fitness: 49299 
--------------------------------------------- 
