--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49559
New Best Solution Fitness: 49558
New Best Solution Fitness: 49509
Generation: 3
New Best Solution Fitness: 49508
Generation: 4
New Best Solution Fitness: 49470
Generation: 5
New Best Solution Fitness: 49418
New Best Solution Fitness: 49402
Generation: 6
New Best Solution Fitness: 49345
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.455556 
Mean sub-tour choices: 0.7 
Best Solution Fitness: 49345 
--------------------------------------------- 
