--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50179
New Best Solution Fitness: 50087
New Best Solution Fitness: 49996
Generation: 3
New Best Solution Fitness: 49943
New Best Solution Fitness: 49888
New Best Solution Fitness: 49876
New Best Solution Fitness: 49851
Generation: 4
New Best Solution Fitness: 49724
New Best Solution Fitness: 49632
Generation: 5
Generation: 6
New Best Solution Fitness: 49623
Generation: 7
New Best Solution Fitness: 49598
Generation: 8
New Best Solution Fitness: 49577
Generation: 9
Generation: 10
New Best Solution Fitness: 49467
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.9 
Mean sub-tour choices: 1.11111 
Best Solution Fitness: 49467 
--------------------------------------------- 
