--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49897
Generation: 3
New Best Solution Fitness: 49880
Generation: 4
New Best Solution Fitness: 49782
Generation: 5
New Best Solution Fitness: 49620
New Best Solution Fitness: 49609
New Best Solution Fitness: 49581
Generation: 6
New Best Solution Fitness: 49570
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 49416
Generation: 10
New Best Solution Fitness: 49393
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.366667 
Mean sub-tour choices: 0.588889 
Best Solution Fitness: 49393 
--------------------------------------------- 
