--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49925
New Best Solution Fitness: 49808
New Best Solution Fitness: 49782
Generation: 3
New Best Solution Fitness: 49645
New Best Solution Fitness: 49618
New Best Solution Fitness: 49597
Generation: 4
New Best Solution Fitness: 49593
New Best Solution Fitness: 49559
Generation: 5
New Best Solution Fitness: 49501
Generation: 6
New Best Solution Fitness: 49486
Generation: 7
New Best Solution Fitness: 49393
Generation: 8
Generation: 9
New Best Solution Fitness: 49359
New Best Solution Fitness: 49298
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.95556 
Mean sub-tour choices: 2.35556 
Best Solution Fitness: 49298 
--------------------------------------------- 
