--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49851
Generation: 3
New Best Solution Fitness: 49777
Generation: 4
New Best Solution Fitness: 49719
Generation: 5
New Best Solution Fitness: 49700
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 49661
Generation: 10
New Best Solution Fitness: 49624
New Best Solution Fitness: 49611
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.377778 
Mean sub-tour choices: 0.666667 
Best Solution Fitness: 49611 
--------------------------------------------- 
