--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49750
New Best Solution Fitness: 49725
Generation: 3
New Best Solution Fitness: 49642
New Best Solution Fitness: 49625
Generation: 4
New Best Solution Fitness: 49614
Generation: 5
Generation: 6
New Best Solution Fitness: 49580
New Best Solution Fitness: 49576
New Best Solution Fitness: 49565
New Best Solution Fitness: 49559
Generation: 7
New Best Solution Fitness: 49555
Generation: 8
New Best Solution Fitness: 49552
Generation: 9
New Best Solution Fitness: 49520
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.02222 
Mean sub-tour choices: 1.64444 
Best Solution Fitness: 49520 
--------------------------------------------- 
