--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49705
New Best Solution Fitness: 49656
New Best Solution Fitness: 49631
New Best Solution Fitness: 49521
Generation: 3
Generation: 4
New Best Solution Fitness: 49520
Generation: 5
New Best Solution Fitness: 49486
Generation: 6
New Best Solution Fitness: 49475
Generation: 7
New Best Solution Fitness: 49472
Generation: 8
Generation: 9
New Best Solution Fitness: 49458
Generation: 10
New Best Solution Fitness: 49457
New Best Solution Fitness: 49450
New Best Solution Fitness: 49448
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.8 
Mean sub-tour choices: 1.16667 
Best Solution Fitness: 49448 
--------------------------------------------- 
