--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49851
New Best Solution Fitness: 49841
Generation: 3
New Best Solution Fitness: 49793
New Best Solution Fitness: 49770
Generation: 4
New Best Solution Fitness: 49745
New Best Solution Fitness: 49728
Generation: 5
New Best Solution Fitness: 49725
Generation: 6
New Best Solution Fitness: 49717
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 49703
New Best Solution Fitness: 49690
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.955556 
Mean sub-tour choices: 1.28889 
Best Solution Fitness: 49690 
--------------------------------------------- 
