--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50291
New Best Solution Fitness: 50241
New Best Solution Fitness: 50177
New Best Solution Fitness: 50074
Generation: 3
New Best Solution Fitness: 49774
New Best Solution Fitness: 49761
New Best Solution Fitness: 49752
Generation: 4
New Best Solution Fitness: 49744
Generation: 5
New Best Solution Fitness: 49707
Generation: 6
New Best Solution Fitness: 49697
New Best Solution Fitness: 49624
New Best Solution Fitness: 49605
New Best Solution Fitness: 49589
Generation: 7
New Best Solution Fitness: 49573
New Best Solution Fitness: 49555
Generation: 8
New Best Solution Fitness: 49548
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.25556 
Mean sub-tour choices: 1.91111 
Best Solution Fitness: 49548 
--------------------------------------------- 
