--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49706
New Best Solution Fitness: 49682
New Best Solution Fitness: 49649
Generation: 3
New Best Solution Fitness: 49634
Generation: 4
New Best Solution Fitness: 49625
Generation: 5
Generation: 6
New Best Solution Fitness: 49605
Generation: 7
New Best Solution Fitness: 49601
Generation: 8
Generation: 9
New Best Solution Fitness: 49531
New Best Solution Fitness: 49509
Generation: 10
New Best Solution Fitness: 49500
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.866667 
Mean sub-tour choices: 1.2 
Best Solution Fitness: 49500 
--------------------------------------------- 
