--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49660
New Best Solution Fitness: 49642
Generation: 3
New Best Solution Fitness: 49630
New Best Solution Fitness: 49575
Generation: 4
Generation: 5
New Best Solution Fitness: 49467
Generation: 6
New Best Solution Fitness: 49455
New Best Solution Fitness: 49446
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 49432
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.755556 
Mean sub-tour choices: 1.05556 
Best Solution Fitness: 49432 
--------------------------------------------- 
