--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49670
New Best Solution Fitness: 49669
Generation: 3
New Best Solution Fitness: 49660
Generation: 4
New Best Solution Fitness: 49452
New Best Solution Fitness: 49445
New Best Solution Fitness: 49370
Generation: 5
Generation: 6
New Best Solution Fitness: 49361
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 49355
Generation: 10
New Best Solution Fitness: 49316
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.455556 
Mean sub-tour choices: 0.833333 
Best Solution Fitness: 49316 
--------------------------------------------- 
