--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49825
New Best Solution Fitness: 49770
Generation: 3
New Best Solution Fitness: 49638
New Best Solution Fitness: 49583
New Best Solution Fitness: 49541
Generation: 4
New Best Solution Fitness: 49486
Generation: 5
Generation: 6
New Best Solution Fitness: 49456
Generation: 7
New Best Solution Fitness: 49430
Generation: 8
Generation: 9
New Best Solution Fitness: 49412
Generation: 10
New Best Solution Fitness: 49352
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.17778 
Mean sub-tour choices: 1.44444 
Best Solution Fitness: 49352 
--------------------------------------------- 
