--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49676
New Best Solution Fitness: 49675
Generation: 3
New Best Solution Fitness: 49543
New Best Solution Fitness: 49484
Generation: 4
New Best Solution Fitness: 49468
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 49434
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.14444 
Mean sub-tour choices: 1.54444 
Best Solution Fitness: 49434 
--------------------------------------------- 
