--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50084
New Best Solution Fitness: 50056
Generation: 3
New Best Solution Fitness: 49678
New Best Solution Fitness: 49667
New Best Solution Fitness: 49663
Generation: 4
New Best Solution Fitness: 49645
Generation: 5
New Best Solution Fitness: 49492
Generation: 6
New Best Solution Fitness: 49458
Generation: 7
New Best Solution Fitness: 49455
New Best Solution Fitness: 49422
Generation: 8
New Best Solution Fitness: 49317
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.711111 
Mean sub-tour choices: 0.9 
Best Solution Fitness: 49317 
--------------------------------------------- 
