--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49568
Generation: 3
New Best Solution Fitness: 49534
New Best Solution Fitness: 49533
Generation: 4
New Best Solution Fitness: 49527
New Best Solution Fitness: 49472
Generation: 5
New Best Solution Fitness: 49397
Generation: 6
New Best Solution Fitness: 49333
Generation: 7
New Best Solution Fitness: 49265
New Best Solution Fitness: 49251
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 49245
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.711111 
Mean sub-tour choices: 0.955556 
Best Solution Fitness: 49245 
--------------------------------------------- 
