--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49758
New Best Solution Fitness: 49747
New Best Solution Fitness: 49523
Generation: 3
New Best Solution Fitness: 49464
Generation: 4
New Best Solution Fitness: 49463
New Best Solution Fitness: 49447
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 49424
Generation: 9
New Best Solution Fitness: 49408
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.922222 
Mean sub-tour choices: 1.45556 
Best Solution Fitness: 49408 
--------------------------------------------- 
