--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49550
New Best Solution Fitness: 49535
Generation: 3
New Best Solution Fitness: 49462
New Best Solution Fitness: 49447
Generation: 4
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 49441
Generation: 8
New Best Solution Fitness: 49390
Generation: 9
New Best Solution Fitness: 49385
Generation: 10
New Best Solution Fitness: 49324
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.855556 
Mean sub-tour choices: 1.24444 
Best Solution Fitness: 49324 
--------------------------------------------- 
