--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49685
New Best Solution Fitness: 49684
New Best Solution Fitness: 49675
Generation: 3
New Best Solution Fitness: 49660
New Best Solution Fitness: 49654
Generation: 4
New Best Solution Fitness: 49606
Generation: 5
New Best Solution Fitness: 49469
Generation: 6
New Best Solution Fitness: 49452
Generation: 7
New Best Solution Fitness: 49445
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.466667 
Mean sub-tour choices: 0.666667 
Best Solution Fitness: 49445 
--------------------------------------------- 
