--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50377
New Best Solution Fitness: 50366
New Best Solution Fitness: 50362
New Best Solution Fitness: 50248
Generation: 3
New Best Solution Fitness: 50107
Generation: 4
Generation: 5
New Best Solution Fitness: 50090
New Best Solution Fitness: 50052
Generation: 6
Generation: 7
New Best Solution Fitness: 50001
Generation: 8
New Best Solution Fitness: 49818
Generation: 9
New Best Solution Fitness: 49811
Generation: 10
New Best Solution Fitness: 49721
New Best Solution Fitness: 49714
New Best Solution Fitness: 49683
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.344444 
Mean sub-tour choices: 0.633333 
Best Solution Fitness: 49683 
--------------------------------------------- 
