--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49868
New Best Solution Fitness: 49824
New Best Solution Fitness: 49794
Generation: 3
New Best Solution Fitness: 49648
New Best Solution Fitness: 49627
Generation: 4
Generation: 5
New Best Solution Fitness: 49626
Generation: 6
Generation: 7
New Best Solution Fitness: 49569
New Best Solution Fitness: 49532
Generation: 8
New Best Solution Fitness: 49510
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.666667 
Mean sub-tour choices: 0.944444 
Best Solution Fitness: 49510 
--------------------------------------------- 
