--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49972
New Best Solution Fitness: 49943
Generation: 3
New Best Solution Fitness: 49813
New Best Solution Fitness: 49795
Generation: 4
New Best Solution Fitness: 49767
Generation: 5
New Best Solution Fitness: 49673
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 49665
New Best Solution Fitness: 49594
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.711111 
Mean sub-tour choices: 1.22222 
Best Solution Fitness: 49594 
--------------------------------------------- 
