--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50213
New Best Solution Fitness: 50206
New Best Solution Fitness: 50203
New Best Solution Fitness: 50191
Generation: 3
New Best Solution Fitness: 49783
New Best Solution Fitness: 49732
Generation: 4
New Best Solution Fitness: 49683
Generation: 5
New Best Solution Fitness: 49638
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.355556 
Mean sub-tour choices: 0.511111 
Best Solution Fitness: 49638 
--------------------------------------------- 
