--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50353
New Best Solution Fitness: 50350
New Best Solution Fitness: 50325
New Best Solution Fitness: 50314
Generation: 3
New Best Solution Fitness: 49964
New Best Solution Fitness: 49925
New Best Solution Fitness: 49873
Generation: 4
New Best Solution Fitness: 49872
Generation: 5
New Best Solution Fitness: 49840
Generation: 6
New Best Solution Fitness: 49814
Generation: 7
New Best Solution Fitness: 49710
New Best Solution Fitness: 49526
Generation: 8
New Best Solution Fitness: 49522
Generation: 9
Generation: 10
New Best Solution Fitness: 49521
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.35556 
Mean sub-tour choices: 1.51111 
Best Solution Fitness: 49521 
--------------------------------------------- 
