--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49840
New Best Solution Fitness: 49835
New Best Solution Fitness: 49816
New Best Solution Fitness: 49798
Generation: 3
New Best Solution Fitness: 49504
Generation: 4
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 49481
Generation: 9
Generation: 10
New Best Solution Fitness: 49430
New Best Solution Fitness: 49427
New Best Solution Fitness: 49387
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.13333 
Mean sub-tour choices: 1.53333 
Best Solution Fitness: 49387 
--------------------------------------------- 
