--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49959
New Best Solution Fitness: 49926
Generation: 3
New Best Solution Fitness: 49844
New Best Solution Fitness: 49829
New Best Solution Fitness: 49822
Generation: 4
New Best Solution Fitness: 49690
New Best Solution Fitness: 49671
New Best Solution Fitness: 49606
Generation: 5
New Best Solution Fitness: 49408
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.388889 
Mean sub-tour choices: 0.644444 
Best Solution Fitness: 49408 
--------------------------------------------- 
