--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49804
Generation: 3
New Best Solution Fitness: 49779
New Best Solution Fitness: 49758
New Best Solution Fitness: 49706
Generation: 4
New Best Solution Fitness: 49692
New Best Solution Fitness: 49685
Generation: 5
New Best Solution Fitness: 49663
New Best Solution Fitness: 49604
New Best Solution Fitness: 49597
Generation: 6
New Best Solution Fitness: 49490
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 49456
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.422222 
Mean sub-tour choices: 0.711111 
Best Solution Fitness: 49456 
--------------------------------------------- 
