--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50137
New Best Solution Fitness: 50125
New Best Solution Fitness: 50031
New Best Solution Fitness: 50019
Generation: 3
New Best Solution Fitness: 49882
Generation: 4
New Best Solution Fitness: 49831
Generation: 5
New Best Solution Fitness: 49792
Generation: 6
New Best Solution Fitness: 49785
New Best Solution Fitness: 49692
Generation: 7
New Best Solution Fitness: 49627
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 49607
New Best Solution Fitness: 49498
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.633333 
Mean sub-tour choices: 0.911111 
Best Solution Fitness: 49498 
--------------------------------------------- 
