--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49802
New Best Solution Fitness: 49681
Generation: 3
New Best Solution Fitness: 49540
New Best Solution Fitness: 49525
Generation: 4
New Best Solution Fitness: 49505
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 49447
New Best Solution Fitness: 49423
Generation: 8
New Best Solution Fitness: 49418
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.655556 
Mean sub-tour choices: 0.822222 
Best Solution Fitness: 49418 
--------------------------------------------- 
