--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50222
New Best Solution Fitness: 50077
New Best Solution Fitness: 49969
Generation: 3
New Best Solution Fitness: 49899
New Best Solution Fitness: 49884
Generation: 4
Generation: 5
New Best Solution Fitness: 49870
New Best Solution Fitness: 49858
Generation: 6
New Best Solution Fitness: 49792
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 49776
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.733333 
Mean sub-tour choices: 1.27778 
Best Solution Fitness: 49776 
--------------------------------------------- 
