--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49581
Generation: 3
New Best Solution Fitness: 49531
Generation: 4
New Best Solution Fitness: 49520
Generation: 5
New Best Solution Fitness: 49497
New Best Solution Fitness: 49472
Generation: 6
Generation: 7
New Best Solution Fitness: 49464
Generation: 8
New Best Solution Fitness: 49375
Generation: 9
Generation: 10
New Best Solution Fitness: 49350
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.288889 
Mean sub-tour choices: 0.588889 
Best Solution Fitness: 49350 
--------------------------------------------- 
