--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49833
New Best Solution Fitness: 49761
New Best Solution Fitness: 49692
Generation: 3
New Best Solution Fitness: 49645
New Best Solution Fitness: 49592
Generation: 4
New Best Solution Fitness: 49591
Generation: 5
New Best Solution Fitness: 49558
New Best Solution Fitness: 49553
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 49552
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.52222 
Mean sub-tour choices: 1.64444 
Best Solution Fitness: 49552 
--------------------------------------------- 
