--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49782
New Best Solution Fitness: 49764
New Best Solution Fitness: 49751
Generation: 3
New Best Solution Fitness: 49592
Generation: 4
New Best Solution Fitness: 49591
Generation: 5
New Best Solution Fitness: 49524
New Best Solution Fitness: 49512
New Best Solution Fitness: 49468
Generation: 6
New Best Solution Fitness: 49459
Generation: 7
New Best Solution Fitness: 49456
Generation: 8
New Best Solution Fitness: 49356
New Best Solution Fitness: 49330
Generation: 9
New Best Solution Fitness: 49317
Generation: 10
New Best Solution Fitness: 49310
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.811111 
Mean sub-tour choices: 1.11111 
Best Solution Fitness: 49310 
--------------------------------------------- 
