--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50748
New Best Solution Fitness: 50625
Generation: 3
New Best Solution Fitness: 50192
New Best Solution Fitness: 50176
Generation: 4
New Best Solution Fitness: 50151
New Best Solution Fitness: 50146
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 49970
New Best Solution Fitness: 49628
Generation: 10
New Best Solution Fitness: 49480
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.677778 
Mean sub-tour choices: 1.04444 
Best Solution Fitness: 49480 
--------------------------------------------- 
