--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50163
New Best Solution Fitness: 50122
Generation: 3
New Best Solution Fitness: 50069
New Best Solution Fitness: 50000
Generation: 4
New Best Solution Fitness: 49909
New Best Solution Fitness: 49888
Generation: 5
New Best Solution Fitness: 49532
New Best Solution Fitness: 49511
Generation: 6
New Best Solution Fitness: 49500
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.722222 
Mean sub-tour choices: 0.966667 
Best Solution Fitness: 49500 
--------------------------------------------- 
