--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50121
New Best Solution Fitness: 50089
Generation: 3
New Best Solution Fitness: 50077
Generation: 4
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 49985
Generation: 8
New Best Solution Fitness: 49781
Generation: 9
New Best Solution Fitness: 49761
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.577778 
Mean sub-tour choices: 0.711111 
Best Solution Fitness: 49761 
--------------------------------------------- 
