--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49461
Generation: 3
New Best Solution Fitness: 49395
New Best Solution Fitness: 49364
Generation: 4
New Best Solution Fitness: 49337
Generation: 5
New Best Solution Fitness: 49277
New Best Solution Fitness: 49256
Generation: 6
New Best Solution Fitness: 49228
Generation: 7
Generation: 8
New Best Solution Fitness: 49183
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.733333 
Mean sub-tour choices: 1.12222 
Best Solution Fitness: 49183 
--------------------------------------------- 
