--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49549
New Best Solution Fitness: 49514
Generation: 3
New Best Solution Fitness: 49315
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 49299
Generation: 7
Generation: 8
New Best Solution Fitness: 49278
Generation: 9
New Best Solution Fitness: 49263
Generation: 10
New Best Solution Fitness: 49257
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.688889 
Mean sub-tour choices: 0.888889 
Best Solution Fitness: 49257 
--------------------------------------------- 
