--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50227
New Best Solution Fitness: 50148
Generation: 3
New Best Solution Fitness: 49926
Generation: 4
New Best Solution Fitness: 49836
Generation: 5
Generation: 6
New Best Solution Fitness: 49774
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 49732
New Best Solution Fitness: 49629
Generation: 10
New Best Solution Fitness: 49623
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.7 
Mean sub-tour choices: 1.1 
Best Solution Fitness: 49623 
--------------------------------------------- 
