--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49915
New Best Solution Fitness: 49891
New Best Solution Fitness: 49858
Generation: 3
New Best Solution Fitness: 49676
New Best Solution Fitness: 49651
Generation: 4
New Best Solution Fitness: 49641
New Best Solution Fitness: 49635
Generation: 5
New Best Solution Fitness: 49633
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 49593
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.766667 
Mean sub-tour choices: 1.05556 
Best Solution Fitness: 49593 
--------------------------------------------- 
