--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50358
New Best Solution Fitness: 50343
New Best Solution Fitness: 50337
Generation: 3
New Best Solution Fitness: 50151
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 49961
New Best Solution Fitness: 49869
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 49839
New Best Solution Fitness: 49782
New Best Solution Fitness: 49653
New Best Solution Fitness: 49637
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.711111 
Mean sub-tour choices: 1.03333 
Best Solution Fitness: 49637 
--------------------------------------------- 
