--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49911
New Best Solution Fitness: 49856
Generation: 3
New Best Solution Fitness: 49828
New Best Solution Fitness: 49804
New Best Solution Fitness: 49773
Generation: 4
New Best Solution Fitness: 49705
New Best Solution Fitness: 49704
New Best Solution Fitness: 49634
New Best Solution Fitness: 49604
Generation: 5
New Best Solution Fitness: 49555
New Best Solution Fitness: 49512
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.5 
Mean sub-tour choices: 0.811111 
Best Solution Fitness: 49512 
--------------------------------------------- 
