--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50031
Generation: 3
New Best Solution Fitness: 49911
New Best Solution Fitness: 49905
New Best Solution Fitness: 49827
Generation: 4
New Best Solution Fitness: 49821
Generation: 5
New Best Solution Fitness: 49722
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 49517
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.555556 
Mean sub-tour choices: 0.955556 
Best Solution Fitness: 49517 
--------------------------------------------- 
