--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50255
New Best Solution Fitness: 50227
New Best Solution Fitness: 50125
Generation: 3
New Best Solution Fitness: 50071
New Best Solution Fitness: 49964
Generation: 4
New Best Solution Fitness: 49697
New Best Solution Fitness: 49695
Generation: 5
New Best Solution Fitness: 49595
Generation: 6
Generation: 7
New Best Solution Fitness: 49540
New Best Solution Fitness: 49516
Generation: 8
New Best Solution Fitness: 49504
New Best Solution Fitness: 49483
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.666667 
Mean sub-tour choices: 0.977778 
Best Solution Fitness: 49483 
--------------------------------------------- 
