--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49620
New Best Solution Fitness: 49605
Generation: 3
Generation: 4
New Best Solution Fitness: 49604
Generation: 5
New Best Solution Fitness: 49525
New Best Solution Fitness: 49524
Generation: 6
New Best Solution Fitness: 49481
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 49473
Generation: 10
New Best Solution Fitness: 49398
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.266667 
Mean sub-tour choices: 0.477778 
Best Solution Fitness: 49398 
--------------------------------------------- 
