--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50326
New Best Solution Fitness: 50290
Generation: 3
New Best Solution Fitness: 49836
Generation: 4
New Best Solution Fitness: 49825
Generation: 5
New Best Solution Fitness: 49769
New Best Solution Fitness: 49762
Generation: 6
New Best Solution Fitness: 49713
Generation: 7
New Best Solution Fitness: 49691
New Best Solution Fitness: 49690
Generation: 8
Generation: 9
New Best Solution Fitness: 49592
New Best Solution Fitness: 49573
Generation: 10
New Best Solution Fitness: 49562
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.388889 
Mean sub-tour choices: 0.622222 
Best Solution Fitness: 49562 
--------------------------------------------- 
