--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50152
New Best Solution Fitness: 50107
Generation: 3
New Best Solution Fitness: 49978
New Best Solution Fitness: 49956
New Best Solution Fitness: 49878
Generation: 4
New Best Solution Fitness: 49839
New Best Solution Fitness: 49824
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 49797
New Best Solution Fitness: 49761
Generation: 8
New Best Solution Fitness: 49707
New Best Solution Fitness: 49653
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.42222 
Mean sub-tour choices: 1.37778 
Best Solution Fitness: 49653 
--------------------------------------------- 
