--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49872
New Best Solution Fitness: 49848
New Best Solution Fitness: 49838
New Best Solution Fitness: 49802
Generation: 3
New Best Solution Fitness: 49587
New Best Solution Fitness: 49568
New Best Solution Fitness: 49563
Generation: 4
New Best Solution Fitness: 49559
New Best Solution Fitness: 49557
New Best Solution Fitness: 49540
Generation: 5
New Best Solution Fitness: 49503
Generation: 6
New Best Solution Fitness: 49501
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 49468
New Best Solution Fitness: 49444
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.866667 
Mean sub-tour choices: 1.32222 
Best Solution Fitness: 49444 
--------------------------------------------- 
