--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49831
New Best Solution Fitness: 49830
New Best Solution Fitness: 49771
Generation: 3
New Best Solution Fitness: 49646
New Best Solution Fitness: 49623
Generation: 4
New Best Solution Fitness: 49569
Generation: 5
New Best Solution Fitness: 49477
New Best Solution Fitness: 49453
Generation: 6
New Best Solution Fitness: 49397
Generation: 7
Generation: 8
New Best Solution Fitness: 49344
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.32222 
Mean sub-tour choices: 1.65556 
Best Solution Fitness: 49344 
--------------------------------------------- 
