--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50005
New Best Solution Fitness: 49959
Generation: 3
New Best Solution Fitness: 49607
New Best Solution Fitness: 49561
Generation: 4
New Best Solution Fitness: 49522
Generation: 5
New Best Solution Fitness: 49489
Generation: 6
New Best Solution Fitness: 49474
Generation: 7
New Best Solution Fitness: 49444
New Best Solution Fitness: 49443
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 49405
New Best Solution Fitness: 49402
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.588889 
Mean sub-tour choices: 0.844444 
Best Solution Fitness: 49402 
--------------------------------------------- 
