--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49751
New Best Solution Fitness: 49715
Generation: 3
New Best Solution Fitness: 49439
New Best Solution Fitness: 49434
New Best Solution Fitness: 49395
New Best Solution Fitness: 49392
Generation: 4
New Best Solution Fitness: 49294
Generation: 5
Generation: 6
New Best Solution Fitness: 49285
Generation: 7
Generation: 8
New Best Solution Fitness: 49284
Generation: 9
New Best Solution Fitness: 49276
New Best Solution Fitness: 49275
Generation: 10
New Best Solution Fitness: 49224
New Best Solution Fitness: 49151
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.2 
Mean sub-tour choices: 1.53333 
Best Solution Fitness: 49151 
--------------------------------------------- 
