--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50182
Generation: 3
New Best Solution Fitness: 50090
New Best Solution Fitness: 50053
Generation: 4
New Best Solution Fitness: 49968
New Best Solution Fitness: 49962
Generation: 5
New Best Solution Fitness: 49949
Generation: 6
New Best Solution Fitness: 49807
Generation: 7
New Best Solution Fitness: 49770
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.688889 
Mean sub-tour choices: 0.888889 
Best Solution Fitness: 49770 
--------------------------------------------- 
