--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49641
Generation: 3
New Best Solution Fitness: 49622
Generation: 4
Generation: 5
New Best Solution Fitness: 49572
Generation: 6
New Best Solution Fitness: 49473
New Best Solution Fitness: 49469
Generation: 7
Generation: 8
New Best Solution Fitness: 49431
Generation: 9
Generation: 10
New Best Solution Fitness: 49407
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.422222 
Mean sub-tour choices: 0.744444 
Best Solution Fitness: 49407 
--------------------------------------------- 
