--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50010
New Best Solution Fitness: 50002
Generation: 3
New Best Solution Fitness: 50000
New Best Solution Fitness: 49956
Generation: 4
New Best Solution Fitness: 49952
Generation: 5
Generation: 6
New Best Solution Fitness: 49656
New Best Solution Fitness: 49652
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 49637
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.588889 
Mean sub-tour choices: 0.855556 
Best Solution Fitness: 49637 
--------------------------------------------- 
