--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49956
New Best Solution Fitness: 49946
New Best Solution Fitness: 49941
New Best Solution Fitness: 49894
Generation: 3
New Best Solution Fitness: 49866
New Best Solution Fitness: 49787
Generation: 4
New Best Solution Fitness: 49732
Generation: 5
New Best Solution Fitness: 49600
New Best Solution Fitness: 49596
Generation: 6
Generation: 7
New Best Solution Fitness: 49590
Generation: 8
New Best Solution Fitness: 49488
New Best Solution Fitness: 49480
Generation: 9
New Best Solution Fitness: 49362
New Best Solution Fitness: 49333
Generation: 10
New Best Solution Fitness: 49310
New Best Solution Fitness: 49268
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.733333 
Mean sub-tour choices: 1.12222 
Best Solution Fitness: 49268 
--------------------------------------------- 
