--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49699
New Best Solution Fitness: 49665
Generation: 3
New Best Solution Fitness: 49517
New Best Solution Fitness: 49442
New Best Solution Fitness: 49440
Generation: 4
New Best Solution Fitness: 49432
Generation: 5
New Best Solution Fitness: 49425
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 49360
Generation: 9
New Best Solution Fitness: 49359
New Best Solution Fitness: 49352
Generation: 10
New Best Solution Fitness: 49351
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.511111 
Mean sub-tour choices: 0.844444 
Best Solution Fitness: 49351 
--------------------------------------------- 
