--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49850
New Best Solution Fitness: 49718
Generation: 3
New Best Solution Fitness: 49414
Generation: 4
Generation: 5
New Best Solution Fitness: 49369
Generation: 6
New Best Solution Fitness: 49329
Generation: 7
New Best Solution Fitness: 49319
New Best Solution Fitness: 49318
New Best Solution Fitness: 49296
Generation: 8
New Best Solution Fitness: 49241
New Best Solution Fitness: 49229
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.733333 
Mean sub-tour choices: 1.22222 
Best Solution Fitness: 49229 
--------------------------------------------- 
