--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50528
New Best Solution Fitness: 50510
Generation: 3
New Best Solution Fitness: 50354
Generation: 4
New Best Solution Fitness: 50106
Generation: 5
New Best Solution Fitness: 49984
Generation: 6
New Best Solution Fitness: 49932
Generation: 7
Generation: 8
New Best Solution Fitness: 49627
Generation: 9
Generation: 10
New Best Solution Fitness: 49604
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.577778 
Mean sub-tour choices: 0.922222 
Best Solution Fitness: 49604 
--------------------------------------------- 
