--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49989
New Best Solution Fitness: 49978
Generation: 3
New Best Solution Fitness: 49737
New Best Solution Fitness: 49664
Generation: 4
New Best Solution Fitness: 49619
New Best Solution Fitness: 49590
Generation: 5
New Best Solution Fitness: 49541
New Best Solution Fitness: 49517
Generation: 6
New Best Solution Fitness: 49506
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 49443
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.42222 
Mean sub-tour choices: 1.52222 
Best Solution Fitness: 49443 
--------------------------------------------- 
