--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50372
New Best Solution Fitness: 50364
New Best Solution Fitness: 50231
Generation: 3
New Best Solution Fitness: 49865
Generation: 4
New Best Solution Fitness: 49854
Generation: 5
Generation: 6
New Best Solution Fitness: 49853
Generation: 7
New Best Solution Fitness: 49842
Generation: 8
Generation: 9
New Best Solution Fitness: 49651
Generation: 10
New Best Solution Fitness: 49559
New Best Solution Fitness: 49473
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.733333 
Mean sub-tour choices: 1.03333 
Best Solution Fitness: 49473 
--------------------------------------------- 
