--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49674
New Best Solution Fitness: 49588
Generation: 3
New Best Solution Fitness: 49549
Generation: 4
New Best Solution Fitness: 49358
New Best Solution Fitness: 49351
Generation: 5
Generation: 6
New Best Solution Fitness: 49346
New Best Solution Fitness: 49339
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 49293
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.688889 
Mean sub-tour choices: 1.05556 
Best Solution Fitness: 49293 
--------------------------------------------- 
