--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49465
Generation: 3
New Best Solution Fitness: 49442
Generation: 4
New Best Solution Fitness: 49338
New Best Solution Fitness: 49282
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.322222 
Mean sub-tour choices: 0.544444 
Best Solution Fitness: 49282 
--------------------------------------------- 
