--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50536
New Best Solution Fitness: 50228
Generation: 3
New Best Solution Fitness: 50180
New Best Solution Fitness: 50171
Generation: 4
New Best Solution Fitness: 50078
New Best Solution Fitness: 50077
New Best Solution Fitness: 50043
Generation: 5
New Best Solution Fitness: 49810
Generation: 6
New Best Solution Fitness: 49796
Generation: 7
New Best Solution Fitness: 49795
Generation: 8
New Best Solution Fitness: 49767
New Best Solution Fitness: 49728
Generation: 9
New Best Solution Fitness: 49598
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.855556 
Mean sub-tour choices: 1.3 
Best Solution Fitness: 49598 
--------------------------------------------- 
