--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49724
New Best Solution Fitness: 49710
Generation: 3
New Best Solution Fitness: 49657
Generation: 4
Generation: 5
New Best Solution Fitness: 49639
Generation: 6
Generation: 7
New Best Solution Fitness: 49511
New Best Solution Fitness: 49503
Generation: 8
New Best Solution Fitness: 49488
New Best Solution Fitness: 49470
Generation: 9
New Best Solution Fitness: 49433
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.755556 
Mean sub-tour choices: 1.42222 
Best Solution Fitness: 49433 
--------------------------------------------- 
