--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49750
New Best Solution Fitness: 49741
Generation: 3
New Best Solution Fitness: 49735
New Best Solution Fitness: 49734
Generation: 4
New Best Solution Fitness: 49667
New Best Solution Fitness: 49666
Generation: 5
New Best Solution Fitness: 49615
Generation: 6
Generation: 7
New Best Solution Fitness: 49404
Generation: 8
New Best Solution Fitness: 49389
Generation: 9
New Best Solution Fitness: 49291
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.677778 
Mean sub-tour choices: 1.06667 
Best Solution Fitness: 49291 
--------------------------------------------- 
