--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50037
Generation: 3
Generation: 4
New Best Solution Fitness: 49978
Generation: 5
New Best Solution Fitness: 49515
Generation: 6
Generation: 7
New Best Solution Fitness: 49485
New Best Solution Fitness: 49471
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.422222 
Mean sub-tour choices: 0.644444 
Best Solution Fitness: 49471 
--------------------------------------------- 
