--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50307
New Best Solution Fitness: 50297
New Best Solution Fitness: 50221
New Best Solution Fitness: 49920
Generation: 3
New Best Solution Fitness: 49786
Generation: 4
New Best Solution Fitness: 49736
New Best Solution Fitness: 49727
New Best Solution Fitness: 49724
Generation: 5
New Best Solution Fitness: 49654
Generation: 6
New Best Solution Fitness: 49650
New Best Solution Fitness: 49645
New Best Solution Fitness: 49616
Generation: 7
New Best Solution Fitness: 49495
New Best Solution Fitness: 49457
Generation: 8
New Best Solution Fitness: 49439
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.04444 
Mean sub-tour choices: 1.32222 
Best Solution Fitness: 49439 
--------------------------------------------- 
