--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50116
New Best Solution Fitness: 49978
Generation: 3
New Best Solution Fitness: 49786
New Best Solution Fitness: 49775
New Best Solution Fitness: 49741
New Best Solution Fitness: 49672
Generation: 4
New Best Solution Fitness: 49657
New Best Solution Fitness: 49627
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 49626
Generation: 10
New Best Solution Fitness: 49564
New Best Solution Fitness: 49549
New Best Solution Fitness: 49466
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.488889 
Mean sub-tour choices: 0.811111 
Best Solution Fitness: 49466 
--------------------------------------------- 
