--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49912
New Best Solution Fitness: 49842
New Best Solution Fitness: 49765
Generation: 3
New Best Solution Fitness: 49687
Generation: 4
New Best Solution Fitness: 49610
New Best Solution Fitness: 49565
Generation: 5
New Best Solution Fitness: 49472
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.17778 
Mean sub-tour choices: 1.96667 
Best Solution Fitness: 49472 
--------------------------------------------- 
