--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50046
New Best Solution Fitness: 50030
New Best Solution Fitness: 49897
New Best Solution Fitness: 49896
Generation: 3
New Best Solution Fitness: 49854
New Best Solution Fitness: 49845
Generation: 4
New Best Solution Fitness: 49770
New Best Solution Fitness: 49752
Generation: 5
New Best Solution Fitness: 49493
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.588889 
Mean sub-tour choices: 0.744444 
Best Solution Fitness: 49493 
--------------------------------------------- 
