--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49830
New Best Solution Fitness: 49824
New Best Solution Fitness: 49799
Generation: 3
New Best Solution Fitness: 49768
New Best Solution Fitness: 49749
Generation: 4
New Best Solution Fitness: 49721
Generation: 5
New Best Solution Fitness: 49636
New Best Solution Fitness: 49557
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.977778 
Mean sub-tour choices: 1.35556 
Best Solution Fitness: 49557 
--------------------------------------------- 
