--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50118
New Best Solution Fitness: 50104
New Best Solution Fitness: 50099
Generation: 3
New Best Solution Fitness: 49589
Generation: 4
Generation: 5
New Best Solution Fitness: 49576
Generation: 6
New Best Solution Fitness: 49549
Generation: 7
New Best Solution Fitness: 49547
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 49535
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.722222 
Mean sub-tour choices: 1.11111 
Best Solution Fitness: 49535 
--------------------------------------------- 
