--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50984
New Best Solution Fitness: 50903
New Best Solution Fitness: 50892
Generation: 3
New Best Solution Fitness: 50017
Generation: 4
New Best Solution Fitness: 49885
Generation: 5
New Best Solution Fitness: 49663
Generation: 6
Generation: 7
New Best Solution Fitness: 49600
Generation: 8
New Best Solution Fitness: 49592
Generation: 9
New Best Solution Fitness: 49443
New Best Solution Fitness: 49435
Generation: 10
New Best Solution Fitness: 49417
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.511111 
Mean sub-tour choices: 0.866667 
Best Solution Fitness: 49417 
--------------------------------------------- 
