--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49810
New Best Solution Fitness: 49765
New Best Solution Fitness: 49734
Generation: 3
New Best Solution Fitness: 49577
New Best Solution Fitness: 49552
Generation: 4
Generation: 5
New Best Solution Fitness: 49530
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 49498
Generation: 10
New Best Solution Fitness: 49442
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.17778 
Mean sub-tour choices: 1.42222 
Best Solution Fitness: 49442 
--------------------------------------------- 
