--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49614
New Best Solution Fitness: 49606
Generation: 3
New Best Solution Fitness: 49589
Generation: 4
New Best Solution Fitness: 49573
Generation: 5
Generation: 6
New Best Solution Fitness: 49504
Generation: 7
New Best Solution Fitness: 49487
Generation: 8
New Best Solution Fitness: 49486
New Best Solution Fitness: 49465
Generation: 9
Generation: 10
New Best Solution Fitness: 49360
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.566667 
Mean sub-tour choices: 0.933333 
Best Solution Fitness: 49360 
--------------------------------------------- 
