--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49740
New Best Solution Fitness: 49701
Generation: 3
New Best Solution Fitness: 49639
Generation: 4
New Best Solution Fitness: 49580
New Best Solution Fitness: 49574
Generation: 5
New Best Solution Fitness: 49557
Generation: 6
New Best Solution Fitness: 49514
Generation: 7
New Best Solution Fitness: 49507
Generation: 8
New Best Solution Fitness: 49504
Generation: 9
New Best Solution Fitness: 49458
New Best Solution Fitness: 49455
New Best Solution Fitness: 49454
Generation: 10
New Best Solution Fitness: 49439
New Best Solution Fitness: 49437
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.988889 
Mean sub-tour choices: 1.55556 
Best Solution Fitness: 49437 
--------------------------------------------- 
