--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49603
New Best Solution Fitness: 49586
Generation: 3
New Best Solution Fitness: 49561
Generation: 4
New Best Solution Fitness: 49469
Generation: 5
New Best Solution Fitness: 49444
New Best Solution Fitness: 49431
Generation: 6
New Best Solution Fitness: 49430
Generation: 7
New Best Solution Fitness: 49426
New Best Solution Fitness: 49406
Generation: 8
New Best Solution Fitness: 49401
Generation: 9
Generation: 10
New Best Solution Fitness: 49382
New Best Solution Fitness: 49314
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.05556 
Mean sub-tour choices: 1.74444 
Best Solution Fitness: 49314 
--------------------------------------------- 
