--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50494
New Best Solution Fitness: 50491
New Best Solution Fitness: 50430
New Best Solution Fitness: 50366
Generation: 3
New Best Solution Fitness: 50252
New Best Solution Fitness: 50205
New Best Solution Fitness: 50188
New Best Solution Fitness: 50144
Generation: 4
New Best Solution Fitness: 50131
Generation: 5
New Best Solution Fitness: 50008
New Best Solution Fitness: 49984
New Best Solution Fitness: 49856
Generation: 6
New Best Solution Fitness: 49823
Generation: 7
New Best Solution Fitness: 49767
New Best Solution Fitness: 49752
New Best Solution Fitness: 49732
Generation: 8
New Best Solution Fitness: 49628
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.888889 
Mean sub-tour choices: 1.34444 
Best Solution Fitness: 49628 
--------------------------------------------- 
