--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50237
New Best Solution Fitness: 50108
Generation: 3
New Best Solution Fitness: 49730
Generation: 4
New Best Solution Fitness: 49726
New Best Solution Fitness: 49687
Generation: 5
New Best Solution Fitness: 49649
Generation: 6
New Best Solution Fitness: 49621
Generation: 7
Generation: 8
New Best Solution Fitness: 49570
New Best Solution Fitness: 49569
Generation: 9
New Best Solution Fitness: 49544
New Best Solution Fitness: 49540
Generation: 10
New Best Solution Fitness: 49528
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.733333 
Mean sub-tour choices: 1.17778 
Best Solution Fitness: 49528 
--------------------------------------------- 
