--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50648
New Best Solution Fitness: 50382
New Best Solution Fitness: 50293
Generation: 3
New Best Solution Fitness: 49831
New Best Solution Fitness: 49824
Generation: 4
New Best Solution Fitness: 49778
New Best Solution Fitness: 49745
Generation: 5
New Best Solution Fitness: 49734
Generation: 6
New Best Solution Fitness: 49732
Generation: 7
Generation: 8
New Best Solution Fitness: 49615
New Best Solution Fitness: 49594
Generation: 9
New Best Solution Fitness: 49582
Generation: 10
New Best Solution Fitness: 49563
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.21111 
Mean sub-tour choices: 1.36667 
Best Solution Fitness: 49563 
--------------------------------------------- 
