--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50259
New Best Solution Fitness: 50065
Generation: 3
New Best Solution Fitness: 50064
New Best Solution Fitness: 50040
Generation: 4
New Best Solution Fitness: 50005
New Best Solution Fitness: 49961
Generation: 5
New Best Solution Fitness: 49847
New Best Solution Fitness: 49846
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 49759
Generation: 9
New Best Solution Fitness: 49735
Generation: 10
New Best Solution Fitness: 49670
New Best Solution Fitness: 49647
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.622222 
Mean sub-tour choices: 1.08889 
Best Solution Fitness: 49647 
--------------------------------------------- 
