--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50093
New Best Solution Fitness: 50042
Generation: 3
New Best Solution Fitness: 49996
Generation: 4
New Best Solution Fitness: 49789
Generation: 5
New Best Solution Fitness: 49522
Generation: 6
New Best Solution Fitness: 49475
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.377778 
Mean sub-tour choices: 0.655556 
Best Solution Fitness: 49475 
--------------------------------------------- 
