--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50155
New Best Solution Fitness: 50078
Generation: 3
New Best Solution Fitness: 50044
New Best Solution Fitness: 50021
Generation: 4
New Best Solution Fitness: 50012
New Best Solution Fitness: 50010
New Best Solution Fitness: 49989
Generation: 5
New Best Solution Fitness: 49942
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 49941
New Best Solution Fitness: 49937
Generation: 10
New Best Solution Fitness: 49902
New Best Solution Fitness: 49735
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.633333 
Mean sub-tour choices: 0.977778 
Best Solution Fitness: 49735 
--------------------------------------------- 
