--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49550
New Best Solution Fitness: 49539
Generation: 3
Generation: 4
New Best Solution Fitness: 49510
Generation: 5
New Best Solution Fitness: 49473
New Best Solution Fitness: 49391
Generation: 6
New Best Solution Fitness: 49371
Generation: 7
New Best Solution Fitness: 49318
Generation: 8
New Best Solution Fitness: 49304
Generation: 9
Generation: 10
New Best Solution Fitness: 49289
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.722222 
Mean sub-tour choices: 1.05556 
Best Solution Fitness: 49289 
--------------------------------------------- 
