--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\usa13509.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 20935609
New Best Solution Fitness: 20918908
New Best Solution Fitness: 20918118
New Best Solution Fitness: 20917859
Generation: 3
New Best Solution Fitness: 20657698
New Best Solution Fitness: 20656431
New Best Solution Fitness: 20655806
New Best Solution Fitness: 20655542
New Best Solution Fitness: 20655513
New Best Solution Fitness: 20651046
Generation: 4
New Best Solution Fitness: 20539165
New Best Solution Fitness: 20535564
New Best Solution Fitness: 20530764
Generation: 5
New Best Solution Fitness: 20522546
New Best Solution Fitness: 20521928
New Best Solution Fitness: 20518483
New Best Solution Fitness: 20518368
Generation: 6
New Best Solution Fitness: 20495783
New Best Solution Fitness: 20495590
New Best Solution Fitness: 20494067
New Best Solution Fitness: 20493043
Generation: 7
New Best Solution Fitness: 20491356
New Best Solution Fitness: 20491184
New Best Solution Fitness: 20490596
Generation: 8
New Best Solution Fitness: 20490438
New Best Solution Fitness: 20490424
Generation: 9
New Best Solution Fitness: 20484232
New Best Solution Fitness: 20484074
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 8.05556 
Mean sub-tour choices: 9.08889 
Best Solution Fitness: 20484074 
--------------------------------------------- 
