--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\usa13509.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 20786957
New Best Solution Fitness: 20783604
New Best Solution Fitness: 20775636
New Best Solution Fitness: 20772016
Generation: 3
New Best Solution Fitness: 20688097
New Best Solution Fitness: 20687159
New Best Solution Fitness: 20685346
New Best Solution Fitness: 20680293
New Best Solution Fitness: 20674229
Generation: 4
New Best Solution Fitness: 20648992
New Best Solution Fitness: 20648069
New Best Solution Fitness: 20642085
Generation: 5
New Best Solution Fitness: 20637522
New Best Solution Fitness: 20636514
Generation: 6
New Best Solution Fitness: 20635658
Generation: 7
New Best Solution Fitness: 20635489
Generation: 8
Generation: 9
New Best Solution Fitness: 20634631
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 5.3 
Mean sub-tour choices: 6.15556 
Best Solution Fitness: 20634631 
--------------------------------------------- 
