--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\usa13509.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 20639033
New Best Solution Fitness: 20609077
Generation: 3
New Best Solution Fitness: 20549716
New Best Solution Fitness: 20528468
Generation: 4
New Best Solution Fitness: 20518453
New Best Solution Fitness: 20516546
Generation: 5
New Best Solution Fitness: 20491172
New Best Solution Fitness: 20487327
Generation: 6
New Best Solution Fitness: 20486585
New Best Solution Fitness: 20486307
Generation: 7
New Best Solution Fitness: 20485468
New Best Solution Fitness: 20485449
Generation: 8
New Best Solution Fitness: 20485406
Generation: 9
New Best Solution Fitness: 20485134
Generation: 10
New Best Solution Fitness: 20483605
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 9.25556 
Mean sub-tour choices: 10.5667 
Best Solution Fitness: 20483605 
--------------------------------------------- 
