--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\usa13509.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 21077405
New Best Solution Fitness: 21064987
New Best Solution Fitness: 21064715
New Best Solution Fitness: 21064415
Generation: 3
New Best Solution Fitness: 20944210
New Best Solution Fitness: 20943252
New Best Solution Fitness: 20939081
New Best Solution Fitness: 20925335
Generation: 4
New Best Solution Fitness: 20883993
New Best Solution Fitness: 20883411
New Best Solution Fitness: 20882276
Generation: 5
New Best Solution Fitness: 20872948
New Best Solution Fitness: 20872366
New Best Solution Fitness: 20872233
Generation: 6
New Best Solution Fitness: 20869786
New Best Solution Fitness: 20868853
Generation: 7
New Best Solution Fitness: 20865271
New Best Solution Fitness: 20865053
New Best Solution Fitness: 20864746
Generation: 8
New Best Solution Fitness: 20864240
Generation: 9
New Best Solution Fitness: 20863067
Generation: 10
New Best Solution Fitness: 20669002
New Best Solution Fitness: 20666247
New Best Solution Fitness: 20614821
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 6.74444 
Mean sub-tour choices: 7.83333 
Best Solution Fitness: 20614821 
--------------------------------------------- 
