--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\usa13509.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 20639860
New Best Solution Fitness: 20627541
Generation: 3
New Best Solution Fitness: 20564950
New Best Solution Fitness: 20560213
New Best Solution Fitness: 20558849
New Best Solution Fitness: 20558781
New Best Solution Fitness: 20558288
Generation: 4
New Best Solution Fitness: 20544560
New Best Solution Fitness: 20543241
New Best Solution Fitness: 20542538
New Best Solution Fitness: 20542238
Generation: 5
New Best Solution Fitness: 20541769
New Best Solution Fitness: 20540450
New Best Solution Fitness: 20540216
Generation: 6
New Best Solution Fitness: 20540142
New Best Solution Fitness: 20539767
New Best Solution Fitness: 20539257
New Best Solution Fitness: 20538428
Generation: 7
New Best Solution Fitness: 20538354
New Best Solution Fitness: 20537979
New Best Solution Fitness: 20537469
Generation: 8
New Best Solution Fitness: 20537020
Generation: 9
New Best Solution Fitness: 20534342
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 10.6222 
Mean sub-tour choices: 11.9111 
Best Solution Fitness: 20534342 
--------------------------------------------- 
