--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\usa13509.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 20752242
New Best Solution Fitness: 20744839
New Best Solution Fitness: 20739769
New Best Solution Fitness: 20739250
New Best Solution Fitness: 20736490
Generation: 3
New Best Solution Fitness: 20646361
New Best Solution Fitness: 20645326
New Best Solution Fitness: 20644003
New Best Solution Fitness: 20643810
New Best Solution Fitness: 20643507
Generation: 4
New Best Solution Fitness: 20604107
New Best Solution Fitness: 20604039
New Best Solution Fitness: 20602730
New Best Solution Fitness: 20602716
Generation: 5
New Best Solution Fitness: 20597143
New Best Solution Fitness: 20595813
New Best Solution Fitness: 20595766
Generation: 6
New Best Solution Fitness: 20593148
New Best Solution Fitness: 20592661
New Best Solution Fitness: 20592195
Generation: 7
New Best Solution Fitness: 20589174
New Best Solution Fitness: 20589149
Generation: 8
New Best Solution Fitness: 20586556
New Best Solution Fitness: 20585335
Generation: 9
New Best Solution Fitness: 20584774
New Best Solution Fitness: 20583634
Generation: 10
New Best Solution Fitness: 20579476
New Best Solution Fitness: 20573295
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 7.42222 
Mean sub-tour choices: 8.4 
Best Solution Fitness: 20573295 
--------------------------------------------- 
