--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\usa13509.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 20832075
New Best Solution Fitness: 20817388
New Best Solution Fitness: 20815792
New Best Solution Fitness: 20791493
New Best Solution Fitness: 20788565
Generation: 3
New Best Solution Fitness: 20713049
New Best Solution Fitness: 20710872
New Best Solution Fitness: 20710752
New Best Solution Fitness: 20708834
Generation: 4
New Best Solution Fitness: 20576705
New Best Solution Fitness: 20573997
New Best Solution Fitness: 20573965
Generation: 5
New Best Solution Fitness: 20559241
New Best Solution Fitness: 20559139
Generation: 6
New Best Solution Fitness: 20553332
New Best Solution Fitness: 20553161
New Best Solution Fitness: 20552431
New Best Solution Fitness: 20551685
Generation: 7
New Best Solution Fitness: 20550408
Generation: 8
Generation: 9
New Best Solution Fitness: 20550375
Generation: 10
New Best Solution Fitness: 20550357
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 6.15556 
Mean sub-tour choices: 7.15556 
Best Solution Fitness: 20550357 
--------------------------------------------- 
