--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\usa13509.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 20802820
New Best Solution Fitness: 20781425
New Best Solution Fitness: 20780925
New Best Solution Fitness: 20775841
New Best Solution Fitness: 20760530
Generation: 3
New Best Solution Fitness: 20623331
New Best Solution Fitness: 20618378
New Best Solution Fitness: 20616821
New Best Solution Fitness: 20598839
Generation: 4
New Best Solution Fitness: 20529176
New Best Solution Fitness: 20528015
New Best Solution Fitness: 20527941
New Best Solution Fitness: 20526895
Generation: 5
New Best Solution Fitness: 20525395
New Best Solution Fitness: 20525328
New Best Solution Fitness: 20525111
New Best Solution Fitness: 20525109
New Best Solution Fitness: 20524760
Generation: 6
New Best Solution Fitness: 20524693
New Best Solution Fitness: 20524474
Generation: 7
New Best Solution Fitness: 20520506
New Best Solution Fitness: 20519786
Generation: 8
New Best Solution Fitness: 20518836
New Best Solution Fitness: 20518733
New Best Solution Fitness: 20518163
Generation: 9
New Best Solution Fitness: 20517761
Generation: 10
New Best Solution Fitness: 20517658
New Best Solution Fitness: 20515143
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 7.78889 
Mean sub-tour choices: 9.02222 
Best Solution Fitness: 20515143 
--------------------------------------------- 
