--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142697
New Best Solution Fitness: 142518
Generation: 3
New Best Solution Fitness: 141848
New Best Solution Fitness: 141798
New Best Solution Fitness: 141727
New Best Solution Fitness: 141697
Generation: 4
New Best Solution Fitness: 141677
New Best Solution Fitness: 141656
New Best Solution Fitness: 141631
New Best Solution Fitness: 141607
Generation: 5
New Best Solution Fitness: 141601
New Best Solution Fitness: 141598
Generation: 6
New Best Solution Fitness: 141591
Generation: 7
New Best Solution Fitness: 141580
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.71111 
Mean sub-tour choices: 3.62222 
Best Solution Fitness: 141580 
--------------------------------------------- 
