--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141601
New Best Solution Fitness: 141538
New Best Solution Fitness: 141504
New Best Solution Fitness: 141467
Generation: 3
New Best Solution Fitness: 141293
New Best Solution Fitness: 141271
New Best Solution Fitness: 141249
Generation: 4
New Best Solution Fitness: 141207
New Best Solution Fitness: 141199
New Best Solution Fitness: 141188
New Best Solution Fitness: 141183
Generation: 5
New Best Solution Fitness: 141172
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.07778 
Mean sub-tour choices: 5.13333 
Best Solution Fitness: 141172 
--------------------------------------------- 
