--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141540
New Best Solution Fitness: 141515
New Best Solution Fitness: 141415
Generation: 3
New Best Solution Fitness: 141065
New Best Solution Fitness: 141044
Generation: 4
New Best Solution Fitness: 141036
New Best Solution Fitness: 141015
Generation: 5
New Best Solution Fitness: 141013
New Best Solution Fitness: 140997
Generation: 6
New Best Solution Fitness: 140971
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.63333 
Mean sub-tour choices: 2.25556 
Best Solution Fitness: 140971 
--------------------------------------------- 
