--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142430
New Best Solution Fitness: 142384
New Best Solution Fitness: 142337
New Best Solution Fitness: 142257
Generation: 3
New Best Solution Fitness: 141744
New Best Solution Fitness: 141743
New Best Solution Fitness: 141741
New Best Solution Fitness: 141740
Generation: 4
New Best Solution Fitness: 141735
New Best Solution Fitness: 141661
Generation: 5
New Best Solution Fitness: 141502
New Best Solution Fitness: 141482
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.97778 
Mean sub-tour choices: 4.07778 
Best Solution Fitness: 141482 
--------------------------------------------- 
