--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141913
New Best Solution Fitness: 141841
New Best Solution Fitness: 141832
New Best Solution Fitness: 141817
New Best Solution Fitness: 141804
Generation: 3
New Best Solution Fitness: 141470
New Best Solution Fitness: 141443
New Best Solution Fitness: 141433
New Best Solution Fitness: 141432
New Best Solution Fitness: 141405
Generation: 4
New Best Solution Fitness: 141364
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.92222 
Mean sub-tour choices: 4.11111 
Best Solution Fitness: 141364 
--------------------------------------------- 
