--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142036
New Best Solution Fitness: 141980
New Best Solution Fitness: 141762
Generation: 3
New Best Solution Fitness: 141550
New Best Solution Fitness: 141549
New Best Solution Fitness: 141494
New Best Solution Fitness: 141493
Generation: 4
New Best Solution Fitness: 141374
Generation: 5
New Best Solution Fitness: 141274
New Best Solution Fitness: 141269
New Best Solution Fitness: 141249
Generation: 6
New Best Solution Fitness: 141248
New Best Solution Fitness: 141243
Generation: 7
New Best Solution Fitness: 141205
Generation: 8
New Best Solution Fitness: 141194
Generation: 9
New Best Solution Fitness: 141145
Generation: 10
New Best Solution Fitness: 141100
New Best Solution Fitness: 141097
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.04444 
Mean sub-tour choices: 3.96667 
Best Solution Fitness: 141097 
--------------------------------------------- 
