--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142233
New Best Solution Fitness: 142203
New Best Solution Fitness: 142153
New Best Solution Fitness: 142117
New Best Solution Fitness: 142100
New Best Solution Fitness: 142064
Generation: 3
New Best Solution Fitness: 141839
New Best Solution Fitness: 141827
New Best Solution Fitness: 141807
New Best Solution Fitness: 141758
New Best Solution Fitness: 141714
New Best Solution Fitness: 141654
Generation: 4
New Best Solution Fitness: 141632
New Best Solution Fitness: 141588
New Best Solution Fitness: 141517
Generation: 5
New Best Solution Fitness: 141481
New Best Solution Fitness: 141466
Generation: 6
New Best Solution Fitness: 141457
New Best Solution Fitness: 141448
New Best Solution Fitness: 141435
Generation: 7
New Best Solution Fitness: 141182
New Best Solution Fitness: 141119
Generation: 8
New Best Solution Fitness: 141102
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.44444 
Mean sub-tour choices: 4.35556 
Best Solution Fitness: 141102 
--------------------------------------------- 
