--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142162
New Best Solution Fitness: 142116
New Best Solution Fitness: 142074
New Best Solution Fitness: 142053
Generation: 3
New Best Solution Fitness: 141670
New Best Solution Fitness: 141534
Generation: 4
New Best Solution Fitness: 141414
New Best Solution Fitness: 141401
New Best Solution Fitness: 141400
Generation: 5
New Best Solution Fitness: 141341
New Best Solution Fitness: 141328
Generation: 6
New Best Solution Fitness: 141323
New Best Solution Fitness: 141280
Generation: 7
New Best Solution Fitness: 141241
New Best Solution Fitness: 141212
Generation: 8
New Best Solution Fitness: 141182
New Best Solution Fitness: 141173
Generation: 9
New Best Solution Fitness: 141165
New Best Solution Fitness: 141027
Generation: 10
New Best Solution Fitness: 141015
New Best Solution Fitness: 140985
New Best Solution Fitness: 140975
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.41111 
Mean sub-tour choices: 4.57778 
Best Solution Fitness: 140975 
--------------------------------------------- 
