--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141143
New Best Solution Fitness: 141140
New Best Solution Fitness: 141135
New Best Solution Fitness: 141112
New Best Solution Fitness: 141053
New Best Solution Fitness: 141044
Generation: 3
New Best Solution Fitness: 140883
New Best Solution Fitness: 140763
Generation: 4
New Best Solution Fitness: 140719
New Best Solution Fitness: 140715
New Best Solution Fitness: 140690
Generation: 5
New Best Solution Fitness: 140584
New Best Solution Fitness: 140479
New Best Solution Fitness: 140475
Generation: 6
New Best Solution Fitness: 140371
New Best Solution Fitness: 140367
New Best Solution Fitness: 140366
Generation: 7
New Best Solution Fitness: 140363
New Best Solution Fitness: 140359
Generation: 8
New Best Solution Fitness: 140355
Generation: 9
New Best Solution Fitness: 140332
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.81111 
Mean sub-tour choices: 4.77778 
Best Solution Fitness: 140332 
--------------------------------------------- 
