--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141960
New Best Solution Fitness: 141952
New Best Solution Fitness: 141913
Generation: 3
New Best Solution Fitness: 141297
New Best Solution Fitness: 141279
Generation: 4
New Best Solution Fitness: 141121
New Best Solution Fitness: 141118
Generation: 5
New Best Solution Fitness: 141025
Generation: 6
New Best Solution Fitness: 140966
New Best Solution Fitness: 140954
Generation: 7
New Best Solution Fitness: 140906
New Best Solution Fitness: 140904
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.71111 
Mean sub-tour choices: 3.6 
Best Solution Fitness: 140904 
--------------------------------------------- 
