--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141609
New Best Solution Fitness: 141565
New Best Solution Fitness: 141553
New Best Solution Fitness: 141522
Generation: 3
New Best Solution Fitness: 141310
New Best Solution Fitness: 141260
Generation: 4
New Best Solution Fitness: 141151
New Best Solution Fitness: 141138
Generation: 5
New Best Solution Fitness: 141098
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 141032
New Best Solution Fitness: 140958
Generation: 9
New Best Solution Fitness: 140774
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.51111 
Mean sub-tour choices: 2.16667 
Best Solution Fitness: 140774 
--------------------------------------------- 
