--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142181
New Best Solution Fitness: 142119
New Best Solution Fitness: 142073
New Best Solution Fitness: 142033
Generation: 3
New Best Solution Fitness: 141894
New Best Solution Fitness: 141891
New Best Solution Fitness: 141883
New Best Solution Fitness: 141882
New Best Solution Fitness: 141826
Generation: 4
New Best Solution Fitness: 141540
New Best Solution Fitness: 141471
Generation: 5
New Best Solution Fitness: 141435
New Best Solution Fitness: 141426
New Best Solution Fitness: 141424
Generation: 6
New Best Solution Fitness: 141422
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.5 
Mean sub-tour choices: 5.52222 
Best Solution Fitness: 141422 
--------------------------------------------- 
