--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142184
New Best Solution Fitness: 142069
New Best Solution Fitness: 142055
Generation: 3
New Best Solution Fitness: 141586
New Best Solution Fitness: 141563
New Best Solution Fitness: 141562
Generation: 4
New Best Solution Fitness: 141529
New Best Solution Fitness: 141438
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 141435
Generation: 8
New Best Solution Fitness: 141401
Generation: 9
New Best Solution Fitness: 141250
New Best Solution Fitness: 141216
Generation: 10
New Best Solution Fitness: 141212
New Best Solution Fitness: 141191
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.2 
Mean sub-tour choices: 4.23333 
Best Solution Fitness: 141191 
--------------------------------------------- 
