--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141755
New Best Solution Fitness: 141709
New Best Solution Fitness: 141702
New Best Solution Fitness: 141695
New Best Solution Fitness: 141679
New Best Solution Fitness: 141538
Generation: 3
New Best Solution Fitness: 141305
New Best Solution Fitness: 141289
New Best Solution Fitness: 141250
New Best Solution Fitness: 141249
New Best Solution Fitness: 141233
Generation: 4
New Best Solution Fitness: 141148
New Best Solution Fitness: 141144
Generation: 5
New Best Solution Fitness: 141109
Generation: 6
New Best Solution Fitness: 141069
New Best Solution Fitness: 141065
Generation: 7
New Best Solution Fitness: 140957
New Best Solution Fitness: 140845
Generation: 8
New Best Solution Fitness: 140837
New Best Solution Fitness: 140821
Generation: 9
New Best Solution Fitness: 140795
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.96667 
Mean sub-tour choices: 2.66667 
Best Solution Fitness: 140795 
--------------------------------------------- 
