--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141815
New Best Solution Fitness: 141734
Generation: 3
New Best Solution Fitness: 141465
New Best Solution Fitness: 141464
Generation: 4
New Best Solution Fitness: 141419
New Best Solution Fitness: 141359
Generation: 5
New Best Solution Fitness: 141278
New Best Solution Fitness: 141248
Generation: 6
New Best Solution Fitness: 141244
Generation: 7
New Best Solution Fitness: 141200
Generation: 8
New Best Solution Fitness: 141186
Generation: 9
New Best Solution Fitness: 141150
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.28889 
Mean sub-tour choices: 3.07778 
Best Solution Fitness: 141150 
--------------------------------------------- 
