--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141962
New Best Solution Fitness: 141820
New Best Solution Fitness: 141798
New Best Solution Fitness: 141671
Generation: 3
New Best Solution Fitness: 141267
New Best Solution Fitness: 141214
New Best Solution Fitness: 141193
New Best Solution Fitness: 141190
Generation: 4
New Best Solution Fitness: 141134
New Best Solution Fitness: 141129
Generation: 5
New Best Solution Fitness: 141128
Generation: 6
New Best Solution Fitness: 141121
New Best Solution Fitness: 141096
Generation: 7
New Best Solution Fitness: 141074
Generation: 8
New Best Solution Fitness: 141049
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.25556 
Mean sub-tour choices: 4.31111 
Best Solution Fitness: 141049 
--------------------------------------------- 
