--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141542
New Best Solution Fitness: 141484
New Best Solution Fitness: 141360
Generation: 3
New Best Solution Fitness: 141086
New Best Solution Fitness: 141078
New Best Solution Fitness: 141067
New Best Solution Fitness: 141065
Generation: 4
New Best Solution Fitness: 141031
New Best Solution Fitness: 141012
New Best Solution Fitness: 141008
Generation: 5
New Best Solution Fitness: 140958
Generation: 6
New Best Solution Fitness: 140944
New Best Solution Fitness: 140943
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 140916
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.24444 
Mean sub-tour choices: 4.27778 
Best Solution Fitness: 140916 
--------------------------------------------- 
