--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142109
New Best Solution Fitness: 141978
New Best Solution Fitness: 141958
New Best Solution Fitness: 141869
Generation: 3
New Best Solution Fitness: 141766
New Best Solution Fitness: 141761
New Best Solution Fitness: 141722
New Best Solution Fitness: 141588
Generation: 4
New Best Solution Fitness: 141546
New Best Solution Fitness: 141543
New Best Solution Fitness: 141530
New Best Solution Fitness: 141398
Generation: 5
New Best Solution Fitness: 141385
New Best Solution Fitness: 141364
Generation: 6
Generation: 7
New Best Solution Fitness: 141361
Generation: 8
New Best Solution Fitness: 141348
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.53333 
Mean sub-tour choices: 5.64444 
Best Solution Fitness: 141348 
--------------------------------------------- 
