--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142343
New Best Solution Fitness: 142206
New Best Solution Fitness: 142103
Generation: 3
New Best Solution Fitness: 141839
New Best Solution Fitness: 141796
New Best Solution Fitness: 141718
New Best Solution Fitness: 141691
Generation: 4
New Best Solution Fitness: 141641
New Best Solution Fitness: 141626
New Best Solution Fitness: 141618
New Best Solution Fitness: 141615
Generation: 5
New Best Solution Fitness: 141589
New Best Solution Fitness: 141574
New Best Solution Fitness: 141566
Generation: 6
New Best Solution Fitness: 141551
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 141487
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.68889 
Mean sub-tour choices: 4.97778 
Best Solution Fitness: 141487 
--------------------------------------------- 
