--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142587
New Best Solution Fitness: 142548
New Best Solution Fitness: 142506
Generation: 3
New Best Solution Fitness: 142161
New Best Solution Fitness: 142160
New Best Solution Fitness: 142153
New Best Solution Fitness: 142142
New Best Solution Fitness: 142138
Generation: 4
New Best Solution Fitness: 142092
New Best Solution Fitness: 142077
New Best Solution Fitness: 142071
Generation: 5
New Best Solution Fitness: 141872
New Best Solution Fitness: 141863
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 141822
New Best Solution Fitness: 141813
Generation: 10
New Best Solution Fitness: 141809
New Best Solution Fitness: 141545
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.08889 
Mean sub-tour choices: 4.14444 
Best Solution Fitness: 141545 
--------------------------------------------- 
