--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142018
New Best Solution Fitness: 141919
New Best Solution Fitness: 141789
Generation: 3
New Best Solution Fitness: 141670
New Best Solution Fitness: 141476
Generation: 4
New Best Solution Fitness: 141468
New Best Solution Fitness: 141440
New Best Solution Fitness: 141424
Generation: 5
New Best Solution Fitness: 141393
New Best Solution Fitness: 141391
New Best Solution Fitness: 141383
Generation: 6
New Best Solution Fitness: 141346
New Best Solution Fitness: 141339
New Best Solution Fitness: 141329
Generation: 7
New Best Solution Fitness: 141322
Generation: 8
Generation: 9
New Best Solution Fitness: 141237
Generation: 10
New Best Solution Fitness: 141202
New Best Solution Fitness: 141200
New Best Solution Fitness: 141150
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.46667 
Mean sub-tour choices: 4.43333 
Best Solution Fitness: 141150 
--------------------------------------------- 
