--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141427
New Best Solution Fitness: 141342
New Best Solution Fitness: 141339
Generation: 3
New Best Solution Fitness: 141068
Generation: 4
New Best Solution Fitness: 141059
New Best Solution Fitness: 141031
Generation: 5
New Best Solution Fitness: 140992
New Best Solution Fitness: 140981
Generation: 6
Generation: 7
New Best Solution Fitness: 140959
New Best Solution Fitness: 140958
Generation: 8
New Best Solution Fitness: 140936
Generation: 9
New Best Solution Fitness: 140935
New Best Solution Fitness: 140753
Generation: 10
New Best Solution Fitness: 140712
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.91111 
Mean sub-tour choices: 2.6 
Best Solution Fitness: 140712 
--------------------------------------------- 
