--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141366
New Best Solution Fitness: 141292
New Best Solution Fitness: 141272
New Best Solution Fitness: 141268
New Best Solution Fitness: 141138
Generation: 3
New Best Solution Fitness: 141072
New Best Solution Fitness: 141070
New Best Solution Fitness: 141054
Generation: 4
New Best Solution Fitness: 141036
New Best Solution Fitness: 140987
Generation: 5
New Best Solution Fitness: 140985
Generation: 6
Generation: 7
New Best Solution Fitness: 140903
New Best Solution Fitness: 140893
Generation: 8
New Best Solution Fitness: 140885
Generation: 9
New Best Solution Fitness: 140859
Generation: 10
New Best Solution Fitness: 140801
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.85556 
Mean sub-tour choices: 3.72222 
Best Solution Fitness: 140801 
--------------------------------------------- 
