--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141471
New Best Solution Fitness: 141369
New Best Solution Fitness: 141362
New Best Solution Fitness: 141335
Generation: 3
New Best Solution Fitness: 141060
New Best Solution Fitness: 141036
New Best Solution Fitness: 140958
Generation: 4
New Best Solution Fitness: 140882
New Best Solution Fitness: 140881
New Best Solution Fitness: 140879
Generation: 5
New Best Solution Fitness: 140873
New Best Solution Fitness: 140872
Generation: 6
New Best Solution Fitness: 140855
Generation: 7
Generation: 8
New Best Solution Fitness: 140824
Generation: 9
New Best Solution Fitness: 140628
Generation: 10
New Best Solution Fitness: 140627
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.52222 
Mean sub-tour choices: 3.37778 
Best Solution Fitness: 140627 
--------------------------------------------- 
