--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 140930
New Best Solution Fitness: 140829
New Best Solution Fitness: 140758
New Best Solution Fitness: 140751
New Best Solution Fitness: 140678
Generation: 3
New Best Solution Fitness: 140634
New Best Solution Fitness: 140618
Generation: 4
New Best Solution Fitness: 140584
New Best Solution Fitness: 140520
New Best Solution Fitness: 140430
Generation: 5
Generation: 6
New Best Solution Fitness: 140404
Generation: 7
Generation: 8
New Best Solution Fitness: 140358
Generation: 9
New Best Solution Fitness: 140351
Generation: 10
New Best Solution Fitness: 140326
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.88889 
Mean sub-tour choices: 2.98889 
Best Solution Fitness: 140326 
--------------------------------------------- 
