--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142161
New Best Solution Fitness: 142101
New Best Solution Fitness: 142088
New Best Solution Fitness: 142066
New Best Solution Fitness: 141956
Generation: 3
New Best Solution Fitness: 141411
New Best Solution Fitness: 141376
Generation: 4
New Best Solution Fitness: 141226
Generation: 5
Generation: 6
New Best Solution Fitness: 141221
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.84444 
Mean sub-tour choices: 2.63333 
Best Solution Fitness: 141221 
--------------------------------------------- 
