--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141819
New Best Solution Fitness: 141761
Generation: 3
New Best Solution Fitness: 141625
New Best Solution Fitness: 141557
New Best Solution Fitness: 141490
Generation: 4
New Best Solution Fitness: 141411
New Best Solution Fitness: 141394
Generation: 5
New Best Solution Fitness: 141383
New Best Solution Fitness: 141380
Generation: 6
New Best Solution Fitness: 141355
New Best Solution Fitness: 141338
Generation: 7
New Best Solution Fitness: 141333
Generation: 8
Generation: 9
New Best Solution Fitness: 141330
Generation: 10
New Best Solution Fitness: 141325
New Best Solution Fitness: 141322
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.16667 
Mean sub-tour choices: 4.16667 
Best Solution Fitness: 141322 
--------------------------------------------- 
