--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142102
New Best Solution Fitness: 142074
New Best Solution Fitness: 142068
New Best Solution Fitness: 141971
New Best Solution Fitness: 141873
Generation: 3
New Best Solution Fitness: 141658
New Best Solution Fitness: 141657
New Best Solution Fitness: 141629
Generation: 4
New Best Solution Fitness: 141606
New Best Solution Fitness: 141532
Generation: 5
New Best Solution Fitness: 141450
Generation: 6
New Best Solution Fitness: 141442
Generation: 7
New Best Solution Fitness: 141419
New Best Solution Fitness: 141402
Generation: 8
New Best Solution Fitness: 141308
Generation: 9
New Best Solution Fitness: 141298
Generation: 10
New Best Solution Fitness: 141137
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.91111 
Mean sub-tour choices: 3.64444 
Best Solution Fitness: 141137 
--------------------------------------------- 
