--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142134
New Best Solution Fitness: 142033
New Best Solution Fitness: 142026
New Best Solution Fitness: 142005
New Best Solution Fitness: 141914
New Best Solution Fitness: 141912
Generation: 3
New Best Solution Fitness: 141496
New Best Solution Fitness: 141429
New Best Solution Fitness: 141375
Generation: 4
New Best Solution Fitness: 141229
New Best Solution Fitness: 141201
New Best Solution Fitness: 141118
Generation: 5
New Best Solution Fitness: 141095
New Best Solution Fitness: 141079
Generation: 6
New Best Solution Fitness: 141035
Generation: 7
New Best Solution Fitness: 141034
Generation: 8
New Best Solution Fitness: 141025
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.81111 
Mean sub-tour choices: 3.74444 
Best Solution Fitness: 141025 
--------------------------------------------- 
