--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141894
New Best Solution Fitness: 141582
Generation: 3
New Best Solution Fitness: 141282
New Best Solution Fitness: 141190
New Best Solution Fitness: 141168
Generation: 4
New Best Solution Fitness: 141150
New Best Solution Fitness: 141137
New Best Solution Fitness: 141088
Generation: 5
New Best Solution Fitness: 141075
Generation: 6
Generation: 7
New Best Solution Fitness: 140970
Generation: 8
New Best Solution Fitness: 140890
New Best Solution Fitness: 140873
Generation: 9
New Best Solution Fitness: 140847
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.26667 
Mean sub-tour choices: 5.4 
Best Solution Fitness: 140847 
--------------------------------------------- 
