--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142004
New Best Solution Fitness: 141851
New Best Solution Fitness: 141807
New Best Solution Fitness: 141680
Generation: 3
New Best Solution Fitness: 141352
New Best Solution Fitness: 141163
Generation: 4
New Best Solution Fitness: 141038
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 140985
Generation: 8
New Best Solution Fitness: 140943
New Best Solution Fitness: 140942
New Best Solution Fitness: 140911
Generation: 9
New Best Solution Fitness: 140886
New Best Solution Fitness: 140850
New Best Solution Fitness: 140847
Generation: 10
New Best Solution Fitness: 140844
New Best Solution Fitness: 140842
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.9 
Mean sub-tour choices: 2.63333 
Best Solution Fitness: 140842 
--------------------------------------------- 
