--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141289
New Best Solution Fitness: 141191
New Best Solution Fitness: 141178
New Best Solution Fitness: 141160
New Best Solution Fitness: 141130
New Best Solution Fitness: 141109
Generation: 3
New Best Solution Fitness: 140992
New Best Solution Fitness: 140979
New Best Solution Fitness: 140928
Generation: 4
New Best Solution Fitness: 140828
New Best Solution Fitness: 140809
Generation: 5
New Best Solution Fitness: 140796
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.18889 
Mean sub-tour choices: 3.2 
Best Solution Fitness: 140796 
--------------------------------------------- 
