--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141513
New Best Solution Fitness: 141351
New Best Solution Fitness: 141344
New Best Solution Fitness: 141326
New Best Solution Fitness: 141206
Generation: 3
New Best Solution Fitness: 141004
New Best Solution Fitness: 140920
Generation: 4
New Best Solution Fitness: 140889
New Best Solution Fitness: 140885
New Best Solution Fitness: 140869
Generation: 5
New Best Solution Fitness: 140865
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 140860
Generation: 9
New Best Solution Fitness: 140789
New Best Solution Fitness: 140759
Generation: 10
New Best Solution Fitness: 140755
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.31111 
Mean sub-tour choices: 4.64444 
Best Solution Fitness: 140755 
--------------------------------------------- 
