--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141965
New Best Solution Fitness: 141882
New Best Solution Fitness: 141855
New Best Solution Fitness: 141843
New Best Solution Fitness: 141791
New Best Solution Fitness: 141779
Generation: 3
New Best Solution Fitness: 141430
New Best Solution Fitness: 141416
New Best Solution Fitness: 141374
Generation: 4
New Best Solution Fitness: 141237
New Best Solution Fitness: 141200
Generation: 5
New Best Solution Fitness: 141190
New Best Solution Fitness: 141180
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 141133
Generation: 9
Generation: 10
New Best Solution Fitness: 141107
New Best Solution Fitness: 141065
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.31111 
Mean sub-tour choices: 4.48889 
Best Solution Fitness: 141065 
--------------------------------------------- 
