--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141365
New Best Solution Fitness: 141285
New Best Solution Fitness: 141264
Generation: 3
New Best Solution Fitness: 140815
New Best Solution Fitness: 140814
New Best Solution Fitness: 140791
Generation: 4
New Best Solution Fitness: 140729
New Best Solution Fitness: 140726
Generation: 5
New Best Solution Fitness: 140725
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.58889 
Mean sub-tour choices: 3.6 
Best Solution Fitness: 140725 
--------------------------------------------- 
