--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142167
New Best Solution Fitness: 141872
New Best Solution Fitness: 141822
Generation: 3
New Best Solution Fitness: 141544
New Best Solution Fitness: 141495
New Best Solution Fitness: 141482
Generation: 4
New Best Solution Fitness: 141433
Generation: 5
New Best Solution Fitness: 141431
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.32222 
Mean sub-tour choices: 4.3 
Best Solution Fitness: 141431 
--------------------------------------------- 
