--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142038
New Best Solution Fitness: 141935
New Best Solution Fitness: 141643
New Best Solution Fitness: 141609
Generation: 3
New Best Solution Fitness: 141241
New Best Solution Fitness: 140933
Generation: 4
New Best Solution Fitness: 140872
New Best Solution Fitness: 140852
Generation: 5
New Best Solution Fitness: 140738
Generation: 6
New Best Solution Fitness: 140735
New Best Solution Fitness: 140732
New Best Solution Fitness: 140717
Generation: 7
New Best Solution Fitness: 140646
New Best Solution Fitness: 140628
New Best Solution Fitness: 140621
New Best Solution Fitness: 140620
Generation: 8
New Best Solution Fitness: 140478
New Best Solution Fitness: 140388
Generation: 9
New Best Solution Fitness: 140379
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.23333 
Mean sub-tour choices: 4.06667 
Best Solution Fitness: 140379 
--------------------------------------------- 
