--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141695
New Best Solution Fitness: 141667
New Best Solution Fitness: 141636
Generation: 3
New Best Solution Fitness: 141453
New Best Solution Fitness: 141409
New Best Solution Fitness: 141332
Generation: 4
New Best Solution Fitness: 141220
New Best Solution Fitness: 141210
Generation: 5
New Best Solution Fitness: 141196
Generation: 6
New Best Solution Fitness: 141187
Generation: 7
New Best Solution Fitness: 141180
New Best Solution Fitness: 141172
New Best Solution Fitness: 141164
Generation: 8
Generation: 9
New Best Solution Fitness: 141057
New Best Solution Fitness: 140954
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.9 
Mean sub-tour choices: 2.64444 
Best Solution Fitness: 140954 
--------------------------------------------- 
