--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142004
New Best Solution Fitness: 141884
New Best Solution Fitness: 141855
Generation: 3
New Best Solution Fitness: 141648
New Best Solution Fitness: 141604
Generation: 4
New Best Solution Fitness: 141589
Generation: 5
Generation: 6
New Best Solution Fitness: 141514
Generation: 7
New Best Solution Fitness: 141369
New Best Solution Fitness: 141346
New Best Solution Fitness: 141333
Generation: 8
New Best Solution Fitness: 141286
New Best Solution Fitness: 141282
Generation: 9
New Best Solution Fitness: 141059
New Best Solution Fitness: 140958
Generation: 10
New Best Solution Fitness: 140926
New Best Solution Fitness: 140898
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.97778 
Mean sub-tour choices: 3.78889 
Best Solution Fitness: 140898 
--------------------------------------------- 
