--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141879
New Best Solution Fitness: 141543
Generation: 3
New Best Solution Fitness: 141337
New Best Solution Fitness: 141262
New Best Solution Fitness: 141193
Generation: 4
New Best Solution Fitness: 141171
New Best Solution Fitness: 141160
Generation: 5
New Best Solution Fitness: 141067
New Best Solution Fitness: 141066
New Best Solution Fitness: 141062
Generation: 6
New Best Solution Fitness: 141061
Generation: 7
New Best Solution Fitness: 140869
Generation: 8
New Best Solution Fitness: 140854
New Best Solution Fitness: 140810
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.21111 
Mean sub-tour choices: 3.05556 
Best Solution Fitness: 140810 
--------------------------------------------- 
