--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142692
New Best Solution Fitness: 142677
New Best Solution Fitness: 142598
New Best Solution Fitness: 142508
Generation: 3
New Best Solution Fitness: 141778
New Best Solution Fitness: 141767
New Best Solution Fitness: 141689
Generation: 4
New Best Solution Fitness: 141492
New Best Solution Fitness: 141484
New Best Solution Fitness: 141408
New Best Solution Fitness: 141344
Generation: 5
New Best Solution Fitness: 141327
New Best Solution Fitness: 141321
Generation: 6
New Best Solution Fitness: 141320
New Best Solution Fitness: 141319
Generation: 7
Generation: 8
New Best Solution Fitness: 141315
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.5 
Mean sub-tour choices: 4.93333 
Best Solution Fitness: 141315 
--------------------------------------------- 
