--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141959
New Best Solution Fitness: 141914
New Best Solution Fitness: 141887
New Best Solution Fitness: 141797
Generation: 3
New Best Solution Fitness: 141613
New Best Solution Fitness: 141575
New Best Solution Fitness: 141544
New Best Solution Fitness: 141506
Generation: 4
New Best Solution Fitness: 141471
New Best Solution Fitness: 141344
Generation: 5
New Best Solution Fitness: 141106
New Best Solution Fitness: 141092
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 141005
New Best Solution Fitness: 140999
New Best Solution Fitness: 140979
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.16667 
Mean sub-tour choices: 3.06667 
Best Solution Fitness: 140979 
--------------------------------------------- 
