--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141482
New Best Solution Fitness: 141452
New Best Solution Fitness: 141384
New Best Solution Fitness: 141370
New Best Solution Fitness: 141245
Generation: 3
New Best Solution Fitness: 141160
New Best Solution Fitness: 141016
New Best Solution Fitness: 141000
Generation: 4
New Best Solution Fitness: 140972
New Best Solution Fitness: 140856
Generation: 5
New Best Solution Fitness: 140755
New Best Solution Fitness: 140727
Generation: 6
Generation: 7
New Best Solution Fitness: 140713
New Best Solution Fitness: 140691
Generation: 8
New Best Solution Fitness: 140644
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.62222 
Mean sub-tour choices: 4.56667 
Best Solution Fitness: 140644 
--------------------------------------------- 
