--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142319
New Best Solution Fitness: 142296
New Best Solution Fitness: 142195
Generation: 3
New Best Solution Fitness: 142040
New Best Solution Fitness: 142010
New Best Solution Fitness: 141803
Generation: 4
New Best Solution Fitness: 141567
Generation: 5
New Best Solution Fitness: 141539
New Best Solution Fitness: 141526
New Best Solution Fitness: 141426
Generation: 6
New Best Solution Fitness: 141425
New Best Solution Fitness: 141413
Generation: 7
New Best Solution Fitness: 141400
Generation: 8
Generation: 9
New Best Solution Fitness: 141281
New Best Solution Fitness: 141256
New Best Solution Fitness: 141255
New Best Solution Fitness: 141232
Generation: 10
New Best Solution Fitness: 141231
New Best Solution Fitness: 141219
New Best Solution Fitness: 141165
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.45556 
Mean sub-tour choices: 3.53333 
Best Solution Fitness: 141165 
--------------------------------------------- 
