--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141988
New Best Solution Fitness: 141867
Generation: 3
New Best Solution Fitness: 141517
New Best Solution Fitness: 141512
New Best Solution Fitness: 141495
New Best Solution Fitness: 141269
Generation: 4
New Best Solution Fitness: 141264
New Best Solution Fitness: 141263
Generation: 5
New Best Solution Fitness: 141258
Generation: 6
Generation: 7
New Best Solution Fitness: 141251
Generation: 8
New Best Solution Fitness: 141227
Generation: 9
New Best Solution Fitness: 141225
Generation: 10
New Best Solution Fitness: 141224
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.16667 
Mean sub-tour choices: 3.28889 
Best Solution Fitness: 141224 
--------------------------------------------- 
