--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142079
New Best Solution Fitness: 141942
New Best Solution Fitness: 141909
Generation: 3
New Best Solution Fitness: 141704
New Best Solution Fitness: 141622
New Best Solution Fitness: 141574
Generation: 4
New Best Solution Fitness: 141520
Generation: 5
Generation: 6
New Best Solution Fitness: 141479
New Best Solution Fitness: 141468
Generation: 7
New Best Solution Fitness: 141467
Generation: 8
New Best Solution Fitness: 141356
New Best Solution Fitness: 141228
Generation: 9
New Best Solution Fitness: 140946
New Best Solution Fitness: 140929
Generation: 10
New Best Solution Fitness: 140889
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.27778 
Mean sub-tour choices: 4.28889 
Best Solution Fitness: 140889 
--------------------------------------------- 
