--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141801
New Best Solution Fitness: 141782
New Best Solution Fitness: 141757
New Best Solution Fitness: 141646
Generation: 3
New Best Solution Fitness: 141310
New Best Solution Fitness: 141287
New Best Solution Fitness: 141284
New Best Solution Fitness: 141277
Generation: 4
New Best Solution Fitness: 141246
New Best Solution Fitness: 141239
Generation: 5
New Best Solution Fitness: 141230
Generation: 6
New Best Solution Fitness: 141226
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 141225
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.36667 
Mean sub-tour choices: 3.34444 
Best Solution Fitness: 141225 
--------------------------------------------- 
