--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142329
New Best Solution Fitness: 142192
New Best Solution Fitness: 142092
New Best Solution Fitness: 142072
Generation: 3
New Best Solution Fitness: 141946
New Best Solution Fitness: 141910
New Best Solution Fitness: 141901
New Best Solution Fitness: 141891
Generation: 4
New Best Solution Fitness: 141882
New Best Solution Fitness: 141863
New Best Solution Fitness: 141861
Generation: 5
New Best Solution Fitness: 141779
Generation: 6
New Best Solution Fitness: 141756
New Best Solution Fitness: 141746
Generation: 7
New Best Solution Fitness: 141727
Generation: 8
New Best Solution Fitness: 141707
Generation: 9
New Best Solution Fitness: 141644
Generation: 10
New Best Solution Fitness: 141639
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.33333 
Mean sub-tour choices: 4.5 
Best Solution Fitness: 141639 
--------------------------------------------- 
