--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141938
New Best Solution Fitness: 141675
Generation: 3
New Best Solution Fitness: 141603
New Best Solution Fitness: 141599
New Best Solution Fitness: 141553
Generation: 4
New Best Solution Fitness: 141543
Generation: 5
New Best Solution Fitness: 141525
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 141515
New Best Solution Fitness: 141507
Generation: 9
New Best Solution Fitness: 141381
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.07778 
Mean sub-tour choices: 2.94444 
Best Solution Fitness: 141381 
--------------------------------------------- 
