--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142474
New Best Solution Fitness: 142293
New Best Solution Fitness: 142278
Generation: 3
New Best Solution Fitness: 141787
New Best Solution Fitness: 141746
New Best Solution Fitness: 141740
Generation: 4
New Best Solution Fitness: 141600
New Best Solution Fitness: 141578
Generation: 5
New Best Solution Fitness: 141566
New Best Solution Fitness: 141552
Generation: 6
New Best Solution Fitness: 141528
Generation: 7
New Best Solution Fitness: 141516
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.13333 
Mean sub-tour choices: 5.32222 
Best Solution Fitness: 141516 
--------------------------------------------- 
