--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141856
New Best Solution Fitness: 141832
New Best Solution Fitness: 141817
New Best Solution Fitness: 141798
New Best Solution Fitness: 141760
Generation: 3
New Best Solution Fitness: 141320
New Best Solution Fitness: 141272
New Best Solution Fitness: 141226
Generation: 4
New Best Solution Fitness: 141181
New Best Solution Fitness: 141167
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 141158
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.91111 
Mean sub-tour choices: 3.83333 
Best Solution Fitness: 141158 
--------------------------------------------- 
