--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141966
New Best Solution Fitness: 141717
New Best Solution Fitness: 141563
Generation: 3
New Best Solution Fitness: 141176
New Best Solution Fitness: 141072
New Best Solution Fitness: 141055
Generation: 4
New Best Solution Fitness: 140940
New Best Solution Fitness: 140939
New Best Solution Fitness: 140891
Generation: 5
New Best Solution Fitness: 140842
New Best Solution Fitness: 140814
Generation: 6
New Best Solution Fitness: 140788
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 140787
Generation: 10
New Best Solution Fitness: 140757
New Best Solution Fitness: 140755
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.78889 
Mean sub-tour choices: 3.94444 
Best Solution Fitness: 140755 
--------------------------------------------- 
