--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142541
New Best Solution Fitness: 142508
New Best Solution Fitness: 142489
New Best Solution Fitness: 142464
New Best Solution Fitness: 142386
New Best Solution Fitness: 142251
New Best Solution Fitness: 142246
Generation: 3
New Best Solution Fitness: 141915
New Best Solution Fitness: 141822
Generation: 4
New Best Solution Fitness: 141759
New Best Solution Fitness: 141730
New Best Solution Fitness: 141728
Generation: 5
New Best Solution Fitness: 141699
New Best Solution Fitness: 141696
Generation: 6
New Best Solution Fitness: 141695
New Best Solution Fitness: 141691
Generation: 7
New Best Solution Fitness: 141676
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.13333 
Mean sub-tour choices: 4.01111 
Best Solution Fitness: 141676 
--------------------------------------------- 
