--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142074
New Best Solution Fitness: 141966
New Best Solution Fitness: 141965
New Best Solution Fitness: 141908
Generation: 3
New Best Solution Fitness: 141420
New Best Solution Fitness: 141382
New Best Solution Fitness: 141344
New Best Solution Fitness: 141201
Generation: 4
New Best Solution Fitness: 141135
New Best Solution Fitness: 141068
New Best Solution Fitness: 141060
Generation: 5
New Best Solution Fitness: 141030
New Best Solution Fitness: 141024
New Best Solution Fitness: 141015
Generation: 6
New Best Solution Fitness: 141013
New Best Solution Fitness: 141002
Generation: 7
New Best Solution Fitness: 140942
New Best Solution Fitness: 140940
New Best Solution Fitness: 140936
New Best Solution Fitness: 140905
Generation: 8
New Best Solution Fitness: 140903
New Best Solution Fitness: 140899
New Best Solution Fitness: 140897
Generation: 9
New Best Solution Fitness: 140893
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.15556 
Mean sub-tour choices: 5.13333 
Best Solution Fitness: 140893 
--------------------------------------------- 
