--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141788
New Best Solution Fitness: 141699
Generation: 3
New Best Solution Fitness: 141562
New Best Solution Fitness: 141539
New Best Solution Fitness: 141533
Generation: 4
New Best Solution Fitness: 141436
New Best Solution Fitness: 141434
New Best Solution Fitness: 141413
New Best Solution Fitness: 141402
Generation: 5
New Best Solution Fitness: 141390
New Best Solution Fitness: 141382
Generation: 6
New Best Solution Fitness: 141259
New Best Solution Fitness: 141239
Generation: 7
New Best Solution Fitness: 141165
Generation: 8
New Best Solution Fitness: 141163
Generation: 9
Generation: 10
New Best Solution Fitness: 141145
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.1 
Mean sub-tour choices: 4.05556 
Best Solution Fitness: 141145 
--------------------------------------------- 
