--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141632
New Best Solution Fitness: 141452
New Best Solution Fitness: 141450
Generation: 3
New Best Solution Fitness: 141255
Generation: 4
New Best Solution Fitness: 141246
Generation: 5
New Best Solution Fitness: 140994
New Best Solution Fitness: 140981
New Best Solution Fitness: 140969
Generation: 6
New Best Solution Fitness: 140966
New Best Solution Fitness: 140965
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.57778 
Mean sub-tour choices: 3.38889 
Best Solution Fitness: 140965 
--------------------------------------------- 
