--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142742
New Best Solution Fitness: 142561
New Best Solution Fitness: 142525
New Best Solution Fitness: 142438
Generation: 3
New Best Solution Fitness: 141956
New Best Solution Fitness: 141951
New Best Solution Fitness: 141907
New Best Solution Fitness: 141887
Generation: 4
New Best Solution Fitness: 141881
New Best Solution Fitness: 141876
New Best Solution Fitness: 141863
Generation: 5
New Best Solution Fitness: 141847
Generation: 6
New Best Solution Fitness: 141842
Generation: 7
New Best Solution Fitness: 141803
Generation: 8
New Best Solution Fitness: 141790
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.6 
Mean sub-tour choices: 3.56667 
Best Solution Fitness: 141790 
--------------------------------------------- 
