--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141479
New Best Solution Fitness: 141342
New Best Solution Fitness: 141310
New Best Solution Fitness: 141286
New Best Solution Fitness: 141277
Generation: 3
New Best Solution Fitness: 141170
New Best Solution Fitness: 141161
New Best Solution Fitness: 141148
New Best Solution Fitness: 141108
New Best Solution Fitness: 141103
Generation: 4
New Best Solution Fitness: 140948
New Best Solution Fitness: 140943
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 140906
New Best Solution Fitness: 140899
Generation: 9
New Best Solution Fitness: 140816
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.68889 
Mean sub-tour choices: 3.8 
Best Solution Fitness: 140816 
--------------------------------------------- 
