--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142010
New Best Solution Fitness: 141946
New Best Solution Fitness: 141936
New Best Solution Fitness: 141817
Generation: 3
New Best Solution Fitness: 141458
New Best Solution Fitness: 141417
New Best Solution Fitness: 141390
New Best Solution Fitness: 141330
Generation: 4
New Best Solution Fitness: 141130
New Best Solution Fitness: 141101
Generation: 5
Generation: 6
New Best Solution Fitness: 141066
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 141052
New Best Solution Fitness: 141033
Generation: 10
New Best Solution Fitness: 140992
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.32222 
Mean sub-tour choices: 3.36667 
Best Solution Fitness: 140992 
--------------------------------------------- 
