--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142293
New Best Solution Fitness: 142276
New Best Solution Fitness: 142273
New Best Solution Fitness: 142131
Generation: 3
New Best Solution Fitness: 141886
New Best Solution Fitness: 141870
New Best Solution Fitness: 141864
Generation: 4
New Best Solution Fitness: 141757
New Best Solution Fitness: 141753
New Best Solution Fitness: 141748
Generation: 5
Generation: 6
New Best Solution Fitness: 141717
Generation: 7
New Best Solution Fitness: 141710
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.08889 
Mean sub-tour choices: 2.9 
Best Solution Fitness: 141710 
--------------------------------------------- 
