--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142242
New Best Solution Fitness: 142127
New Best Solution Fitness: 142111
New Best Solution Fitness: 142103
Generation: 3
New Best Solution Fitness: 141779
New Best Solution Fitness: 141765
New Best Solution Fitness: 141761
Generation: 4
New Best Solution Fitness: 141573
New Best Solution Fitness: 141565
Generation: 5
New Best Solution Fitness: 141551
Generation: 6
New Best Solution Fitness: 141527
New Best Solution Fitness: 141491
New Best Solution Fitness: 141409
Generation: 7
New Best Solution Fitness: 141274
Generation: 8
New Best Solution Fitness: 141256
Generation: 9
Generation: 10
New Best Solution Fitness: 141250
New Best Solution Fitness: 140984
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.35556 
Mean sub-tour choices: 3.27778 
Best Solution Fitness: 140984 
--------------------------------------------- 
