--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142177
New Best Solution Fitness: 142069
New Best Solution Fitness: 142058
New Best Solution Fitness: 141996
New Best Solution Fitness: 141873
Generation: 3
New Best Solution Fitness: 141677
New Best Solution Fitness: 141633
New Best Solution Fitness: 141598
Generation: 4
New Best Solution Fitness: 141583
New Best Solution Fitness: 141570
Generation: 5
New Best Solution Fitness: 141555
Generation: 6
New Best Solution Fitness: 141326
New Best Solution Fitness: 141158
Generation: 7
New Best Solution Fitness: 141150
New Best Solution Fitness: 141136
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.76667 
Mean sub-tour choices: 3.55556 
Best Solution Fitness: 141136 
--------------------------------------------- 
