--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 142221
New Best Solution Fitness: 142125
New Best Solution Fitness: 142026
New Best Solution Fitness: 141993
Generation: 3
New Best Solution Fitness: 141525
New Best Solution Fitness: 141447
Generation: 4
New Best Solution Fitness: 141081
Generation: 5
New Best Solution Fitness: 140979
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 140962
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.95556 
Mean sub-tour choices: 3.88889 
Best Solution Fitness: 140962 
--------------------------------------------- 
