--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\pcb3038.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 141392
New Best Solution Fitness: 141321
Generation: 3
New Best Solution Fitness: 140975
New Best Solution Fitness: 140928
New Best Solution Fitness: 140927
New Best Solution Fitness: 140918
Generation: 4
New Best Solution Fitness: 140729
New Best Solution Fitness: 140719
Generation: 5
New Best Solution Fitness: 140624
New Best Solution Fitness: 140623
New Best Solution Fitness: 140617
Generation: 6
New Best Solution Fitness: 140606
New Best Solution Fitness: 140605
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.8 
Mean sub-tour choices: 3.76667 
Best Solution Fitness: 140605 
--------------------------------------------- 
