--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49942
New Best Solution Fitness: 49776
Generation: 3
New Best Solution Fitness: 49593
Generation: 4
New Best Solution Fitness: 49476
Generation: 5
New Best Solution Fitness: 49330
New Best Solution Fitness: 49319
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.977778 
Mean sub-tour choices: 1.77778 
Best Solution Fitness: 49319 
--------------------------------------------- 
