--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50460
New Best Solution Fitness: 50441
New Best Solution Fitness: 50439
New Best Solution Fitness: 50430
Generation: 3
New Best Solution Fitness: 50420
New Best Solution Fitness: 50409
Generation: 4
New Best Solution Fitness: 50383
Generation: 5
New Best Solution Fitness: 50300
New Best Solution Fitness: 50285
Generation: 6
New Best Solution Fitness: 50272
Generation: 7
New Best Solution Fitness: 50202
New Best Solution Fitness: 50187
Generation: 8
New Best Solution Fitness: 50114
Generation: 9
New Best Solution Fitness: 49726
New Best Solution Fitness: 49692
Generation: 10
New Best Solution Fitness: 49613
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.633333 
Mean sub-tour choices: 1.07778 
Best Solution Fitness: 49613 
--------------------------------------------- 
