--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50163
New Best Solution Fitness: 49920
Generation: 3
New Best Solution Fitness: 49717
New Best Solution Fitness: 49688
New Best Solution Fitness: 49619
Generation: 4
New Best Solution Fitness: 49564
New Best Solution Fitness: 49529
Generation: 5
Generation: 6
New Best Solution Fitness: 49522
Generation: 7
Generation: 8
New Best Solution Fitness: 49429
New Best Solution Fitness: 49408
New Best Solution Fitness: 49364
Generation: 9
New Best Solution Fitness: 49343
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.733333 
Mean sub-tour choices: 1.24444 
Best Solution Fitness: 49343 
--------------------------------------------- 
