--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49585
New Best Solution Fitness: 49561
New Best Solution Fitness: 49509
Generation: 3
New Best Solution Fitness: 49499
Generation: 4
New Best Solution Fitness: 49310
New Best Solution Fitness: 49279
Generation: 5
New Best Solution Fitness: 49255
Generation: 6
Generation: 7
New Best Solution Fitness: 49250
Generation: 8
New Best Solution Fitness: 49208
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.866667 
Mean sub-tour choices: 1.27778 
Best Solution Fitness: 49208 
--------------------------------------------- 
