--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50273
New Best Solution Fitness: 50258
Generation: 3
New Best Solution Fitness: 50176
Generation: 4
New Best Solution Fitness: 50084
New Best Solution Fitness: 50075
New Best Solution Fitness: 50019
Generation: 5
New Best Solution Fitness: 49816
Generation: 6
New Best Solution Fitness: 49792
Generation: 7
New Best Solution Fitness: 49636
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 49602
New Best Solution Fitness: 49584
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.955556 
Mean sub-tour choices: 1.38889 
Best Solution Fitness: 49584 
--------------------------------------------- 
