--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49867
Generation: 3
New Best Solution Fitness: 49780
New Best Solution Fitness: 49755
Generation: 4
New Best Solution Fitness: 49702
New Best Solution Fitness: 49694
New Best Solution Fitness: 49677
Generation: 5
New Best Solution Fitness: 49669
Generation: 6
New Best Solution Fitness: 49623
New Best Solution Fitness: 49537
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.766667 
Mean sub-tour choices: 1.46667 
Best Solution Fitness: 49537 
--------------------------------------------- 
