--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49890
New Best Solution Fitness: 49888
New Best Solution Fitness: 49884
New Best Solution Fitness: 49808
Generation: 3
New Best Solution Fitness: 49669
New Best Solution Fitness: 49603
Generation: 4
New Best Solution Fitness: 49526
New Best Solution Fitness: 49489
New Best Solution Fitness: 49435
Generation: 5
New Best Solution Fitness: 49407
New Best Solution Fitness: 49392
Generation: 6
New Best Solution Fitness: 49363
New Best Solution Fitness: 49362
Generation: 7
New Best Solution Fitness: 49345
Generation: 8
Generation: 9
New Best Solution Fitness: 49316
Generation: 10
New Best Solution Fitness: 49264
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.911111 
Mean sub-tour choices: 1.56667 
Best Solution Fitness: 49264 
--------------------------------------------- 
