--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50239
New Best Solution Fitness: 50218
New Best Solution Fitness: 50197
New Best Solution Fitness: 50123
Generation: 3
New Best Solution Fitness: 49893
New Best Solution Fitness: 49872
Generation: 4
New Best Solution Fitness: 49871
Generation: 5
New Best Solution Fitness: 49794
New Best Solution Fitness: 49785
Generation: 6
New Best Solution Fitness: 49746
Generation: 7
New Best Solution Fitness: 49646
New Best Solution Fitness: 49644
Generation: 8
New Best Solution Fitness: 49570
New Best Solution Fitness: 49551
Generation: 9
Generation: 10
New Best Solution Fitness: 49513
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.06667 
Mean sub-tour choices: 1.84444 
Best Solution Fitness: 49513 
--------------------------------------------- 
