--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50141
New Best Solution Fitness: 50077
New Best Solution Fitness: 50046
Generation: 3
New Best Solution Fitness: 49952
New Best Solution Fitness: 49950
Generation: 4
New Best Solution Fitness: 49944
New Best Solution Fitness: 49919
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 49787
New Best Solution Fitness: 49786
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 49729
New Best Solution Fitness: 49728
New Best Solution Fitness: 49714
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1 
Mean sub-tour choices: 1.61111 
Best Solution Fitness: 49714 
--------------------------------------------- 
