--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49963
New Best Solution Fitness: 49873
New Best Solution Fitness: 49824
Generation: 3
New Best Solution Fitness: 49721
New Best Solution Fitness: 49711
New Best Solution Fitness: 49605
Generation: 4
New Best Solution Fitness: 49539
Generation: 5
New Best Solution Fitness: 49534
Generation: 6
New Best Solution Fitness: 49502
New Best Solution Fitness: 49490
Generation: 7
New Best Solution Fitness: 49420
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.41111 
Mean sub-tour choices: 2.5 
Best Solution Fitness: 49420 
--------------------------------------------- 
