--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50177
New Best Solution Fitness: 50134
New Best Solution Fitness: 50074
Generation: 3
New Best Solution Fitness: 49877
New Best Solution Fitness: 49774
Generation: 4
New Best Solution Fitness: 49769
New Best Solution Fitness: 49746
New Best Solution Fitness: 49734
Generation: 5
Generation: 6
New Best Solution Fitness: 49647
Generation: 7
New Best Solution Fitness: 49637
Generation: 8
New Best Solution Fitness: 49389
Generation: 9
New Best Solution Fitness: 49379
Generation: 10
New Best Solution Fitness: 49329
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.06667 
Mean sub-tour choices: 1.67778 
Best Solution Fitness: 49329 
--------------------------------------------- 
