--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49908
New Best Solution Fitness: 49901
New Best Solution Fitness: 49899
New Best Solution Fitness: 49882
New Best Solution Fitness: 49859
Generation: 3
New Best Solution Fitness: 49572
New Best Solution Fitness: 49567
New Best Solution Fitness: 49559
Generation: 4
Generation: 5
New Best Solution Fitness: 49521
New Best Solution Fitness: 49481
Generation: 6
New Best Solution Fitness: 49407
New Best Solution Fitness: 49377
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.766667 
Mean sub-tour choices: 1.26667 
Best Solution Fitness: 49377 
--------------------------------------------- 
