--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49815
New Best Solution Fitness: 49776
New Best Solution Fitness: 49770
New Best Solution Fitness: 49650
Generation: 3
New Best Solution Fitness: 49529
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 49491
New Best Solution Fitness: 49470
Generation: 7
New Best Solution Fitness: 49465
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.01111 
Mean sub-tour choices: 1.6 
Best Solution Fitness: 49465 
--------------------------------------------- 
