--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49617
New Best Solution Fitness: 49616
New Best Solution Fitness: 49582
New Best Solution Fitness: 49555
Generation: 3
New Best Solution Fitness: 49522
New Best Solution Fitness: 49470
Generation: 4
Generation: 5
New Best Solution Fitness: 49409
Generation: 6
New Best Solution Fitness: 49389
Generation: 7
New Best Solution Fitness: 49378
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.14444 
Mean sub-tour choices: 1.62222 
Best Solution Fitness: 49378 
--------------------------------------------- 
