--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49708
New Best Solution Fitness: 49669
New Best Solution Fitness: 49653
Generation: 3
New Best Solution Fitness: 49629
Generation: 4
New Best Solution Fitness: 49583
Generation: 5
New Best Solution Fitness: 49490
Generation: 6
New Best Solution Fitness: 49488
New Best Solution Fitness: 49452
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 49313
New Best Solution Fitness: 49269
Generation: 10
New Best Solution Fitness: 49202
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.688889 
Mean sub-tour choices: 1.13333 
Best Solution Fitness: 49202 
--------------------------------------------- 
