--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50277
New Best Solution Fitness: 50165
Generation: 3
New Best Solution Fitness: 49560
Generation: 4
New Best Solution Fitness: 49187
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.388889 
Mean sub-tour choices: 0.688889 
Best Solution Fitness: 49187 
--------------------------------------------- 
