--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50024
New Best Solution Fitness: 49966
New Best Solution Fitness: 49923
Generation: 3
New Best Solution Fitness: 49915
New Best Solution Fitness: 49889
New Best Solution Fitness: 49860
Generation: 4
New Best Solution Fitness: 49781
New Best Solution Fitness: 49769
Generation: 5
New Best Solution Fitness: 49740
Generation: 6
Generation: 7
New Best Solution Fitness: 49701
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.17778 
Mean sub-tour choices: 1.84444 
Best Solution Fitness: 49701 
--------------------------------------------- 
