--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49446
New Best Solution Fitness: 49435
Generation: 3
Generation: 4
New Best Solution Fitness: 49311
New Best Solution Fitness: 49287
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 49262
Generation: 9
New Best Solution Fitness: 49247
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.05556 
Mean sub-tour choices: 1.53333 
Best Solution Fitness: 49247 
--------------------------------------------- 
