--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50421
Generation: 3
New Best Solution Fitness: 50215
New Best Solution Fitness: 50205
Generation: 4
New Best Solution Fitness: 50198
New Best Solution Fitness: 50189
Generation: 5
New Best Solution Fitness: 50182
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 50146
Generation: 9
New Best Solution Fitness: 50084
New Best Solution Fitness: 50073
New Best Solution Fitness: 50062
New Best Solution Fitness: 50058
New Best Solution Fitness: 50009
Generation: 10
New Best Solution Fitness: 49990
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.13333 
Mean sub-tour choices: 1.97778 
Best Solution Fitness: 49990 
--------------------------------------------- 
