--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50015
New Best Solution Fitness: 49987
New Best Solution Fitness: 49982
New Best Solution Fitness: 49917
Generation: 3
New Best Solution Fitness: 49792
Generation: 4
New Best Solution Fitness: 49672
New Best Solution Fitness: 49627
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 49589
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.8 
Mean sub-tour choices: 1.35556 
Best Solution Fitness: 49589 
--------------------------------------------- 
