--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50027
Generation: 3
New Best Solution Fitness: 49823
New Best Solution Fitness: 49701
New Best Solution Fitness: 49696
Generation: 4
New Best Solution Fitness: 49686
New Best Solution Fitness: 49643
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 49589
Generation: 9
New Best Solution Fitness: 49549
Generation: 10
New Best Solution Fitness: 49539
New Best Solution Fitness: 49521
New Best Solution Fitness: 49518
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.722222 
Mean sub-tour choices: 1.17778 
Best Solution Fitness: 49518 
--------------------------------------------- 
