--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50282
New Best Solution Fitness: 50207
Generation: 3
New Best Solution Fitness: 50194
New Best Solution Fitness: 50184
Generation: 4
New Best Solution Fitness: 50013
New Best Solution Fitness: 49988
Generation: 5
New Best Solution Fitness: 49954
Generation: 6
New Best Solution Fitness: 49925
Generation: 7
New Best Solution Fitness: 49884
Generation: 8
New Best Solution Fitness: 49839
New Best Solution Fitness: 49823
New Best Solution Fitness: 49793
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.911111 
Mean sub-tour choices: 1.4 
Best Solution Fitness: 49793 
--------------------------------------------- 
