--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50528
New Best Solution Fitness: 50514
New Best Solution Fitness: 50460
New Best Solution Fitness: 50381
New Best Solution Fitness: 50350
Generation: 3
New Best Solution Fitness: 49727
New Best Solution Fitness: 49721
New Best Solution Fitness: 49678
New Best Solution Fitness: 49653
Generation: 4
New Best Solution Fitness: 49652
Generation: 5
New Best Solution Fitness: 49596
New Best Solution Fitness: 49588
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.18889 
Mean sub-tour choices: 1.78889 
Best Solution Fitness: 49588 
--------------------------------------------- 
