--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50037
New Best Solution Fitness: 50026
Generation: 3
New Best Solution Fitness: 50010
New Best Solution Fitness: 49999
New Best Solution Fitness: 49967
Generation: 4
New Best Solution Fitness: 49918
New Best Solution Fitness: 49873
New Best Solution Fitness: 49864
Generation: 5
New Best Solution Fitness: 49844
New Best Solution Fitness: 49790
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 49780
New Best Solution Fitness: 49737
Generation: 9
New Best Solution Fitness: 49563
New Best Solution Fitness: 49509
New Best Solution Fitness: 49479
Generation: 10
New Best Solution Fitness: 49467
New Best Solution Fitness: 49383
New Best Solution Fitness: 49372
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.866667 
Mean sub-tour choices: 1.41111 
Best Solution Fitness: 49372 
--------------------------------------------- 
