--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50465
New Best Solution Fitness: 50423
New Best Solution Fitness: 50388
Generation: 3
New Best Solution Fitness: 49943
Generation: 4
New Best Solution Fitness: 49922
New Best Solution Fitness: 49798
Generation: 5
New Best Solution Fitness: 49793
Generation: 6
New Best Solution Fitness: 49768
New Best Solution Fitness: 49760
New Best Solution Fitness: 49526
Generation: 7
New Best Solution Fitness: 49518
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.16667 
Mean sub-tour choices: 1.88889 
Best Solution Fitness: 49518 
--------------------------------------------- 
