--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49507
New Best Solution Fitness: 49476
Generation: 3
New Best Solution Fitness: 49434
Generation: 4
New Best Solution Fitness: 49387
New Best Solution Fitness: 49375
Generation: 5
New Best Solution Fitness: 49352
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 49210
New Best Solution Fitness: 49175
New Best Solution Fitness: 49174
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.433333 
Mean sub-tour choices: 0.777778 
Best Solution Fitness: 49174 
--------------------------------------------- 
