--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49578
New Best Solution Fitness: 49569
New Best Solution Fitness: 49453
New Best Solution Fitness: 49448
Generation: 3
New Best Solution Fitness: 49379
Generation: 4
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 49324
New Best Solution Fitness: 49308
Generation: 8
Generation: 9
New Best Solution Fitness: 49220
New Best Solution Fitness: 49159
Generation: 10
New Best Solution Fitness: 49118
New Best Solution Fitness: 49103
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.788889 
Mean sub-tour choices: 1.34444 
Best Solution Fitness: 49103 
--------------------------------------------- 
