--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50071
New Best Solution Fitness: 50016
New Best Solution Fitness: 50009
New Best Solution Fitness: 49994
Generation: 3
New Best Solution Fitness: 49975
New Best Solution Fitness: 49921
Generation: 4
New Best Solution Fitness: 49915
New Best Solution Fitness: 49894
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 49621
Generation: 8
New Best Solution Fitness: 49610
Generation: 9
New Best Solution Fitness: 49503
Generation: 10
New Best Solution Fitness: 49502
New Best Solution Fitness: 49477
New Best Solution Fitness: 49423
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.17778 
Mean sub-tour choices: 1.6 
Best Solution Fitness: 49423 
--------------------------------------------- 
