--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50253
New Best Solution Fitness: 50239
New Best Solution Fitness: 50213
Generation: 3
New Best Solution Fitness: 50037
New Best Solution Fitness: 49997
Generation: 4
New Best Solution Fitness: 49975
New Best Solution Fitness: 49960
New Best Solution Fitness: 49935
Generation: 5
New Best Solution Fitness: 49920
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.92222 
Mean sub-tour choices: 2.71111 
Best Solution Fitness: 49920 
--------------------------------------------- 
