--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50131
New Best Solution Fitness: 50105
New Best Solution Fitness: 50076
New Best Solution Fitness: 49917
New Best Solution Fitness: 49888
Generation: 3
New Best Solution Fitness: 49875
New Best Solution Fitness: 49864
New Best Solution Fitness: 49820
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 49763
New Best Solution Fitness: 49762
Generation: 7
New Best Solution Fitness: 49588
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.02222 
Mean sub-tour choices: 1.57778 
Best Solution Fitness: 49588 
--------------------------------------------- 
