--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49596
New Best Solution Fitness: 49476
Generation: 3
New Best Solution Fitness: 49381
Generation: 4
Generation: 5
New Best Solution Fitness: 49352
New Best Solution Fitness: 49302
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.555556 
Mean sub-tour choices: 0.877778 
Best Solution Fitness: 49302 
--------------------------------------------- 
