--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49835
New Best Solution Fitness: 49782
New Best Solution Fitness: 49730
Generation: 3
New Best Solution Fitness: 49674
New Best Solution Fitness: 49644
New Best Solution Fitness: 49642
Generation: 4
New Best Solution Fitness: 49593
New Best Solution Fitness: 49541
Generation: 5
Generation: 6
New Best Solution Fitness: 49529
Generation: 7
Generation: 8
New Best Solution Fitness: 49497
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.07778 
Mean sub-tour choices: 1.8 
Best Solution Fitness: 49497 
--------------------------------------------- 
