--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50167
New Best Solution Fitness: 50059
New Best Solution Fitness: 50041
Generation: 3
New Best Solution Fitness: 49965
New Best Solution Fitness: 49953
New Best Solution Fitness: 49881
Generation: 4
Generation: 5
New Best Solution Fitness: 49760
Generation: 6
New Best Solution Fitness: 49708
Generation: 7
New Best Solution Fitness: 49707
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 49681
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.422222 
Mean sub-tour choices: 0.733333 
Best Solution Fitness: 49681 
--------------------------------------------- 
