--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50044
New Best Solution Fitness: 50016
New Best Solution Fitness: 50003
Generation: 3
New Best Solution Fitness: 49650
New Best Solution Fitness: 49641
Generation: 4
New Best Solution Fitness: 49634
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 49621
Generation: 8
New Best Solution Fitness: 49554
New Best Solution Fitness: 49539
Generation: 9
Generation: 10
New Best Solution Fitness: 49512
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.877778 
Mean sub-tour choices: 1.27778 
Best Solution Fitness: 49512 
--------------------------------------------- 
