--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49594
New Best Solution Fitness: 49537
Generation: 3
New Best Solution Fitness: 49509
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 49495
Generation: 7
Generation: 8
New Best Solution Fitness: 49477
New Best Solution Fitness: 49418
Generation: 9
New Best Solution Fitness: 49395
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.588889 
Mean sub-tour choices: 1.04444 
Best Solution Fitness: 49395 
--------------------------------------------- 
