--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49794
New Best Solution Fitness: 49737
New Best Solution Fitness: 49712
New Best Solution Fitness: 49701
Generation: 3
New Best Solution Fitness: 49690
New Best Solution Fitness: 49645
Generation: 4
New Best Solution Fitness: 49642
Generation: 5
New Best Solution Fitness: 49632
New Best Solution Fitness: 49613
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 49500
New Best Solution Fitness: 49495
New Best Solution Fitness: 49494
Generation: 9
Generation: 10
New Best Solution Fitness: 49463
New Best Solution Fitness: 49457
New Best Solution Fitness: 49456
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.73333 
Mean sub-tour choices: 2.36667 
Best Solution Fitness: 49456 
--------------------------------------------- 
