--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50033
New Best Solution Fitness: 50028
New Best Solution Fitness: 50022
Generation: 3
New Best Solution Fitness: 49796
Generation: 4
New Best Solution Fitness: 49693
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 49549
New Best Solution Fitness: 49541
New Best Solution Fitness: 49531
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.811111 
Mean sub-tour choices: 1.41111 
Best Solution Fitness: 49531 
--------------------------------------------- 
