--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49568
New Best Solution Fitness: 49542
New Best Solution Fitness: 49530
Generation: 3
New Best Solution Fitness: 49483
New Best Solution Fitness: 49477
New Best Solution Fitness: 49462
Generation: 4
New Best Solution Fitness: 49447
New Best Solution Fitness: 49426
New Best Solution Fitness: 49393
Generation: 5
New Best Solution Fitness: 49378
New Best Solution Fitness: 49357
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.12222 
Mean sub-tour choices: 1.78889 
Best Solution Fitness: 49357 
--------------------------------------------- 
