--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49822
Generation: 3
New Best Solution Fitness: 49821
Generation: 4
New Best Solution Fitness: 49809
New Best Solution Fitness: 49808
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 49768
Generation: 8
Generation: 9
New Best Solution Fitness: 49716
Generation: 10
New Best Solution Fitness: 49695
New Best Solution Fitness: 49621
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.666667 
Mean sub-tour choices: 1.3 
Best Solution Fitness: 49621 
--------------------------------------------- 
