--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49702
New Best Solution Fitness: 49685
Generation: 3
New Best Solution Fitness: 49663
Generation: 4
New Best Solution Fitness: 49610
New Best Solution Fitness: 49558
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 49542
Generation: 10
New Best Solution Fitness: 49497
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.4 
Mean sub-tour choices: 0.722222 
Best Solution Fitness: 49497 
--------------------------------------------- 
