--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49681
Generation: 3
New Best Solution Fitness: 49624
New Best Solution Fitness: 49615
Generation: 4
Generation: 5
New Best Solution Fitness: 49606
New Best Solution Fitness: 49554
Generation: 6
New Best Solution Fitness: 49510
New Best Solution Fitness: 49464
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 49461
New Best Solution Fitness: 49451
New Best Solution Fitness: 49443
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.377778 
Mean sub-tour choices: 0.633333 
Best Solution Fitness: 49443 
--------------------------------------------- 
