--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50044
New Best Solution Fitness: 50043
New Best Solution Fitness: 50020
Generation: 3
New Best Solution Fitness: 49967
New Best Solution Fitness: 49816
Generation: 4
New Best Solution Fitness: 49794
Generation: 5
Generation: 6
New Best Solution Fitness: 49777
Generation: 7
Generation: 8
New Best Solution Fitness: 49564
Generation: 9
New Best Solution Fitness: 49546
Generation: 10
New Best Solution Fitness: 49516
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.8 
Mean sub-tour choices: 1.41111 
Best Solution Fitness: 49516 
--------------------------------------------- 
