--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49694
New Best Solution Fitness: 49654
Generation: 3
New Best Solution Fitness: 49637
Generation: 4
New Best Solution Fitness: 49565
New Best Solution Fitness: 49545
Generation: 5
New Best Solution Fitness: 49520
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 49498
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.57778 
Mean sub-tour choices: 2.47778 
Best Solution Fitness: 49498 
--------------------------------------------- 
