--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49962
New Best Solution Fitness: 49861
Generation: 3
New Best Solution Fitness: 49854
Generation: 4
Generation: 5
New Best Solution Fitness: 49848
Generation: 6
New Best Solution Fitness: 49726
Generation: 7
Generation: 8
New Best Solution Fitness: 49660
Generation: 9
Generation: 10
New Best Solution Fitness: 49580
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.666667 
Mean sub-tour choices: 1.1 
Best Solution Fitness: 49580 
--------------------------------------------- 
