--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50248
New Best Solution Fitness: 50206
New Best Solution Fitness: 50201
New Best Solution Fitness: 49952
Generation: 3
New Best Solution Fitness: 49737
New Best Solution Fitness: 49730
New Best Solution Fitness: 49692
New Best Solution Fitness: 49651
Generation: 4
New Best Solution Fitness: 49639
New Best Solution Fitness: 49616
Generation: 5
New Best Solution Fitness: 49481
Generation: 6
New Best Solution Fitness: 49471
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.28889 
Mean sub-tour choices: 1.91111 
Best Solution Fitness: 49471 
--------------------------------------------- 
