--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50487
New Best Solution Fitness: 50474
New Best Solution Fitness: 50460
Generation: 3
New Best Solution Fitness: 50408
Generation: 4
New Best Solution Fitness: 50176
New Best Solution Fitness: 50019
Generation: 5
New Best Solution Fitness: 49941
Generation: 6
New Best Solution Fitness: 49847
New Best Solution Fitness: 49838
Generation: 7
Generation: 8
New Best Solution Fitness: 49741
New Best Solution Fitness: 49731
New Best Solution Fitness: 49690
Generation: 9
New Best Solution Fitness: 49677
New Best Solution Fitness: 49661
Generation: 10
New Best Solution Fitness: 49640
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.7 
Mean sub-tour choices: 1.26667 
Best Solution Fitness: 49640 
--------------------------------------------- 
