--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50140
New Best Solution Fitness: 50055
Generation: 3
New Best Solution Fitness: 49995
New Best Solution Fitness: 49930
Generation: 4
New Best Solution Fitness: 49709
New Best Solution Fitness: 49700
New Best Solution Fitness: 49687
Generation: 5
New Best Solution Fitness: 49656
New Best Solution Fitness: 49619
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 49594
Generation: 9
New Best Solution Fitness: 49570
Generation: 10
New Best Solution Fitness: 49544
New Best Solution Fitness: 49513
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.888889 
Mean sub-tour choices: 1.46667 
Best Solution Fitness: 49513 
--------------------------------------------- 
