--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49873
New Best Solution Fitness: 49872
New Best Solution Fitness: 49865
Generation: 3
New Best Solution Fitness: 49831
New Best Solution Fitness: 49821
Generation: 4
New Best Solution Fitness: 49766
New Best Solution Fitness: 49749
Generation: 5
New Best Solution Fitness: 49697
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.15556 
Mean sub-tour choices: 2 
Best Solution Fitness: 49697 
--------------------------------------------- 
