--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49911
New Best Solution Fitness: 49837
New Best Solution Fitness: 49813
Generation: 3
New Best Solution Fitness: 49803
Generation: 4
New Best Solution Fitness: 49763
New Best Solution Fitness: 49730
Generation: 5
Generation: 6
New Best Solution Fitness: 49704
Generation: 7
New Best Solution Fitness: 49668
Generation: 8
New Best Solution Fitness: 49635
Generation: 9
New Best Solution Fitness: 49596
Generation: 10
New Best Solution Fitness: 49567
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.54444 
Mean sub-tour choices: 2.12222 
Best Solution Fitness: 49567 
--------------------------------------------- 
