--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50247
New Best Solution Fitness: 50144
Generation: 3
New Best Solution Fitness: 50101
New Best Solution Fitness: 50061
New Best Solution Fitness: 50059
New Best Solution Fitness: 49998
Generation: 4
New Best Solution Fitness: 49958
New Best Solution Fitness: 49922
Generation: 5
New Best Solution Fitness: 49795
New Best Solution Fitness: 49785
Generation: 6
Generation: 7
New Best Solution Fitness: 49776
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 49770
New Best Solution Fitness: 49719
New Best Solution Fitness: 49714
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.966667 
Mean sub-tour choices: 1.47778 
Best Solution Fitness: 49714 
--------------------------------------------- 
