--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49628
New Best Solution Fitness: 49627
New Best Solution Fitness: 49624
New Best Solution Fitness: 49561
Generation: 3
New Best Solution Fitness: 49549
New Best Solution Fitness: 49545
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 49526
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.644444 
Mean sub-tour choices: 0.988889 
Best Solution Fitness: 49526 
--------------------------------------------- 
