--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49940
New Best Solution Fitness: 49883
New Best Solution Fitness: 49828
Generation: 3
New Best Solution Fitness: 49680
New Best Solution Fitness: 49549
Generation: 4
New Best Solution Fitness: 49514
Generation: 5
New Best Solution Fitness: 49489
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 49450
Generation: 9
Generation: 10
New Best Solution Fitness: 49429
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.833333 
Mean sub-tour choices: 1.51111 
Best Solution Fitness: 49429 
--------------------------------------------- 
