--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49574
New Best Solution Fitness: 49438
Generation: 3
New Best Solution Fitness: 49414
New Best Solution Fitness: 49393
Generation: 4
New Best Solution Fitness: 49381
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 49329
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.16667 
Mean sub-tour choices: 1.87778 
Best Solution Fitness: 49329 
--------------------------------------------- 
