--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49576
New Best Solution Fitness: 49567
New Best Solution Fitness: 49527
Generation: 3
New Best Solution Fitness: 49499
New Best Solution Fitness: 49490
Generation: 4
New Best Solution Fitness: 49446
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 49403
Generation: 9
New Best Solution Fitness: 49381
New Best Solution Fitness: 49338
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.544444 
Mean sub-tour choices: 0.966667 
Best Solution Fitness: 49338 
--------------------------------------------- 
