--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49905
New Best Solution Fitness: 49778
Generation: 3
New Best Solution Fitness: 49636
Generation: 4
New Best Solution Fitness: 49594
Generation: 5
New Best Solution Fitness: 49547
New Best Solution Fitness: 49518
Generation: 6
New Best Solution Fitness: 49502
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.922222 
Mean sub-tour choices: 1.65556 
Best Solution Fitness: 49502 
--------------------------------------------- 
