--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49842
New Best Solution Fitness: 49836
New Best Solution Fitness: 49830
New Best Solution Fitness: 49785
New Best Solution Fitness: 49774
Generation: 3
New Best Solution Fitness: 49711
New Best Solution Fitness: 49643
New Best Solution Fitness: 49605
Generation: 4
New Best Solution Fitness: 49577
New Best Solution Fitness: 49495
Generation: 5
New Best Solution Fitness: 49431
New Best Solution Fitness: 49426
Generation: 6
New Best Solution Fitness: 49414
Generation: 7
Generation: 8
New Best Solution Fitness: 49349
New Best Solution Fitness: 49344
Generation: 9
New Best Solution Fitness: 49341
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.26667 
Mean sub-tour choices: 1.83333 
Best Solution Fitness: 49341 
--------------------------------------------- 
