--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50049
New Best Solution Fitness: 50045
New Best Solution Fitness: 49993
Generation: 3
New Best Solution Fitness: 49752
Generation: 4
New Best Solution Fitness: 49751
New Best Solution Fitness: 49750
New Best Solution Fitness: 49730
Generation: 5
New Best Solution Fitness: 49662
Generation: 6
New Best Solution Fitness: 49609
Generation: 7
New Best Solution Fitness: 49608
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.11111 
Mean sub-tour choices: 1.71111 
Best Solution Fitness: 49608 
--------------------------------------------- 
