--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49633
New Best Solution Fitness: 49609
Generation: 3
New Best Solution Fitness: 49574
Generation: 4
New Best Solution Fitness: 49553
Generation: 5
New Best Solution Fitness: 49535
Generation: 6
New Best Solution Fitness: 49534
Generation: 7
New Best Solution Fitness: 49476
New Best Solution Fitness: 49475
Generation: 8
Generation: 9
New Best Solution Fitness: 49451
New Best Solution Fitness: 49410
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.666667 
Mean sub-tour choices: 1.2 
Best Solution Fitness: 49410 
--------------------------------------------- 
