--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50112
New Best Solution Fitness: 50062
New Best Solution Fitness: 50035
New Best Solution Fitness: 50031
New Best Solution Fitness: 49962
Generation: 3
New Best Solution Fitness: 49933
New Best Solution Fitness: 49871
Generation: 4
New Best Solution Fitness: 49852
Generation: 5
New Best Solution Fitness: 49845
Generation: 6
New Best Solution Fitness: 49828
Generation: 7
New Best Solution Fitness: 49811
Generation: 8
New Best Solution Fitness: 49631
New Best Solution Fitness: 49614
Generation: 9
New Best Solution Fitness: 49555
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.711111 
Mean sub-tour choices: 1.23333 
Best Solution Fitness: 49555 
--------------------------------------------- 
