--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49857
Generation: 3
New Best Solution Fitness: 49751
New Best Solution Fitness: 49743
New Best Solution Fitness: 49742
Generation: 4
New Best Solution Fitness: 49734
Generation: 5
New Best Solution Fitness: 49724
New Best Solution Fitness: 49695
Generation: 6
New Best Solution Fitness: 49430
New Best Solution Fitness: 49365
Generation: 7
Generation: 8
New Best Solution Fitness: 49352
New Best Solution Fitness: 49341
Generation: 9
New Best Solution Fitness: 49254
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.566667 
Mean sub-tour choices: 1 
Best Solution Fitness: 49254 
--------------------------------------------- 
