--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50643
New Best Solution Fitness: 50585
Generation: 3
New Best Solution Fitness: 50368
New Best Solution Fitness: 50232
Generation: 4
New Best Solution Fitness: 50209
Generation: 5
New Best Solution Fitness: 50159
New Best Solution Fitness: 50157
Generation: 6
New Best Solution Fitness: 50107
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 50106
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.2 
Mean sub-tour choices: 1.96667 
Best Solution Fitness: 50106 
--------------------------------------------- 
