--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49904
New Best Solution Fitness: 49791
New Best Solution Fitness: 49784
Generation: 3
New Best Solution Fitness: 49745
New Best Solution Fitness: 49737
New Best Solution Fitness: 49694
Generation: 4
Generation: 5
New Best Solution Fitness: 49482
Generation: 6
New Best Solution Fitness: 49472
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.477778 
Mean sub-tour choices: 0.744444 
Best Solution Fitness: 49472 
--------------------------------------------- 
