--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50289
New Best Solution Fitness: 50206
New Best Solution Fitness: 50155
Generation: 3
New Best Solution Fitness: 50133
Generation: 4
New Best Solution Fitness: 49873
New Best Solution Fitness: 49787
Generation: 5
Generation: 6
Generation: 7
New Best Solution Fitness: 49757
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 49749
New Best Solution Fitness: 49727
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.07778 
Mean sub-tour choices: 1.77778 
Best Solution Fitness: 49727 
--------------------------------------------- 
