--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50302
New Best Solution Fitness: 50291
New Best Solution Fitness: 50253
New Best Solution Fitness: 50244
New Best Solution Fitness: 50237
Generation: 3
New Best Solution Fitness: 50218
New Best Solution Fitness: 50196
Generation: 4
New Best Solution Fitness: 49749
New Best Solution Fitness: 49727
Generation: 5
New Best Solution Fitness: 49659
Generation: 6
New Best Solution Fitness: 49652
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 49650
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.26667 
Mean sub-tour choices: 1.94444 
Best Solution Fitness: 49650 
--------------------------------------------- 
