--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50152
New Best Solution Fitness: 50075
New Best Solution Fitness: 50037
Generation: 3
New Best Solution Fitness: 49806
New Best Solution Fitness: 49797
New Best Solution Fitness: 49781
Generation: 4
New Best Solution Fitness: 49722
New Best Solution Fitness: 49697
Generation: 5
New Best Solution Fitness: 49633
New Best Solution Fitness: 49608
New Best Solution Fitness: 49490
Generation: 6
New Best Solution Fitness: 49465
Generation: 7
New Best Solution Fitness: 49461
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.12222 
Mean sub-tour choices: 1.74444 
Best Solution Fitness: 49461 
--------------------------------------------- 
