--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49721
New Best Solution Fitness: 49662
New Best Solution Fitness: 49556
Generation: 3
New Best Solution Fitness: 49546
Generation: 4
New Best Solution Fitness: 49501
Generation: 5
Generation: 6
New Best Solution Fitness: 49213
New Best Solution Fitness: 49196
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.822222 
Mean sub-tour choices: 1.21111 
Best Solution Fitness: 49196 
--------------------------------------------- 
