--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49913
New Best Solution Fitness: 49848
Generation: 3
New Best Solution Fitness: 49709
New Best Solution Fitness: 49625
Generation: 4
New Best Solution Fitness: 49483
Generation: 5
New Best Solution Fitness: 49472
New Best Solution Fitness: 49461
New Best Solution Fitness: 49438
Generation: 6
New Best Solution Fitness: 49405
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 49382
Generation: 10
New Best Solution Fitness: 49376
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.466667 
Mean sub-tour choices: 0.811111 
Best Solution Fitness: 49376 
--------------------------------------------- 
