--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49817
New Best Solution Fitness: 49792
New Best Solution Fitness: 49782
Generation: 3
New Best Solution Fitness: 49498
New Best Solution Fitness: 49463
Generation: 4
New Best Solution Fitness: 49458
Generation: 5
New Best Solution Fitness: 49456
Generation: 6
New Best Solution Fitness: 49413
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.35556 
Mean sub-tour choices: 2.02222 
Best Solution Fitness: 49413 
--------------------------------------------- 
