--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50565
Generation: 3
New Best Solution Fitness: 49571
New Best Solution Fitness: 49543
New Best Solution Fitness: 49539
Generation: 4
New Best Solution Fitness: 49494
Generation: 5
Generation: 6
New Best Solution Fitness: 49493
Generation: 7
New Best Solution Fitness: 49459
New Best Solution Fitness: 49423
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.488889 
Mean sub-tour choices: 0.8 
Best Solution Fitness: 49423 
--------------------------------------------- 
