--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49981
New Best Solution Fitness: 49977
Generation: 3
New Best Solution Fitness: 49965
Generation: 4
New Best Solution Fitness: 49921
New Best Solution Fitness: 49897
New Best Solution Fitness: 49806
Generation: 5
New Best Solution Fitness: 49691
New Best Solution Fitness: 49646
New Best Solution Fitness: 49635
New Best Solution Fitness: 49536
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 49528
Generation: 10
New Best Solution Fitness: 49465
New Best Solution Fitness: 49348
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.688889 
Mean sub-tour choices: 1.1 
Best Solution Fitness: 49348 
--------------------------------------------- 
