--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50044
Generation: 3
New Best Solution Fitness: 49975
New Best Solution Fitness: 49941
Generation: 4
New Best Solution Fitness: 49921
New Best Solution Fitness: 49837
New Best Solution Fitness: 49803
Generation: 5
New Best Solution Fitness: 49770
New Best Solution Fitness: 49736
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 49730
Generation: 10
New Best Solution Fitness: 49729
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.911111 
Mean sub-tour choices: 1.52222 
Best Solution Fitness: 49729 
--------------------------------------------- 
