--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49912
New Best Solution Fitness: 49800
Generation: 3
New Best Solution Fitness: 49784
Generation: 4
New Best Solution Fitness: 49681
New Best Solution Fitness: 49596
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.533333 
Mean sub-tour choices: 0.988889 
Best Solution Fitness: 49596 
--------------------------------------------- 
