--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49799
New Best Solution Fitness: 49784
New Best Solution Fitness: 49695
Generation: 3
New Best Solution Fitness: 49678
Generation: 4
New Best Solution Fitness: 49659
Generation: 5
New Best Solution Fitness: 49650
New Best Solution Fitness: 49647
New Best Solution Fitness: 49625
Generation: 6
New Best Solution Fitness: 49613
New Best Solution Fitness: 49610
Generation: 7
New Best Solution Fitness: 49563
New Best Solution Fitness: 49560
Generation: 8
New Best Solution Fitness: 49526
New Best Solution Fitness: 49525
New Best Solution Fitness: 49515
New Best Solution Fitness: 49503
Generation: 9
New Best Solution Fitness: 49487
New Best Solution Fitness: 49452
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.922222 
Mean sub-tour choices: 1.45556 
Best Solution Fitness: 49452 
--------------------------------------------- 
