--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49688
New Best Solution Fitness: 49648
New Best Solution Fitness: 49590
Generation: 3
New Best Solution Fitness: 49558
New Best Solution Fitness: 49545
Generation: 4
New Best Solution Fitness: 49466
Generation: 5
New Best Solution Fitness: 49424
Generation: 6
New Best Solution Fitness: 49411
New Best Solution Fitness: 49377
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.822222 
Mean sub-tour choices: 2 
Best Solution Fitness: 49377 
--------------------------------------------- 
