--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50325
New Best Solution Fitness: 50324
New Best Solution Fitness: 50263
New Best Solution Fitness: 50238
Generation: 3
New Best Solution Fitness: 50196
Generation: 4
New Best Solution Fitness: 49954
New Best Solution Fitness: 49939
Generation: 5
New Best Solution Fitness: 49887
New Best Solution Fitness: 49886
Generation: 6
New Best Solution Fitness: 49759
New Best Solution Fitness: 49745
New Best Solution Fitness: 49740
Generation: 7
New Best Solution Fitness: 49701
Generation: 8
Generation: 9
New Best Solution Fitness: 49687
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.766667 
Mean sub-tour choices: 1.34444 
Best Solution Fitness: 49687 
--------------------------------------------- 
