--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49454
New Best Solution Fitness: 49449
Generation: 3
New Best Solution Fitness: 49382
New Best Solution Fitness: 49377
Generation: 4
New Best Solution Fitness: 49354
Generation: 5
New Best Solution Fitness: 49289
New Best Solution Fitness: 49283
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 49234
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.855556 
Mean sub-tour choices: 1.27778 
Best Solution Fitness: 49234 
--------------------------------------------- 
