--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50041
New Best Solution Fitness: 49999
New Best Solution Fitness: 49903
Generation: 3
New Best Solution Fitness: 49758
New Best Solution Fitness: 49716
New Best Solution Fitness: 49705
New Best Solution Fitness: 49633
Generation: 4
New Best Solution Fitness: 49591
New Best Solution Fitness: 49496
Generation: 5
New Best Solution Fitness: 49485
New Best Solution Fitness: 49454
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 49389
New Best Solution Fitness: 49327
New Best Solution Fitness: 49299
New Best Solution Fitness: 49227
Generation: 10
New Best Solution Fitness: 49212
New Best Solution Fitness: 49171
New Best Solution Fitness: 49143
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.966667 
Mean sub-tour choices: 1.53333 
Best Solution Fitness: 49143 
--------------------------------------------- 
