--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50058
New Best Solution Fitness: 50025
New Best Solution Fitness: 50003
Generation: 3
New Best Solution Fitness: 49975
New Best Solution Fitness: 49966
Generation: 4
New Best Solution Fitness: 49946
New Best Solution Fitness: 49945
Generation: 5
New Best Solution Fitness: 49904
New Best Solution Fitness: 49895
New Best Solution Fitness: 49862
Generation: 6
New Best Solution Fitness: 49817
New Best Solution Fitness: 49766
Generation: 7
New Best Solution Fitness: 49694
Generation: 8
New Best Solution Fitness: 49672
New Best Solution Fitness: 49657
Generation: 9
New Best Solution Fitness: 49634
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.688889 
Mean sub-tour choices: 1.13333 
Best Solution Fitness: 49634 
--------------------------------------------- 
