--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49506
New Best Solution Fitness: 49452
Generation: 3
New Best Solution Fitness: 49413
New Best Solution Fitness: 49398
Generation: 4
New Best Solution Fitness: 49310
Generation: 5
New Best Solution Fitness: 49301
Generation: 6
New Best Solution Fitness: 49280
Generation: 7
New Best Solution Fitness: 49279
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.05556 
Mean sub-tour choices: 1.54444 
Best Solution Fitness: 49279 
--------------------------------------------- 
