--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49656
New Best Solution Fitness: 49622
New Best Solution Fitness: 49585
Generation: 3
New Best Solution Fitness: 49513
New Best Solution Fitness: 49489
New Best Solution Fitness: 49479
Generation: 4
New Best Solution Fitness: 49442
New Best Solution Fitness: 49418
Generation: 5
New Best Solution Fitness: 49414
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 49413
New Best Solution Fitness: 49412
New Best Solution Fitness: 49378
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.4 
Mean sub-tour choices: 2.11111 
Best Solution Fitness: 49378 
--------------------------------------------- 
