--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49856
New Best Solution Fitness: 49816
New Best Solution Fitness: 49740
Generation: 3
Generation: 4
New Best Solution Fitness: 49672
Generation: 5
New Best Solution Fitness: 49496
Generation: 6
New Best Solution Fitness: 49488
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 49467
Generation: 10
New Best Solution Fitness: 49435
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.566667 
Mean sub-tour choices: 0.977778 
Best Solution Fitness: 49435 
--------------------------------------------- 
