--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49604
New Best Solution Fitness: 49590
Generation: 3
New Best Solution Fitness: 49553
New Best Solution Fitness: 49527
Generation: 4
New Best Solution Fitness: 49515
Generation: 5
Generation: 6
New Best Solution Fitness: 49501
New Best Solution Fitness: 49497
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.766667 
Mean sub-tour choices: 1.3 
Best Solution Fitness: 49497 
--------------------------------------------- 
