--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49888
New Best Solution Fitness: 49829
New Best Solution Fitness: 49749
Generation: 3
New Best Solution Fitness: 49666
New Best Solution Fitness: 49589
New Best Solution Fitness: 49572
Generation: 4
New Best Solution Fitness: 49495
Generation: 5
Generation: 6
New Best Solution Fitness: 49455
Generation: 7
New Best Solution Fitness: 49454
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.833333 
Mean sub-tour choices: 1.31111 
Best Solution Fitness: 49454 
--------------------------------------------- 
