--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50384
New Best Solution Fitness: 50332
Generation: 3
New Best Solution Fitness: 49860
Generation: 4
Generation: 5
Generation: 6
New Best Solution Fitness: 49794
Generation: 7
New Best Solution Fitness: 49789
Generation: 8
Generation: 9
New Best Solution Fitness: 49716
Generation: 10
New Best Solution Fitness: 49712
New Best Solution Fitness: 49634
New Best Solution Fitness: 49582
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.444444 
Mean sub-tour choices: 0.766667 
Best Solution Fitness: 49582 
--------------------------------------------- 
