--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49604
New Best Solution Fitness: 49593
New Best Solution Fitness: 49587
Generation: 3
New Best Solution Fitness: 49548
New Best Solution Fitness: 49493
Generation: 4
New Best Solution Fitness: 49451
Generation: 5
Generation: 6
New Best Solution Fitness: 49376
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.21111 
Mean sub-tour choices: 1.95556 
Best Solution Fitness: 49376 
--------------------------------------------- 
