--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49925
New Best Solution Fitness: 49903
New Best Solution Fitness: 49869
Generation: 3
New Best Solution Fitness: 49838
Generation: 4
New Best Solution Fitness: 49815
Generation: 5
New Best Solution Fitness: 49769
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 49733
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.388889 
Mean sub-tour choices: 0.766667 
Best Solution Fitness: 49733 
--------------------------------------------- 
