--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49880
New Best Solution Fitness: 49853
Generation: 3
Generation: 4
New Best Solution Fitness: 49826
Generation: 5
New Best Solution Fitness: 49786
New Best Solution Fitness: 49704
New Best Solution Fitness: 49638
Generation: 6
Generation: 7
New Best Solution Fitness: 49634
Generation: 8
New Best Solution Fitness: 49600
New Best Solution Fitness: 49557
New Best Solution Fitness: 49536
New Best Solution Fitness: 49518
Generation: 9
New Best Solution Fitness: 49499
New Best Solution Fitness: 49424
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.655556 
Mean sub-tour choices: 1.38889 
Best Solution Fitness: 49424 
--------------------------------------------- 
