--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49522
New Best Solution Fitness: 49479
Generation: 3
New Best Solution Fitness: 49464
Generation: 4
New Best Solution Fitness: 49460
New Best Solution Fitness: 49445
Generation: 5
Generation: 6
New Best Solution Fitness: 49434
Generation: 7
New Best Solution Fitness: 49429
New Best Solution Fitness: 49385
Generation: 8
Generation: 9
New Best Solution Fitness: 49349
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.06667 
Mean sub-tour choices: 1.85556 
Best Solution Fitness: 49349 
--------------------------------------------- 
