--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50110
New Best Solution Fitness: 50057
New Best Solution Fitness: 50012
Generation: 3
New Best Solution Fitness: 49630
New Best Solution Fitness: 49615
Generation: 4
New Best Solution Fitness: 49586
Generation: 5
New Best Solution Fitness: 49578
Generation: 6
Generation: 7
New Best Solution Fitness: 49539
Generation: 8
New Best Solution Fitness: 49515
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.855556 
Mean sub-tour choices: 1.32222 
Best Solution Fitness: 49515 
--------------------------------------------- 
