--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50308
New Best Solution Fitness: 50297
New Best Solution Fitness: 50288
Generation: 3
New Best Solution Fitness: 50253
New Best Solution Fitness: 50242
New Best Solution Fitness: 50196
Generation: 4
New Best Solution Fitness: 50159
Generation: 5
Generation: 6
New Best Solution Fitness: 50078
Generation: 7
Generation: 8
New Best Solution Fitness: 49548
New Best Solution Fitness: 49477
New Best Solution Fitness: 49467
Generation: 9
New Best Solution Fitness: 49442
New Best Solution Fitness: 49441
Generation: 10
New Best Solution Fitness: 49406
New Best Solution Fitness: 49330
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.07778 
Mean sub-tour choices: 1.58889 
Best Solution Fitness: 49330 
--------------------------------------------- 
