--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50262
New Best Solution Fitness: 50230
New Best Solution Fitness: 50201
Generation: 3
New Best Solution Fitness: 50060
New Best Solution Fitness: 50042
New Best Solution Fitness: 50009
Generation: 4
New Best Solution Fitness: 50008
New Best Solution Fitness: 49904
Generation: 5
New Best Solution Fitness: 49902
Generation: 6
New Best Solution Fitness: 49901
New Best Solution Fitness: 49900
New Best Solution Fitness: 49881
Generation: 7
New Best Solution Fitness: 49846
New Best Solution Fitness: 49839
New Best Solution Fitness: 49778
Generation: 8
New Best Solution Fitness: 49530
Generation: 9
New Best Solution Fitness: 49504
Generation: 10
New Best Solution Fitness: 49469
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.05556 
Mean sub-tour choices: 1.63333 
Best Solution Fitness: 49469 
--------------------------------------------- 
