--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 49619
New Best Solution Fitness: 49597
Generation: 3
New Best Solution Fitness: 49551
Generation: 4
New Best Solution Fitness: 49529
Generation: 5
New Best Solution Fitness: 49489
New Best Solution Fitness: 49440
Generation: 6
Generation: 7
New Best Solution Fitness: 49399
Generation: 8
New Best Solution Fitness: 49358
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.766667 
Mean sub-tour choices: 1.23333 
Best Solution Fitness: 49358 
--------------------------------------------- 
