--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\d657.tsp
Algorithm: Hybrid with Chained Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 50819
Generation: 3
New Best Solution Fitness: 50374
New Best Solution Fitness: 50085
Generation: 4
New Best Solution Fitness: 50080
New Best Solution Fitness: 49946
Generation: 5
New Best Solution Fitness: 49923
New Best Solution Fitness: 49907
Generation: 6
New Best Solution Fitness: 49906
Generation: 7
New Best Solution Fitness: 49807
Generation: 8
New Best Solution Fitness: 49793
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 0.9 
Mean sub-tour choices: 1.48889 
Best Solution Fitness: 49793 
--------------------------------------------- 
