--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\bier127.tsp
Algorithm: Black Box Generational 
Population: 10
Mutation probability: 1
Crossover probability: 0.00787402
---------------
Job Complete 
Iterations: 161290
Best Solution Fitness: 127137
--------------------------------------------- 
