--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 591890
New Best Solution Fitness: 591443
Generation: 3
New Best Solution Fitness: 583392
New Best Solution Fitness: 583298
New Best Solution Fitness: 583172
New Best Solution Fitness: 583094
New Best Solution Fitness: 583078
New Best Solution Fitness: 583067
Generation: 4
New Best Solution Fitness: 580210
New Best Solution Fitness: 580129
Generation: 5
Generation: 6
Generation: 7
Generation: 8
New Best Solution Fitness: 580095
Generation: 9
New Best Solution Fitness: 579999
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.11111 
Mean sub-tour choices: 2.67778 
Best Solution Fitness: 579999 
--------------------------------------------- 
