--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 589371
New Best Solution Fitness: 589144
New Best Solution Fitness: 588521
Generation: 3
New Best Solution Fitness: 584827
New Best Solution Fitness: 584760
New Best Solution Fitness: 584648
New Best Solution Fitness: 584564
New Best Solution Fitness: 584127
Generation: 4
New Best Solution Fitness: 582693
New Best Solution Fitness: 582467
New Best Solution Fitness: 582378
New Best Solution Fitness: 582377
New Best Solution Fitness: 582277
Generation: 5
New Best Solution Fitness: 582244
New Best Solution Fitness: 582103
Generation: 6
New Best Solution Fitness: 581992
Generation: 7
New Best Solution Fitness: 581975
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 6.03333 
Mean sub-tour choices: 6.93333 
Best Solution Fitness: 581975 
--------------------------------------------- 
