--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 585491
New Best Solution Fitness: 584961
New Best Solution Fitness: 584746
Generation: 3
New Best Solution Fitness: 583438
New Best Solution Fitness: 583363
New Best Solution Fitness: 582504
Generation: 4
New Best Solution Fitness: 582409
New Best Solution Fitness: 582391
New Best Solution Fitness: 582302
Generation: 5
New Best Solution Fitness: 582251
Generation: 6
New Best Solution Fitness: 580795
New Best Solution Fitness: 580739
New Best Solution Fitness: 580646
New Best Solution Fitness: 580205
Generation: 7
New Best Solution Fitness: 578964
New Best Solution Fitness: 578957
New Best Solution Fitness: 578922
Generation: 8
New Best Solution Fitness: 578574
New Best Solution Fitness: 578567
Generation: 9
New Best Solution Fitness: 578545
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.23333 
Mean sub-tour choices: 5.1 
Best Solution Fitness: 578545 
--------------------------------------------- 
