--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 591315
New Best Solution Fitness: 591028
New Best Solution Fitness: 591009
New Best Solution Fitness: 590883
New Best Solution Fitness: 590873
Generation: 3
New Best Solution Fitness: 582462
New Best Solution Fitness: 582379
New Best Solution Fitness: 582325
New Best Solution Fitness: 582304
New Best Solution Fitness: 582260
Generation: 4
New Best Solution Fitness: 581729
New Best Solution Fitness: 581592
Generation: 5
Generation: 6
New Best Solution Fitness: 581459
Generation: 7
New Best Solution Fitness: 581294
New Best Solution Fitness: 581015
Generation: 8
New Best Solution Fitness: 579377
New Best Solution Fitness: 579336
Generation: 9
New Best Solution Fitness: 579315
Generation: 10
New Best Solution Fitness: 579235
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.7 
Mean sub-tour choices: 3.28889 
Best Solution Fitness: 579235 
--------------------------------------------- 
