--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 598402
New Best Solution Fitness: 597660
New Best Solution Fitness: 597578
Generation: 3
New Best Solution Fitness: 587231
New Best Solution Fitness: 587189
New Best Solution Fitness: 587141
Generation: 4
New Best Solution Fitness: 585370
New Best Solution Fitness: 585368
New Best Solution Fitness: 585348
Generation: 5
New Best Solution Fitness: 582699
Generation: 6
New Best Solution Fitness: 582681
Generation: 7
New Best Solution Fitness: 582612
Generation: 8
New Best Solution Fitness: 581877
New Best Solution Fitness: 581693
Generation: 9
New Best Solution Fitness: 581113
Generation: 10
New Best Solution Fitness: 580770
New Best Solution Fitness: 580349
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.22222 
Mean sub-tour choices: 4 
Best Solution Fitness: 580349 
--------------------------------------------- 
