--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 591439
New Best Solution Fitness: 590480
New Best Solution Fitness: 590235
Generation: 3
New Best Solution Fitness: 584843
New Best Solution Fitness: 584831
New Best Solution Fitness: 584733
New Best Solution Fitness: 584722
Generation: 4
New Best Solution Fitness: 579665
New Best Solution Fitness: 579471
Generation: 5
New Best Solution Fitness: 578878
New Best Solution Fitness: 578864
Generation: 6
Generation: 7
New Best Solution Fitness: 578854
Generation: 8
New Best Solution Fitness: 578365
New Best Solution Fitness: 578172
Generation: 9
New Best Solution Fitness: 578122
Generation: 10
New Best Solution Fitness: 577424
New Best Solution Fitness: 577374
New Best Solution Fitness: 577363
New Best Solution Fitness: 577287
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.53333 
Mean sub-tour choices: 4.33333 
Best Solution Fitness: 577287 
--------------------------------------------- 
