--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 599709
New Best Solution Fitness: 599325
New Best Solution Fitness: 599213
New Best Solution Fitness: 599100
Generation: 3
New Best Solution Fitness: 595555
New Best Solution Fitness: 595438
New Best Solution Fitness: 595398
New Best Solution Fitness: 595342
New Best Solution Fitness: 595298
Generation: 4
New Best Solution Fitness: 593370
New Best Solution Fitness: 593358
New Best Solution Fitness: 593266
New Best Solution Fitness: 593240
Generation: 5
New Best Solution Fitness: 592987
Generation: 6
New Best Solution Fitness: 592734
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 592726
New Best Solution Fitness: 590144
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.17778 
Mean sub-tour choices: 3.86667 
Best Solution Fitness: 590144 
--------------------------------------------- 
