--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 596687
New Best Solution Fitness: 596378
New Best Solution Fitness: 595898
Generation: 3
New Best Solution Fitness: 593693
New Best Solution Fitness: 593676
New Best Solution Fitness: 593540
New Best Solution Fitness: 593268
Generation: 4
New Best Solution Fitness: 590611
New Best Solution Fitness: 590572
New Best Solution Fitness: 590095
Generation: 5
New Best Solution Fitness: 590026
New Best Solution Fitness: 590023
Generation: 6
New Best Solution Fitness: 589839
Generation: 7
New Best Solution Fitness: 587532
Generation: 8
New Best Solution Fitness: 587251
Generation: 9
New Best Solution Fitness: 585345
Generation: 10
New Best Solution Fitness: 585315
New Best Solution Fitness: 583093
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.58889 
Mean sub-tour choices: 3.26667 
Best Solution Fitness: 583093 
--------------------------------------------- 
