--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 592626
New Best Solution Fitness: 592464
New Best Solution Fitness: 592278
New Best Solution Fitness: 592168
New Best Solution Fitness: 591918
Generation: 3
New Best Solution Fitness: 586475
New Best Solution Fitness: 586472
New Best Solution Fitness: 585622
New Best Solution Fitness: 585340
Generation: 4
New Best Solution Fitness: 584056
New Best Solution Fitness: 584053
New Best Solution Fitness: 584035
Generation: 5
New Best Solution Fitness: 584030
New Best Solution Fitness: 584027
Generation: 6
New Best Solution Fitness: 583131
New Best Solution Fitness: 582945
New Best Solution Fitness: 582768
Generation: 7
New Best Solution Fitness: 582742
New Best Solution Fitness: 582739
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 582627
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.95556 
Mean sub-tour choices: 3.7 
Best Solution Fitness: 582627 
--------------------------------------------- 
