--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 588852
New Best Solution Fitness: 588480
Generation: 3
New Best Solution Fitness: 585630
New Best Solution Fitness: 585618
New Best Solution Fitness: 585607
Generation: 4
New Best Solution Fitness: 583536
New Best Solution Fitness: 583464
New Best Solution Fitness: 582744
Generation: 5
New Best Solution Fitness: 582164
New Best Solution Fitness: 582130
Generation: 6
New Best Solution Fitness: 579441
New Best Solution Fitness: 579286
New Best Solution Fitness: 579252
Generation: 7
New Best Solution Fitness: 579022
New Best Solution Fitness: 578882
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 578808
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.76667 
Mean sub-tour choices: 2.27778 
Best Solution Fitness: 578808 
--------------------------------------------- 
