--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 587114
New Best Solution Fitness: 586790
New Best Solution Fitness: 586580
New Best Solution Fitness: 586579
New Best Solution Fitness: 586539
Generation: 3
New Best Solution Fitness: 584771
New Best Solution Fitness: 584757
New Best Solution Fitness: 584313
Generation: 4
New Best Solution Fitness: 582874
New Best Solution Fitness: 582830
Generation: 5
New Best Solution Fitness: 582293
Generation: 6
New Best Solution Fitness: 581712
New Best Solution Fitness: 581706
Generation: 7
New Best Solution Fitness: 581428
New Best Solution Fitness: 581420
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 581312
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.01111 
Mean sub-tour choices: 2.62222 
Best Solution Fitness: 581312 
--------------------------------------------- 
