--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 592339
New Best Solution Fitness: 591230
Generation: 3
New Best Solution Fitness: 582541
New Best Solution Fitness: 582520
New Best Solution Fitness: 582398
Generation: 4
New Best Solution Fitness: 581624
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 581615
New Best Solution Fitness: 581555
Generation: 10
New Best Solution Fitness: 580931
New Best Solution Fitness: 580890
New Best Solution Fitness: 580479
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.4 
Mean sub-tour choices: 4.07778 
Best Solution Fitness: 580479 
--------------------------------------------- 
