--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 594676
New Best Solution Fitness: 594032
New Best Solution Fitness: 593817
Generation: 3
New Best Solution Fitness: 589907
New Best Solution Fitness: 589865
New Best Solution Fitness: 589761
New Best Solution Fitness: 589748
New Best Solution Fitness: 589731
New Best Solution Fitness: 589725
Generation: 4
New Best Solution Fitness: 589339
New Best Solution Fitness: 589300
New Best Solution Fitness: 589182
Generation: 5
New Best Solution Fitness: 587712
Generation: 6
New Best Solution Fitness: 587614
Generation: 7
New Best Solution Fitness: 587576
Generation: 8
New Best Solution Fitness: 586788
New Best Solution Fitness: 586686
New Best Solution Fitness: 586634
Generation: 9
New Best Solution Fitness: 586170
New Best Solution Fitness: 586123
Generation: 10
New Best Solution Fitness: 586085
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.98889 
Mean sub-tour choices: 3.62222 
Best Solution Fitness: 586085 
--------------------------------------------- 
