--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 586466
New Best Solution Fitness: 586370
New Best Solution Fitness: 585935
New Best Solution Fitness: 585874
Generation: 3
New Best Solution Fitness: 582424
New Best Solution Fitness: 582392
New Best Solution Fitness: 582221
Generation: 4
New Best Solution Fitness: 581774
New Best Solution Fitness: 581752
New Best Solution Fitness: 581584
Generation: 5
New Best Solution Fitness: 578199
Generation: 6
New Best Solution Fitness: 578090
New Best Solution Fitness: 578082
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.08889 
Mean sub-tour choices: 3.75556 
Best Solution Fitness: 578082 
--------------------------------------------- 
