--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 596131
New Best Solution Fitness: 595967
New Best Solution Fitness: 595895
New Best Solution Fitness: 595894
New Best Solution Fitness: 595553
New Best Solution Fitness: 595316
New Best Solution Fitness: 594442
Generation: 3
New Best Solution Fitness: 587538
New Best Solution Fitness: 587461
New Best Solution Fitness: 587440
New Best Solution Fitness: 587433
New Best Solution Fitness: 587358
Generation: 4
New Best Solution Fitness: 586135
New Best Solution Fitness: 586112
Generation: 5
New Best Solution Fitness: 583444
Generation: 6
New Best Solution Fitness: 582934
New Best Solution Fitness: 582920
Generation: 7
Generation: 8
New Best Solution Fitness: 582850
Generation: 9
New Best Solution Fitness: 582786
New Best Solution Fitness: 582775
Generation: 10
New Best Solution Fitness: 582486
New Best Solution Fitness: 582474
New Best Solution Fitness: 582461
New Best Solution Fitness: 582427
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.14444 
Mean sub-tour choices: 3.88889 
Best Solution Fitness: 582427 
--------------------------------------------- 
