--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 586133
New Best Solution Fitness: 585539
New Best Solution Fitness: 585374
New Best Solution Fitness: 585277
Generation: 3
New Best Solution Fitness: 582250
New Best Solution Fitness: 581867
Generation: 4
New Best Solution Fitness: 580876
New Best Solution Fitness: 580788
New Best Solution Fitness: 580693
New Best Solution Fitness: 580650
Generation: 5
New Best Solution Fitness: 580494
New Best Solution Fitness: 580441
New Best Solution Fitness: 580411
Generation: 6
New Best Solution Fitness: 580358
Generation: 7
Generation: 8
New Best Solution Fitness: 580336
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.96667 
Mean sub-tour choices: 5.85556 
Best Solution Fitness: 580336 
--------------------------------------------- 
