--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 590597
New Best Solution Fitness: 590475
New Best Solution Fitness: 589910
New Best Solution Fitness: 589623
Generation: 3
New Best Solution Fitness: 587793
New Best Solution Fitness: 587734
New Best Solution Fitness: 587680
New Best Solution Fitness: 587553
New Best Solution Fitness: 585832
Generation: 4
New Best Solution Fitness: 583598
New Best Solution Fitness: 583539
New Best Solution Fitness: 583538
New Best Solution Fitness: 581046
Generation: 5
New Best Solution Fitness: 580916
New Best Solution Fitness: 580856
Generation: 6
New Best Solution Fitness: 580826
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.43333 
Mean sub-tour choices: 5.25556 
Best Solution Fitness: 580826 
--------------------------------------------- 
