--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 589511
New Best Solution Fitness: 589244
New Best Solution Fitness: 588777
New Best Solution Fitness: 588717
Generation: 3
New Best Solution Fitness: 582811
New Best Solution Fitness: 582606
Generation: 4
New Best Solution Fitness: 581839
New Best Solution Fitness: 581096
New Best Solution Fitness: 581026
Generation: 5
New Best Solution Fitness: 580965
New Best Solution Fitness: 580917
Generation: 6
New Best Solution Fitness: 580704
New Best Solution Fitness: 580461
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 580252
New Best Solution Fitness: 580218
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.98889 
Mean sub-tour choices: 3.71111 
Best Solution Fitness: 580218 
--------------------------------------------- 
