--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 593203
New Best Solution Fitness: 592734
New Best Solution Fitness: 591940
Generation: 3
New Best Solution Fitness: 588422
New Best Solution Fitness: 587518
New Best Solution Fitness: 587503
Generation: 4
New Best Solution Fitness: 586729
Generation: 5
New Best Solution Fitness: 586237
New Best Solution Fitness: 586232
New Best Solution Fitness: 586221
Generation: 6
New Best Solution Fitness: 586218
New Best Solution Fitness: 586099
Generation: 7
New Best Solution Fitness: 586096
Generation: 8
New Best Solution Fitness: 585934
Generation: 9
New Best Solution Fitness: 585604
New Best Solution Fitness: 585457
Generation: 10
New Best Solution Fitness: 584401
New Best Solution Fitness: 584376
New Best Solution Fitness: 584222
New Best Solution Fitness: 583986
New Best Solution Fitness: 581082
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 1.82222 
Mean sub-tour choices: 2.31111 
Best Solution Fitness: 581082 
--------------------------------------------- 
