--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 587659
New Best Solution Fitness: 587641
New Best Solution Fitness: 587364
New Best Solution Fitness: 587333
New Best Solution Fitness: 587285
Generation: 3
New Best Solution Fitness: 584636
New Best Solution Fitness: 584631
New Best Solution Fitness: 584606
New Best Solution Fitness: 584601
New Best Solution Fitness: 584338
Generation: 4
New Best Solution Fitness: 584333
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.25556 
Mean sub-tour choices: 2.93333 
Best Solution Fitness: 584333 
--------------------------------------------- 
