--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 588706
New Best Solution Fitness: 588029
New Best Solution Fitness: 587924
New Best Solution Fitness: 587193
Generation: 3
New Best Solution Fitness: 582721
New Best Solution Fitness: 582646
New Best Solution Fitness: 582276
Generation: 4
New Best Solution Fitness: 581431
New Best Solution Fitness: 581356
Generation: 5
New Best Solution Fitness: 580750
Generation: 6
New Best Solution Fitness: 580681
Generation: 7
New Best Solution Fitness: 580512
New Best Solution Fitness: 579906
Generation: 8
New Best Solution Fitness: 579748
Generation: 9
New Best Solution Fitness: 579745
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.64444 
Mean sub-tour choices: 3.32222 
Best Solution Fitness: 579745 
--------------------------------------------- 
