--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 586171
New Best Solution Fitness: 585612
New Best Solution Fitness: 585572
New Best Solution Fitness: 585480
Generation: 3
New Best Solution Fitness: 582202
New Best Solution Fitness: 582051
New Best Solution Fitness: 581846
Generation: 4
New Best Solution Fitness: 581619
New Best Solution Fitness: 581554
Generation: 5
New Best Solution Fitness: 581052
New Best Solution Fitness: 580683
New Best Solution Fitness: 580482
Generation: 6
New Best Solution Fitness: 580478
Generation: 7
New Best Solution Fitness: 580434
Generation: 8
New Best Solution Fitness: 580427
Generation: 9
New Best Solution Fitness: 580410
Generation: 10
New Best Solution Fitness: 580391
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.31111 
Mean sub-tour choices: 5.11111 
Best Solution Fitness: 580391 
--------------------------------------------- 
