--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 592277
New Best Solution Fitness: 591515
New Best Solution Fitness: 591071
New Best Solution Fitness: 591044
New Best Solution Fitness: 591011
Generation: 3
New Best Solution Fitness: 583025
New Best Solution Fitness: 582945
New Best Solution Fitness: 582916
New Best Solution Fitness: 582867
Generation: 4
New Best Solution Fitness: 582813
New Best Solution Fitness: 582795
New Best Solution Fitness: 582746
Generation: 5
New Best Solution Fitness: 582447
New Best Solution Fitness: 582355
Generation: 6
New Best Solution Fitness: 582337
Generation: 7
Generation: 8
New Best Solution Fitness: 579655
New Best Solution Fitness: 579650
New Best Solution Fitness: 579642
Generation: 9
New Best Solution Fitness: 579350
Generation: 10
New Best Solution Fitness: 579240
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.65556 
Mean sub-tour choices: 5.5 
Best Solution Fitness: 579240 
--------------------------------------------- 
