--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 590111
New Best Solution Fitness: 590042
New Best Solution Fitness: 588978
New Best Solution Fitness: 588943
Generation: 3
New Best Solution Fitness: 583560
New Best Solution Fitness: 583540
New Best Solution Fitness: 583466
New Best Solution Fitness: 583448
Generation: 4
New Best Solution Fitness: 582581
New Best Solution Fitness: 582507
New Best Solution Fitness: 582122
Generation: 5
New Best Solution Fitness: 582075
New Best Solution Fitness: 582004
New Best Solution Fitness: 582001
Generation: 6
New Best Solution Fitness: 581921
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 581885
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.23333 
Mean sub-tour choices: 2.92222 
Best Solution Fitness: 581885 
--------------------------------------------- 
