--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 583189
New Best Solution Fitness: 582749
New Best Solution Fitness: 582733
New Best Solution Fitness: 582644
New Best Solution Fitness: 582361
Generation: 3
New Best Solution Fitness: 580714
New Best Solution Fitness: 580631
New Best Solution Fitness: 579864
Generation: 4
New Best Solution Fitness: 579776
New Best Solution Fitness: 579748
New Best Solution Fitness: 579722
New Best Solution Fitness: 579421
Generation: 5
New Best Solution Fitness: 579171
Generation: 6
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 578992
New Best Solution Fitness: 578964
New Best Solution Fitness: 578827
Generation: 10
New Best Solution Fitness: 578403
New Best Solution Fitness: 578170
New Best Solution Fitness: 578115
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.21111 
Mean sub-tour choices: 2.82222 
Best Solution Fitness: 578115 
--------------------------------------------- 
