--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 585854
New Best Solution Fitness: 585706
New Best Solution Fitness: 585691
Generation: 3
New Best Solution Fitness: 583911
New Best Solution Fitness: 583874
New Best Solution Fitness: 583831
Generation: 4
New Best Solution Fitness: 582037
New Best Solution Fitness: 581994
New Best Solution Fitness: 581777
Generation: 5
New Best Solution Fitness: 580035
Generation: 6
New Best Solution Fitness: 580004
Generation: 7
Generation: 8
Generation: 9
New Best Solution Fitness: 579887
Generation: 10
New Best Solution Fitness: 578397
New Best Solution Fitness: 578369
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 3.17778 
Mean sub-tour choices: 3.78889 
Best Solution Fitness: 578369 
--------------------------------------------- 
