--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 588678
New Best Solution Fitness: 588380
New Best Solution Fitness: 588065
New Best Solution Fitness: 588003
New Best Solution Fitness: 587967
New Best Solution Fitness: 587691
Generation: 3
New Best Solution Fitness: 582371
New Best Solution Fitness: 582343
New Best Solution Fitness: 582322
New Best Solution Fitness: 582317
Generation: 4
New Best Solution Fitness: 582240
New Best Solution Fitness: 582212
Generation: 5
New Best Solution Fitness: 581805
Generation: 6
New Best Solution Fitness: 581617
Generation: 7
New Best Solution Fitness: 581590
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.74444 
Mean sub-tour choices: 5.54444 
Best Solution Fitness: 581590 
--------------------------------------------- 
