--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 587957
New Best Solution Fitness: 587711
New Best Solution Fitness: 587632
New Best Solution Fitness: 587596
New Best Solution Fitness: 587564
New Best Solution Fitness: 587534
Generation: 3
New Best Solution Fitness: 582734
New Best Solution Fitness: 582549
Generation: 4
New Best Solution Fitness: 582448
New Best Solution Fitness: 582435
New Best Solution Fitness: 582407
Generation: 5
New Best Solution Fitness: 582394
Generation: 6
New Best Solution Fitness: 582387
Generation: 7
Generation: 8
Generation: 9
Generation: 10
New Best Solution Fitness: 581853
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.71111 
Mean sub-tour choices: 3.36667 
Best Solution Fitness: 581853 
--------------------------------------------- 
