--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 596827
New Best Solution Fitness: 596254
New Best Solution Fitness: 596034
New Best Solution Fitness: 595057
Generation: 3
New Best Solution Fitness: 589025
New Best Solution Fitness: 588991
New Best Solution Fitness: 588968
Generation: 4
New Best Solution Fitness: 586918
Generation: 5
New Best Solution Fitness: 585747
New Best Solution Fitness: 585473
Generation: 6
New Best Solution Fitness: 584154
New Best Solution Fitness: 584111
New Best Solution Fitness: 584036
New Best Solution Fitness: 584029
Generation: 7
New Best Solution Fitness: 583575
Generation: 8
Generation: 9
New Best Solution Fitness: 581317
New Best Solution Fitness: 581267
New Best Solution Fitness: 581186
Generation: 10
New Best Solution Fitness: 580834
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.87778 
Mean sub-tour choices: 3.65556 
Best Solution Fitness: 580834 
--------------------------------------------- 
