--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 596740
New Best Solution Fitness: 596473
New Best Solution Fitness: 596326
New Best Solution Fitness: 596275
Generation: 3
New Best Solution Fitness: 592802
New Best Solution Fitness: 592768
New Best Solution Fitness: 592679
New Best Solution Fitness: 592631
Generation: 4
New Best Solution Fitness: 590389
New Best Solution Fitness: 589968
Generation: 5
Generation: 6
Generation: 7
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.73333 
Mean sub-tour choices: 3.32222 
Best Solution Fitness: 589968 
--------------------------------------------- 
