--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 596001
New Best Solution Fitness: 595401
New Best Solution Fitness: 595362
New Best Solution Fitness: 595328
New Best Solution Fitness: 595229
Generation: 3
New Best Solution Fitness: 593920
New Best Solution Fitness: 593142
Generation: 4
New Best Solution Fitness: 592889
New Best Solution Fitness: 592752
New Best Solution Fitness: 592723
Generation: 5
New Best Solution Fitness: 592697
Generation: 6
Generation: 7
New Best Solution Fitness: 592328
Generation: 8
New Best Solution Fitness: 592229
Generation: 9
New Best Solution Fitness: 591827
New Best Solution Fitness: 591795
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 4.65556 
Mean sub-tour choices: 5.54444 
Best Solution Fitness: 591795 
--------------------------------------------- 
