--------------------------------------------- 
Job start 
Search space: Permutation 
Problem: The Travelling Salesman Problem 
Problem instance: ..\ALL_tsp\rl5915.tsp
Algorithm: Hybrid with Generalized Partition Crossover
Population: 10
Generation: 1
Generation: 2
New Best Solution Fitness: 594437
New Best Solution Fitness: 594006
New Best Solution Fitness: 593850
Generation: 3
New Best Solution Fitness: 585911
New Best Solution Fitness: 585776
New Best Solution Fitness: 585771
Generation: 4
New Best Solution Fitness: 582838
Generation: 5
New Best Solution Fitness: 580937
New Best Solution Fitness: 580891
Generation: 6
New Best Solution Fitness: 580840
Generation: 7
New Best Solution Fitness: 580662
New Best Solution Fitness: 580373
Generation: 8
Generation: 9
Generation: 10
-------------------------
Job Complete 
Iterations: 10
Mean 2-Cost components: 2.51111 
Mean sub-tour choices: 3.11111 
Best Solution Fitness: 580373 
--------------------------------------------- 
